### ISSUE TITLE
Ofrecer registros historicos de tasa de incidencia

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#1]
la cabecera es:
`region, comuna, fecha`

con una columna añadida cada vez que el MINSAL publique un nuevo informe epidemiologico.

**Comment by scornejob** [comment]
dado que la info esta en pdf, el procesamiento depende de la transcripcion a un formato mas consumible

**Comment by ivanMSC** [comment]
No. Es preferible ofrecer datos históricos por comuna del número de casos confirmados. La tasa de incidencia es un número que se recupera en forma precisa con una operación matemática. En cambio, el número de casos confirmados, si bien se puede recuperar a partir de multiplicar la tasa por la población, requiere hacer un redondeo donde se podría perder información.

**Comment by MinCiencia** [comment]
Este es el [data product 18](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto18)
