### ISSUE TITLE
Repo de incremento regional de Confirmados, Recuperados y Fallecidos

### ISSUE THREAD

**Issue by javierconcha** [MinCiencia/Datos-COVID19#100]
Estimados, 
Primero, felicitaciones por este esfuerzo!

He creado un website para el tracking de COVID-19 en Chile que genera datos (csv files) del incremento de Confirmados, Recuperados y Fallecidos por regiones (antes de saber que este repo existía):

[https://github.com/javierconcha/covid-19-Chile](https://github.com/javierconcha/covid-19-Chile)

Los datos son los mismo generados para este repo, pero agrupados de una manera diferente (por serie temporal por region). Lo pongo a disposición, si a alguno le interesa. 

Saludos!

**Comment by MatheusTesseracto** [comment]
Aprovecho este issue para preguntar porque no han subido los datos de incremento de casos por región, tanto de ayer como de hoy?  [frecuencia diaria]

**Comment by MinCiencia** [comment]
Muchas gracias por compartir, buen trabajo.
