### ISSUE TITLE
Producto 37: Muertes 10 de junio igual a 9 de junio

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1002]
Estimados, en el producto 37 subieron datos repetidos para el día 10 de junio. Los datos son idénticos a ayer. Ojalá lo puedan corregir.

Saludos cordiales,

**Comment by dafernandez75** [comment]
Aún sin cambios !!!!

**Comment by dna33** [comment]
Hola, estamos consiguiendo los datos de hoy, espero este actualizado antes de que termine el día.
