### ISSUE TITLE
Falta CanSino en el total de vacunado

### ISSUE THREAD

**Issue by AntoineBraultChile** [MinCiencia/Datos-COVID19#1004]
Hola,

Parece que falta el numero de personas vacunadas con CanSino en el archivo
Datos-COVID19/output/producto76/vacunacion.csv 

Gracias por la ayuda.

**Comment by MinCiencia** [comment]
Así es, estamos trabajando en incorporar vacunación con CanSino, ver issue relacionado: https://github.com/MinCiencia/Datos-COVID19/issues/1000
