### ISSUE TITLE
Producto83 solo presenta registros por Establecimiento y no por Fabricante.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1008]
Hola,
Según se indica el producto 83 debe presentar registros por Fabricante de Vacuna y Establecimiento dónde se aplicó, pero solo presenta data por Establecimiento.

Saludos.

**Comment by dna33** [comment]
Tienes razón, se nos quedó en el tintero. Esperamos subir el desglose por fabricante durante el día.

**Comment by alonsosilvaallende** [comment]
Me parece que está siendo enviado al [Producto 76](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto76).

**Comment by MinCiencia** [comment]
Claro, la informacion existe en ese producto, pero proviene del repo qe ya no mantiene @juancri. Ayer hicimos un avance importante pero todavia no terminamos para generar el desglose por fabricante y dia en el producto83. Apenas este listo avisamos por esta via.

**Comment by dna33** [comment]
Hola, me pueden ayudar a ver si quedó bien?

https://github.com/MinCiencia/Datos-COVID19/commit/c7c2f488976ef5dd68395413483274322ea992a6

Gracias!

**Comment by dafernandez75** [comment]
Hola, 

Al revisar todos los subproductos dentro del producto83 (Establecimiento, 1eraDosis, 2daDosis, ÚnicaDosis), no se puede inferir con ellos el cruce de la data del fabricante (tipo vacuna) por Establecimiento (+de 1800 establecimientos). 

Supongo y desconozco si la idea del producto 83 es poder conocer por Establecimiento las dosis de vacunas por fabricante de manera temporal. Si es así, entonces falta integrar los totales de cada fabricante por cada establecimiento.

Saludos,

**Comment by dna33** [comment]
No, por un lado el total de personas vacunadas por tipo de establecimiento, por otro la información por fabricante. Mi pregunta es, los totales parecen correctos en relación a los demás productos?

**Comment by dna33** [comment]
Ahora pudimos verificar que sí estan correctos los totales @dafernandez75 @alonsosilvaallende

**Comment by paarriagadap** [comment]
Hola! Muchas gracias por su trabajo. Quizás para que lo tengamos claro, habría que poner cuáles productos están contando con soporte para "trasladarse" a esos, si es necesario.

PD: Sólo como formato, puede ser mejor que en el producto 83 aparezca `CanSino` en vez de `Campaña SARS-CoV-2 (CanSino)`, para mantener coherencia con las otras dimensiones de fabricante.

Muchas gracias nuevamente

**Comment by dna33** [comment]
@paarriagadap Vamos a hacer el cambio en Cansino, lo que preguntas se respondió en este issue: https://github.com/MinCiencia/Datos-COVID19/issues/1005

**Comment by dna33** [comment]
https://github.com/MinCiencia/Datos-COVID19/commit/93d25f42c147bc05746aa891a6902f24d882b192

**Comment by alonsosilvaallende** [comment]
Muchas gracias por el trabajo: https://twitter.com/alonsosilva/status/1405687397879328778?s=20
