### ISSUE TITLE
Nuevo producto 88: Vacunacion por fabricante y edad

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#1012]
Link: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto88

https://github.com/MinCiencia/Datos-COVID19/commit/42b382f6d0719a697d6ad68b6ee558c2f32074a5

**Comment by paarriagadap** [comment]
Hola! En la última actualización apareció un fabricante `NULL`, con 0 vacunas. En general no afecta los análisis, me parece, pero aviso por si acaso.
