### ISSUE TITLE
Actualizar población de grupos de edad de niños y adolescentes (P81)

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1018]
Hola, con la ampliación de vacunación a los grupos de edad hasta 12 años se hace necesario actualizar los valores de población por edad y comuna en Chile, que llegan actualmente hasta los 15 en el archivo adicional presentado en el producto 81. De otra manera no se puede graficar el [avance de cada grupo etario](https://public.tableau.com/views/Coronavirus_15857831577770/VacunacinenChile?%3Aembed=y&%3Aembed=y&%3AshowVizHome=no&%3AshowVizHome=n&%3Adisplay_count=y&%3Adisplay_static_image=y&%3Alanguage=es&%3AapiID=host0#navType=0&navSrc=Parse&2):
![image](https://user-images.githubusercontent.com/63430031/123295849-1d0dae80-d4e4-11eb-9cec-ea506573d8f0.png)
![image](https://user-images.githubusercontent.com/63430031/123295919-2bf46100-d4e4-11eb-851b-524ac45b94a0.png)
![image](https://user-images.githubusercontent.com/63430031/123296077-534b2e00-d4e4-11eb-9d0c-458e8a841863.png)

Quizás para ganar tiempo se podría dejar la población de todas las edades, partiendo desde los 0 años (x meses)
Saludos! Muchas gracias.

**Comment by MinCiencia** [comment]
Está actualizado ahora, por favor validar si quedó bien.

**Comment by paarriagadap** [comment]
Hola, los datos se ven actualizados y correctos, según comparo con lo que sale en el sitio de DEIS.

![image](https://user-images.githubusercontent.com/63430031/123444517-f82d4000-d5a4-11eb-9712-872d3b7bd38f.png)
![image](https://user-images.githubusercontent.com/63430031/123444559-067b5c00-d5a5-11eb-8d9e-8f151646b5ec.png)

![image](https://user-images.githubusercontent.com/63430031/123443254-bd76d800-d5a3-11eb-947c-201d1d45ce45.png)
![image](https://user-images.githubusercontent.com/63430031/123443299-c8316d00-d5a3-11eb-9067-1ae543eabcfc.png)
![image](https://user-images.githubusercontent.com/63430031/123443358-d2ec0200-d5a3-11eb-89a9-ad2285eb3f73.png)

Muchas gracias!

**Comment by MinCiencia** [comment]
A ustedes, saludos.
