### ISSUE TITLE
¿Por que en los datos paciente hospitalizados solo entregan información de menores de 39 años? pueden ser mas específicos en el grupo etarios de los pacientes

### ISSUE THREAD

**Issue by Franciscobarack** [MinCiencia/Datos-COVID19#1019]

**Comment by MinCiencia** [comment]
Hola, revisa por favor estos productos:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto22
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto9

**Comment by Franciscobarack** [comment]
si, solo muestra las cifras acumuladas, solo esta el de pacienes hospitalizados hay desglose de paciente por cama critica, uci uti o solo hospitalización.
