### ISSUE TITLE
Necesito ayuda en encontrar toda la información pacientes PIMS, casos diarios, mortalidad, ingresos UCI UCI Etc

### ISSUE THREAD

**Issue by Franciscobarack** [MinCiencia/Datos-COVID19#1021]

**Comment by MinCiencia** [comment]
No existe esa información entre la publicada por el Ministerio de Salud de Chile, por favor ver estos issues para saber como solicitarla por transparencia y lograr se publique en este github: https://github.com/MinCiencia/Datos-COVID19/issues/953
