### ISSUE TITLE
Vacunacion

### ISSUE THREAD

**Issue by JorgeRPL** [MinCiencia/Datos-COVID19#1023]
Estimados, los datos presentados en directorio: **input/Vacunacion/** no se tienen los datos para el dia 29 y 30 de junio.

- En commit: 22703a01eb9b274bb24ee38b3f16b83c77dbb206 (data del 29/06) se encuentran los datos para el dia 29/06
- En commit: 352472f72457077c392f92b930a59e0ba10a0b4f, (data del 30/06) pasaron 2 cosas se eliminaron los datos para el dia 29/06 y tampoco hay registros para el día 30/06.

por favor revisar esta actualización.

De antemano Gracias!!!

**Comment by MinCiencia** [comment]
Gracias, corregido al 29, sin embargo el problema persiste con los datos del 30, DEIS trabaja en solucionarlo.

**Comment by MinCiencia** [comment]
Corregido 62d3bd4c0015231041ba5572d00ccf7f99055154
