### ISSUE TITLE
consulta casos confirmados Producto 37_01-julio-2021

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1024]
Hola, 
al ver el producto 37, llama la atención que presente para las mismas fechas de ayer registros de fallecidos confirmados, debiendo ser +1 registro con respecto al día anterior. 
Lo anterior, es producto de que efectivamente con los registros que hoy se manejan no hay casos de fallecidos confirmados para el 28-junio-2021 o por alguna razón el Deis lo omitió?.
![Captura de pantalla 2021-07-01 144507](https://user-images.githubusercontent.com/69001461/124175291-709b7180-da7b-11eb-88a7-7753118ddf2e.png)

**Comment by MinCiencia** [comment]
Hola, no se entiende lo que te llama la atención, puedes intentar nuevamente o aportar más antecedentes, por favor? Gracias.

**Comment by dafernandez75** [comment]
Lo normal es que cada vez que publican casos confirmados de fallecidos con respecto al día anterior, siempre se aumenta en +1 día en relación a la fecha del día anterior, ver tabla adjunta. 
Ha sido una constante tener 3 días de atraso de registros (reporte 30-junio-2021; registros hasta 27-junio-2021), ahora serían 4 días (reporte 01-julio-2021 ; registro 27-junio-2021), debiendo ser con registros al 28-junio-2021. Que extraño que no lo veas.
Espero ser más claro ahora. Saludos

![foto2](https://user-images.githubusercontent.com/69001461/124179005-2f599080-da80-11eb-9314-df69c23440a3.png)

**Comment by MinCiencia** [comment]
Hola, queda claro. Esto ha ocurrido en el pasado a raíz de feriados, que al parecer es nuevamente el caso. Veamos como evoluciona con los días y si hay algo que preguntar al DEIS, lo haremos. Gracias por el nuevo intento, se entiende mucho mejor.

**Comment by dafernandez75** [comment]
Ok, gracias ustedes por la labor!!!, esperamos todos que lleguen luego los días en que sea habitual no tener registros de fallecidos por varios días, y que no hayan más u071 y u072. A seguir cuidándose !!!. Saludos
