### ISSUE TITLE
Error en input/ReporteDiario/CasosConfirmadosTotales.csv

### ISSUE THREAD

**Issue by benja-opazo** [MinCiencia/Datos-COVID19#1025]
Las filas 424, 425  y 426 están repetidas de las filas 420, 421 y 422

![image](https://user-images.githubusercontent.com/40286841/124194686-07c1f280-da97-11eb-8c28-9712039186d3.png)

**Comment by MinCiencia** [comment]
Cierto, corregiremos en la actualización de hoy.

**Comment by MinCiencia** [comment]
corregido por @cjag20: https://github.com/MinCiencia/Datos-COVID19/commit/4980855d0dab1f5d78c5d58d0c11d07bdfc7d8b5
