### ISSUE TITLE
Data meteorológica

### ISSUE THREAD

**Issue by nro17** [MinCiencia/Datos-COVID19#1029]
Hola, quisiera consultar si tienen información disponible similar a la que aparece para el "Data Product 43 - Datos de calidad del aire por hora", pero con datos meteorológicos (velocidad del viento, dirección del viento, temperatura, humedad relativa, presión atmosférica, radiación solar, etc) para las estaciones del SINCA a nivel nacional?

**Comment by MinCiencia** [comment]
Esas estaciones son de la DMC, o no?

**Comment by nro17** [comment]
No, me refiero a que muchas de las estaciones del SINCA además de monitorear variables de calidad del aire monitorean variables meteorológicas. Ejemplo estación Parque O'Higgins en la RM además de monitorear calidad del aire mide velocidad del viento, dirección del viento, temperatura y humedad relativa: 

https://sinca.mma.gob.cl/index.php/estacion/index/id/273

Así como esta muchas otras estaciones del SINCA miden meteorología por lo que quisiera saber si es posible contar con esta información en línea como aparece para el Data Product 43, gracias!

**Comment by dna33** [comment]
Hola, se vienen novedades respecto de esto, en le contexto del observatorio del cambio climático que estamos prontos a lanzar en enero, ¡atenti!

https://minciencia.gob.cl/occ/

**Comment by nro17** [comment]
Hola @dna33 sabe si hay alguna novedad respecto a esto? Existe algún repositorio del cual se pueda conectar a la data meteorológica de estaciones del SINCA u otra web? Revisé el link que enviaste y aparece la misma información que en diciembre.
Gracias!

**Comment by IgnacioAcunaF** [comment]
Hola @nro17 
Adjunto repositorio afín con información climática: https://github.com/MinCiencia/Datos-CambioClimatico

Pasó el sitio web también:
https://occ.minciencia.gob.cl/

Saludos

**Comment by nro17** [comment]
@IgnacioAcunaF muchas gracias!!
Una consulta, ¿sabes con qué frecuencia se van actualizando los datos?

**Comment by IgnacioAcunaF** [comment]
Si, el repo se actualiza una vez al día (sin embargo dependiendo del producto, algunos se actualizan cada una hora en el sitio [web](https://occ.minciencia.gob.cl/), dependiendo de la disponibilidad del dato).
La mayoría se actualiza una vez al día

**Comment by nro17** [comment]
Perfecto muchas gracias por todo.
