### ISSUE TITLE
Tercera dosis

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#1031]
[Este artículo](https://www.latercera.com/la-tercera-pm/noticia/terceras-dosis-10-pacientes-inmunodeprimidos-han-sido-autorizados-por-el-minsal-para-recibir-refuerzo-contra-el-covid/227QPVPHOJCB7BF76BE6OUZJHY/) de La Tercera informa que al menos 10 personas han sido inmunizadas con una tercera dosis ya sea por ser pacientes inmunodeprimidos o por ser presidentes del directorio de una clínica.

¿Es posible agregar esta información a algún producto? Gracias.

**Comment by AntoineBraultChile** [comment]
Me gustaría reiterar la petición. ¿Es posible tener los datos de la dosis de refuerzo ? Gracias.

**Comment by MinCiencia** [comment]
Hola, ver https://github.com/MinCiencia/Datos-COVID19/issues/1052
