### ISSUE TITLE
Falta actualización Producto 37 (Fallecidos)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1035]
Hola,

Según lo indicado por @min_ciencia_IA (twitter) estaría actualizado para hoy el Producto 37, pero al revisar este no refleja el actualizado para hoy.   

![Captura de pantalla 2021-07-14 192646](https://user-images.githubusercontent.com/69001461/125705356-be5e1a71-91ce-48f6-ac4b-d1a425472acd.png)

**Comment by MinCiencia** [comment]
Cierto, acabamos de actualizarlo.

13255f6a445be5e4587a67c933a41d88b4ffde52

**Comment by dafernandez75** [comment]
Ahora Sí, muchas gracias!!. =)
