### ISSUE TITLE
Actualización de fases del plan Paso a Paso

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#1037]
Actualmente, el [producto 74](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto74) tiene un desfase en la publicación de datos. Por ejemplo, hoy (19 de julio), toda la región metropolitana entra a fase 3, mientras que el producto 74 sólo muestra datos hasta el 15 de julio ([último commit](https://github.com/MinCiencia/Datos-COVID19/tree/370d7ff5389745da7686cc9f610b6319e6f7cc6a/output/producto74)).

Para [puedoir.cl](https://puedoir.cl) utilizamos este producto, pero cuando existen desactualizaciones (como hoy), tenemos que hacer los cambios a mano.

Algunas preguntas y comentarios:

- ¿Fue este un problema puntual con este producto o es normal que esté desactualizado?
- En caso de que sea normal, ¿podemos proveer un producto alternativo que incluya futuros cambios anunciados por el MINSAL?

Actualmente, tenemos las comunas y fases en [este archivo](https://github.com/juancri/pasoapaso/blob/main/src/data.ts#L9), pero tal vez lo mejor sería contribuir un producto con el mismo formato que ya tiene el producto 74 (o, a lo menos, el archivo [paso_a_paso.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto74/paso_a_paso.csv) que es el formato que usamos internamente para sincronizar). ¿Sería útil para alguien más?.

Gracias!

**Comment by dna33** [comment]
Hola, desde Minsal nos indican que: Normalmente lo subimos entre el martes en la tarde y el miércoles en la mañana, o entre los sábados y los domingos. 

Esto implica que habitualmente miércoles y domingos se debería tener la info nueva arriba en este github. Ayer pasó que el Ministro Paris adelantó el balance diario, y no alcanzó a entrar la info del plan paso a paso en los datos. La info hasta el hoy lunes (que no subimos ayer) la subiremos ahora en minutos.

**Comment by juancri** [comment]
Es probable que para el sitio web, querramos agregar una funcionalidad apenas se hacen los anuncios para que los usuarios puedan planificar viajes a futuro, cuando los anuncios ya se hayan implementado.

Por esto, creo que vamos a tener un archivo paralelo al del producto 74. Podríamos comenzar a publicarlo en el repo [https://github.com/juancri/pasoapaso](juancri/pasoapaso) y después ustedes los pueden sincronizar a este repo. ¿Puede ser?. Como decía antes, sería un solo archivo basado en [paso_a_paso.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto74/paso_a_paso.csv). Me avisan si sirve o si prefieren otro formato.

**Comment by MinCiencia** [comment]
Perfecto
*______*
*Demián Arancibia*
Ministerio de Ciencia, Tecnología, Conocimiento e Innovación
Gobierno de Chile

**Comment by juancri** [comment]
Finalmente, decidimos modificar nuestro propio archivo en formato JSON (técnicamente, TypeScript) y es mucho trabajo hacer el backport hacia el formato CSV, pero si alguien quiere intentarlo, los datos están aquí:

https://github.com/juancri/pasoapaso/blob/main/src/data.ts

El archivo actual no tiene cambios futuros ya que los últimos anunciados acaban de entrar en vigencia hoy (miércoles), pero si alguien se anima a hacer el backport, puede ver un ejemplo aquí:

https://github.com/juancri/pasoapaso/blob/bf9f4bd3c5cee1f78ef9eac20a1799341c54b398/src/data.ts#L138-L142
