### ISSUE TITLE
Error en Producto 74, plan Paso a Paso

### ISSUE THREAD

**Issue by villaseca** [MinCiencia/Datos-COVID19#1039]
Estimados,

Tenemos automatizada una visualización comunal en la que vemos en que etapa está cada comuna, pero con este cambio llevamos un par de semanas con la automatización rota.

Quería consultar si lo que muestro en la foto adjunta es un error o si quedará permanentemente así (para ver si adaptamos nuestro código):

![image](https://user-images.githubusercontent.com/3867311/126573954-5ff80ebd-b124-43b4-9382-46020cec617c.png)

Saludos!

**Comment by MinCiencia** [comment]
Hola, hemos corregido. En la actualización de hoy no aparecerán.
