### ISSUE TITLE
Falta actualización Producto 37 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1041]
Hola, 
Según lo indicado en Twitter debería estar actualizado el Producto 37.  Saludos
![Captura de pantalla 2021-07-23 133632](https://user-images.githubusercontent.com/69001461/126820372-21d0a3bc-446f-4389-b8ba-d6713ca0f77b.png)

**Comment by weichafan** [comment]
Hola, se actualizará hoy el producto 37?

**Comment by dafernandez75** [comment]
Lo actualizaron junto con el de hoy sábado 24-julio-2021. 
A qué se debe que no hubo actualización durante todo el día de ayer viernes 20-julio-2021.

**Comment by dafernandez75** [comment]
Por el lado de los U072 fallecidos sospechosos junto a los U071 (Confirmados), acaban de actualizar desde DatosAbiertos  (15hrs., 24-julio-2021) los registros correspondientes. https://deis.minsal.cl/#datosabiertos

**Comment by dafernandez75** [comment]
ok, ya actualizado U071+U072. gracias!!!
