### ISSUE TITLE
Falta actualización Producto 37

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1044]
Hola, 
según lo publicado en twitter por 'Robot de Datos Abiertos Ministerio de Ciencia' Producto 37 debe estar actualizado, cosa que no es así. Saludos
![Captura de pantalla 2021-07-27 170732](https://user-images.githubusercontent.com/69001461/127227809-c6303810-d14b-4153-a116-0205272dcb88.png)

**Comment by dafernandez75** [comment]
Por qué razón no están respondiendo los issues?

**Comment by dna33** [comment]
hola, debería actualizarse junto con el balance de hoy, estamos en terreno en tránsito por el desierto y lamentablemente se rompió una rutina automática que pudimos corregir hoy.

**Comment by dafernandez75** [comment]
Ok gracias por la información.

**Comment by dafernandez75** [comment]
Les comento que la actualización de hoy 28-07-2021 está ok
![Captura de pantalla 2021-07-28 121753](https://user-images.githubusercontent.com/69001461/127359683-4b3c82d0-39a2-4db3-be9f-209731ae0dd9.png)
, no obstante quedó ausente la serie de ayer martes 27-07-2021.
