### ISSUE TITLE
Producto 39

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1047]
Estimados, 

En la última actualización del producto 39 apareció un caso confirmado con fecha de notificación el 8 de enero de 2020. 
Quisiera confirmar que ese dato es correcto o hay algún error en el producto.  

Saludos cordiales, 
![confirmado-1-8](https://user-images.githubusercontent.com/77077102/127566908-c80326fb-ae72-4115-8de9-983d5d054d38.png)
#

**Comment by dna33** [comment]
Hola  @weichafan confirmamos con el equipo de Epidemiología del Minsal que el caso no es real, corregirán en el próximo informe. Muchas gracias por reportar.

**Comment by weichafan** [comment]
Gracias
