### ISSUE TITLE
Datos PCR positivos a la variante Delta

### ISSUE THREAD

**Issue by AntoineBraultChile** [MinCiencia/Datos-COVID19#1049]
Hola,

Minsal informó que se utiliza PCR que permiten de detectar la variante Delta.
https://www.latercera.com/nacional/noticia/minsal-informa-que-fueron-adquiridos-test-pcr-que-permiten-detectar-la-presencia-de-variante-delta-al-momento-de-ser-aplicados/7QDVX42JLZARLFMT7A7BRHTBUU/

Sería muy interesante de tener estos datos para seguir la evolución de la variante
Delta en Chile.

Sabe si se puede obtener ?

Muchas gracias.

**Comment by xavierutox** [comment]
Hace poco se publicó el informe "Informe epidemiológico variantes SARS-CoV-2" con datos hasta el 8 de agosto.
Seria muy bueno tener acceso a los datos utilizados para realizar ese informe o es su defecto utilizar los datos de ese informe en la realización de un nuevo producto con el avance por variantes

**Comment by alfredosvaldo** [comment]
¿Alguna novedad al respecto?. Lo unico que encuentro son los reportados por [OurWorldinData ](https://ourworldindata.org/grapher/covid-variants-bar?stackMode=absolute&country=~CHL) que tienen un desfase
