### ISSUE TITLE
Actualización productos DEIS

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1050]
Hola, el fin de semana pasado no se actualizaron los productos asociados a defunciones confirmadas y sospechosas provenientes de DEIS. Yo al menos uso el 50 y el 84. Creo que también el 37 usa esta información.

Saludos!

**Comment by dna33** [comment]
Es cierto, se corregirá en el balance diario de hoy, durante la próxima hora. Gracias por reportar.

**Comment by paarriagadap** [comment]
Hola, esto no se ha actualizado, creo que ayer se modificó el input no más

**Comment by MinCiencia** [comment]
Tienes razón, lo actualizamos en este commit: https://github.com/MinCiencia/Datos-COVID19/commit/950b948b5c3cbec0b2627acbdfa2f00a9afc848d
