### ISSUE TITLE
Consulta por producto 19 

### ISSUE THREAD

**Issue by fundmetrica** [MinCiencia/Datos-COVID19#1055]
Hola, buen día. el producto 19 aún no se actualiza. Cuando se realizará?

<img width="1319" alt="imagen" src="https://user-images.githubusercontent.com/71306326/128707985-d3dca0a8-df65-40b2-9f6a-99c6372ff80f.png">

Gracias

**Comment by MinCiencia** [comment]
Hola, actualizado hace algunos minutos.
