### ISSUE TITLE
Falta actualización de Producto 37

### ISSUE THREAD

**Issue by jccarvajal** [MinCiencia/Datos-COVID19#1059]
Valores para los últimos días no coinciden con los publicados por DEIS.

**Comment by dafernandez75** [comment]
Hola, también me llamó la atención, al revisar hoy la serie de ayer completa con respecto a la de hoy publicada, se ven en la mayoría de los días, aumentos (+1) de U071 desde el 11 Mayo 2020 en varios días.
Los totales al menos cuadran de U071 36.107, pero si hicieron ajustes desde el 11 mayo 2020.

**Comment by MinCiencia** [comment]
Hola, es posible elaborar un poco más en las diferencias? Nosotros vemos que están los mismos valores que los que publica DEIS diariamente (de hecho este repo se sincroniza con sus bases de datos 1 vez al día)

**Comment by dafernandez75** [comment]
Hola,
Se agradece la publicación de los Sospechosos (U072) en el día de hoy, lo que permite aclarar en parte lo anterior. 
Con ello se puede justificar y confirmar (al menos) que para 13 días con aumento +1 en los U071 desde el 11/05/2021 provienen de los U072. , ya que disminuyen estos (U072) en las mismas fechas . Ver tabla

![diferencias](https://user-images.githubusercontent.com/69001461/129456100-9f854346-cf70-4d4b-950f-28b4ac1e0ee8.png)

**Comment by jccarvajal** [comment]
Gracias
