### ISSUE TITLE
producto45 vs cifras minsal

### ISSUE THREAD

**Issue by JorgeJimenezT** [MinCiencia/Datos-COVID19#1061]
Hola estimados,

Quería consultarles a que se debe la diferencia entre el archivo "CasosConfirmadosPorComuna.csv" del producto45 actualizado al día 10/08, el cual tiene un total de 1.604.858 de casos confirmados a la semana epidemiológica N° 31, vs 1.624.823 que se publicó en el Minsal también el 10/08 (https://www.minsal.cl/covid-19-se-reportan-514-casos-nuevos-y-30-881-examenes/)

Gracias y saludos,
Jorge

**Comment by MinCiencia** [comment]
Hola Jorge, hemos abordado esta duda en varios intercambios anteriores, en resumen porque el informe epidemiológico, que entrega información a nivel comunal, proviene del resultado de la investigación epidemiologica mientras el balance diario es una foto "al dia". Te citamos los siguientes issues con detalles:

-https://github.com/MinCiencia/Datos-COVID19/issues/1015
-https://github.com/MinCiencia/Datos-COVID19/issues/938

Porfa cuéntanos si es que aún tienes preguntas.
