### ISSUE TITLE
Agradecimiento y sugerencia en productos 89 & 90 (casos según estado de vacunación)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1064]
¡Muy buen trabajo poniendo a disposición los datos de casos según estado de vacunación!

Un comentario / sugerencia:

1) En producto 89 se incluyen los datos de población total y casos para cada estado de vacunación) - desagregado por tramo de edad -  para la semana 31 (asumo que se irá incrementando la semana a futuro)

2) En producto 90 se incluyen los datos de casos para cada estado de vacunación para todas las semanas de 2021, pero no se incluye la población total para cada estado de vacunación

Para hacer una correcta interpretación de los datos es importante conocer la población total en cada estado de vacunación en el tiempo.  Esto permite calcular la incidencia y comparar adecuadamente la evolución de la protección de las vacunas.

Sugiero incluir en producto 90 el total de población en cada estado de vacuna para cada semana 
Sugiero extender los datos en producto 89 para todas las semanas de 2021 

Las autoridades de salud destacaron - correctamente - que para una correcta interpretación es importante considerar que en la medida que aumenta la cobertura, aumentará el porcentaje de casos vacunados.  Ojalá puedan agregar el dato de población total según estado de vacunación para hacer una mejor interpretación de los datos.

![image](https://user-images.githubusercontent.com/68602/129352343-d8e85b00-a055-48f8-9a21-0d8c1df4756d.png)

Gracias nuevamente
@elaval

**Comment by dna33** [comment]
Hola @elaval, se puede completar el dato usando lo siguiente:

hay que agrupar este producto https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion.csv, utilizando este que define las semanas epi: https://github.com/MinCiencia/Datos-COVID19/blob/master/input/InformeEpidemiologico/SemanasEpidemiologicas.csv

¿Tiene sentido que cree un csv complementario que haga esta agrupación de vacunados con 1dosis, 2dosis, única, refuerzo?

**Comment by elaval** [comment]
Gracias por la respuesta @dna33 

Había pensado en agregar utilizar los datos de los productos de vacunación para calcular los totales pero creo que hay 2 temas con esto:

1) Los datos de desenlaces (ej en producto 90) se entregan por semana y los datos de vacunación son diarios.
Si queremos ser precisos, especialmente cuando las cifras con bajas, puede que una persona que haya entrado a UCI o fallecido, lo haya hecho pocos días antes de cambiar de estado en esa semana (ej fallece un Lunes y el Viernes cumplía su esquema completo de vacunación).  Si en una semana son pocos casos (ej 4 fallecidos con esquema completo), esto puede cambiar la interpretación de los datos.  
Lo ideal sería tener los datos consolidados tal como los procesa el Departamento de Epidemiología para no tener diferencias en los agregados.

2) Si bien muchos podemos hacer el cruce de las tablas sin mayor problema (e incluso tener código que lo haga en forma automatizada), para algunas personas se les puede hacer más complejo hacer el cruce y sería más práctico tenerlo consolidado en el mismo producto. 
También sería bueno entregar las cifras para el "esquema completo" para evitar versiones distintas si las personas calculan la cifra usando distintas fechas para calcular los "14 días desde la última dósis o dósis única" (ej algunos pueden agregar 13 y otros 14 días)

Saludos

**Comment by alonsosilvaallende** [comment]
Personalmente, no logré replicar los valores que aparecen para la semana 31 (considerando el total de vacunados con dos dosis desde 14 días antes + total de vacunados con dosis única desde 28 días antes), así que pienso que sería útil. Quizás no es necesario agregar otro csv, sino simplemente agregar las columnas población con una dosis, pob. dos dosis, pob. dos dosis completas, pob. única dosis, pob. única dosis completa.

**Comment by dna33** [comment]
Muy buenos comentarios y aportes. Vamos a encontrar una solución en las próximas horas, idealmente previo a la próxima publicación por parte de Minsal (próximo jueves).

**Comment by MinCiencia** [comment]
Hola @elaval, @alonsosilvaallende, @xavierutox, @AntoineBraultChile. Agregamos esta mañana los totales con pauta completa, una dosis, dos dosis.

Totales con pauta completa: https://github.com/MinCiencia/Datos-COVID19/commit/0462414f5b61a4dee428837cb373ec4c5e8f3214

Totales con una dosis y refuerzo: https://github.com/MinCiencia/Datos-COVID19/commit/675a9157dc8ac253444fc595bcd80d5ca211c572

**Comment by AntoineBraultChile** [comment]
Muchas gracias. Seria super tambien de tener los datos de las dosis de refuerzo en el producto 89 (por edad).
Gracias.

**Comment by paarriagadap** [comment]
Hola, será muy útil esta información, muchas gracias. Es posible incluir también al menos los totales sin vacunar? Creo que sólo así se puede hacer la comparación necesaria de incidencia. Lo ideal también sería ir más allá y agregar la población correspondiente a cada categoría señalada en las variables (dos dosis sin 14 días, dos dosis completa, dosis única, dosis única completa) además de los sin vacunarse.

Gracias
