### ISSUE TITLE
Consulta sobre consistencia producto 90 y producto 5

### ISSUE THREAD

**Issue by xavierutox** [MinCiencia/Datos-COVID19#1066]
Hola,

Analizando el producto 90 para la semana epidemiológica 31, me encontré con algo que me causa un poco de confusión y no sé cómo interpretar.

Para la semana epidemiológica 31 se notifican 1 fallecido sin vacunas y 5 fallecidos con el esquema de dos dosis completo. Lo cual es muy inferior al número de fallecidos reportados diarios en el producto 5 para esa semana.

¿A qué se debe esta diferencia?

Saludos

**Comment by elaval** [comment]
Lo que he podido entender es que el producto 90 comunica, por ejemplo, la cantidad de fallecidos que tuvo inicio de síntomas en la semana correspondiente.

En la semana 32, por ejemplo, son sólo 3 fallecidos.  Esto es porque es porque muchas personas que iniciaron síntomas en la semana 32 todavía no enferman gravemente y no han fallecido.   En semanas futuras se actualizarán los datos para la semana 31 y aumentará la cifra de fallecidos.

Los casos que se reportan en en producto 5 son aquellos fallecidos "reportados", por ejemplo, en la semana 32.  Estos en realidad son fallecimientos que ocurrieron en días - o semanas  previas.  Y corresponden a personas que iniciaron síntomas mucho más atrás en el tiempo. 

Esa es mi interpretación para la diferencia en las cifras de ambos productos.

Esta es mi visión como usuario, no soy parte del equipo responsable de estos datos y puede que me equivoque.

Saludos
