### ISSUE TITLE
Casos nuevos por tipo de test

### ISSUE THREAD

**Issue by Sergio-P** [MinCiencia/Datos-COVID19#1067]
Hola, quería consultar si existe algún producto que de cuenta de los casos nuevos separados por tipo de test PCR o Antigenos. En el sitio web de cifras oficiales (https://www.gob.cl/coronavirus/cifrasoficiales/) se muestra este dato justo abajo de los casos nuevos, pero no he encontrado el producto que de cuenta de esto en el github.

**Comment by dna33** [comment]
Hola,

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto7
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto87

**Comment by Sergio-P** [comment]
Gracias por la respuesta, vi que el valor que busco está en el producto 5 a nivel nacional, ahora mi pregunta es si existe este a nivel regional?

**Comment by MinCiencia** [comment]
Vio el 7 y el 87?
*______*
*Demián Arancibia*
Ministerio de Ciencia, Tecnología, Conocimiento e Innovación
Gobierno de Chile

**Comment by Sergio-P** [comment]
Si los vi, el 7 tiene la cantidad de examenes PCR diarios por región que se tomaron y el 87 la cantidad de Antigenos. Pero esto no es la información que estoy preguntando, quiero saber de la cantidad de casos nuevos diarios cuántos de estos fueron confirmados por PCR y cuántos por Ag. Este dato tal como lo dije antres está en el producto 5 pero sólo a nivel nacional.

Para dar un ejemplo, ayer 18-08-2021 en la región metropolitana se anunciaron 257 casos nuevos, es posible saber de estos 257 cuántos fueron confirmados por PCR y cuantos por test de Ag? Por ejemplo 200 fueron por PCR y 57 por Ag?

**Comment by MinCiencia** [comment]
Ajá, eso sería acá:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto3

en los archivos "totales por región"

**Comment by Sergio-P** [comment]
Muchas gracias, exactamente eso era lo que buscaba
