### ISSUE TITLE
Vacunación por comuna, edad y fecha

### ISSUE THREAD

**Issue by mlcastro1** [MinCiencia/Datos-COVID19#1068]
Hola!
Me interesa tener los datos de número de vacunados por fecha, comuna y edad. Para esto estaba utilizando el historial del Producto 81, descargando los datos por fecha y así con la diferencia obtener los vacunados por día.
Sin embargo, para varios casos estoy obteniendo números de vacunados negativos, lo cual no hace sentido.
¿Alguna recomendación?

**Comment by mlcastro1** [comment]
Pregunta relacionada: están disponibles los datos de vacunación (primera dosis) por comuna y edad (Producto 81) antes del 28 de Febrero?

**Comment by dna33** [comment]
por qué te resultan números negativos?

**Comment by mlcastro1** [comment]
Por ejemplo:
En la última versión actualizada el 4 de Marzo, para la comuna de Santa María (región de Valparaíso) y grupo de 65 años, hay 138 personas vacunadas. Luego, en la última versión actualizada el 5 de Marzo, para la comuna de Santa María y grupo de 65 años, hay 129 personas vacunadas.
Por lo tanto, al calcular las personas que se hubiesen vacunado el 5 de Marzo tomando la diferencia entre ambos datos, obtengo que hubo -9 vacunados.

**Comment by dna33** [comment]
Entiendo, eso es habitual en las invetigaciones que se desarrollan por parte de Minsal, ocurre que se rectifican domicilios por ejemplo, por diversas razones.

**Comment by mlcastro1** [comment]
Ok, gracias! 
Y sobre los datos previos al 28/02/2021, están disponibles?

**Comment by dna33** [comment]
no con este desglose, lamentablemente
