### ISSUE TITLE
En el producto 15 no está actualizado el archivo terminado en std

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1069]
Hola.
Es posible actualizar en el producto 15 el archivo de casos por semana epidemiologica de inicio de síntomas del año 2021 terminando en std?
Saludos,

**Comment by dna33** [comment]
Hola,

Tuvimos que particionarlo, porque excedía el límite de 100mb de la plataforma.

https://github.com/MinCiencia/Datos-COVID19/commit/76e6adbe37aa00d9bf249a681b5435fee6439f20

**Comment by felipeelorrieta** [comment]
Gracias!
Saludos
