### ISSUE TITLE
Producto 76: Dosis de refuerzo en fabricante.csv

### ISSUE THREAD

**Issue by lucasrodes** [MinCiencia/Datos-COVID19#1070]
Buenas,
Me preguntaba cómo se reportan las dosis de refuerzo en el fichero [fabricante.csv](https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto76/fabricante.csv).

He observado que en [vacunacion.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion.csv) éstas se reportan con el valor "Refuerzo" en el campo `Dosis`.

Gracias!

**Comment by lucasrodes** [comment]
Creo entender que el producto 76 se importa del repo de @juancri. La alternativa sería el [producto 83](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto83) entiendo.

xref #1005

**Comment by dna33** [comment]
ESO! Iba a escribirte justamente lo mismo.
