### ISSUE TITLE
Stock de vacunas

### ISSUE THREAD

**Issue by loqueelvientoajuarez** [MinCiencia/Datos-COVID19#1071]
Usando los datos de proyección de población INE, uno puede obtener el % de vacunados, creo que sería bastante útil. (Lo hice en https://github.com/loqueelvientoajuarez/campana-vacunacion-covid-19, lo pueden copiar/adaptar si quieren).

**Comment by MinCiencia** [comment]
Buen trabajo,

Acá también lo teníamos implementando:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto81

**Comment by loqueelvientoajuarez** [comment]
> Buen trabajo,
> 
> Acá también lo teníamos implementando:
> 
> https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto81

Bacán, por comuna, por eso no lo vi, buscaba datos a nivel país :-)

Otra duda, en ninguna parte vi una base de datos sobre el stock de vacunas disponible, ¿me equivoco? Hice un listado de las importaciones (https://github.com/loqueelvientoajuarez/campana-vacunacion-covid-19/blob/main/output/contrib/vacunas_importadas_fabricante_fecha.csv) lo que podría servir de base, pero no hay una fuente oficial para dar fe de esos datos.

**Comment by MinCiencia** [comment]
buen punto, podríamo pedirle a alguien de minsal que lo valide y lo incorporamos.
