### ISSUE TITLE
Posible error en reciente actualización de informe EPI

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1072]
Creo que hubo un error en la reciente actualización del Producto 1 / Datos de informe EPI (commit bfd55b7cd9cf5ec53bab317068d1da096044a072)

Los datos para 2021-08-20 parecen ser duplicados del 2021-08-16
![image](https://user-images.githubusercontent.com/68602/130337542-3e1b5edf-b0fc-4174-af9b-28c822a76f29.png)

**Comment by ctroncoso** [comment]
Concuerdo... todas las comunas con 0 casos nuevos. 
¡ Me ilusionaron ! :wink:

**Comment by dafernandez75** [comment]
Hola,

Aún el Minsal no ha subido el informe EPI 148, por lo que en la práctica ningún producto dependiente tendría que estar actualizado....  saludos

![rGqn8LOSWh](https://user-images.githubusercontent.com/69001461/130339597-6e232937-75fc-40d0-abf3-e8596d2358e7.png)

**Comment by MinCiencia** [comment]
Hola a todes, efectivamente desde esta semana el Ministerio de Salud de Chile solo pubicará 1 informe epidemiológico, los días miércoles. Si bien sabíamos de esta decision, el código que actualiza no lo modificamos a tiempo gatillando una actualización falsa. 

Vamos a revertir el commit y continuar sin la actualización de los sábados.

Nuestro foco de trabajo conjunto ahora con el Departamento de Epidemiología son la vigilancia genómica y recuperar el informe de testeo y trazabilidad.

**Comment by MinCiencia** [comment]
Reverted https://github.com/MinCiencia/Datos-COVID19/commit/4f0724318c60e0f20646a93dc1575de1fc1363c2
