### ISSUE TITLE
¿Cómo funciona el Producto 61?

### ISSUE THREAD

**Issue by SophVZ** [MinCiencia/Datos-COVID19#1076]
Hola, el la serie de datos de fallecidos por comuna, tengo una duda. En el caso de que tanto los valores confirmados como los sospechosos sean acumulados:

Sucede que en los datos u07.2 (no confirmados) en las comunas de Huasco, Mejillones, Tocopilla, Caldera, Puchuncaví, Quintero, San Antonio, Coronel y Arauco (son las que revise) los valores aumentan, pero en algunas fechas disminuyen y luego vuelven a aumentar. 

No se si yo entendí mal y no son acumulados, si no diarios y solo los u07.1 son acumulados...

Gracias!

**Comment by dna33** [comment]
Hola, edité el título, simplemente porque es habitual en la investigación epidemiológica que los casos marcados como sospechosos terminen confirḿandose, y por ende reubicandose en esa categoría.

**Comment by dafernandez75** [comment]
recordemos que han existido días, en que los U072 (sospechosos) han disminuido en Chile en +1.000 (nivel país)  con un amplio margen de días afectados.

**Comment by SophVZ** [comment]
Aaaaa! Genial! Muchísimas gracias por la respuesta. No se me había ocurrido
que los casos se podían confirmar posteriormente.

Muchas gracias!
