### ISSUE TITLE
Faltan fechas producto 1

### ISSUE THREAD

**Issue by AntoineBraultChile** [MinCiencia/Datos-COVID19#1085]
Hola,

Me parece que con la actualización de hoy faltan fechas en el producto 1.
Pasamos del 2021-08-16 directamente hasta el 2021-08-27.
Creo que faltan el 20 y el 23 de agosto. 

Muchas gracias.
Saludos.

**Comment by MinCiencia** [comment]
Cieto, gracias por reportar.

Corregimos: https://github.com/MinCiencia/Datos-COVID19/commit/2e9b9eaadfd2a97bd79564a3b439e91783e1c8dd
