### ISSUE TITLE
Acceso a licencia del repositorio

### ISSUE THREAD

**Issue by xavierutox** [MinCiencia/Datos-COVID19#1086]
Hola,

El link de la licencia del repositorio lleva a una pagina no existente

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/35935499/131238417-a35a4725-a987-4b4f-a678-42c47e5db849.png">

**Comment by MinCiencia** [comment]
Hubo cambios en la web del ministerio y se perdio el link, esta restaurada ahora.
