### ISSUE TITLE
Hora estimada para actualización de datos de informe diario?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1088]

**Comment by adinamarca** [comment]
Hola, me sumo a la consulta de @elaval.

Desde ya, gracias por su trabajo a todos y todas.

Saludos!!

**Comment by xavierutox** [comment]
Hola, me sumo a la pregunta y aprovecho de aportar un poco de información

El workflow tuvo el siguiente fallo de dependencias: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35935499/131267941-ad202af1-6321-4018-8876-f2ce0124e7ac.png">

Y aprovecho de recomendar que sería bueno cambiar la hora en que se ejecuta esa acción, dado a que el informe diario en twitter se esta publicando a las 11am y la acción a las 12 aprox

Saludos!

**Comment by MinCiencia** [comment]
Hola, actualizamos hace algunos minutos: https://github.com/MinCiencia/Datos-COVID19/commit/4cca582bdede9f56726d7a680d4ccad4808ee566 

Efectivamente estamos simplificando el archivo de requisitos por temas de interoperabilidad, y cometimos un error con las dependencias.
