### ISSUE TITLE
Datos vigilancia genómica (variantes)

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#1089]
Hola estimad@s,

Tengo una **pequeña sugerencia**, y tiene relación con **añadir datos de vigilancia genómica o variantes a nivel nacional, y segregarlos de forma regional de ser posible**.

He estado indagando, y existen informes por parte del Minsal, apoyados por el Min. Ciencia, en concreto, [en este enlace](https://www.minciencia.gob.cl/areas-de-trabajo/minciencia-covid19/secuenciagenomica/).

![image](https://user-images.githubusercontent.com/63689583/131592607-1cddc28e-d041-40a3-aa61-f07a4736787c.png)

¿Es posible agregar estos datos al presente repo? Si bien, es enorme la cantidad de datos que ya de por sí se manejan, sería genial poder contar con los mencionados.

Desde ya, muchas gracias por su enorme contribución y trabajo en democratización de datos.

Saludos.

**Comment by MinCiencia** [comment]
Hola, estamos trabajando en integrar estas fuentes, cualquier ayuda es bienvenida.

https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perCountryData.json
https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perClusterData.json

**Comment by adinamarca** [comment]
> Hola, estamos trabajando en integrar estas fuentes, cualquier ayuda es bienvenida.
> 
> https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perCountryData.json https://raw.githubusercontent.com/hodcroftlab/covariants/master/web/data/perClusterData.json

¡Hola! @MinCiencia @dna33 
Acabo de incorporar dichos datos en el [siguiente vínculo](https://raw.githubusercontent.com/pandemiaventana/pandemiaventana/main/out/variants/varianteschile.csv). Están filtrados nacionalmente y se actualizan aprox. 3-4 veces al día (por lo que, en caso de existir actualización desde la fuente, el .csv se mantendrá actualizado también). [Realicé un pequeño notebook aquí en relación al filtro de datos](https://pandemiaventana.github.io/pandemiaventana/out/variants/variants.html).

Ojalá pueda ayudar.

¡Saludos!

**Comment by dna33** [comment]
Hola, gracias, tremendo trabajo!

¿ es real la última actualización solo al 27 de diciembre? me pareció ver en GISAID hasta el 10 de enero ayer.

**Comment by adinamarca** [comment]
> Hola, gracias, tremendo trabajo!
> 
> ¿ es real la última actualización solo al 27 de diciembre? me pareció ver en GISAID hasta el 10 de enero ayer.

Hola! De nada.

Sí! Es raro, parece existir cierto desfase en la actualización de la fuente (_no es problema del repo que realicé_), dado que no es del todo frecuente. De todas formas corroboré que sí se actualiza, pero demora. Desconozco si existirá otra fuente con mayor frecuencia de actualización.

![image](https://user-images.githubusercontent.com/63689583/149828085-d11d9ec8-3340-49cb-99a9-c248f80a71c3.png)
