### ISSUE TITLE
Productos no actualizados

### ISSUE THREAD

**Issue by javierlopeza** [MinCiencia/Datos-COVID19#109]
Veo que:
[output/producto5/TotalesNacionales.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5/TotalesNacionales.csv)
Será actualizado con la PR https://github.com/MinCiencia/Datos-https://github.com/MinCiencia/Datos-COVID19/pull/108.

Pero los siguientes productos aún no se actualizan (último dato es del 28-abril):
* [output/producto14/FallecidosCumulativo.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto14/FallecidosCumulativo.csv)
* [output/producto3/CasosTotalesCumulativo.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/CasosTotalesCumulativo.csv)

**Comment by javierconcha** [comment]
Cree el pull request #110 con la actualización de los datos que faltan. Espero que admin los acepte.
