### ISSUE TITLE
Producto 37 Fallecido, falta actualización 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1090]
Hola,
Solo actualizaron lo pendiente de ayer?, no se ve reflejado lo ya informado por el Minsal el de hoy .

Saludos

**Comment by Jorgecibia** [comment]
y falta actualiza sospechosos del 27/Ago, saludos y gracias

**Comment by paarriagadap** [comment]
Hola! Al parecer ya se han actualizado tanto el 37 como el 50, pero el 84 también falta, que viene del mismo lugar.
Saludos!

**Comment by dafernandez75** [comment]
Si bien es cierto la nueva actualización del día totaliza los 36.945 (U071), llama la atención que solo correspondan hasta los registros del 28-agosto-2021, debiendo ser al 29-agosto-2021, ya que generalmente hay desfase de 3 días.
