### ISSUE TITLE
Datos en producto 54 (Número de reproducción efectivo) volvió a fecha anterior luego de actualización

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1093]
El producto 53 tiene actualmente datos hasta el 21 de Agosto

Commit b4e608d38bbbc669ba68b533811c0850830d5126 había actualizado los datos al 28 de Agosto
Commit 01b7779d2adb36592abf07446650bcf42dcdf0f9 volvió a version de datos hasta el 21 de Agosto

¿Se revirtió intencionalmente?
¿Cuándo podremos contar con datos actualizados al 28 de Agosto?

Gracias

![image](https://user-images.githubusercontent.com/68602/132101219-6d0d468c-9eaa-4314-b722-dcd2de96a993.png)

**Comment by dna33** [comment]
Hola, no fue intencional, hay un proceso que corría automáticamente bajo ciertos criterios que cambiaron, recién lo actualicé y no debería volver a revertirse. Lamentablemente pasó 2 veces, la segunda pensé que ya lo había resuelto. Gracias por avisar.
