### ISSUE TITLE
Falta actualización Producto 37 (U071,U072)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1094]
Hola,
Está aún pendiente de la actualización de hoy, con respecto a U071 y U072.
¿Cuándo se actualizará este producto? 
¿a qué se debe que las actualizaciones recientes se están demorando más que antes?

Saludos.

**Comment by dna33** [comment]
Hola, en el balance diario de hoy se incluirán. No se están demorando más, al igual que antes, a veces fallan los procesos automáticos.

**Comment by dafernandez75** [comment]
Hola, con la reciente actualización (hace 40min) no se actualizaron los U072 (Sospechosos), fallo el proceso automático.
