### ISSUE TITLE
Consulta sobre producto 89

### ISSUE THREAD

**Issue by jorgepacheco84** [MinCiencia/Datos-COVID19#1096]
Hola, quería consultar la periodicidad del producto 89.

Saludos.

**Comment by dna33** [comment]
Hola, debería ser semanal, los días jueves, pero esta en rodaje y camino a establizarse. Este jueves debería haber una nueva actualización y acabamos de hacer la que correspondía al jueves pasado https://github.com/MinCiencia/Datos-COVID19/commit/f1a2b858f9d1fac2df41f54ae40f9491e8e66b5c
