### ISSUE TITLE
Hola, con la reciente actualización (hace 40min) no se actualizaron los U072 (Sospechosos), fallo el proceso automático.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1097]
Hola, con la reciente actualización (hace 40min) no se actualizaron los U072 (Sospechosos), fallo el proceso automático.
En relación a los Confirmados U071 totalizan 37.104 siendo que deben ser 37.108 según balance diario del Minsal al 06-09-2021. 
![hVJRDlVeTL](https://user-images.githubusercontent.com/69001461/132255360-164ec5f4-2972-4196-96a0-1a9d86bb0bc2.png)

_Originally posted by @dafernandez75 in https://github.com/MinCiencia/Datos-COVID19/issues/1094#issuecomment-913819733_

**Comment by dna33** [comment]
Corregido https://github.com/MinCiencia/Datos-COVID19/commit/fb16e74295a6e76e0709d1b90816fde28a47583a, gracias por avisar.

**Comment by dafernandez75** [comment]
Hola, 
No se actualizó el U071 (confirmados) sigue totalizando 37.104 al 06-09-2021, según Minsal con cifras del Deis es de 
37.108.

![minsal](https://user-images.githubusercontent.com/69001461/132259711-ee327b14-7cea-4539-a54e-0c44e1233648.png)
