### ISSUE TITLE
No se actualizó el U071 sigue totalizando 37.104 y debe ser 37.108. (serie Confirmados 06-sep-2021)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1098]
Hola, 
No se actualizó el U071 (confirmados) sigue totalizando 37.104 al 06-09-2021, según Minsal con cifras del Deis es de 
37.108.

![minsal](https://user-images.githubusercontent.com/69001461/132259711-ee327b14-7cea-4539-a54e-0c44e1233648.png)

_Originally posted by @dafernandez75 in https://github.com/MinCiencia/Datos-COVID19/issues/1097#issuecomment-913848044_

**Comment by dafernandez75** [comment]
Hola, con la actualización de hoy 07-sep-2021, la serie de ayer 06-sep-2021 se mantiene en 37.104, por qué no es 37.108?,

la de hoy ok con respecto al Minsal 37.115.

**Comment by dna33** [comment]
Estoy en conversación con el equipo del Ministerio de Salud de Chile, y efectivamente hubo un error en la publicación de ayer. Me enviarán la corrección en minutos y publicaremos, muchas gracias.
