### ISSUE TITLE
Cómo es posible que el ministerio de ciencia de Chile tenga que recurrir a Web Scraping para obtener datos oficiales?

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#11]
Uno pensaría que como ministerio tienen acceso a hacer consultas a EPIVIGILA. Qué pasa?
Tienen pensado acceder a los datos de forma transparente?

**Comment by dna33** [comment]
Hola, el sistema EPIVIGILA sigue siendo interno al Ministerio de Salud, hemos si generado integraciones de actualización de datos automáticas utilizando la información que hemos ido sido capaces de disponer, a raíz del trabajo en la mesa de datos 

- [Informe 1 de la submesa de Datos COVID-19](https://www.minciencia.gob.cl/sites/default/files/informe_1_submesa_datos_covid19_200507.pdf) 
- [Informe 2 de la submesa de Datos COVID-19](https://www.minciencia.gob.cl/sites/default/files/informe_2_sub-mesa_datos_covid19_1.pdf)
- [Informe 3 de la submesa de Datos COVID-19](https://www.minciencia.gob.cl/sites/default/files/informe_numero_3_submesa_datos_covid19_1.pdf)
- [link a las actas de la submesa entre abril y septiembre 2020](https://www.minciencia.gob.cl/covid19) al final de la página, sorry el diseño, aparecen los links a las actas de las reuniones semanales. 
- [link al whitepaper con lecciones aprendidas](https://www.minciencia.gob.cl/DocumentoTrabajo), este documento registra el proceso por el que tuvimos que transitar para disponibilizar datos.
