### ISSUE TITLE
Actualizar producto 68 y 70

### ISSUE THREAD

**Issue by datagovuc** [MinCiencia/Datos-COVID19#1101]

**Comment by dna33** [comment]
hola, el que no se haya actualizado trnadŕa que ver con esto que les pregunté en el commit https://github.com/MinCiencia/Datos-COVID19/commit/c031a61b82d0ee399d708495a134acef2f1d89d9?  



Nota pregunta, para @datagovuc: Los siguientes archivos no fueron procesados, a qué productos corresponden?

Not processed: ['../input/UC/carga.ss.csv', '../input/UC/tasa test comunal.csv', '../input/UC/tasa test regional.csv', '../input/UC/prob72.nacional.csv', '../input/UC/tasa test nacional.csv', '../input/UC/prob72.regional.csv', '../input/UC/prob72.provincial.csv', '../input/UC/carga.provincial.csv', '../input/UC/tasa test provincial.csv', '../input/UC/carga.nacional.csv', '../input/UC/carga.regional.csv', '../input/UC/confirmados nacional.csv']
