### ISSUE TITLE
Problema producto 84

### ISSUE THREAD

**Issue by SophVZ** [MinCiencia/Datos-COVID19#1102]
Hola! ya lo comente pero no se si era el hilo correcto.

En el producto 84 salen solo 0 como valores de muertes en las muertes confirmadas. No se si a mi me sale mal o tiene algún error.

Saludos!

**Comment by dna33** [comment]
Tienes razón, vamos a revisar. Probablemente se dba al cambio en columnas desde la fuente, ha pasado antes. Esperamos poder revisarlo antes del sábado, día en que se debe actualizar.

**Comment by SophVZ** [comment]
gracias!

**Comment by MinCiencia** [comment]
Hola, puedes revisar ahora? Esta última actualización parace venir bien.

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/1112

**Comment by SophVZ** [comment]
Oka. Escribo cualquier cosa!

Gracias!
