### ISSUE TITLE
Actualización productos 63 al 67

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#1103]
Estimados:

Por qué no se ha actualizado en más de 1 mes los productos cuya data proviene del análisis del **Laboratorio de Biología Computacional de la Fundación Ciencia & Vida**? En caso que ellos ya no puedan aportar, qué se hará para mantener actualizada esa data?

**Comment by MinCiencia** [comment]
Hola, estamos trabajando junto al Ministerio de Salud en re-incorporar esa actualización. La semana pasada el Minsal logró entregar un input en los formatos equivalentes a los que entregan otras fuentes, y esta semana hemos trabajado en procesarlo para reproducir los productos que mencionas y añadir un par más. Creo que debería estar listo antes del próximo miércoles.

**Comment by ishmaster** [comment]
Ok! entonces quedo atento a las próximas mejoras.
Por último, dentro de esos productos adicionales, está considerada la data de **Razón de contactos por caso (región y comuna)**? Esto para verificar la evolución de la trazabilidad.

**Comment by MinCiencia** [comment]
Publicado https://github.com/MinCiencia/Datos-COVID19/commit/b53194b40e8072ecb856d70e5addb18314132ee8
