### ISSUE TITLE
Inconsistencias en los fallecidos

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#1105]
Hola:
Tengo inconsistencias en los fallecidos, que hayan fallecidos negativos entre un día superior y uno inferior (de fechas), no me calza

Serie | Publicacion |  09-09-2021 | 10-09-2021 | Totales
confirmados          | 21                  | 5                 | 37159
confirmados              3                  | 0                 | 37178
Diferencia              | -18                 | -5               | 19

Solicito revisar, por favor.

Eduardo

**Comment by MinCiencia** [comment]
Hola, puedes especificar a qué producto te refieres?
