### ISSUE TITLE
PRODUCTO 3: Posible error informe 17-06-2020

### ISSUE THREAD

**Issue by diegoquezadac** [MinCiencia/Datos-COVID19#1106]
El día 16 de Junio se contabilizaba un total de 184.449 casos totales informados, al dia siguiente 220.628. Es decir, es como si el día 16 de Junio se hubiesen informado 36.179 nuevos casos.

No encuentro algún README  explicando el porqué de este dato anómalo, por lo que sospecho que puede ser un error.

**Comment by dafernandez75** [comment]
fuel el cambio de metodología, ampliamente difundido.

**Comment by diegoquezadac** [comment]
Muchas gracias Daniel. Sospechaba que podía ser algo así pero no encontraba la información.
