### ISSUE TITLE
Diferencias Fallecidos Producto 89 / Producto 90

### ISSUE THREAD

**Issue by cbalarth** [MinCiencia/Datos-COVID19#1107]
Hola. La suma de fallecidos para una misma semana no calza entre "Producto 89" y "Producto 90".
¿Lo entendí mal o hay un problema? Me aseguré de quitar todos los filtros y hacer la suma total de fallecidos para la misma semana epid.

**Comment by elaval** [comment]
Por lo que yo entiendo se reportan cifras diferentes

Producto 89: Personas fallecidas en la semana respectiva
Producto 90: Personas fallecidas de entre aquellos que hayan tenido inicio de síntomas la semana respectiva

Pero la documentación no es muy clara al respecto y sería muy útil clarificarlo y despejar las dudas que se producen

**Comment by dna33** [comment]
¿qué es lo que falta aclarar en la documentación? Es como indica @elaval, en la documentación se puede leer.

**Comment by MinCiencia** [comment]
Pero preguntamos nuevamente, ¿qué es lo que no está claro? Puede distinguirlo usted con claridad, para no interpretar nosotros?

**Comment by ctroncoso** [comment]
> Pero preguntamos nuevamente, ¿qué es lo que no está claro? Puede distinguirlo usted con claridad, para no interpretar nosotros?

No es consistente si los valores corresponden a casos en que el evento OCURRIÓ durante esa SE o si fue REPORTADO durante esa SE.

Siendo especifico:
Columna `sin_vac_casos` se entiende como que los casos son los reportados esta semana, independiente si el inicio de síntomas comenzaron hace 3 semanas.  Esta columna corresponde al instante en que es reportado.

Columna `dosis_unica_uci` corresponde al EVENTO fecha de ingresó a UCI. independiente de cuando haya sido reportado. 
A diferencia del anterior, esta está corregida y corresponde al evento y no al reporte. 

Ambos datos están claros, si se le da una lectura bien rigurosa, pero aún así, por consistencia, mantendría en sets separados, elementos basados en fechas de reporte y los que han sido corregido a la fecha del evento.
