### ISSUE TITLE
Actualización de productos 89 & 90

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1108]
Consulta/comentario (con ánimo constructivo)

Al día de hoy (Martes 14 Sep - 9am) no se han actualizado los productos 89 y 90 para los cuales esperábamos actualización la semana pasada.

Según la documentación la "Frecuencia de actualización" está "Asociado a los informes semanales, publicados por el Ministerio de Salud de Chile" y el último informe semanal del Ministerio de Salud fue publicado con fecha 8 de Septiembre de 2021

[INFORME EPIDEMIOLÓGICO No 5 INCIDENCIA Y GRAVEDAD DE CASOS COVID-19 SEGÚN ANTECEDENTE DE
VACUNACIÓN CHILE 08-09-2021](https://www.minsal.cl/wp-content/uploads/2021/09/informe_vacuna_08_09_2021.pdf)

![image](https://user-images.githubusercontent.com/68602/133256845-848801df-ba4c-45d5-b7ee-1e2ee23d7155.png)

¿Cuándo se espera la actualización de estos productos?
¿Será posible actualizarlos en las fechas que se publiquen los informes semanales del Ministerio de Salud?

Saludos y gracias

**Comment by dna33** [comment]
será  posible, sin embargo hemos estado avanzando en otros temas esta semana y no hemos automatizado todavía esa rutina. Espero podamos hacer una actualización antes del jueves.

**Comment by jorgepacheco84** [comment]
Hola, ¿Se ha sabido cuándo se actualizarán estos productos?

Saludos

**Comment by MinCiencia** [comment]
Hola, están actualizados al 15 de septiembre ahora -datos recibidos el jueves pasado que recién pudimos actualizar: https://github.com/MinCiencia/Datos-COVID19/commit/5ba5a26ade04a9ce071aec471136dc4194cc5b67 

Debería actualizarse los días jueves, semanalmente.
