### ISSUE TITLE
Inconsistencia en casos activos producto 19

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#1110]
Estimados:

Al revisar los casos activos por comuna según la última actualización disponible en github se produce una disminución en la región metropolitana.

- Lunes 13 de septiembre: 1.957
- Viernes 17 de septiembre: 976
- Δ%: -50,13%

Por otro lado, el informe diario refleja un aumento.

- Lunes 13 de septiembre: 1.496
- Viernes 17 de septiembre: 1.604
- Δ%: 7,22%

Entendiendo que hay diferencias de criterio que hacen que los datos no calcen, cómo se explica que hayan bajado los casos activos en github siendo que el reporte diario reporta un aumento?

**Comment by MinCiencia** [comment]
Corregimos la actualización hoy, por favor revisar: 48319511bc374f9c5b2ef8917c1534828efd6d25
