### ISSUE TITLE
Actualización de productos de defunciones

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1111]
Hola, he visto que no se han actualizado hace 2 semanas los productos de defunciones DEIS (50 y 84), que incluyen en detalle información de muertes sospechosas y confirmadas. Espero que se pueda regularizar su actualización.

Saludos!

**Comment by MinCiencia** [comment]
Hola, revisar https://github.com/MinCiencia/Datos-COVID19/issues/1112
