### ISSUE TITLE
falló la actualización Producto 37 (fallecidos confirmados y sospechosos)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1112]
Hola,
falló la actualización Producto 37 (fallecidos confirmados U071 y sospechosos U072).
Nota: El Deis recién hoy actualizó fallecidos totales por diferentes causa desde Datos Abiertos.

Saludos

**Comment by MinCiencia** [comment]
Hola, así es, subimos las series del 9 de septiembre fdaa207794e075e7b5fe3c711c6817acf66ba91b y el 16 de septiembre a4be386b6ee9565fa84316f6758100a51fc6892f
