### ISSUE TITLE
Agregar poblaciones de niños de 6 a 12 años

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1113]
Hola, como ahora se vacunan los niños menores de 12 años es necesario añadir al archivo adicional de población por comuna del P81 los números para las edades entre 6 y 12, para estimar correctamente el avance porcentual de ese grupo.

Saludos y muchas gracias

**Comment by MinCiencia** [comment]
Hola, @paarriagadap. Acabamos de añadirlo en este commit 5f4c5f8130db63500f6320c8ecb93a4a3d8bc4e5, muchas gracias por la atención.
