### ISSUE TITLE
error en producto 61

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#1116]
Hola, buenas tardes

El producto 61 tiene el mismo valor el 17.09 y el 20.09, se repiten los valores

Etiquetas de fila | Suma   de 17-09-2021 | Suma   de 20-09-2021
Total general       | 48032                          | 48032

Favor corregir,

Saludos,

Eduardo

**Comment by dna33** [comment]
gracias por reportar, corregido 5858cfc8fedb9dcdb60316b9e5313253597519b3
