### ISSUE TITLE
Falta actualización real Producto 39, según @min_ciencia_IA 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1117]
Hola,
Según publicación de la cuenta de twitter @min_ciencia_IA debería estar actualizado el producto 39.
Correspondiente el Informe EPI 152 subido por el Minsal hace pocos momentos.

Al revisar este Producto39 aún no está actualizado, debió haber fallado la actualización.

Saludos
![epi152](https://user-images.githubusercontent.com/69001461/134434547-c9115509-7869-4a9d-ac68-7d45a5de61ab.png)
![fotoprod39](https://user-images.githubusercontent.com/69001461/134434563-5f763656-e0e8-4333-a751-17c9d9f729b6.png)

**Comment by dna33** [comment]
corregido 5858cfc8fedb9dcdb60316b9e5313253597519b3
