### ISSUE TITLE
Producto 65 solo tiene datos hasta el 06 de Septiembre

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1118]
Hola, el producto de tasa de positividad comunal tiene datos solo hasta el 06 de Septiembre (2 informes TTA atrás). Tienen pensada una pronta actualización de este producto que incluya datos del último informe?

**Comment by dna33** [comment]
si, al día siguiente de su publicación pretendemos se actualice. Es decir hoy.

**Comment by MinCiencia** [comment]
It's done 4daeecc7f769977a6ac50ca39cbd8a5d65607679
