### ISSUE TITLE
Error producto 61

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#1119]
Hola buenas tardes.

Existe un error en el producto 61, no es posible que con PCR+ disminuyan los fallecidos el día 24.09 respecto al 20.09, favor verificar.
Con pronóstico probable, estamos claro que pueden variar.

                            | 20-09-2021     | 24-09-2021
Etiquetas de fila | U07.1 | U07.2    | U07.1  | U07.2
Total general      | 37.367 | 10.808 | 37.253 | 10.779

Saludos,

Eduardo

**Comment by dna33** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/1120
