### ISSUE TITLE
Error actualización Producto 39 (Fecha Inicio Síntomas)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1120]
Hola,
La actualización de hoy, repitió la serie ya publicada el 20-sep-2021 (Fecha Inicio Síntomas).

Saludos.

**Comment by EduardoB-Chile** [comment]
Si existe un posible error pues la publicación del 22.09 indicada en Bío Bío (entre positivos y probables) 185,544 casos y lo publicado hoy 25.09 indica 185.405 casos.

Existe incongruencia, al igual que el en producto 61, favor revisar.

Saludos,

Eduardo

**Comment by dna33** [comment]
efectivamente, la publicación de hoy no viene con datos nuevos. Minsal esta corrigiendo. Publicaremos nuevamente cuando exista solución.

**Comment by dna33** [comment]
corregido aa30ac91abd7c85c172aa9ae5c62868abcc2923b
