### ISSUE TITLE
Consulta sobre actualización de producto 89

### ISSUE THREAD

**Issue by jorgepacheco84** [MinCiencia/Datos-COVID19#1121]
Hola:

¿Cuándo se actualiza el producto 89 de la semana pasada y esta semana?

Saludos.

**Comment by dna33** [comment]
Hola, habitualmente al día siguiente de la publicación del informe epidural. Se acaba de hacer esta mañana: https://github.com/MinCiencia/Datos-COVID19/commit/17a0466d4aece74f3fb83089323aa8d42dc29140
