### ISSUE TITLE
Inconsistencia variación casos activos producto 19

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#1124]
Estimados:

Les comento que se produce una inconsistencia en la variación de casos activos indicada en el producto 19 entre el 27 de septiembre y el 1 de octubre de 2021. A modo de ejemplo, se presenta información para la región metropolitana.

1) Github
- 27 de septiembre: 3.038
- 1 de octubre: 3.356
- **Δ%: 10,47%**

2) Reporte diario MINSAL
- 27 de septiembre: 2.279
- 1 de octubre: 2.069
- **Δ%: -9,21%**

Si hubo un error, favor indicar cuándo se regularizará la información. Gracias!

**Comment by ishmaster** [comment]
Hola demian!
Entiendo perfectamente las diferencias de criterio de ambos reportes. No obstante, me parece extraño que las diferencias porcentuales sean de signo distinto, siendo que debiesen ser consistentes ya sea al alza o a la baja. Además, cabe señalar que comparo todas las semanas las diferencias porcentuales de ambos reportes y, salvo excepciones como ahora, siempre es consistente con el signo de la variación.

**Comment by dna33** [comment]
Y pudiste revisar el producto 46? Te entrega alguna perspectiva?

**Comment by ishmaster** [comment]
Sí revisé el producto 46. Lamentablemente no me sirve para el análisis de casos activos que yo hago a nivel regional y que puedo obtener de los productos 3 y 19. Entonces, al comparar las variaciones porcentuales (incluyendo casos probables) en ambos productos siempre son consistentes, ya sea al alza o a la baja. Por lo mismo, me llamó la atención que se produjera una inconsistencia en el signo de la variación porcentual.

Por último, señalo que esta situación ya ocurrió anteriormente y quedó consignada en el issue #1110, por lo que se procedió con la revisión y corrección de datos del producto 19.

**Comment by ishmaster** [comment]
Al revisar el producto 3 para la región metropolitana, incluyendo los casos probables, los datos son los siguientes:

- 27 de septiembre: 3.052
- 1 de octubre: 2.828
- **Δ%: -7,34%**

Como puedes ver, esto no se condice a nivel del signo de la variación porcentual indicada en el 1º post (**10,47%**) según los datos del producto 19.

**Comment by dna33** [comment]
mira, aunque se vea anómal, parece haber sido una alza real en base a la mejor información disponible del departamento de epidemiología

![WhatsApp Image 2021-10-06 at 16 11 49](https://user-images.githubusercontent.com/12438811/136271666-9b7a5dfb-97d7-482b-84fb-3e1b4dd82eb7.jpeg)

**Comment by ishmaster** [comment]
Si es así, llama la atención que no se haya visto reflejada esa alza en el producto 3 ya que, como te mencioné anteriormente, siempre ha sido consistente el signo de la variación porcentual de los casos activos (incluyendo casos activos probables) entre los productos 3 y 19.

**Comment by MinCiencia** [comment]
Bueno, el hecho de que el informe epi considera la fecha de inicio de síntomas y no la confirmación por laboratorio, sitúa los casos en una línea de tiempo distinta, en principio no está obligada a darse esa tendencia, aunque se de habitualmente

**Comment by dna33** [comment]
Corregidas las series de activos y actuales acorde a la nueva definición del ministerio de salud para casos activos, vigente desde octubre. Gracias nuevamente a @ishmaster por insistir en el tema y permitirnos coordinar con Ministerio de Salud la corrección de los datos.

2733db62f7f7088b2fda5727f43c1cd3ce7a3b96
263cdf85208cc77923593c0b928e613020aa97e1
76a5b01e304b537c0e92cd7e19d1defa20c386a6
d76a51bb174334b9f1dc9dbaaa91311261f3f4f9
