### ISSUE TITLE
Producto 14, fallecidos acumulados csv, inconsistencia de datos

### ISSUE THREAD

**Issue by Axoluther** [MinCiencia/Datos-COVID19#1126]
En la fecha 2020 junio entre los días 5, 6 y 7 se aprecia un error respecto a la frecuencia acumulada.
Por ejemplo, en la región de la Araucanía tiene los datos por día: 47, 48, 49, 31, 32, 32 , 33 ...
Y no solo la Araucanía, varias de las regiones tienen este problema en la misma fila en adelante

**Comment by dna33** [comment]
Muchas veces se re-clasifican las defunciones que ocurren lejos de su domicilio. Disminuciones pueden deberse a eso. Que información buscas? Hay productos que ofrecen mayor detalles sobre estadisticas relacionadas.
