### ISSUE TITLE
Error en valores del producto 67

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#1127]
Estimados:

Favor revisar los valores del producto 67 desde el 2-8-2021 ya que no corresponden a la oportunidad de notificación señalados en los informes semanales TTA.

**Comment by dna33** [comment]
Hola, puedes por favor indicar con más precisión las diferencias? Ayuda para plantear al Ministerio de Salud.

**Comment by ishmaster** [comment]
A modo de ejemplo, te indico los valores para la comuna de Iquique:

1) Github

![image](https://user-images.githubusercontent.com/62425955/136697316-624f6e7d-5368-438a-90d5-1fa0af08a691.png)

2) Informe semanal TTA (valor en %)

- 2-8-2021: 100
- 9-8-2021: 98,7
- 16-8-2021: 98,6
- 23-8-2021: 98,5
- 30-8-2021: 100
- 6-9-2021: 88,4
- 13-9-2021: 97,8
- 20-9-2021: 96,8
- 27-9-2021: 93,1
- 4-10-2021: 100

**Comment by ishmaster** [comment]
Hola!
Hay novedades sobre este tema?

**Comment by ishmaster** [comment]
Aún veo que no se corrigen los valores del producto 67. A modo de ejemplo y dando continuidad a lo ya publicado previamente, la comuna de Iquique presenta los siguientes valores para la fecha 25-10-2021:

- Github: 99,7%
- Informe semanal TTA: 100%
