### ISSUE TITLE
Importante error en datos de incidencia de fallecidos - Producto 89

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1129]
En Producto 89 se entregan los datos de cantidad de casos, ingreso a UCI y fallecidos - y la respectiva incidencia - para cada grupo de edad
![image](https://user-images.githubusercontent.com/68602/136775876-720fa21a-cc1b-4768-badd-e47cbfc70ae2.png)
Al ver las cifras de incidencia para fallecidos en al semana 39 hay un error evidente para el grupo de 41 a 50 años: se indica 0 fallecidos y una incidencia > 0
![image](https://user-images.githubusercontent.com/68602/136777796-fb30d5ba-2368-43cb-9838-a746eb4d05ee.png)
Al realizar el cálculo de incidencia con los datos publicados (fallecidos y población) es posible identificar que hay errores en la incidencia (o el número de fallecidos) publicados para distintos grupos de edad
![image](https://user-images.githubusercontent.com/68602/136777187-2e55b83b-293d-4c53-9f61-4c67aaf5e1f6.png)

Creo que esto es un problema importante ya que se puede comunicar un mensaje erróneo de la efectividad de las vacunas contra la muerte

Por ejemplo, con los datos publicados para el grupo >= 80 años se tiene una incidencia de fallecidos de 5,6 en personas vacunadas con esquema completo y 2,7 para aquellas sin esquema completo.  El dato indica que hay casi el doble de incidencia en los vacunados con esquema completo (cuando en realidad debiera ser menor: 2,1)
![image](https://user-images.githubusercontent.com/68602/136778796-1f9d922d-a90c-4feb-bed3-8cb958851b5b.png)

**Comment by dna33** [comment]
Hola, al parecer ahora esta todo bien, no? Puedes chequear?

**Comment by elaval** [comment]
Sí.  Acabo de chequear y la incidencia parece estar correcta.

Saludos
