### ISSUE TITLE
Algunos productos no actualizados post reporte diario

### ISSUE THREAD

**Issue by javierlopeza** [MinCiencia/Datos-COVID19#113]
Algunos productos no se están actualizando con el script que genera los outputs desde el reporte diario.

[output/producto5/TotalesNacionales.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5/TotalesNacionales.csv)
[output/producto14/FallecidosCumulativo.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto14/FallecidosCumulativo.csv)
[output/producto3/CasosTotalesCumulativo.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/CasosTotalesCumulativo.csv)

Al menos esos productos se mantienen con el 30-abril como último dato.

**Comment by scornejob** [comment]
Gracias @javierlopeza . El problema se gatilló por el cambio de ayer en la pagina del minsal. Estamos trabajando en los problemas: https://github.com/MinCiencia/Datos-COVID19/tree/update20200430/output tiene los productos arreglados.

**Comment by javierconcha** [comment]
Algo no tiene que estar funcionando en el scrapper después del último cambio en la pagina del Minsal:

https://github.com/MinCiencia/Datos-COVID19/blob/master/src/webpage.py

No tengo tiempo de verlo ahora, pero si tu @javierlopeza o alguien puede ayudar a resolver el problema, pueden crear un fork, new branch, resolverlo, commit y después pull request al repositorio original.

**Comment by MinCiencia** [comment]
Ahora si se están actualizando, muchas gracias @javierconcha por el reporte.
