### ISSUE TITLE
Producto89: Separación de casos sin vacuna de los casos con esquema incompleto

### ISSUE THREAD

**Issue by oiturra** [MinCiencia/Datos-COVID19#1139]
Actualmente la columna **estado_vacunacion** en el producto89 puede ser con **esquema completo** o **sin esquema completo**.

Quería proponer que se separara esta categoría en **esquema completo**, **esquema incompleto** y **sin esquema**, para poder tener mejor visón sobre las personas que han iniciado su esquema y las que derechamente no han recibido vacuna alguna.

Saludos
Oscar

**Comment by dna33** [comment]
se añadiò la dosis de refuerzo, acorde a minsal no resulta relevante la diferenciacion que propones...
