### ISSUE TITLE
Persiste problema actualización productos 91 y 92 

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1144]
Persiste problema con actualización productos 91 y 92. Ayer lo que se publicó en producto 91 (ingresos UCI), parece corresponder al producto 92 (ingresos hospitalizados). 

Y el producto 92 sigue sin actualizar. Podrían revisar por favor 

Ayer el ministro mostró datos de ingresos UCI que cerraban en 29, nada que ver con lo que está hoy en producto 91.

**Comment by elaval** [comment]
Acabo de revisar los datos publicados en los commits recientes y confirmo las diferencias que reports @weichafan 

En commit 5748b21be801eb6da1f2169a4eb460ddf3cb1652 (Oct 16, 2021) se reporta 16,57 para el 2021-10-07

https://github.com/MinCiencia/Datos-COVID19/blob/5748b21be801eb6da1f2169a4eb460ddf3cb1652/output/producto91/Ingresos_UCI_std.csv
![image](https://user-images.githubusercontent.com/68602/139850104-b1da24de-e0f3-40f3-b8c8-4595afbd001f.png)

En commit 0e00ff0eeb919237a6419e89a7d31d693411bead (Oct 28, 2021) se reporta 55,14 para el 2021-10-07

https://github.com/MinCiencia/Datos-COVID19/blob/0e00ff0eeb919237a6419e89a7d31d693411bead/output/producto91/Ingresos_UCI_std.csv
![image](https://user-images.githubusercontent.com/68602/139850572-5f73e2de-15a0-4298-98f4-90e3463e2923.png)

**Comment by dna33** [comment]
hola,

el microservicio que actualiza desde la Unidad de gestiòn de camas crìticas de la subsecretaria de redes asistenciales corrìa bien, pero estaban entregando los archivos equivocados, pedimos corregir la situaciòn, espero no vuelva a ocurrir. Por ahora corregimos a mano.
