### ISSUE TITLE
Consulta Producto 37, factibilidad de agregar los U099

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1145]
Hola,

Según lo publicado por el DEIS a través de 'DatosAbiertos', agregaron 4 fallecidos hombres como U099 a los fallecidos, adicionales a los U071 y U072, según se indica corresponden: "Asignación provisoria de nuevas afecciones de etiología incierta, Condición de salud posterior a COVID-19 no especificada".

Por ello, sería consecuente agregar tales registros al Producto37 y en otro producto que aplique, y a la vez clarificar con el DEIS estos registros provisorios,  si corresponden a que estos fallecidos padecieron de Covid19. 

Saludos

**Comment by dna33** [comment]
se corrige con d0d49443db30057ccefc875b78771f07790c0c90 ?

**Comment by dafernandez75** [comment]
No, ya que es una nueva clasificación que hizo el Deis ( 4 casos U099). 
Habrá que esperar si los provisorios U099 aparecen nuevamente este sábado.

A la fecha:
U071: 37.794
U072: 10.873
U099: 4
Total Fallecidos: 48.671
![u099](https://user-images.githubusercontent.com/69001461/140435844-c3f11bce-5f03-494d-97db-af30a190cb4c.png)

**Comment by daniamr** [comment]
@dafernandez75 hola, me podrías enviar tu excel?

**Comment by dafernandez75** [comment]
Hola, descargalo de acá, se actualiza todos los sábados. Saludos https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2021_28102021.zip

**Comment by daniamr** [comment]
Gracias

**Comment by dna33** [comment]
@dafernandez75 revisar qué pasó con el último commit 01a9b372f26980b42ff308aa278bcfb4f13d9f89

**Comment by dafernandez75** [comment]
Aún el Deis no actualiza 'Datos Abiertos' para ver actualización de los fallecidos U099.
mantiene el enlace: 
https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2021_28102021.zip

https://deis.minsal.cl/#datosabiertos

**Comment by dna33** [comment]
https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2021_11112021.zip

Ahi está

**Comment by dafernandez75** [comment]
Agregaron +1. Tenemos ahora 5 clasificados en U099.
U071: 37951
U072: 10898
U099: 5
Total Fallecidos: 48.854

![099_13112021](https://user-images.githubusercontent.com/69001461/141660167-caa39c17-c191-4304-ad83-298782375cc2.png)

**Comment by dafernandez75** [comment]
Agregaron +1. Tenemos ahora 6 clasificados en U099.
U071: 38282
U072: 10924
U099: 6
Total Fallecidos: 49.212

Ref. https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2021_25112021.zip

Pueden consultar al Deis sobre esta clasificación U099, ya que siguen agregando fallecidos bajo esta clasificación y si aplica o no agregarlos al Producto37, ya que corresponde a fallecidos relacionados con Covid19.

![u099_271121](https://user-images.githubusercontent.com/69001461/143687762-d931081d-3074-4a69-97f2-5550331bad69.png)

**Comment by ctroncoso** [comment]
Creo que hay un dilema en cómo el deis comunica estos casos. Se agradece que se intente resumir/simplificar, pero en el proceso se pierde información. Para el análisis, es lejos mas crítico el contar con el set de diagnóstico y sobre todo el diagnostico principal. En los casos de covid, la información es reducida al código U solo, lo que puede no ser preciso. 
![image](https://user-images.githubusercontent.com/121016/143688131-e416bb3f-26df-4189-a071-169fe0663a9c.png)
No es solo que el código exista, sino si está como principal o secundario, más el código GRD. Ese conjunto es el que entrega la información completa.
