### ISSUE TITLE
Diferencias en cifras de casos, ingreso a UCI y fallecidos en distintas fuentes (productos)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1146]
Se detectan importantes diferencias en datos entregados por distintos productos.  Esto puede deberse a errores en los datos o a problemas en la documentación que hace interpretar erróneamente los datos.

Acá entrego una síntesis de los datos obtenidos de distintas fuentes para la **Semana Epidemiológica 31** (1 al 7 Agosto 2021) y adjunto una página web con más detalles.
# Casos confirmados
![image](https://user-images.githubusercontent.com/68602/139600939-7f71b53d-3efc-4f1a-a535-4d2bf4aec54a.png)

# Fallecidos
![image](https://user-images.githubusercontent.com/68602/139600989-dff650f0-53b1-4bcc-b193-b679f09b7afc.png)

# Ingreso a UCI
![image](https://user-images.githubusercontent.com/68602/139601003-ba1264c9-2e02-4029-b1e6-6e041cc680db.png)

El detalle de cómo se obtienen estas cifras (y mis comentarios y preguntas sobre las diferencias) se pueden encontrar en la siguiente página web: <a href="https://observablehq.com/@elaval/chequeo_datos_casos_uci_fallecidos" target="_blank">https://observablehq.com/@elaval/chequeo_datos_casos_uci_fallecidos</a>

**Comment by weichafan** [comment]
Mientras contestan, algún día (contestan, pero no resuelven). Hace muchos días he pedido que actualicen el producto 91 de ingresos a UCI. Lo actualizaron, con lo que parece corresponder a ingresos hospitalarios. Últimos datos están por 79 ingresos diarios, el ministro Paris mostró el jueves 28 que llegaban hasta los 29.   

Hace algunos días puse el problema  #1144 

Me cerré yo mismo el issue #1140 

y se los dije en el issue #1136  

que me lo cerraron por el issue 1140. Pero más allá de cerrar issue, los últimos datos de ingresos a UCI están en el producto 91 en la actualización anterior que fue hace 15 días, que tenía datos (aparentemente coherentes) hasta el 7 de octubre.  

Esto ya es como la ventanilla de cualquier servicio público, te patean para que vayas a otra ventanilla, pero no verifican que lo que publica corresponda a lo que debieran publicar.

**Comment by daniamr** [comment]
Hola, quiero añadir lo siguiente a tu observación para que también sea aclarado.
Quise hacer una comparación con el producto 89 "Incidencia de casos según estado de vacunación, grupo de edad, y semana epidemiológica." y 90 DP - "Distribución de casos según antecedentes de vacunación y semana epidemiológica", 

 Sin embargo, me encontré inconsistencias y me surgieron varias dudas; 

Revisé dentro de la semana epidemiológica 31 a 41 de ambos productos 89 y 90, y lo que me figuró fue lo siguiente; 

Hay diferencias cada semana de las 10 (31 a 41), tanto en casos COVID, como uci y muertes. A continuación, el detalle;

Producto 
producto 89 total muertes (semana 31 a 41): 1463
producto 90 total muertes (semana 31 a 41): 596
Total, diferencia 867, de los cuales 486 corresponden a esquema completo. 

eso es una diferencia del 57% en 10 semanas de muertes para el esquema completo. 

producto 89 total muertes con dosis de refuerzo: 21
producto 90 total muertes con dosis de refuerzo: 30 
total, dif: 9 
* en este punto es importante recalcar que en el producto 90 menciona que la semana 32 hubo 2 muertes y 14 muertes en la semana 33, sin embargo, en el producto 89 menciona que de la semana 31 a 34 no hay muertes. y en la semana 35 dice que hay 6, en la semana 36 dice que hay 7.

producto 89 total casos COVID (semana 31 a 41); 97822
producto 90 total casos COVID (semana 31 a 41): 49.612
total, diferencia: 48.210, de los cuales 39.701 corresponden a esquema completo.  

eso es una diferencia del 59% en 10 semanas del esquema completo…. 

producto 89 total UCI: 1310
producto 90 total Uci 1113
Total, dif: 197, de los cuales; 169 corresponden a esquema completo que faltarían en el producto 90, 37 esquema incompleto que faltarían en el producto 90 y 9 refuerzo que sobrarían en el esquema completo, dentro de las semanas 31 a 41.  

Además, tengo dudas respecto de la definición de las variables del producto 90;

cito; 'sin_vac_fall' indicando el número de casos confirmados que fallecieron de COVID-19 durante la semana epidemiológica correspondiente y que al iniciar síntomas (sintomáticos) o al momento de la toma de muestra (asintomáticos) no ha recibido ninguna dosis de vacuna.

por lo que se entiende, podría darse el caso que una persona dio positivo a COVID asintomático, hizo sus 14 días de cuarentena, a los días de hacer su cuarentena se puso la vacuna, ejemplo al día 20, y al día 22 murió, eso se considera muerte por COVID, ya que cabe dentro de la definición. 

Por lo que mi duda es, como saben a esos casos para saber si fue efecto de la vacuna la muerte o fue efecto del covid, ¿si por definición de la variable sería solo covid?  se hace un estudio especial o solo se asume, y de hacer un estudio especial, donde están los datos? 

cito; 'sin_vac_casos' indicando el número de casos confirmados durante la semana epidemiológica correspondiente, y que al iniciar síntomas (sintomáticos) o al **momento de la toma de muestra (asintomáticos) no ha recibido ninguna dosis** de vacuna.

cito; 'una_dosis_casos' indicando el número casos confirmados durante la semana epidemiológica correspondiente, y que al iniciar síntomas (sintomáticos) o al momento de la toma de muestra (asintomáticos) han recibido la primera dosis y no la segunda dosis, en un esquema que incluye dos dosis,

hablan solo de la semana epidemiológica para revisar el tiempo, sin embargo, no me queda claro si pudiera haber casos que dieron positivo, por ejemplo, la semana 20 (¿hicieron su cuarentena y luego se pusieron la vacuna la semana 23, y después de la vacuna iniciaron los síntomas, se considera como caso COVID sin vacuna o como caso de vacuna 1 dosis? 

Vale decir, ¿estaría dentro de la semana 20 o la semana 23?  y ¿cómo saber que el inicio de los síntomas no fue producto de reacción frente a la vacuna? ¿le hacen seguimiento? si es así, donde están los datos? 

Además, siendo que el producto 89, no considera a los menores de 6 años, ¿cómo puede tener más casos, si el producto 90 no considera el rango etario? 

Otra duda es; basándose solo en el producto 90, ¿como se explica que el total de Uci de esquema completo semana 1 a 41 sean 2634 y total de muertes de semana a 1 a 41 sean 4247?  

El misal usó como referencia el producto 90 y 89 con fecha de 20-10-2021 en su informe de vacunas para hacer gráficos, sin embargo, ambos productos no conversan y tampoco figura las fechas en ambos productos para aclarar y aunque fuera el caso de descuadre de semana, las muertes con las dosis de refuerzo son más en el producto 90 que en el producto 89, lo que haría una diferencia en la incidencia que muestran en los informes epidemiológicos basados en el producto 89. Esto pensando que en el producto 89 solo figuran desde la semana 35, y en el otro desde la semana 32 (2 muertes) y en la semana 33 (14 muertes), ya que en la semana 35 la población de 423 ccon0 casos, y bien distinto sería con 6 personas vacunadas es diferente la incidencia.  o con 22 personas muertas sobre 423 de población. No queda claro. 


Quedo atenta.

**Comment by daniamr** [comment]
Me faltó mencionar que la fecha del informe epidemiológico, del 20-10-2021, contiene un gráfico donde se ven los casos desde semana 1 a 41, sin embargo al revisar de la 31 a la 41, figurarían 48.210 casos menos, siendo 39.701 del esquema completo como mencioné. 

ejemplo; la diferencia sería lo que le faltaría al producto 90, por tanto al gráfico establecido en el informe epidemiológico fecha 20-10-2021 figura separado esas dos variables (pero las diferencias están)

casos covid esquema completo( vacunados 2 dosis mayor a 14 días y dosis única) ; producto 90 semana 31: 2453 vs producto 89 semana 31:  8196 diferencia 5743 
casos covid esquema completo; producto 90 semana 32: 2096 vs producto 89 semana 32: 7332 diferencia 5236
casos covid esquema completo; producto 90 semana 33: 1897 vs producto 89 semana 33: 5640 diferencia 3743
casos covid esquema completo; producto 90 semana 34: 1617 vs producto 89 semana 34: 4584 diferencia 2967

y así para el resto de las semanas hasta la 41. lo que haría que la curva y el porcentaje del gráfico sea diferente. 

Entonces esos gráficos estarían incorrectos? 

quedo atenta.

**Comment by dna33** [comment]
Hola, estamos trabajando en resolver sus dudas.  Nos confunde un poco la relaciòn de este reporte o issue, con anteriores que han hecho acá ustedes mismos, nos pueden ayudar cerrando los que estèn incluidos ahora en este nuevo? Esta semana tenemos a varios integrantes del equipo fuera, por COP26 y estrategia nacional de inteligencia artificial, entre otras cosas, pero intentamos avanzar con estas importantes preguntas.

**Comment by elaval** [comment]
Gracias por el update Demián (@dna33)

Para reducir la confusión te adjunto un resumen de los issues que yo he generado y cómo se relacionan entre sí

### 1. Problema en documentación de productos 89 & 90
Para mi un problema inicial es que **la documentación de los productos 89 y 90 no ha sido clara** sobre a que corresponden los datos de UCI & fallecidos en las respectivas semanas.

- La documentación aclara que el reporte de **casos**  en producto 89 son casos reportados en la respectiva semana y en producto 90 son casos que iniciaron los síntomas en la respectiva semana (**eso despeja mis dudas sobre las diferencias de CASOS en ambos productos**)

- Pero la documentación indica que "**ingreso a uci**" y "**fallecidos**" en ambos productos, 89 y 90, corresponde a casos que **ingresaron a UCI durante la semana epidemiológica correspondiente** y que **fallecieron de COVID-19 durante la semana epidemiológica correspondiente**

Si la documentación es correcta, el total de ingresos a UCI y de fallecidos en las respectivas semanas debiese coincidir para productos 89 y 90 (**pero no coincide**).  Si hay algo que explique la diferencia, esperaríamos que se indique en la documentación y eso despejaría las dudas.

Esto se planteó en el issue #1065 y mi impresión es que la documentación todavía no resuelve las dudas

En el presente issue(#1146) muestro comparaciones de las cifras para distintos productos, lo que evidencia que existe diferencia entre los datos en ambos productos (89 & 90) y también con datos de otras fuentes oficiales (fallecidos por fecha de reporte y fallecidos por fecha de defunción).

Más allá de las diferencias entre productos 89 y 90, tampoco es claro porque estos no calzan con datos oficiales de fallecidos en las respectivas semanas.

Para validar si datos de ingresos en UCI son consistentes con lo informado en el productos 89 & 90  se comparan con los datos del producto 91, pero estos parecen estar errados (detalle a continuación)

### 2 Error en datos de ingreso diario a UCI (Producto 91)

Al hacer los cruces con datos de ingreso a UCI se observa que el producto 91 (que debiera ser la referencia oficial de ingreso a UCI por fecha), mostraba datos muy por sobre lo esperado desde la última actualización.

Esto se informa en el issue #1144 por @weichafan (y yo lo comento corroborando lo planteado)

Un update reciente entrega cifras en Producto 91 que son muy superiores a las entregadas en updates previos (esto hace pensar que se está entregando datos que no corresponde sólo a pacientes COVID19 en UCI como se entregaba antes)

### 3 Error (o diferencia no explicada) en actualización de datos de producto 90 

Este creo que es un tema distinto a los mencionados más arriba y se informó en el issue #1143 

En una reciente actualización se modificó la distribución de las cifras de casos según esquema de vacunación para semanas anteriores (creo que no se modificó el total de cada semana sino que cuantos casos correspondían a una dosis y cuantos a dosis completa).  No sabemos si los datos que habíamos utilizado en semanas anteriores estaban errados o si los datos recientes están errados (esto preocupa porque genera dudas sobre la confiabilidad de estos datos)

**Comment by daniamr** [comment]
gracias. estuve leyendo los anteriores, sin embargo, pese a explicación de la semana epidemiológica, lo leí cuando definieron la variable, no obstante todas las demás variable están definidas según inicio de síntomas o asintomático, por lo que en teoría según yo,  lo que debiese ocurrir es un desface, no un descuadre tan amplio, porque si agarro la semana 30 y 29, aún así no calzan. 

Con respecto al punto 3, creo que es importante mantener las variables aisladas en cuanto a tipo de vacunación. no he podido revisar todos los productos, los miré a simple vista, pero por más que busqué solo esos dos productos tenían separado por estado de vacunación o no vacuna y edad. 

Es una preocupación, porque como tu dices, la confiabilidad del estudio sobre la eficacia de las vacunas se ve bastante comprometido. Además, que no da datos suficientes como para hacer un análisis costo beneficio a corto, mediano o largo plazo. 

Por ejemplo, los menores de 18 años, casi ni se mueren y no van a UCI, realmente vale la pena vacunarlos? pensando en que los datos de efectos carcinógenos no fueron solicitados, ni entregados? lo cual es un efecto que pudiese ocurrir a largo plazo. 

a mi juicio, estas estadísticas se supone que son fundamentales para tomar decisiones a nivel macro, pero si los datos proporcionados no son confiables, las decisiones tampoco lo serían.

**Comment by daniamr** [comment]
quiero añadir con respecto de lo que dijiste; La documentación aclara que el reporte de casos en producto 89 son casos reportados en la respectiva semana y en producto 90 son casos que iniciaron los síntomas en la respectiva semana (eso despeja mis dudas sobre las diferencias de CASOS en ambos productos)

Si fuer así, no se explicarían las muertes, porque como sería? síntoma de muerte en la semana 32 y se muere en la semana 35? en ambos casos las muertes deberían al menos corresponder por semana no? Realmente no me queda claro ese punto y creo que amerita una revisión...

**Comment by daniamr** [comment]
raro sería que iniciaran los síntomas de muerte semanas antes... y si fuera por desface de fechas, debiese ser similar la cifra a la semana siguiente o subsiguiente no? 

![image](https://user-images.githubusercontent.com/93507862/140180482-eb124615-f2db-484c-b5ab-a181f9499b83.png)

**Comment by elaval** [comment]
@daniamr mi hipótesis (pero no es lo que dice la documentación) es que en el producto 90 se reportan muertes de casos que iniciaron síntomas en la semana respectiva.  Eso explicaría la diferencia en muertes para cada semana entre los productos 89 y 90.   

Muchas de las muertes de pacientes que iniciaron los síntomas ocurren muchas semanas después y distribuidas en varias semanas (incluso muchas todavía no ocurren).  Por eso no es sólo un desfase de "n" semanas exacta sino una distribución diferente.

**Comment by daniamr** [comment]
es una hipótesis, lo que lleva a preguntarse,  si se contagió covid asintomático la semana 30 se puso la vacuna 1 a los 14 días, luego al día 21 la segunda dosis y luego los 14 días para completar el esquema y murió a los 2 días. como estaría categorizado? en la semana 30 o en la semana 37? 

se considera muerte sin vacuna o se considera muerte con esquema completo? hacen seguimiento de esos casos particulares para diferenciar si fue producto de la vacuna o fue por covid? y si no lo hacen, no sería un sesgo como para evaluar la efectividad de la vacuna y sus posibles efectos?

**Comment by daniamr** [comment]
En todo caso, 9 meses de distribución diferente es mucho no?

**Comment by elaval** [comment]
Yo esperaría que en producto 90 se asocie el esquema de vacunación al momento en que iniciaron los síntomas.  Si una persona fallece con 2 dosis, pero al iniciar síntomas no estaba vacunada, se reportaría como no vacunada.

Pero nuevamente ... esto debería quedar muy claro en la documentación para evitar especulaciones

**Comment by daniamr** [comment]
Claro, pero eso no generaria un sesgo?  Porque 9 meses de diferencia entre inicio de sintoma y muerte es mucho. Además, se puede vacunar estando con sintomas? 
 Porque una persona que muere hoy digamos que muere de covid, después de la vacuna de refuerzo, sin embargo, el "inicio" de sus sintomas fueron en marzo?

**Comment by weichafan** [comment]
Ese no es problema, para que DEIS considere una persona fallecida por COVID19 hay parámetros que evitan eso que dices de un tiempo muy largo. Eso está publicado por el minsal en las directrices que entrega la OMS. https://www.minsal.cl/wp-content/uploads/2020/05/Guidelines_Cause_of_Death_COVID-19.pdf

También evitan que una persona que falleció, por ejemplo, en un accidente de tránsito y era confirmado covid19 se lo considere como muerte covid-19.

**Comment by weichafan** [comment]
Creo que el problema está en la redacción de los informes del MINSAL que dan confusión (y debieran estar incorrectos). 
En Métodos se lee: "...para los ingresos a UCI o de defunciones, se presentan los casos cuya fecha de ingreso a UCI o de defunción se encuentra dentro de la SE en cosideración".  Creo que esto sólo aplica a las tablas por edad. 

Sin embargo, en el gráfico c, d, e, f dice "según SE de ingreso a UCI (defunción)", pero los datos son los que muestra el producto 90, menos las últimas 2 semanas (que se leen en el producto 90, pero que no se reportan en los gráficos)... y esos deberían ser por inicio de síntomas, tal como se entiende de la documentación del producto 90.

**Comment by weichafan** [comment]
Estimado @dna33 otra vez parece que el producto 91 parece haberse actualizado con hospitalizaciones y no ingresos a UCI. Y el producto 92 no se ha actualizado.  

Te escribo aquí para no abrir otro issue.

**Comment by daniamr** [comment]
Ok, entiendo, "There should be no period of 
complete recovery from COVID-19 between illness and death"  lo cual según las definiciones son 14 días de no tener sintomas.  Sin embargo, los casos de muertes donde  no son notificados en epivigila el inicio de sintomas (clinicamente) se da por entendido que se busca el ultimo pcr o la primera consulta que pudo haber sido hace 9 meses?  Y de ser así, como saber si era asintomatico o no, la ultima vez que tuvo pcr positivo?  Y que estuvo recuperado en los 14 días? Cuales son los datos. Ademas, donde estan los datos de los reportes Y59.8? Si hay casos que no se están notificando a epivigila de inicio de sintomas,  también tendrán casos que no han sido notificados en Y59.8? Ademas, han hecho seguimiento a esos casos no notificados para determinar si es Y59.8 o efectivamente una complicación de covid por 9 meses? Si es así, donde estan los datos?

**Comment by daniamr** [comment]
" "Fecha de Pesquisa'; Se considera como fecha inicial, la fecha de primera consulta (que pudo ser hace 259 días) y si éste tampoco existiera, es utilizada la fecha de notificación (de que fecha? Pudo ser hace 259 diás?)
Al considerar la fecha de pesquisa de las personas que fallecieron por COVID19 y su fecha de defunción, se observó un 75% de los fallecidos, tuvo al menos  30 días (osea 30 o más) de latencia entre la fecha de pesquisa y fecha de defunción. El máximo de días de latencia, fue de  259 días y el mínimo de 0.

Fuente; INFORME SEMANAL DE DEFUNCIONES POR COVID19
N°29

**Comment by daniamr** [comment]
@weichafan, pero sí es ub problema, dado que estárian diciendo que en la semana 32, específicamente el 11 de agosto cuyo día es el mismo del inicio de vacubació de refuerzo, murieron 2 personas que iniciaron sus sintomas  esa semana.? 

Y el la semana 33, del 15 al 21 de agosto, 14 personas iniciaron sus sintomas y murieron (con vac de refuerzo) a las semanas siguientes? Y eso es cosiderado muerte por Covid? Me pregunto, donde están los datos que indica que hace diferencia entre Y59.8 y covid? 

Cito; "personas pueda arrojar una PCR positiva luego de la vacunación.." 
Fuente; 

https://www.ispch.cl/noticia/el-instituto-de-salud-publica-reitera-calidad-seguridad-y-eficacia-de-la-vacuna-contra-covid-19-y-llama-a-la-poblacion-a-mantener-los-cuidados-para-evitar-contagios/

**Comment by elaval** [comment]
Datos en producto 91 fueron corregidos en commit 5d2436b1453d7853f2796a5735b45339c69a69a4 [https://github.com/MinCiencia/Datos-COVID19/tree/5d2436b1453d7853f2796a5735b45339c69a69a4/output/producto91](https://github.com/MinCiencia/Datos-COVID19/tree/5d2436b1453d7853f2796a5735b45339c69a69a4/output/producto91)

Ahora parecen reflejar promedio diario de ingreso a UCI de pacientes COVID19.  Al transformar el promedio diario a la cifra semanal, se observa diferencia con lo informado para el total de casos con ingreso a UCI en productos 89 & 90 para una misma semana (en la imagen para semana 31)
![image](https://user-images.githubusercontent.com/68602/140500294-d8234d1d-b662-468e-acbb-450b2bd35f0a.png)

**Comment by dna33** [comment]
@elaval, por razones de tiempo no logro entender bien qué queda por resolver de este ticket, agradezco clarificación.

**Comment by elaval** [comment]
Hola @dna33 el problema de fondo es que el producto 89 y el producto 90 hacen referencia a los datos de casos, ingresos a UCI y fallecidos en las distintas semanas epidemiológicas, pero las cifras no calzan con lo indicado en otros productos.

Lo que sería necesario para resolver el ticket (y aclarar las dudas) es una explicación de estas diferencias.

En concreto se requiere aclarar los siguientes puntos

1. Producto 89 informa casos reportados en cada semana epidemiológica, pero reporta cifras a las informadas en el producto 5 (ej un 12,5% menos para la semana 31)
2. Producto 89 informa ingresos a UCI en cada semana epidemiológica, al igual que lo indicado para el producto 90,  pero las cifras de cada semana no calzan entre sí y tampoco calzan con lo informado en el producto 91 (ej en semana 31 se informa 228, 202 y 304 respectivamente)
3. Producto 89 informa fallecidos en cada semana epidemiológica, al igual que lo indicado para el producto 90, pero las cifras de cada semana no calzan entre sí y tampoco calzan con lo informado en el 37 (fallecidos por fecha de defunción) ni producto 5 (fallecidos por fecha de reporte)

Para mi una explicación posible es que producto 90 no informa los datos de ingreso a UCI ni fallecidos ocurridos en la respectiva semana epidemiológica, sino los de fallecidos de entre las personas que iniciaron los síntomas en la respectiva semana epidemiológica (pero eso no está en la documentación).  Si se aclara que esta es una razón de la discrepancia aclararía muchas dudad.

Otra explicación para las discrepancias puede ser que producto 89 en los fallecidos e ingreso a UCI no considera a todos los casos sino que sólo a los mayores de 12 años (pero no podemos comprobar esto ya que los otros productos no incluyen datos por edad).

En definitiva, hay discrepancias en los datos y no se entiende la razón de esta discrepancia.  Una aclaración que lo explique resolvería este ticket.

Saludos Demián!

**Comment by daniamr** [comment]
Hola @elaval , me podrías enviar el detalle?  Para verlo porfa! 

Fijate en la definición de inicio de síntomas, eso equivale a que el esquema de vacunación, se considera del momento desde que se presentaron síntomas clinicamente (las personas sintomaticas)  o que se tomó la muestra (asintomaticos). Eso sale en el minsal 10-11-2021 y además en cada producto (no lo aclara en el 89, pero según indica el informe debiese también modificar el esquema de vacubación según la variable inicio de síntoma)

También semana epidemiológica inicio de sintomas, por lo que pondrán la semana en que inició losnsintomas y no la que murió o ingresó a uci. 

Ahora tienes un número indeterminado de fecha pesquisa; aquellos que no tienen información, asique lo ven como la primera consulta o muestra, que pudo tener una latencia de tiempo de 0 a 259 días. Ergo, pudo haber cambiado su esquema de vacunación. 

Por tanto, mi teoria es que el producto 5 lleva cuenta de los recuperados, y difiere de los demás productos, debido a la fecha pesquisa (inicio de síntomas desconocido para epivigila, fue tomada una fecha de 9 meses atrás por no tener los datos), pudiendo pasar por alto los recuperados.

**Comment by elaval** [comment]
@daniamr puedes ver el detalle de mis comparaciones en esta página https://observablehq.com/@elaval/chequeo_datos_casos_uci_fallecidos

**Comment by ox217** [comment]
Buenas tardes.

Meses después compartimos las mismas interrogantes que @elaval. Hay clara inconsistencia en los primeros meses, por ejemplo, al calcular los muertos totales acumulados durante los primeros meses usando el producto 90 y los acumulados usando datos del https://www.gob.cl/coronavirus/cifrasoficiales/, estos difieren.

Hay alguna explicación de por qué pasaba esto? @dna33.

Saludos.
