### ISSUE TITLE
DIFERENCIAS PRODUCTO 89 Y 90 + DUDAS DEFINICION VARIABLES

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1147]
Hola, quiero hacer la siguiente observación para que también sea aclarado.

Quise hacer una comparación con el producto 89 "Incidencia de casos según estado de vacunación, grupo de edad, y semana epidemiológica." y 90 DP - "Distribución de casos según antecedentes de vacunación y semana epidemiológica", ya que no figura la incidencia de casos, uci y muerte diferenciado por grupo etario, semana y estado de vacunación (sin vac, 1 dosis, 1 dosis unica, 2 dosis, 2 dosis mayor a 14 días, refuerzo) 

 Sin embargo, me encontré inconsistencias y me surgieron varias dudas; 

Revisé dentro de la semana epidemiológica 31 a 41 de ambos productos 89 y 90, y lo que me figuró fue lo siguiente; 

Hay diferencias cada semana de las 10 (31 a 41), tanto en casos COVID, como uci y muertes. A continuación, el detalle;

Producto 
producto 89 total muertes (semana 31 a 41): 1463
producto 90 total muertes (semana 31 a 41): 596
Total, diferencia 867, de los cuales 486 corresponden a esquema completo. 

eso es una diferencia del 57% en 10 semanas de muertes para el esquema completo. 

producto 89 total muertes con dosis de refuerzo: 21
producto 90 total muertes con dosis de refuerzo: 30 
total, dif: 9 
* en este punto es importante recalcar que en el producto 90 menciona que la semana 32 hubo 2 muertes y 14 muertes en la semana 33, sin embargo, en el producto 89 menciona que de la semana 31 a 34 no hay muertes. y en la semana 35 dice que hay 6, en la semana 36 dice que hay 7.

producto 89 total casos COVID (semana 31 a 41); 97822
producto 90 total casos COVID (semana 31 a 41): 49.612
total, diferencia: 48.210, de los cuales 39.701 corresponden a esquema completo.  

eso es una diferencia del 59% en 10 semanas del esquema completo….  osea del total de diferencia el 82% le corresponde solo a esquema completo. 

producto 89 total UCI: 1310
producto 90 total Uci 1113
Total, dif: 197, de los cuales; 169 corresponden a esquema completo que faltarían en el producto 90, 37 esquema incompleto que faltarían en el producto 90 y 9 refuerzo que sobrarían en el esquema completo, dentro de las semanas 31 a 41.  

Además, tengo dudas respecto de la definición de las variables del producto 90;

cito; 'sin_vac_fall' indicando el número de casos confirmados que fallecieron de COVID-19 durante la semana epidemiológica correspondiente y que al iniciar síntomas (sintomáticos) o al momento de la toma de muestra (asintomáticos) no ha recibido ninguna dosis de vacuna.

por lo que se entiende, podría darse el caso que una persona dio positivo a COVID asintomático, hizo sus 14 días de cuarentena, a los días de hacer su cuarentena se puso la vacuna, ejemplo al día 20, y al día 22 murió, eso se considera muerte por COVID, ya que cabe dentro de la definición. 

Por lo que mi duda es, como saben a esos casos para saber si fue efecto de la vacuna la muerte o fue efecto del covid, ¿si por definición de la variable sería solo covid?  se hace un estudio especial o solo se asume, y de hacer un estudio especial, donde están los datos? eso no alteraría la indagación para saber la incidencia respectiva de la vacuna vs no vacuna? 

cito; 'sin_vac_casos' indicando el número de casos confirmados durante la semana epidemiológica correspondiente, y que al iniciar síntomas (sintomáticos) o al ****momento de la toma de muestra (asintomáticos) n**o ha recibido ninguna dosis** de vacuna.

cito; 'una_dosis_casos' indicando el número casos confirmados durante la semana epidemiológica correspondiente, y que al **iniciar síntomas (sintomáticos**) o al momento de la toma de muestra (asintomáticos) han recibido la primera dosis y no la segunda dosis, en un esquema que incluye dos dosis,

hablan solo de la semana epidemiológica para revisar el tiempo, sin embargo, no me queda claro si pudiera haber casos que dieron positivo, por ejemplo, la semana 20 (¿hicieron su cuarentena y luego se pusieron la vacuna la semana 23, y después de la vacuna iniciaron los síntomas, se considera como caso COVID sin vacuna o como caso de vacuna 1 dosis? 

Vale decir, ¿estaría dentro de la semana 20 o la semana 23?  y ¿cómo saber que el inicio de los síntomas no fue producto de reacción frente a la vacuna? ¿le hacen seguimiento? si es así, donde están los datos? 

Además, siendo que el producto 89, no considera a los menores de 6 años, ¿cómo puede tener más casos, si el producto 90 no considera el rango etario? 

Otra duda es; basándose solo en el producto 90, ¿Cómo se explica que el total de Uci de esquema completo semana 1 a 41 sean 2634 y total de muertes de semana a 1 a 41 sean 4247?  

además en el producto 89, como se explica que de un total de 748 en UCi de personas con esquema completo de la semana 31 a 41 existan  850 muertes de personas con esquema completo? 

Porque se podría entender de que van menos a UCI pero mueren más?  

El misal usó como referencia el producto 90 y 89 con fecha de 20-10-2021 en su informe de vacunas para hacer gráficos, sin embargo, ambos productos no conversan y tampoco figura las fechas en ambos productos para aclarar y aunque fuera el caso de descuadre de semana, las muertes con las dosis de refuerzo son más en el producto 90 que en el producto 89, lo que haría una diferencia en la incidencia que muestran en los informes epidemiológicos basados en el producto 89. Esto pensando que en el producto 89 solo figuran desde la semana 35, y en el otro desde la semana 32 (2 muertes) y en la semana 33 (14 muertes), ya que en la semana 35 la población de 423 ccon0 casos, y bien distinto sería con 6 personas vacunadas es diferente la incidencia.  o con 22 personas muertas sobre 423 de población. No queda claro. 

ejemplo; la diferencia sería lo que le faltaría al producto 90, por tanto, al gráfico establecido en el informe epidemiológico fecha 20-10-2021 figuras separadas esas dos variables (pero las diferencias están, ya que al sumar los números indicados en el gráfico corresponden al producto 90 y se cita abajo ese producto. Además, eso hace que la curva del gráfico se vea diferente, como si hubiera una disminución de casos desde la semana 31 a la 41, más de lo que correspondería.  Entonces, si faltan agregar esos 48.210 casos, el grafico mostrado en el informe epidemiológico estaría incorrecto y si el producto 90 está en lo correcto, la incidencia del producto 89 estaría incorrecto. Como se explica eso? 

A CONTINUACIÓN, SOLO LA DIFERENCIA ENTRE EL PRODUCTO 89 Y 90 DE CASOS COVID DE PERSONAS CON ESQUEMA COMPLETO; 

![image](https://user-images.githubusercontent.com/93507862/140165807-d0f07d38-7fbd-4bc9-8c4d-d6f5f1f6fe9c.png)

y la última consulta, aprovechando, porqué no se piden y las farmacéuticas no entregan antecedentes de los estudios respecto a si genera efectos carcinógenos y/o de infertilidad respectivamente como indica el informe de SOFARCHI? esos datos no hubieran sido favorables para obtener un análisis costo beneficio? 

Cito: Pfizer
![image](https://user-images.githubusercontent.com/93507862/140168094-1f30995f-1430-4736-b3a3-cf18fa15d2e2.png)

Cito Sinovac:
![image](https://user-images.githubusercontent.com/93507862/140168308-962b80a6-db4d-48a6-a941-6e9b183c9fff.png)

quedo atenta.

**Comment by daniamr** [comment]
Además, quisiera que me aclararan lo siguiente; 

Cito; En la base de datos de Epivigila, **se consigna la información relacionada al inicio de síntomas.**  Cuando este dato no pudo ser rescatado, **se considera como fecha inicial,** la fecha de **primera consult**a; y si éste tampoco existiera, es **utilizada la fecha de notificación**, esta fecha se denominará "Fecha de Pesquisa'.  

Al considerar la fecha de pesquisa de las personas que fallecieron por COVID19 y su fecha de defunción, se observa un ... 
 El 25% de las personas tuvo una latencia de al menos  8 días (Primer Quartil) y un el 75% de los fallecidos, tuvo al menos  30 días de latencia entre la fecha de pesquisa y fecha de defunción. 

**_**El má**_ximo de días de latencia, fue de  259 días y el mínimo de 0._****_**  ¿
Fuente: informe semanal defunciones DEIS N°38 fecha 4 de marzo 2021.

¿HAY PERSONAS QUE ESTUVIERON CON SINTOMAS COVID POR 9 MESES?  

Vale decir, una persona que le notificaron que tenía Covid, con síntomas muy leves en la semana 20,  luego para  la semana 40 se vacuna y logra su esquema completo, a la semana siguiente tiene síntomas covid más fuertes, pero no se hace pcr, si no cae directamente en UCI o muere directamente por covid con inicio de síntomas de la semana 20? 

Entonces esa persona que pasó 20 semanas (5 meses)  con "sintomas Covid" fallece, queda en la semana 40; como muerte con esquema completo o en la semana 20; como muerte sin vacuna?  

Parece que hay un sesgo ahí con el tema de la vacuna, lo cual podría relacionarse con la menor cantidad de UCI en esquema completo en relación a la cantidad de muertes.

Ósea,  hay personas persona que se contagiaron en julio del 2020, fallecieron en marzo del 2021?  

no se esclarece cual es la cantidad de estos casos, solo menciona que el 75% murió después de los 30 días, para lo cual de un máximo de 259 días, quizás debiesen haber sido más específicos no?

**Comment by MinCiencia** [comment]
Hola, este no es el lugar que corresonde para contestar preguntas sobre el DEIS.

**Comment by daniamr** [comment]
@MinCiencia  y a quién le podré preguntar?

No se enojen tanto, son solo preguntas.

**Comment by MinCiencia** [comment]
Hola, no estamos enojados, pero si tenemos poco tiempo y es poco considerado de su parte la forma de preguntar, en cantidad, cuidado del lenguaje, redacción, etc.

**Comment by ctroncoso** [comment]
Cierto, es importante considerar que este es un ambiente colaborativo.  Podremos estar disconformes con los datos, pero hay que considerar que estamos del mismo lado. Encontrar como proveer información de la forma mas clara y oportuna posible. 

Si hay errores, en lo posible, revisar la automatización que genera el reporte, verificar el código, los archivos fuentes y si puede y logra encontrar el error, comunicarlo. 
Principalmente no considerar que esto es un menú de pedidos. El esfuerzo es enorme y muy proclive a errores, y nuestro trabajo, como ciudadanos es, si hay errores, ayudar a corregirlos. 

Temo que esta área se ha convertido en una sala de chat para tratar temas ajenos a errores en el repositorio. @MinCiencia, recomendaría que se abriera un DISCORD donde se puedan tratar temas como este entre usuarios, y limitar la zona de issues a su función principal que es la de resolver problemas de repositorio.

**Comment by daniamr** [comment]
@MinCiencia, ok, entiendo que a veces prima fijarse en la forma en vez del fondo. Me parece discriminatorio y poco considerado tu comentario.  Solo son preguntas. Y por lo demás,  "parte la forma de preguntar, en cantidad y falta de orden, cuidado del lenguaje, redacción, etc" es una falacia pensar que eso se debe a poco consideración hacia ustedes.

**Comment by daniamr** [comment]
@MinCiencia además, me encantaria hacer algun discord o algo.

**Comment by ctroncoso** [comment]
Creo que un discord para que la comunidad asista a la comunidad (CA) puede ser más práctico, y liberamos este espacio para temas de origen de datos y estructura de repositorios. 

> @MinCiencia, ok, entiendo que a veces prima fijarse en la forma en vez del fondo. Me parece discriminatorio y poco considerado tu comentario. Solo son preguntas. Y por lo demás,  "parte la forma de preguntar, en cantidad y falta de orden, cuidado del lenguaje, redacción, etc" es una falacia pensar que eso se debe a poco consideración hacia ustedes.

Es cierto que son solo preguntas, pero hay que cuidar el tiempo del otro.  La forma en que realizan las preguntas son importantes en una comunidad. Mantenerlas cortas, precisas y acotadas es una forma de mostrar respeto por el tiempo del otro. En los personal solo pregunto cuando ya he agotado el 100% de mis posibilidades, y hasta de pensarlo dos veces.  Entiendo que no están para resolver mis problemas, sino que todos estamos para resolver los problemas de todos. 
Por ejemplo, si se detectan inconsistencias graves, puede que sea mejor formar un equipo con miembros de la comunidad, primero para verificar que exista inconsistencia, y segundo, hacer un fork y ofrecer una solución.  De lo contrario los issues se convierten en una plataforma de servicio al cliente, que no lo es. No somos clientes. 

Espero que no lo tome a mal. Lleva tiempo acostumbrarse a trabajar en linea con equipos que pueden llegar a tener 600 o más miembros, y tal vez por falta de experiencia no se daba cuenta que estaba tocando el timbre con mas insistencia que lo aceptable.

**Comment by daniamr** [comment]
Sí, me parece lógico. Yo también he invertido mucho tiempo en esto. El valor del tiempo invertido no creo que sea solo unilateral y creo que sería ofensivo que digas que mi tiempo vale menos que los demás. También creo que es horrible de parte de ustedes el hecho de que tener más dudas o inquietudes que otros, se etiquete como "tocar el timbre con más insistencia de lo aceptable".  

Tampoco creo que sean servicio al cliente, no pongas palabras que yo no he dicho. Ustedes son los expertos no? Hasta donde sé, se le pregunta a los que saben.

**Comment by ctroncoso** [comment]
> @ctroncoso Sí, me parece lógico. Yo también he invertido mucho tiempo en esto. El valor del tiempo invertido no creo que sea solo unilateral y creo que sería ofensivo que digas que mi tiempo vale menos que los demás. También creo que es horrible de parte de ustedes el hecho de que tener más dudas o inquietudes que otros, se etiquete como "tocar el timbre con más insistencia de lo aceptable".
> 
> Tampoco creo que sean servicio al cliente, no pongas palabras que yo no he dicho. Ustedes son los expertos no? Hasta donde sé, se le pregunta a los que saben.

Espero que lo tomes como un aprendizaje. 
Soy tan ciudadano común como tú y la gran mayoría de los que participan acá. Cero relación con minsal o minciencia más que las ganas de ser un aporte y que ese producto le sirva a todos. 
Te insisto que trabajar en comunidad tiene sus lineamientos de convivencia. Toma las señales. La comunidad estará más propicia a ayudarte y responder preguntas.

**Comment by daniamr** [comment]
@ctroncoso sí sé, recuerdo que me lo habías mencionado anteriormente que eras un cuidadado como yo. Cuando me dijeron que podían hacer un discord, yo acepté feliz. Quizás les parezca más simpática por Discord 🤔
