### ISSUE TITLE
Actualización Producto 37

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1149]
Estimados,

No es primera vez que informo que el producto 37 está actualizado según la cuenta del Ministerio de Ciencias en twitter, pero en la práctica no es así. 

Lo adecuado es que las problemáticas que se levanten y cierran, no vuelvan a pasar.

Sugiero hacer mejoras urgentes en la gestión de la reportabilidad, más seria y no excusarse en que están en otros proyectos para no gestionar y corregir de forma oportuna. 

Lo anterior lo menciono también, ya que existen varios Issues en que estos, no les toman el peso correspondiente además de ir solicitando resumenes de los issues, dilatando con ello tener registros correctos para toda la comunidad que depende de este repositorio.

Si tienen inconvenientes de apoyo técnico de profesionales que estén 100% trabajandi en este repositorio escalen la problemática y denla a conocer.

![Screenshot_20211104-161022_Twitter](https://user-images.githubusercontent.com/69001461/140407198-c69437c7-55f1-4caf-b9f6-5fcfd1677eb9.jpg)

**Comment by dna33** [comment]
Hola, a veces suben los archivos de forma incompleta, el esquema para subrilos es de microservicios, pero el tuiteo es 1 para todos, entonces pasa que avisa actualizaciòn y algunas veces el microservicio relacionado con las defunciones deis, no hizo la pega. 

Quizàs, como eres un usuario màs avanzado, puedes programarte una manera de que te notifique cuando actualiza la carpeta producto37.. asi no sufres con esto.

saludos,

Demiàn

**Comment by dafernandez75** [comment]
Demian, cerraste el Issue pese a que no se ha actualizado el Producto 37 con los datos actualizados, ni con los sospechosos de la semana pasada ni con los confirmados indicados hoy por el Minsal.

**Comment by dna33** [comment]
d0d49443db30057ccefc875b78771f07790c0c90
bcc44e362b517e8ac26a3231f8ea9a9e6490397c

**Comment by dafernandez75** [comment]
Ahora sí, recién actualizado. Saludos 
![deis](https://user-images.githubusercontent.com/69001461/140434628-de08ae9d-7e8e-4a4a-907a-6d6686115b6b.png)
