### ISSUE TITLE
Infectados Asintomáticos del 29-04 están contados en los Infectados Acumulados del 30-04

### ISSUE THREAD

**Issue by nvalenzuelaf** [MinCiencia/Datos-COVID19#115]
Hola, en el producto:

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/CasosTotalesCumulativo.csv

Están contando los infectados asintomáticos del día 29-04 (que corresponden a 250 para la Región Metropolitana) dentro de los casos acumulados del 30-04 (para la RM, los acumulados del día 29-04 tienen 250 menos casos y los acumulados del día 30-04 tienen 250 más casos).

**Comment by javierconcha** [comment]
Hola,
Tomé la decisión de incluir esos casos en Santiago para que la matemática cuadrara. Acá va mi razonamiento:

- Primero que todo, producto 3 es una tabla de "Casos Totales Acumulados", y no hace la distinción de casos con o sin síntomas. 

- Los casos totales del día 28 son 14365. Los casos nuevos del día 29 son 520+250=770. Por lo tanto los casos totales que debieran reportarse el día 29 son 14365+770=15135 y no los 14885 reportados en la tabla (al menos la última que logré salvar). 

- Para que esto sea el caso, los 250 que aparecen en "Casos nuevos sin síntomas" debieran haber sido asignados a Santiago, y así los "Casos totales acumulados" sumen 15135, i.e. (272+183+514+42+76+526+(8639+250*)+104+392+761+719+1273+182+481+7+714)=15135.

- Por lo tanto, los casos totales para la Region Metropolitana para el 29: (8639+250*)=8889

**Comment by javierconcha** [comment]
Hola. 
Creo que esto estaría relacionado con #117.
@nvalenzuelaf , segun tu, cuales debieran ser los reportados para la RM el 29, 8639 ó 8889?

**Comment by nvalenzuelaf** [comment]
Hola Javier,

Es como lo dices tú en #117 , el día 29 deberían haber 8889 en la Región metropolitana. 

Saludos y gracias.
