### ISSUE TITLE
ACLARACION U07.1 y 0.2 CON MUERTOS 

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1151]
Quisiera saber, cuanto de los 16 muertos del producto 90 corresponden a muerte por Covid U07.2 con esquema de refuerzo. Cuyo inicio de sintomas fue en; 

Semana 32: equivalente a 2 muertos.
Semana 33: equivalente a 14 muertos. 

No se especifica la variable fallecidos por vac de refuerzo si es o no confirmado. Y si se consideraron solo los U07.1, cuantos fallecieron con U07.2 e iniciaron sus síntomas en la semana 32 y 33? 

Quedo atenta.

**Comment by ctroncoso** [comment]
El análisis tendrías que realizarlo. Acá solo vas a encontrar los ingredientes de la torta. 
Para los fallecidos y causa de muerte, te recomendaría el listado del deis publicado semanalmente en [Datos Abiertos 
](https://deis.minsal.cl/#datosabiertos).
Lamentablemente no hay forma aún para unir fallecidos con su esquema de vacunación, ya que eso requeriría conocer sus RUT, y eso vulnera la ley de privacidad. 
En FONASA hay publicación de los egresos hospitalarios del 2019 y 2020. Se espera que a futuro se publiquen los de 2021. En condición de egreso, podrías filtrar por "fallecido"  y quienes tengan Diagnóstico U07.X.  Con eso podría tener los RUTS encriptados y consultar por el estado de vacunación de esos via transparencia. 
Como ves, no es una ruta simple,

**Comment by daniamr** [comment]
Pero independiente a los rut, podrán llevar una cuabtificacion de eso, osea dar a conocer el número sin el rut?  Digo, por transparencia no? 

Además que la variable U07.2 la cual se define; 
COVID-19, virus no identificado
Utilice este código cuando se diagnostique COVID-19 clínica o epidemiológicamente, pero las pruebas de laboratorio no sean concluyentes o no estén disponibles. Use código adicional, si lo desea, para identificar neumonía u otras manifestaciones. 
 
No es lo mismo no concluyente que no disponible. Como se define no disponible? 

Existe una separación de esas variables o un recuento de eso?

**Comment by daniamr** [comment]
Una ruta bien escabrosa para datos que parecen importante, que podrían incluso comprometer la validez o la medición de la eficacia no?

**Comment by daniamr** [comment]
Osea me refiero, que podrían llevar una estadistica similar, semana epidemiologica con fecha de incicio de sintomas, de casos u07.2, separado por esquema de vacunación. Osea en el producto 61 al menos separa, pero por comuna y ponen fechas, que se da  cada 4 dias, lo cual hace más dificil hacer le cuadre y traspasarlo a semana epidemiológica.. pero no está por inicio de sintomas, ni tampoco está por estado de vacunacion (sin, 1, 2, comp o refuerzo... 

Porque no me queda claro, como saben que 14 muertos tuvieron fecha de inicio de sintomas la semana 33, si no es por algún codigo o por algún rut?

**Comment by daniamr** [comment]
Además, si llevan registro de las personas vacunadas ( con el qr) también tienen las fechas de vacunación. Se pudo haber puesto un código o algo para unirlas y así hacer una revisión, según fecha de vacunación. Y así esclarecer casos posibles de estudio para ver si fue efecto o no de la vacuna, y de ser así, sacar esos casos de la estadística y hacer un cruce con ESAVI...

**Comment by daniamr** [comment]
Hola @ctroncoso oye sacame de una duda entonces...como el minsal puede aseverar la tasa de mortalidad de covid según el estado de protección vacunal, si  "lamentablemente no hay forma aún para unir fallecidos con su esquema de vacunación"?

**Comment by ctroncoso** [comment]
Minsal tiene los datos completos. Pueden hacer el cruce. 
Somos nosotros somos los que no tenemos esa información. 
Es muy complicado y nebuloso el límite entre cuanto informar y cuando ya estás vulnerando la privacidad de otros. 
Hay mucho prejuicio y mal uso que se le puede llegar a dar a la información de hacerse pública sin algún tipo de ofuscación.

**Comment by daniamr** [comment]
Pero ellos los cita a ustedes, específicamente al producto 89 para decir cuál es la tasa de mortalidad....  dato que ustedes no tienen  como para unir fallecidos con su esquema de vacunación... . 

![image](https://user-images.githubusercontent.com/93507862/140588167-6f74f39a-8504-432b-bcf7-753b21934776.png)

Y si el  Minsal puede hacer el cruce, podrá hacer una tabla con esos datos, evidentemente sin tener que revelar los datos personales..

**Comment by ctroncoso** [comment]
ojo.. yo soy tan ciudadano como usted, no tengo relación con minciencia ni con este repositorio, como también lo son la mayoría de los que usamos y comentamos por acá. 

El minsal ES la fuente de información y si, tiene mas acceso que nosotros, y hasta el minciencia. 
Ellos hacen el cruce y entregan el resultado para que sea publicado acá. 

Por eso, la FUENTE es MINSAL, pero la serie de tiempo resultante es la de github/minciencia.

**Comment by daniamr** [comment]
Entonces, le podrán pedir entonces al Minsal esos datos para hacer el cruce? ya que ellos los tienen.. me refiero claro está al cruce, no a la información personal de cada persona... 

Además, tendré que esperar la respuesta de una persona oficial de minciencia, para saber si disponen de los datos de mi pregunta inicial, ya que tu no tienes relación?

**Comment by ctroncoso** [comment]
> Entonces, le podrán pedir entonces al Minsal esos datos para hacer el cruce? ya que ellos los tienen.. me refiero claro está al cruce, no a la información personal de cada persona...
> 
> Además, tendré que esperar la respuesta de una persona oficial de minciencia, para saber si disponen de los datos de mi pregunta inicial, ya que tu no tienes relación?

ya la hemos pedido sin resultados.

**Comment by daniamr** [comment]
Enserio?? Pero la han pedido a traves de transparencia? 

Gracias por responder en todo caso..

**Comment by daniamr** [comment]
Y por lo demas, lo que tu dices si no han dado respuesta, es una suposición que la fuente sea minsal y hagan el cruce internamente...  suposición que habria que aclarar no?

**Comment by ctroncoso** [comment]
> @ctroncoao Y por lo demas, lo que tu dices si no han dado respuesta, es una suposición que la fuente sea minsal y hagan el cruce internamente... suposición que habria que aclarar no?

si hubo respuesta, pero sin resultado. Se indicó que se haría publica cierta información, que es la que está en la zona de fonasa, pero que no corresponde al período solicitado (2019-2020). Tampoco se cruzó la información con vacunados ni se implementó un metodo para entregar la información en forma semanal. 
Pero que hubo respuesta, si hubo, no la que fue solicitada.

**Comment by daniamr** [comment]
@ctroncoso y en esa respuesta me podrías decir donde o dar el link, está para revisarla?

**Comment by ctroncoso** [comment]
No son muy útiles los links ya que no tienen nada aparte del número de solicitud. Las respuestas se envían por mail. 

Solicitud: https://www.portaltransparencia.cl/PortalPdT/escritorio-ciudadano?codigo=AO001T0014319
Reclamo por no respuesta: https://extranet.consejotransparencia.cl/Web_SCW2/Paginab/FichaCaso.aspx?ID=52017

**Comment by daniamr** [comment]
@ctroncoso Gracias! Lo revisaré, de todas maneras me acabo de responder sola a mi pregunta, pero esperaré la respuesta oficial, ya que es solo una suposición mia.

**Comment by dna33** [comment]
Hola, cuál es la pregunta en este issue, qué queda sin contestar, @daniamr ?

**Comment by daniamr** [comment]
En el producto 90, no define la variable esquema de refuerzo según inicio de sintomas, no queda claro si son covid confirmados.

**Comment by MinCiencia** [comment]
Hola, acorde al readme.md del producto, se toma la fecha de inicio de síntomas para asociarlos a la semana epi. 

El archivo 'incidencia_en_vacunados.csv' contiene las columnas

> 'semana_epidemiologica' que corresponde a la semana epidemiologica del año 2021 según el inicio de síntomas,

**Comment by daniamr** [comment]
Sí, pero no queda claro si pudieran ser confirmados o probables. (Debiesen ser confirmados según la lógica del readme)

**Comment by MinCiencia** [comment]
Hola, el archivo tiene distintas columnas, pero los casos se clasifican por su fecha de inicio de síntomas en la semana correspondiente.

**Comment by dna33** [comment]
Hola  @daniamr, entiendes lo que te estan explicando o necesitas más info-diálogo? Saludos

**Comment by daniamr** [comment]
@dna33 sería buenísimo!

**Comment by daniamr** [comment]
@dna33 coordinemos una!
