### ISSUE TITLE
PRODUCTO 89 SEPARACION DE ESQUEMA INCOMPLETO+ DUDA DEFINICION DATOS

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1152]
Hola, quería saber si tienen los datos por separado de esquema incompleto ( sin vac, 1 dosis, 2 dosis, etc) ? Y desde la SE 1? 

Además, quiero entender, la categoría esquema completo o incompleto sobre qué definición se hace? Se considera a los no notificados, para determinar el esquema? 

Osea alguien murió después del esquema completo, cuyo inicio de sintomas no se tienen datos, se considera la primera consulta que fue hace 200 días atras, queda como no vacunado? 

O solo se considera el tipo de esquema al momento de morir? 

La variable solo habla del estado de vacunación ,  que da a suponer que ea al momento de morir, pues no lo relaciona con el inicio de sintomas, prefiero corroborarlo. 

Quedo a la espera.

**Comment by dna33** [comment]
Hola, voy a contestar por partes. A la primera pregunta, esto no te sirve? https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto90

**Comment by daniamr** [comment]
No, porque está se entiende que se categoriza de manera distinta. 
En el caso del producto 90, según la definición de la variable semana epidemiologica coml sintoma, se entiende que si una persona murió con fecha en semana 40, pero "inició sus sintomas en la 30" la contabilización del muerto se pone en la semana 30. Lo cual generaría 2 efectos; 1; que no corresponde la muerte a la semana epidemiologica real y 2; que el esquema de vacunación cambia según inicio de síntoma en casos pcr positivo pero no notificados en epivigila.

**Comment by daniamr** [comment]
Por eso, se entiende en la tabla 89, se mantiene la contabilización de muertos segun SE real, sin embargo no queda claro si el esquema de vacunacion está modificado según el inicio de sintomas, sobre todo en aquellos casos no notificados..

**Comment by daniamr** [comment]
@dna33  por lo que se entiende, es el estado de vacunacion a la hora de morir. Pero quiero corroborarlo.

**Comment by daniamr** [comment]
@dna33 quisiera saber, cono cuanto tardan en responder?

Quedo atenta.

**Comment by dna33** [comment]
hola, depende de que tan bien planteada esté la pregunta, y luego de que tan simple sea contestar. Revisamos todos los días y vamos contestando en la medida de lo posible.

**Comment by daniamr** [comment]
Ok gracias!

**Comment by daniamr** [comment]
@dna33 oye estuve viendo que hay algunas preguntas que están desde marzo. Vale decir, se pueden demorar 7 meses en contestar?

**Comment by dna33** [comment]
hola, claro, yo coordino al equipo que contesta. Tienes alguna duda relacionada con alguna de ellas? En general la tasa de cierre o respueta, es 5 veces mayor que la tasa de apertura. Pero hay algunas preguntas mal planteadas, o para las que no hay respuesta también.

**Comment by daniamr** [comment]
@dna33, pero al menos responden si esa pregunta no se entiende o que no hay respuesta para eso? Como saber, digo, porque si no se entiende, así se puede explicar, o si ustedes no tienen la respuesta, al menos saber a quien dirigirse y que sí tenga la respuesta. 

Realmente me urge aclarar todas las dudas que les he puesto.

**Comment by dna33** [comment]
No se entiende lo que dices ahora, lo que dices más arriba, te sugiero plantear tu pregunta al lugar que te indiqué en el mensaje anterior. Yo no tengo información para contestarte, porque no hago investigación epidemiológica, mi foco es disponibilzar los resultados del trabajod e ese equipo en este github. Suerte.

**Comment by dna33** [comment]
si, contestamos. Me confudí en la respuesta anterior que borré, porque pensé estaba en otro de los issues que has abierto ultimamente. Saludos. Y en este issue yendo a tus preguntas originales:

> Hola, quería saber si tienen los datos por separado de esquema incompleto ( sin vac, 1 dosis, 2 dosis, etc) ? Y desde la SE 1?

El producto 90 tiene esa separación, mas no por rango etario. No contamos con más información hecha pública por Minsal, el camino ahi es solicitar esa información a ese ministerio.

> Además, quiero entender, la categoría esquema completo o incompleto sobre qué definición se hace? Se considera a los no notificados, para determinar el esquema?

Asumo la pregunta es relativa al producto 89, cito el readme del producto `estado_vacunacion: corresponde al estado de vacunación la que se clasifica en "con esquema completo" para aquellas personas que han sido inoculadas con dos dosis y han transcurrido más de 14 días desde su segunda inoculación o han recibido una vacuna de un esquema de vacunación que incluye únicamente una sola dosis y han transcurrido más de 28 días desde la inoculación. Esta variable toma el valor "sin esquema completo" si las personas no tienen un esquema completo de vacunación.`

> Osea alguien murió después del esquema completo, cuyo inicio de sintomas no se tienen datos, se considera la primera consulta que fue hace 200 días atras, queda como no vacunado?

No se entiende la pregunta

> O solo se considera el tipo de esquema al momento de morir?

Cito, nuevamente, la documentación del producto -  `'estado_vacunacion' corresponde al estado de vacunación la que se clasifica en "con esquema completo" para aquellas personas que han sido inoculadas con dos dosis y han transcurrido más de 14 días desde su segunda inoculación o han recibido una vacuna de un esquema de vacunación que incluye únicamente una sola dosis y han transcurrido más de 28 días desde la inoculación. Esta variable toma el valor "sin esquema completo" si las personas no tienen un esquema completo de vacunación.
`
