### ISSUE TITLE
Nuevas defunciones (P37) no fue procesado por reporte diario. No se actualizó archivo de origen.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1153]
Hola!
Proceso de update de reporte diario corrió bien, pero no generó el PR37. El archivo de origen no estaba actualizado.
```/input/NuevaDefDefunciones/DefuncionesDEIS.csv``` 
¿No estaba en el FTP?

**Comment by dafernandez75** [comment]
Hola Carlos,
Supongo que deben estar esperando la actualización del Deis (DatosAbiertos), ya que tampoco está actualizado.
Para tener el Producto 37 con los U071,U072,U099. Saludos.

https://deis.minsal.cl/#datosabiertos

**Comment by ctroncoso** [comment]
Debe ser eso. Aguantar un rato. Gracias. !

**Comment by dafernandez75** [comment]
lo acaban de actualizar pero solo los u071. saludos.
