### ISSUE TITLE
FECHA PESQUISA / ESTADO DE VACUNACION

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1156]
Tengo dudas con respecto; 

Quiero poder saber; 

1. Cuantos muertos hay de casos confirmados (pcr positivo) hay con fecha pesquisa? Y cambiaron de esquema de vacunación (según inicio de síntoma)? Y a que esquema de vacunación cambiaron (sin, 1, 2, 2 compl etc)  
( no segrega ni tampoco da cuenta de si cambiaron de estado de vac.)  Y considerando, la definición de la variable en el producto 90,  el cual se entiende que se considera el esquema según inicio de sintoma, por cuanto, aunque esté vacunado, se considera no vac porque inició sus sintomas antes de la vac, pero en la fecha pesquisa se considera la muestra (no indica cual que pudo haber sido hace 9 meses atrás) o la primera consulta, que pudo haber sido hace 9 meses atrás).

Y de esos muertos confirmados con fecha pesquisa, según que fecha se considera positivo (al morir o al inicio de sintomas (primera consulta o muestra)? 
Osea, consideran la toma de muestra que pudo ser hace 9 meses atrás como positivo o el pcr de la muerte? 

2. Cuantos casos hay de muestra inconclusa segun estado de vacunación (sin, 1,2 2 compl etc) ? Y de esos casos, cuantos hay con fecha pesquisa según estado de vac (sin, 1 2 etc) ?  Y cuantos cambiaron de esquema de vacunación? 

Quedo atenta. 

Gracias.

**Comment by daniamr** [comment]
Hasta ahora solo he podido recabar esos datos relacionados; 

el 20% de  los casos del 2021 corresponden a covid no identificado u072, vale decir 5.499. 

hay 4.059 muertes más que el 2021,  un 20% más de muertes covid confirmado , de los cuales se ve un aumento en todos los trimestres, especialmente en el 2 y 3, vale decir de la semana 15 a la 30. 

Entre la semana 15 el 45% ya estaba vacunada con primera dosis,  28 a del 2021 el 86% de la población ya estaba vacunada con la primera dosis.


![image](https://user-images.githubusercontent.com/93507862/140632071-b36471fe-7e1e-479f-b93c-8e90d98be419.png)

**Comment by dna33** [comment]
La diferencia clave que tienes que considerar es que el producto 90:

`- 'semana_epidemiologica' que corresponde a la semana epidemiologica del año 2021 según el inicio de síntomas, `


para el producto 89:

`- 'semana_epidemiologica' que corresponde a la semana epidemiologica del año 2021, `

**Comment by daniamr** [comment]
@dna33, si lo leí, quiero saber respecto de la fecha de pesquisa, de inicio de síntomas. Cuantos  muertos cambiaron de estado de vacunación en el producto 90, segun la fecha de pesquisa.

**Comment by MinCiencia** [comment]
Hola, @daniamr. Disculpa la demora en contestar. ¿qué es "fecha de pesquisa"?

Si na persona lamentablemente fallece, nunca se le hace un PCR estando fallecido, en algunos casos una persona se toma el PCR y fallece antes de obtener el resultado. En tal caso se actualiza retroactivamente.

**Comment by daniamr** [comment]
@MinCiencia 

Cito; En la base de datos de Epivigila, se consigna la información relacionada al inicio de síntomas. Cuando este dato no pudo ser rescatado, se considera como fecha inicial, la fecha de primera consulta; y si éste tampoco existiera, es utilizada la fecha de notificación, esta fecha se denominará "Fecha de Pesquisa'.

Al considerar la fecha de pesquisa de las personas que fallecieron por COVID19 y su fecha de defunción, se observa un ...
El 25% de las personas tuvo una latencia de al menos 8 días (Primer Quartil) y un el 75% de los fallecidos, tuvo al menos 30 días de latencia entre la fecha de pesquisa y fecha de defunción.

El máximo de días de latencia, fue de 259 días y el mínimo de 0
 
Eso figura en los informes epidemiologicos, al menos hasta el 41, donde posteriormente no hacen ninguna referencia al tema, como dando algun cambio a la definición de esa variable.

**Comment by daniamr** [comment]
Entonces según lo que indicas, una persona pudo haber tenido clinicamente sintomas de covid, se sospecha covid U07.2 pero no se verificó a la hora de morir un pcr, entomces se busca un pcr para ver inicio de sintomas, se busca en sistema, tuvo un pcr positivo anteriormente,  según inicio se sintomas ( que pudo ser hace 9 meses atrás) y se considera U07.1?

**Comment by MinCiencia** [comment]
Ajá, entonces fecha de pesquisa puede ser: FIS, Consulta o Notificación en ese orden, dependiendo de si el dato está o no. Gracias por la aclaración.

Respecto de su nueva pregunta, haciendo un esfuerzo por interpretarla, la situación que usted se imagina es bien confusa. Lo que ocurre habitualmente es que una persona se siente enferma y consulta al médico, este le ordena hacerse un examen. En algunos casos la persona podría lamentablemente fallecer antes que el resultado de ese exámen estuviese disponible. En tal caso la persona durante los días en que no se tenga el resultado será "sospechosa", para luego ser "confirmada" cuando eso último ocurra. También existen casos de personas que no consultan, por ende no llegan a epivigila, no son declaradadas sospechosas ni se hacen un pcr; en esos casos un doctor o doctora debe determinar causa de muerte, y puede identificarla como sospechoso de covid, en ese caso quedará en ese estado pues no se puede hacer un pcr. 

La situación que ud. se imagina es muy confusa, incluye que alguien se hiciera un pcr y fuera positivo en el pasado, luego se recuperase y volviera a contagiarse y morir? Si algo así llegase a ocurrir, dependería nuevamente si en este nuevo evento, la persona consultó y se hizo un pcr o no.

**Comment by daniamr** [comment]
@MinCiencia ya, entendido la fecha de pesquisa " eso definido según el mismo minsal" son aquellos casos de los cuales epivigila no tiene los datos. Lo curioso es que tiene un tiempo de latencia máximo de 259 días reportados hasta el 25 de marzo del 2021. Por cuanto, al no saber los datos y colocarlo retroactivamente desde la fecha de muerte, podría pasar por alto que esa primera consulta correspondería a recuperados y no un nuevo caso. Lo cual cuadra con el hecho de que hay 4.147 menos de recuperados confirmados. Dado que el total de casos confirmados debiese ser igual al total de casos confirmados recuperados más los muertos acumulados más los casos activos del día correspondiente.   Casos que podrían estar afectando a la evaluacion de incidencia según esquema de vacunación, ya que este cambia segun inicio de sintomas.
