### ISSUE TITLE
CRUCE ESAVI/EPIVIGILA

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1157]
Hola, no he podido encontrar ningún protocolo para hacer un diagnóstico diferencial entre efecto adverso (si no me equivoco correspondería a Y59.8) y U07.2, post vacuna.  Solo pude ver el flujograma hasta el informe ep. 95 , y dice que si es inconcluso se devuelve  caso probable. En ESAVI, tampoco se ve que hagan el cruce o que diga que hay que hacer un diagnóstico diferencial. 

![image](https://user-images.githubusercontent.com/93507862/140626114-d2b60c48-a3e4-45c1-a7a1-bc50807442a7.png)

![image](https://user-images.githubusercontent.com/93507862/140626132-49730f33-30d8-40f7-a28d-4f6f8cdafba2.png)

Me podrían decir si hay, y si hay donde está? 

Tampoco he podido encontrar algún estudio o protocolo que haga un diagnostico diferencial entre personas confirmados covid asintomaticos, cuya fecha de diagnotico sea previa a la vacunación, pero su estado empeoró post vacunación. 

Me podrían decir si hay y de ser así, donde está?

**Comment by dna33** [comment]
Hola, creo que esta pregunta tienes que remitirla al departamento de epidemiología del ministerio de salud, su encargada es la Dra. Alejandra Pizarro, experta en salud pública además.

Su correo es alejandra.pizarro@minsal.cl. Puedes citar el link, y dado la interacción que hemos tenido en otros issues, te advierto que probablemente demore en contestar, sin embargo me consta que apenas pueda lo hará.

**Comment by daniamr** [comment]
Gracias!!!
