### ISSUE TITLE
Producto 89 - cambio de formato en reciente commit: separación por ";" en vez de ","

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1158]
En reciente commit ffc584e6ca464a7850d7767df72a5cfb15f4f730 los campos en el archivo csv vienen separados por punto y coma ";" en vez de coma ","
![image](https://user-images.githubusercontent.com/68602/140643063-098da4a9-b042-4614-9baf-953ef16c4d1a.png)

En commits anteriores (y en otros productos) los datos venían separados por comas ","

![image](https://user-images.githubusercontent.com/68602/140643127-5f5cb8c0-b516-44bb-8b6a-8f6fa5726421.png)

Sugiero mantener un separador consistente para los archivos csv.

Algunos de estos productos alimentan código que procesa los datos automáticamente y se pueden generar errores al cambiar de formato.

Saludos y gracias por el trabajo que hacen publicando los datos

**Comment by dna33** [comment]
Hola, gracias por reportar. Cambiaron el formato desde la base de datos que cargamos, en el commit modifiqué el codigo como pueden ver, aparte de actualizar los datos con la última carga correspondiente a este lunes 8 de noviembre. 

2d896f0eb8c370c0a87739be55361b30eb45ad2f
