### ISSUE TITLE
Producto 89 - Error en cifras de incidencia

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1159]
En reciente actualización de producto 89 se observan errores en las cifras de incidencia
 
Por ejemplo se indica que **incidencia_casos = "2.443.676.725.890.110"**

![image](https://user-images.githubusercontent.com/68602/140643723-25628df5-c4d8-4b69-98a7-54efae3c5906.png)

**Comment by AntoineBraultChile** [comment]
Hola, será posible tambien de cambiar el seperador para comma (',') como en un csv clásico.
Muchas gracias.

**Comment by victorfica** [comment]
Hola @dna33 gracias por el update. 
Las cifras siguen con errores, en particular el formato decimal en las columnas `incidencia_casos` `incidencia_uci` `incidencia_def`.

**Comment by dna33** [comment]
¿Puedes revisar ahora? Hice 3 commits, uno que actualizó los datos corrigiendo el separador (desde ";" a ","), un segundo que actualizó las incidencias, y un tercero que corrigió porque me equiviqué en el código para defunciones.

1) 2d896f0eb8c370c0a87739be55361b30eb45ad2f
2) d03c86eeb1ba0f586f1dba3dd979ec9d83f30385
3) fe1deab88dba6f80c0af1acd252d08ee7f13c90d

**Comment by AntoineBraultChile** [comment]
Muchas gracias. A mi me parece bien. Es posible de poner un . y no un , para escribir los números decimales ? Creo que solo hay que cambiar la linea 

df_output_file.to_csv(producto, index=False, sep=',',decimal=',') 

en df_output_file.to_csv(producto, index=False, sep=',',decimal='.'), no ?
