### ISSUE TITLE
Producto 20: NumeroVentiladores_T.csv No actualizado

### ISSUE THREAD

**Issue by patricionicolas** [MinCiencia/Datos-COVID19#116]
El archivo: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto20/NumeroVentiladores_T.csv no ha sido actualizado en los ultimos dias. No así con sus archivos similares que si recibieron actualizacion: NumeroVentiladores.csv,  NumeroVentiladores_std.csv.

**Comment by fzmolina** [comment]
Arreglamos el problema. Muchas gracias por reportarlo
