### ISSUE TITLE
Diferencias en muertes DEIS vs producto 90:

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1161]
Diferencias en muertes total muertes DEIS (U07.1) vs producto 90 (confirmados):

Enn ambos casos tienen muestra positiva, por cuanto da a entender que alude a lo mismo. 

sem 1 a 42 al 16 de octubre del año 2021
Producto 90: 16889	
DEIS: 20789	

Diferencia: 3900	

Porqué se da esa diferencia?

Será que esas muertes fueron adjudicadas en el producto 90 al año 2020 por inicio de sintoma?

**Comment by MinCiencia** [comment]
Hola, nuevamente la misma pregunta. El producto 90 esta ordenada por fecha de inicio de síntoma, por favor lea el readme.md de cada producto para descartar que las cosas que ud. pregunta aparezcan ahi. 

Además, su cálculo de defunciones del deis parece estar malo, desde qué día hasta que día contó?

Saludos y gracias por aclarar, de antemano.

**Comment by daniamr** [comment]
Hola nuevamente, lo saqué desde el 1 de enero hasta el 16 de octubre. 

Me fijé, serían 99 menos considerando que la semana epidemiológica 1 comienza desde el 3 de enero. Osea 20.690,  hace días la tabla 90 eran 16.889, lo que hace una diferencia de; 3.801.

Con los datos actualizados del producto 90, a la misma fecha; 3 de enero al 16 de octubre, sería una diferencia de; 
Deis: 20690 
Prod. 90; 17.032
Dif. 3.658. 

Entonces, asumo que la respuesta es sí, que 3658 personas  en el producto 90 no están dado que el inicio de síntoma fue antes del 03 de enero del 2021?
