### ISSUE TITLE
Información Necesaria para un completo análisis del producto 93

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1162]
Hola,
Es posible incorporar la cantidad de casos confirmados y de contactos estrechos encontrados en el producto 93?.
Lamentablemente, este producto ahora solo tiene la razón de contactos por caso y esa información es insuficiente para hacer la validación de los indicadores a nivel regional y nacional.
Más aún, esa información antes se podía extraer manualmente de los informes de trazabilidad que publica el Ministerio de Salud todos los miércoles, pero ahora ni siquiera esta disponible allí, por lo que se vuelve más necesario actualizar este producto.
Espero que puedan realizar esta modificación.
Saludos,

**Comment by dna33** [comment]
Hola, hicimos este producto 94, es de utilidad? Me parece que el conteo total se puede calcular con los datos disponibles (casos totales multiplicados por casos por contacto).

7fba7dcbb66f9c5f6675e4f91a9841dd690a5e21

**Comment by felipeelorrieta** [comment]
Hola, se ve bien. Lo probare y cuento como me va. Saludos y gracias.
