### ISSUE TITLE
Actualización Sospechosos, Producto 37.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1163]
Hola,

Generalmente los registros U072 (fallecidos sospechosos), uno los podría encontrar desde: https://deis.minsal.cl/#datosabiertos  (Defunciones por Causa (actualización semanal)).

Por algún motivo, el Deis no los ha actualizado desde el sábado 06-noviembre-2021.

Sin embargo, si uno ingresa dentro del mismo sitio, a 'Defunciones Covid19 2020-2021', se encuentra que desde este lunes 08-noviembre-2021, si tienen los registros actualizados a los fallecidos sospechosos.

Considerando lo anterior expuesto, tienen acceso a la data de esa visualización o a la base de datos correspondientes para poder actualizar la serie sospechosos?.

![1de2](https://user-images.githubusercontent.com/69001461/141161343-d0c5901e-4f9a-493a-859e-91347ad74011.png)

![3JH1lYUbVp](https://user-images.githubusercontent.com/69001461/141161365-910b3ce3-5b58-4860-9574-888bdfbf6734.png)

**Comment by dna33** [comment]
Lamentablemente no tenemos acceso a la data de esa visualización, pero platié el problema al ministerio de salud.

**Comment by dna33** [comment]
01a9b372f26980b42ff308aa278bcfb4f13d9f89
