### ISSUE TITLE
CASOS RECUPERADOS - NO CUADRA

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1164]
Hola, quiero consultar con respecto de la variable "casos confirmados recuperados" del producto 5. 

Casos totales: 1.715.352
Casos confirmados recuperados : 16.660.049
Casos activos: 13.261
Casos fallecidos: 37.895

Según entiendo, la cantidad casos totales, debiera ser igual a casos confirmados recuperados más casos activos, más casos fallecidos, pero me da una diferencia de 4.147. 

A que se debe esa diferencia, a que categoría pertenecen los 4.147 de casos confirmados totales,  si no son casos activos confirmados, no son recuperados  confirmados y no son fallecidos? 

Además, hice un análisis por fecha y calzaba hasta el 19 de octubre del 2020, no obstante el 20 de octubre del 2020 ya habían 84 casos de diferencia a favor del total de casos. Desde esa fecha en adelante ya no cuadra. inclusive, para el 11 de noviembre del 2020 ya tenían un descuadre por 294 casos ¿qué ocurrió?

"Se entiende por casos totales o acumulados el número total de casos confirmados desde el primer caso confirmado hasta la fecha de elaboración del reporte o informe"

esa relación sí se da con la variable de "casos recuperados por fecha de inicio de síntomas" y "casos recuperados por fecha de diagnóstico". donde sí cuadran. Sin embargo, esos datos, según la definición, solo son proyecciones y no reales. 

datos que el minsal está ocupando para informar al país. 
diferencia a 8 de noviembre 2021  4.126  
Usadas los mismos datos que el minsal. 

Publicado 8 de noviembre: 8 de noviembre de 2021 titulado; "COVID-19: Chile supera los 24 millones de exámenes PCR y antígenos realizados"

![image](https://user-images.githubusercontent.com/93507862/141241611-7ff7e2fe-b9f4-4531-94d2-b1c94f0b168d.png)

![image](https://user-images.githubusercontent.com/93507862/141241989-924d86a0-3be4-4117-8d06-b89502e1495a.png)

**Comment by MinCiencia** [comment]
Hola, el número total de recuperados que ud. presenta es erróneo. Por favor aclarar la pregunta.

**Comment by MinCiencia** [comment]
En todo caso, a partir del 20 octubre minsal deja de entregar esa cifra directamente y desde entonces es calculada por dos indicadores automaticamente:

casos recuperados por FD es el indicador que se calcula como ud. busca.

**Comment by daniamr** [comment]
20 de octubre de que año, 2020 o 2021?

Quedo atenta.

**Comment by MinCiencia** [comment]
2020, ya no se usa "recuperados" en ni una nomenclatura. Solo se mantiene ese calculo por continuidad.

**Comment by daniamr** [comment]
@MinCiencia hola nuevamente, lo que no entiendo, es; si no está activo, no está muerto y no está recuperado, en qué estado están?
