### ISSUE TITLE
fuerte aumento de casos Activo Producto19 están ok los datos?

### ISSUE THREAD

**Issue by Orlando-GIS** [MinCiencia/Datos-COVID19#1165]
Estimados 

Los datos muestra un fuerte aumento en los datos activos en todas las comunas, entre el ultimo archivo del 8  de noviembre y el anterior del 5 de noviembre, estarán bien los datos subidos?

si sumo todos los casos activos por comuna  del 5 de noviembre da un total de 28.456 v/s los 43.282 de la misma suma del  8 de noviembre.

Saludos 

Orlando

**Comment by MinCiencia** [comment]
Parece en primera mirada haber un problema, vamos a investigar.

**Comment by dna33** [comment]
Hola, por ahora confirmamos que hay un problema, el equipo de Ministerio de Salud está trabajando en la solución y nosotros publicaremos en cuanto la tengan.

**Comment by MinCiencia** [comment]
Corregido en https://github.com/MinCiencia/Datos-COVID19/commit/33d9efb0c8473d15d1f5e5514aea0da9423d2784
