### ISSUE TITLE
 PRODUC 90 Y 89 / ESQUEMA DE REFUERZO

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1169]
Hola, quiero entender, porqué la diferencia de muertos? 
Entiendo que el prod. 90 es de inicio de síntoma y el producto 89 según SE. 

tengo 2 dudas; 

1.  a la semana 44;  ¿ 17 PERSONAS CAMBIARON DE ESQUEMA DE VACUNACIÓN EN EL PRODUCTO 90 Y QUEDARON CONTABILIZADOS EN OTRO ESQUEMA  Y NO DE REFUERZO?  porque raro sería que esos 17 muertos le inicien los síntomas después de la muerte,  a menos que sean zombis jaja. 
 
en el caso de semana 45,  prod. 89 a la semana epidemiológica hay un total de 56 muertos, en cambio en el producto 90 hay 39, por tanto hay una diferencia de 17 personas. 

2. a la semana 41; E EL PRODUCTO 90, INCORPORARON 9 MUERTOS  QUE AÚN NO OCURRÍAN? ponen muertos proyectados o fue error de digitación? 
es curioso que a la semana 41 el total en el producto 90 el total sea 30 y en el producto 89, tienen  un total de  21 muertos, con una diferencia de 9 muertos. Si el producto 89 es a la semana real, el total de muertos debiese ser igual o mayor que el producto 90 (entendiendo que en el producto 90 pueden cambiar esquema de vacunación) y se puede contabilizar en semanas anteriores a la 31. 

Además, tampoco se entiende porqué en el producto 89 en la semana 35 antes figuraban 6 y luego figuran 12. Que pasó? Porqué se cambian retroactivamente, si se supone que es a semana epidemiológica real.  O esa semana se les pasaron 6 muertos y a la semana siguiente se les pasó incluir 7 muertos y así. 

Eso hace que la incidencia comunicada en cada semana sea erronea, ya que están constantemente "arreglando" datos retroactivamente, pero informan una incidencia X según semana, entonces ese informe que se emitió en el minsal  ya está incorrecto?

A LA SEMANA 44
![image](https://user-images.githubusercontent.com/93507862/141702996-4e69d2c3-b2c4-4c63-9348-a25263238ffa.png)

A LA SEMANA 41
![image](https://user-images.githubusercontent.com/93507862/141703035-9dad4d51-7bef-4ad0-9390-c0367c58463a.png)

**Comment by MinCiencia** [comment]
Buenos días, @daniamr. Intentamos entender su pregunta pero está presentada con errores:

1. Ni el producto 89 ni el 90 han hablado aún de la semana epi 45.
2. Su comprensión de registro por fecha de inicio de sintomas o registro por evento no está correcta.

Respecto del producto 90, lo que ocurre acorde a los datos que nos entrega el MINSAL, es que lamentablemente fallecieron 30 
personas que inciaron síntamos la semana 41 (hasta el momento de publicación), de las cuales  respecto de su esquema de vacunación su estado era 14 sin esquema completo, 15 con esquema completo y 1 con dosis de refuerzo completa.

Respecto del producto 89, lo que ocurre acorde a los datos que nos entrega el MINSAL, es que lamentablemente ocurrió en la semana 41 la defunción de un total de 51 personas (hasta el momento de publicación), de las cuales 22 no tenían vacunas,1 con una dosis,0 dos dosis,27 con dos dosis completa ,0 con dosis unica,0 dosis unica completa ,1 dosis de refuerzo completa.

Le pedimos que no use entre comillas "arreglando", que sería bueno entienda que el proceso de investigación epidemiológica va desplegandose en el tiempo, y se van encontrando nuevas informaciones que se ven reflejadas en los datos. Su manera de referirse da la sensación de intenciones distintas a las que se tienen, la intención que gobierna el proceso es la de caracterizar adecuadamente qué sucedió respecto de la pandemia en un momento determinado en el país.

**Comment by daniamr** [comment]
Hola,@MinCiencia, paciencia, estoy tratando de entender, por algo pregunto. 

Entiendo que me tratas de explicar de manera "horizontal" osea viendo solo la semana en cuestión, pero mi pregunta se orienta  a  los totales, osea de manera "vertical" Quizás esa confusion  se da, porque justo por coinsidencia cabe de que EN la semana 41 da un total de 30 fallecidos en el producto 90. Pero yo me refiero a la sumatoria de la columna "esquema de refuerzo". 

 Ya fue preguntado lo del inicio de sintoma y esquema de vacunación de refuerzo, dado que la variable de esquema de ruefuerzo no está definida en el readme. Entonces Demian me envió la definicion de la semana epidemiologica según inicio de sintoma, lo cual se puede leer en el readme. La variable esquema completo por ejemplo dice; casos que al iniciar sus síntomas tenian ese esquema. Por tanto se puede extrapolar a la variable de refuerzo, dado que aún no es definida en el readme. Osea se entiende que esa fila corresponde a aquellos fallecidos que iniciaron su síntoma en esa semana y murieron (posteriormente). Entonces a la semana 41, había un total de 30 personas fallecidas que iniciaron su sintoma en la semana 32,33,34 etc, y que tenian esquema de refuerzo.  

"Respecto de la 89, hasta la semana 41, como dices tu, no habían 51, habían 21 fallecidos clasificados como esquema de refuerzo distribuidos en diferentes semanas, por eso coloqué la imagen comparativa.  

Insisto, no lo estoy viendo por semana, lo estoy viendo por la sumatoria de esas semanas y es ahí donde no me cuadra. Ya que HASTA la semana 41, en ambos productos según las definiciones debiese dar un total de 30 fallecidos de esquema completo.
