### ISSUE TITLE
Casos totales nacionales y RM para el 29 de abril

### ISSUE THREAD

**Issue by javierconcha** [MinCiencia/Datos-COVID19#117]
Hola,

Creo que los casos reportados para el día 29 de abril debieran ser diferentes a los reportados en las tablas de este repo, como lo había incluido en el pull request #110, i.e. 
RM: 8889 (y no 8639).
Chile Total Acumulados: 15135 (y no 14885).

Acá va mi razonamiento:
- Primero que todo, producto 3 es una tabla de "Casos Totales Acumulados", y no hace la distinción de casos con o sin síntomas. 

- Los casos totales del día 28 son 14365. Los casos nuevos del día 29 son 520+250=770. Por lo tanto los casos totales que debieran reportarse el día 29 son 14365+770=15135 y no los 14885 reportados en la tabla del Minsal (al menos la última que logré salvar; ver abajo). 

- Para que esto sea el caso, los 250 que aparecen en "Casos nuevos sin síntomas" debieran haber sido asignados a Santiago, y así los "Casos totales acumulados" sumen 15135, i.e. (272+183+514+42+76+526+(8639+250*)+104+392+761+719+1273+182+481+7+714)=15135.

- Por lo tanto, los casos totales para la Region Metropolitana para el 29: (8639+250*)=8889

Siguiendo el mismo razonamiento para el 30:
- Para la RM los casos nuevos totales son 736 más los casos del día anterior 8889, i.e. 8889+736=9625, que coincide con los reportados en la tabla. 

Patallazos de las tablas que tengo: [Abril 28](https://github.com/javierconcha/covid-19-Chile/blob/master/rawdata/2020-04-28-Casos-confirmados.png), [Abril 29](https://github.com/javierconcha/covid-19-Chile/blob/master/rawdata/2020-04-29-Casos-confirmados.png), [Abril 30](https://github.com/javierconcha/covid-19-Chile/blob/master/rawdata/2020-04-30-Casos-confirmados.png)

**Comment by fzmolina** [comment]
Hola Javier,

Estoy de acuerdo con tu razonamiento. Es algo que corregiremos. Utilizamos lo reportado por el Ministerio de Salud para ese día, con un error que luego corrigieron el día siguiente. Muchas gracias por tu comentario.

**Comment by MinCiencia** [comment]
Hola, reportamos también el error que debiera ser corregido en los pdf publicados diariamente (29 de abril). Las series de tiempo en este repositorio se encuentran actualizadas con la información correcta ahora.
