### ISSUE TITLE
PROD. 90 Y 89 ESQUEMA DE REFUERZO

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1170]
Hola, dado a que no me respondieron a la pregunta, insistiré. Quizás esa confusión se dió, porque justo por coincidencia cabe de que EN la semana 41 da un total de 30 fallecidos (de diferentes esquemas) en el producto 90. Pero yo me refiero a la sumatoria de cada semana, vale decir al total de la columna "esquema de refuerzo" en cada uno de los productos y haciendo una comparación entre productos..

Ya fue preguntado lo del inicio de síntoma y esquema de vacunación de refuerzo, dado que la variable de esquema de refuerzo no está definida en el readme. Entonces Demian me envió la definición de la semana epidemiológica según inicio de síntoma, lo cual se puede leer en el readme. La variable esquema completo por ejemplo dice; casos que al iniciar sus síntomas tenían ese esquema. Por tanto se puede extrapolar a la variable de refuerzo, dado que aún no es definida en el readme. Ósea se entiende que esa fila corresponde a aquellos fallecidos que iniciaron su síntoma en esa semana y murieron (posteriormente). Entonces a la semana 41, había un total de 30 personas fallecidas que iniciaron su síntoma en la semana 32,33,34 etc, y que tenían esquema de refuerzo (tercera dosis).

Hola, quiero entender, porqué la diferencia de muertos? 
Entiendo que el prod. 90 es de inicio de síntoma y el producto 89 según SE. 

tengo 2 dudas; 

1.  desde la semana 31 a la 44;  ¿ 17 PERSONAS CAMBIARON DE ESQUEMA DE VACUNACIÓN EN EL PRODUCTO 90 Y QUEDARON CONTABILIZADOS EN OTRO ESQUEMA  Y NO DE REFUERZO?  porque raro sería que esos 17 muertos le inicien los síntomas después de la muerte,  a menos que sean zombis jaja. 
 
en el caso de semana 44,  prod. 89 a la semana epidemiológica hay un total de 56 muertos, en cambio en el producto 90 hay 39, por tanto hay una diferencia de 17 personas. 

2.  desde  la semana 31 a la 41; E EL PRODUCTO 90, INCORPORARON 9 MUERTOS  QUE AÚN NO OCURRÍAN? ponen muertos proyectados o fue error de digitación? 
es curioso que a la semana 41 el total en el producto 90 el total sea 30 y en el producto 89, tienen  un total de  21 muertos, con una diferencia de 9 muertos. Si el producto 89 es a la semana real, el total de muertos debiese ser igual o mayor que el producto 90 (entendiendo que en el producto 90 pueden cambiar esquema de vacunación) y se puede contabilizar en semanas anteriores a la 31. 

Además, tampoco se entiende porqué en el producto 89 en la semana 35 antes figuraban 6 y luego figuran 12. Que pasó? Porqué se cambian retroactivamente, si se supone que es a semana epidemiológica real.  O esa semana se les pasaron 6 muertos y a la semana siguiente se les pasó incluir 7 muertos y así. 

Eso hace que la incidencia comunicada en cada semana sea errónea, ya que están constantemente actualizando datos retroactivamente y la incidencia de 6 no es lo mismo que 12. pero informan una incidencia X según semana, entonces ese informe que se emitió en el minsal  ya está incorrecto? digo porque se agregaron 6 personas en ese esquema en esa semana, que antes no habían.

A LA SEMANA 44
![image](https://user-images.githubusercontent.com/93507862/141702996-4e69d2c3-b2c4-4c63-9348-a25263238ffa.png)

A LA SEMANA 41
![image](https://user-images.githubusercontent.com/93507862/141703035-9dad4d51-7bef-4ad0-9390-c0367c58463a.png)

**Comment by MinCiencia** [comment]
Hola, no entendemos sus preguntas. Las tablas tiene que etiquetarlas con la variable que quiere que observemos, cada producto presenta varias variables y es confuso como ud. las propone. Quedamos atentos a sus correcciones antes de contestar.

**Comment by MinCiencia** [comment]
Lo otro, por favor en adelante, en general no tenemos que pedirle esto a nadie, pero puede por favor escribir una pregunta por issue? asi es más fácil trabajar.

**Comment by MinCiencia** [comment]
Respecto de su segunda tabla, los valores estan incorrectos al menos para la columna referente al prod90

**Comment by daniamr** [comment]
A la fecha están ya modificados retroactivamente, sin embargo hace 12 días esos eran los valores. 
Trataré de hacer 1 pregunta por inssue.

Tienes razón con respecto de la tabla hasta la semana 44, corrijo (adjunto imagen). Entonces la misma relación se da con 
 la vez anterior hasta la semana 41. 

Hay más muertes en la tabla 90 que en la tabla 89 dentro del mismo esquema (dosis de refuerzo). lo cual es raro, dado que en la tabla 89, se supone que son las muertes correspondientes a la semana epidemiológica real de ese esquema de vacuna.  Ergo, el total de la tabla (semana 31, 32, 33, 34, etc) 90 y el total de la tabla 89 debiesen dar la misma cantidad, la distribución por semana sería distinta, pero no la cantidad total. 

No entiendo a qué se debe la diferencia de 11 muertes menos en la tabla 89.

![image](https://user-images.githubusercontent.com/93507862/141847375-1e5b154a-b4fd-415d-8735-8a674f018ce4.png)

**Comment by MinCiencia** [comment]
Hola @daniamr. Ud. espera que los totales calcen entre ambos productos, y eventualmente lo harán, sin embargo puede ser que el uno o el otro aún no cuenten los casos respectivamente o bien, como aún ocurre, que la serie del producto 89 este incompleta para semanas anteriores a la 35. Su pregunta no procede, de todos modos, o bien quizás proceda algunas semanas después de terminada la pandemia, cuando las cifras en total se estabilicen.

**Comment by daniamr** [comment]
@MinCiencia pero esto es registro estadístico!!! tiene que calzar!!! Si no calza, es porque hay problemas en su contabilización .... Si no, se corre el riego de informar mal a las personas!!!!

**Comment by MinCiencia** [comment]
Pero como se le ha explicado no procede en este caso, pues es dinámico (está en evolución sujeto a los procesos de investigación epidemiológica), y son dos cifras distintas ontológicamente distintas, y además en el caso del producto 89 solo informa para esquema de refuerzo a partir de la semana 35, mientras el otro lo hace desde semanas anteriores.

**Comment by daniamr** [comment]
Sí, pero hay que entender que en una reportan 9 muertos más que la otra, y eso a fecha de termino de semana debe calzar. no es porque aunque ontológicamente se distribuya de manera diferente, la cantidad de muertos a la fecha no cambia.

Es bien distinto reportar una incidencia de esquema de refuerzo por población  según semana si tienes 9 muertos menos. haces cálculos que están incorrectos, no por la variable de inicio de síntoma que se entiende que se actualice retroactivamente, pero no por la fecha de ocurrencia (que se supone que es a tiempo real.  por eso sería lógico que la tabla 89 reportara más muertos que la 90, pero no así a la inversa. 

Ya los cálculos de incidencia estarían equívocos, solo por el hecho de modificar retroactivamente una tabla que avanza a tiempo real.

**Comment by MinCiencia** [comment]
nada es a tiempo real, todo depende de la velocidad de procesamiento de los datos, por ejemplo cuando una persona muere, puede que se tarden algunos días en inscribirla, además, puede ser que nunca haya ido al médico por ende no está en epivigila y no figura como caso.

**Comment by daniamr** [comment]
@MinCiencia obvio que se pueden demorar algunos datos, por la velocidad de procesamiento y que se demoren en inscribirlas, es una forma de decir a tiempo real, vale decir que son las muertes que se contabilizaron durante esa semana. Sin embargo, ya se reportaron esos 9 en el producto 90, ergo esos datos ya estaban disponibles.  Entiendo que ustedes solo colocan los datos que el Minsal les da, pero evidentemente, dada la seriedad de la pandemia y la gran campaña de vacunación que se ha emprendido, los datos deberían calzar para que las cifras tengan seriedad.  

Quisiera saber qué premisas tengo que no proceden?

**Comment by MinCiencia** [comment]
Bueno hay algunas cosas que nos parecen equivocadas. Veamos:

Esto por ejemplo, no "debe calzar", en casos que cuyo cuadro clínico evoluciona por más de una semana por ejemplo -muy habitual para el caso de las personas que lamentablemente fallecen:

> y eso a fecha de termino de las semana debe calzar. no es porque aunque ontológicamente se distribuya de manera diferente, la cantidad de muertos a la fecha no cambia.

O esto, nosotros no contabilizamos nada:

> pero esto es registro estadístico!!! tiene que calzar!!! Si no calza, es porque hay problemas en su contabilización .... Si no, se corre el riego de informar mal a las personas!!!!

O esto, que derechamente nos cuesta encontrarle sentido:

> que no pueden haber muertos futuros (que no han ocurrido) , según la definición de las variables

**Comment by daniamr** [comment]
Bueno hay algunas cosas que nos parecen equivocadas. Veamos:

Esto, por ejemplo no "debe calzar". En casos que cuyo cuadro clínico evoluciona por más de una semana por ejemplo -muy habitual para el caso de las personas que lamentablemente fallecen. Por otra parte, su uso de la palabra "ontología" como advervio de modo también es muy confuso.

@MinCiencia, entiendo que es confuso, pero esos casos que mencionan debiesen continuar como activos. Si estuvieron 9 meses con covid, esos 9 meses debiese considerarse como activo, no? 

*su ontología. De nuevo, la forma y no el fondo. 

O esto, nosotros no contabilizamos nada:

pero esto es registro estadístico!!! tiene que calzar!!! Si no calza, es porque hay problemas en su contabilización .... Si no, se corre el riego de informar mal a las personas!!!!

Entonces; es porque hay problema cuando cuentan las personas, o si lo prefieres, cuando suman. 

O esto, que derechamente nos cuesta encontrarle sentido:

que no pueden haber muertos futuros (que no han ocurrido) , según la definición de las variables.

Pues bueno, si hay 9 muertos más reportados en una tabla, esos 9 muertos ya fueron sumados en esa tabla, pero no fueron sumados en la otra. Entonces, si ya fueron reportados, porqué no fueron sumados en la otra tabla?  Por eso digo que raro sería que son muertes que aún no han ocurrido o que no han sido reportados, si ya fueron reportados en la otra tabla...
