### ISSUE TITLE
No sé cómo se obtiene la cifra "casos confirmados recuperados" (was CASOS RECUPERADOS CONFIRMADOS / NO CUADRAN)

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1171]
Hola, dado a que en la pregunta anterior me respondieron solo sobre los recuperados por FD, quiero insistir con respecto de la variable "casos confirmados recuperados" del producto 5.

Casos totales: 1.715.352
Casos confirmados recuperados : 16.660.049
Casos activos: 13.261
Casos fallecidos: 37.895

Según entiendo, la cantidad casos totales, debiera ser igual a casos confirmados recuperados más casos activos, más casos fallecidos, pero me da una diferencia de 4.147.

A que se debe esa diferencia, a que categoría pertenecen los 4.147 de casos confirmados totales, si no son casos activos confirmados, no son recuperados confirmados y no son fallecidos?

Además, hice un análisis por fecha y calzaba hasta el 19 de octubre del 2020, no obstante el 20 de octubre del 2020 ya habían 84 casos de diferencia a favor del total de casos. Desde esa fecha en adelante ya no cuadra. inclusive, para el 11 de noviembre del 2020 ya tenían un descuadre por 294 casos ¿qué ocurrió?

datos que el minsal está ocupando para informar al país.
diferencia a 8 de noviembre 2021 4.126
Usadas los mismos datos que el minsal.

Publicado 8 de noviembre: 8 de noviembre de 2021 titulado; "COVID-19: Chile supera los 24 millones de exámenes PCR y antígenos realizados"

![image](https://user-images.githubusercontent.com/93507862/141241611-7ff7e2fe-b9f4-4531-94d2-b1c94f0b168d.png)

![image](https://user-images.githubusercontent.com/93507862/141241989-924d86a0-3be4-4117-8d06-b89502e1495a.png)

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/1164

Y su respuesta la puede encontar en el reporte diario, en la nota al pie de dicho reporte, que amablemente le copiamos acá, sería bueno que antes de insistir tanto leyera bien las documentaciones de las cosas por las que pregunta:

> Para el cálculo estimado de confirmados recuperados se substrae a los casos confirmados acumulados, los casos activos confirmados y los casos fallecidos, independientemente de su causa
> de muerte.

**Comment by daniamr** [comment]
@MinCiencia hola nuevamente, lo que no entiendo, es; si no está activo, no está muerto y no está recuperado, en qué estado están?

"Nota aclaratoria 3: A partir del 2 de junio las series por Fecha de Diagnóstico se dejaron de reportar diariamente, pero se mantiene el cálculo acá a pedida de varios usuarios que quieren continuar utilizando dichas curvas."

"Hola, el número total de recuperados que ud. presenta es erróneo. Por favor aclarar la pregunta."

En qué está erróneo? Si el mismo minsal usó esa cifra el 8 de noviembre del presente, por eso coloqué la imagen. Cito; La cifra total de personas que han sido diagnosticadas con COVID-19 en el país alcanza a las 1.711.442 De ese total, 12.717 pacientes se encuentran en etapa activa. Los casos recuperados son 1.656.720. Donde están esos 4.126 casos, a qué categoría corresponden, si no son total activos, ni total muertos acumulados, ni total recuperados confirmados acumulados? 

Copio link por si quieres mirarlo.

https://www.minsal.cl/covid-19-se-reportan-2-367-nuevos-casos-y-65-817-examenes-a-nivel-nacional-en-las-ultimas-24-horas/

Gracias!

**Comment by daniamr** [comment]
@MinCiencia, Pues me enseñaste a obtener la cifra de los casos confirmados y recuperados, pero aún así me da el mismo monto, de diferencia.  Ahora, como la variable es "independientemente de su causa de muerte", agregué a los U07.2. Aún así me sigue dando diferencias. 

¿Será que aún no sé sacar la cifra, por el "independientemente de la causa de muerte?

**Comment by ctroncoso** [comment]
Para esos análisis creo que deberías revisar la base de egresos del DEIS. 
Requiere un poco mas de conocimiento a nivel de codificación de casos. Eso es, comprender lo que es un diagnostico principal, secundario y los mecanismos definidos por CIE-10. 
Por ejemplo, es totalmente factible que una persona tenga un diagnóstico principal de politraumatizado con condición de egreso de fallecido y aún así tener dignosticos secundarios de covid positivo. Estos no entran en la cuenta de fallecidos por covid. Te dejo el instructivo 7 del minsal con las normas de codificación que se han usado durante la pandemia, y que definen cómo se deben categorizar casos en alta... ya sea por egreso sano o fallecido. 

[Instructivo Nº 7 Codificación casos Coronavirus (COVID-19)v_7.1.pdf](https://github.com/MinCiencia/Datos-COVID19/files/7547548/Instructivo.N.7.Codificacion.casos.Coronavirus.COVID-19.v_7.1.pdf)

**Comment by daniamr** [comment]
@MinCiencia si lo había leido, de hecho revisé del excel del Deis de muerte por día según diagnóstico (salen todos)  y consideré esas variables para hacer los filtros y ese fue el monto que me dió.

**Comment by ctroncoso** [comment]
OK... también debes considerar que hay personas que han fallecido en casa, muchos sin PCR que pueden haber sido catalogadas como muertes por covid en forma temporal y que después se descartaron, o incluso lo opuesto. Vas a tener casos que simplemente abandonarán la estadística.

**Comment by daniamr** [comment]
@ctroncoso sí claro, esos casos que fueron probables (U07.2). Pero si considerara a los U07.2 dentro de "independientemente de la causa de muerte" la diferencia seria de 6.720...

**Comment by daniamr** [comment]
@MinCiencia Lo revisé, sin embargo me da por igual en ambos filtros.  No hace la distinción, solo se remite a la subcategorización del diagnóstico. Me podrías ayudar y decirme dónde podría encontrar la información que distinga  las personas que dieron positivo a Covid, pero que murieron por otra causa? 

Tu respuesta me ayudó, de que pudieran corroborar que esos 4.127 casos corresponden a esa categoría, sería favorable que hicieran un apartado con la variable y mayor especificación de la misma para mayor claridad. 

Quedo atenta y gracias!

**Comment by dna33** [comment]
Hola  @daniamr, preguntamos esto a Ministerio de Salud, nos indican que es posible que una persona sea diagnosticada con covid y lamentablemente fallezca por otra causa. En ese caso aveces quedan como sospechosos, otras veces fue claramente un ataque al corazón, o un accidente de tránsito. 

Me permito preguntarte, a raíz de la dedicación que ha tenido el equipo para repsonder tus preguntas, en qué estas trabajando? Será de utilidad pública o solo haces preguntas para satisfacer tus legitimas dudas personales?

**Comment by daniamr** [comment]
Me alagas, @dna33! Realmente valoro mucho el tiempo dedicado! Nunca lo hubiera pensado!  

Pues solo soy una cuidadana como cualquiera. Quizás, con muchas dudas y ganas de entender a cabalidad un tema que me genera curiosidad.  

A que te refieres con utilidad pública?

**Comment by dna33** [comment]
Me refiero de si es algo que responda al bien común, según tú, o solamente estamos contestándote tus preguntas que te van naciendo sin responder a otra cosa que tu legítima curiosidad.

Me alegra que te sientas alagada, para eso estamos.

**Comment by daniamr** [comment]
Nada en particular. 
Cuando tenga más dudas, preguntaré. 
Mil gracias!!

**Comment by daniamr** [comment]
*H
