### ISSUE TITLE
DUDA /  DEFUNCIONES POR OTRA CAUSA CON COVID CONFIRMADO

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1173]
Me podrías ayudar a encontrar la información que distinga las personas que dieron positivo a Covid, pero que murieron por otra causa?

Quedo atenta y gracias!

**Comment by MinCiencia** [comment]
Hola nuevamente, @daniamr. No tenemos esa información, lo más cercano es revisar la publicación del DEIS.
