### ISSUE TITLE
DUDA / TABLA 89

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1174]
No entiendo a qué se debe la diferencia de 11 muertes de esquema de refuerzo menos en la tabla 89  que el 90 hasta la semana 44? Siendo que esas 11 muertes adicionales en la tabla 90 sí fueron informados??

Vuelvo a preguntar, porque sí fueron informadas en un producto y en otro no?

**Comment by MinCiencia** [comment]
Hola, @daniamr. Sigues refiriéndote a los fallecidos con dosis de refuerzo completa, cómo preguntaste en los issues https://github.com/MinCiencia/Datos-COVID19/issues/1170 y https://github.com/MinCiencia/Datos-COVID19/issues/1169?

Preguntamos para ordenarnos, quedamos atentos.

**Comment by daniamr** [comment]
@MinCiencia si, aludo a lo mismo. Sin embargo, no quedó claro porqué las muertes fueron reportadas en una tabla no se consideraron en otra. La respuesta anterior fue vaga.

**Comment by MinCiencia** [comment]
Si, mira quizás es porque la pregunta estuvo planteada por su parte con inforamción incompleta: ¿puede por favor completar su tabla? Esto quiere decir desde la semana 35 para producto90 y desde la semana 32 producto89.

**Comment by daniamr** [comment]
@MinCiencia sería al revés. El producto 89 carece de información para esas respectivas semanas. No obstante se supone que en la tabla 89 no es semana epidemiologica segun inicio de síntoma, es por eso que no se entiende (digo por las definiciones), que el producto 89 requiera de actualizaciones, ya que se supone que; pir definición va en tiempo lineal de presente a futuro. No así en el 90, que según las definiciones va en tiempo retroactivo; vale decir de presente a pasado, (una persona que murió hoy la pongo en la semana por decir 31 porque ahí le empezaron los síntomas) lo que explica las constantes actualizaciones. 

Me doy a entender?  por eso encuentro raro que en la tabla 90 el total sea mayor, siendo que según definición de semana epidemiológica, debiese ser igual ó menor al producto 89.

**Comment by MinCiencia** [comment]
Cierto, nos referíamos al producto 89. No, no se explica su manera de entender el tiempo. 

Respecto de nuestro pensamiento representa la mejor explicación con que contamos para ud. Claro, sumado a lo dicho en sus presentaciones anteriores de la misma pregunta. Es probablemente la razón también. 

Saludos

**Comment by daniamr** [comment]
Gracias!!

Ustedes podrían preguntarle al minsal? 

Para saber como entienden el tiempo, tanto en variable de "protección completa"  (si suman los esquemas de vacunación ya cambiados por inicio de síntoma o si es la sumatoria por esquema según fecha de evento; fallecido).

Digo, como para tener una buena lectura de la tabla.

Quedo atenta. 

Saludos,

**Comment by dna33** [comment]
Hola, me quedo con la tarea de preguntarle a minsal, cualquier novedad te escribo acá.

**Comment by daniamr** [comment]
Muchas gracias Demian!!  Creo que tanto a mi como a otros, les ayudaría a leer adecuadamente la tabla! 

Quedaré atenta.
