### ISSUE TITLE
Inconsistencia de datos entre informe PDF publicado por Ministerio de salud y datos asociados en Producto 90

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1175]
El Ministerio de Salud publica semanalmente un "Informe de indicadores Estrategia Nacional de Testeo, Trazabilidad y Aislamiento Departamento de Epidemiología"
![image](https://user-images.githubusercontent.com/68602/142267164-64cd4cb9-86c8-47fe-85c3-69d5d482f36e.png)

En este informe se incluye una tabla con frecuencia de casos confirmados y se indica que 
"La serie de datos corresponde al Producto 90 descargable desde 
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto90/incidencia_en_vacunados.csv"

![image](https://user-images.githubusercontent.com/68602/142267042-be64a516-da05-4438-8e6f-81f6cb1886ae.png)

El gráfico publicado en el informe de hoy, 17 Nov 2021, muestra datos hasta la semana 43 con las siguientes cifras para esa semana:
sin vacuna: 1.435
una dosis: 565
dos dosis: 115
dos dosis completa: 4.666
dosis unica: 2
dosis unica completa: 326
dos refuerzo completa: 393

Estos datos no corresponden a los publicados en el producto 90 hoy 17 de Noviembre
![image](https://user-images.githubusercontent.com/68602/142268264-ffeccdae-0e70-4d7b-8363-e501f404e99d.png)

Pero si calzan con los publicados hace 11 días atrás en el repositorio de datos
![image](https://user-images.githubusercontent.com/68602/142268363-949d261a-4991-4041-8fcf-d21cfe9a0ce1.png)

Todo indica que el informe del Departamento de Epidemiología no actualizó este gráfico en el documento PDF publicado y eso hace que los datos no sean consistentes con los publicados en el repositorio de datos

El que se indique que la serie de datos corresponde a lo publicado en el producto 90 genera confusión en los lectores de los informes.  Sugiero notificar al Departamento de Epidemiología que se están publicando gráficos no actualizados (verifiqué este gráfico pero puede que este error también ocurra en otros gráficos) y solicitar que corrijan la publicación.

Gracias

**Comment by dna33** [comment]
Hola, es que no se publicaron hoy los datos, como sale en tu foro, @elaval. Se publican habitualmente los días jueves am. Nos pidieron hacerlo junto con el informe desde ahora en adelante y el equipo trabaja en eso. En minutos estará la actualización.

**Comment by dna33** [comment]
Me indican desde el departamento de epidemiología de Minsal que han subido un informe corregido.
