### ISSUE TITLE
Proporción de hospitalizaciones por Covid con una o más comorbilidades vs ninguna comorbilidad.

### ISSUE THREAD

**Issue by wgomg** [MinCiencia/Datos-COVID19#1176]
Hola, el producto 35 entrega los datos de ingresos hospitalarios segregados por comorbilidad pero no entrega información respecto de personas que posean más de una. No se puede establecer cuántos ingresos hospitalarios corresponden a personas con una más comborbilidades y cuántas corresponden a personas sin comorbilidades.

¿Es posible incluir esta información en este producto? O quizás se puede inferir de alguna manera que desconozco.

**Comment by wgomg** [comment]
Estoy escarbando entre lo disponible en el sitio del deis, igual quise preguntar acá por si las moscas. 

Gracias de todas maneras, avísame si cierro esto no más o lo dejo abierto por si alguien más puede aportar algo.

**Comment by ctroncoso** [comment]
Lo ideal sería contar con listado de egresos como pùblica fonasa en su zona de [datos abiertos](https://www.fonasa.cl/sites/fonasa/datos-abiertos/bases-grd), sin embargo, solo está disponible 2019 y 2020 y exclusivamente de hospitales públicos. 

De todos los datos que se pudieran tener, el código GRD es el mas importante ya que en su último dígito te indica si es sin, con comorbilidad o comorbilidad mayor.  (0,1,2). 

En las listas se leen como W/CC (con complicación o comorbilidad) o W/MCC (con complicación o comorbilidad mayor).

---------------------

@dna33 he visto que este espacio está teniendo doble uso, tanto como para reportar issues como un especie de "soporte". 
Creo que como la misión de proveer datos públicos del minciencia puede llegar a expandirse, este esquema de todo junto puede volverse poco manejable en el futuro. Te interesaría si conversamos sobre un community server para liberar un poco este y futuros espacios?

**Comment by dna33** [comment]
claro, mi correo es darancibia@minciencia.gob.cl; coordinemos ahi

**Comment by ctroncoso** [comment]
> claro, mi correo es [darancibia@minciencia.gob.cl](mailto:darancibia@minciencia.gob.cl); coordinemos ahi

Perfect.
