### ISSUE TITLE
Producto 65 - Ultimo registro fechado Martes 16 Nov 2021 y no Lunes 15 Nov 2021 (regularmente era un Lunes"

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1177]
![image](https://user-images.githubusercontent.com/68602/142297813-4857863e-5325-4103-8f07-b0e7d378bd20.png)

**Comment by dna33** [comment]
Cierto, corregido: 22e720c5a50e4b53d805cb70b3473a22d8b59fad

gracias por reportar.
