### ISSUE TITLE
PRODUCTO 45/ NO NOTIFICADOS

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1178]
Hola nuevamente! Me surgió una duda, cómo se entiende el producto 45? Las columnas hacia los lados, enumeradas con 202007 etc, qué significan? 

Quedo atenta. 

Gracias!

**Comment by MinCiencia** [comment]
Hola, la tabla esta agrupada por semana epidemiológica, en la primera columna y comuna en las primeras filas. La notación para semanas epi es la siguiente:
- primeros cuatro caracteres corresponden al año
- últimos dos corresponden a la semana epidemiológica.

El valor en cada celda corresponde a la cantidad de cada serie (probables, no notificados, confirmados) en la semana epi correspondeinte a su fila, y la comuna correspondiente a su columna.

**Comment by daniamr** [comment]
Ya entiendo, gracias!

Y son cifras acumulativas o aisladas? Vale decir, a la suma en última fecha de actualización, da el total? O para obtener el total se considera la sumatoria desde la primera fecha hasta la última? 

Quedo atenta.

Gracias!

**Comment by MinCiencia** [comment]
Están ordenados por FIS o fecha de notificación si es que la primera no está disponible, es decir para cada semana epi ese es el total de casos confirmados, no-notificados (aka notificados por laboratorio) o probables que iniciaron síntomas. Para saber el total a la fecha, o en un período determinado, debes sumar los valores. 

Esta curva corresponde en su última publicación a la mejor información disponible por parte del departamento de epidemiología, en base a su proceso de vigilancia epi.

**Comment by daniamr** [comment]
Gracias, pero me gustaría que me corroboraras; entonces hay un total de 1.452.380 casos que no están disponibles la fecha de inicio de síntoma? 

Haciendo la sumatoria total de cada semana en relación a cada fecha de publicación. 

Quedo atenta. 

Gracias!

**Comment by MinCiencia** [comment]
¿Puede ud. por favor elaborar cómo llegó a esa conclusión? Está totalmente equivocada.

**Comment by daniamr** [comment]
Es la sumatoria total de cada dígito de la tabla CasosNoNotificadosPorComunaHistorico_2021.csv.

**Comment by MinCiencia** [comment]
Esa tabla va tomando una foto de lo que publica el Ministerio de Salud de Chile en cada informe, asi que no corresponde usarla como ud. la usó. En el caso de las tablas con el sufijo Histórico_YYYY.csv, cuenta con una columna extra "publicación" que corresponde a cuando se publicaron los datos por parte de la autoridad sanitaria.

**Comment by MinCiencia** [comment]
Modificamos el readme.md del producto, que imaginamos consultó para incluir la respuesta a sus preguntas (https://github.com/MinCiencia/Datos-COVID19/commit/c6e79e6f35c565487586e272ca36f0ce2e638284).

**Comment by daniamr** [comment]
Gracias, porque queda un poco a la imaginación. 

Entonces, en la tabla CasosNoNotificadosPorComuna.csv dice que hay 15.620 casos no notificados según inicio de síntoma
 misma cifra que da en la tabla CasosNoNotificadosPorComunaHistorico_2021.csv. (haciendo la sumatoria por fecha de 19 de noviembre del presente relacionado con semana epidemiológica). 

Por cuanto, a la fecha de 19 de noviembre, hay 15.620 casos que no cuentan con su respectiva notificación?

**Comment by daniamr** [comment]
Te agradecería que me corroboraras, ya que no quisiera darle una lectura equívoca al producto.

**Comment by MinCiencia** [comment]
La definición de casos no notificados o casos notificados por laboratorio aparece en el informe epidemiológico del ministerio de salud, en su glosario, que le recomendamos leer. 

En todo caso, corresponden a casos que se hicieron PCR sin pasar por epivigila hasta que fueron confirmados por un laboratorio, esto puede ser porque no fueron al servicio de salud o médico, o bien porque ahi fallaron en notificar via epivigila.

**Comment by daniamr** [comment]
Dado que no me corriges, asumo que la respuesta es sí; 15.620 personas no cuentan con su respectiva notificación. 

Gracias!!

**Comment by dna33** [comment]
Si, así es. Ese es el total de casos que cumplen con haber sido notificados por el laboratorio.

**Comment by daniamr** [comment]
Gracias!!!
