### ISSUE TITLE
Cifra anómala en casos totales confirmados por antígeno 25 Noviembre 2021

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1179]
En el reporte diario del 25 Noviembre 2021 se reporta (en repositorio de datos producto 3 y en reporte en PDF) una cifra total de 
86.862 casos confirmados x antígeno

El 24 Noviembre se reportaron 78.774 (una diferencia de 8.088).  Esta diferencia es una cifra extremadamente alta (los nuevos casos x antígeno reportados el 25 Nov son 467

Esto puede ser un error en los datos del día o un ajuste por datos no reportados previamente.  Se agradecería si se puede informar a que corresponde.

Esta cifra (casos x antígeno) es muy importante ya que permite calcular los casos confirmados x test PCR y las respectivas positividades.

![image](https://user-images.githubusercontent.com/68602/143513361-b4e0f00d-340f-4ad8-975e-2a4ab0b9991a.png)

![image](https://user-images.githubusercontent.com/68602/143513680-9d144970-d53b-4f81-ab5c-283ad6de1952.png)

Gracias

**Comment by MinCiencia** [comment]
Hola, muchas gracias por la observación. Efectivamente se realizaron modificaciones nos contestan desde el Ministerio de Salud, en virtud de un nuevo ORD publicado en el diario oficial. Lo esperable, nos indican, es que haya más casos confirmados por antígeno y menos probables, de hecho en el balance de ayer tiene menos probables acumulados que el de anteayer.
[ORD_4518_15_11_2021_Def_de_caso.pdf](https://github.com/MinCiencia/Datos-COVID19/files/7611849/ORD_4518_15_11_2021_Def_de_caso.pdf)

**Comment by elaval** [comment]
Gracias por la información (explica mucho pero hay algo que no calza que planteó al final)

Entiendo entonces que dada las nuevas definiciones (ORD_4518) muchos de los casos que antes se reportaban como probables (especialmente contactos estrechos que presentaban síntomas) ya no se reportarán como probables sino que serán tratados como casos sospechosos a los que se les aplicará test (PCR o antígeno).

Esto explicaría una disminución en casos probables y un aumento en casos confirmados por antígeno en días recientes

Esto se observa al observar gráficos con total de casos confirmados por antígeno y total de casos probables

Total casos confirmados por antígeno (Producto 3):
_Se observa un escalón con un fuerte aumento (lo cual es consistente con la explicación)_
![image](https://user-images.githubusercontent.com/68602/143783290-156055b4-d236-4ba8-8358-34295a4258d8.png)

Total casos probables (Producto 3):
_Se observa un descenso del total acumulado de casos probables (lo cual es consistente con la explicación)_
![image](https://user-images.githubusercontent.com/68602/143783325-caa8edea-e4cd-4660-860a-22ccc3db47f3.png)


**LO QUE NO CALZA**
Si hubo un aumento brusco de casos confirmados por antígeno, **debería haber habido también un aumento brusco de los casos confirmados totales** (que incluye tanto casos confirmados por PCR como por antígeno).  Sin embargo este aumento no se observa en las cifras de casos confirmados totales (Producto 3):

![image](https://user-images.githubusercontent.com/68602/143783395-ea44c4cd-fb27-4993-ac39-3a6c4920923d.png)

Nota:  hoy se informan **Casos acumulados** (PCR + antígeno)  y **Casos confirmados por antigeno** en Producto 3.  La manera de determinar cuantos casos acumulados son confirmados x PCR es restando los casos confirmados x antígeno del total de Casos  Acumulados.   Si hay un alza brusca de casos x antígeno y no del total de casos confirmados, el cálculo daría un descenso brusco de casos confirmados x PCR (lo cual no tiene sentido).

¿No correspondería ajustar también el total acumulado de casos confirmados a partir de la misma fecha que se ajustaron los casos confirmados x antígeno?
