### ISSUE TITLE
Consulta respecto Data Product 43 - Calidad del aire

### ISSUE THREAD

**Issue by nro17** [MinCiencia/Datos-COVID19#1180]
Buenas tardes, según entiendo el Data Product 43 actualiza datos de calidad del aire de las estaciones del SINCA cada una hora, sin embargo, al revisar hoy la información solo hay datos hasta julio 2021, me gustaría confirmar ¿este producto ya no está funcionando?, si no funciona, ¿me podrían orientar un poco de cómo se puede acceder a la API de datos del SINCA?. Muchas gracias.

**Comment by dna33** [comment]
Hola, estaba fallando desde esa fecha efectivamente, lo acabamos de corregir y continuará su actualización. Cambiaron el formato de la respuesta de su api y arrunió el código.

https://github.com/MinCiencia/Datos-COVID19/commit/782cfac6d45bfdd4dbcb9a07d6cc0e5b929ff0c9
