### ISSUE TITLE
Cambio Brusco en Información de Datos-COVID19/input/Vacunacion/carga_vacunacion_sem_epi.csv

### ISSUE THREAD

**Issue by hco1975** [MinCiencia/Datos-COVID19#1183]
Ocurre un cambio brusco en la información del archivo carga_vacunacion_sem_epi.csv. ¿A qué se debe? Entre la información del 29 de noviembre con respecto a la del 22 de Noviembre 2021

Por ejemplo la semana 33 los fallecidos con dosis de refuerzo eran 14, en la actualización cambian a 0. A que se debe ese cambio, los fallecidos se cuentan con respecto a la semana de inicio de sintomas, por lo cual no pueden moverse de una semana a otra.

Otro ejemplo, semana 33 los casos de vacunados 1 dosis cambian de 2.248 a 255 casos. Ocurre lo mismo en casi todas las semanas. Debe ser un error de actualización. Por favor explicar el cambio.

![image](https://user-images.githubusercontent.com/95724160/145122765-843758bf-1b07-4a1e-9cba-2bf076e2fa93.png)

**Comment by dna33** [comment]
Hola, puedes por favor revisar si esto se mantiene en la última carga?

Gracias, quedo atento.

**Comment by hco1975** [comment]
Si, se mantiene. Cambió bruscamente datos de unas columnas hacia otras. ¿Porqué sucedió?

Por ejemplo, de la columna una_dosis_casos que en la semana 33 estaba en 2.248, ahora se encuentra en 256. Es un cambio muy brusco para un ajuste de casos. Lo mismo ocurre en todas las semanas, comparado con los archivos anteriores.

En cuanto a los fallecidos también los valores se movieron entre columnas. Por ejemplo la semana 33 la columna dosis_ref_comp_fall tenía 14, ahora tiene 0.

**Comment by hco1975** [comment]
> Si, se mantiene. Cambió bruscamente datos de unas columnas hacia otras. ¿Porqué sucedió?
> 
> Por ejemplo, de la columna una_dosis_casos que en la semana 33 estaba en 2.248, ahora se encuentra en 256. Es un cambio muy brusco para un ajuste de casos. Lo mismo ocurre en todas las semanas, comparado con los archivos anteriores.
> 
> En cuanto a los fallecidos también los valores se movieron entre columnas. Por ejemplo la semana 33 la columna dosis_ref_comp_fall tenía 14, ahora tiene 0.

Hola. ¿Existe respuesta al cambio de los datos?

**Comment by dna33** [comment]
Hola, en el informe 17 de incidencia en vacunados de Minsal se explica la razón del cambio. 

![image](https://user-images.githubusercontent.com/12438811/146958451-7ca52429-dcc6-481a-bc70-8dbb12f6d705.jpeg)

Te dejamos el link: https://www.minsal.cl/wp-content/uploads/2021/12/informe_vacuna_01_12_2021.pdf

**Comment by hco1975** [comment]
Hola. No es eso. Leí con detenimiento el Ordinario B51 / N°4518 y corresponde a definiciones para definir un caso como sospechoso (lo que no corresponde para el producto90 porque trabaja con caso confirmado), y agrega la prueba de test de antígenos para el caso confirmado, lo que debiera aumentar la cuenta, pero no disminuirla o cambiarla de estado de vacunación.

Por otro lado, lo que dice la nota aclaratoria sobre "... podrá explicar variaciones ..." no es una explicación científica. Por favor volver a revisar los casos, los ingresos a UCI y los fallecidos, y explicar el cambio brusco en los datos. Les recuerdo que cambia en más de 2.000 casos por semana.

Por ejemplo, de la columna una_dosis_casos que en la semana 33 estaba en 2.248, ahora se encuentra en 256. Es un cambio muy brusco para un ajuste de casos. Lo mismo ocurre en todas las semanas, comparado con los archivos anteriores.

En cuanto a los fallecidos también los valores se movieron entre columnas. Por ejemplo la semana 33 la columna dosis_ref_comp_fall tenía 14, ahora tiene 0.

**Comment by dna33** [comment]
Eso nos transmitieron desde el Ministerio de Salud, que tiene la información y el equipo para contestar. Yo agrego que se han visto ajustes de casos de esas magnitudes anteriormente, por ejemplo podría haber un descarte de casos de esa magnitud que contaban con test Ag negativo, pero no podían ser descartados simplemente porque legalmente no existía ese Ordinario.

Nosotros no tenemos más elementos para informarte sobre esto, puedes escribir directamente a Salud.

**Comment by hco1975** [comment]
Si sumamos los casos (globales, sin tipificar), los casos son similares en magnitud. Se puede inferir que los casos cambiaron de tipificación, no fueron descartados. La consulta es para aclarar cual es la razón del cambio.

¿Donde debo consultar? ¿Cuales son los datos de Salud para realizar la consulta?

**Comment by dna33** [comment]
La directora del departamento de epidemiología es Alejandra Pizarro: apizarroibanez@minsal.cl; otra opción es que efectivamente no se contara con la fecha de inicio de síntomas en la primera publicación, se usara fecha de notificación, y luego se contara con ese dato y por ende se reclasificaran los casos en otra semana.

Te menciono esto y lo del caso anterior, sin haber visto los detalles, por supuesto, usando situaciones que han pasado anteriormente.

**Comment by hco1975** [comment]
Enviamos la consulta a Alejandra Pizarro. Esperamos respuesta.

**Comment by hco1975** [comment]
Enviadas 2 solicitudes a Alejandra Pizarro, sin respuesta, sin acuso de recibo. ¿Pueden ustedes solicitar la explicación?
