### ISSUE TITLE
Actualización de datos de vacunación

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1184]
Hola, veo que en general los datos de vacunación están actualizados hasta el día 5 de diciembre pasado, incluso cuando su última actualización fue el 9. Hay algún problema o se ha modificado la frecuencia de actualización?

Saludos!

**Comment by MinCiencia** [comment]
Hola, error en el código. Esta corregido en los próximos minutos, gracias por reportar.
