### ISSUE TITLE
Población por comuna de 3 a 5 años

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1185]
Hola, con la ampliación de la vacunación a los niños de 3 a 5 años hace falta incorporar la población de ellos para calcular el porcentaje avance. Esta información está en el P81.

Muchas gracias, saludos!

**Comment by dna33** [comment]
Incorporado e7557caacd0c0d530e0bebccf522d888119a3e59, gracias!
