### ISSUE TITLE
Error en fecha en última actualización de Positividad x Comuna (Porducto 65)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1186]
Datos de positividad x comuna de última actualización debieron haber sido para el 6 de Diciembre (2021-12-06) pero están con fecha 11 de Noviembre (2021-11-06):

![image](https://user-images.githubusercontent.com/68602/145832785-c1731a42-dcc4-419d-9acc-ad4f5fbcf0db.png)

**Comment by dna33** [comment]
gracias por reportar, efectivamente había un error que fue corregido: 0ffb14179f4a72fa9ca9796f4c4875959536ba52
