### ISSUE TITLE
Error en PRODUCTO 1: datos de casos confirmados por comuna  para 2021-12-17 (publicados el 2021-12-18)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1187]
En la actualización del 2021-12-18 los datos de casos confirmados para el 2021-12-17 duplican las cifras que se habían informado el 2021-12-13 para todas las comunas del país

![image](https://user-images.githubusercontent.com/68602/146655652-e8e1ec3a-d44c-4c02-a0ea-a1ddd769c406.png)

**Comment by MinCiencia** [comment]
Cierto, no corrió adecuadamente la rutina relativa a productos del informe epi, se encuentra corregido: 927e0d18120a9cc6d68f79e93b557d9ea772d941

**Comment by MinCiencia** [comment]
927e0d18120a9cc6d68f79e93b557d9ea772d941
