### ISSUE TITLE
¡Necesitamos tu apoyo!

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#1188]
Esta plataforma ha sido reconocida por el Servicio Civil como finalista del concurso "Funciona! 2021". El concurso constituye un reconocimiento a la capacidad de innovación reflejada en iniciativas diseñadas e implementadas por equipos de funcionarios públicos y municipales a nivel nacional. Y también representa un reconocimiento a quienes usan y crean la solución, es decir ustedes.

[Vota aquí](https://www.concursofunciona.cl/) por la iniciativa **@Min_ciencia_IA: Sistema integrado de información y divulgación abierta de salud pública y bot de datos para enfrentar la emergencia sanitaria por COVID-19 de Subsecretaría de Ciencia, Tecnología, Conocimiento e Innovación**  y ayúdala a ganar en la selección final que realizará un jurado especializado durante el mes de Enero 2022.

Acá pueden ver información sobre como se presentó esto al concurso: https://www.concursofunciona.cl/2021/12/min_ciencia_ia-sistema-integrado-de-informacion-y-divulgacion-abierta-de-salud-publica-y-bot-de-datos-para-enfrentar-la-emergencia-sanitaria-por-covid-19/

**Comment by dafernandez75** [comment]
Felicitaciones a todo el equipo que lidera y mantiene el repositorio. Saludos

**Comment by dna33** [comment]
¡Si alguien quiere enviar un video, grabado con el celular, contando brevemente en 15-30 segundos cómo usa esta plataforma, bievenido! Pueden enviarlo a futuro@minciencia.gob.cl o subir link acá.

**Comment by ctroncoso** [comment]
Va video!

> ¡Si alguien quiere enviar un video, grabado con el celular, contando brevemente en 15-30 segundos cómo usa esta plataforma, bievenido! Pueden enviarlo a [futuro@minciencia.gob.cl](mailto:futuro@minciencia.gob.cl) o subir link acá.

**Comment by adinamarca** [comment]
> ¡Si alguien quiere enviar un video, grabado con el celular, contando brevemente en 15-30 segundos cómo usa esta plataforma, bievenido! Pueden enviarlo a futuro@minciencia.gob.cl o subir link acá.

Hola Demián.
¿Aún se puede enviar?
Saludos.

**Comment by dna33** [comment]
Si!
