### ISSUE TITLE
Datos publicados de producto 15 erroneos

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#1191]
Estimados

Los datos publicados hoy 29.12 del producto 15, son los mismos que se publicaron el día 25.12, lo mismo sucede con el producto 61

Saludos,

Eduardo

**Comment by dna33** [comment]
Hola Eduardo, voy a investigar qué pasó con el producto 61. Por otro lado, cómo comparas para el producto15 ?

**Comment by dna33** [comment]
Hola, corregido en https://github.com/MinCiencia/Datos-COVID19/commit/da37a80a96caa9c8c3e993bc88fad8154973f36d

Gracias por reportar.
