### ISSUE TITLE
Reporte diario NO FUE ACTUALIZADO el 1 Enero 2022 

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1194]
Parto por saludar en este nuevo año a las personas que trabajan manteniendo este repositorio de datos (y a las que - como yo - somos usuarios de dichos datos).

¡Qué sea un mejor año para todas y todos!

Consulta:
Hoy - 1 de Enero 2022 - a las 17:55 todavía no están disponibles los datos del Informe Diario.  Hay alguna hora estimada para publicar con estos datos?

Gracias

![image](https://user-images.githubusercontent.com/68602/147860068-6f3e7d10-2455-42eb-9806-35aeb80579eb.png)

**Comment by MinCiencia** [comment]
Hola, corregido: f1b73f061fcc3a956df66602ff3521ef188693f2

Gracias por reportar
