### ISSUE TITLE
Productos 15 y 45 sin actualizar

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1197]
Hola, en la actualización de ayer de productos asociados al reporte epidemiológico solo se actualizaron algunos productos. 

De los que vi, al menos faltan por actualizar productos 15 y 45. 

De antemano gracias

**Comment by weichafan** [comment]
Gracias, se solucionó...me auto-cierro issue

**Comment by dna33** [comment]
corregido, gracias por reportar: d066689710d6fcf6995f5c40e7da219b3f0b25e9
