### ISSUE TITLE
Actualización productos DEIS (50, 84)

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1198]
Hola, quería reportar que los datos de defunciones confirmadas y sospechosas provenientes de DEIS y separadas por comuna y edad (productos 50 y 84) no han sido actualizados en 17 días. Espero que pueda retomarse la frecuencia de actualización.

Saludos,

**Comment by dna33** [comment]
Actualizado: ef22c6e7973acf0f3ac8132136c732a704f2b999

Aprovecho de comentarte que la iniciativa compite en concurso del servicio civil, con entidades que tienen más de 10 veces el número de funcionarios que nuestro recién creado ministerio de ciencia, en ese sentido sería ideal si nos ayudas a difundir y a convocar votantes pues vamos perdiendo en el marcador. Esta abierto hasta el 7 de enero (mañana): https://www.concursofunciona.cl/
