### ISSUE TITLE
Datos aparentemente duplicados para 2020-04-09 Producto 3 CasosTotalesCumulativo.csv

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#12]
Al parecer en Producto3 / CasosTotalesCumulativo.csv los datos de 2020-04-09 están duplicados c/r a los de 2020-04-08

Gracias por este importante trabajo poniendo a disposición los datos crudos por esta vía. Es muy relevante y muy necesario

![image](https://user-images.githubusercontent.com/68602/78961429-68929300-7abf-11ea-9b19-34e16ae4dbcf.png)

**Comment by ivanMSC** [comment]
🤣🤣🤣
