### ISSUE TITLE
Producto 16, última y penúltima semana datos repetidos

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1200]
Producto 16 última y penúltima semana mismos datos. 
Producto 39 no se actualizó con datos epi. 
Producto 15 también parece con problemas

Por favor revisar.

**Comment by ishmaster** [comment]
Estimados:

Adicional a lo mencionado por @weichafan , también se repiten los datos (iguales al 3-1-2022) en el producto 19.

**Comment by ctroncoso** [comment]
agregar Pr1... también están repetidas las fechas  del 03 y 07

**Comment by dna33** [comment]
corregido: 47446a7d3edd45f122fc2cd6095ebdba9d9eee05

ver https://github.com/MinCiencia/Datos-COVID19/issues/1201
