### ISSUE TITLE
Revisar Pr1 - Último registro está duplicado. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1201]
Los casos por comuna de fechas 03/01 y 07/01 son idénticos.
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto1/Covid-19.csv

**Comment by sebarivas** [comment]
Ocurre lo mismo en el producto 19. Parece ser un error general de carga.

**Comment by elaval** [comment]
Apoyando lo indicado en este issue:

![image](https://user-images.githubusercontent.com/68602/148691214-ff50d532-3084-4440-a164-2263796b41a0.png)

**Comment by dna33** [comment]
Gracias por reportar. Efectivamente no hubo carga de datos de forma oportuna este fin de semana y las rutinas corrieron con los datos del miércoles. Acabamos de corregirlo: 47446a7d3edd45f122fc2cd6095ebdba9d9eee05
