### ISSUE TITLE
Producto 90: Posible sobreescritura y por ende pérdida de datos

### ISSUE THREAD

**Issue by samirop** [MinCiencia/Datos-COVID19#1202]
Estimados, al menos parte de los datos de la primera semana epidemiológica se están sobreescribiendo desde la primera semana de enero 2022. ¿Es esto a propósito? ¿Se perderán los datos antiguos? En cualquier caso, sería útil agregar una columna de fecha además de la de "semana epidemiológica".
Gracias por el trabajo.
Saludos

**Comment by dna33** [comment]
Hola, así es. Nos percatamos también en la última actualización. lo corregimos y tendremos que ver como manejar los años para adelante.

47446a7d3edd45f122fc2cd6095ebdba9d9eee05
