### ISSUE TITLE
Producto 37 - Defunciones DEIS - Sin dato actualizados

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1204]
Hola, no esta actualizado el producto con los casos Sospechosos que DEIS publicó el 8/Ene y los datos al 10/Ene del reporte diario

Gracias

**Comment by Jorgecibia** [comment]
Hola, hoy actualizaron, pero al 10/ene (falta el 11/Ene) y faltan sospechosos al 7/Ene

**Comment by MinCiencia** [comment]
Corregido, gracias por reportar! baed6e250411938e371f9bffb676d7075df5cc6a
