### ISSUE TITLE
Producto 7 - actualización exámenes PCR regiones antofagasta-coquimbo

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#1205]
Estimados:

Dada la corrección en la cantidad de exámenes PCR en las regiones de antofagasta y coquimbo, cuándo se hará la corrección del producto 7?

- Informe diario 11-1-2022: [link](https://s3.amazonaws.com/gobcl-prod/public_files/Campa%C3%B1as/Corona-Virus/Reportes/11.01.2022_Reporte_Covid19.pdf)

**Comment by dna33** [comment]
Hola @ishmaster, puedes chequear si se corrigió con la actualización del balance de hoy 640f3869e5df25f63d514cb325efbbe0670b9a40?

**Comment by ishmaster** [comment]
Hola @dna33 !
No se corrigieron los valores.

**Comment by dna33** [comment]
ACTUALIZADO: 7f00f9fadcf46544a59aeb14e1f810a2bd64aaff
