### ISSUE TITLE
Información sobre cuarta dosis

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1209]
Hola!
Tienen contemplado en estos días actualizar los archivos de vacunaciones con la información de la cuarta dosis que comenzó esta semana? Al menos en la plataforma de DEIS ya está disponible.

Saludos!

**Comment by dna33** [comment]
Añadimos, se está incluyendo desde la actualización del viernes. Gracias por la sugerencia!
