### ISSUE TITLE
semana epidemiologica 0

### ISSUE THREAD

**Issue by AntoineBraultChile** [MinCiencia/Datos-COVID19#1210]
Hola,

A que fechas corresponde la semana epidemiologica 0 ?

Gracias,
Saludos

**Comment by dna33** [comment]
donde aparece? sospecho que es la 52, del año n cuando tiene días en el año n+a; habíamos hecho ese ajuste para algunos productos.

**Comment by AntoineBraultChile** [comment]
Olvidé de decirlo: es en el producto 89

**Comment by dna33** [comment]
Vamos a corregir, viene desde la fuente. Reportado a minsal ya. gracias.
