### ISSUE TITLE
Producto 76

### ISSUE THREAD

**Issue by jccarvajal** [MinCiencia/Datos-COVID19#1211]
En los archivos de "vacunación", al agregar los datos de la cuarta dosis no ampliaron el campo de "región" para incluirla, por lo que los datos quedaron descuadrados.

**Comment by dna33** [comment]
corregido, en la actualización de mañana se deberían ver bien.

**Comment by dna33** [comment]
para estar seguro, en que productos esta el problema?

**Comment by jccarvajal** [comment]
OK. En el producto76, los archivos "vacunación".

**Comment by dna33** [comment]
f6096d0fc48d9aa89a80ee12df1368968306dad9 va a corregir esto, gracias por reportar.

**Comment by dna33** [comment]
7f983ddf9b43de59fac55b47829934a4e9955e61
