### ISSUE TITLE
¿Podrían publicar día de la semana en que se actualizan productos semanales?

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1212]
Por favor, es cansador estar viendo si actualizaron o no ciertos productos que en semanas previas se actualizaron un día de la semana y luego pasan 10 o 14 días sin actualizarse. 

A veces no se actualizan por errores de los códigos y otras porque no tienen los datos. Si nos dicen qué dices se debiera actualizar cada producto sería más fácil para los que seguimos los datos y los necesitamos para diferentes actividades. 

Por favor, publiquen en cada producto qué día debiera se actualizado. 

Por ejemplo productos 89, 90, 91 y 92

Gracias.

**Comment by MinCiencia** [comment]
hola, habitualmente los jueves. A veces hay problemas y falla en cumplirse, pero esa es la planificacion.
