### ISSUE TITLE
Producto 76 : falta la fila refuerzo para aysen

### ISSUE THREAD

**Issue by AntoineBraultChile** [MinCiencia/Datos-COVID19#1213]
Hola,

En el producto 76, archivo vacunacion.csv, falta la fila refuerzo para la región de Aysen.

Muchas gracias.
Saludos.

**Comment by dna33** [comment]
f6096d0fc48d9aa89a80ee12df1368968306dad9, vamos a correr la actualización de vacunas en base a este update en el código. Debería funcionar, en alrededor de 1 hora estarán los resultados actualizados.

**Comment by dna33** [comment]
7f983ddf9b43de59fac55b47829934a4e9955e61
