### ISSUE TITLE
Pacientes UCI según antecedentes de vacunación y semana epidemiológica

### ISSUE THREAD

**Issue by pescap** [MinCiencia/Datos-COVID19#1214]
Estimados, 
Quería saber si el número de Pacientes UCI según antecedentes de vacunación y semana epidemiológica estaba disponible en alguna parte.

En el Producto 90 se dan los ingresos UCI, pero no el número actual de pacientes. 
Gracias y saludos,
Paul

**Comment by paarriagadap** [comment]
Hola, creo que el 89 te sirve, que muestra la incidencia absoluta y relativa para casos, UCI y defunciones

**Comment by pescap** [comment]
Hola! Gracias por tu mensaje. El 89 y 90 indican número de casos que **ingresaron** a UCI. Estoy tratando de buscar datos describiendo los casos que **están** en UCI.

**Comment by paarriagadap** [comment]
Ah, perdón, tienes razón. No hay entonces.

**Comment by ctroncoso** [comment]
> Hola! Gracias por tu mensaje. El 89 y 90 indican número de casos que **ingresaron** a UCI. Estoy tratando de buscar datos describiendo los casos que **están** en UCI.

Se miden de 2 maneras. 

- El **DEIS** cuenta los EGRESOS codificados una vez que son dados de alta.  
- El otro es el recuento diario de camas que realiza la **UGCC** (unidad de gestión de centralizada de camas).

En ninguno existe registro público individual de estado de vacunación. 
Solo hay estado de vacunación de ingreso, no de estancia. 

Si lo que buscas es hacer un análisis de edad, tipo de vacuna , LOS (largo de estadía) y correlacionar con  condición de alta (no mejorado, mejorado, fallecido), estamos en las mismas. No hay información pública.

**Comment by pescap** [comment]
¡Muchas gracias Carlos! Aprovecho la oportunidad para pedir feedback. 

En [este gráfico](https://github.com/YachayData/MinCienciaDS/blob/main/sintesis.pdf), asumimos que: la distribución de los pacientes UCI según estado de vacunación = distribución de los ingresos UCI según estado de vacunación de las **5 últimas semanas**. 

Elegimos 5 semanas porque el número total de ingresos UCI en las 5 últimas semanas correspondía aproximadamente a la cantidad de pacientes UCI. 

Si a alguien se le ocurre (o conoce) una mejor forma de estimar la cifra de pacientes UCI nos avisan, ¡gracias!
Paul
