### ISSUE TITLE
Productos 91 y 92 sin actualizar

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1215]
Hola, datos de ingresos a UCI y hospital ¿cuándo se podrán actualizar?  
Hoy cumplen 7 días sin actualizar, aunque la anterior actualización fue muy atrasada. 

Solía ser los jueves.

**Comment by dna33** [comment]
se había quedado el commit en el tintero: https://github.com/MinCiencia/Datos-COVID19/commit/ce6625174425b2c8b4b73a4a85abc52e1145cdad
