### ISSUE TITLE
Producto 37 - Fallecidos DEIS sin actualizar casos sin PCR (Sospechosos)

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1217]
Hola, este dato se publicó en reporte DEIS el 14/Ene pero no se ha actualizado la distribución diaria.  Gracias

**Comment by Jorgecibia** [comment]
Hola, hay una nueva actualización del DEIS pero no aparece en el producto 37(me refiero a los sospechosos), alguna novedad ?

**Comment by MinCiencia** [comment]
actualizado https://github.com/MinCiencia/Datos-COVID19/commit/7bbc2630820c276fab21a02481469b58e2baae92
