### ISSUE TITLE
Fecha de informe es distinta a fecha de datos

### ISSUE THREAD

**Issue by javierlopeza** [MinCiencia/Datos-COVID19#122]
Hoy se subió un informe epidemiológico con fecha de 1 de mayo, pero que incluye los datos por comuna al 30 de abril.

En el producto 19: [CasosActivosPorComuna](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto19/CasosActivosPorComuna.csv), los datos que se agregaron hoy señalan que son del 1 de mayo: ¿no deberían ser del 30 de abril como lo señala el informe en cada región?

![image](https://user-images.githubusercontent.com/11431769/80872931-10e0e500-8c83-11ea-94dd-b1c2748d6ef5.png)

**Comment by MinCiencia** [comment]
Hola @javierconcha 

La fecha otorgada a cada reporte corresponde a la publicación por MINSAL. Habitualmente refleja el registro del día anterior, salvo que se indique lo contrario.

Hemos seguido este principio para todas las series de tiempo.
