### ISSUE TITLE
Duda sobre producto 74

### ISSUE THREAD

**Issue by sebaapblz** [MinCiencia/Datos-COVID19#1220]
Primero que todo agradecer la buena pega que están haciendo en compartir esta información y que sea accesible para todos, incluso para quienes no somos desarrolladores.

Ahora mi duda (problema).

Según yo, hasta ayer, la última fecha de actualización estaba hasta el 15-01-2022. Hoy actualicé y la última fecha cambió al 08-01-2022, por lo que, aparentemente, se habrían eliminado registros de la tabla (puede que el error sea mío). Al margen de ese problema, que no es tan relevante, y sabiendo que la RM pasó a fase 3, cuándo creen que podrían actualizar el dato de la fase actual.

De antemano, muchas gracias.
Saludos!!!

**Comment by dna33** [comment]
Cierto, corregido en este commit: 1462c23872ffddf0f4c70e2f26a24d781888efc9.

La rutina automática tomó la fuente equivocada hoy, no debería volver a ocurrir. La fecha actual es al 19 de enero 2022.

**Comment by elaval** [comment]
Apoyo lo comentado por el autor del issue

En commit 55745c7fb1cbbf4cfb71c7218a48c7ec5c0490db (del 16 de Enero) habían datos hasta el 2022-01-15
![image](https://user-images.githubusercontent.com/68602/150406334-978c9cc3-585e-4c78-b7a7-7f2c03bd6ab0.png)

En commit 83c5a7c123883f1538b18e8c9500b312e910b9ef (del 20 de Enero) hay datos hasta e 2022-01-08
![image](https://user-images.githubusercontent.com/68602/150406778-b4863c8e-ece7-4391-a734-418ce35e24a5.png)

**Comment by elaval** [comment]
Acabo de ver el comentario con la corrección!  

Gracias

**Comment by sebaapblz** [comment]
Buenísimo, se pasaron!! Muchas gracias!!

Saludos!
