### ISSUE TITLE
Alguna estimación de cuando se actualizará el Producto 65 (Positividad x Comuna)?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1222]
Fue actualizado hace 9 días atrás:

![image](https://user-images.githubusercontent.com/68602/150657274-f0acfa8b-8c62-4153-8e1c-caebfd2cb6ba.png)

**Comment by MinCiencia** [comment]
ver https://github.com/MinCiencia/Datos-COVID19/issues/1221
