### ISSUE TITLE
Epi del 24 y del 21 son idénticos. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1226]
En referencia al #1224 y #1225 
Hay un error en la carga del informe EPI del 24. Los datos son idénticos al día 21. 
commit: 96589d6698d3825552dac567766ca8f7cc0e4d8b

**Comment by MinCiencia** [comment]
Cierto, corregido en 547b4aed8662bdfaa056164ed50b9d35687285f9
