### ISSUE TITLE
HAY 89 NIÑOS MENORES A 6 AÑOS FALLECIDOS  CON ESQUEMA DE REFUERZO!?!

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1228]
Hola, como están? tanto tiempo. 

Me surgió una duda, al ver la diferencia en la tabla 89 y 90 en la categoría fallecidos por covid con esquema de refuerzo, me di cuenta que la tabla 90 tiene 89 fallecidos de más que la 89. total esquema de refuerzo 291 muertos en producto 90 y total 202 muertos esquema de refuerzo producto 89 respectivamente. Como la 89 no muestra a los niños menores de 6 años, la diferencia se explicaría por esa razón, ósea, 89 niños menores a 6 años han muerto de covid con la vacuna de refuerzo. 

Ambas tablas se presentan en el mismo periodo desde el inicio de la campaña de vacunación de esquema de refuerzo (semana 32), donde en el producto 90 el primer muerto es en la semana 34 (por el inicio de síntoma) 0 la semana 35 y en el producto 89, los primeros muertos en la semana 35 (6 muertos esa misma semana). 

Realmente no sé como pudieron morir 6 en la semana 35 (semana correspondiente), pero solo a 1 le inició síntoma en la semana 34 y 0 en la 35. (semana según inicio de síntoma). Pero en fín. ¿Quizás le iniciaron los síntomas después de morir? 🙈

Además no se entiende, porque en el Deis, indica que solo 35 niños entre 1 a 5 años han muerto por covid desde inicio de pandemia.  

Añadiré, que en el Deis, en la semana 52 figuran 106 muertos mayores de 5 años, (igualmente para mayores de 6 años)  pero en el producto 89 solo 69.
En la semana 51 figuran en el Deis 142 muertos mayores de 5 años, (igualmente filtrado con mayores de 6 años) pero en el producto 89, 106 muertos.
En la semana 50 figuran en el Deis 183 muertos mayores de 5 años, (misma cifra filtrado con mayores de 6 años) pero en el producto 89, 122

Entonces, ¿honestamente, tienen el despelote, hay 89 niños menores a 6 años muertos por covid con dosis de refuerzo o qué?

Cómo se explica esa diferencia. Las conjeturas dan para mucho. Quizás si fueran más específicos se entendería mejor para darle una buena lectura a las dos tablas y entender las diferencias.  

Sin mencionar que solo está definido esquema completo e incompleto, pero no el esquema de refuerzo en el Readme. 

Quedo atenta.

Gracias!

Saludos!!!

**Comment by dna33** [comment]
Hola, descarto categoricamente tu interpretación. No, los rangos etarias que no aparecen en el producto 90 es porque no se tienen registros de casos confirmados, ingreso a uci, o fallecimiento. Asi que el razonamiento no es correcto. 

Por el tiempo que dedico personalmente y el de mi equipo a contestarte, me permito hacerte esta invitación: te invito a usar el lenguaje de una manera más cuidadosa en temas que son sensibles, como el fallecimiento en general y en particular de personas menores de edad. Me refiero a que deberías reconocer en primer lugar que los cruces entre distintas fuentes que intentas hacer son espúreos, no es posible hacerlos con la información pública disponible, y por ende sería necesario expresar tus conjeturas de una forma mucho más exploratoria, reconociendo lo lejos de la verdad que pueden estar.

**Comment by daniamr** [comment]
Hola, gracias por tu invitación, pero no contestaste mi pregunta de;  cómo se explican las diferencias. Hasta donde sé, no hice una pregunta moral, hice una pregunta relacionada con los datos.


Sé que en el Deis solo aparecen 34 niños, de 0 a 5 años, fallecidos por covid desde inicio de pandemia. Por tanto, dudo a que se deba a eso. Sin embargo, dado a la definición de las variables y el tiempo transcurrido entre ambas tablas, el total de fallecidos en esquema de refuerzo debiese ser la misma cantidad. 


Lo explicaré así, si tienes 10 manzanas, en una la clasificas por color y en otra por tamaño, claramente, la distribución en ambas será diferente. Sin embargo siempre serán 10 manzanas. 


Por cuanto, si en el producto 89 dice que es a la semana epidemiológica correspondiente, se entiende que si una persona falleció en la semana 35, se contabiliza en la semana 35. Entonces al contrastarlo con el Deis, al mismo periodo, no cuadra. 


Ahora sí comparo los totales, entre el producto 90 y el 89, tampoco cuadran, entendiendo que la distribución en tiempo debiera ser diferente, pero los totales debieran ser iguales. No así en los demás esquemas, debido a que el periodo de tiempo observado es diferente (vale decir mayor tiempo en el producto 90 que el 89), por lo que no se puede saber. 


Además, es fácil decir que una conjetura es falsa, sin dar argumentos y explicaciones pertinentes. Los que saben son ustedes, no yo. Seria una falacia decir que algo es falso, solo porque desconoces los datos. "cruces entre distintas fuentes que intentas hacer son espúreos, no es posible hacerlos con la información pública disponible" 

Quedo atenta!

**Comment by daniamr** [comment]
y a qué se debe la diferencia?

**Comment by dna33** [comment]
Hola denuevo, ¿cuál es la nueva pregunta ahora, puedes especificar, por favor?

**Comment by dna33** [comment]
En principio, no son fuentes de datos que necesariamente se puedan cruzar. El DEIS opera en conjunción con el registro civil y presenta la información quizás más actualizada y con el sistema de observación más robusto que se puede acceder. Por otro lado, los datos del producto 89 vienen de los sistemas de información epidemiológicos, que tienen sistemas de observación menos robustos (las notificaciones obligatorias que se hacen en la APS).

 Dicho eso, algunas preguntas:
¿Los datos del deis que estas revisando, cuál es la causa de defunción?
¿Cuál es la definición de semana epi que estas usando?

**Comment by daniamr** [comment]
Respondo;
1. La causa de defunción es covid confirmado, vale decir U07.1 
2. Según calendario de semana epidemiológica de salud responde, ahí salen de qué a qué fecha es cada semana. 

Ósea, si los datos de la tabla 89 proviene de un sistema menos robusto, también son menos confiables. 
¿Qué es la APS?
¿Dónde se están esos datos en bruto (ósea no categorizados y no filtrados?

Quedo atenta, gracias.

**Comment by MinCiencia** [comment]
Los datos del deis se publican en deis.minsal.cl, la última publicación que contiene una base de datos donde cada fila es un caso anonimizado esta acá: https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2021_20012022.zip

Ahi pudes ver las edades de las defunciones, y el motivo también.

**Comment by daniamr** [comment]
No, esos datos ya los tengo. 

Me refería a los de APS. Que no sé que es y donde se ven los datos datos de APS, quiero ver la fuente del producto 89.

**Comment by MinCiencia** [comment]
La atención primaria de salud: https://redsalud.ssmso.cl/atencion-primaria-de-salud/ es el pilar fundamental de la salud pública de Chile, sus datos abiertos se consiguen a través de DEIS también. Los datos relativos a covid 19 que son públicos son los que estan en esta base de datos, no hay fuentes con mayores detalles. Hay varias personas que han intentado pedirlos por transparencia sin éxito.

**Comment by daniamr** [comment]
Ya muchas gracias!!!

**Comment by daniamr** [comment]
Demián, saqué la diferencia por semana y total. El producto 89, solo tiene contabilizado el 75% de las muertes que figuran en el Deis. 

Sabrás cuál es el criterio? O qué está pasando? Porque 849 muertos de menos no es menor... 

![20220127_211727](https://user-images.githubusercontent.com/93507862/151464820-b055fcf2-521f-4efc-a6ba-110016a11691.jpg)

**Comment by MinCiencia** [comment]
NOTA ACLARATORIA, desde Minsal, que agregaremos a los productos 89 y 90:
El producto 89 presenta los eventos de casos, ingresos UCI y defunciones, según ocurrencia en la semana de reporte. Estos son consolidados sin una actualización retrospectiva, por lo cual podría presentar diferencias con otros reportes que se emiten en paralelo.

El producto 90 presenta las cifras de casos, ingresos UCI y defunciones según semana de inicio de síntomas, no por  ocurrencia del evento, con actualización retrospectiva semanal, por lo cua

**Comment by daniamr** [comment]
Por lo cual? Quedó como a media frase 👀

**Comment by MinCiencia** [comment]
si, fue puesa recién, como dice el mensaje.

**Comment by daniamr** [comment]
Sí me di cuenta después de preguntar, que decía "agregaremos". 

Gracias!!!

**Comment by daniamr** [comment]
Oye una duda, pero si no los modifican, porque hay 2 cambios en el producto 89? 

En la tabla antigua, donde es hasta la sem. 41, figura que en la semana 40, 1735 casos sin esquema completo, pero ahora en la nueva figuran 1691. 

Además en la semana 41, en la tabla antigua figura 5523 casos en esquema completo, pero en la de ahora 5522.

A qué se deben esos cambios?
