### ISSUE TITLE
Por favor actualizar la Información COVID19/input/Vacunacion/carga_vacunacion_sem_epi.csv

### ISSUE THREAD

**Issue by hco1975** [MinCiencia/Datos-COVID19#1229]
No se actualizó hasta el momento la información de COVID19/input/Vacunacion/carga_vacunacion_sem_epi.csv con los datos de la semana pasada.

Con estos datos se completa Producto90.

Por favor actualizar, sobre la semana pasada, donde tuvimos peak de contagios.

**Comment by MinCiencia** [comment]
actualizado, b913693d1146b11311c4e812941d548db8641544
