### ISSUE TITLE
datos repetidos

### ISSUE THREAD

**Issue by cmcgato** [MinCiencia/Datos-COVID19#1231]
hola, los datos de la actualización del producto 19 de hoy sábado son iguales a los del miércoles 26.

![Captura de Pantalla 2022-01-29 a la(s) 13 54 49](https://user-images.githubusercontent.com/70454388/151669857-6759d437-fc99-470d-b590-57c6a2f7d22e.png)

saludos y gracias por todo el trabajo

**Comment by ishmaster** [comment]
Estimados:

Adicional a lo comentado por @cmcgato, favor revisar los últimos datos del producto 1 ya que son iguales a los del 24-01-2022.

**Comment by MinCiencia** [comment]
Cierto, gracias por reportar. Corregido: 52915ec8b4f49c033713d786e6ba8ff189b1fa17
