### ISSUE TITLE
Producto 37 - Defunciones DEIS - Falta actualizar Sospechosos al 28/Ene

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1233]
Hola, falta actualizar sospechosos según última actualización del DEIS al 28/Ene.   Gracias

**Comment by Jorgecibia** [comment]
Aun sin actualizar y ya hay otra actualización al 5/Feb, algún comentario ?

**Comment by IgnacioAcunaF** [comment]
Actualizado los productos p37, p50 y p84 en commit [c2c6b95](https://github.com/MinCiencia/Datos-COVID19/commit/c2c6b9534222b7ed7cf612f2f291b3dd31192195)
