### ISSUE TITLE
Actualizar productos para ICOVID y revertir la lectura a nuestro repositorio, gracias.

### ISSUE THREAD

**Issue by datagovuc** [MinCiencia/Datos-COVID19#1237]

**Comment by Jorgecibia** [comment]
Esto tiene que ver con los productos 55 y 65 que no están actualizados ?

**Comment by datagovuc** [comment]
el 55 sí

**Comment by IgnacioAcunaF** [comment]
Actualizado en el PR #1241 para fecha 20220202, y revertida la lectura al repositorio
