### ISSUE TITLE
No reportar "recuperados"

### ISSUE THREAD

**Issue by jorgeperezrojas** [MinCiencia/Datos-COVID19#124]
Estimados y estimadas,

@dna33 me recomendó abrir un issue acá por este tema. No me imaginé que fuera a tener algún futuro o impacto, pero tal vez sí lo tiene si los ingenieros e ingenieras a cargo consideran mi punto de vista y los antecedentes. 

El dato que reportan como "recuperado" (hoy en el archivo https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5/TotalesNacionales.csv) no sigue ninguna norma ni estándar, ni es semánticamente consistente con lo que una persona común y corriente consideraría como un paciente recuperado. De hecho, hay pacientes que en este momento están en la UCI conectados a un ventilador artificial y son contados como recuperados según ese número. Las recomendaciones del consejo asesor COVID son sumamente claras (miren esta entrevista por ejemplo https://ciperchile.cl/2020/05/01/el-sistema-de-salud-ha-respondido-bien-pero-estamos-lejos-de-decir-que-superamos-la-primera-ola/). Sin embargo el Minsal lo calcula con la fórmula (`recuperados[t] = confirmados[t-14] - muertos[t]`) lo expliqué con un poco más de detalle (identificando a algunas personas recuperadas) acá: https://ciperchile.cl/2020/04/30/academico-acusa-que-estadistica-del-minsal-considera-recuperados-a-personas-que-estan-en-riesgo-de-morir/

Mas aún, ni los informes Epidemiológicos (https://www.gob.cl/coronavirus/cifrasoficiales/#informes) ni los informes de situación (http://epi.minsal.cl/informes-covid-19/) reportan el dato de "recuperado" (pueden hacer un CTRL+F en cualquiera de los archivos). 

Por otro lado, los datos que ustedes hacen disponibles acá son usados por muchas personas para hacer visualizaciones que reportan los recuperados y que luego otra gente ve. El Minsal les pone un "👍" en sus cifras oficiales. Esto es un muy mal mensaje si lo que queremos es transmitir la realidad del riesgo que Chile está empezando recién a vivir y entre todos tenemos que tratar de ser responsables en lo que nos compete a cada uno.

Entiendo que las cifras pueden tener una definición técnica clara (sinónimo de "no activo" por ejemplo), pero cuando tenemos una posición de más información que otras personas, podemos hacer una diferencia con pequeñas decisiones. Piensen que absolutamente ningún ciudadano (niguno) fuera de Chile recibe este mensaje de las autoridades. Nosotros somos el único pais del mundo que calcula "recuperados" con una fórmula (hace poco nos empezó a copiar Uruguay).

Por esto, creo que sería muy bueno que dejaran de reportar esa cifra con ese nombre. Mi impresión es que el Minsal también debiera dejar de reportarlo, pero no le puedo abrir un issue al Minsal.

Saludos

**Comment by alonsosilvaallende** [comment]
Totalmente de acuerdo con @jorgeperezrojas Además como lo reporta Ricardo Baeza la diferencia podría ser más del doble de lo que la gente entiende por recuperado (https://twitter.com/polarbearby/status/1256673287356051456?s=21 ). Se podría inventar un nombre que sin ser despectivo no se preste a malas interpretaciones de los ciudadanos.

**Comment by jorgeperezrojas** [comment]
Mientras en el MinCyT toman una decisión, invito a todos y todas los que usan estos datos para cualquier cosa que tenga que ver con entregar información (recopilarlos o hacer visualizaciones, reportes o informes) a no reportar el número de "recuperados" en sus respectivos sitios, o, si lo quisieran reportar de todas maneras, incluir un DISCLAIMER tan grande y visible como se pueda de que el número **no son** personas que se han recuperado del COVID si no la fórmula que indico. Entre todos podemos hacer una diferencia por pequeña que sea. Cada persona que mira nuestros datos puede empezar a recibir un mejor mensaje que comunique de manera más efectiva el riesgo en el que estamos. Mas vale tarde que nunca.

**Comment by ivanMSC** [comment]
Estos ultimos dos dias, el minsal ya no usa la formula de los 14 dias. Los numeros ya no cuadran con la formula.

**Comment by ivanMSC** [comment]
Puedes hacer un estudio de simulación Montecarlo y si asumes que en **promedio** la gente se recupera en 14 días, entonces la formula no está mal. Tiene **poca** variabilidad respecto de la dispersión de la variable de días para la recuperación.

Lo único que es polémico es el promedio de 14 días. La curva real de recuperados es solo sensible (muy sensible) al **promedio** de días para la recuperación de los pacientes. 

No necesitas saber exactamente cuándo se recupera cada paciente para tener un buen indicador del total de recuperados. Solo necesitas saber el promedio.

Lo que deberían hacer es estudiar unos 1000 pacientes. Es decir, hacer 1000 tests de salida y estimar el promedio de días para la recuperación total. Ahí recién tendrá validez la formula.

Si el Minsal demuestra que efectivamente el promedio es de 14 días, entonces la fórmula está bien. Si resulta que el promedio es de 30 días, habrá que correr la formula de nuevo.

Qué dice la OMS respecto del promedio de días para la recuperación?

**Comment by saangel** [comment]
@ivanMSC , sobre lo último: en febrero salió un reporte tras estudio de los casos _reportados_ en China que dice "Using available preliminary data, the median time from onset to clinical recovery for mild cases is approximately 2 weeks and is 3-6 weeks for patients with severe or critical disease.", ver https://www.who.int/docs/default-source/coronaviruse/who-china-joint-mission-on-covid-19-final-report.pdf página 14

**Comment by jorgeperezrojas** [comment]
El comité asesor es sumamente claro en su recomendación:

``` 
Nosotros hicimos una recomendación de cuándo considerar que una persona dejaba de ser contagiante, que en el fondo es el concepto de recuperado. Ese número corresponde a las personas que están asintomáticas a los 14 días desde que empezó la enfermedad, en aquellos que nunca estuvieron hospitalizados; y 14 días después del alta médica en aquellos que estuvieron hospitalizados, y que están sin síntomas; y las personas que están con síntomas, tienen que ser evaluadas por un médico. Un fallecido obviamente que no es un recuperado, y una persona que está hospitalizada tampoco se puede contar a los 14 días, sino desde el alta. Es un trabajo un poco más detallado.
``` 

https://ciperchile.cl/2020/05/01/el-sistema-de-salud-ha-respondido-bien-pero-estamos-lejos-de-decir-que-superamos-la-primera-ola/

Mi punto no es técnico sino comunicacional. Para mí es irresponsable reportar un número a la ciudadanía con una carga semántica tan fuerte como "recuperado" cuando realmente nos referimos a cualquier otra cosa técnica. Por otro lado, si nos vamos a lo técnico, ningún informe científico de Epi Minsal usa el término de "recuperado". Dado que además el comité asesor propuso una metodología que no se cumple, este número reportado acá como "recuperado" parece muy poco serio (un artefacto de "marketing"). Y no solo eso, si no que puede llevar a equivocaciones de la ciudadanía. Este es un repositorio científico que mira mucha gente. Tratemos de entender que cada decisión que tomamos afecta como se desarrolla esta pandemia en adelante. Reportar "recuperados" personalmente considero una irresponsabilidad científica.

**Comment by rebollodani** [comment]
abri un issue hace una semana acerca de lo mismo, lo he reclamado en todos los idiomas y nada..... es mas, ahora con la incorporación de datos de pacientes positivos asintomáticos el dato de recuperados es un numero que tiene cero trazabilidad ya que antes respondía a una resta y ahora es cualquier número). Mi issue lo respondieron con algo absurdo como … la información esta en el producto xxx e incoporaremos la definición de recuperados en el read me.. cueck….

**Comment by jorgeperezrojas** [comment]
Nada que hacer al parecer. Este ya no es un repositorio científico ni algo crítico que realmente ayude a tomar decisiones. Parece nada más una página Web de gobierno con poca conciencia en lo que los datos pueden generar en la audiencia y en la ciudadanía. Todos los que estamos usando este repositorio de paso estamos ayudando a esparcir información poro rigurosa. La verdad es que es una pena :(

**Comment by MinCiencia** [comment]
@alonsosilvaallende ¿qué nombre recomiendas para esa serie?

**Comment by alonsosilvaallende** [comment]
@MinCiencia Antes hubiera dicho "casos confirmados no fallecidos a 14 días" pero me parece que cambiaron la fórmula nuevamente, así que ahora no sé. De hecho, yo no los utilizo ni tampoco el concepto de casos confirmados activos porque se calcula con ese 'recuperados' que no es tal.

**Comment by MinCiencia** [comment]
Muy bien, @alonsosilvaallende. En ese sentido, ¿viste el dato de fecha de inicio de síntomas (fis)? Ese se reporta a nivel comunal agrupado por semana epidemiológica, en el informe epidemiológico la distinción que se usa para "activos" es de 14 días desde la fis.

**Comment by dna33** [comment]
El grupo de Ciencia y Vida, Neurociencias UV y USS hizo este resumen basado en el trabajo de otro grupo, basado en evidencia secundaria a la fecha (_peer reviewed_): 
![WhatsApp Image 2020-05-10 at 10 10 50 AM](https://user-images.githubusercontent.com/12438811/81506311-6e98b100-92c3-11ea-98ba-785f1309b273.jpeg)
Lo que encuentro interesante es que FIS es una línea base, sobre la cuál se pueden hacer proyecciones de activos en base a esta evidencia secundaria, ¿sirve?

**Comment by jorgeperezrojas** [comment]
Muchas gracias por el gráfico @dna33 sería genial que pudieran explicar con detalle entonces a qué corresponde el número reportado todos los días en este repositorio etiquetado bajo el nombre de recuperado, eso daría mucho más claridad a las personas que utilizan los datos publicados. Gracias

**Comment by MinCiencia** [comment]
Para contribuir al análisis, publicamos el total de inscripciones de nacimientos y defunciones del registro civil, por comuna, con update diario:

[Data Product 31](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto31) - Nacimientos en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Nacimientos inscritos en el Registro Civil de Chile, desde el 2010 a la fecha, actualizados diariamente.

[Data Product 32](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto32) - Defunciones en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Defunciones inscritas en el Registro Civil de Chile, desde el 2010 a la fecha, actualizadas diariamente.

**Comment by jorgeperezrojas** [comment]
Hola,

Al parecer los "recuperados" siguen sin ser calculados siguiendo algún criterio clínico. Tampoco es real lo que dicen de que "han testeado negativo". De hecho, los "nuevos recuperados" siguen calculándose como los "nuevos confirmados" 14 días atrás, menos los muertos del día actual. Acá pueden ver un ejemplo de cálculo para el 19 de mayo. 

![Screen Shot 2020-05-23 at 18 10 46](https://user-images.githubusercontent.com/15633182/82744281-49d11e80-9d44-11ea-9fe2-6d332e4f6551.png)

Pueden hacer ustedes mismos el cálculo para los días desde el 14 de mayo en adelante. Es sumamente frustrante que en un repositorio científico no entiendan bien el significado del número que están reportando.

Vuelvo a insistir en el título de este issue. ¿Podrían por favor dejar de reportar "recuperados"? 

Si lo quieren seguir reportando, ¿podrían por favor especificar claramente con un warning al inicio del repositorio que este número es una fórmula desde otros números? Creo que es una muy mala señal a la ciudadanía si no lo hacen. Mucha gente usa los datos de este repositorio para graficar e informar y estamos en una situación crítica en donde nada de lo que hagamos es inocuo. 

Gracias

**Comment by jorgeperezrojas** [comment]
Finalmente el minsal decidió no reportarlo mas. Espero que no hagan el cálculo desde los activos en este github y podamos por fin empezar a comunicar de manera razonable las cifras a la ciudadanía.

Este issue ya puede cerrarse. Saludos
