### ISSUE TITLE
Actualización Datos de hoy 9 Feb pendiente

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1246]
Hola, que pasa con actualizacion de hoy de los productos diarios, yo uso el 09, el 10, 37, 01, 03 .... etc

Gracias

**Comment by IgnacioAcunaF** [comment]
Hola, [el workflow del balance diario ](https://github.com/MinCiencia/Datos-COVID19/actions/runs/1818767755)de hoy 09 de febrero tuvo un código de error, por lo cual fue ejecutado nuevamente. 
Ahora se encuentra actualizado. 
Gracias por reportar
