### ISSUE TITLE
Producto 37 - Defunciones por COVID sin actualizar el día de hoy 10/feb

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1249]
Hola, falta actualización de hoy del producto.  gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia,
Gracias por el aviso. Se actualizaron los archivo de input y se están generando los archivos del producto en el [workflow](https://github.com/MinCiencia/Datos-COVID19/actions/runs/1826728920) en este momento.

**Comment by IgnacioAcunaF** [comment]
Fe de erratas: se estaban actualizando los productos de TTA. Voy a revisar el 37

**Comment by Jorgecibia** [comment]
Ok, gracias, quedo atento

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Actualizado producto 37 en el commit 22dee4a9787ac8a30d591f13786af201a21b32aa.
Gracias por reportar

**Comment by Jorgecibia** [comment]
Gracias
