### ISSUE TITLE
Producto 92 - Evolución semanal de ingresos a hospitalización por covid sin actualizar el día 10 febrero

### ISSUE THREAD

**Issue by alonsosilvaallende** [MinCiencia/Datos-COVID19#1250]
Hola,

La actualización de la evolución semanal de ingresos a hospitalización por covid no se actualizó el día 10 de febrero (se actualiza normalmente cada 7 días). Muchas gracias.

**Comment by IgnacioAcunaF** [comment]
Actualizado en commit c6c54ce0f8acce265648cc62b56d80d8793c2f74.
Gracias!
