### ISSUE TITLE
Error en la última carga de informe epidemiológico, Producto 19 (datos del sábado)

### ISSUE THREAD

**Issue by sebarivas** [MinCiencia/Datos-COVID19#1254]
Estimados, los datos para este sábado en el Producto 19 (Informe Epidemiológico) están repetidos con los inmediatamente previos. Les agradecería mucho si lo pueden revisar y corregir donde corresponda. Saludos y buen fin de semana!

**Comment by IgnacioAcunaF** [comment]
Hola @sebarivas
Gracias por reportar. Mirándolo actualmente.

**Comment by IgnacioAcunaF** [comment]
@sebarivas 
Actualizados los productos del Informe Epidemiológico para este sabado.
Se realizó un revert a estos cambios duplicados (b86c4c613db83f86fed5b403a55a360512df22af), y luego se volvió a ejecutar el proceso de actualización (a9faf1d5b0c9e00e2d2182e6e3c95e5813ad44b4).

La razón fue debido a que el pre-procesamiento automatico de los datos consideró el archivo anterior (07-02-2022), lo que generó la duplicación. Se actualizó para los datos del 11-02-200.

Gracias por reportar.
Buen fin de semana
