### ISSUE TITLE
Producto 37 - No actualizado 13 Feb y 14 Feb

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1257]
Hola, falta actualizar los fallecidos agregado hoy en en el producto.  Gracias

**Comment by MinCiencia** [comment]
Hola, actualizado en b9d4f647f4354254b53d82830821294299a95b58, muchas gracias por reportar.

**Comment by Jorgecibia** [comment]
Gracias, estamos ok, saludos. muy buen trabajo hacen uds

**Comment by MinCiencia** [comment]
Póngalo en sus redes sociales para que más gente lo valore, muchas gracias por difundir.
