### ISSUE TITLE
Antiguo, pero para revisar.  Datos duplicados en archivo INPUT /input/ReporteDiario/CasosConfirmadosTotales.csv

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1258]
Probando con datos históricos con archivos de entrada, me saltaron varias fechas duplicadas. 
Es este archivo, están duplicados las fechas 2021-06-15 al 2021-06-21. 
Saludos!

**Comment by IgnacioAcunaF** [comment]
Hola @ctroncoso,
Arreglado en 9675e1d99ea4e1517b124737f28fff38d5542283

Gracias!
Saludos
