### ISSUE TITLE
Error en el último informe epidemiológico publicado hoy 16/02/2022

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#1259]
En el archivo [output/producto16/CasosGeneroEtario.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto16/CasosGeneroEtario.csv), la columna 2022-02-14 parece  tener los mismos valores que 2022-02-07.

**Comment by MinCiencia** [comment]
Cierto, el ultimo informe completo venía con los datos del 7 de febrero, corregimos en este commit: bb2a5630638722e79e4849027a9fe842a7767346

**Comment by juancri** [comment]
Gracias!
