### ISSUE TITLE
Pendientes

### ISSUE THREAD

**Issue by MinCiencia** [MinCiencia/Datos-COVID19#1263]
- [x] 1. Automatizar carga de productos legados por grupo ICOVID
- [x] 2. Automatizar carga de incidencia en vacunados
- [x] 3. Automatizar carga de indicadores de testeo y trazabilidad

**Comment by IgnacioAcunaF** [comment]
Voy con el 1

**Comment by IgnacioAcunaF** [comment]
1. Listo en e0565179847e8b9092272f4daf18cb1b1f52378a

**Comment by IgnacioAcunaF** [comment]
2. Listo en e91114f37384c3e2124ff2ca25fba63d35474af5

**Comment by IgnacioAcunaF** [comment]
3. Listo en cde6e6c63d13dbd49cd3bdb1395faebe3d5853f7 y 84e9f16321027eda1e1bbf305b1b85607cee5c36
