### ISSUE TITLE
Producto14 - Ajuste datos

### ISSUE THREAD

**Issue by aifuenzalida** [MinCiencia/Datos-COVID19#1267]
Estimados:
Favor corregir los valores del Producto14, ya que en los dias 2020-06-29 y 2020-06-30 se añadió un .0 al final y puede generar inconsistencias, al no ser de la misma estructura de datos que los otros dias.

**Comment by IgnacioAcunaF** [comment]
Hola @aifuenzalida 
Gracias por reportar. Ajustado en 550efb5454cd41d0c12de3b1c9389e6b670bab4d.
Saludos!
