### ISSUE TITLE
Error en Columna sin_vac_casos Producto90

### ISSUE THREAD

**Issue by hco1975** [MinCiencia/Datos-COVID19#1270]
Error en columna sin_vac_casos en Producto90, aparece en 0 en todas las semanas.

![image](https://user-images.githubusercontent.com/95724160/156260184-d89a4462-c2b7-4ac2-bb9e-89cab4db5563.png)

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar.
Cerrado en f32351f3c405531967bb6a8b0910fe3a9697982d
