### ISSUE TITLE
No hay actualización del reporte diario para el 01/03/2022

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#1271]
Al parecer, no se actualizó el reporte diario hoy martes 1ro de marzo, 2022.

https://github.com/MinCiencia/Datos-COVID19/raw/master/output/producto3/CasosTotalesCumulativo.csv

**Comment by MinCiencia** [comment]
corregido 0be081d4dfa8a68ea6f50ca27865f25a7afe9c86, gracias por reportar.
