### ISSUE TITLE
Productos 76 y 77 sin actualizar, esta con datos vacunación al 22/Feb

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1272]
Hola, es factible actualizar.  Gracias

**Comment by MinCiencia** [comment]
Han habido dificultades de parte de DEIS en la entrega de estos archivos, la próxima semana comunican podrán resolverlos. Por ahora su envío es intermitente, el último recibido corresponde al 25 de febrero.

**Comment by Jorgecibia** [comment]
Gracias, estare atento, ahora esta actualizado al 3/Mar. saludos

**Comment by patriciorojasm** [comment]
Hola. Quisiera saber que significan las columnas que van de la 3 a 80, ya que no llevamos 80 semanas de vacunacion. Ademas queria pedir que se complete la informacion de las filas (regiones). Esto pasa en varios productos relacionados con la vacunacion. Gracias

**Comment by ctroncoso** [comment]
> Hola. Quisiera saber que significan las columnas que van de la 3 a 80, ya que no llevamos 80 semanas de vacunacion. Ademas queria pedir que se complete la informacion de las filas (regiones). Esto pasa en varios productos relacionados con la vacunacion. Gracias

¿A cuál de todos los archivos te refieres?

**Comment by patriciorojasm** [comment]
Producto 77, archivo  total_vacunados_region_edad.csv

**Comment by ctroncoso** [comment]
> Producto 77, archivo total_vacunados_region_edad.csv

Cuando tengas esas dudas, revisa el archivo `std`  [total_vacunados_region_edad_std.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto77/total_vacunados_region_edad_std.csv)
Usualmente vas a encontrar la misma data en 3 formatos. 
* con solo series, `std`
* una normal en forma de pivot
* y otra transpuesta `T`

En ese se muestran los datos en forma de series. 
Y puedes ver que corresponden a las edades. 
![image](https://user-images.githubusercontent.com/121016/159089122-3f965bf1-8b47-4060-961a-c88f0d5feca9.png)

**Comment by patriciorojasm** [comment]
El archivo _std tiene en el mismo problema, no hay nombres de region (primera columna) a partir de la fila 56. Aparecen en la columna 92, y vuelven a desaparecer en la 146.  Esto es similar a lo que pasa en  total_vacunados_region_edad.csv
Adjunto pantallazo.
El archivo _t tampoco tiene los nombres de la region a partir de la columna 56, similar al archivo original que no los tiene en las filas.
Adjunto pantallazo.

Ademas está la pregunta original, a que corresponden las columnas enumeradas entre 3 y 80 en el archivo  total_vacunados_region_edad.csv ? Supongo que son fechas y no numero de semana, pero no aparecen las fechas. 
Espero haber sido mas explicito.

![Screenshot from 2022-03-18 20-48-07](https://user-images.githubusercontent.com/18587387/159098202-a8c433a8-6ea2-45eb-956c-f3d400efd429.png)

![Screenshot from 2022-03-18 20-49-25](https://user-images.githubusercontent.com/18587387/159098206-91d4563f-f58c-4832-b254-ee35a9d9337d.png)

**Comment by ctroncoso** [comment]
@patriciorojasm Posiblemente las regiones vacías corresponden a las "Desconocida" que hay en otros informes. Eso lo tendrían que confirmar con los datos originales el @MinCiencia 

Respecto a los 3-80, son edades.

**Comment by patriciorojasm** [comment]
Excelente, estaba buscando el PR76. Muchas gracias por todas las explicaciones

**Comment by ctroncoso** [comment]
Un gusto @patriciorojasm !

**Comment by Jorgecibia** [comment]
Hola, estamos con retraso de una semana en la información, hay una periodicidad para actualizar este producto con datos vacunación ?

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Actualizado el producto 76 (75f52abe3ce33c772b53cd61c323a0400df5f229).

Estas últimas semanas ese producto había estado siendo actualizado de forma manual, pero afinamos el proceso automático (3174eeed42939c313dd8dff4a9dd8c880db00bd6).

Saludos
