### ISSUE TITLE
Por Favor Actualizar Producto90 con información de semana epidemiológica 2022-08

### ISSUE THREAD

**Issue by hco1975** [MinCiencia/Datos-COVID19#1274]
Estimados:

     Por favor actualizar Producto90 con la información de semana pasada 2022-08. Además revisión de error en casos semanales de no vacunados (columna se encuentra en 0)

**Comment by hco1975** [comment]
Hola. Actualizar semanas 2022-08 y 2022-09 (antepasada y pasada).

Además revisión de error en casos semanales de no vacunados (columna se encuentra en 0)

**Comment by IgnacioAcunaF** [comment]
Revisado el error en el producto 90 (f32351f3c405531967bb6a8b0910fe3a9697982d) y la actualización para la semana 2022-09.
Dejo abierto este issue a la espera de la actualización semana 2022-10
