### ISSUE TITLE
Productos 15, 16 y 39 con problemas en actualización EPI

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1275]
Hola, 

Por favor, hubo problemas en la actualización de los datos EPI de hoy sábado. 
Por ejemplo, el producto 16 tiene repetidas las últimas 2 filas. 

Ojalá lo puedan arreglar, 

Saludos cordiales,

**Comment by dna33** [comment]
cierto, corregido en https://github.com/MinCiencia/Datos-COVID19/commit/e641a10290bea49f8ec692dc3972b74aa204c139
