### ISSUE TITLE
Producto 90 con error: 2da columna con 0s

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1276]
Estimados, el producto 90 se actualizó con errores. Los casos sin vacuna de la segunda columna solo aparecen 0s

Favor verificar. 

Gracias

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @weichafan por reportar.
Solucionado en el commit f32351f3c405531967bb6a8b0910fe3a9697982d
