### ISSUE TITLE
Informe epi con datos erróneos

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#1279]
El informe epi [publicado hoy](https://github.com/MinCiencia/Datos-COVID19/commit/79bcaa6f154569bb315a5f910abc5ba8326b89e0) tiene datos erroneos. Por ejemplo:

|Grupo de edad |Sexo |... |2022-03-04 |2022-03-07 |2022-03-11
|-|-|-|-|-|-
|00 - 04 años |M |... |52210 |53389 |164

https://github.com/MinCiencia/Datos-COVID19/blob/79bcaa6f154569bb315a5f910abc5ba8326b89e0/output/producto16/CasosGeneroEtario.csv

**Comment by IgnacioAcunaF** [comment]
Hola @juancri 
Estamos revisando con el Ministerio de Salud los archivos de input de ese informe. 
Mientras tanto, podrias indicarnos si has encontrado otros archivos derivados de ese informe con errores?

Saludos

**Comment by IgnacioAcunaF** [comment]
Hola @juancri 
Hicimos las correcciones y actualizamos los informes epidemiológicos
Cierro este PR, quedamos atentos a cualquier otro comentario y/ observación. 
Saludos
