### ISSUE TITLE
Actualización de producto diario no se generó correctamente. Producto 5 del cual dependen otros procesos no se actualizó para día 12.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1283]
Estuve revisando el código del proceso de actualización de producto diario y creo que hay un concepto que puede estar generando muchos de los errores cuando la actualización no se corre el mismo día de la generación del archivo input. 

En esta línea se toma la fecha de HOY, 
https://github.com/MinCiencia/Datos-COVID19/blob/7481c81797a23366355eb7a4ebf0856abfd44e43/src/reporteDiario.py#L102-L103

y es usada aquí como referencia a "última línea". 
https://github.com/MinCiencia/Datos-COVID19/blob/7481c81797a23366355eb7a4ebf0856abfd44e43/src/reporteDiario.py#L118

El dilema es que si el proceso se corre pasada la medianoche UTC (ojo que no corre en Chile), la fecha de referencia no será la correcta. 

Recomendaría cambiar por un `.max() `, para que haga referencia a la ultima fecha del archivo y no depender de cuándo se ejecuta el proceso de actualización.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso.
Tuvimos un contratiempo con los archivos diarios de los ultimos días, pero se realizo la recarga manual (commit 7953a7c0fdcd32df782502d8e3ef5888e1df9cc7 por ejemplo)

Revisaremos la propuesta para las fechas.
Gracias!

**Comment by IgnacioAcunaF** [comment]
Hola @ctroncoso 
Solo para hacer follow up: tomado el issue. Como comentas, esas lineas generan casos de borde no deseados.

Abordado de la siguiente manera 90b3b24297df7a276e5ace8fb948e6b7d751a806

**Comment by IgnacioAcunaF** [comment]
Pasó tb el comentario del PR:

"La siguientes lineas comentadas de código tienen el supuesto de que el procesamiento ocurre el mismo día del informe diario. Sin embargo, puede darse un caso de borde en el cual este procesamiento no ocurra el mismo día, por ejemplo, se atrase un día el procesamiento.

Un caso hipotético: si el día 17 de un mes se procesa el informe del día anterior es decir, del 16, la información del día 17 quedaría registrada con los datos del día 16.
Es por lo anterior que le fecha de procesamiento se modificó al último insumo disponible el cual se encuentra en la carpeta input/ReporteDiario/CasosConfirmados con la fecha del reporte en cuestión"

**Comment by ctroncoso** [comment]
Impecable! ahora depende del contenido. 
PD: buena solución para la serie de archivos con fechas en los filename!
