### ISSUE TITLE
Error actualización Producto37 (14 marzo 2022)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1284]
Hola,
Actualización realizada corresponde a los registros del reporte de ayer 13 marzo 2022 y no al de hoy 14 marzo 2022.
Fallecidos U071 (reporte 13 marzo 2022): 43.879
Fallecidos U071 (reporte 14 marzo 2022): 44.005

Saludos.

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar.
Actualizado en b552a0099cd7fd6e764ef8b157be927ebf3374d3

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar, 
Estamos conversando con los equipos para obtener el insumo para actualizar.
Saludos!

**Comment by IgnacioAcunaF** [comment]
Actualizado para el miércoles 16 en el commit 40b3e7b3ddfd81fd127cdfa603d9b25d8c5f71a3.
Estaremos pendientes para el día de hoy tb, si no lo procesaremos manualmente.

Saludos!

**Comment by dafernandez75** [comment]
Hola,
se repite el error de actualización y/o fallo el proceso manual antes descrito para hoy 17 marzo 2022, se actualiza solo hasta los registros de ayer 16 marzo 2022 y no según lo reportado para el día de hoy.
Saludos.

**Comment by dafernandez75** [comment]
Hola,

Con respecto al actualizado de hoy que ya está actualizado según reporte, existen más registros de fallecidos según lo que indique en el punto anterior por el Deis, por qué razón no consideraron todos los registros?. 

Es decir, los registros que ya estaban a disposición por el Deis el día jueves 16 marzo 2022, serán publicados por este repositorio mañana sábado 19 marzo 2022 ?.

**Comment by IgnacioAcunaF** [comment]
Hola @dafernandez75 
Gracias por el comentario.
En efecto, una vez por semana actualizamos en base al reporte del DEIS en la URL que nos comentas, al momento de su publicación. Esa actualización automática en el GitHub estaba programada para ejecutarse el día de ayer, pero el proceso tuvo un inconveniente que estamos depurando.

Fue actualizada en el commit
d0cb9ee98f33adacb088992c1961416babbae448 recientemente, donde U071 se referencia como confirmados, y U072 como sospechosos.

Muchas gracias

**Comment by dafernandez75** [comment]
En resumen, con lo actualizado a la fecha y hora en este repositorio, estaría pendiente de registrar +101 fallecidos U071, con los registros del Deis al 17 marzo 2022.
Ayer según Deis eran +194 U071, que lo separaron acá en +93 U071 para hoy 18 marzo 2022 y por defecto serán +101 para mañana 19 marzo 2022.  

He seguido desde su creación este repositorio, lo que pasa es que el Deis normalmente los días sábados dejaban a disposición  los registros hasta el jueves de la misma semana (U071,U072,U099). Ahora el Deis ha mejorado los tiempos de entrega, ya que los 2 últimos jueves el Deis en la tarde del día está subiendo los registros de fallecidos (con registros hasta el miércoles de la misma semana).
Lo que es extraño, es por qué el Minsal en su reportería está separando los registros de fallecidos del Deis en dos días, me explico.
