### ISSUE TITLE
Posible error de fecha en última actualización de datos de informe EPI

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1287]
La última actualización de datos del informe epi aparece con fecha "2022-03-13", lo cual no calza con un intervalo de 7 días con respecto a la actualización de la semana pasada.  Se esperaba que tuviese fecha "2022-03-14"

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/68602/158706801-4653c47f-e251-4b7b-ac15-ac46d949d17e.png">

**Comment by ctroncoso** [comment]
El error proviene de la fuente, al menos para el PR1
input/InformeEpidemiologico/CasosAcumuladosPorComuna.csv


![image](https://user-images.githubusercontent.com/121016/158708383-feb847d4-f42a-4fca-94ac-7332854b5354.png)

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @elaval por reportar.
Como bien menciona @ctroncoso, el input del informe esta asociado a esa fecha (con un día menos que lo esperado). 
Estamos haciendo la traza del procesamiento (ya que hay un pre-procesamiento por nuestro lado para generar ese input), para ver si se generó en esa etapa, o en caso contrario, revisarlo con Minsal.

**Comment by IgnacioAcunaF** [comment]
Estimados, como actualización:
Nuestra revisión y traza indica que fue del pre-procesamiento de los datos al asignar el nombre de la columna, y no del insumo original.
Estamos trabajando en una mejora para que esto no vuelva a ocurrir, y para cambiar el nombre de la columna de los productos.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en be1f9adb0798f6dcccf12d53c2ce52a0023bd8d4 con datos nuevos y rectificado el día 14.

Saludos!
