### ISSUE TITLE
Producto 37 con datos atrasados

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#1289]
Estimados:

Los datos del producto 37 están desfasados un día, lo publicado hoy corresponden a lo comunicado el día de ayer.

Favor subir los datos que correspondan a las cifras oficiales del día.

Gracias,

Eduardo

**Comment by IgnacioAcunaF** [comment]
Hola @EduardoB-Chile 
Datos actualizados en 1d90c4134207d933b1cf32e736083c140bd2969e

Saludos!
