### ISSUE TITLE
Actualización producto 22: hospitalizados x edad 

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1293]
Estimados, 

Esta semana no se han publicado informes epidemiológicos donde se informaba acumulado de pacientes hospitalizados divididos en algunos rangos etarios.  No sé si los informes en pdf se discontinuarán. Pero si fuese el caso, podrían volver a publicar esta información en el producto 22? 

Lleva 5 meses sin actualización. 

Saludos cordiales,

**Comment by IgnacioAcunaF** [comment]
Hola @weichafan,
Estoy revisando el producto 22. Comentó con más detalles lo antes posible.

Saludos

**Comment by IgnacioAcunaF** [comment]
Update: 
@weichafan vamos a actualizar el producto 22 con los próximos informes epidemiológicos, y actualizar retroactivamente la información faltante. 
Mañana subiremos el update (estamos cargando los archivos de los días faltantes)

**Comment by IgnacioAcunaF** [comment]
Actualizado en ac9864ccdb13d64ba50aa8415768b513cd68118a, y realizadas las modificaciones para su actualización automática con el resto de los productos.

Saludos
