### ISSUE TITLE
Actualización Productos 76 y 77 - Vacunas 

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1294]
Hola, van 9 dias sin actualizar, alguna estimación para tener datos actuales ?.  Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Tuvimos un inconveniente con el mecanismo de traspaso de los insumos para la generación de estos productos, el cual estamos solucionando.
El día de mañana probablemente haya una actualización manual de estos productos, en cuanto automatizamos el nuevo mecanismo de traspaso.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en 833cc1d0baa9a67fab757f12dcec9cba46d8995a.
Saludos!

**Comment by Jorgecibia** [comment]
SIgue actualizado al 8/Mar pese a que se cargó nuevamente

**Comment by IgnacioAcunaF** [comment]
Lo ví. 
Mañana revisaré a detalle, a demás de contactar a MinSal para una nueva actualización

Saludos

**Comment by IgnacioAcunaF** [comment]
El problema fue que existe otro proceso que sobre-escribió la actualización con datos antiguos. Ver commit e6986ba6a38fc09a425a6a63c66507a4acd4e4d1.

Estoy dando de baja ese proceso, y volviendo a actualizar.
Saludos

**Comment by Jorgecibia** [comment]
Gracias a ti Ignacio, me queda una duda eso si respecto a la fecha de la info en Producto 77 y 76, porque normalmente son a la misma fecha y tienen la misma cantidad de vacunas, pero ahora el 77 aparece con varias más, por ejemplo en 4ta dosis:
P77 dice 2.058.114 dosis
P76 dice 1.900.798 dosis
