### ISSUE TITLE
Actualización Producto 55 - Positividad x Comuna

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1296]
Hola, llevamos 6 dias sin actualizar este producto, debería estar actualizado al 14/Mar último reporte Epi.   Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Asociado a https://github.com/MinCiencia/Datos-COVID19/issues/1290.
Tenemos un delay con esos insumos, estan en generación. 
Comentó cuando tengamos más novedades

Saludos

**Comment by IgnacioAcunaF** [comment]
Se acaba de realizar una actualización en commit 54852063e23dc4c73edcd216dcdcb503220e9ff3

Saludos
