### ISSUE TITLE
Actualización producto 65 - Índice Positividad

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1297]
Lleva sin actualizar 16 dias, favor considerar. Debiera estar al 14/Mar  Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Actualizado en el commit 709f5ddce97a9c67d3fdf293a48b59049de76f9c en conjunto con otros productos de TTA.

Ese procesamiento tenia un componente manual, que acabamos de mejorar (84e9f16321027eda1e1bbf305b1b85607cee5c36 y cde6e6c63d13dbd49cd3bdb1395faebe3d5853f7). 

Saludos
