### ISSUE TITLE
Productos 01, 19, y 38 asociados a Reporte Epidemiológico estan al 13/mar en vez del 14/Mar

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1298]
Falta el día 14/Mar, en estos productos para que estén alineados al  Reporte Epi, así ha sido históricamente, publicados a los viernes y lunes.  Gracias

**Comment by ctroncoso** [comment]
> Falta el día 14/Mar, en estos productos para que estén alineados al Reporte Epi, así ha sido históricamente, publicados a los viernes y lunes. Gracias

Al parecer vienen del origen. Comentado acá.
https://github.com/MinCiencia/Datos-COVID19/issues/1287#issuecomment-1069746482

**Comment by IgnacioAcunaF** [comment]
Gracias @Jorgecibia por el reporte.
Copio mensaje del otro PR:
Estamos haciendo la traza del procesamiento (ya que hay un pre-procesamiento por nuestro lado para generar ese input), para ver si se generó en esa etapa, o en caso contrario, revisarlo con Minsal.

Saludos

**Comment by IgnacioAcunaF** [comment]
Lo mismo que en https://github.com/MinCiencia/Datos-COVID19/issues/1287#issuecomment-1075664340 

> Estimados, como actualización:
Nuestra revisión y traza indica que fue del pre-procesamiento de los datos al asignar el nombre de la columna, y no del insumo original.
Estamos trabajando en una mejora para que esto no vuelva a ocurrir, y para cambiar el nombre de la columna de los productos.
Saludos

Saludos!

**Comment by IgnacioAcunaF** [comment]
Actualizado en be1f9adb0798f6dcccf12d53c2ce52a0023bd8d4 con datos nuevos y rectificado el día 14.

Saludos!
