### ISSUE TITLE
Algunos productos con datos de vacunación no se han actualizado en 10 días (Ej Producto 78)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#1299]
Ejemplo: 
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78

<img width="907" alt="image" src="https://user-images.githubusercontent.com/68602/159133019-447ccd41-1f35-4cc5-9673-605d8bfd6f4c.png">

**Comment by IgnacioAcunaF** [comment]
Hola @elaval,
Gracias por reportar. Esta relacionado al PR https://github.com/MinCiencia/Datos-COVID19/issues/1294.
Hubieron unos cambios en la forma del canal de traspaso de información que estamos trabajando con MinSal para automatizar, y de momento estaremos actualizando de forma manual.

Ya estamos procesando una actualización con los datos de ayer, que se encuentra corriendo en este momento:
https://github.com/MinCiencia/Datos-COVID19/runs/5613674827

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en 833cc1d0baa9a67fab757f12dcec9cba46d8995a.
Saludos!
