### ISSUE TITLE
Tests realizados y analizados.

### ISSUE THREAD

**Issue by wgomg** [MinCiencia/Datos-COVID19#13]
¿Será posible tener también un repositorio de tests/exámenes realizados **y analizados**, y sus resultados, diariamente por comuna y región?

**Comment by ivanMSC** [comment]
Tengo la impresión que la gente de este repo está solo scrapeando la web del minsal. Si el minsal no pone esos datos, entonces el ministerio de ciencia no los tiene, lo cual me parece absurdo.
Hasta donde yo sé, el minsal no ha reportado tests por comuna.

**Comment by wgomg** [comment]
Este repositorio entrega herramientas para scrapear la web del minsal, pero eso no necesariamente significa que el ministerio de ciencia obtiene de esa manera sus datos. Una de las intenciones de abrir este issue es esperar que eso sea aclarado, además de responder a la pregunta que hice.

Ojalá esto tenga la intención también de servir como medio de retroalimentación y no simple publicación unilateral.

**Comment by ivanMSC** [comment]
No. En su readme dice:

> En cuanto a los archivos a nivel comunal: Transcribimos los datos publicados por el Ministerio de Salud en pdf en: https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/ A partir de esa transcripción se genera un archivo csv, ubicado en la carpeta input. Este se procesa con el código en src, para generar los archivos csv en output.
>En cuanto a los archivos a nivel regional: Hacemos scrapping de tabla en https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/ y generamos archivo csv por día.

**Comment by EnzoAndree** [comment]
> Tengo la impresión que la gente de este repo está solo scrapeando la web del minsal. Si el minsal no pone esos datos, entonces el ministerio de ciencia no los tiene, lo cual me parece absurdo.
> Hasta donde yo sé, el minsal no ha reportado tests por comuna.

Solo he visto el numero de test por regíon, en reportes diarios, https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/09.04.2020_Reporte_Covid19v3.pdf por ejemplo la página 3

**Comment by ivanMSC** [comment]
@EnzoAndree Claro. Sería ideal que el ministerio de ciencia pusiera a disposición aquella información que no está disponible por otros medios. Como lo que pide @wgomg 

La información que está en este repo no es más de la que ya varios hemos estado recopilando desde hace tiempo.

Si el @MinCiencia no pone algo que valga la pena en este repo, como una API con información anonimizada en tiempo real del EPIVIGILA, entonces mantener este repo se convierte es dinero fiscal mal gastado.

**Comment by jorgeperezrojas** [comment]
Estoy de acuerdo contigo y se los hice saber directamente a ellos. La persona a cargo es bien buena onda, pero, y se lo dije en su cara, es impresentable que muestren esto como producto de la "Mesa de Datos del Ministerio de Ciencias". 

Yo he estado manteniendo datos desde hace algún tiempo y tengo los exámenes notificados, los pacientes en UCI, etc. pero solo información pública. Si quieres mirar algunas puedes entrar acá (aportar, también es bienvenido.) https://github.com/jorgeperezrojas/covid19-data

Hay gente haciendo una API acá y con ellos estamos cooperando también. 
https://github.com/sanguineti/chile-coronapi

**Comment by jorgeperezrojas** [comment]
Hola @ivanMSC vi que también tienes datos de COVID en tu github. Podemos cooperar, tengo unos scripts bien robustos para extraer datos desde distintas partes (incluyendo el .pdf de comunas). Creo que lo razonable es que este github coopere con nosotros y no al revés, y que el Ministerio de Ciencias dedique su tiempo, esfuerzo y recursos a presionar al MinSal para que liberen datos en serio. Tal vez podríamos invitar a más gente que se ha estado esforzando en este tema.

**Comment by ivanMSC** [comment]
@jorgeperezrojas He estado recopilando datos por comuna día a día de los comunicados de las intendencicas y seremias. Mi idea era armar el historial por comuna, pero en algunas regiones la información no la encuentro, así que no lo he publicado aún.

Cómo puede ser que un ministerio no pueda hacer más de lo que un triste weon cómo yo hace gratuitamente en su casa en el rato libre? Qué podemos hacer para que el @MinCiencia demuestre que sirve cómo ministerio? Me tiene emputecido este repo.

**Comment by maibennett** [comment]
> ¿Será posible tener también un repositorio de tests/exámenes realizados **y analizados**, y sus resultados, diariamente por comuna y región?

Sumando a eso, si se están agregando datos de tests rápidos + PCR (que parece es lo que esta pasando), podrían desagregarlos, para hacer el análisis consistente.

**Comment by valkot** [comment]
Yo estoy Haciendo web scraping desde que iniciaron a publicar en esa tabla en minsal, pero los datos son muy generales, por ejemplo los necesitaba a nivel comunal y en el PDF tampoco son tan exactos, porque cuando una comuna tiene menos de 4 casos no le ponen el valor.

He estado solicitando el detalle de los recuperados por comuna pero sin respuesta, y el detalle de géneros por comuna de infectados, hay mucha ambigüedad en la información

**Comment by maibennett** [comment]
> Yo estoy Haciendo web scraping desde que iniciaron a publicar en esa tabla en minsal, pero los datos son muy generales, por ejemplo los necesitaba a nivel comunal y en el PDF tampoco son tan exactos, porque cuando una comuna tiene menos de 4 casos no le ponen el valor.
> 
> He estado solicitando el detalle de los recuperados por comuna pero sin respuesta, y el detalle de géneros por comuna de infectados, hay mucha ambigüedad en la información

hahaha, creo que todos (o la mayoría) los que estamos acá tenemos códigos de web scrapping para los datos públicos y estamos manteniendo nuestros propios repositorios. Creo que la petición generalizada es tener datos más completos que los que se están informando, y también mayor consistencia (hay comunas, por ejemplo, donde el numero de casos baja).

**Comment by wgomg** [comment]
Más de 1 día y ninguna nueva noticia, nada que hacerle.

**Comment by GonzaloAfa** [comment]
Al paso que están entregando los datos... tendremos algo util recién en el 2021 :/

**Comment by rickynet** [comment]
> Yo estoy Haciendo web scraping desde que iniciaron a publicar en esa tabla en minsal, pero los datos son muy generales, por ejemplo los necesitaba a nivel comunal y en el PDF tampoco son tan exactos, porque cuando una comuna tiene menos de 4 casos no le ponen el valor.
> 
> He estado solicitando el detalle de los recuperados por comuna pero sin respuesta, y el detalle de géneros por comuna de infectados, hay mucha ambigüedad en la información

pero aparece la tasa y con la tasa y la densidad poblacional se puede sacar un dato aproximado

**Comment by dna33** [comment]
Hola, sigue siendo válida la pregunta que origina este debate? Se han agregado alguno productos con esta información:

Siendo quizás el más detallado, este: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto65 

Quedo atento a su respuesta.
