### ISSUE TITLE
Datos de vacunación con Moderna

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1305]
Hola, me preguntaba si ya hay datos de la aplicación de la vacuna de Moderna. En febrero llegó un [embarque de 1,5 millones de vacunas](https://www.minsal.cl/llega-a-chile-el-primer-embarque-de-vacunas-moderna-contra-el-sars-cov2/) de esta farmacéutica y esos datos aún no se tienen en la plataforma de DEIS, [por lo que puedo ver](https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F9037e283-1278-422c-84c4-16e42a7026c8&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false).

De estar ya aplicándose es importante incorporarlas a la base de datos de DEIS y por consecuencia acá.
Saludos!

**Comment by IgnacioAcunaF** [comment]
Hola @paarriagadap,
Levantamos el requerimiento con el DEIS.

Saludos

**Comment by paarriagadap** [comment]
Gracias Ignacio. Interesante que no se haya usado aún después de 2 meses, pero qué bueno que se vaya aplicar ahora.

**Comment by IgnacioAcunaF** [comment]
Hola @paarriagadap 
La información ya se encuentra disponible, ver c699f7d7cad22cdcc1d9c829e81c415ce592b386
Saludos!

**Comment by paarriagadap** [comment]
Muchas gracias! Ahora crecieron los números de las últimas semanas.
