### ISSUE TITLE
Producto 37 DEFUNCIONES COVID x FECHA DEFUNCIÓN - Inclusión de Probables en reporte diario

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1306]
Hola, el producto no ha sido actualizado hoy.

También respecto a la inclusión de los Fallecidos sin PCR con diagnóstico, como ser reportará este dato que antes era semanal, tendremos todos los días el incremento de estos casos por su fecha de defunción.

Gracias

**Comment by IgnacioAcunaF** [comment]
Actualizado el producto 37 en 4bb06044d70ae0126e6f8d8f582cb9ab6cb984ec.

Con respecto a la segunda consulta, dejó abierto el PR aún.
Saludos

**Comment by dafernandez75** [comment]
Al revisar el reporte Minsal de hoy lunes 21 marzo 2022, total fallecidos (U071+U072) = **55.965**
Total Producto37(U071) = 44.616
Total Fallecidos Deis (U072, al miércoles 15 marzo 2022. según registro Deis 17marzo2022) = 11.340
Nos da un total de **55.956**, incluyendo los Deis U099 (26, según registro Deis 17marzo2022 ) = 55.982

**Comment by Jorgecibia** [comment]
No entendi tu cuenta Daniel.
Los U072 que dices al 15 de marzo, son reporte anterior del DEIS que en producto 37 están fechados al 11/03, luego en esta semana suben a 11.340 que están fechados en P37 18/Mar
Lo que pasa es que hay 9 casos más que yo asumo son U072 que sube este total a 11.349
Y 44.616 +11.349 = 55.965 
Por eso mi 2da pregunta, cómo se reportan estos 9 casos  o los casos diarios U072 en este producto, si me preguntan a mí, yo diría que el dato sospechoso que se daba una vez a la semana, ahora tiene que ser diario
Gracias

**Comment by dafernandez75** [comment]
Los U072 ->11.340 son los que conocemos que entrega el Deis en Datos Abiertos (registros disponibles desde el jueves 17 marzo 2022, cuya data U072 es hasta el 15-03-2022).  Corresponden a los mismos que este repositorio sube el 18-03-2022 con data al 15-03-2022 al igual que el Deis, no los veo al 11-03-2022 como indicas, lo acabo de re-chequear por si lo han modificado.
  
https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2022_17032022.zip 

También me sumo a la inquietud, que si el Minsal va a colocar diariamente en reporte el total de fallecidos, sea el total de fallecidos a iguales fechas de registros tanto para los U071,U072 y los U099 (ya que estos también están señalados en el dataset del Deis desde Datos Abiertos), en donde estos últimos al parecer long covid la administración anterior del repositorio le hizo las consultas al Deis y no tuvieron respuesta para precisar a quienes correspondan, ya que no se están presentando en las estadísticas diarias y estos van levemente en aumento.

**Comment by dafernandez75** [comment]
en el caso del 55.965 para mi que se le dieron vueltas los números al digitador del panel de reporte!!!

**Comment by Jorgecibia** [comment]
Si he bajado ese archivo, y creo que en el reporte del 11/Mar, tenía 35 casos más U072, que corresponden a fechas del 2021 y 2020 si mal no recuerdo, al final ajuste el dato a los que se publica en P37, que también una vez a la semana pública los U072 bajo columna SOSPECHOSOS

Puede ser que estos 9 casos de diferencia no existan y sea como dices tu que se les dio vuelta el número, pero el Producto 14 esta consistente con el mismo número, por lo que creo más plausible que son 9 casos mas U072

**Comment by dafernandez75** [comment]
Por eso deben indicar al menos en el panel de reporte, hasta qué fecha son los registros correspondientes de U071 y U072, todavía la mayoría de los chilenos y otros usuarios piensan que son los fallecidos de las ultimas 24hrs en un solo día.

**Comment by dafernandez75** [comment]
Según reporte de hoy miércoles 23 marzo 2022, se actualizaron nuevamente los U072 al alza, sería conveniente conocer en qué fechas se están agregando los U072 que están agregando, para ello el producto 37 debe registrarlo y según reciente actualización no viene con actualización los sospechosos (U072). 

![230322_fallecidos](https://user-images.githubusercontent.com/69001461/159732511-6d625769-5e7d-4dbf-937b-04f94da30d62.png)

**Comment by dafernandez75** [comment]
Hola,
Según lo recién actualizado por el Deis, hoy jueves 24-03-2022:
https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2022_24032022.zip

Fallecidos Confirmados U071 (al 23-03-2022): 44.940
Fallecidos Sospechosos U072 (al 20-03-2022): 11.358
Fallecidos U099 (al 18-03-2022): 27
Total Fallecidos: 56.325

**Comment by Jorgecibia** [comment]
Osea estan los datos que darán hoy, este archivo se actualizaba semanalmente, se estará actualizando diariamente ?

**Comment by dafernandez75** [comment]
Al parecer la información está de alguna manera (ref. Deis), pero no los transparentan a través del Minsal y no los informan oportunamente o tienen problemas de comunicación con los responsables de este repositorio. Son muchos los problemas de actualización que de un día para otro está pasando con el repositorio.

**Comment by dafernandez75** [comment]
Al igual que la semana pasada, distribuirán en 2 días los fallecidos U071 confirmados por el Deis (viernes25 y sábado26 marzo 2022).

44.940 - 44.864 = 76 serán los U071 para el reporte del Minsal sábado 26-03-2022.

![deis](https://user-images.githubusercontent.com/69001461/160149493-57df86bc-5452-4fc8-a637-9c67c754951f.png)

**Comment by IgnacioAcunaF** [comment]
Estimados,
Luego de conversar internamente con los equipos: los datos que se han entregado los días jueves en Datos Abiertos corresponde a información en proceso de validación que se publicará 48 horas (el sábado) de forma oficial en el reporte diario (lo que ocurría de la misma forma anteriormente los días sábados, como nota Daniel en https://github.com/MinCiencia/Datos-COVID19/issues/1284#issuecomment-1072629792). 
Estamos en un proceso de armonización de los insumos de información, pero como les comenté en el mensaje anterior, el producto 37 seguirá utilizando los fallecidos del reporte diario de forma oficial, y ahora se le agregará los casos sospechosos de forma diaria (en vez de semanal) que utilizan la información oficial del DEIS.

Saludos

**Comment by IgnacioAcunaF** [comment]
Comentario solo para mantenerlos al tanto:
Estamos revisando la mejor manera de incluir esta nueva serie en la ya existente (casos sospechosos). Esperamos el jueves/viernes tenerla incorporada. 

Saludos

**Comment by Jorgecibia** [comment]
Gracias Ignacio

**Comment by IgnacioAcunaF** [comment]
Estimados,
Se creo el [producto 95](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto95), el cual tiene la información de los fallecidos sospechosos y confirmados según el reporte diario. 
Como la cifra del reporte diaria es el total agregado, no desagregado por fecha de registro del fallecimiento (vs el producto 37), por lo cual se decidió mantener el producto 37 tal cual esta (entregando información desagregada según fecha, con actualización semanal para los sospechosos).

Es importante notar que el producto 37 se actualiza tomando en consideración información PM, la cual se muestra en el reporte diario el día siguiente. Es por esto que el producto 37 va "adelantado", para los sospechosos, un día al reporte diario (por ejemplo, el producto 37 para el día 25 registra 11.358 fallecidos probables, que es el valor que se registra el día 26 de marzo en el producto 95, debido a que este último esta asociado al reporte diario)

Saludos

**Comment by Jorgecibia** [comment]
Gracias Ignacio
