### ISSUE TITLE
Duda producto 5: Fallecidos totales

### ISSUE THREAD

**Issue by xavierutox** [MinCiencia/Datos-COVID19#1307]
Hola,

Revisando el producto 5, en la sección de fallecidos, figura un incremento de 11447 en el ultimo periodo registrado (hoy).

¿Es esto normal o se debe a un error?

**Comment by ctroncoso** [comment]
se incluyen ahora (como corresponde) los fallecidos con diagnóstico U07.2, que son con covid confirmado por medidas de imagenología (TAC, Rx, etc).

**Comment by ctroncoso** [comment]
@MinCiencia: ojo con los \n en los nombres de las columnas/series.  
Son legales para csv, pero una mala práctica. 
![image](https://user-images.githubusercontent.com/121016/159343307-d47d653e-a002-44dc-90be-b4f4945056d0.png)

**Comment by IgnacioAcunaF** [comment]
Gracias @ctroncoso por reportar. Lo estamos viendo.
Como cambio un poco algunos campos del documento de reporte diario, estamos ajustando.

Saludos

**Comment by ctroncoso** [comment]
Super @IgnacioAcunaF !  Es solo un detalle, y si, suele suceder (más de una vez me ha pasado) con las típicas "columnas nuevas". Sigamos avanzando!

**Comment by IgnacioAcunaF** [comment]
Actualizados los nombres de las columnas en el commit d41e374677d1c1f39e7b2e7a0a02753a0b616415

Saludos!!
