### ISSUE TITLE
PRODUCTO 37 - Fallecidos - Sin actualizar 

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1322]
Hola, falto actualizar los fallecidos por fecha defunción.  Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Estamos viendo qué pasó con el insumo para ese producto.
Probablemente mañana tengamos novedades.
Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en 0ac216ae09174843d4af627202f5541f4f4336cc
Saludos!

**Comment by Jorgecibia** [comment]
Gracias
