### ISSUE TITLE
Datos camas UCI

### ISSUE THREAD

**Issue by jtquiroga** [MinCiencia/Datos-COVID19#1323]
Parece haber un problema en el producto 58, de camas UCI. En particular, explota el uso de camas por concepto COVID el 30 de marzo. Es esto un error? O se debe a un cambio de cálculo? Adjunto gráfico de la página del minsal.

![image](https://user-images.githubusercontent.com/77852576/162021202-e488ed6b-12dc-4256-abab-98541ccf2e1b.png)

**Comment by IgnacioAcunaF** [comment]
Muchas gracias por reportar @jtquiroga 
En efecto vemos un error. Estamos viendo el insumo con el Minsal para hacer la corrección.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizada la información en 43b470b1d57521b4ef9e642f13186503d4912621.

**Comment by IgnacioAcunaF** [comment]
Grafico actualizado: 
<img width="790" alt="image" src="https://user-images.githubusercontent.com/31544929/162042655-dc04fc81-cbed-4d8d-9879-8f4f9aa72d2d.png">

Gracias @jtquiroga por reportar.
Saludos

**Comment by jtquiroga** [comment]
Muchas gracias!
