### ISSUE TITLE
Producto 14 - Rectificar

### ISSUE THREAD

**Issue by aifuenzalida** [MinCiencia/Datos-COVID19#1326]
Dos cosas respecto al producto 14:
- @IgnacioAcunaF al parecer la corrección de los datos de los dias 29 y 30 /06/2020 no se ejecutó (https://github.com/MinCiencia/Datos-COVID19/pull/1317), ya que siguen saliendo con .0 al final.
- ¿Que cambio de criterio se generó el 21-03-2022, que pasamos de 44k muertos a 56k muertos?

**Comment by IgnacioAcunaF** [comment]
Hola @aifuenzalida 
Voy a revisar el producto 14, como indicas el proceso volvió a generar los decimales para ese día. Veré el cambio desde el insumo inicial.

Con respecto a la segunda consulta, [cito a Minsal](https://www.minsal.cl/ministerio-de-salud-cambia-el-reporte-de-las-personas-fallecidas-por-covid-19/): 

_Antes de esta fecha la cifra entregada de decesos producto al Covid-19 consideraba solo los casos confirmados con resultado positivo de test PCR, pero de ahora en adelante la estadística de fallecidos contempla tanto muertes con PCR positivo como casos probables no confirmados mediante este test, utilizando la metodología recomendada por la Organización Mundial de la Salud (OMS) y utilizada por el Departamento de Estadísticas e Información de Salud (DEIS)._

_Producto de este cambio de criterio, el día de hoy el número de fallecidos en Chile durante toda la pandemia aumentó de 44.616 a 55.965, al sumar a la cifra de fallecidos con PCR positivo los casos probables desde inicios de la pandemia. Igualmente, la cifra de decesos diarios también experimenta un aumento en relación con los días anteriores por la misma razón._

**Comment by IgnacioAcunaF** [comment]
Rectificado el primer punto en 215ef2c9de734023e17d7c9c2cb28164955a0f3a.
Gracias por reportar!
