### ISSUE TITLE
Filas duplicadas en producto 89

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1329]
Hola, el producto 89 tiene dos veces la información para cada semana epidemiológica. Lamentablemente, esos datos tampoco coinciden en cada una de estas filas. A que se debe esta diferencia?.

**Comment by IgnacioAcunaF** [comment]
Hola @felipeelorrieta,
En efecto hay muchas filas repetidas, vamos a realizar la corrección correspondiente y buscar en qué parte del proceso se esta generando esta duplicidad. 
Con respecto a la diferencia que mencionas, al hacer el filtro por filas únicas, vemos que la última semana (2022-13) no coinciden (notamos que el resto de las semanas si). Revisaremos qué ocurrió para esta semana.

Saludos

**Comment by IgnacioAcunaF** [comment]
@felipeelorrieta 
Actualizada la información en c6d01ce0ea6aa1d427231b625f8fb6b1e1bb9bb5.

Saludos
