### ISSUE TITLE
Producto 15 no se actualizó el sábado

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1330]
Producto 15 no se actualizó el sábado, se actualizó el 16, pero repitiendo los últimos datos. Posiblemente otros productos con problemas, podrían revisar la actualización epi? 

Gracias

**Comment by Jorgecibia** [comment]
Hola, si no están actualizados al 6/Abril los productos 01, 19, 38, 55, y 65. que se actualizan a los días lunes y viernes.

Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @weichafan 
Gracias por reportar. Él insumo para la actualización se generó después de la hora del procesamiento automático, por lo que el proceso tomó el archivo anterior (repitiendo los datos).
Revertiré ese commit y procesaré manualmente el insumo del sabado.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en c6df1492fb06c19ff3243e030b89944e00497f02.
Saludos
