### ISSUE TITLE
Mal fechas productos 1 y 19

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1338]
Productos de casos por comuna tienen en última columna fecha 25 de Abril, imagino que debiese ser 22 de Abril.

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar @felipeelorrieta 
Estamos revisando.

Saludos

**Comment by IgnacioAcunaF** [comment]
Corregido en d1a3b961354cee9b8dde3c79e497707a91661e11.
Gracias @felipeelorrieta 

Saludos
