### ISSUE TITLE
Producto 37 - Fallecidos DEIS - Actualización datos al 27/Abr pendiente

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1341]
Hola, hoy 27/Abr no se ha actualizado el producto.  Gracias

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar @Jorgecibia 
Estamos consultando por el insumo

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en b3259571d69f81d11f5a8d5b6d4ea981b3566153
Saludos

**Comment by Jorgecibia** [comment]
Gracias
