### ISSUE TITLE
Datos Reporte Epi con problemas: productos 15, 16, 39

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1343]
Estimados,

Los datos del reporte epidemiológico de hoy se subieron con problemas, por favor revisar. 
Producto 15 con datos del reporte del sábado, producto 16 últimos datos repetidos. 

Saludos cordiales y gracias

**Comment by IgnacioAcunaF** [comment]
Hola @weichafan 
Muchas gracias por reportar. 
Corregido en 1a3eb39a3c7cc1afec4284f256f4fa178447fd15

Saludos!
