### ISSUE TITLE
Producto 37 - DEFUNCIONES DEIS pendiente actualizar Sospechosos (último dato esta al 15/Abr)

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1345]
Actualización semanal de sospechosos por fecha de defunción está pendiente para el 22/Abr

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar @Jorgecibia.
Revisaremos mañana con el DEIS el insumo (a modo general existieron dificultades técnicas por la desconexión del registro civil ocurrida la semana pasada)

Saludos

**Comment by dafernandez75** [comment]
Hola,
Ya esta ok el DEIS en Datos Abiertos en el día de hoy, incluye los confirmados y sospechosos, que cuadran con el reporte de hoy del Minsal, con registros al 27-Abril-2022.

https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2022_28042022.zip

Saludos

**Comment by IgnacioAcunaF** [comment]
Gracias @dafernandez75 @Jorgecibia 
Actualizado en a5f803fd2ebfce3394b05aa09f3879b3b3c494e8

Saludos!

**Comment by Jorgecibia** [comment]
Gracias, exelente trabajo el que hacen
