### ISSUE TITLE
Actualización de balance diario 8-mayo está incompleto. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1347]
Solo se actualizaron los archivos  DEIS. 
commit: 21ca6691c357f148a0a35332ab68bcc00e4ffa70

**Comment by IgnacioAcunaF** [comment]
Gracias por el reporte @ctroncoso 
Estamos viendo un error en el procesamiento automático para el archivo de ayer .
Estamos corrigiendo a la brevedad.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en def3b702e79134dc43dd520034ea0c57c6485cff
Muchas gracias @ctroncoso por el reporte

Buen inicio de semana

**Comment by ctroncoso** [comment]
Igualmente! Excelente trabajo.
