### ISSUE TITLE
Actualización Data Product

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1348]
Estimados,

Me gustaría consultar en qué fecha podrían actualizar los datos de los Data Product que tuvieron su actualización hace 4 días. Estas fuentes de datos están actualizadas al 2022-05-07 y es crítico actualmente para nuestra organización conocer los datos hasta el 2022-05-08.

Agradezco de antemano su disposición y quedo atento. Saludos cordiales,

**Comment by IgnacioAcunaF** [comment]
Hola @sebawsky 
¿Te refieres a los productos asociados a a0dc73d0fd69831f0da2c725f13dae347972c2e4? ¿O otros productos en particular?
Por favor si nos podrías indicar que data product en particular con tal de canalizar mejor la consulta.
Saludos!

**Comment by ctroncoso** [comment]
> Estimados,
> 
> Me gustaría consultar en qué fecha podrían actualizar los datos de los Data Product que tuvieron su actualización hace 4 días. Estas fuentes de datos están actualizadas al 2022-05-07 y es crítico actualmente para nuestra organización conocer los datos hasta el 2022-05-08.
> 
> Agradezco de antemano su disposición y quedo atento. Saludos cordiales,

Tip: siempre es bueno indicar a cual de todos los productos que se generan en este github apunta tu consulta. 
Esto considerando que hay productos que ya no se actualizan y existen por registro históricos, otros se actualizan semanalmente, a diario y  cada 3 o 4 días.

**Comment by IgnacioAcunaF** [comment]
Hola @sebawsky 
Se acaban de actualizar los productos mencionados en el siguiente comentario:

> Hola @sebawsky ¿Te refieres a los productos asociados a [a0dc73d](https://github.com/MinCiencia/Datos-COVID19/commit/a0dc73d0fd69831f0da2c725f13dae347972c2e4)? ¿O otros productos en particular? Por favor si nos podrías indicar que data product en particular con tal de canalizar mejor la consulta. Saludos!


En el commit dbf2180912df366fd9dda77785a10fd0d638ecfe.
¿Les sirve esa actualización?
Saludos
