### ISSUE TITLE
Producto 37 - Defunciones DEIS pendiente actualización del 12Mayo

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1349]
Hola, no esta actualizado al 12/Mayo el producto referido. Gracias

**Comment by IgnacioAcunaF** [comment]
Gracias por reportar @Jorgecibia 
Actualizado en 9b2e80d9ae1d5486ab0736f31be16a26c4f6951c
Saludos

**Comment by Jorgecibia** [comment]
Gracias
