### ISSUE TITLE
Producto 65 - Positividad - Falta actualización al 9/Mayo

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1350]
Hola, no están datos al 9/Mayo asociados al último reporte epidemiológico. Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
Nos contactamos hoy AM con el MINSAL y nos indican que los productos de TTA se deberían actualizar hoy.
Cualquier cosa comento.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en 042ddf93ac800012247ec5d01397c08b4c866245

**Comment by Jorgecibia** [comment]
Gracias
