### ISSUE TITLE
Falla en actualización de algunos productos balance diario

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1351]
Hola, 

Hoy se actualizaron algunos productos del balance diario, pero otros no. 
Asumo que lo irán a corregir dentro de un rato, pero les aviso por si les sirve.

Gracias como siempre.

**Comment by IgnacioAcunaF** [comment]
Hola @weichafan 
Muchas gracias por reportar!
Uno de los insumos no habia sido considerado por el proceso, ahora si en la actualización c0e54dca5a3e7fa00700fc6641bc8a32a545d6ca

Saludos!!
