### ISSUE TITLE
Producto 37 - Defunciones DEIS - Pendiente actualización semanal "Sospechosos"

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1352]
Hola, esta pendiente actualizar los datos de "sospechosos" esta semana, Gracias

**Comment by IgnacioAcunaF** [comment]
gracias @Jorgecibia por reportar.
Estamos en revisión del insumo
Saludos!

**Comment by IgnacioAcunaF** [comment]
Actualizado en f47f01049475e70928acdf5c5301285d1496ac42 y el resto de productos asociados a DEIS en fc72877e98127f7bb75fcbf7fd37521165ea7bf2

**Comment by Jorgecibia** [comment]
Gracias
