### ISSUE TITLE
Producto 55 -Positividad - Falta actualizar al 20/May

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#1353]
Hola, este producto no tiene actualizado los dia 16 y 20 de mayo en que se reportan los casos por comuna.  Gracias

**Comment by IgnacioAcunaF** [comment]
Hola @Jorgecibia 
En revisión
Gracias por el reporte!

**Comment by Jorgecibia** [comment]
Gracias
