### ISSUE TITLE
No ha llegado informe EPI del Lunes 23?

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1354]
Sorry usar esta vía, pero veo que el informe no está ni publicado en la web ni tampoco lo he visto acá. 
¿Saben si está retrasado?

**Comment by ctroncoso** [comment]
Espectacular. Estaba "consternado". Gracias Ignacio!

**Comment by ctroncoso** [comment]
Uhhhh... 
No se vé simple. Como input de procesos, sobreescribe muchos archivos, así que cortar por fecha destruiría datos en el output. 
Voy a revisar los scripts para ver si puedo dar una mano.

**Comment by ctroncoso** [comment]
Listoco, veo el commit. Grax!

**Comment by IgnacioAcunaF** [comment]
Actualizado el informe en c013cc6aadc8230e3176ebdcd11bff5d510b0fcc, sin el archivo producto15/FechaInicioSintomasHistorico_2022_1st_std.csv. Voy a dejar abierto el issue hasta agregarlo o ver que hacer en su defecto.

**Comment by ctroncoso** [comment]
Gracias... voy a leer el script que lo procesa... si veo alguna opción viable, te comento por acá. 
Consulta, este archivo viene íntegro de un ftp o puede ser pre-procesado (onda un "tail") antes de que entre al hub?

**Comment by IgnacioAcunaF** [comment]
> Uhhhh... No se vé simple. Como input de procesos, sobreescribe muchos archivos, así que cortar por fecha destruiría datos en el output. Voy a revisar los scripts para ver si puedo dar una mano.

Buenisimo, muchas gracias @ctroncoso, toda contribución nos ayuda. A modo de referencia, a pasado antes, por ejemplo en vacunación. En ese caso, resolvimos separando el archivo en dos y luego juntandolo (ver última linea de https://github.com/MinCiencia/Datos-COVID19/blob/master/.github/workflows/vacunacion.yml) :

```    - name: transfer files
      run: |
          pwd
          ls
          ls -la Datos-COVID19/input/Vacunacion
          rsync -auH MinCienciaDataPreparation/output/Vacunacion/. Datos-COVID19/input/Vacunacion
          ls -la Datos-COVID19/input/Vacunacion
          **cat Datos-COVID19/input/Vacunacion/WORK_ARCHIVO_9-* > Datos-COVID19/input/Vacunacion/WORK_ARCHIVO_9.csv**
```

Probablemente lo mejor sea separar ese archivo en dos en src/informeEpidemiologico.py. Mañana lo veo y vamos comentando.
Saludos

**Comment by IgnacioAcunaF** [comment]
> Gracias... voy a leer el script que lo procesa... si veo alguna opción viable, te comento por acá. Consulta, este archivo viene íntegro de un ftp o puede ser pre-procesado (onda un "tail") antes de que entre al hub?

Viene integreo, pero cuando el problema es el insumo, en el preprocesamiento lo acortamos, por ejemplo para el caso de Vacunación:
``
    - name: Split large files
      run: |
        pwd
        cd output/Vacunacion
        split -l 750000 WORK_ARCHIVO_9.csv WORK_ARCHIVO_9-
        rm WORK_ARCHIVO_9.csv
``

Luego, cuando llega a este repo, se concatena con un cat (el codigo que mande en el comentario anterior, con el cat), pero para el caso de vacuna el insumo es el que pesa más de 100Mb, no el producto. Es por eso que lo mejor me da la impresión será separar ese historico en 2.

**Comment by IgnacioAcunaF** [comment]
Separado en dos (en un archivo a y b) en 1cc69d8116232992ad5bbcc5cf62267e32861eea
