### ISSUE TITLE
Falló actualización de balance diario (29-05), pero en el action sale en verde. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1357]
Hola, estaba revisando el balance diario. Dice que corrió, pero hay un warning en el run.
https://github.com/MinCiencia/Datos-COVID19/actions/runs/2404740615

Revisando el input, no hay actualización en input/ReporteDiario.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso por el reporte.
Como mencionas, la action se ejecutó bien, pero el insumo utilizado fue el del día anterior, por lo que no actualizó el repositorio.
Ahora se encuentra ejecutandose nuevamente

**Comment by ctroncoso** [comment]
> Muchas gracias @ctroncoso por el reporte. Como mencionas, la action se ejecutó bien, pero el insumo utilizado fue el del día anterior, por lo que no actualizó el repositorio. Ahora se encuentra ejecutandose nuevamente

Cosas que pasan. Más de alguna vez me fui con el archivo del mes pasado. Impeque, veamos como vá. Gracias!

**Comment by IgnacioAcunaF** [comment]
Actualizado en def06f96b2265573fbbb26dbcce5c86d1677db17
Gracias @ctroncoso !!
Buen inicio de semana

**Comment by ctroncoso** [comment]
> Actualizado en [def06f9](https://github.com/MinCiencia/Datos-COVID19/commit/def06f96b2265573fbbb26dbcce5c86d1677db17) Gracias @ctroncoso !! Buen inicio de semana

Igualmente! buena semana! (Ojalá llueva)
