### ISSUE TITLE
Acumulados que bajan

### ISSUE THREAD

**Issue by Themrpie** [MinCiencia/Datos-COVID19#1359]
Revisando los [datos](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto35/Comorbilidad_T.csv) de comorbilidades puedo ver que el día 2021-06-18	los casos acumulados bajan.
Por ejemplo los hospitalizados con hipertensión pasan de 48522.0 a 46446.0. Quizás estoy entendiendo mal, pero es el único día donde se ve esto por lo que parece una anomalía.

**Comment by IgnacioAcunaF** [comment]
Estimado @Themrpie,
Revisamos lo que nos indicas con el MINSAL. Los casos de comorbilidad son acumulados, por lo que en efecto no deberían disminuir. La razón en efecto corresponde a una anomalía, relacionada a error de código para el informe mencionado, que se enmienda en el informe siguiente.

Saludos
