### ISSUE TITLE
Nombres de regiones y consistencia de los productos que vienen de informe epidemiológico

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#136]
1) ¿Será mejor poner los nombres de regiones y comunas iguales para todos (estándar de la Subsecretaría de Desarrollo Regional y Administrativo (SUBDERE)?
2) El data product 1, casos totales por comuna, no tiene los totales por región, pero el [data product 25 casos actuales por fecha de inicio de síntomas](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto25) y el [data product 19 casos activos por fecha de inicio de síntomas](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto19) en cambio si incluyen estos totales. Creo que hay que agregar totales regionales al data product 1, o eliminar del 19 y el 25. 
3) Si deciden dejarlos, también añadiría un total nacional, en todos los productos mencionados.

**Comment by scornejob** [comment]
respecto a 2: la decision de poner o no totales se debe a que en los reportes diarios se comunicaban los casos "por determinar" como una comuna. Decidimos obviar ese dato en ese formato, e incluirlo en el total (en otras palabras: la diferencia entre el total publicado y el total computado corresponde a los casos por determinar)

**Comment by dna33** [comment]
ok, lo de los totales mejor entonces no lo movamos, mantengamos estándar sí los nombres de regiones y comunas

**Comment by fzmolina** [comment]
Sobre ese punto 2: tal vez podríamos tomar ese estándar para todos los
productos similares que vienen del informe EPI, e.g. casos actuales,
activos, semanas epidemiológicas, porque en esos sí estamos colocando el
total por regiones

Sobre lo de las regiones y comunas lo estoy mirando. Otra cosa, hay otros
campos que es bueno mantener un estándar, por ejemplo en los rangos de edad
en unos colocamos los números solamente y en otros agregamos "años" al
final. Otro issue es que en otras categorías utilizamos acentos y en otras
no (por ortografía deberían)

Faviola

   o                o                o                o                o
 /<.            _ /<.            _ /<.            _ /<.            _ /<.
)>(*)       o  (*)>(*)      o   (*)>(*)     o    (*)>(*)    o     (*)>(*)

------
