### ISSUE TITLE
No se puede descomprimir el master.zip

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#1363]
Hola al parecer hay un problema con el producto 46 del repositorio. Ya que cuando descargo el repositorio.zip y lo descomprimo solo lo hace hasta el producto 45.
Es posible arreglarlo?
De antemano muchas gracias

**Comment by ctroncoso** [comment]
Lo descargué y lo mismo. No creo que pueda repararse ya que es una característica del sitio github. 
Temo que tendrás que clonar el repo con git.

![image](https://user-images.githubusercontent.com/121016/174139402-46372513-7a5f-4bac-a9f9-0e08701562aa.png)

**Comment by IgnacioAcunaF** [comment]
Hola @felipeelorrieta 
Tal como comenta @ctroncoso, es muy probable que sea limitación de Github. Replicaré y veré si hay alguna forma de solucionar, pero puede que sea un punto de tope de la plataforma.

En el intertanto, lo mejor es clonar con git clone https://github.com/MinCiencia/Datos-COVID19.git 
Saludos

**Comment by IgnacioAcunaF** [comment]
Hola @felipeelorrieta 
Efectivamente es una limitación de plataforma, por lo tantoi, el work around es usar git clone.

Saludos
