### ISSUE TITLE
Datos epi se actualizaron mal sábado 18

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1364]
Hola, 

Aparentemente hoy los datos de los productos asociados con reporte epi se 
actualizaron mal, por favor revisar.

Muchas gracias, saludos

**Comment by ctroncoso** [comment]
Efectivamente el último dato es del día lunes 13 y no del viernes 17.

**Comment by IgnacioAcunaF** [comment]
Gracias @weichafan y @ctroncoso por reportar.
Actualizando ahora de forma manual

saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en 450a76a587403b6f375901a40a48f72474fbb1cc.
Que tengan buen domingo!

Saludos

**Comment by ctroncoso** [comment]
Gracias Ignacio! Buen domingo!
