### ISSUE TITLE
Datos Abiertos DEIS 23-06-2022 solo actualizó hasta el 31-12-2021 !!!

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1367]
Hola,

Favor informar al DEIS a quien corresponda que el repositorio de Datos Abiertos de hoy 23-06-2022 (ya que generalmente actualiza los registros los jueves para todos los fallecidos, incluidos por covid19 confirmados U071 y sospechosos U072), solo presenta registros hasta el 31-12-2021.

https://repositoriodeis.minsal.cl/DatosAbiertos/VITALES/DEFUNCIONES_FUENTE_DEIS_2016_2022_23062022.zip

**Comment by IgnacioAcunaF** [comment]
Gracias @dafernandez75 por reportar.
Lo levantaremos con el DEIS.

Saludos

**Comment by IgnacioAcunaF** [comment]
@dafernandez75 actualizado los datos en el link:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/31544929/175425521-574d85f8-7808-49b1-a949-77f242a87707.png">

Gracias de nuevo por el reporte.
Saludos
