### ISSUE TITLE
Fallecidos de informe diario P.37 no se actualizó. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1371]
Producto 37 de fallecidos de informe diario, no se actualizó. 
Revisando input, no hubo cambio en `NuevaDefDefunciones`
Tal vez relacionado con #1370?

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso por reportar.
El archivo del día 26 llegó más tarde de lo previsto, por lo que no se actualizó para ese día.

Los datos se actualizaron para el 27, incluyendo en la serie el día 26 de forma retroactiva bc0588a9401e4c9c90afac604021a5bb7d2e4ea8

Saludos
