### ISSUE TITLE
Fallecidos por comuna y edad está vacío.

### ISSUE THREAD

**Issue by Themrpie** [MinCiencia/Datos-COVID19#1372]
Al parecer hay un problema con este archivo porque esta relleno de ceros.
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto84/fallecidos_comuna_edad_confirmadas.csv

**Comment by IgnacioAcunaF** [comment]
Hola @Themrpie 
Gracias por reportar
Revisaremos el insumo del DEIS para verificar algún error de procesamiento o ir a la fuente.
Saludos!

**Comment by IgnacioAcunaF** [comment]
Probablemente relacionado con https://github.com/MinCiencia/Datos-COVID19/issues/1370

**Comment by IgnacioAcunaF** [comment]
Estimado @Themrpie 
Revisado el archivo. No se encontró finalmente algún problema con respecto a este.

Por ejemplo, para el día 2022-06-22:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/31544929/177209895-ec972848-153f-4b6b-a866-0ccbdea547fe.png">
Para el día 2022-06-21:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/31544929/177209946-ba8dd9f4-05e1-44e9-b46f-9ee167753ccb.png">

La razón por la que se ve como si fueran solo 0 es por el número de tipologías: al ser 2422 filas (combinación comuna + rango etario) y los fallecimientos un número que generalmente es menor a 100, hay aprox 2300 ceros vs menos de 100 unos, lo que da la impresión de vacío.

Quedo atento a comentarios, 
Saludos
