### ISSUE TITLE
Balance diario no cargó datos para hoy 29 de junio. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1373]
Action corrió bien (salvo un error en el cleanup), pero no actualizó nada.  ¿falla en origen?

**Comment by IgnacioAcunaF** [comment]
Gracias @ctroncoso por reportar.
En efecto, la situación se debe en el origen. Lo estamos revisando con el MINSAL para tener la actualización del insumo.

Saludos
