### ISSUE TITLE
Falló la actualización epi de sábado? duda producto 22

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1374]
Parece que hubo problemas actualización datos epi de hoy sábado.

Por favor verificar. 

Aprovecho de preguntar. En el producto 22 se informan pacientes hospitalizados, pero regularmente va 1 informe epi atrás, ose hoy deberían publicarse los datos del miércoles y el miércoles próximo los de hoy sábado. Me tinca que puede ser por algún error en la automatización. El producto 16 siempre va al día del epi, por ejemplo.

**Comment by IgnacioAcunaF** [comment]
Hola @weichafan 
Revisaremos en estos momentos.
Gracias por el reporte!

**Comment by IgnacioAcunaF** [comment]
Como update: estamos a la espera de unos archivos de insumo para actualizar la versión del día sabado. Mientras tanto, se realizó un revert del commit con información duplicada

**Comment by IgnacioAcunaF** [comment]
Update: Actualizado los archivos del informe de epi del día sabado en e0a1b13d0061ad8045ef2c1f4481b2ae4c61dcd7.

**Comment by IgnacioAcunaF** [comment]
Estimado @weichafan,
Estuvimos revisando lo comentado en el producto 22, y vemos que los transpuestos (HospitalizadosEtario_Acumulado_T.csv) van a atrasados tal como lo comentas, no así la versión original (HospitalizadosEtario_Acumulado.csv).

Por ejemplo, para el commit 4845f79781cd3265ade801c85926621df7c5f376 del día 29-06, el producto debía mostrar hasta información hasta la fecha 27-06. Al revisar el insumo, se ve que este venia con dicha información:

_input/InformeEpidemiologico/HospitalizadosGeneroEtario_Acumulado.csv_:
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/31544929/178581394-5c7619e0-3acc-49dc-9909-a9e41e19d99b.png">


El producto HospitalizadosEtario_Acumulado.csv tambien tambien lo contempló (output/producto22/HospitalizadosEtario_Acumulado.csv):

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/31544929/178581007-cb289c4b-2f2d-43b6-8375-416388d1189e.png">

Sin embargo, el traspuesto del producto anterior presentaba información hasta el 24-06 (informe anterior, como indicas en el issue):

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/31544929/178581528-b7fb8d81-5d4b-4c0f-bbc9-d57ce8bc4675.png">

Es decir, en efecto el producto 22 transpuesto va un informe más atrasado (no así el normal). La razón identificada de esto es la siguiente: en el proceso que genera estos productos, _src/informeEpidemiologico.py_, transponer el archivo ocurre antes del procesamiento de la nueva información (que ocurre en la linea 338), asi que toma la información anterior.

![image](https://user-images.githubusercontent.com/31544929/178581894-d840a0d7-cf54-4b63-9125-277c45839eaf.png)

Modificaremos el orden de las lineas 334 y 335 para que ocurra despues de agregar la nueva información (linea 338).
Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en https://github.com/MinCiencia/Datos-COVID19/commit/c7d9b8df6b53d3feee630433a671cbeb9741f721.
Gracias por reportar!
