### ISSUE TITLE
Producto 89: Cálculo de incidencia_def

### ISSUE THREAD

**Issue by edomt** [MinCiencia/Datos-COVID19#1376]
Muchas gracias por su trabajo en este repositorio.

Utilizamos el producto 89 para los datos de [este artículo](https://ourworldindata.org/covid-deaths-by-vaccination) en Our World in Data.

Desde el commit 4636768298a7516a265feac8d7f23f29f6676910, parece que la columna `incidencia_def` ya no es igual a `casos_def * 100000 / poblacion`.

Por ejemplo en la fila 23, con `casos_def` = 11 y `poblacion` = 1026009, se esperaría que `incidencia_def` = 1.072. Pero en el archivo actual el resultado es 0.344.

Sería posible comprobarlo, por favor?

Gracias.

**Comment by ctroncoso** [comment]
Por lo que veo, desde el commit e02d20783d9b2b80b6eba8e13689bc2625dce40c (17-nov-2021) se eliminó el cálculo de incidencias, probablemente porque estas ya vienen en el archivo de origen (?)

![image](https://user-images.githubusercontent.com/121016/177338663-e660fabc-a05e-47ee-9850-9b67a3c14113.png)

**Comment by IgnacioAcunaF** [comment]
Estimado @edomt 
Muchas gracias por los comentarios, y aprovechamos de felicitar el excelente trabajo realizado por OWID.
Con respecto a la consulta, hubo un cambio en el día del commit 4636768298a7516a265feac8d7f23f29f6676910 ya que se agregaron nuevos campos (4ta dosis de vacunación), por lo que estamos verificando el nuevo archivo de insumo en base a lo expuesto. 
Esta relacionado también a https://github.com/MinCiencia/Datos-COVID19/issues/1304#issuecomment-1172913335 (PR que aprovecho de reabrir).

En cuanto tengamos verificación con la autoridad sanitaria, les comentaremos.
Saludos

**Comment by IgnacioAcunaF** [comment]
Estimados, 
Se revisó lo levantado con la autoridad sanitara, y se actualizó el insumo con el cual se realiza el producto 89.
Antes, existian los siguientes valores en el producto 89 para la incidencia: _incidencia_casos, incidencia_hospi, incidencia_uci, incidencia_def_. Desde el commit e367822bf89e333346bc12d3a72261f6216e06c1, a demás de adicionarse la 4ta dosis de vacunación, se separa las 4 variables de incidencia en dos tipos (cruda y ponderada).

**1. Cruda (Raw)**:
- incidencia_cruda_confirmados,
- incidencia_cruda_hospi,
- incidencia_cruda_uci,
- incidencia_cruda_def

**2. Ponderada**:
Corresponde a un ajuste con una metodología clásica de ajuste de tasas por método directo
- incidencia_ponderada_confirmados,
- incidencia_ponderada_hospi,
- incidencia_ponderada_uci,
- incidencia_ponderada_def

El caso del que comentas @edomt, consistiria en la _incidencia_cruda_def_. Como se puede ver en la fila 23 el valor de dicha columna es 1.072115351814653 (que coincide con el calculo que expones). El valor que que ocasionó el origen del presente issue, el que para este caso tenía valor de 0.344 corresponde a _incidencia_ponderada_def_.
Para preservar la serie anterior, se recomienda usar la variable _incidencia_cruda_def_.

Saludos
