### ISSUE TITLE
contagios diarios por comuna

### ISSUE THREAD

**Issue by Hpoblete55** [MinCiencia/Datos-COVID19#1378]
Buenas tardes, ¿Dónde puedo obtener los datos "Historial comunas contagios diario"?. Los estaba sacando de: "ivanMSC/COVID19_Chile/master/historial_comunas.csv" pero dejaron de publicar el 19 de junio de 2022. Les agradecería si me pueden guiar para obtener esta información.
Saludos
Hector Poblete

**Comment by ctroncoso** [comment]
Los datos por comuna no son de publicación diaria por lo que tengo entendido. Son parte del informe epidemiológico que se hacen los lunes y viernes.  Dale una mirada al [Producto 1](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto1)

**Comment by IgnacioAcunaF** [comment]
Estimado @Hpoblete55 
Tal como comenta @ctroncoso, el producto de contagios diarios por comuna lo puedes encontrar en el producto número 1. Esta actualización se realiza con el informe epidemiologico, y ocurre dos veces por semana (se publican en este repositorio miércoles y sábado).

Saludos

**Comment by Hpoblete55** [comment]
Hola
Gracias por responder
Si, he tratado de buscar la información de los contagiados por día, tenemos un informe mensual en nuestra compañía para monitorear el estado de la pandemia por comunas, teníamos una rutina programada para descargar la información de los siguientes des URL, ¿saben si se descontinuaron?

https://raw.githubusercontent.com/ivanMSC/COVID19_Chile/master/historial_comunas.csv
https://raw.githubusercontent.com/ivanMSC/COVID19_Chile/master/covid19_chile.csv

Saludos
Hector Poblete

De: Carlos Troncoso ***@***.***>
Enviado el: viernes, 8 de julio de 2022 01:05 p. m.
Para: MinCiencia/Datos-COVID19 ***@***.***>
CC: Hector Poblete ***@***.***>; Author ***@***.***>
Asunto: Re: [MinCiencia/Datos-COVID19] contagios diarios por comuna (Issue #1378)


Los datos por comuna no son de publicación diaria por lo que tengo entendido. Son parte del informe epidemiológico que se hacen los lunes y viernes. Dale una mirada al Producto 1<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMinCiencia%2FDatos-COVID19%2Ftree%2Fmaster%2Foutput%2Fproducto1&data=05%7C01%7Chpoblete%40aminerals.cl%7C69ed94a3652342c5ac5e08da6103f697%7Cd96f3d5a3042402a994b05725b2e1427%7C1%7C0%7C637928966938666969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yBRKmkC10BSDKwLnQ5Q7MKUWJeBrP%2FBt11gUsVa73dk%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMinCiencia%2FDatos-COVID19%2Fissues%2F1378%23issuecomment-1179198289&data=05%7C01%7Chpoblete%40aminerals.cl%7C69ed94a3652342c5ac5e08da6103f697%7Cd96f3d5a3042402a994b05725b2e1427%7C1%7C0%7C637928966938676963%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QpwqsMP27%2Fdrzsd%2BhBTyRDlszToHN%2BviJ1Ba8nD2MKI%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVEWUWOPDFQZBHD243K4WLTVTBNS5ANCNFSM526OHJXA&data=05%7C01%7Chpoblete%40aminerals.cl%7C69ed94a3652342c5ac5e08da6103f697%7Cd96f3d5a3042402a994b05725b2e1427%7C1%7C0%7C637928966938686956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BofZU450nJ%2FHabikjpOibAP%2Br9AfjYB88a11FvnDBvM%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

⚠️Advertencia Ciberseguridad Antofagasta Minerals: Este es un correo externo⚠️

1.- Verifique que es remitente confiable, 2.- No descargue adjuntos desconocidos, 3.- No haga clic en ningún vínculo, 4.-Ante sospechas reenvíelo a Mesa de Ayuda.

La información contenida en este correo y archivos adjuntos es propiedad de Antofagasta Minerals S.A. y puede contener información privilegiada, confidencial o reservada y su divulgación no autorizada está prohibida por ley. Si Ud. recibe este correo por error, le rogamos avisarnos de inmediato y eliminarlo.
________________________________
The information contained in this email, and attachments, is property of Antofagasta Minerals S.A. and may contain privileged, confidential or reserved information, and its unauthorized disclosure is prohibited by law. If you receive this message by mistake, please notify the sender immediately and eliminate the message.

**Comment by IgnacioAcunaF** [comment]
No tenemos conocimiento a la mantención de dicho repositorio, pero revisando en los issues, https://github.com/ivanMSC/COVID19_Chile/issues/40#issuecomment-1159929339, se puede ver que las actualizaciones se descontinuaron hace 19 días 

Por lo que se puede la fuente de datos indicada en ese repositorio es de multiples instituciones (no directamente de los reportes oficiales del MINSAL). Las actualizaciones que manejamos en este repositorio son de estos reportes que tienen la periocidad antes mencionada (por temas de validación de la información, entre otros).

Saludos
