### ISSUE TITLE
Producto 14 std incorrecto

### ISSUE THREAD

**Issue by Leandermen** [MinCiencia/Datos-COVID19#138]
![image](https://user-images.githubusercontent.com/6208975/81026832-71218380-8e49-11ea-9295-a88cb091c4a7.png)
Esta dando confirmados no fallecidos

**Comment by scornejob** [comment]
efectivamente: habia un error en el dataframe a meltear.

Arreglado en https://github.com/MinCiencia/Datos-COVID19/pull/141
