### ISSUE TITLE
no se cargaron los datos de nuevas defunciones para el 28 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1389]
https://github.com/MinCiencia/Datos-COVID19/tree/master/input/NuevaDefDefunciones no cargó con la actualización de informe diario.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso por reportar.
Actualizado en ced9096ac665b8e51e54007b7e25829b1dc1e17d

Saludos!

**Comment by ctroncoso** [comment]
Grax!
