### ISSUE TITLE
Portar a python notebook contribuido en  #134

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#139]
en https://github.com/MinCiencia/Datos-COVID19/pull/134 se contribuyo un notebook para generar outputs. Sin embargo, no estoy seguro que sea facil correr notebooks en github actions, asi que deberiamos portarlo a script.

**Comment by Leandermen** [comment]
estoy evaluando este [Run Notebook](https://github.com/marketplace/actions/run-notebook)

**Comment by scornejob** [comment]
@Leandermen , en el branch https://github.com/MinCiencia/Datos-COVID19/tree/issue139 porte el notebook a un script. Eso nos simplifica la automatizacion, al punto de que podemos dejarla amarrada a un pr a `input/Cuarentenas`, lo que generaría un nuevo producto 29. 

Lo importante es que si consensuamos usar el script en vez del notebook, deprecamos el último, pero no sé si lo utilizas fuera de este repo. Nos cuentas?

**Comment by scornejob** [comment]
(Y esta solucion ademas nos permite cerrar el issue de mantener actualizado el producto 29)

**Comment by scornejob** [comment]
@Leandermen , solo me falta tu confirmacion para mergear este branch.

**Comment by Leandermen** [comment]
Yo no tengo problemas en cambiarlo, de hecho estaba viendo esa misma linea de pasarlo a script. No lo he testeado todavía pero si lo han probado no tengo inconvenientes

**Comment by scornejob** [comment]
Gracias @Leandermen!

Yo lo he probado y "funciona", en el sentido de que no se cae, pero me gustaría coordinar un test contigo, dado que eres el experto.

Desde mi ignorancia: te propongo que crees un input con una nueva cuarentena dummy en el branch  issue139 mediante pr a ese branch, y yo corro el porting, y te cuento para que revises el output. Si esta ok, mergeamos.
Te parece sensato?

**Comment by Leandermen** [comment]
ok, crearé un subproducto con pocas cuarentenas para que lo pruebes. Coordinemos un test en los prox dias

**Comment by scornejob** [comment]
gracias. Hice er merge y corri el script, pero no vi cambios en los outputs. Voy a debuggear un poco.

**Comment by scornejob** [comment]
@Leandermen , no veo donde haces referencia en el notebook al input. Me explicas como funciona?

**Comment by Leandermen** [comment]
En primer lugar, el notebook no hace referencia al input (eso es otro script que estoy viendo como refinarlo y no lo he incluido. lo que pasa es que la base de datos central de donde se obtienen se consume a través de una API de la tecnología ArcGIS de Esri (por eso se usa el modulo arcgis de python), el notebook se conecta al servicio, establece una consulta de las cuarentenas sin geometría en formato Spatial Enabled Data Frame (SEDF) el cual es reconocible por pandas y luego guarda el dataframe como CSV, lo que estoy viendo es como usar el mismo proceso para generar el geojson en Input ya que lo unico que hace es descargar la siguiente URL como geojson [Consulta API](https://services1.arcgis.com/LsoiDXzijohT7g97/arcgis/rest/services/COVID19ChileAcciones/FeatureServer/1/query?where=1%3D1&outFields=Nombre,Estado,Alcance,FInicio,FTermino,Cut_Com,Detalle,Shape__Area,Shape__Length,CuarentenaID&outSR=4326&orderByFields=CuarentenaID+ASC&f=pgeojson)

**Comment by scornejob** [comment]
gracias @Leandermen por la aclaracion. Entonces, tengo dos preguntas:
1.- Puedes revisar el output en el branch https://github.com/MinCiencia/Datos-COVID19/tree/issue139 ?
Si esta ok, entonces deprecamos el notebook, y dejamos el script.
2.- Si el input no se ocupa, tiene algun sentido que lo disponibilicemos en el repo? (esta segunda pregunta la podemos discutir por correo si quieres)

**Comment by scornejob** [comment]
hola @Leandermen , 

has podido revisar el output?

**Comment by Leandermen** [comment]
Hola Sebastian.
Disculpa mi retraso, te remitiré la consulta por correo

Saludos
