### ISSUE TITLE
Solicitud de Nuevo Producto

### ISSUE THREAD

**Issue by hco1975** [MinCiencia/Datos-COVID19#1392]
Como se ha mostrado en Issue anteriores, los productos 89 y 90 tienen importantes diferencias con los datos de defunciones del DEIS, siendo esta última base la más robusta.

Es por esto que se solicitó por transparencia los datos de defunciones tomando como base la planilla del DEIS, y adicionando los datos de Epivigilia y Campañas de Vacunación.

Luego de la espera por el consejo de Transparencia, y realizado el Amparo y los descargos iniciales (inicialmente rechazaron la entrega de información), finalmente Minsal entregó los datos solicitados, que es el detalle de los fallecidos por Covid probable y sospechoso, con Edad, Sexo, Fecha de Defunción, Fecha Epivigilia y Fecha Lab (estos 2 para identificar la fecha de inicio de síntomas), fecha de primera dosis de vacuna, tipo de primera dosis de vacuna, fecha de segunda dosis de vacuna, tipo de segunda dosis de vacuna, fecha de tercera dosis de vacuna, tipo de tercera dosis de vacuna, fecha de cuarta dosis de vacuna, tipo de cuarta dosis de vacuna.

Por este medio les comparto esa planilla entregada (hoja ORIGINAL), y agregamos una hoja con columnas calculadas.

SOLICITUD A MINCIENCIA: La apertura de este Issue es para solicitar a MinCiencia que realice esta misma solicitud a Minsal periódicamente, o que MinCiencia se encargue de cruzar los datos periódicamente y disponibilizar esos datos creando un nuevo producto. 
Está demostrado que Minsal puede generar este archivo.

Por otro lado, esta planilla demuestra lo que en Issue anteriores se sospechaba, Los productos 89 y 90 no contienen información robusta para poder realizar informes como el "Informe Epidemiológico" y obtener información relevante desde ellos. Y por otro lado, la información de inicio de síntomas es bastante ambigua y errada en algunos casos, provocando que personas sean catalogadas erróneamente en su estado de vacunación.

[cruce_defunciones_epivigila_y_vacunas_18_07_2022.zip](https://github.com/MinCiencia/Datos-COVID19/files/9229068/cruce_defunciones_epivigila_y_vacunas_18_07_2022.zip)

**Comment by hco1975** [comment]
Les recuerdo esta solicitud.

**Comment by IgnacioAcunaF** [comment]
Hola @hco1975,
Revisamos la solicitud con los equipos del Ministerio de Salud, sin embargo, no es posible generar esa información como producto para el presente repositorio Github. Las razón es debido a que la generación de dicho insumo es de un alto requerimiento para su elaboración en Minsal, y para el Ministerio de Ciencia no es posible realizar el cruce ya que son fuentes propias de la autoridad sanitaria. 

Saludos

**Comment by hco1975** [comment]
Ignacio.

Gracias por responder.

Debo manifestar mi desacuerdo con la respuesta, en cuanto que:

1.- El Ministerio de Salud mantiene una base de datos actualizada de fallecimientos, la cual deja disponible al público a través de la página de DEIS. Esto quiere decir que MINSAL tiene la información de fallecidos y causa de fallecimiento, pudiendo desprender fácilmente la causa de fallecimiento "Covid19" confirmado y sospechoso. Esta información MINSAL la tiene en detalle y con asociación de RUT para cada registro.
2.- El ministerio de Salud mantiene una base de datos de vacunados, en detalle con tipo de vacuna, marca, fecha de vacunación. Esta información MINSAL la mantiene en detalle y con asociación de RUT para cada registro. Sin esta información no podría entregar el dato para generar los pases de movilidad.
3.- El Ministerio de Salud mantiene una base de datos con las fechas de inicio de sintomas para cada persona con PCR positivo o marcado como sospechoso Covid. Esta base de datos la mantiene con RUT para cada registro.
4.- El Ministerio de Salud, a través del departamente de epidemiología, genera semanalmente 2 tablas de datos que comparte con el ministerio de ciencias: Los archivos https://github.com/MinCiencia/Datos-COVID19/blob/master/input/Vacunacion/carga_vacunacion_sem_epi.csv e https://github.com/MinCiencia/Datos-COVID19/blob/master/input/Vacunacion/incidencia_estado_vacunacion.csv. En esos archivos, el MINSAL entrega a la ciudadanía la cantidad de casos, ingreso a UCI y fallecidos, de manera consolidada. Con estos archivos el MINCIENCIA genera los archivos PRODUCTO89 y PRODUCTO90, con los cuales el MINSAL genera los informes epidemiológicos semanales. ¿Debieramos entender que no tienen acceso a los datos que originan esa consolidación?, ya que en esas consolidaciones se encuentran todos los términos involucrados en la solicitud realizada: Tienen la fecha de inicio de síntomas, tienen la fecha de defunción, tienen el estado de vacunación al iniciar síntomas. Si esos fallecidos no tienen como asociarlos a los fallecidos que el mismo MINSAL tiene en su base de datos DEIS, ¿De donde entonces sacan los datos?. 
5.- Como se señala en el punto 4, el MINSAL para poder generar los 2 archivos antes mencionados, necesariamente debe tener los datos en detalle, para luego poder consolidarlos en estos 2 archivos.
6.- Para cualquier científico de datos, es una tarea trivial y rutinaria juntar 2 tablas en una sola, utilizando un campo común, como lo es el RUT. Por cuanto no es una tarea difícil o costosa en tiempo de realizar. Un pequeño programa en Python puede tomar los datos desde las fuentes y consolidar.

En resumen. ¿Cómo el Minsal responde que no tiene ese archivo? ¿o que su generación es de un alto requerimiento?. Sabemos que Producto89 y Producto90 tienen problemas con la información que presentan, falta de datos, retraso en las entregas, y alto porcentaje de diferencias con la base de datos de Fallecidos de DEIS. ¿De donde sacan Producto89 y Producto90? ¿Es correcto su generación si manifiestan que obtener los datos como se requiere para un análisis no es posible?. Recordemos que las autoridades toman decisiones respecto al manejo de la pandemia con información que extraen de Producto89 y Producto90, y me señalas que en realidad la información de fallecidos y estado de vacunación Minsal no puede obtenerla, y visto de otra manera, no la tiene agrupada como se necesasita, y lo que entrega dista en más de 20 % de las bases de datos más robustas como la de Fallecidos de DEIS, ¿no cuenta con esa información?
