### ISSUE TITLE
datos de defunciones no se cargaron en la actualización diaria - 01 agosto. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1393]
https://github.com/MinCiencia/Datos-COVID19/tree/master/input/NuevaDefDefunciones no se actualizó en el proceso de hoy.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias por el reporte @ctroncoso 
Actualizado en bf42b69b65360b9f6c8221c8d42fcdf347e1a073

Saludos
