### ISSUE TITLE
 SOLICITUD NOTA ACLARATORIA PARA EL GATO SCHRODI

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1394]
¡Hola a todos! @MinCiencia ¡Espero que se encuentren muy bien! Si bien entiendo que por todos lados dicen que son datos provisorios, quería solicitar notas aclaratorias para que se entienda también cual es el alcance del concepto "provisorio"; 

1. Dejar en los productos correspondientes una aclaración de: Los datos ofrecidos respecto de los fallecidos por Covid 19 confirmado, se clasifican según la última toma de muestra positiva, al encontrarse una nueva muestra más cercana al fallecimiento en epivigila, desde octubre del 2021 no se modifican la causa de muerte (en ningún producto ni en el Deis) hasta la validación con el Ine, quedando como covid confirmado, pudiendo no haber sido así, hasta que se haga dicha validación. Como se aclaró en el issue #1390

2. Las personas consignadas como no vacunadas; vacunados pueden estar clasificados como no vacunadas por el concepto de inicio de síntoma. Eso en los productos que correspondan (89 y 90). como se puede observar en el issue #1360.

Digo yo, para que el gato entienda cómo es posible que esté vacunado y no vacunado a la vez y como es posible que esté fallecido por covid confirmado y no covid confirmado a la vez. Pobre Schrodi está muy confundido. jeje

Aún no queda claro si los esquemas incompletos, completos etc, del producto 89, ya están pre filtrados por esta variable y ni la definición ni la nota aclaratoria que existe se especifica, pues solo se puede interpretar que enfermó, llegó a UCI o falleció durante esa semana, pero no aclara si su estado de vacunación es el que tenía al momento de fallecer o al momento de comenzar a enfermarse. Solo puede quedar en el simple cruce de estado de vacunación (el cual se puede o no clasificar según cuando enfermó) y la semana que falleció. 

Asique Schrodi sigue confundido con la interpretación;

![image](https://user-images.githubusercontent.com/93507862/182444682-766954ca-d141-4d26-aedf-14ab59dc1b2c.png)

Que en el producto 89: dado que no se especifica, queda a libre interpretación, y bien podría ser algo así: que esta persona falleció en la semana 2022 -07, teniendo un esquema de vacunación incompleto (pues cuando se enfermó no contaba con alguna dosis). bien, segunda interpretación; podría haber sido que falleció en esa semana como 1er refuerzo menor a 14 días o tercera interpretación; como que falleció la esa semana con 2 refuerzo menor a 6 meses? 

Que en el producto 90: Esta persona enfermó el 24 de febrero del 2020, decidió vacunarse por primera vez casi al año después de haberse enfermado, el 5 de febrero del 2021. y se puso su cuarta dosis el 17 de febrero del 2022, y falleció 5 días después, el 22 de febrero del 2022. Ésta persona según el producto 90, está categorizado como NO VACUNADO, ya que AL momento de iniciar síntoma, vale decir el 24 de febrero del 2020, no ha recibido ninguna dosis de vacuna. 

Cito producto 89: 'estado_vacunacion' corresponde al estado de vacunación la que se clasifica en "con esquema completo" para aquellas personas que han sido inoculadas con dos dosis y han transcurrido más de 14 días desde su segunda inoculación o han recibido una vacuna de un esquema de vacunación que incluye únicamente una sola dosis y han transcurrido más de 28 días desde la inoculación. Esta variable toma el valor "sin esquema completo" si las personas no tienen un esquema completo de vacunación.

Cito: El producto 89 presenta los eventos de casos, ingresos UCI y defunciones, según ocurrencia en la semana de reporte. Estos son consolidados sin una actualización retrospectiva, por lo cual podría presentar diferencias con otros reportes que se emiten en paralelo.

En el producto 90, ya se que definen 'sin_vac_fall' indicando el número de casos confirmados que fallecieron de COVID-19 durante la semana epidemiológica correspondiente y que AL iniciar síntomas (sintomáticos) o  AL momento de la toma de muestra (asintomáticos) no ha recibido ninguna dosis de vacuna.

Ojalá pudieran aclararlo, dado que muchos quizás estén interesados en poder interpretar correctamente las variables. 

Que tengan un buen día. 

Saludos,

**Comment by IgnacioAcunaF** [comment]
Hola @daniamr,
Muchas gracias por tu recomendación y por las indagaciones. Lo revisaremos con MINSAL en miras de clarificar las dudas de los productos.
Saludos

**Comment by daniamr** [comment]
Muchas gracias, ojalá puedan clarificar, sobre todo lo del producto 89, si ya están filtrando el estado de vacunación cuando enfermó o cuando falleció. 

Gracias. 

Saludos,

**Comment by IgnacioAcunaF** [comment]
Hola @daniamr,
Gracias por la paciencia. Para clarificar y agrega como aclaración el Readme (eb4e698584203c5c3e0de8b38655ccd08af040c1), el producto 89 (al igual que el producto 90) usa la fecha de inicio de sintomas:

**Nota aclaratoria producto 89**

>Para generar la categorización de estado de vacunación, se calcula el tiempo transcurrido entre la fecha de inicio síntomas y la última fecha de vacunación

El caso en particular:

>Que en el producto 89: dado que no se especifica, queda a libre interpretación, y bien podría ser algo así: que esta persona falleció en la semana 2022 -07, teniendo un esquema de vacunación incompleto (pues cuando se enfermó no contaba con alguna dosis). bien, segunda interpretación; podría haber sido que falleció en esa semana como 1er refuerzo menor a 14 días o tercera interpretación; como que falleció la esa semana con 2 refuerzo menor a 6 meses?

Dada la definición anterior, la persona al inicio de síntomas no contaba con alguna dosis, por lo que clasifica en el producto 89 como _Sin esquema completo_, siendo la primera interpretación que mencionas la correcta _(pues cuando se enfermó no contaba con alguna dosis)_

Es decir, ambos productos utilizan el tiempo entre la **fecha de inicio de síntomas** y la última **fecha de vacunación**.

-----
Aprovecho el issue tambien para informar que tambien se agrego una descripción de los tipos de estado_vacunación que puede tener el producto 89 en d37286c177ce209ef94730e728387f0731bcb8db

**Comment by daniamr** [comment]
@IgnacioAcunaF muchas gracias por tu pronta respuesta!! 

El gato Schrodi ahora está menos confundido. 

Saludos!

**Comment by daniamr** [comment]
@IgnacioAcunaF, la nota aclaratoria se incorporó hoy?

**Comment by IgnacioAcunaF** [comment]
Si, la incorporé en el README del 89 hace dos horas (https://github.com/MinCiencia/Datos-COVID19/commit/eb4e698584203c5c3e0de8b38655ccd08af040c1)

**Comment by daniamr** [comment]
@IgnacioAcunaF muchas gracias!!!!

**Comment by daniamr** [comment]
@IgnacioAcunaF entonces quiere decir que los INFORME EPIDEMIOLÓGICO De 
INCIDENCIA Y GRAVEDAD DE CASOS COVID-19 SEGÚN ANTECEDENTE DE
VACUNACIÓN
 
Citan el producto 89 como fuente de datos, ergo, las incidencias calculadas son sobre esquemas basados en inicio de sintoma.

Estoy en lo correcto?

**Comment by IgnacioAcunaF** [comment]
Hola @daniamr 
Correcto.
Saludos
