### ISSUE TITLE
Producto 15 no se actualizó el sábado pasado

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1395]
Hola, estaba revisando los datos del reporte epi y me fijé que no se actualizaron datos epi del producto 15. 

Ojalá puedan actualizarlos.

Saludos cordiales,

**Comment by Themrpie** [comment]
Acá también estamos a la espera, son varios productos que no se han actualizado. Ojalá lo puedan hacer pronto.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @weichafan por el reporte.
El producto 15 se encuentra actualizado en 873a326e2ad4964b7c03c8c65c99c4d59e8ac508.

Saludos
