### ISSUE TITLE
No cargó input de reporte diario. Action corrió bien pero con información de ayer. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1397]
No se actualizó carpeta input de Reporte diario previo a la ejecución del Action. Datos procesados son los de ayer.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso 
Actualizado en c7a7d47a893e60d0a4b554467bd8f55311290748

Saludos

**Comment by ctroncoso** [comment]
Excelente! Grax!
