### ISSUE TITLE
No se actualizaron los datos de defunción. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1399]
Hola! NuevaDefDefunciones nuevamente no cargó.  
Creo que habrá que poner una alarma en el código para que avise cuando los datos no estén disponibles al momento de la carga.

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso de nuevo por reportar.

La situación ocurre cuando él insumo se genera después de un horario de corte (y por lo que luego hay que hacerlo manual), por lo que en el commit se f439d9a0167b49ff0be9b8142ebbcbe4346204ce se agregó una segunda ejecución a las 13:00.

Estaremos monitoreando el comportamiento.
Saludos!

**Comment by ctroncoso** [comment]
Gracias @IgnacioAcunaF . Me imaginaba que era por un desfase en horario de corte. Igual estaré vigilando para avisar en caso de ocurrir. Excelente y gracias por todo!

**Comment by ctroncoso** [comment]
Ahh.. ojo con el cambio de horario, ya que asumo que estos cron corren en horario UTC, para estar atentos. Saludos!

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @ctroncoso.
Actualizado en f4729237e9c1570640ec66a434f9a8359f0cf5b8.

Si, estan en GTM-0, asi que es un factor a considerar.

Saludos
