### ISSUE TITLE
no se cargó reporte diario en la actualización de hoy 13 agosto.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1400]

**Comment by IgnacioAcunaF** [comment]
Hola @ctroncoso
Gracias por reportar
Actualizado en 6204df49be9d9d792ceb6344ee64600b5f2c7c71 (ahora está ejecutandose el proceso a las 11:00 y a las 13:00)
Saludos

**Comment by ctroncoso** [comment]
Excelente, Gracias Ignacio!
