### ISSUE TITLE
Estado de vacunación incorrecto en P89 (80 años o más)

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#1401]
Hola! En la última actualización del producto 89 ha aparecido entre las categorías de `estado_vacunacion` la opción "80 años o más", lo que claramente es un error. Se les debe haber corrido algún dato de edad en la captura de información
![image](https://user-images.githubusercontent.com/63430031/184500988-459b63da-edb3-4102-a545-7c6ca24dc34b.png)

Saludos! Muchas gracias

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @paarriagadap 
Lo reportaremos con MINSAL para que puedan corregir de origen.

Saludos

**Comment by IgnacioAcunaF** [comment]
Actualizado en cb8660a295f04ce9d0d052454309f40103319d50
Saludos!
