### ISSUE TITLE
Errores en datos

### ISSUE THREAD

**Issue by Themrpie** [MinCiencia/Datos-COVID19#1402]
Hola. Encontré otros errores en el producto89 y también en el 52 donde aparece que hay -3 camas en Magallanes

<img width="1037" alt="Captura de Pantalla 2022-08-13 a la(s) 15 44 30" src="https://user-images.githubusercontent.com/73369706/184508671-fde7e859-3aa8-4368-bc82-ac3a4ef0acd8.png">
<img width="1054" alt="Captura de Pantalla 2022-08-13 a la(s) 15 37 39" src="https://user-images.githubusercontent.com/73369706/184508675-86d024e5-6eb3-4131-bc0a-98759a430934.png">

<img width="981" alt="Captura de Pantalla 2022-08-13 a la(s) 15 47 43" src="https://user-images.githubusercontent.com/73369706/184508668-5432b87e-8095-4a7c-b949-f58c01347dbd.png">

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @Themrpie por el reporte
Esta al tanto el Ministerio de Salud para la revisión de dichos insumos.

Saludos!

**Comment by IgnacioAcunaF** [comment]
Muchas gracias @Themrpie por el reporte.
El producto 52 se encuentra actualizado en 1b7922d4a515c98780259ab7b4035bd719c41804. El producto 89, como se menciono en el otro issue, se solvento el cb8660a295f04ce9d0d052454309f40103319d50.

Saludos
