### ISSUE TITLE
Actualización EPI corrió ayer, pero no veo actualizaciones en los datos. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1403]
El pr16 que debería salir de estas actualizaciones, dice que fue actualizado hace 5 días, y el action corrió ayer. 
¿Problemas con las fuentes?

**Comment by IgnacioAcunaF** [comment]
Hola @ctroncoso 
Gracias por reportar. En efecto estamos viendo una situación con el servidor, por lo que el insumo aun no se procesa. 
Estamos trabajando para solucionar ASAP.

Saludos

**Comment by ctroncoso** [comment]
Todo el FUAA my friend. Gracias!

**Comment by IgnacioAcunaF** [comment]
Muchas gracias!!!
Actualizado en 7f373f5b069cbbc52bfd51425c628d329669e9be
El informe de Epi de mañana ya esta cargado asi que no debería haber atraso con el

Saludos y buen finde
