### ISSUE TITLE
Data product 22 y 30. Desagregar datos por comuna

### ISSUE THREAD

**Issue by iamalonso** [MinCiencia/Datos-COVID19#1404]
Hola, es posible obtener datos desagregados por comuna correspondientes a los Data Products 22 y 30.

Saludos,
Alonso

**Comment by iamalonso** [comment]
@IgnacioAcunaF Podrías darnos información acerca de si es posible obtener datos desagregados por comuna correspondientes a los Data Products 22 y 30.

Agradezco mucho la ayuda que puedas prestarnos 👍🏽

**Comment by IgnacioAcunaF** [comment]
Hola @iamalonso
Espero estés muy bien. Desde hace algunos días no me encuentro ejerciendo labores en el Ministerio. 
Recomiendo dirigir la solicitud a [futuro@minciencia.gob.cl](mailto:futuro@minciencia.gob.cl) 

Saludos!
