### ISSUE TITLE
EFECTIVIDAD VACUNA - BASE CALCULO PROD. 89

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1408]
Hola buen día @minciencia, @IgnacioAcunaF,@jorgepacheco84

Esperando que se encuentren, quería consultar sobre los cálculos de la efectividad de la vacuna. 

Según este post de ustedes, 
https://github.com/jorgepacheco84/metodo_tamizaje

Se entiende que usan el método tamizaje, pero no dice desde cuando se usa y si actualmente se está usando ese para hacer ese cálculo. 
 

Les agradecería mucho si pudieran decirme desde que fecha a qué fecha se ha usado ese método, con el producto 89 como base de datos para generar el cálculo.  

Quedo atenta. 

Y desde ya, muchas gracias!! 

Saludos,

**Comment by IgnacioAcunaF** [comment]
Hola @daniamr 
Con respecto al link enviado, no corresponde a una fuente oficial de este repositorio, si no que a un proyecto individual, por lo que no aplican los metodos alli referidos.

El producto 89 calcula la incidencia, según el README: 
> (...) corresponde a la tasa de incidencia (por cada 100 mil habitantes) para el grupo de edad

Es decir, la operación entre las incidencias sería casos_confirmados / población = incidencia_cruda_confirmados, por ejemplo

Saludos

**Comment by daniamr** [comment]
Ah, gracias que buena aclaración. 

Igual sería bueno saber si para obtener la eficacia de la vacuna si usan o no los esquemas filtrados por inicio de sintoma.

Quedo atenta. 

Saludos,
