### ISSUE TITLE
EFICACIA VACUNA - ESQUEMAS -INICIO DE SINTOMA 

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1411]
Hola buen día, como están? 

Tengo dudas, cuando sacan los cálculos de la eficacia de la vacuna, los esquemas están filtrados según la variable inicio de síntoma? 

Quedo atenta. 

Saludos,

**Comment by IgnacioAcunaF** [comment]
Hola @daniamr 
¿A cual producto en particular te refieres?

Saludos

**Comment by daniamr** [comment]
La verdad es que no he visto ningún producto, pero quizás sepan ustedes o podrían solicitar esos datos a minsal para generar un nuevo producto.

**Comment by IgnacioAcunaF** [comment]
Entiendo, la pregunta acerca de qué producto era para contextualizar la respuesta.
Eso corresponde más a a las conclusiones que se puedan hacer con los datos disponibles, en un contexto de investigación. 
Te dejó [el enlace de un documento del Ministerio de Salud](https://www.minsal.cl/wp-content/uploads/2022/06/Cuarta-dosis-de-vacuna-contra-SARS-CoV-2-en-poblacio%CC%81n-general-desde-los-18-an%CC%83os-ACTUALIZACIO%CC%81N.pdf) donde se habla acerca de la efectividad de las vacunas, y donde se cita a un [estudio realizado en Chile](https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(22)00112-7/fulltext#:~:text=a%20third%20dose.-,Our%20results%20suggest%20that%20a%20homologous%20or%20heterologous%20booster%20dose,protection%20than%20the%20homologous%20booster.), con datos del país, para que puedas leer más de la metodología. 
Sin embargo eso (y las preguntas asociadas) es externo a este repositorio, y escapa de los alcances de este (que busca entregar datos para habilitar estos análisis ). 

Espero que esto te pueda ayudar
Saludos
