### ISSUE TITLE
EFICACIA VACUNA - ESQUEMAS INICIO DE SÍNTOMA

### ISSUE THREAD

**Issue by daniamr** [MinCiencia/Datos-COVID19#1412]
Hola buen día, como están?  @minciencia @IgnacioAcunaF. 

Tengo dudas, cuando sacan los cálculos de la eficacia de la vacuna, los esquemas están filtrados según la variable inicio de síntoma? 

Quedo atenta. 

Saludos,

**Comment by IgnacioAcunaF** [comment]
Duplicado de https://github.com/MinCiencia/Datos-COVID19/issues/1411
