### ISSUE TITLE
No cargó Reporte Diario  20-ago

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1414]
action corrió ok, pero carpeta input no contiene los datos de hoy.
https://github.com/MinCiencia/Datos-COVID19/tree/master/input/ReporteDiario

**Comment by IgnacioAcunaF** [comment]
Actualizado en e695ad680295f56e027755f810b139f011dbc291.
Gracias @ctroncoso x reportar.
Buen finde!

**Comment by ctroncoso** [comment]
Gracias! Buen finde también!
