### ISSUE TITLE
Productos 91 y 92 sin actualizar por 17 días

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1416]
Hola estimados, 

Será posible verificar la situación de productos 91 y 92 que hace un par de semanas no se actualizan.

Saludos y gracias

**Comment by MinCiencia** [comment]
Hola @weichafan , muchas gracias por reportar.

El proceso se ha ejecutado recientemente de forma correcta, los datos se encuentran disponibles.

Saludos
