### ISSUE TITLE
Productos diarios no se están actualizando

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1418]
Estimados, hace 3 días los productos del balance diario no se están actualizado. Productos tales como el 3, 8,9, 24 

Saludos y gracias de antemano

**Comment by ctroncoso** [comment]
Efectivamente, el último registro del reporte diario es del día 13.

**Comment by lcvidelam** [comment]
Por favor actualizar

**Comment by MinCiencia** [comment]
Estimados, muchas gracias por reportar.

Hemos remitido la información al Minsal para su debida actualización.

Saludos

**Comment by ctroncoso** [comment]
Usualmente estos problemas estaban resueltos a las pocas horas. Hoy tampoco hubo actualización.

**Comment by ishmaster** [comment]
Hola!
Cuál es el estatus del problema de actualización de datos? Cuándo se va a resolver?
Gracias!

**Comment by felipeelorrieta** [comment]
Hola Cuando se vuelven a actualizar los productos del balance diario?

**Comment by MinCiencia** [comment]
Estimados, les pido las disculpas correspondientes. Estamos con un problema de actualización que no hemos podido resolver, pero estamos avanzando con un equipo dedicado para que vuelva a funcionar correctamente lo antes posible.
Les comentaremos por este medio cuando esté disponible.

Saludos!

**Comment by ctroncoso** [comment]
En lo que podamos asistir, creo que habemos varios dispuestos a ayudar a que este servicio y otros de datos abiertos se mantengan vigentes tanto para este como otras métricas.

**Comment by ctroncoso** [comment]
Se produjo un error al actualizar el balance diario del repositorio remoto.
![image](https://user-images.githubusercontent.com/121016/191765971-db6cf62f-98e9-4468-9700-5f9aa1cb51ae.png)
Ese action se ejecutó manualmente, pero el repositorio, al parecer se modificó durante por otro proceso durante la ejecución y quedaron fuera de sincronía. Hay que correrlo nuevamente

**Comment by MinCiencia** [comment]
Gracias! volvimos a correrlo pero sigue cayéndose. Tenemos la teoría que tiene que ver con el formato del reporte diario. Les vamos contando cualquier novedad.

**Comment by ctroncoso** [comment]
> Gracias! volvimos a correrlo pero sigue cayéndose. Tenemos la teoría que tiene que ver con el formato del reporte diario. Les vamos contando cualquier novedad.

El error se produce al hacer el commit al remote.  

El pull de Datos-Covid19 y del repositorio de preparación corren ok.
Rsync entre output de preparación e input Datos-Covid19 también ccorre sin problemas.
Instalación de python y dependencias corren ok.
Scripts que generan el output también corre ok.

El error se produce en el commit de Datos-Covid19.
Indica que el repositorio destino (github) tiene un commit que no está en el local (lo que no tiene mucho sentido)

Probaría con un `git log` en el local y en el remoto para verificar que el error sea efectivamente falta de sync.

**Comment by ctroncoso** [comment]
oki.. ya corrió bien el action. Ahora falta que carguen los archivos en el repositorio de preparación.
Esos deberían provenir de un SFTP del minsal.

**Comment by MinCiencia** [comment]
Muchas gracias por las recomendaciones, nos sirvieron para ir esclareciendo el problema. Los productos fueron actualizados.

Saludos!

**Comment by ctroncoso** [comment]
Así he visto. Tediosa la tarea de correr el proceso por cada día, pero veo que se van llenando bien los datos. 
Gracias por el esfuerzo y en lo que se pueda aportar, totalmente disponibles.

**Comment by MinCiencia** [comment]
Ya, ahora si quedó actualizado. Nuevamente muchas gracias por las recomendaciones, nos sirvieron para ir acotando el problema. Los productos fueron actualizados, nos comentan cualquier cosa!
Vamos a monitorear de cerca las próximas cargas.

Saludos y gracias nuevamente.

**Comment by ctroncoso** [comment]
Hoy carga de reporte diario operó casi bien, salvo la carga de `/input/NuevaDefDefunciones` qué no se concretó.
