### ISSUE TITLE
Jupyter Notebook MinCiencia - Nombre Columnas

### ISSUE THREAD

**Issue by Karlangaz** [MinCiencia/Datos-COVID19#142]
Estimados,

Desde que se agregaron casos nuevos asintomáticos,, el jupyter que se publica tiene errores,
Es factible corregirlo?, en mi poco conocimiento, creo que se debe a que las columnas de los CSV cambia a parir del 29 de Abril en adelante.

Existe otro caso: en el codigo de graficar varios días, en la linea 

dataTotalRecuperados = pd.read_csv("https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/recuperados.csv", index_col=0)

También se esta cayendo, al parecer cambio el archivo

saludos.
![Captura](https://user-images.githubusercontent.com/49219231/81084513-f5185180-8ec3-11ea-9c8c-9020e2f8009c.JPG)

**Comment by scornejob** [comment]
gracias @karlagaz . El error se debe a que esa serie la movimos de ese archivo a "TotalesNacionales.csv", dentro del  mismo producto. Actualizaremos el notebook en breve.

**Comment by karlagaz** [comment]
> gracias @karlagaz . El error se debe a que esa serie la movimos de ese archivo a "TotalesNacionales.csv", dentro del mismo producto. Actualizaremos el notebook en breve.

Gracias!

**Comment by fzmolina** [comment]
Hola Karlangaz, muchas gracias por tu reporte. Tuvimos una secuencia de errores, una de ellas es la que explicó scornejob, la otra se debe al cambio en las columnas que entrega el Ministerio de Salud en su reporte diario. Al momento ambos problemas están solucionados, y agradecemos reportar los problemas que puedas tener en el futuro, pues la información es bastante dinámica.

Entonces, el notebook que publicamos primero nos pareció muy extenso, así que se dividió en tres: https://github.com/MinCiencia/Datos-COVID19/blob/master/DataObservatory_ex1.ipynb, el segundo y tercero siguen con 'ex2.ipynb' y 'ex3.ipynb' al final. Tienen el contenido del anterior. La migración a utilizar 'TotalesNacionales.csv' (producto 5) supone una mejora en los gráficos con los totales nacionales en vez de usar el producto 4.

**Comment by Karlangaz** [comment]
lo estoy revisando!, muchas gracias!

Saludos.
