### ISSUE TITLE
excess mortality

### ISSUE THREAD

**Issue by dbangcal** [MinCiencia/Datos-COVID19#1420]
Hola,
¿Puedes actualizar el archivo .PNG de exceso de mortalidad?

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto96/Excess_Mortality.png

O, ¿podrías enseñarme cómo hacerlo?

Gracias,
David (No hablo español)

------------------------

Hello,
Can you update the excess mortality .PNG file?

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto96/Exceso_Mortalidad.png

Or, could you teach me how to do it?

Thank you,
David

**Comment by ctroncoso** [comment]
Are you familiar with coding in "R" ?
If so, you'll find the code that renders that file in `/src/exceso_mortalidad.R`

We should check on that, as the action that renders product 96 executes without issues.

**Comment by ctroncoso** [comment]
@MinCiencia habría que probar corriendo el script R en forma local para ver que se genere bien el png. No veo problemas en el código. ¿Puede ser la ruta o que no se incluya en el commit?

**Comment by MinCiencia** [comment]
Hi @dbangcal 

We have updated the consulted png graphic.

To generate it, you must have R and RStudio installed, then run the `https://github.com/MinCiencia/Datos-COVID19/blob/master/src/exceso_mortalidad.R` file locally, this file will generate the png and csv files on your computer.

Attached modified `exceso_mortalidad_2.R` file, which was used only to generate the png graphic (change txt extension to R).

[Exceso_mortalidad_2.txt](https://github.com/MinCiencia/Datos-COVID19/files/9650100/Exceso_mortalidad_2.txt)

Best regards


@ctroncoso gracias por colaborar, en respuesta a tu consulta no está incluido en el commit. Saludos!

**Comment by ctroncoso** [comment]
Excelente!

@dbangcal , the png should now be available in the repository and updated regularly.
