### ISSUE TITLE
Datos EPI no se cargaron sábado 1 de octubre

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1421]
Hola, 

Por favor, ojalá puedan actualizar los datos epi del sábado. Productos como el 15, 16, 22, 39, 61. 

Saludos cordiales,

**Comment by MinCiencia** [comment]
Hola @weichafan , gracias por reportar.

Informamos que debido a cambios en el reporte COVID, en el documento se señala lo siguiente:

_"Por definición de Jefatura de DIGERA, información sobre la Subsecretaría de Redes Asistenciales no se actualizará durante los fines de semana. Valor reflejado es lo último reportado."_

Tras lo cual, el proceso que se encontraba automatizado se encuentra con unos problemas en los cuales nos encontramos trabajando.

Saludos

**Comment by MinCiencia** [comment]
Hola @weichafan,

Se han actualizado los datos en https://github.com/MinCiencia/Datos-COVID19/commit/749b35e4fdab9dfabf939683432bb8d9236d2b8b

Saludos
