### ISSUE TITLE
Falla general en actualización de reporte diario y epi.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1423]
El reporte diario ha tenido fallas desde el 1 de octubre. Datos sin actualizar principalmente. 
El informe epi, se recibió con los mismos datos que el informe anterior y sin actualización. 

Creo que es necesario saber si esto tiene un problema de origen, donde el minsal / deis, no están enviando la información, o hay problemas en el procesado de datos desde Minciencia. 

Estamos en una fase crítica en que se está probando una nueva estrategia en un escenario de mayor contagio que el año pasado y no poder medir el resultado puede ser muy contraproducente. 

El sistema de información abierta que se ha generado en Chile ha sido alabado en todo el mundo, y no corresponde dejar que se oxide y desarme.  Tenemos algo que no existe ni en países que llamamos "referentes" como Noruega o Suecia, y que ahora ellos nos miran a nosotros como referente. 

En qué podemos ayudar para que esto no se desarme.

**Comment by MinCiencia** [comment]
Hola Carlos, estamos revisando para entender la raíz de la falla. Los mantendremos al tanto.

Saludos,

**Comment by ctroncoso** [comment]
Gracias y en lo que se pueda ayudar, habemos muchos siempre dispuestos.

**Comment by MinCiencia** [comment]
Hola @ctroncoso , gracias por reportar.

Informamos que debido a cambios en el reporte COVID, en el documento se señala lo siguiente:

_"Por definición de Jefatura de DIGERA, información sobre la Subsecretaría de Redes Asistenciales no se actualizará durante los fines de semana. Valor reflejado es lo último reportado."_

Tras lo cual, el proceso que se encontraba automatizado se encuentra con unos problemas en los cuales nos encontramos trabajando.

Saludos

**Comment by ctroncoso** [comment]
OK, entonces el problema se origina en la fuente. Esperemos que lo tengan solucionado durante la semana.

**Comment by MinCiencia** [comment]
Hola Carlos, al parecer ya identificamos el problema, estamos haciendo pruebas y les comentamos si funciona.

Saludos,

**Comment by weichafan** [comment]
Gracias, 

Y suerte con los arreglos. Estamos pendientes al igual que Carlos.

**Comment by ctroncoso** [comment]
> Hola Carlos, al parecer ya identificamos el problema, estamos haciendo pruebas y les comentamos si funciona.
> 
> Saludos,

Excelente, y como siempre, en lo que podamos aportar, estamos al pie del cañón.

**Comment by ctroncoso** [comment]
> Hola Carlos, al parecer ya identificamos el problema, estamos haciendo pruebas y les comentamos si funciona.
> 
> Saludos,

Al menos hoy no logró pasar la barrera. 
¿Están con problemas de preproceso en el repositorio privado?

Recuerden que tenemos un servidor discord para minciencia. Nadie lo pescó mucho, pero si es práctico para ayudar a sacar estos problemas, les dejo el enlace. 
https://discord.gg/jPHbedaH 
![image](https://user-images.githubusercontent.com/121016/194133200-1cef1a9f-f7a6-49b7-8808-7625ae2cb903.png)

**Comment by weichafan** [comment]
Ojala identifiquen luego el problema

**Comment by MinCiencia** [comment]
Ya fue identificado el issue y resuelto, hubo que modificar el código! Problema con el reconocimiento de las fechas, pero ya solucionado.

Saludos,

**Comment by MinCiencia** [comment]
Estimados,

Se ha subido una actualización del código, los productos de reporte diario se han actualizado correctamente.

Saludos

**Comment by ctroncoso** [comment]
Excelente Gracias!
