### ISSUE TITLE
Faltan informes epidemiológicos del día Sep--30 y Oct-7

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1427]
Estuve revisando la carpeta input de Informes Epidemiológicos, y veo que faltan 2 informes de los viernes 30 de septiembre y 7 de octubre. 
Como son datos que se analizan comparando semana anterior, complica el tener este agujero de 2 semanas continuas. Se vé que es un problema de origen de datos, pero esto afecta varios productos (1, 2, 6, 15, 16, 18, 19, 21, 22, 25, 28, 34, 35, 38, 39, 45). 
Creo conveniente revisar con minsal si este informe ha perdido prioridad, ya que incluso en el sitio de minsal, no se actualizan los epi desde el 19 de sept. 
![image](https://user-images.githubusercontent.com/121016/196056865-aa199b71-628d-4d99-9c72-e2a10542d7f4.png)

**Comment by MinCiencia** [comment]
Hola @ctroncoso , muchas gracias por reportar.

Remitiremos la información a MINSAL para su actualización.

Saludos

**Comment by MinCiencia** [comment]
Hola @ctroncoso ,

Desde minsal no indican que en su sitio web se encuentra la información.

https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/

Por otro, se ha solicitado a segegob la actualización de información que nos reportaste puesto que ellos administran ese sitio web.

Saludos

**Comment by ctroncoso** [comment]
Perfecto. 
Estuve revisando en el sitio de minsal, y por folio correlativo no existen los informes de esas fechas. No se realizaron.
Solo hay continuidad semanal en los informes publicado los lúnes, pero los de  los viernes, no tienen continuidad semanal.
Gracias!
