### ISSUE TITLE
Datos reporte epi

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1428]
Hola, buenas. 

Escribo para preguntar por los datos del reporte epi que se actualizaba los días miércoles. Productos como el 15, 16, 22 no han sido actualizados.  

Se podrán actualizar,  muchas gracias.

**Comment by MinCiencia** [comment]
Hola @weichafan ,

Gracias por reportarnos esta situación la cual estamos revisando.

Saludos

**Comment by ctroncoso** [comment]
@weichafan ... no se si no se publican, no se generan o qué, pero el último reporte epi... [207](https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/), es del 10 de octubre (publicado el 12).
Debería haber salido uno el 17 y publicado el 19. No salió 
Hoy 21 debería salir otro y publicarse este domingo. Veremos.

**Comment by ctroncoso** [comment]
Vi un intento de correr manualmente el Epi 208 que salió hoy y tiene fecha lunes 17. 
Debería haber sido publicado el miércoles 19, pero por lo visto, está atrasado. 
Lamentablemente el proceso terminó OK pero no cargó nada. 
Por la estructura del proceso, no se actualizó en el repositorio privado `MinCiencia/InformeEPI-input`. Ahi ya no podemos ayudar ya que está fuera de nuestra visibilidad y capacidad de acción.

**Comment by ctroncoso** [comment]
@MinCiencia, se podría intentar correr manual el informe epi hoy? Ya está el 208, pero por lo que veo no cargó. Puede que ya esté listo para correr.  Grax!

**Comment by ctroncoso** [comment]
No funcionó. Corrió el proceso pero no cargó nada. 
¿Podemos ayudar en algo @MinCiencia ?

**Comment by weichafan** [comment]
Cierro este, porque no se cargaron datos del 19, ahora faltan del 19 y 22 como pido en el issue #1430
