### ISSUE TITLE
Falló carga de informe diario 24.oct.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1429]
Favor revisar que se haya cargado los datos del informe diario del Minsal. No hubo actualización en ninguna de las 2 corridas de Actualiza Balance Diario.

**Comment by MinCiencia** [comment]
Hola @ctroncoso , gracias por reportarnos la situación.

Efectivamente el reporte del 24 de octubre tenía unos errores en formato de datos, se han realizado las correcciones y ejecutado ambos procesos pendientes 24 y 25.

Saludos

**Comment by ctroncoso** [comment]
> Hola @ctroncoso , gracias por reportarnos la situación.
> 
> Efectivamente el reporte del 24 de octubre tenía unos errores en formato de datos, se han realizado las correcciones y ejecutado ambos procesos pendientes 24 y 25.
> 
> Saludos

Impecable. Creo que todos hemos tenido que lidiar con esas extracciones que cambian a lo largo del tiempo. 
Bien, veremos como sale todo hoy. Exito!
![image](https://user-images.githubusercontent.com/121016/197797702-b0fee3bf-4c95-4c19-aeb3-d3059833e918.png)
