### ISSUE TITLE
Datos reportes epidemiológicos de los días 19 y 22 de octubre no han sido publicado con éxito

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1430]
Estimados, 

No han sido actualizados productos asociados a reportes epidemiológicos esperados el miércoles 19 y luego el sábado 22 de octubre. 

No se han actualizado productos como el 15, 16, 22, 39  

Gracias

**Comment by ctroncoso** [comment]
@weichafan : 
Revisé también y solo está el reporte 208.
Las fechas son medio enredadas.
El 208 tiene fecha de creación Lunes 17, debería haberse publicado el 19, pero se publicó el 21.
El informe 209 debería haberse creado el 21 y publicado el 23. Hasta la fecha o no se ha publicado o no fue creado.

![image](https://user-images.githubusercontent.com/121016/197646084-9d82a12d-2b2a-4f82-a16f-2135f53afcca.png)

Entonces, tenemos pendiente el que se procese y publique en GitHub el informe 208, y ver si se hizo o no el 209. De haberse hecho, esperar a que sea publicado y procesado.

**Comment by MinCiencia** [comment]
Estimados, muchas gracias por levantar esta observación.

Hemos solicitado a MINSAL la actualización de datos en la plataforma.

Saludos

**Comment by ctroncoso** [comment]
Un gusto. Y gracias por mantener todo esto funcionando. En serio, lo mostré a un grupo de epidemiólogos suecos y quedaron fascinados. "Nosotros no tenemos nada así en Suecia".  Esta plataforma de acceso transparente a la información es una creación espectacular.

**Comment by MinCiencia** [comment]
Hola @weichafan , @ctroncoso , muchas gracias por reportarnos la situación.

Se han terminado de procesar los informes epidemiológicos que se encontraban pendientes, con ello se han actualizado todos los productos que estaban atrasados.

Saludos
