### ISSUE TITLE
Actualización producto19

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1431]
Estimados,

Agradeciendo de antemano su apoyo, quisiera consulta por la posibilidad de actualizar el producto 19 "Casos activos por fecha de inicio de síntomas y comuna", el cual lleva 13 días sin se actualizado como se muestra en la siguiente imagen:

![image](https://user-images.githubusercontent.com/50386332/198588430-04ebe6de-b2da-4e0a-a75f-c6bca01343ae.png)

Saludos,

**Comment by MinCiencia** [comment]
Hola @sebawsky , muchas gracias por reportarnos la situación.

Se han terminado de procesar los informes epidemiológicos que se encontraban pendientes, con ello se han actualizado todos los productos que estaban atrasados incluido el reportado por tu persona.

Saludos

**Comment by ctroncoso** [comment]
Gracias! Vimos el proceso. Gracias por el esfuerzo, compromiso y dedicación. Kudos!
