### ISSUE TITLE
Informe diario no cargado - publicación y procesado. (SeGeGob?)

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1432]
El día de ayer, no se cargó el informe diario del 31 de oct en github. Aún así, el informe si fue publicado en el sitio web de datos oficiales. 
Hoy tampoco se cargó el informe diario en github y aunque si pareciera que hubo un intento de subir el informe al sitio web, los permisos para descargarlo están malos. ¿Esto lo tendría que ver la SeGeGob?

![image](https://user-images.githubusercontent.com/121016/199337517-0e494622-008a-4ba3-b1c4-56f6ff4fb83b.png)

Si la falta de carga de datos en github, responde a algo normal de fin de semana. Esperaremos el martes para ver los datos. Gracias por el trabajo!

**Comment by MinCiencia** [comment]
Hola @ctroncoso, gracias por reportarnos la situación.

¿en cual url estas tratando de obtener el archivo?

Saludos

**Comment by ctroncoso** [comment]
En https://www.gob.cl/pasoapaso/cifrasoficiales/#datos
pero creo que esto es responsabilidad de la secretaría general de gob. 

![image](https://user-images.githubusercontent.com/121016/199505743-743c65ae-611f-463c-8422-f00da5363814.png)

**Comment by ctroncoso** [comment]
Respecto al informe diario. Luego de que corriera hoy el proceso, se vé actualizado hasta el día 31. Hay aún 2 reportes diarios que no se han cargado.

**Comment by MinCiencia** [comment]
Hola @ctroncoso, gracias por reportarnos la situación.

Efectivamente los datos en Cifras Oficiales las actualiza segegob, hemos tomado contacto con ellos para su actualización.

Saludos

**Comment by MinCiencia** [comment]
Hola @ctroncoso ,

La información ya se encuentra actualizada en la pagina web.

Saludos y gracias por reportarnos.

**Comment by ctroncoso** [comment]
Espectacular. Gracias!
