### ISSUE TITLE
Actualización Productos 7, 13, 19, 49, 58 (y otros)

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1433]
Estimados,

Esperando se encuentren bien quisiera consultar respecto a la actualización de algunos productos  7, 13, 19, 49 y 58 (principalmente estos pero entiendo que hay otros que se encuentran en la misma situación). La fecha máxima disponible actualmente en los datos es el 31-10-2022 (actualizado hace unos minutos atrás desde la creación de este Issue), cuándo tienen considerado actualizar el día pendiente?

Gracias de antemano y quedo atento !

**Comment by MinCiencia** [comment]
hola @sebawsky , gracias por reportar.

Efectivamente estamos revisando un problema relacionado al formato de los datos del día 01 de noviembre.
Esperamos poder resolver este problema lo más pronto posible.

Saludos

**Comment by MinCiencia** [comment]
Hola @sebawsky , se han actualizado los productos obtenidos del reporte diario.

Productos que son obtenidos desde el informe EPI, serán actualizados a la brevedad.

Saludos
