### ISSUE TITLE
Informe epidemiológico 2 de nov con problemas

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#1434]
Hola, 
La actualización del reporte epi de hoy miércoles 2 de noviembre fue con problemas. Hubo productos como el 15 que no se actualizaron. Y otros, como el 16, se agregó al final un dato del 14 de octubre. 

Saludos y gracias

**Comment by ctroncoso** [comment]
No se cargó ni el informe del 1 ni del 2, y todos sus productos asociados.  Usualmente es pq minsal no lo subió al ftp privado.

**Comment by MinCiencia** [comment]
Hola @weichafan,

Hemos actualizado los productos obtenidos desde el Informe-EPI.

Saludos
