### ISSUE TITLE
Reporte diario 30 de Nov no cargó ni fue procesado. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1438]
Buenos días. 
Ayer 30, el proceso de reporte diario falló en su intento de las 12 y 14 hs. No se actualizaron las tablas `input`.

**Comment by MinCiencia** [comment]
Hola @ctroncoso , gracias por reportar.

Estamos revisando el proceso.

Saludos

**Comment by MinCiencia** [comment]
Hola @ctroncoso, hemos solicitado al minsal la corrección en el reporte del 30 de noviembre.

Saludos

**Comment by ctroncoso** [comment]
Gracias. Ojo que tampoco llegó el de hoy 1. 
![image](https://user-images.githubusercontent.com/121016/205135289-ecb8c9d8-6a48-42dd-a0fe-ac89fe8fdc1d.png)

**Comment by MinCiencia** [comment]
Hola @ctroncoso,

Los reportes de los días siguientes seguirán fallando, hasta que no tengamos corrección del reporte del 30 de noviembre.

Saludios

**Comment by ctroncoso** [comment]
Comprendo y correcto. Cada reporte depende del anterior y se deben procesar en forma incremental. Esperemos que salga todo bien. Gracias por todo el trabajo!

**Comment by MinCiencia** [comment]
Hola @ctroncoso , se esta procesando los informes pendientes.

Desde el 30 de noviembre hubo un cambio en una de las tablas informadas por minsal.

Saludos

**Comment by MinCiencia** [comment]
Hola @ctroncoso , se encuentra normalizado el proceso.

Saludos

**Comment by ctroncoso** [comment]
Excelente! Gracias! Que tengan una excelente semana!
