### ISSUE TITLE
Actualización Producto 58

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1439]
Estimados,

Agradeciendo de antemano su apoyo quisiera consultar la posibilidad de actualizar los datos del producto 58 (Disponibilidad de camas críticas), actualmente está disponible la información hasta el 22 de Noviembre del 2022.

Saludos,

**Comment by MinCiencia** [comment]
hola @sebawsky , estamos revisando la situación y confirmando con minsal.

Saludos

**Comment by MinCiencia** [comment]
Hola @sebawsky , hemos solicitado a minsal la actualización de información con los datos respectivos.

Saludos
