### ISSUE TITLE
Reporte diario sin actualización hace 3 días. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1441]
Sé que no es su responsabilidad el asegurarse que les llegue la información, pero recomendaría poner en el proceso del informe diario, un chequeo para revisar que minsal haya hecho llegar el informe a tiempo. Se comprende que no llegue a las 12:25, pero 3 días ya es mucho y los reclamos llegan a minciencia. 
En lo que podamos ayudar, favor nos lo indican. Esto es el comienzo del proyecto de datos abiertos y no puede degradarse.

**Comment by MinCiencia** [comment]
Hola @ctroncoso , gracias por reportarnos la situación.

Se ha solicitado que minsal suba el informe correspondiente al 07-12-2022, se necesita de este informe para poder avanzar en los siguientes (08/12 y 09/12) que ya fueron subidos.

Estamos a la espera de su respuesta.

Saludos

**Comment by ctroncoso** [comment]
Se comprende. 
Es una lástima que el minciencia tenga que dar la cara por fallas de gestión de minciencia. Gracias por permanecer y persistir en este proyecto.

**Comment by MinCiencia** [comment]
Estimados, 

Desde minsal subieron el archivo faltante (07/12) y por ende, se han procesado todos los reportes que faltaban.

Saludos

**Comment by ctroncoso** [comment]
Espectacular! Gracias!
