### ISSUE TITLE
Actualización Productos 7, 13, 19, 49, 58

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1442]
Estimados,

Esperando se encuentren bien quisiera consultar respecto a la actualización de algunos productos 7, 13, 19, 49 y 58 (principalmente estos pero entiendo que hay otros que se encuentran en la misma situación). Los datos se encuentran actualmente actualizados hasta 6/12/2022, cuándo tienen considerado actualizar los días pendiente (7 y 8 de diciembre)?

Gracias de antemano y quedo atento !

**Comment by MinCiencia** [comment]
Hola @sebawsky , gracias por reportarnos.

Se encuentra relacionado al issue [https://github.com/MinCiencia/Datos-COVID19/issues/1441]

_"Se ha solicitado que minsal suba el informe correspondiente al 07-12-2022, se necesita de este informe para poder avanzar en los siguientes (08/12 y 09/12) que ya fueron subidos.

Estamos a la espera de su respuesta."_

Saludos

**Comment by MinCiencia** [comment]
Estimados,

Desde minsal subieron el archivo faltante (07/12) y por ende, se han procesado todos los reportes que faltaban.

Saludos
