### ISSUE TITLE
Informe diario 14/12/2022 no fue cargado en el repositorio. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1443]
Sabemos que es historia repetida y no es responsabilidad de Minciencia, pero hay que dejar registro.

**Comment by MinCiencia** [comment]
hola @ctroncoso , gracias por reportar.

Tal cual, no ha sido subido a nuestro sftp el reporte del 14/12. Hemos informado a minsal para que lo suban.

Saludos

**Comment by ctroncoso** [comment]
De esperarse... y por supuesto, a esperar. La lata es que los obliga a correr el action manualmente, que debe ser aún mas lata. 
Gracias!

**Comment by MinCiencia** [comment]
Estimados,

Respecto al reporte diario, minsal no ha cargado a nuestro ftp los reportes del 14 y 15 de diciembre. 

Esto ya se encuentra informado a minsal para que actualicen la información.

Saludos

**Comment by ctroncoso** [comment]
Iremos mejorando. Gracias por el esfuerzo y tolerancia.

**Comment by MinCiencia** [comment]
Hola @ctroncoso , se ha actualizado la información.

Saludos!

**Comment by ctroncoso** [comment]
Excelente! Gracias!
