### ISSUE TITLE
Actualización Productos 7, 13, 19, 49, 58 y otros

### ISSUE THREAD

**Issue by sebawsky** [MinCiencia/Datos-COVID19#1444]
Estimados,

Esperando se encuentren bien quisiera consultar respecto a la actualización de algunos productos 7, 13, 19, 49 y 58 (principalmente estos pero entiendo que hay otros que se encuentran en la misma situación). Los datos se encuentran actualmente actualizados hasta 13/12/2022, cuándo tienen considerado actualizar los días pendiente (14 y 15 de diciembre)?

En particular los datos del producto 58 (Disponibilidad de camas críticas), actualmente está disponible la información hasta el 29 de Noviembre del 2022. Si es posible gestionar la actualización de estos datos.

Gracias de antemano y quedo atento !

**Comment by MinCiencia** [comment]
Hola gracias por reportar.

Este problema esta relacionado con retraso por parte del minsal en la actualización de los datos en nuestro repositorio FTP.
Se encuentran informados de la situación y esperamos que suban pronto la información.

Saludos

**Comment by MinCiencia** [comment]
Hola @sebawsky , los reportes faltantes han sido subidos al repositorio.

De esta forma ha sido actulizada la información en los distintos productos.

Saludos!
