### ISSUE TITLE
Archivo para proceso UC llegó vacío.  - Falla "Actualiza_productos_de_UC"

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#1445]
El siguiente archivo cargó sin contenido. 0B y causó falla en action "Actualiza_productos_de_UC"
https://github.com/MinCiencia/Datos-COVID19/blob/master/input/UC/incidencia_edad_regionales.csv

**Comment by MinCiencia** [comment]
Hola @ctroncoso , gracias por reportarnos.

Esta situación fue informada a minsal y esperamos que carguen el archivo correctamente.

Saludos

**Comment by MinCiencia** [comment]
Proceso se ha ejecutado correctamente tras la entrega de archivos desde minsal.
