### ISSUE TITLE
[INFO] Problema reporte diario 30-12-2022

### ISSUE THREAD

**Issue by MinCiencia** [MinCiencia/Datos-COVID19#1446]
Hola a tod@s, 

Se está revisando problema con reporte diario del 30 de diciembre, una vez se solucione podremos subir los datos de los días siguientes y que se encuentran pendientes.

Saludos

**Comment by ctroncoso** [comment]
20!?!

**Comment by MinCiencia** [comment]
Estimados, ayer fueron actualizados los datos que se encontraban pendientes.

**Comment by ctroncoso** [comment]
Excelente! Muchas gracias!
