### ISSUE TITLE
Agregar producto 4 en formato serie de tiempo

### ISSUE THREAD

**Issue by bastianolea** [MinCiencia/Datos-COVID19#145]

**Comment by scornejob** [comment]
@bastianolea, puedes desarrollar tu peticion?
Tengo la impresion de que [el producto 11](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto11) es lo que necesitas.

**Comment by scornejob** [comment]
Frente a la falta de realimentacion, cierro este issue.
