### ISSUE TITLE
Error Producto37 Fallecidos

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#1456]
Hola,

Al revisar hoy el producto37 Fallecidos confirmados U071, con respecto a la versión anterior, serie del 28-marzo-2023 (registros al 25-marzo-2023) tiene una diferencia de -630 fallecidos, de 52.735 a 52.105 fallecidos, dato: las diferencias están durante el año 2020.

Saludos.

**Comment by ctroncoso** [comment]
Producto10 también muestra esa caída en número de fallecidos 
![image](https://user-images.githubusercontent.com/121016/228622789-75d5e271-c065-4ec3-8dae-acf3f08c4a75.png)
![image](https://user-images.githubusercontent.com/121016/228622963-786b96eb-ff3e-4813-91c9-3cc0654f1f76.png)

**Comment by dafernandez75** [comment]
Hola,
Habrá alguna respuesta por la diferencia de los Fallecidos U071?, agrego otra consulta para el caso de los Fallecidos U072, la diferencia a la fecha es -2.883 (registro anterior año 2020 = 5.374, registros ajustados oficiales año 2020 =2.491).

Saludos

**Comment by jorgepacheco84** [comment]
Hola a todos/as:

Lo identificado no es un error. 

El día 27 de marzo se publicó, en conjunto con Instituto Nacional de Estadísticas, las cifras oficiales para el año 2020 (https://www.ine.gob.cl/sala-de-prensa/prensa/general/noticia/2023/03/27/en-2020-el-covid-19-caus%C3%B3-el-14-8-de-los-fallecimientos-y-disminuy%C3%B3-la-esperanza-de-vida).

Durante el proceso de validación de las defunciones se reclasificaron 3.538 casos que fueron reportados de manera provisional como COVID-19 para el año 2020, pasando de 22.218 casos de defunciones por COVID-19 ese año a 18.680 reportados en la base oficial de 2020. Esto se explica en el apartado 4 del documento "Impactos del COVID-19 en la mortalidad de Chile durante el año 2020". Adjunto enlace: https://www.ine.gob.cl/docs/default-source/demografia-y-migracion/publicaciones-y-anuarios/mortalidad/impactos-del-covid-19-en-la-mortalidad-de-chile-durante-2020.pdf?sfvrsn=c664eb78_4

Si están interesados en identificar las variaciones en la causa básica de defunción* entre la base preliminar y oficial pueden revisar el anexo 1. 

En la página del DEIS puede acceder a la base de datos actualizada y a los tableros con la información oficial para el año 2020.

Saludos cordiales.

* La causa básica de defunción corresponde a "la enfermedad o lesión que inició la cadena de acontecimientos patológicos que condujeron directamente a la muerte o a las circunstancias del accidente o violencia que produjo la lesión fatal". Para identificarla se aplican las reglas de codificación y modificación propuestas en el volumen 2 de la Clasificación Internacional de Enfermedades (CIE).

**Comment by ctroncoso** [comment]
Gracias @jorgepacheco84,
Así pude ver al descargar los datos. Han habido varios cambios en el criterio de codificación a medida que se ha conocido más al virus. A mi me solía llegar el `Instructivo 7` del minsal  (esta es la versión 7.1 del instructivo)
![image](https://user-images.githubusercontent.com/121016/231309379-bf3c3293-99c5-4b35-8dab-9cd139607ccb.png)
con las reglas de codificación actualizadas para los egresos (tanto vivos, no mejorados y exitus letalis) y mas de una vez se recodificaron casos en forma retroactiva al cambiar la normativa.  Tengo entendido que ese instructivo no es público (aunque no hay razón para que no lo sea), pero si lo pudieses obtener para tu análisis, sería interesante ya que explica como ha cambiado el criterio a lo largo de la pandemia. 
Saludos y gracias por los links y la explicación!
