### ISSUE TITLE
Producto 5: Perdida de datos día 2020-05-04	

### ISSUE THREAD

**Issue by patricionicolas** [MinCiencia/Datos-COVID19#146]
Todos los archivos del producto 5 presentan el problema de no indicar datos el día 2020-05-04.	

TotalesNacionales.csv:
![image](https://user-images.githubusercontent.com/17221394/81095308-d4a3c380-8ed2-11ea-90f8-293fd8113fee.png)

TotalesNacionales_T.csv:
![image](https://user-images.githubusercontent.com/17221394/81095374-eab18400-8ed2-11ea-8b1f-016401d9a084.png)

TotalesNacionales_std.csv:
![image](https://user-images.githubusercontent.com/17221394/81095424-fb61fa00-8ed2-11ea-9d31-d2f13f3af1dd.png)

**Comment by scornejob** [comment]
Por error elimine ese dia en mi commit:

commit 0f83ca6bbb2f1c137c3654672e82fca5d7944fc8

arreglado en el branch issue146
