### ISSUE TITLE
algunos archivos están mal estructurados

### ISSUE THREAD

**Issue by lufke** [MinCiencia/Datos-COVID19#15]
Hay algunas tablas en las que faltan columnas en el encabezado, haciendo que no se puedan leer en forma correcta

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-04-10-CasosConfirmados-totalRegional.csv
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-04-09-CasosConfirmados-totalRegional.csv

Posiblemente, cambiaron el formato de la tabla desde donde están leyendo los datos.

Favor revisar

**Comment by scornejob** [comment]
@lufke efectivamente parece que hubo un cambio en las tablas (pusieron "," para decimales)
Puedes confirmar que estan ok?

**Comment by klaimmore** [comment]
Sugiero ignorar columna "% Casos totales" del scrapping. Es un dato secundario derivado del totalRegion y totalPais. Ademas esta aproximado y al parecer no es muy confiable (el del dia 10/4 tiene un error de espaciado entre los numeros para atacama)

**Comment by lufke** [comment]
> 
> 
> @lufke efectivamente parece que hubo un cambio en las tablas (pusieron "," para decimales)
> Puedes confirmar que estan ok?

está reparado
