### ISSUE TITLE
Datos del reporte diario no actualizados

### ISSUE THREAD

**Issue by javierlopeza** [MinCiencia/Datos-COVID19#152]
El commit 8b4758cf4009503d280c43bbb7fa924466e6807f agregaba los datos del reporte diario del 6 de mayo, pero erróneamente repitió los datos del 5 de mayo.

Debe ser porque a las 12pm todavía no se actualizaba la tabla en la página del MINSAL y el workflow no revisa si son datos nuevos o no.

**Comment by scornejob** [comment]
Gracias @javierlopeza . 

efectivamente, los datos estan repetidos, pero no todos:

```
2020-05-05,7,27,51,8,6,31,1179,5,9,2,12,21,0,1,0,14,1317
2020-05-06,7,27,51,8,6,31,1179,5,9,2,12,21,0,1,0,14,1373
```

corregiremos los productos cuando se actulice la pagina del MINSAL. En el intertanto, eliminaremos los datos repetidos

**Comment by javierlopeza** [comment]
Perfecto. Recién la actualizaron, para que recorran el workflow.
