### ISSUE TITLE
Producto 5: TotalesNacionales.csv

### ISSUE THREAD

**Issue by patricionicolas** [MinCiencia/Datos-COVID19#153]
No fueron actualizados los datos. Tambien pareciera que hay una fila con un dato menos porque perdiò el formato.

![image](https://user-images.githubusercontent.com/17221394/81204824-d08da980-8f97-11ea-9f63-1ed99a11980f.png)

**Comment by scornejob** [comment]
Me parece que ese no es el commit correcto:

https://github.com/MinCiencia/Datos-COVID19/commit/7c0f05f4b904c68c1875c9c5401dd95e608d791c
