### ISSUE TITLE
Sugerencia datos de comunas en cuarentena

### ISSUE THREAD

**Issue by InformaticaFPY** [MinCiencia/Datos-COVID19#156]
Estimados, 
Para un mejor análisis, sugiero disponibilizar datos de comunas que se encuentran en cuarentena respectivo nombre, region, fecha de inicio, fin y estado (cuarentena finalizada, vigente y nuevas/futuras). Esto le permitirá a los trabajadores y empresas a tomar mejores decisiones respecto del confinamiento, ventas de productos, etc..

**Comment by Leandermen** [comment]
@InformaticaFPY Actualmente los datos de Cuarentenas están siendo entregados al repositorio en formato GeoJson en [Carpeta Cuarentenas](../tree/master/input/Cuarentenas). De hecho sobre ello se derivan archivos CSV con los datos en [DP29](../tree/master/output/producto29)

**Comment by InformaticaFPY** [comment]
Gracias por la aclaración. Lo único malo que la información se encuentra des-actualizada. Aparecen comunas que están actualmente en cuarentena en estado **[3] Futura** (Ejemplo: Quilicura) y no aparecen las futuras comunas que entraran en cuarentena (ejemplo: La Florida).
Saludos!

**Comment by Leandermen** [comment]
Respecto a eso, anoche se hizo el pull request con la ultima actualización. Debería estar actualizado ahora

**Comment by damorend** [comment]
Por si a alguien le sirve, acá dejé un registro histórico de las cuarentenas por comuna: https://docs.google.com/spreadsheets/d/1IjirW9zoW5H-x8AnQcQaKXZXiS1tCuTs0PxSkNxYE0g/edit?usp=sharing

No es una BBDD oficial sino que una recopilación desde distintas fuentes. Por favor dejen un comentario si tienen correcciones u observaciones.

**Comment by wgomg** [comment]
Aprovecho este issue para preguntar, ¿alguien conoce los criterios específicos para declarar cuarentenas? Lo único que he encontrado es esto: 

- Velocidad de Propagación de la Enfermedad
- Densidad de casos por km2
- Perfil etáreo de la población del territorio (adultos mayores y personas con enfermedades crónicas)
- Vulnerabilidad Social

Pero no he pillado algo más preciso.

**Comment by Leandermen** [comment]
Respecto a los criterios, MINSAL los ha ido cambiando (de hecho planeo corregirlo en la proxima actualización de cuarentenas). Actualmente segun los ultimos reportes se ha definido como criterios:
- Casos Activos
- Aumento en la incidencia de casos activos (vale decir activos por cada 100.000 habitantes)
- Activos por km2 (densidad)
- Capacidad asistencial de la red COVID-19 (estadisticas de redes asistenciales).

En nuestro equipo hemos ido calculando estas variaciones con los informes EPI de este repo por lo menos para 3 de las 4 variables (nos falta la de capacidad asistencial) [Situación por Comunas](https://covid19.soporta.cl/datasets/af921e75ed2940a5b71febdd5aa4744a_0?geometry=-78.207%2C-35.284%2C-63.386%2C-32.085&showData=true)
