### ISSUE TITLE
cambio de - por null

### ISSUE THREAD

**Issue by fzmolina** [MinCiencia/Datos-COVID19#161]
Estimado, quisiera por favor solicitar cambiar los campos con '-' por null en los productos:

DP 7 y DP 21.

También quisiera solicitar una revisión de los DP6: en el archivo csv las líneas 1092, 3500, 3962 tienen '-' en las columnas 2 y 10 (considerando la primera columna como 1). La línea 4846 tiene null en la primera columna y '-' en las columnas 2 y 10. Además, el formato de fecha es diferente al de los demás productos

DP11: el formato de fecha es diferente a los demás productos
DP12: Hereda los '-' del DP7, además el formato de fecha es diferente

Muchas gracias

**Comment by scornejob** [comment]
producto 7 y 21 listos
Producto 6 es una contribucion. Voy a revisar y poner lo que encuentre aca.

**Comment by scornejob** [comment]
producto 11 y 12tambien corresponden a una contribucion.

**Comment by fzmolina** [comment]
Muchas gracias scornejob!
