### ISSUE TITLE
Fuente de reporte diario

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#168]
Hola! Veo que los productos del reporte diario del dia de hoy han sido actualizados en este repositorio, pero en el sitio de gob.cl el reporte de hoy aún no existe.

Cuál es la fuente de los datos de hoy?

**Comment by MinCiencia** [comment]
Es el reporte diario https://www.gob.cl/coronavirus/cifrasoficiales/#reportes

**Comment by ivanMSC** [comment]
@MinCiencia Me explico mejor:

El reporte diario apareció en el servidor de gob.cl a las 12:51 mientras que en este repo, los productos asociados se actualizaron a las 12:25. Esto es incluso antes de que la Subsecretaria diera el reporte en TV (inicio de transmisión a las 12:31)

Si tienen el acceso al reporte diario de primera mano, sugeriría generar los productos 3, 4, 5, 13, 14, 26 y 27 en base a ese reporte, en lugar de usar webscraper.

**Comment by MinCiencia** [comment]
Nos llega cuando hace el _release_ el Ministerio de Salud de Chile, nos vamos a fijar si es que gob.cl vamos a considerar tu sugerencia, si es que detectamos que nos llega antes que la actualización.

**Comment by ivanMSC** [comment]
Gracias por la aclaración! 👍
