### ISSUE TITLE
producto 11 - sin actualizacion

### ISSUE THREAD

**Issue by jpvillanuevac** [MinCiencia/Datos-COVID19#169]
Hola,

estoy leyendo el producto 11 directo desde raw y parece que dejo de actualizarse.

Se volvera a actualizar?

gracias

**Comment by scornejob** [comment]
hola @jpvillanuevac . 
El problema del producto 11 es que no hemos podido automatizarlo usando github actions.

Lo acabamos de actualizar a mano.

**Comment by jpvillanuevac** [comment]
Ah ok! gracias scornejob por la aclaracion.

saludos!
