### ISSUE TITLE
duplicidad de archivos para araucania 22 y 23 de marzo

### ISSUE THREAD

**Issue by hsepulvedac** [MinCiencia/Datos-COVID19#17]
los archivos del 22 y 23 de marzo son los mismos, al revisar todos la suma total acumulada da 709, cifras entregadas hoy para la araucanía son de 712
2020-03-22-CasosConfirmados-totalRegional.csv
2020-03-23-CasosConfirmados-totalRegional.csv

**Comment by scornejob** [comment]
@hsepulvedac , los archivos fueron regenerados. Puedes confirmar?
