### ISSUE TITLE
Dato de pacientes críticos faltante para fecha específica

### ISSUE THREAD

**Issue by nachomr7** [MinCiencia/Datos-COVID19#172]
El dato de pacientes críticos para el 1 de abril no está en las series disponibles

**Comment by fzmolina** [comment]
Hola nachomr7. Ese es un dato que no está desde el origen. En los reportes diarios del Ministerio de Salud se encuentra un gráfico sobre la hospitalización diaria en unidades de cuidados intensivos y pacientes críticos (por ejemplo: pag. 8 en el reporte diario de hoy 13 de mayo). En ese gráfico se puede apreciar el dato faltante con fecha 31-03-2020, que corresponde a la fecha de corte (21 hrs de cada día). En este repositorio se utiliza la fecha de publicación (la fecha posterior al día de corte), por eso se ve reflejado el 1 de abril.
