### ISSUE TITLE
Sugerencia datos históricos de Nº de pacientes conectados a ventilación mecánica invasiva diaria

### ISSUE THREAD

**Issue by nachomr7** [MinCiencia/Datos-COVID19#173]
Actualmente existen datos de ventiladores ocupados (hasta hoy en 1275) pero como conversan éstos con los que se muestran en el informe diario que van en 470 hasta hoy?

**Comment by MinCiencia** [comment]
Hola @nachomr7, ¿de dónde viene esa cifra "470"?

**Comment by nachomr7** [comment]
<img width="624" alt="may10" src="https://user-images.githubusercontent.com/46497914/81518293-9d3a7a00-930b-11ea-9543-3119eaab41be.png">

**Comment by Leandermen** [comment]
del informe diario 
![image](https://user-images.githubusercontent.com/6208975/81518354-c65b0a80-930b-11ea-95cb-eaaae5ac062b.png)

**Comment by MinCiencia** [comment]
Muchas gracias por la aclaración, tomamos la sugerencia y añadimos el [data product 30](output/producto30). 

Para responder bien ahora a tu pregunta: el resumen que indica @Leandermen corresponde a pacientes covid19 usando VMI, mientras el de ventiladores ocupados corresponde a pacientes con diversos diagnósticos usando VMI, por eso el último es mayor [data product 20](output/producto20).

**Comment by wgomg** [comment]
¿Hay alguna estadística de VMI utilizados hasta la fecha en años anteriores para comparar con este año?

**Comment by worldofvitox** [comment]
hola, estos son los valores para los días antecedentes, es decir desde el 28 de marzo


47
75
82
108
142
168
190
225
252
270
286
316
317
318
