### ISSUE TITLE
Estandarizar nombres de campos

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#176]
Independientemente de las filas o columnas, hay campois llamados fechas y Fechas. Se debe estandarizar.

**Comment by fzmolina** [comment]
Pienso que se puede estandarizar por la letra inicial mayúscula: Fecha en vez de fecha

**Comment by MinCiencia** [comment]
Debería este ticket ser cerrado, o aún está pendiente?

**Comment by scornejob** [comment]
Sigue en https://github.com/MinCiencia/Datos-COVID19/issues/246
