### ISSUE TITLE
Datos diarios

### ISSUE THREAD

**Issue by edinsonvergarabustos** [MinCiencia/Datos-COVID19#178]
Favor entregar la serie completa día a día como corresponde. Esta serie no sirve. Gracias

**Comment by MinCiencia** [comment]
Hola, ¿a qué te refieres @edinsonvergarabustos?

**Comment by edinsonvergarabustos** [comment]
Hola, se necesitan los datos diarios por comuna (1,2,3,4,5,6,7....31) y no (1,3,6,8,10...)

**Comment by MinCiencia** [comment]
Hay datos desagregados a nivel comunal se publican cuando la autoridad sanitaria los hace públicos, desde el 8 de abril, esto ocurre 2 veces a la semana (lunes y viernes), antes del 8 de abril ocurría 3 veces a la semana: lunes, miércoles y viernes.

Hay datos a nivel nacional y regional que se publican diariamente.

De todas maneras, en http://www.minciencia.gob.cl/comunidad_covid19 puedes revisar una serie de desarrollos a partir de estos datos.

**Comment by edinsonvergarabustos** [comment]
Perdone usted pero me interesan series diarias comunales, el resto que me señala lo sé y no obedece a mi problema. Por favor le ruego escalar mi solicitud a una instancia superior para que se ajuste está serie por cuánto los días que omiten comunalmente igualmente generaron nuevos casos a nivel región y es necesario contar con esos datos faltantes para que sean trabajados científicamente, de lo contrario no tienen sentido, considerando además, que se trata del Ministerio de ciencia. Gracias

**Comment by MinCiencia** [comment]
Estamos trabajando para disponer datos con mayor desagregación temporal ¿Nos puedes indicar qué tipo de análisis estas desarrollando?

**Comment by edinsonvergarabustos** [comment]
Gracias. Urge tener esos datos en series diarias. Actualmente en modelos econométricos ARIMA que requieren de series temporales definidas, en la serie comunal actual por ejemplo, no sería problema si los datos presentados fuesen siempre cada dos días, pero el problema es que hay algunos cada tres, cada cuatro, diarios, entonces no sirven. También trabajando en modelos econométricos multivariados con variables dummy y con variables proxy, modelos que han funcionado bien con datos nacionales, pero ahora urge trabajar con datos comunales.

**Comment by javierlopeza** [comment]
> Hay datos desagregados a nivel comunal y se publican cuando la autoridad sanitaria los hace públicos, desde el 8 de abril, esto ocurre 2 veces a la semana (lunes y viernes), antes del 8 de abril ocurría 3 veces a la semana: lunes, miércoles y viernes.
> 
> Hay datos a nivel nacional y regional que se publican diariamente.
> 
> De todas maneras, en http://www.minciencia.gob.cl/comunidad_covid19 puedes revisar una serie de desarrollos a partir de estos datos.

¿Qué pasa con los datos de esta semana? Se supone que se publicaban ayer (lunes) y nada aún.

**Comment by edinsonvergarabustos** [comment]
Ahora más que nunca se necesita la serie diaria de contagios comunales. No sé si continuar solicitándola por acá o utilizar otros medios. Favor solucionar por acá. Gracias

**Comment by fzmolina** [comment]
Estimado edinsonvergarabustos, en input/InformeEpidemiologico/ puedes encontrar los archivos históricos de las fecha de inicio de síntomas según las semanas epidemiológicas publicado en el Informe Epidemiológico del Ministerio de Salud del país

**Comment by MinCiencia** [comment]
Entiendo que lo que solicita @edinsonvergarabustos son series de tiempo diarias, cuestión que la autoridad sanitaria no está publicando a nivel comunal, pero si a nivel regional y nacional.

**Comment by edinsonvergarabustos** [comment]
Comprendo. Muchas gracias por sus respuestas. Saludos

**Comment by MinCiencia** [comment]
Hoy agregamos dos nuevas series diarias por comuna: nacimientos y defunciones inscritos en el registro civil, totales por comuna.

[Data Product 31](https://github.com/Data-Observatory/MinCiencia-Datos-COVID19/tree/nacimientos_defunciones/output/producto31) - Nacimientos en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Nacimientos inscritos en el Registro Civil de Chile, desde el 2010 a la fecha, actualizados diariamente.

[Data Product 32](https://github.com/Data-Observatory/MinCiencia-Datos-COVID19/tree/nacimientos_defunciones/output/producto32) - Defunciones en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Defunciones inscritas en el Registro Civil de Chile, desde el 2010 a la fecha, actualizadas diariamente.

**Comment by edinsonvergarabustos** [comment]
Espectacular, gracias. Es posible indicar las defunciones que sean por covid?

**Comment by MinCiencia** [comment]
Claro, en cuanto el DEIS termine de procesar la información del registro civil, esos se harán públicos también.

**Comment by edinsonvergarabustos** [comment]
Que genial. Gracias!

**Comment by MinCiencia** [comment]
Hola @edinsonvergarabustos, DEIS también ha hecho públicos sus registros:

https://public.tableau.com/profile/deis4231#!/vizhome/HechosVitalesdesdeel2000/NotaTcnica?publish=yes

**Comment by edinsonvergarabustos** [comment]
Gracias por la info. Iré a bucear por esos lares.
