### ISSUE TITLE
MEJORAS BASE COVID-19

### ISSUE THREAD

**Issue by miguelcarvajala** [MinCiencia/Datos-COVID19#18]
1.- Los datos de días 22   y 23 de marzo están duplicados.
2.- Datos del 31 de marzo en columna regiones   tiene un orden diferente a los demás reportes (casi alfabético).
3.- La fecha   otorgada a cada reporte corresponde al registro del día anterior (es   conveniente poner nota).

Atte.,
MAC
--

**Comment by scornejob** [comment]
@miguelcarvajala :
1.- Estamos buscando las fuentes para confirmar los datos.
2.- lo solucionamos en https://github.com/MinCiencia/Datos-COVID19/issues/21
3.- Agregamos la nota en la descripcion del producto.

Mantengamos este ticket hasta resolver (1)

**Comment by rodguzman** [comment]
Los datasets tienen distintas estructuras dependiendo del día:

-Datasets del 03/03 al 03/21 estructura: REGION, C. NUEVOS, C. TOTALES, C. RECUPERADOS 
-Datasets del 22/03 al 25/03 estructura: REGION, C. NUEVOS, C. TOTALES, FALLECIDOS
-Datasets del 26/03 al 04/04 estructura: REGION, C. NUEVOS, C. TOTALES, C. RECUPERADOS, FALLECIDOS
-Datasets del 05/04 al 14/04 estructura: REGION, C. NUEVOS, C. TOTALES, % C. TOTALES, FALLECIDOS

**Comment by rickynet** [comment]
han cambiado las estructuras por que se ha pedido mas informacion,hoy lo explico la sub secretaria de minsal
