### ISSUE TITLE
Estan repetidos los datos del dia 13 Mayo

### ISSUE THREAD

**Issue by Orlando-GIS** [MinCiencia/Datos-COVID19#185]
Se repitieron los mismos datos del 12 de Mayo

**Comment by paarriagadap** [comment]
Sí, al menos los productos 3, 5 y 14, que cuentan casos y fallecidos

**Comment by elaval** [comment]
![image](https://user-images.githubusercontent.com/68602/81843589-caf60d80-951b-11ea-8ece-f26245896045.png)

**Comment by MinCiencia** [comment]
Corrigiendo, muchas gracias por reportar. Avisamos por acá cuando esté ok.

**Comment by MinCiencia** [comment]
Actualizado.
