### ISSUE TITLE
CasosNuevosCumulativo_std.csv mal generado

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#187]
Hola, este archivo, correspondiente al producto 13 está mal generado, debido a que muestra casos acumulados y no casos nuevos, como es el caso de los otros dos archivos, CasosNuevosCumulativo.csv y CasosNuevosCumulativo_T.csv https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto13

**Comment by fzmolina** [comment]
Hola paarriagadap,

Gracias por tu reporte. El problema ha sido resuelto.

**Comment by paarriagadap** [comment]
Gracias!
