### ISSUE TITLE
Acceso a estos reportes institucionalizados

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#19]
Me he dado cuenta que estos últimos días varias regiones reportan los casos con este formato. Parece ser un formato institucionalizado y me pregunto si se encuentran disponibles de forma centralizada en algún sitio del gobierno. Alguien sabe donde están los de todas las regiones?

![93045107_148929636634235_508875567840362496_o](https://user-images.githubusercontent.com/35350256/79031172-ff685980-7b6a-11ea-9371-70174bc7a41c.jpg)
![93052296_1329646443901390_3684791028948140032_n](https://user-images.githubusercontent.com/35350256/79031173-00998680-7b6b-11ea-84d5-9882a157ea61.jpg)
![92632462_669329956973569_5758586593065566208_o](https://user-images.githubusercontent.com/35350256/79031175-00998680-7b6b-11ea-968d-85e165fb53ff.jpg)

**Comment by dna33** [comment]
Finalmente hemos estabilizado el flujo de la información en las siguientes etapas:

servicios de salud, seremis, autoridad central, gobierno, publico.

No quiere decir que sea la forma optima, pero es la que ha permitido mantener consistencia.
