### ISSUE TITLE
Urgente: graves inconsistencias en casos por fecha por inicio de síntomas, por comuna

### ISSUE THREAD

**Issue by gomena** [MinCiencia/Datos-COVID19#190]
Estimados, he estado mirando atentamente el producto 15 y he observado inconsistencias en los últimos días

1)El nuevo FechaPorInicioDeSintomasHistorico.csv es inconstitente con el historial de ediciones de FechasPorInicioDeSintomas.csv. Según he podido comprobar, el historial de éste último sí coincide con los pdf de los informes epidemiológicos. Sin embargo, FechaPorInicioDeSintomasHistorico.csv es inconsistente. Ver por ejemplo Puente Alto el día 2020-05-01. Se observan 90 casos en la SE17 y ninguno en la SE18 y SE19. En el pdf correspondiente (https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/Informe_EPI_01_05_2020.pdf) hay 164 casos en la SE17 y 34 en la SE18. Estos últimos númers son conistente con el primer commit del 2 de mayo (https://github.com/MinCiencia/Datos-COVID19/blob/c65c19f490624ab8d41a22540c939d9d6e85f59d/output/producto15/FechaInicioSintomas.csv), pero no así con el segundo 

Una posible explicación es que a veces aparecen dos ediciones del csv en el mismo día, y sólo la primera coincide con el pdf. 

Ruego explicar qué están haciendo realmente. Me parece preocupante porque también he visto el nuevo detalle en https://github.com/MinCiencia/Datos-COVID19/tree/master/input/InformeEpidemiologico

Los datos por fecha de inicio de síntomas mencionados ahí, nuevamente, no coinciden con los valores de los pdf.

Gonzalo

**Comment by gomena** [comment]
Según he podido ver más atentamente parece ser un problema con las fechas asociadas a cada informe en el histórico; ruego revisar este asunto

**Comment by fzmolina** [comment]
Muchas gracias gomena, estamos revisando el error. Los archivos del último informe epidemiológico ya fueron corregidos. Estamos trabajando en los históricos. Muchas gracias por tu reporte

**Comment by gomena** [comment]
gracias!!
De lo que he podido ver:

En el histórico que tienen las fechas 13-04-2020 y 15-04-2020 parecen ambos  coincidir con el pdf del informe del 15-04-2020 (sin embargo, en los pdf el 13-04-2020 contiene información distinta, por lo que vale la pena incluirla). El del 18-04-2020 parece estar OK con el informe en pdf. Lo mismo con el 04-05-2020 y 08-05-2020. Entre medio no he podido verificar aún.

Los datos del último informe (11-05-2020) aún no están disponible. Podrían agregarlos por favor antes de que se colapsen con el informe que debería aparecer mañana?

**Comment by fzmolina** [comment]
Hola,

Acabo de verificar, el archivo del 13 fue agregado, algunos entre medio hubo confusión de versiones. Los tengo en otro branch (prod15Historical en el input/InformeEpidemiologico), debo arreglar un par de cosas antes de llevarlos al output del master.

Los datos del último informe están en FechaInicioSintomas.csv, FechaInicioSintomas_T.csv y FechaInicioSintomas_std.csv. El histórico es el que falta arreglar.

**Comment by gomena** [comment]
buenísimo muchas gracias!!

**Comment by fzmolina** [comment]
Arreglado!

**Comment by fzmolina** [comment]
Hola gomena,

Gracias por tu reporte. Verifiqué y parece que está todo ok ahora. Sobre la fecha, justo me percaté también de ese desfase de un día. La arreglaremos.

**Comment by fzmolina** [comment]
listo Gomena, ya están correctas las fechas.

**Comment by gomena** [comment]
muchas gracias! estoy de acuerdo que está arreglado :)
