### ISSUE TITLE
Tasa Positiva Región Mayor a 100%

### ISSUE THREAD

**Issue by worldofvitox** [MinCiencia/Datos-COVID19#191]
hola, ayer algunas regiones dieron tasa PCR mayor a 100% por ejemplo, 

DP7 PCR por Región 13 de Mayo Region Tarapacá
AL3 = 6

DP13 Nuevos contagiados por Región 13 de Mayo Region Tarapacá, 
BU3 = 37

es por algun trasvasije entre regiones?

**Comment by MinCiencia** [comment]
Hola, así es. Las muestras a veces se envían fuera de las regiones, en base a la capacidad de testeo en el momento.
