### ISSUE TITLE
Producto20: Informaciòn distinta a informada por MINSAL.

### ISSUE THREAD

**Issue by patricionicolas** [MinCiencia/Datos-COVID19#198]
En el twitter oficial del Ministerio de salud informan mayor cantidad de ventiladores totales que las mostradas en el producto 19.

Twitter Minsal:
![image](https://user-images.githubusercontent.com/17221394/82069984-1c300980-96a2-11ea-8cd5-49a42b38aa09.png)

Archivo producto 19:
![image](https://user-images.githubusercontent.com/17221394/82070204-67e2b300-96a2-11ea-906a-2959032b9930.png)

Sin embargo la cantidad de ventiladores disponibles si concuerdan.
![image](https://user-images.githubusercontent.com/17221394/82070361-9f515f80-96a2-11ea-9efd-602b5acda772.png)

¿Por que ocurre esto?

**Comment by MinCiencia** [comment]
Hola @patricionicolas, nosotros obtenemos la cifra desde el reporte diario publicado en https://www.gob.cl/coronavirus/cifrasoficiales/#reportes
