### ISSUE TITLE
Data de fallecidos a la fecha este año y años anteriores.

### ISSUE THREAD

**Issue by wgomg** [MinCiencia/Datos-COVID19#201]
Hice la pregunta acá hace un par de días https://github.com/MinCiencia/Datos-COVID19/issues/173#issuecomment-628270214 pero nadie pescó, y a la vista que que se armó cierto revuelo a causa de ello entre ayer y hoy, ¿será posible que se entregue este repositorio la información de fallecidos por causas respiratorias y causas asociadas a cuadros respiratorios de este año y años anteriores?

**Comment by MinCiencia** [comment]
Disculpa por no contestar, @wgomg. Solo vimos la versión inicial de tu comentario en la notificación, no la edición que hiciste posteriormente. Vamos a publicar nacimientos y defunciones inscritos en el registro civil, totales por comuna.

**Comment by MinCiencia** [comment]
[Data Product 31 ](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto31)- Nacimientos en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Nacimientos inscritos en el Registro Civil de Chile, desde el 2010 a la fecha, actualizados diariamente. 

[Data Product 32 ](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto32)- Defunciones en Chile: Set de 3 archivos en formato csv que dan cuenta del número de Defunciones inscritas en el Registro Civil de Chile, desde el 2010 a la fecha, actualizadas diariamente.

**Comment by wgomg** [comment]
@MinCiencia Muchas gracias, habrá alguna posibilidad de tener datos de la DISE también?

**Comment by MinCiencia** [comment]
¿DISE? Te refieres al departamento de estadística e información del MINSAL (DEIS)?

**Comment by wgomg** [comment]
Sí, eso mismo, DEIS, error de tipeo antes jaja

**Comment by MinCiencia** [comment]
Hola, DEIS del Ministerio de Salud de Chile logró hacer públicos sus datos también, en un formato que no es el mejor, pero si alguien los comienza a transcribir podría anunciarlo acá. 

Esto es lo que han publicado:

https://public.tableau.com/profile/deis4231#!/vizhome/HechosVitalesdesdeel2000/NotaTcnica?publish=yes

**Comment by wgomg** [comment]
¡Muchas gracias por el esfuerzo!

¿Será mucho pedir que también entreguen los fallecimientos por causa de muerte?

**Comment by MinCiencia** [comment]
Con la publicación diaria en el producto 37, y 32 podemos dar por cerrado este issue.
