### ISSUE TITLE
Datos 31 de marzo producto 3

### ISSUE THREAD

**Issue by LuisAcunaSM** [MinCiencia/Datos-COVID19#21]
Hola, los felicito por ir haciendo más transparentes la información pero... es obvio que en el día 31 de marzo el _producto 3_ se produjo error de digitación de los datos que se hace más evidente al graficarlos, posiblemente una translocación en la planilla.

```git
commit 9a67381f3f57b59acbf17cf6f9b3d09da9beaf03 (HEAD -> master, origin/master, origin/devel, 
origin/HEAD)
Author: Seba Cornejo <sebastian.cornejo@gmail.com>
Date:   Sat Apr 11 19:24:41 2020 -0400

    prod 3
```

**Comment by scornejob** [comment]
Gracias @LuisAcunaSM 

Efectivamente, hubo una permutación en los datos, pero ya estan corregidos. Puedes confirmar?

**Comment by LuisAcunaSM** [comment]
¡Confirmado, @scornejob :ok_hand: !
