### ISSUE TITLE
Informacion desagregada para PCR

### ISSUE THREAD

**Issue by faesepulveda** [MinCiencia/Datos-COVID19#210]
Hola gracias a todos por sus esfuerzos en armar este repositorio !

es posible conseguir información desagregada para los test pcr? esto es, cantidad de test  en hombres, cantidad de test en mujeres, cantidad de test por genero etario? revise todo los data products y los inputs y no encontré la información. cualquier ayuda es bienvenida. 

Muchas gracias !

**Comment by MinCiencia** [comment]
Hola @faesepulveda esa información aún no es dispuesta de manera pública. ¿Por qué la buscas? Siempre nos sirve conocer eso mejor, para ir avanzando en abrir más datos, si es que es posible.
