### ISSUE TITLE
Hospitalizados por región

### ISSUE THREAD

**Issue by faesepulveda** [MinCiencia/Datos-COVID19#211]
Existe algún csv o alguna fuente donde conseguir la información de hospitalizaciones por región? revise el repositorio como los informes epidemiologicos y el reporte diario y no logro dar con esta información que debería existir.. es importante para los análisis !

gracias de antemano

**Comment by MinCiencia** [comment]
Hola @faesepulveda no existe a nivel del Ministerio de Salud, hay otros usuarios que consumen reportes de cifras desde SEREMI directamente, quizás @ivanMSC tiene alguna respuesta satisfactoria a tu duda.

**Comment by ivanMSC** [comment]
@faesepulveda Las SEREMI (excepto la RM) entregan detallados informes día a día a través de sus canales oficiales. En ellos puedes encontrar lo que buscas.

Por ejemplo, para la región de Valparaíso: https://seremi5.redsalud.gob.cl/21670-2/

Si no encuentras la información en las web oficiales, prueba buscando Seremi, intendencias o gores en twitter y facebook.
