### ISSUE TITLE
de donde obtienen los datos demograficos?

### ISSUE THREAD

**Issue by faesepulveda** [MinCiencia/Datos-COVID19#215]
estaba revisando y los datos demográficos presentados por región no se corresponden a los disponibles en el ultimo censo? alguien podría clarificar esto? gracias!

**Comment by Paula69-mat** [comment]
No lo he revisado pero deben corresponder a las Proyecciones de Población del año 2020 que realiza el INE en base al CENSO 2017

**Comment by MinCiencia** [comment]
Hola @faesepulveda y @Paula69-mat. Efectivamente, pueden encontrarlas en el siguiente link:

https://www.ine.cl/estadisticas/sociales/demografia-y-vitales/proyecciones-de-poblacion
