### ISSUE TITLE
examenes totales disminuyen un día en Prod17

### ISSUE THREAD

**Issue by saangel** [MinCiencia/Datos-COVID19#219]
Hola, estoy leyendo datos desde el producto 17 y hay sólo un día en el que el total de exámenes realizados disminuye. ¿De dónde surge ese error? ¿Se puede corregir?

Gracias,

![image](https://user-images.githubusercontent.com/12454348/82358586-b78fea00-99d4-11ea-9237-5ccbfaecf9af.png)

**Comment by fzmolina** [comment]
Hola saangel,

Está corregido. Se trató de un typo. Muchas gracias por tu reporte.
