### ISSUE TITLE
casos a nivel comunal (contagiados/fallecidos) desagregados por quinquenio y sexo

### ISSUE THREAD

**Issue by matiashheinrich** [MinCiencia/Datos-COVID19#220]
Es posible tener datos a nivel comunal de contagios y fallecidos desagregados por quinquenio y sexo?

**Comment by JLorenzoBermejo** [comment]
En la misma línea de la pregunta de Matías: sería posible obtener datos de contagios y fallecidos a nivel regional y comunal por sexo y grupo etario?

**Comment by MinCiencia** [comment]
Gracias, vamos a considerar estas sugerencias. Estamos trabajando constantemente por generar más data products. Saludos.
