### ISSUE TITLE
SUGERENCIA: nuevo producto con fallecidos totales en 2020 (adicional a producto32)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#223]
En producto 32 se publican las defunciones diarias desde 2010, y es actualizado diariamente (este es un archivo de casi 17MB)

Sin embargo, los datos históricos (2010 a 2019) son estables y sólo se necesitan descargar 1 vez para generar parámetros de comparación.

Los datos de 2020 (actualizados diariamente) se requieren descargar con regularidad.

**Sugiero publicar un archivo separado con las defunciones inscritas en 2020** para minimizar el volumen de descarga diaria que es requerido para un análisis de fallecidos totales.

![image](https://user-images.githubusercontent.com/68602/82475711-e40e3980-9a9a-11ea-84a5-293a357ddcdf.png)

![image](https://user-images.githubusercontent.com/68602/82475813-0f912400-9a9b-11ea-8e04-26059010bb87.png)

**Comment by scornejob** [comment]
hola @elaval 
Podrias desarrollar el caso de uso?
Pregunto por que me imagino que clonas el repo, y despues solamente haces pull para bajar los deltas, y en ese escenario, los 17 megas se bajarian solo al primera vez. O consumes el raw directamente?

**Comment by scornejob** [comment]
Hola @elaval 

El cambio esta implementado en https://github.com/MinCiencia/Datos-COVID19/tree/issue223.
Sin embargo, pienso que deberiamos aclarar el caso de uso antes de hacer/aceptar el PR.

**Comment by elaval** [comment]
Te doy más antecedente:

El análisis de Excess Mortality requiere comparar los fallecidos semanales durante 2020 con un valor estimado para los fallecidos el 2020 (sin pandemia).  Esta estimación se hace con los datos históricos (específicamente 2015-2019).

Una vez que tenemos la "linea de base" establecida, lo que necesitamos es actualizar los datos día a día para el 2020.

Yo hago esto en una página web:
https://observablehq.com/@elaval/mortalidad-en-exceso-durante-epidemia-de-coronavirus-en-ch

En esta página (y en otras que he desarrollado) descargo los datos actualizados en línea desde el feed raw de github (ejemplo https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto32/Defunciones_std.csv).

Los datos son descargados directamente al navegador del usuario (y no necesito clonar ni hacer un pull del repositorio).  Por lo tanto, cada vez que un usuario se conecta a la página, se decarga el total de los datos.

Esto no es mayor problema cuando estamos analizando datos del desarrollo de la pandemia (número de casos, fallecidos, hospitalizados), pero se torna un volumen relevante cuando estamos descargando datos históricos diarios x comuna desde 2010

**Comment by MinCiencia** [comment]
Gracias por la explicación @elaval, super bien. Mientras terminamos de analizar una petición: super interesante el análisis que están haciendo, ¿pueden poner en la página que obtienen los datos de este repositorio, con un link también, por favor?

**Comment by scornejob** [comment]
Entiendo. Dado que consumes el raw, hago el pr
