### ISSUE TITLE
DP5 y DP22 sin decimales?

### ISSUE THREAD

**Issue by worldofvitox** [MinCiencia/Datos-COVID19#227]
hola, gracias por ayudarme con issue anterior

podrían cambiar el output de DP5 para que no tenga el ".0" después de cada valor entero? quizás me estoy adelantando a algo pero no veo como podría ser util para alguien ya que estamos hablando de casos que nunca van a ser fraccionales.

gracias!

**Comment by MinCiencia** [comment]
Hola, no podemos. Tiene que ver con cómo tratamos los números y consistencia con el resto de los productos. ¿Por qué te genera problemas a ti con algún código? Quizás podemos ayudar a manejarlo.

**Comment by worldofvitox** [comment]
hola, entendido, no hay problema, se arregla. la pregunta era porque solo esos productos vienen con decimal.
