### ISSUE TITLE
Discrepancias en # de fallecidos con datos de registro civil

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#228]
Hola, hasta ahora estaba usando datos de fallecidos descargados del registro civil (Descarga Excel de https://estadisticas.sed.srcei.cl/defcom) pero en el futuro quisiera usar los datos publicados en el repositorio de MinCiencia

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto32/2020-Defunciones_std.csv

Hoy descargué los datos de ambas fuentes y muestran algunas discrepancias cuando agrego el total para el país. Son diferencias menores, pero hacen dudar de la consistencia absoluta de los datos.  Por ejemplo, para Enero 2020
![image](https://user-images.githubusercontent.com/68602/82613535-7e51a880-9b93-11ea-808c-7fa22ef7677a.png)

¿Cuál será la razón de la discrepancia? ¿Cuál considerar como válida?

Gracias

**Comment by MinCiencia** [comment]
Hola hemos actualizado nuestro código para que realice actualizaciones una vez por hora y mantener consistencia con el registro civil. La razón, como indica el registro civil y el deis es que los números para el periodo 2017-2020 se encuentran en etapa de validación y recolección respectivamente, por lo que pueden cambiar a medida que avanza el proceso.
