### ISSUE TITLE
Inconsistecia entre confirmados diarios y acumulados por region

### ISSUE THREAD

**Issue by ricgaldame** [MinCiencia/Datos-COVID19#229]
El 03-03-2020 existe una diferencia entre el acumulado y el diario. El primer día deberían ser idénticos y no lo son. Por favor revisar y mejorar

**Comment by fzmolina** [comment]
Hola ricgaldame,

El primer día de la serie de tiempo es el 2020-03-03. Según el informe de Situación COVID-19 entregado por el departamento de epidemiología del Ministerio de Salud, con fecha 10 de marzo 2020 página 3, dice textualmente: "El primer caso confirmado se notificó el 2 de marzo de 2020". Es decir, el caso acumulado al 3 de marzo proviene del día 2 de ese mes. Por ello, no es un caso nuevo del 3 de marzo.
