### ISSUE TITLE
Inconsistencia en tabla de casos nuevos diarios

### ISSUE THREAD

**Issue by ricgaldame** [MinCiencia/Datos-COVID19#230]
Esta es la tabla:
https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto13/CasosNuevosCumulativo.csv

Para la fecha 05-05-2020 el Total debe ser 1373 no 1317

**Comment by fzmolina** [comment]
Hola ricgaldame,

Se trató de un error de origen, ya se ha corregido. Muchas gracias por el reporte
