### ISSUE TITLE
Agregar Causa Inmediata de Muerte, para que sean comparables con los datos de DEIS https://deis.minsal.cl/

### ISSUE THREAD

**Issue by guillermoburr** [MinCiencia/Datos-COVID19#236]
Agregar la causa inmediata de muerte de acuerdo a las “NORMAS PARA EL REGISTRO DE LA CAUSA DE MUERTE EN EL CERTIFICADO MÉDICO DE DEFUNCIÓN” del Ministerio de Salud. Esto con el fin de hacer comparable la serie de tiempo con la que se encuentra en https://deis.minsal.cl/

**Comment by MinCiencia** [comment]
Hola @guillermoburr, hemos hecho el esfuerzo de publicar los datos entre 2017-2020 a pesar de que aún se encuentran en proceso de validación y recolección respectivamente, en coordinación con el registro civil.  El DEIS a su vez ha hecho lo propio. Sin embargo, como indican en su página, no es posible para ellos aún hacer públicos esos datos:

<img width="1199" alt="Screen Shot 2020-05-23 at 4 51 53 PM" src="https://user-images.githubusercontent.com/63315154/82740355-08c21580-9d16-11ea-84c8-471f36f711a1.png">
