### ISSUE TITLE
Inconsistencia: Recuperados Región Metropolitana > Recuperados Chile

### ISSUE THREAD

**Issue by javierlopeza** [MinCiencia/Datos-COVID19#238]
## Datos Informe EPI 22/05

El [último Informe EPI](https://www.minsal.cl/wp-content/uploads/2020/05/Informe_EPI_22_05_2020.pdf) indica, a esa fecha, que en la **Región Metropolitana** hay 48.266 casos confirmados y 16.979 casos activos (pág. 33).
![image](https://user-images.githubusercontent.com/11431769/82734650-558ff700-9cea-11ea-906d-3876466077fe.png)

El mismo informe reporta 48.350 casos confirmados y 423 fallecidos en la **Región Metropolitana** (pág. 9):
![image](https://user-images.githubusercontent.com/11431769/82734791-33e33f80-9ceb-11ea-860f-f0ecd0866a9e.png)

### Problema Nº1

Los casos confirmados son inconsistentes, 48.266 ≠ 48.350. ¿A qué se debe esta diferencia?

### Problema Nº2

Haciendo el cálculo de recuperados:
**Recuperados = Confirmados - Activos - Fallecidos**
se obtiene que los recuperados de la Región Metropolitana son:
48.350 - 16.979 - 423 = 30.948 recuperados.

La inconsistencia está en que los recuperados **a nivel nacional**, según el reporte diario de hoy 23 de mayo, son 26.546, es decir, 4.402 menos recuperados que la Región Metropolitana.

En resumen, la Región Metropolitana tiene 30.948 recuperados y Chile 26.546. ¿Cómo se explica esto?

https://www.gob.cl/coronavirus/cifrasoficiales/
![image](https://user-images.githubusercontent.com/11431769/82735049-d4862f00-9cec-11ea-925b-aec2bb6c4fe7.png)

**Comment by sibieta** [comment]
Revisando, creo que el problema de inconsistencia que se ve es debido a la característica del informe epidemiologico, donde los datos que reporta contemplan el calendario epidemiologico por semanas y tambien excluye datos no confirmados de residencia por comunas.

**Comment by fzmolina** [comment]
Hola javierlopeza,

Sobre la pregunta 1: 1. Tal como dice @sibieta, el informe epidemiologico no incluye los casos sin residencia conocida. Estos son 6 para la RM (ver producto 28). 2. no todos los confirmados por exámen PCR están ingresados al sistema de EPIVIGILA. Para el país el porcentaje es de 99.9% de los confirmados por PCR.

Sobre la pregunta 2: El número de recuperados que consideran en el Reporte Diario usa la fecha de notificación del examen PCR, proyectando recuperación en 14 días. Por otro lado, como también apunta @sibieta, el informe EPI incluye el resultado de la investigación de cada uno de los casos, que reportan la fecha de inicio de sus síntomas (FIS). Esta ultima es a su vez considerada en dicho informe para proyectar el período en que una persona esta activa.

**Comment by javierlopeza** [comment]
Excelente, gracias por la aclaración. Sería bueno explicar las razones del uso de 2 metodologías distintas para calcular la misma cifra.

**Comment by MinCiencia** [comment]
Gracias por la sugerencia. La razón tiene que ver con la gestión de la autoridad Sanitaria, el reporte diario tiene información al día, mientras que el informe EPI va actualizándose a medida que avanza la investigación epidemiológica, se hace un esfuerzo tremendo por mantener todas las cifras alineadas. Nota que las cifras no se llaman igual. Las del informe EPI tienen la frase "por fecha de inicio de síntomas", escritas en todo el reporte y también en este repositorio.
