### ISSUE TITLE
Base de datos anonimizada para proyectos de investigación  

### ISSUE THREAD

**Issue by JLorenzoBermejo** [MinCiencia/Datos-COVID19#239]
Estimadas y estimados, 

Sería valiosísimo para la comunidad científica contar con una base de datos anonimizada de todos los pacientes diagnosticados con COVID-19 en Chile - una fila por paciente, en las columnas las variables que no permitan la re-identificación de las personas en la base de datos: sexo, edad al diagnóstico en quinquenios, region, comuna (agrupar si permite identificación), fecha de diagnóstico (agrupar en semanas si permite identificación), recuperación, fecha recuperación, fallecimiento, fecha fallecimiento, hospitalización básica/media/UCI/UTI, fecha inicio hospitalización básica/media/UCI/UTI, fecha término hospitalización, ventilación mecánica, fecha inicio ventilación mecánica, fecha término ventilación mecánica. 
Esta base de datos permitiría generar información muy útil para el sistema de salud chileno. 
Muchas gracias de antemano y a su disposición si puedo apoyar en algo,
Justo

**Comment by dna33** [comment]
Hola @JLorenzoBermejo, muchas gracias por su sugerencia. El conjunto de datos que usted alude es muy completo y no tengo dudas que se puede agregar valor con él. Hoy se toman decisiones con datos de esa naturaleza (entre otros) y permiten tomar decisiones a la autoridad sanitaria, pero no se hacen públicos, según se ha explicado para no poner en riesgo la privacidad de los pacientes (ver prensa al respecto). Esto no quiere decir que no se harán nunca públicos, hemos estado trabajando en la dirección de mayor publicación de datos y continuaremos haciéndolo, en conjunto con el Ministerio de Salud de Chile. Algunas preguntas: 1) ¿qué otros países hacen abiertos (públicos) conjuntos de datos con esa cantidad de información sobre COVID19? Nosotros hemos revisado los reportes de la fundación independiente Ciudadanía Inteligente, entre otras fuentes y hasta ahora no hemos encontrado un país que haga público un conjunto de datos así de amplio. Ayuda saber de otros ejemplos 2) Usted tiene ejemplos concretos del análisis que quisiera hacer con dicha base de datos? Ayuda saber sus opiniones sobre oportunidades y valor que se generaría por hacerlo.

**Comment by JLorenzoBermejo** [comment]
Hola Demián, 

Sería beneficioso para Chile que los investigadores tengamos acceso a este tipo de datos cuanto antes – siempre asegurando la privacidad de los pacientes mediante un nivel adecuado de agregación y/o firmando un compromiso de confidencialidad si fuese necesario.  
En Alemania la información está disponible en https://npgeo-corona-npgeo-de.hub.arcgis.com/, desconozco la política de datos en otros países y su relevancia para Chile.

A mí me interesaría sobre todo investigar las desigualdades regionales, en línea con esta publicación https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1006756.

Me avisan por favor si puedo de alguna manera contribuir para avanzar en esta dirección!

**Comment by dna33** [comment]
Hola, muchas gracias por la elaboración. Sin embargo, no veo en la página de Alemania donde se disponen los datos con el nivel de individualización y todas las características que defines de manera abierta. Mi alemán es limitado en todo caso, pero me ayudaría si me envías el link directo a aquello. 

En caso de que no tengas datos a nivel individual como estas sugiriendo en este issue, ¿qué datos agregados a nivel regional y comunal te servirían para estudiar dichas desigualdades?

**Comment by JLorenzoBermejo** [comment]
Hola Demián, 

Este enlace contiene los datos individuales de 141.507 pacientes: https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0/data

La estructura que propongo para la base de datos individuales respeta la privacidad – basta con agrupar categorías de las variables, por ejemplo juntar comunas o utilizar semanas en vez de días para las fechas. 

Una alternativa mas sencilla, pero con menos información, serían los datos agregados a nivel regional y comunal, pero estratificados por sexo, edad al diagnóstico en quinquenios, fecha/semana de diagnóstico, fecha/semana de recuperación, fecha/semana de fallecimiento, fecha/semana de hospitalización básica/media/UCI/UTI, fecha/semana de término hospitalización, fecha/semana de inicio y término de la ventilación mecánica.

Mas sencillos todavía pero con menos información, serían los datos agregados a nivel regional y comunal, estratificados por sexo, edad al diagnóstico en quinquenios, fecha/semana de diagnóstico, recuperación (si/no), fallecimiento (si/no), hospitalización básica/media/UCI/UTI (si/no), ventilación mecánica (si/no).

Muchas gracias de antemano!

**Comment by dna33** [comment]
Buenas sugerencias, muchas gracias.

Respecto del link de Alemania, de nuevo mi alemán es pobre, ¿me puedes ayudar a ver qué columnas incluye a nivel individual?

**Comment by JLorenzoBermejo** [comment]
Muchas gracias Demián, 

Ya revisé las series temporales, para los análisis que intento hacer solo faltaría el sexo y el grupo etario en las series temporales de (1) casos confirmados y de complicaciones tras el contagio: (2) hospitalización básica/media/UCI/UTI, (3) ventilación mecánica y (3) fallecimientos. 

Las columnas en la tabla son Codigo_region, Region, Codigo_comuna, Comuna, Grupo etario, Sexo, Caso_confirmado, Fallecimiento, Fecha_notificiacion,...
Algunas filas agrupan a varios pacientes: la tabla tiene 141.507 filas, pero en Alemania llevamos hasta ahora 178.281 casos confirmados.

Sería excelente contar con estos datos y poder investigar posibles desigualdades regionales!

**Comment by kotelocl** [comment]
Para llegar a un poco más de granularidad sin ser invasivo, sería bueno aperturar el **Producto 1** (Casos totales por comuna incremental) a sexo y rango etario.

Tomemos como ejemplo el primer registro del archivo **Covid-19_std.csv**, para Arica el 30-03-2020 con 6 casos confirmados. Suponiendo una apertura por sexo y edad, podría quedar así.

Region | Codigo region | Comuna | Codigo comuna | Poblacion | Fecha | Rango Etario | Sexo | Casos Confirmados
-- | -- | -- | -- | -- | -- | -- | -- | --
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | <= 39 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | <= 39 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 40-49 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 40-49 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 50-59 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 50-59 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 60-69 | H | 2
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 60-69 | M | 3
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 70-79 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 70-79 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 80-89 | H | 1
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 80-89 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | >=90 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | >=90 | M | 0

Lo importante es tener la apertura por edad y sexo, lo demás se puede manejar por "debajo" en las distintas herramientas que utilicemos para realizar los análisis.

**Comment by JLorenzoBermejo** [comment]
Estimad@s, eso sería excelente!

Sería posible aperturar además:
- el Producto 14 (Fallecidos con COVID-19 por región<https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto14>) a sexo y rango etario, y
- el Producto 24 (Hospitalización de pacientes COVID-19 en sistema integrado<https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto24>) a región, sexo y rango etario?

Poder contar además con los Productos 14 y 24 por comuna en vez de por región (juntando todas las comunas de Santiago si no es conveniente liberar ahora esta información) sería también muy útil para poder investigar diferencias regionales con alguna granularidad.


Von: kotelo [mailto:notifications@github.com]
Gesendet: Dienstag, 26. Mai 2020 20:29
An: MinCiencia/Datos-COVID19
Cc: Lorenzo Bermejo, apl.Prof. Justo; Mention
Betreff: Re: [MinCiencia/Datos-COVID19] Base de datos anonimizada para proyectos de investigación (#239)


Para llegar a un poco más de granularidad sin ser invasivo, sería bueno aperturar el Producto 1 (Casos totales por comuna incremental) a sexo y rango etario.

Tomemos como ejemplo el primer registro del archivo Covid-19_std.csv, para Arica el 30-03-2020 con 6 casos confirmados. Suponiendo una apertura por sexo y edad, podría quedar así.
Region

Codigo region

Comuna

Codigo comuna

Poblacion

Fecha

Rango Etario

Sexo

Casos Confirmados

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

<= 39

H

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

<= 39

M

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

40-49

H

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

40-49

M

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

50-59

H

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

50-59

M

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

60-69

H

2

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

60-69

M

3

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

70-79

H

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

70-79

M

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

80-89

H

1

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

80-89

M

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

>=90

H

0

Arica y Parinacota

15

Arica

15101

247552

2020-03-30

>=90

M

0


Lo importante es tener la apertura por edad y sexo, lo demás se puede manejar por "debajo" en las distintas herramientas que utilicemos para realizar los análisis.

**Comment by gustavodv** [comment]
> Estimadas y estimados, 
> 
> Sería valiosísimo para la comunidad científica contar con una base de datos anonimizada de todos los pacientes diagnosticados con COVID-19 en Chile - una fila por paciente, en las columnas las variables que no permitan la re-identificación de las personas en la base de datos: sexo, edad al diagnóstico en quinquenios, region, comuna (agrupar si permite identificación), fecha de diagnóstico (agrupar en semanas si permite identificación), recuperación, fecha recuperación, fallecimiento, fecha fallecimiento, hospitalización básica/media/UCI/UTI, fecha inicio hospitalización básica/media/UCI/UTI, fecha término hospitalización, ventilación mecánica, fecha inicio ventilación mecánica, fecha término ventilación mecánica. 
> Esta base de datos permitiría generar información muy útil para el sistema de salud chileno. 
> Muchas gracias de antemano y a su disposición si puedo apoyar en algo,
> Justo  

Estimados, comparto misma inquietud.
Con 39años de edad me vacuné el 01.04.21 por tener un IMC sobre 30, ante esto me nace la pregunta: si el 30% de la población chilena tiene sobrepeso/obesidad, ¿Cuántos chilen@s  se hubiesen salvado si la campaña hubiese sido enfocada a este grupo de personas desde un primer minuto?", Quiero responderme esa pregunta con Data Analyst con Python, me intriga saber correlación IMC alto vs camas ocupadas/muertes.

**Comment by ctroncoso** [comment]
> Hola @JLorenzoBermejo, muchas gracias por su sugerencia. El conjunto de datos que usted alude es muy completo y no tengo dudas que se puede agregar valor con él. Hoy se toman decisiones con datos de esa naturaleza (entre otros) y permiten tomar decisiones a la autoridad sanitaria, pero no se hacen públicos, según se ha explicado para no poner en riesgo la privacidad de los pacientes (ver prensa al respecto). Esto no quiere decir que no se harán nunca públicos, hemos estado trabajando en la dirección de mayor publicación de datos y continuaremos haciéndolo (desde el principio publicando información diariamente en relación al espectro temporal, avanzando en el espectro geográfico al nivel comunal desde abril) en conjunto con el Ministerio de Salud de Chile (ver [informe mesa de datos](http://www.minciencia.gob.cl/sites/default/files/informe_1_submesa_datos_covid19_200507.pdf)). Algunas preguntas: 1) ¿qué otros países hacen abiertos (públicos) conjuntos de datos con esa cantidad de información sobre COVID19? Nosotros hemos revisado los reportes de la fundación independiente Ciudadanía Inteligente, entre otras fuentes y hasta ahora no hemos encontrado un país que haga público un conjunto de datos así de amplio. Ayuda saber de otros ejemplos 2) Usted tiene ejemplos concretos del análisis que quisiera hacer con dicha base de datos? Ayuda saber sus opiniones sobre oportunidades y valor que se generaría por hacerlo.

De hecho, toda esa información se codifica y entrega al DEIS en todos los hospitales de Chile en forma regular. Incluso hospitales privados para casos convenio (incluidos COVID). En este están hasta 30 diagnósticos, hasta 30 procedimientos, fecha de ingreso, egreso y traslados con fechas entre unidades. 
De hecho, el deis entrega esa información, pero solo deja la columna del primer diagnóstico. en Datos Abiertos de fallecidos, aun cundo la información está para todo paciente que sea dado de alta, ya sea vivo o fallecido. 
Lo que se debe consultar es por la CODIFICACIÓN GRD de egresos hospitalarios.
