### ISSUE TITLE
Incoherencias en datos a nivel regional

### ISSUE THREAD

**Issue by correa-araneda** [MinCiencia/Datos-COVID19#24]
He revisado los datos reportados a escala regional diario. He detectado diferencias en casos nuevos en relación al total acumulado. Esto es mas evidente en los datos de la región de Arica y Parinacota. Adjunto datos erróneos marcados en amarillo.

[casos nacionales de covid19.xlsx](https://github.com/MinCiencia/Datos-COVID19/files/4466627/casos.nacionales.de.covid19.xlsx)

**Comment by dna33** [comment]
Me aprece han sido corregidos.
