### ISSUE TITLE
Producto 30 sin actualización el 23/05

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#241]
Hola, los archivos correspondientes al producto 30 (Pacientes en Ventilación Mecánica Intensiva) se saltan el dato correspondiente al 23 de mayo (900)

**Comment by fzmolina** [comment]
Hola parriagadap,

Puedes compartir por favor la fuente de ese dato?

**Comment by paarriagadap** [comment]
Hola, te refieres a los 900? Lo vi en el tablero diario de https://www.gob.cl/coronavirus/cifrasoficiales/, pero parece que no se incluye en el infome.

**Comment by fzmolina** [comment]
En efecto, no se incluye en el informe de ese día.

**Comment by paarriagadap** [comment]
No encuentro una captura del tablero en redes sociales, pero sí este tuit: https://twitter.com/ColMedSantiago/status/1264203389124186113
![image](https://user-images.githubusercontent.com/63430031/82831398-f19e3780-9e7d-11ea-8b83-0372aedc7851.png)

**Comment by paarriagadap** [comment]
https://twitter.com/ministeriosalud/status/1264203026308321287 
![image](https://user-images.githubusercontent.com/63430031/82831557-578abf00-9e7e-11ea-82f1-3c5f249239b0.png)

**Comment by fzmolina** [comment]
Arreglado. Muchas gracias por el feedback!
