### ISSUE TITLE
En la base de datos de cuarentena Total para Puerto Williams tiene Errores

### ISSUE THREAD

**Issue by derek-corcoran-barrios** [MinCiencia/Datos-COVID19#244]
En la base de datos de [Cuarentena total ](https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto29/Cuarentenas-Totales.csv) para puerto williams, el inicio de la cuarentena es una fecha posterior a la de término la cuarentena debiera iniciarse el día 22 de marzo, lo que probocó el error

Gracias

**Comment by MinCiencia** [comment]
Hola, @Leandermen, muchas gracias por tu ayuda con esto.

**Comment by E-Mendez** [comment]
Hola, 
La resolución de la cuarentena en Puerto Williams fue publicada en el diario oficial el día 28 de Marzo
" 7. Dispóngase cuarentena a la ciudad de Puerto Williams, perteneciente a la comuna de
Cabo de Hornos. "(p.3 del PDF, link abajo)

Saludos!
https://www.diariooficial.interior.gob.cl/publicaciones/2020/03/28/42617/01/1746621.pdf

**Comment by Leandermen** [comment]
Se corregirá en el próximo pull request
