### ISSUE TITLE
Datos de confirmados totales por comuna incremental por comuna (DP1) erroneos

### ISSUE THREAD

**Issue by jdonas** [MinCiencia/Datos-COVID19#248]
Hola,

El DP1 parece tener errores o no ser incremental. Por ejemplo si miro la serie en la comuna de Puerto Montt aparecen 73 casos confirmados al 27 de Abril, sin embargo al 1 de Mayo aparecen 52 casos confirmados. Si fueran casos totales por comuna incremental esto sería un error.
Agradezco mucho si me pueden aclarar o guiar donde puedo obtener la infromación correcta.

Saludos

**Comment by kotelocl** [comment]
No están erróneos.

Los casos se van actualizando a medida que van recabando más datos y confirmando información. Es algo que ocurre en muchas comunas. Al principio son datos provisiorios, y a medida que evoluciona el reporte debido a la investigación epidemiológica, se actualizan las cifras.

**Comment by MinCiencia** [comment]
Es tal como indica @kotelocl, muchas gracias.
