### ISSUE TITLE
Apertura de datos por Sexo y Rango Etario (Producto 1) - Solicitud a Minsal

### ISSUE THREAD

**Issue by kotelocl** [MinCiencia/Datos-COVID19#249]
Bastante simple, ¿hay alguna forma de qué el Ministerio de Ciencia pueda solicitar al Ministerio de Salud esta información para los contagios del Producto 1?

Para aumentar un poco la granularidad del dato sin ser invasivo, sería bueno aperturar el **Producto 1** (Casos totales por comuna incremental) a sexo y rango etario.

Tomemos como ejemplo el primer registro del archivo **Covid-19_std.csv**, para Arica el 30-03-2020 con 6 casos confirmados. Suponiendo una apertura por sexo y edad, podría quedar así.

Region | Codigo region | Comuna | Codigo comuna | Poblacion | Fecha | Rango Etario | Sexo | Casos Confirmados
-- | -- | -- | -- | -- | -- | -- | -- | --
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | <= 39 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | <= 39 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 40-49 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 40-49 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 50-59 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 50-59 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 60-69 | H | 2
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 60-69 | M | 3
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 70-79 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 70-79 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 80-89 | H | 1
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | 80-89 | M | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | >=90 | H | 0
Arica y Parinacota | 15 | Arica | 15101 | 247552 | 2020-03-30 | >=90 | M | 0

Lo importante es tener la apertura por edad y sexo. Lo mismo se podría aplicar para los fallecidos (**Producto 14**), y realizar una mezcla con el **Producto 10**.

**Comment by JLorenzoBermejo** [comment]
Estimad@s, eso sería excelente! 

Sería posible aperturar además:
- el Producto 14 (Fallecidos con COVID-19 por región) a sexo y rango etario, y 
- el Producto 24 (Hospitalización de pacientes COVID-19 en sistema integrado) a región, sexo y rango etario?

Poder contar además con los Productos 14 y 24 por comuna en vez de por región (juntando todas las comunas de Santiago si no es conveniente liberar ahora esta información) sería también muy útil para poder investigar diferencias regionales con alguna granularidad.

**Comment by dna33** [comment]
Se han hecho avances en esta dirección pueden revisar los nuevos productos aportados en colaboración entre los Ministerio de Salud y Ciencia y el grupo ICOVID? Quedo atento a sus comentarios.

**Comment by JLorenzoBermejo** [comment]
Estimado Demián,

Muchas gracias por la notificación!
Se abrieron los fallecimientos y hospitalizaciones de regiones/comunas por edad y sexo?
No logro encontrar esta información.
Muchas gracias de antemano y saludos!


Von: Demián Arancibia [mailto:notifications@github.com]
Gesendet: Freitag, 15. Januar 2021 16:02
An: MinCiencia/Datos-COVID19
Cc: Lorenzo Bermejo, apl.Prof. Justo; Comment
Betreff: Re: [MinCiencia/Datos-COVID19] Apertura de datos por Sexo y Rango Etario (Producto 1) - Solicitud a Minsal (#249)


Se han hecho avances en esta dirección pueden revisar los nuevos productos aportados en colaboración entre los Ministerio de Salud y Ciencia y el grupo ICOVID? Quedo atento a sus comentarios.

**Comment by MinCiencia** [comment]
Los fallecimientos si,

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto84

Hospitalizaciones con ese nivel de detalles no aun.
*______*
*Demián Arancibia*
Ministerio de Ciencia, Tecnología, Conocimiento e Innovación
Gobierno de Chile
