### ISSUE TITLE
producto3/CasosTotalesCumulativo.csv no tiene actualizado datos para 2020-04-12

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#25]
Si bien existe tabla para producto4/2020-04-12-CasosConfirmados-totalRegional.csv

![image](https://user-images.githubusercontent.com/68602/79127825-8aff0780-7d70-11ea-81a7-2ae2c33778c2.png)

En Datos-COVID19/output/producto3/CasosTotalesCumulativo.csv no se incluyen los datos para 2020-04-12

Supongo que hay un tema de sincronización en la actualización de las tablas

![image](https://user-images.githubusercontent.com/68602/79127713-630fa400-7d70-11ea-9943-e44fdbbb0654.png)

Saludos

**Comment by LuisAcunaSM** [comment]
Lo mismo ocurre con los datos de hoy. Se pueden obtener a partir de los ficheros diarios, es relevante que la planilla incremental esté actualizada para poder automatizar algunas tareas pregramables en base a los datos clonados, por favor.

**Comment by ivanMSC** [comment]
@LuisAcunaSM Si necesitas los datos por región con actualización instantánea, revisa mi repo https://github.com/ivanMSC/COVID19_Chile

Se actualiza automáticamente, apenas los datos son publicados.

**Comment by LuisAcunaSM** [comment]
¿Es tuyo `https://tiny.cc/covid19chile`? :astonished: 
Notable, @ivanMSC Y gracias por el dato :handshake:

**Comment by elaval** [comment]
> @LuisAcunaSM Si necesitas los datos por región con actualización instantánea, revisa mi repo https://github.com/ivanMSC/COVID19_Chile
> 
> Se actualiza automáticamente, apenas los datos son publicados.

Muchas gracias @ivanMSC   

Tu repositorio es muy útil (el formato y lo oportuna de la actualización)

@scornejob @MinCiencia : Creo que les sería útil tener una actualización de la serie de tiempo como lo hace @ivanMSC

**Comment by MinCiencia** [comment]
Hola @elaval estuvimos revisando qué pasó el domingo con la rutina automática para update de este producto, corre todos los días a medio día y actualiza la columna con el valor reportado por MINSAL, en el futuro no debería haber problemas. Gracias por reportar.
