### ISSUE TITLE
Datos duplicados de fallecidos diarios por comuna

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#252]
Acabo de notar que en esta tabla ahora están duplicados los registros de defunciones por comuna:
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto32/2020-Defunciones_std.csv

**Comment by paarriagadap** [comment]
Lo mismo iba a poner. Además, en los archivos que guardan desde 2010 a 2020 sólo 2020 aparece duplicado

**Comment by MinCiencia** [comment]
Gracias por reportar.

**Comment by scornejob** [comment]
Honestamente, no pude dar con el bug, ni replicar el problema, asi que desacople las etapas en https://github.com/MinCiencia/Datos-COVID19/tree/issue252
Veamos en los siguientes dias si se repite esto.

**Comment by paarriagadap** [comment]
Por lo menos hoy no están duplicados. Gracias.
