### ISSUE TITLE
Informe EPI numero 20, aun no?

### ISSUE THREAD

**Issue by Leandermen** [MinCiencia/Datos-COVID19#253]
Llama la atención que siguiendo con el calendario de publicación de cifras comunales aun no se publique el Informe Epidemiológico Número 20 que por fecha debería corresponder al 25 de mayo (que muestran el estado hasta el 24 de mayo).

Actualmente realizo análisis de evolución de tasas y valores en períodos de 14 días (Variación 14 días), y los períodos de publicación son claves para ese análisis:
- 4 de mayo con 20 de abril
- 8 de mayo con 24 de abril
- .... (y asi)
- 25 de mayo con 11 de mayo

Hay algún cambio que se espera en esta materia que sea conocido desde EPI MINSAL o hay alguna razón de retraso en la entrega del informe

**Comment by javierlopeza** [comment]
Para nosotros en [COVID-19 en tu comuna](https://covid19entucomuna.cl/) también es crucial la publicación oportuna de estos informes, de lo contrario la información publicada por comuna queda obsoleta.

**Comment by javierlopeza** [comment]
@Leandermen fue publicado hace algunos minutos.

**Comment by dna33** [comment]
Hola, hubo algunas iteraciones más de lo habitual, pero salió finalmente.
