### ISSUE TITLE
Falta caracter de cierre en archivo "SemanasEpidemiologicas.csv"

### ISSUE THREAD

**Issue by E-Mendez** [MinCiencia/Datos-COVID19#259]
R entrega la siguiente advertencia al abrir el archivo :

Warning message in read.table(file = file, header = header, sep = sep, quote = quote, :
“incomplete final line found by readTableHeader on 'https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto15/SemanasEpidemiologicas.csv'”

Solución:
The message indicates that the last line of the file doesn't end with an End Of Line (EOL) character (linefeed (\n) or carriage return+linefeed (\r\n)). The original intention of this message was to warn you that the file may be incomplete; most datafiles have an EOL character as the very last character in the file.
https://stackoverflow.com/questions/5990654/incomplete-final-line-warning-when-trying-to-read-a-csv-file-into-r

Saludos.

**Comment by scornejob** [comment]
Hola @E-Mendez .

Puedes hacer un PR con el fix, si gustas.
