### ISSUE TITLE
product7/Exámenes

### ISSUE THREAD

**Issue by alonsosilvaallende** [MinCiencia/Datos-COVID19#26]
Tengo una consulta: este es el número de exámenes realizados en el día o el número de exámenes con resultados reportados en el día?

**Comment by alonsosilvaallende** [comment]
Acá va un gist para mostrar que al parecer son los exámenes realizados ese día y anonimizados de alguna forma (muchos zeros): https://gist.github.com/alonsosilvaallende/e3c660b08625dc674edca1abf9ee21f2

**Comment by MinCiencia** [comment]
Este es el proceso como lo entendemos: Se toman muestras en los servicios de salud y se envían a laboratorios para ser testeados. Los laboratorios informan la cantidad de test hechos durante el día. Ocurre que en algunos lugares no hay capacidad de testeo, por ende se envían a otros lados e incluso fuera de la región, en aquellos casos se demoran más en confirmar o descartar.
