### ISSUE TITLE
Datos de defunciones 2020 duplicados

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#265]
Hola, nuevamente ocurrió que los datos de defunciones 2020 provenientes del Registro Civil están duplicados

**Comment by scornejob** [comment]
Hola @paarriagadap , 

estoy buscando las duplicaciones así:
```
$ cat output/producto32/2020-Defunciones_std.csv | sort | uniq -c | head
      1 Antofagasta,2,Antofagasta,2101,10,2020-01-02
      1 Antofagasta,2,Antofagasta,2101,10,2020-01-20
      1 Antofagasta,2,Antofagasta,2101,10,2020-01-23
      1 Antofagasta,2,Antofagasta,2101,10,2020-03-16
      1 Antofagasta,2,Antofagasta,2101,10,2020-03-31
      1 Antofagasta,2,Antofagasta,2101,10,2020-04-27
      1 Antofagasta,2,Antofagasta,2101,10,2020-04-30
      1 Antofagasta,2,Antofagasta,2101,11,2020-05-04
      1 Antofagasta,2,Antofagasta,2101,1,2020-01-05
      1 Antofagasta,2,Antofagasta,2101,1,2020-02-02
```

entonces, si busco todas las cuentas que no son unicas :
```
$ cat output/producto32/2020-Defunciones_std.csv | sort | uniq -c | egrep -v "     1"


```

no me muestra duplicaciones...

**Comment by paarriagadap** [comment]
Hola, tienes razón, ya no hay duplicados. Si es que sólo se generó una vez hoy debí haberme confundido y ejecuté una versión anterior, de cuando había fallado. Gracias.

**Comment by paarriagadap** [comment]
Hola, se duplicó de nuevo. Supongo que pasa cuando el algoritmo no encuentra datos nuevos y sólo copia de nuevo lo que hay.

**Comment by scornejob** [comment]
Hola @paarriagadap ,

Veo las duplicaciones y triplicaciones en el historico:
```
sebas at darkside in ~/repo/Datos-COVID19 (master)
$ cat output/producto32/Defunciones_std.csv | sort | uniq -c | grep  "      2" | wc -l
217

sebas at darkside in ~/repo/Datos-COVID19 (master)
$ cat output/producto32/Defunciones_std.csv | sort | uniq -c | grep  "      3" | wc -l
14552

```

**Comment by scornejob** [comment]
El error es mío: no eliminaba los duplicados despues de concatenar lo de la API.

**Comment by paarriagadap** [comment]
Bueno, muchas gracias!
