### ISSUE TITLE
Incorporar nuevos datos desde el informe diario

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#266]
Hola, podrían procesar la información nueva que se ha ido publicando en los informes diarios, como los pacientes UCI por tipo de ventilación: ![image](https://user-images.githubusercontent.com/63430031/83287525-743d3480-a1a7-11ea-840a-9998b86c9c6d.png)

O lo relativo a residencias sanitarias:
![image](https://user-images.githubusercontent.com/63430031/83288902-c54e2800-a1a9-11ea-945b-dbd483290852.png)
![image](https://user-images.githubusercontent.com/63430031/83288914-cd0dcc80-a1a9-11ea-9f06-dd909de31aff.png)

Gracias!

**Comment by fzmolina** [comment]
Hola @paarriagadap ,

Hemos actualizado el DP30 con los datos correspondientes a ventilación mecánica en pacientes UCI. También se agregó el DP36 con la información sobre las residencias sanitarias.

**Comment by paarriagadap** [comment]
Muchas gracias!
