### ISSUE TITLE
Información descuadrada en Producto 20

### ISSUE THREAD

**Issue by nachomr7** [MinCiencia/Datos-COVID19#273]
Para el 29 de mayo existen 2173 ventiladores ocupados y 345 disponibles lo cual correctamente suma un total de 2518, pero para el 30 de mayo están los mismos 2173 ocupados y 345 disponibles pero con un total de 2544 ventiladores, lo cual no corresponde a la suma.

**Comment by paarriagadap** [comment]
Es verdad. Es una falla desde el informe que lo muestra así. El 04/05 pasa algo similar, con 1174 ocupados y 654 disponibles que suman 1828, pero aparece 1825 como el total. Yo termino usando sólo los ocupados y disponibles

**Comment by dna33** [comment]
Me parece estos descuadres han sido corregidos, gracias por reportar.
