### ISSUE TITLE
Para el producto 5 & Casos nuevos sin síntomas están con valor vacíos

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#279]
Hola, que tal
Para el producto 5, los valores iniciales de Casos nuevos sin síntomas están con valor vacíos desde la fecha 2020-03-03 hasta 2020-04-28, a domo de sugerencia, se podrían rellenar con valores 0.0 como los demás, Gracias

**Comment by worldofvitox** [comment]
en lo personal, me parece que tiene valor que se haga el distingo entre que un dato no se haya reportado en esa fecha, y que haya sido cero.

**Comment by ekos77** [comment]
ok, gracias

**Comment by MinCiencia** [comment]
Hola, ha sido más popular en general la visión de @worldofvitox. Si es que necesitas rellenar con ceros, hay varias opciones en paquetes populares como Pandas, por citar algún ejemplo. Cuéntanos si necesitas ayuda para enviarte algunos links. Saludos.

**Comment by ekos77** [comment]
Genial @MinCiencia agradecería mucho la ayuda, intento traspasar estos archivos .csv a .json, pero los script que hacen lectura posterior de estos .json, generan errores de lectura, dada la variedad en sus resultados, siendo como mencionaba inicialmente valores vacíos o 0.0, así que reitero mi interés y agradezco mucho estos link para resolverlos, pese que la transformación de estos archivos lo realizo en .php y no en .py, aun que de todas formas me interesa la información

**Comment by MinCiencia** [comment]
El package de pyton Pandas ha sido útil en este tipo de necesidades. Mira este ejemplo y cuéntanos por favor si resuelve tu necesidad:

https://stackoverflow.com/questions/13295735/how-can-i-replace-all-the-nan-values-with-zeros-in-a-column-of-a-pandas-datafram

**Comment by ekos77** [comment]
@MinCiencia Muchas gracias por el dato, ya fue solucionado con **PythonPanda**

**Comment by ekos77** [comment]
@MinCiencia Respecto al indice de movilidad, por ejemplo, en Antofagasta, comuna x, día x, aparece un indice de movilidad interno de 0,1..., esto se lee como ¿"cada persona realiza 0,1... viajes diarios"? y si no es así, ¿Como se lee dicho dato? gracias.
