### ISSUE TITLE
producto 33 & Movilidad en Chile

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#280]
Hola, que tal
Para el producto 33, se expresan datos de movilidad por regiones y comunas en un solo archivo.
Lo cual es muy poco practico para crear modelos de datos, por varias razones
pregunto, ¿Es posible acceder a esta información de forma mas objetiva, ya sea en archivos separados por regiones o comunas almeno?

**Comment by paarriagadap** [comment]
Si te sirve, aparte de esta movilidad por comunas existe la movilidad publicada por Google. En el caso de Chile, está a nivel de país y regiones y es más reciente: https://www.google.com/covid19/mobility/

**Comment by MinCiencia** [comment]
Hola @ekos77, ¿por qué te resulta poco práctico el formato de publicación?

**Comment by ekos77** [comment]
@MinCiencia, Hola, gracias por atender al mi inquietud:
Espero expresarme bien.
En lo personal, seria ideal generar un JSON con estos datos en varios niveles, pero el formato expuesto, me impide mucho tomar algunos datos en especifico o filtrarlos por región o comuna, por que la información esta toda junta, por decirlo así.
Sin mencionar que el archivo tiene un tamaño bastante grande, lo cual podría reducirse tal vez desagregando aun más la información.

**Comment by scornejob** [comment]
@ekos77 , que herramienta usas para hacer análisis?

**Comment by ekos77** [comment]
@scornejob  estoy iniciando el proyecto, pero para capturar los .cvs utilizo script de .php y .py. para transformarlos a .json, y finalmente los intento graficar con morris.js.. pronto subiré los repositorios estimado por si le sirve a alguien más

**Comment by scornejob** [comment]
@ekos77 , nosotros usamos la biblioteca [pandas](https://pandas.pydata.org/), para procesar los datos. [Aca](https://colab.research.google.com/drive/1XZgfe4GXAHD3A_XLU355amU572kYuvok?usp=sharing) hay un snippet donde filtramos, graficamos y pasamos a json.

**Comment by ekos77** [comment]
@scornejob estimado, muchas gracias por el tips´s, me es de gran ayuda gracias

**Comment by ekos77** [comment]
borraron los repositorios oficiales?

**Comment by scornejob** [comment]
cerrando dado que el issue reportado fue atendido.

**Comment by ekos77** [comment]
@MinCiencia  Respecto al indice de movilidad, por ejemplo, en Antofagasta, comuna x, día x, aparece un indice de movilidad interno de 0,1..., esto se lee como ¿"cada persona realiza 0,1... viajes diarios"? y si no es así, ¿Como se lee dicho dato? gracias.

**Comment by MinCiencia** [comment]
Claro, quizás es más claro si lo piensas como que se requieren al menos 10 personas para encontrar una que hace 1 viaje.

Esta normalizado por el número de habitantes por comuna.

**Comment by ekos77** [comment]
@MinCiencia Gracias por la aclaración, buenas noches.
