### ISSUE TITLE
deprecar producto 14 

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#281]
A partir del 20200602, en https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/ no esta el desglose de fallecidos por region, por lo tanto no podemos obtener el dato desde ahi.

**Comment by paarriagadap** [comment]
Con eso no quedaría ningún archivo con las muertes por región, cierto? De los informes del Minsal también sacaron los PCR por región

**Comment by scornejob** [comment]
No se depreca el prod14: se genera a partir del reporte diario.
https://github.com/MinCiencia/Datos-COVID19/pull/284
