### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [MinCiencia/Datos-COVID19#285]
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data framehttp://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/2BBSWG

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by MinCiencia** [comment]
Hi, thank you for including this dataset there.

1) What else besides what we already do in this repository are you asking us to do? We currently update daily most of the data in the repository 
2) All relevant metadata is shared in the readme.md of each data product.

**Comment by reeshmabijosh** [comment]
Hello,

Thanks for your willingness to contribute.
 Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and
I’ll give you the necessary permissions for editing your dataset.
Then please add relevant metadata - description and keywords to your
dataset.”

Thanks
Reeshma K
