### ISSUE TITLE
producto 7 no se actualizara mas?

### ISSUE THREAD

**Issue by robdi123** [MinCiencia/Datos-COVID19#291]
hay alguna forma de seguir obteniendo la data del producto 7? desde el reporte del 02/06 ya no aparece.

**Comment by MinCiencia** [comment]
Se va a reponer en los próximos días.

**Comment by robdi123** [comment]
Gracias!

**Comment by ahecheve** [comment]
@MinCiencia 

Hola! Entiendo que se repondrá prontamente, pero se sabe más o menos cuando?
Desde el 2/6 el numero de examenes PCR es Null

Muchas gracias de antemano.

**Comment by ahecheve** [comment]
Muchas gracias a quien lo haya corregido.
El producto está entregando la DATA nuevamente. 

Se debiese cerrar el Issue.

**Comment by MinCiencia** [comment]
Ha sido un trabajo conjunto con el Ministerio de Salud y su Departamento de Epidemiología.
