### ISSUE TITLE
Producto 5: significado de recuperados y activos

### ISSUE THREAD

**Issue by javierconcha** [MinCiencia/Datos-COVID19#293]
Me acabo de dar cuenta (después que mi website cratched) que el Minsal empezó a reportar los casos activos en vez de los de recuperados. Veo que el producto 5 tiene los datos para el 02/06 y 03/06 en blanco. 

Mi consulta es: Ya no se actualizará los recuperados en el producto 5?

Lo otro es que tengo ahora la confusion de que se estaba reportando como recuperados antes.
Hubiera pensado que:
activos = totales - fallecidos - recuperados 
y por lo tanto:
recuperados = totales - fallecidos - activos

Pero cuando trato de obtener los recuperados usando esto ultimo para el 02/06 y 03/06 , obtengo 90,748 y 86,173, respectivamente, lo que es un incremento bastante grande comparado con los 44,946 del 01/06. 

Que no estoy considerando?

Mas info:
https://www.emol.com/noticias/Nacional/2020/06/03/988030/Minsal-balance-coronavirus.html

**Comment by valkot** [comment]
si te dará mas grande el numero porque si ves el valor que tenias en activos antes por ejemplo el 01/06 era de 59.100 y el 02/06 bajo a 21.325 por ende te da esto:

01/06/20 =>  Recuperados = 108.686 - ( 1.113 + 59.100 ) => 44.946
02/06/20 => Recuperados = 108.686 - ( 1.188 + 21.325 ) => 86.173
03/06/20 => Recuperados = 113.628 - ( 1.275 + 21.605 ) => 90.748

**Comment by ivanMSC** [comment]
No viste las noticias?

**Comment by aminoplis** [comment]
Estimados, no hay como considerar 21.605 como el total de casos activos a Nivel Nacional. Ahora en la base de la Univ Johns Hopkins puso los 21.605 como casos recuperados!!!!
Finalmente no entiendo el criterio ni como se va a corregir.

**Comment by javierlopeza** [comment]
Lo primero que hay que tener claro es que los recuperados que se reportan son desde el punto de vista epidemiológico, es decir, son el número de personas que han superado el período infectante, lo que no equivale a una recuperación clínica. Esto se deja claro en los conceptos clave del [Informe EPI](https://www.minsal.cl/wp-content/uploads/2020/06/Informe_EPI_010620.pdf).

En cuanto al cambio de metodología de conteo de casos activos:

Previo al 2 de junio, los casos activos a nivel nacional publicados en el Reporte Diario eran contabilizados usando la fecha de notificación del examen PCR, entregando cifras mucho más conservadoras, pero rápidas para la efectiva gestión diaria de la autoridad sanitaria. Desde el 2 de junio, el Reporte Diario cambió la metodología de conteo de casos activos por la misma que utiliza el Informe Epidemiológico, es decir, la fecha de inicio de síntomas.

El mayor efecto de este cambio es que la información a nivel nacional, entregada diariamente por el Ministerio de Salud, será más precisa, por usar la fecha de inicio de síntomas para calcular el período en que una persona infectada puede contagiar. El día en que se aplica el cambio de metodología de conteo efectivamente disminuyen notablemente los casos activos a nivel nacional dado que gran parte de ellos estaban, en realidad, fuera del periodo de contagio.

El 2 de junio, en [COVID-19 en tu comuna](https://covid19entucomuna.cl/), calculamos retroactivamente los casos activos a nivel nacional utilizando los Informes Epidemiológicos publicados en las semanas anteriores para ser consistentes en la información visualizada. Al ver el gráfico de casos activos a nivel nacional se puede ver que hay consistencia en las cifras entregadas en los Informes EPI anteriores y las nuevas cifras entregadas desde el 2 de junio. De esta manera, toda cifra de casos activos que presentamos en esta página, es calculada utilizando la fecha de inicio de síntomas.

**Comment by valkot** [comment]
> Estimados, no hay como considerar 21.605 como el total de casos activos a Nivel Nacional. Ahora en la base de la Univ Johns Hopkins puso los 21.605 como casos recuperados!!!!
> Finalmente no entiendo el criterio ni como se va a corregir.

Lo mas probable es que ellos estuvieran haciendo scraping de donde todos lo hacemos y como los señores pusieron los activos donde ellos antes tenían los recuperados, te muestra ese valor.

Lo malo de Minsal es que no sigue un estándar y genera que la lectura de terceros sea errónea.

**Comment by javierconcha** [comment]
Me pregunto si se podrá corregir los recuperados anteriores al 02/06 aplicando el nuevo criterio, y así evitar ese salto en la gráfica de recuperados.

**Comment by MinCiencia** [comment]
Hola @javierconcha, hemos decidido hacer un par de cosas, pero no implementado aún:

1. crear 2 nuevas categorías en el producto 5, "recuperados por FIS", "activos por FIS" y calcularlas con el reporte diario acorde al criterio informado por la autoridad sanitaria.
2. renombrar columnas actuales y darle continuidad a la serie con el criterio anterior.

El criterio de 1 es el que se usaba para las comunas, en el producto 15 y 19 por ejemplo. El criterio de 2 es el que está indicado en el readme del producto 5.

**Comment by ahecheve** [comment]
@MinCiencia Muchas gracias por esta respuesta. Muy claro lo que se hará.

Desde el 2/6, la columna recuperados está quedando como NaN. Entiendo que al implementarse esto, "recuperados por FC" corregiría esto.

**Comment by MinCiencia** [comment]
Hola, hemos hecho el cambio en el producto 5 como fue anunciado, se mantendrán por 2 semanas las columnas antiguas, y se añadieron 4 nuevas columnas con los conteos por criterios de fecha de diagnóstico y por fecha de inicio de síntomas.

**Comment by MartinSchaffernicht** [comment]
Entendiendo que el inicio de la fase "activa" y su término son mejor representado por la fecha de inicio de los síntomas (FIS) que la fecha de diagnóstico (FD), esto se refiere a dos variables de flujo "empezar a ser un caso activo" y "terminar la fase activa". Entonces si hasta el 1/6 se ha usado la FD para depositar gente en "casos activos" y retirarlos de "activos", los "activos" reflejaron la situación con un desfase de un par de días. 

Ahora el movimiento de "activo" a "recuperado" se hace según FIS, pero la llegada a "activos" sigue haciendose según FD. Entonces, los nuevos activos se agregan a "activos" recién cuando está el diagnóstico, pero se retiran X días antes (según FID). Esto da la sensación de que tengamos menos "activos", pero es una especie de ilusion. 

Se debería usar FIS también para los casos nuevos: cuando se confirma un caso por diagnóstico y la persona indica que los síntomas empezaron X días antes, se deberían corregir retroactivamente las cifras de "casos nuevos". Ya que no hay dos columnas "casos nuevos FD" y "casos nuevos FIS", me imagino que no se está haciendo. 

Si mi razonamiento está equivocado, me gustaría recibir una corrección en la que se indica cuántos días de diferencia hay en promedio entre FD y FIS, y por qué no sería eróneo añadir casos nuevos según FD y sacar casos recuperados según FIS.

**Comment by MartinSchaffernicht** [comment]
Agregando al comentario de ayer, creo que se debería adaptar la manera de cifrar los "casos nuevos" diarios de DF a FIS, o por lo menos incluir una columna "Nuevos casos FIS" en los datos. Mi razonamiento para esto me resultó largo, lo anoté en un PDF. Corto: creo que si uno agrega _casos nuevos_ a _casos activos_ según fecha de diagnóstico (FD) y los saca como _recuperados_ a los 14 días de haber sido _casos nuevos_ segín fecha de inicio de síntomas (FIS), esto disminuye erróneamente el número de _casos activos_. 


[Acerca del conteo de los casos según fecha de diagnóstico o de fecha de inicio de síntomas.pdf](https://github.com/MinCiencia/Datos-COVID19/files/4768058/Acerca.del.conteo.de.los.casos.segun.fecha.de.diagnostico.o.de.fecha.de.inicio.de.sintomas.pdf)
