### ISSUE TITLE
[Nuevo Dataset] Contagios reportados por Gendarmería

### ISSUE THREAD

**Issue by cnavarreteliz** [MinCiencia/Datos-COVID19#30]
Hola, encontré este conjunto de datos publicado por Gendarmería con el número de contagios de la población penal en Chile, el que se ha estado actualizando desde el 08/04/2020.
[https://www.gendarmeria.gob.cl/corona2020.html](https://www.gendarmeria.gob.cl/corona2020.html)

**Comment by estebaniglesias** [comment]
Hola @cnavarreteliz ! 
Muy importante esta información! Te gustaría colaborar con este tipo de ideas, o inluso programando la extracción de estos datos?
En https://github.com/YachayData/COVID-19 estamos trabajando, aceptamos todo tipo de colaboración. Si tenemos una buena herramienta para extraer estos datos, hacemos un pull request a MinCiencia!
