### ISSUE TITLE
Defunciones se han reducido el día de hoy

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#302]
Hola! Habrá alguna razón por la que el número de defunciones de las últimas semanas se haya reducido entre ayer y hoy? Vi que en la actualización de `Defunciones_std.csv` se eliminaron 218 registros y no se agregó ninguno, pero no estoy seguro si es esa la razón: https://github.com/MinCiencia/Datos-COVID19/commit/c5564b21e3a5890f3dde8cd89ae2841ba7d77902
![image](https://user-images.githubusercontent.com/63430031/83799829-05128500-a66c-11ea-8f21-197d0a3e0554.png)

**Comment by MinCiencia** [comment]
Hola, pusiste un link que apunta al data product de nacimientos. Puedes explicar bien a que data product te refieres, por favor?

**Comment by paarriagadap** [comment]
En realidad el link era de todas las actualizaciones desde el Registro Civil. Igual pasó que al día siguiente el archivo mostró más casos y siguió aumentando los días posteriores, así que quizás haya que cerrar el issue.
