### ISSUE TITLE
producto 5

### ISSUE THREAD

**Issue by AlvaroHumeres** [MinCiencia/Datos-COVID19#307]
Hola estimados, muchas gracias por el trabajo que hacen con esto! tengo una duda, el producto 5 hace unos días que dejó de actualizarse en varias columnas, lo seguirán actualizando? muchas gracias!

**Comment by ahecheve** [comment]
Entiendo que el campo de recuperados por el cambio de definición hace algunos días no se ha actualizado.

Hoy se hizo otra modificación y no me queda claro si el producto seguirá funcionando o no...
"ported prod 5 to reporte diario deprecating webscrapper"

**Comment by Daniel77july** [comment]
Hola. Voy a aprovecha de seguir el mismo hilo...la columna de hoy tiene datos errados
Imagino que es lo mismo que comenta el colega al principio

**Comment by scornejob** [comment]
gracias a todos,

Correjimos en parte. Estamos estudiando alternativas para extraer el dato de los casos activos.

**Comment by LuisAcunaSM** [comment]
¡Corregido!
Gracias a quien lo haya hecho.

**Comment by scornejob** [comment]
ahora si, estan todos los datos disponibles. De nada @LuisAcunaSM
