### ISSUE TITLE
En Producto 3 se capturó información errónea

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#311]
Hola, en el producto 3, [Casos totales por región](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto3), hubo un error de captura de los informes, al parecer por el punto de miles que en algunos casos se interpretó como coma. Esto es en los casos de Tarapacá, Ñuble y el Total. 
![image](https://user-images.githubusercontent.com/63430031/83977944-afd3af00-a8c9-11ea-8da0-8214988622b6.png)

**Comment by scornejob** [comment]
gracias @paarriagadap . Efectivamente, hubo un problema con los puntos. Ya lo arreglamos.

**Comment by paarriagadap** [comment]
Gracias!
