### ISSUE TITLE
Product 4 tiene cifras erroneas para Junio 7

### ISSUE THREAD

**Issue by maikelson** [MinCiencia/Datos-COVID19#312]
En archivo 2020-06-07-CasosConfirmados-totalRegional.csv el total no suma (13415) y agreando los nuevos al dia anterior tampoco. Gracias!

**Comment by maikelson** [comment]
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-06-07-CasosConfirmados-totalRegional.csv - Fila 18

**Comment by scornejob** [comment]
Ya fue arreglado
