### ISSUE TITLE
Datos incrementales que decrecen ?

### ISSUE THREAD

**Issue by titore74** [MinCiencia/Datos-COVID19#32]
Datos de Valparaiso y Puerto Montt decrecen entre el 1 y el 3 de abril:

![Screen Shot 2020-04-14 at 12 55 18](https://user-images.githubusercontent.com/63661056/79252532-ca505580-7e4f-11ea-942f-337606bb12c2.png)

**Comment by ivanMSC** [comment]
Deben ser los casos de los barcos Silver Explorer en Los Lagos y el Isabela Island en Valparaíso.

**Comment by titore74** [comment]
Buena ! Gracias
