### ISSUE TITLE
Página de minsal con fecha equivocada para el 09/06

### ISSUE THREAD

**Issue by javierconcha** [MinCiencia/Datos-COVID19#325]
La página del minsal:
https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/
creo que actualizó los datos para el 09/06 pero no cambió lo siguiente:

> "Informe corresponde al 8 de junio de 2020. El corte de la información se realizó a las 21:00 horas del 7 de junio."

Alguien puede corroborar esto.
Gracias!

**Comment by MinCiencia** [comment]
Hola @javierconcha, reportamos el error. Gracias!
