### ISSUE TITLE
producto 37: Datos para 09/06 son idénticos a datos para 08/06

### ISSUE THREAD

**Issue by damorend** [MinCiencia/Datos-COVID19#326]
Hola, como dice el título, no hay diferencias entre los datos de defunciones de ayer y la cifra actualizada al día de hoy. El total de las defunciones de los dos días anteriores correspondía a la cifra de fallecidos informada en los informes diarios respectivos, en cambio hoy se actualizó la información sin incluir los 19 casos nuevos informados.

**Comment by damorend** [comment]
Hola, como dice el título, no hay diferencias entre los datos de defunciones de ayer y la cifra actualizada al día de hoy. El total de las defunciones de los dos días anteriores correspondía a la cifra de fallecidos informada en los informes diarios respectivos, en cambio hoy se actualizó la información sin incluir los 19 casos nuevos informados.

**Comment by MinCiencia** [comment]
@damorend tuvimos un problema en el update automático de hoy, ya está solucionado. Gracias por reportar.
