### ISSUE TITLE
PRECAUCIÓN: Último informe EPI del 13/04/2020 tiene un par de errores

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#33]
Los números no cuadran en comunas Aisén y Coyhaique. 

![image](https://user-images.githubusercontent.com/35350256/79271344-a865cb80-7e6d-11ea-9189-1766417bc4e9.png)

Si calculan el total de casos para estas comunas a partir de la tasa y población se obtiene 4 en Aisén y 1 en Coyhaique.

Según información recopilada desde comunicados de gobierno regional de Aisén, la comuna de Aisén debe tener 4 casos confirmados a la fecha y la comuna de Coyhaique debe tener 1 caso confirmado a la fecha. Por lo tanto, las tasas informadas son correctas, pero no el número de casos confirmados.

**Comment by ivanMSC** [comment]
Esperemos que @MinCiencia corrija esto antes de hacer su scrape.

**Comment by MinCiencia** [comment]
Gracias, acorde a MINSAL esto se debía al ejercicio de proteger identidad de personas en comunas con pocos contagiados. En los últimos reportes y frente al hecho de que el número se puede calcular de la tasa, lo han estado reportando. Lo agregamos como nota a los datos.
