### ISSUE TITLE
Base de datos infectados incompleta

### ISSUE THREAD

**Issue by aerrazuriz** [MinCiencia/Datos-COVID19#333]
He estado buscando una base única que contenga lo siguientes campos en cada fila:

**fecha, edad, género, comuna, contagios**

¿Alguno sabe si existe esta base o que bases se podría utilizar para construirla?

Agradezco su ayuda.

**Comment by MinCiencia** [comment]
fecha, edad, género, contagios: 

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto16

comuna, contagios:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto1

**Comment by aerrazuriz** [comment]
Gracias, pero con las bases enviadas no puedo cruzar las variables Género y  Edad con variable Comuna. Necesito la base de los contagios diarios por Edad y Genero y Comuna. ¿Es posible obtenerla?

Saludos,

AE



Augusto Errázuriz
Business Development Officer, Mid Markets
BIG DATA SCORING AMERICA SpA
Mobile Phone: +569 8929 5996
Fixed Phone: +562 3262 9477
Skype: augusto.errazuriz

www.bigdatascoring.com
[cid:image001.png@01D1B2B4.08B322B0]



De: Ministerio de Ciencia, Tecnología, Conocimiento, e Innovación. <notifications@github.com>
Enviado el: jueves, 11 de junio de 2020 12:22
Para: MinCiencia/Datos-COVID19 <Datos-COVID19@noreply.github.com>
CC: Augusto Errázuriz <augusto.errazuriz@bigdatascoring.com>; Author <author@noreply.github.com>
Asunto: Re: [MinCiencia/Datos-COVID19] Base de datos infectados incompleta (#333)


fecha, edad, género, contagios:

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto16

comuna, contagios:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto1

**Comment by MinCiencia** [comment]
No, la autoridad sanitaria no ha hecho publica esa información a nivel comunal. Puedes explicar para qué la necesitas? Puede ayudar a avanzar en esa dirección. Estamos junto con el Ministerio de Salud avanzando en la publicación de más datos en sus informes y en este repositorio.

**Comment by aerrazuriz** [comment]
Claro! somos una empresa Finlandesa especialistas en modelos predictivos orientadas principalmente a soluciones financieras a nivel global. No obstante, hace solos unos días nos adentramos a modelar modelos predictivos de contagios COVID-19 para América Latina. Si bien hemos comenzado con el caso de Colombia, los resultados que hemos conseguido en dicho país son muy promisorios. Estamos avanzando con modelos en Brasil y Chile, pero hemos visto que para el caso de Chile la información es más limitada.

Si fuera posible conseguir el cruce Edad, Genero, Comuna y ojala Manzana, podríamos rápidamente dar a conocer los resultados de un modelo para Chile y disponerlo para la autoridad sanitaria.

Cuéntame si eso sería posible.
Saludos,

AE


De: Ministerio de Ciencia, Tecnología, Conocimiento, e Innovación. <notifications@github.com>
Enviado el: jueves, 11 de junio de 2020 12:41
Para: MinCiencia/Datos-COVID19 <Datos-COVID19@noreply.github.com>
CC: Augusto Errázuriz <augusto.errazuriz@bigdatascoring.com>; Author <author@noreply.github.com>
Asunto: Re: [MinCiencia/Datos-COVID19] Base de datos infectados incompleta (#333)


No, la autoridad sanitaria no ha hecho publica esa información a nivel comunal. Puedes explicar para qué la necesitas? Puede ayudar a avanzar en esa dirección. Estamos junto con el Ministerio de Salud avanzando en la publicación de más datos en sus informes y en este repositorio.

**Comment by MinCiencia** [comment]
Hola, puedes compartir la fuente de los datos de Brasil que estas utilizando? Conocemos los de Colombia.

Esta semana se compartirán nuevos datos a nivel comunal, sin embargo el desglose por sexo y edad a nivel comunal no está entre ellos.

**Comment by aerrazuriz** [comment]
Hola,

Acabo de notar que me rebotó el correo con los datos de Brasil, al parecer, solo pueden recibir correos bajo los 4mb. De todos modos, los pueden encontrar en este link:

https://covid.saude.gov.br/

Por otro lado, ¿es posible hablar con alguien para obtener de manera confidencial los datos desagregados a nivel de manzana censal? Creemos que podemos construir un modelo altamente predictivo si consiguiéramos dichos datos. Como ya comenté, dispondríamos el modelo para uso de la autoridad sanitaria gratuitamente.

Quedo atento,
Saludos,


AE



Augusto Errázuriz
Business Development Officer, Mid Markets
BIG DATA SCORING AMERICA SpA
Mobile Phone: +569 8929 5996
Fixed Phone: +562 3262 9477
Skype: augusto.errazuriz

www.bigdatascoring.com
[cid:image001.png@01D1B2B4.08B322B0]






De: Ministerio de Ciencia, Tecnología, Conocimiento, e Innovación. <notifications@github.com>
Enviado el: jueves, 11 de junio de 2020 12:54
Para: MinCiencia/Datos-COVID19 <Datos-COVID19@noreply.github.com>
CC: Augusto Errázuriz <augusto.errazuriz@bigdatascoring.com>; Author <author@noreply.github.com>
Asunto: Re: [MinCiencia/Datos-COVID19] Base de datos infectados incompleta (#333)


Hola, puedes compartir la fuente de los datos de Brasil que estas utilizando? Conocemos los de Colombia.

Esta semana se compartirán nuevos datos a nivel comunal, sin embargo el desglose por sexo y edad a nivel comunal no está entre ellos.

**Comment by aerrazuriz** [comment]
Estimados,

Hemos trabajado con la data que ha sido publicada hasta el momento pero los resultados están lejos de lo esperado. Los modelos no son estables porque el nivel de granuralidad es muy bajo. Necesito solicitar la data COVID a nivel de manzana, en otras palabras, necesito los siguientes campos:

Edad, Genero, Manzana (or equivalent), etc…
56     M           00000000000
47     M           10101010010
82     F             22121211112

Entiendo que esto no es público, pero es la única forma de poder generar un modelo estable y altamente predictivo con los datos existentes. ¿Qué alternativas para solicitar esta información existen? ¿Solicitar por ley de transparencia?
No tenemos problemas en firmar un Acuerdo de Confidencialidad, al final, esto lo hacemos ad-honorem por el bienestar del país.

Quedo atento.
Saludos,

AE



Augusto Errázuriz
Business Development Officer, Mid Markets
BIG DATA SCORING AMERICA SpA
Mobile Phone: +569 8929 5996
Fixed Phone: +562 3262 9477
Skype: augusto.errazuriz

www.bigdatascoring.com
[cid:image001.png@01D1B2B4.08B322B0]



De: Augusto Errázuriz
Enviado el: martes, 16 de junio de 2020 9:24
Para: 'MinCiencia/Datos-COVID19' <reply@reply.github.com>; MinCiencia/Datos-COVID19 <Datos-COVID19@noreply.github.com>
CC: Author <author@noreply.github.com>
Asunto: RE: [MinCiencia/Datos-COVID19] Base de datos infectados incompleta (#333)

Hola,

Acabo de notar que me rebotó el correo con los datos de Brasil, al parecer, solo pueden recibir correos bajo los 4mb. De todos modos, los pueden encontrar en este link:

https://covid.saude.gov.br/

Por otro lado, ¿es posible hablar con alguien para obtener de manera confidencial los datos desagregados a nivel de manzana censal? Creemos que podemos construir un modelo altamente predictivo si consiguiéramos dichos datos. Como ya comenté, dispondríamos el modelo para uso de la autoridad sanitaria gratuitamente.

Quedo atento,
Saludos,


AE



Augusto Errázuriz
Business Development Officer, Mid Markets
BIG DATA SCORING AMERICA SpA
Mobile Phone: +569 8929 5996
Fixed Phone: +562 3262 9477
Skype: augusto.errazuriz

www.bigdatascoring.com
[cid:image001.png@01D1B2B4.08B322B0]






De: Ministerio de Ciencia, Tecnología, Conocimiento, e Innovación. <notifications@github.com<mailto:notifications@github.com>>
Enviado el: jueves, 11 de junio de 2020 12:54
Para: MinCiencia/Datos-COVID19 <Datos-COVID19@noreply.github.com<mailto:Datos-COVID19@noreply.github.com>>
CC: Augusto Errázuriz <augusto.errazuriz@bigdatascoring.com<mailto:augusto.errazuriz@bigdatascoring.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Asunto: Re: [MinCiencia/Datos-COVID19] Base de datos infectados incompleta (#333)


Hola, puedes compartir la fuente de los datos de Brasil que estas utilizando? Conocemos los de Colombia.

Esta semana se compartirán nuevos datos a nivel comunal, sin embargo el desglose por sexo y edad a nivel comunal no está entre ellos.
