### ISSUE TITLE
Actualizaciones

### ISSUE THREAD

**Issue by valkot** [MinCiencia/Datos-COVID19#334]
Estimados,

Les comento que el product 29 no se actualiza oportunamente, siguen apareciendo como "Futura" Calama y San Antonio, y lo otro en el product 5 esta actualizado hasta el 09/06/20 .

**Comment by Cacunas1** [comment]
Me sumo al comentario de @valkot . El **product 5** está desactualizado en 2 días.

**Comment by scornejob** [comment]
esta arreglado. Hubo un cambio en el codigo que estamos investigando
