### ISSUE TITLE
DP 36

### ISSUE THREAD

**Issue by valkot** [MinCiencia/Datos-COVID19#335]
Estimados,

Quisiera si pueden aclarar la terminología usada en este DP, puesto que los reportes de Minsal nombran a "cupos totales" no mencionan habitaciones, lo pregunto porque no se entiende si en una "habitación" puede estar una sola persona, y hemos visto que hay residencias para parejas.

Mas que nada para poder hacer el pie chart entre los cupos versus los usuarios.

PD. Disculpen que genere tantos hilos.

**Comment by fzmolina** [comment]
Estimado @valkot 

Los primeros reportes diarios utilizaron la nomenclatura que está en el repo, e.g. habitaciones. Al momento no se ha considerado hacer cambios a los campos cada vez que cambian los nombres de las columnas de las tablas en el reporte diario.

Para referecia: encabezado de la tabla correspondiente el 2 de junio 

<img width="710" alt="Screen Shot 2020-06-11 at 12 57 08" src="https://user-images.githubusercontent.com/13983083/84417450-a4db9000-abe3-11ea-813d-47c2a6e8b0a2.png">

**Comment by fzmolina** [comment]
El nombre de la columna "habitaciones totales" ha sido modificado por "cupos totales".

**Comment by valkot** [comment]
Gracias lo preguntaba porque TrakCare hace diferenciación entre cama y habitación por dar un ejemplo.

Se agradece la aclaración.

> Estimado @valkot
> 
> Los primeros reportes diarios utilizaron la nomenclatura que está en el repo, e.g. habitaciones. Vamos a actualizar para estar acorde con lo último reportado.
> 
> Para referecia: encabezado de la tabla correspondiente el 2 de junio
> 
> <img alt="Screen Shot 2020-06-11 at 12 57 08" width="710" src="https://user-images.githubusercontent.com/13983083/84417450-a4db9000-abe3-11ea-813d-47c2a6e8b0a2.png">

Gracias lo preguntaba porque TrakCare hace diferenciación entre cama y habitación por dar un ejemplo.

Se agradece la aclaración.
