### ISSUE TITLE
actualizacion producto 5

### ISSUE THREAD

**Issue by gmezaarrepol** [MinCiencia/Datos-COVID19#336]
Mucho gusto saludarlos, y agradezco la puesta a disposición de los datos. Respecto a la actualización del producto 5, al parecer falló el día de ayer, dado que aun esta el dato hasta el día 09/06. ¿cuando estará disponible el archivo actualizado?

Muchas gracias por su aporte.

**Comment by scornejob** [comment]
esta arreglado. Hubo un cambio en el codigo que estamos investigando

**Comment by gmezaarrepol** [comment]
muchas gracias por su pronta respuesta.
