### ISSUE TITLE
TotalesNacionales_std.csv (Producto 5)

### ISSUE THREAD

**Issue by ahecheve** [MinCiencia/Datos-COVID19#337]
Estimados,

Algo pasó que el producto en asunto, cambió. El archivo ahora, se muestra igual que el _T.
Por favor lo podrían revisar? 

Gracias de antemano!

**Comment by fzmolina** [comment]
Hola @ahecheve 

Se ha corregido. Muchas gracias por reportar

**Comment by ahecheve** [comment]
@fzmolina Muchísimas gracias por esto y todo el trabajo que están realizando.
Quedó OK, cerraré el issue.

**Comment by fzmolina** [comment]
Gracias a ti por ayudarnos a mejorar
