### ISSUE TITLE
Consulta sobre archivos FechaInicioSintomas

### ISSUE THREAD

**Issue by ConstanzaFosco** [MinCiencia/Datos-COVID19#346]
Buenos días. Necesitaría confirmar los datos de la semana 8. De acuerdo con la nota al pie del informe en versión pdf habría solo 1 caso en Las Condes. Sin embargo, en los archivos csv aparecen 2 casos, uno en Las Condes y otro en Vitacura.
Los totales del informe en pdf concuerdan con la versión de 1 caso solamente.
Muchas gracias.

**Comment by fzmolina** [comment]
Hola @ConstanzaFosco ,

Podrías indicar en qué informe (fecha) hay 1 caso en la semana epidemiológica 8 en Las Condes?

Saludos!

**Comment by ConstanzaFosco** [comment]
Hola! Gracias por contestar.
En los últimos informes escritos (en pdf) en las notas al pie.
Concretamente a partir del informe que salió con fecha 15 de mayo, en todos
ellos. La semana 8 no se publica pero aparece en una nota al pie.
Por ejemplo, en el que salió publicado ayer: "Un caso de residencia en Las
Condes no se visualiza en la tabla según fecha de inicio de síntomas ya que
corresponde a la semana epidemiológica 8."
Yo he estado siguiendo los datos del informe impreso. Y el total del
informe impreso coincide cuando solo tienes un caso en la S8.
saludos!
Constanza

**Comment by fzmolina** [comment]
Hola ConstanzaFosco,

Se está revisando con la fuente. Gracias por la observación.

La SE8 en el repositorio corresponde a la distribución de casos de acuerdo a la fecha de inicio de síntomas reportada en el informe epidemiológico del 20 de abril 2020.

**Comment by ConstanzaFosco** [comment]
Si! Gracias! Ya se que antes aparecían 2 casos, pero como continuamente
cambian los datos incluso los de las primeras semanas...muchas gracias!

**Comment by fzmolina** [comment]
Hola @ConstanzaFosco ,

Hemos actualizado los archivos FechaInicioSintomas en la SE8. En el país se ha reportado un caso en la comuna de Las Condes. Los que fueron reportados en los informes epidemiológicos del 20 y 24 de abril corresponden a errores de digitación. 

Saludos!

**Comment by ConstanzaFosco** [comment]
Muchas gracias!
