### ISSUE TITLE
Acerca de la consistencia de la información pública sobre los casos nuevos y los casos activos 

### ISSUE THREAD

**Issue by MartinSchaffernicht** [MinCiencia/Datos-COVID19#347]
Este mensaje se refiere a la información sobre los casos nuevos y los casos activos - no desde un punto de vista informático, sino que desde el punto de vista de "la gente" que busca comprender la dinámica del COVID-19.

He tenido varias dificultades para hacer uso e interpretar la información oficial. Los reiterados cambios de formato, contenido y de meteorología entre los reportes diarios y los informes epidemiológicos hacen que algunas informaciones importantes son entre muy difíciles o imposibles de interpretar. En especial, no he podido creer que cuando uno cambia el cálculo de los casos activos desde la fecha de diagnóstico a la fecha de inicio de síntomas, esto por día significar una disminución de los casos activos de 2/3 - en una fase de la pandemia cuando el número de casos nuevos diarios sigue creciendo. 

He intentado comprender las definiciones de los informes epidemiológicos y las explicaciones que se encuentran en la Internet; he intentado replicar las cifras que Gobernó indica diariamente en base de los datos oficiales, y no comprendo la manera como se procesan datos para estimar los casos activos y los casos recuperados. Tampoco pude comprender por qué se siguen usando los casos nuevos según fecha de diagnóstico en los reportes diarios cuando se informan según fecha de inicio de síntomas en los informes epidemiológicos.

Creo que es importante transparentar (y eventualmente revisar) la forma de calcular y la forma de entregar la información. Las siguientes páginas contiene mis dudas (y su respectivo fundamento).  La segunda sección analiza la información entregada por el gobierno en los informes epidemiológicos y los reportes diarios, para señalar duras incoherencias en las definiciones. Luego, la sección 3 entrega una definición de los conceptos acorde al modelo SEIR, pensando que esto puede ayudar a aclarar las definiciones conceptuales. La cuarta sección presente y fundamente mis duras respecto de las nuevas cifras de casos activos.

No sé si este foro es el lugar correcto para plantear mis dudas, pero espero que ustedes puedan mirar el cocumento adjunto y, si encuentren errores me los explican - y si mi argumentación les parece correcta, eventualmente la pueden usar. Agradecería retroalimentación.

[Consulta al Ministerio de Ciencias.pdf](https://github.com/MinCiencia/Datos-COVID19/files/4782485/Consulta.al.Ministerio.de.Ciencias.pdf)

**Comment by worldofvitox** [comment]
hola Martin, totalmente de acuerdo con que el informe y en general la estructura de datos necesita una consistencia absoluta de criterios y nomenclatura, creo que en la ultima tabla las diferencias que tienes son mas que nada del paso de criterio semanal a diario, pero te planteo una cosa adicional que no he visto que se esté usando: tu pregunta acerca de por qué la diferencia tan grande entre los activos FIS vs FD, se puede usar como un data point adicional, algo así como "visibilidad" ya que da información agregada y facil de usar acerca de qué tan tarde se está notificando en promedio.
si los activos FD son iguales a los FIS (imposible pero para ilustrar) tendriamos una visibilidad del 100% de los "días contagio" de cada notificado.
esta razón ha ido variando dramaticamente en el tiempo, desde un 73% a principios de mayo, hasta 36% en el ultimo informe EPI, es decir en promedio, un contagiado solo sabe de su status positivo en el día 11, con todo lo que eso conlleva.
esto tiene bastante correlato con los backlog en laboratorios, el ajuste de stock de positivos de anteayer, y las persistentes versiones acerca de demoras extremas en entrega de resultados.

**Comment by dna33** [comment]
Hola, queria saber si esta duda sigue vigente. Quedo atento, gracias.

**Comment by MartinSchaffernicht** [comment]
Hola,
mis preguntas ya no son las de junio 2020 ahora. Pienso que los "data products" han sido bastante transparentes y constantes en el tiempo. Encuentro los nombres de las variables que el Gobierno informa muy problemáticos (los datos confirmados no son la "realidad" como afirma la página https://www.gob.cl/coronavirus/cifrasoficiales/; el uso no sistemático de la palabra "total" borra la diferencia entre variables de estado y de flujo y además, no se clarifica lo que significa "casos diarios" ya que no se hace diferencia entre los casos reales y los casos detectados por PCR), pero claramente la presentación de los datos ha mejorado mucho con la inclusión de las series temporales.

Saludos,
Martin

**Comment by dna33** [comment]
Gracias por los comentarios, los remití a los equipos de comunicaciones, a cargo de las visualizaciones en gob.cl.

Saludos,

Demián

**Comment by MartinSchaffernicht** [comment]
Gracias Demián,

Martin
