### ISSUE TITLE
Fechas vacías en Producto 37

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#349]
Hola, en el Producto 37, [Defunciones por COVID en Chile (reporte diario)](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto37), aparecieron unas fechas con valor vacío y que incluyen muertos, con lo que no calzan los cálculos con los del informe diario:

![image](https://user-images.githubusercontent.com/63430031/84711639-6f5cdc80-af2c-11ea-88b8-445d827af3ae.png)

**Comment by MinCiencia** [comment]
Corregido. Gracias por reportar
