### ISSUE TITLE
Producto 37 no se actualizó

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#354]
Hola, el Producto 37, [Defunciones por COVID en Chile (reporte diario)](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto37) no se actualizó hoy.

**Comment by MinCiencia** [comment]
Hola @paarriagadap, hubo una demora en la entrega de ayer. Acabamos de subir las cifras para ayer y hoy. Gracias por reportar.

**Comment by paarriagadap** [comment]
Hola, nuevamente el producto no está disponible hoy

**Comment by ctroncoso** [comment]
> Hola, nuevamente el producto no está disponible hoy

Era esperable que se demorara. Con el reporte del DEIS supuse que tendrían nueva estructura. Está actualizado ya.
