### ISSUE TITLE
Detalle de los casos agregados ayer

### ISSUE THREAD

**Issue by damorend** [MinCiencia/Datos-COVID19#359]
El Minsal debe entregar un detalle de los 31.422 casos añadidos ayer al total acumulado, desagregados al menos por comuna y día de inicio de síntomas. No tiene sentido esperar al sábado o domingo para que lo informen en un pdf. Los casos ya están definidos, no van a cambiar en 3 ó 4 días. Tienen los datos, los pueden liberar inmediatamente en formato de tabla en esta plataforma.

**Comment by ivanMSC** [comment]
xd

**Comment by dna33** [comment]
Esto se desagrega en el producto 59 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto59 por fecha de notificación y en el producto 60 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto60 por fecha de inicio de síntomas.
