### ISSUE TITLE
Geometrías de cuarentenas de comunas Valparaíso y Viña del Mar están intercambiadas

### ISSUE THREAD

**Issue by JavierL1** [MinCiencia/Datos-COVID19#360]
Las [geometrías](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto29/Cuarentenas-Geo.geojson) de las cuarentenas correspondientes a Valparaíso y Viña del Mar tienen valores intercambiados. Por lo que veo el problema es solo en los campos `Nombre` y `Cut_Com`.

**Comment by scornejob** [comment]
@Leandermen , nos puedes ayudar con este issue?

**Comment by Leandermen** [comment]
Se corregirá en próximo pull request junto con añadir las comunas decretadas hoy

**Comment by scornejob** [comment]
EL PR fue mergeado. @JavierL1 puedes confirmar si esta ok y comentar/cerrar el issue?

**Comment by JavierL1** [comment]
Todo ok, gracias. 👍
