### ISSUE TITLE
Missing values producto 7

### ISSUE THREAD

**Issue by rguerral** [MinCiencia/Datos-COVID19#364]
Hola, 
El producto "DP7 - Exámenes PCR por región: Descripción" tiene datos faltantes para todas las regiones entre el 02/06 y el 09/06. Saben a que se debe? Gracias!

**Comment by fzmolina** [comment]
Hola @rguerral ,

La distribución de exámenes PCR por región no fue informada en el Reporte Diario durante esas fechas

**Comment by rguerral** [comment]
Gracias @fzmolina !
