### ISSUE TITLE
Cuál es la diferencia entre los dos archivos de test PCR?

### ISSUE THREAD

**Issue by gomena** [MinCiencia/Datos-COVID19#37]
No es claro de la descripción de producto 7 cuál es la diferencia entre ambos, y una inspección visual revela grandes similaridades (si no son iguales). Existe alguna forma de resolver a partir de esos datos el problema "algunos tests que se realizaron en la región X aparecen en la región Y"?

**Comment by alonsosilvaallende** [comment]
Me parece que son iguales sólo que uno es el transpuesto del otro.

**Comment by MinCiencia** [comment]
Tal cual, nos han solicitado hacer aquello las personas usándolo.

**Comment by gomena** [comment]
Gracias!!
