### ISSUE TITLE
Error tipeo producto 20 (20/06/2020)

### ISSUE THREAD

**Issue by nachomr7** [MinCiencia/Datos-COVID19#373]
Para el 20 de junio el número de ventiladores ocupados dice 2073 pero deberían ser 2703 para que calce con las cifras de disponibles y totales

**Comment by ctroncoso** [comment]
Del informe 20/06/2020
![image](https://user-images.githubusercontent.com/121016/85207142-ddbae980-b2f4-11ea-86ec-64723284aa77.png)

https://github.com/MinCiencia/Datos-COVID19/blame/master/output/producto20/NumeroVentiladores_std.csv#L205

**Comment by fzmolina** [comment]
Hola,

Ha sido corregido. Gracias por reportar
