### ISSUE TITLE
Line list data

### ISSUE THREAD

**Issue by Mougk** [MinCiencia/Datos-COVID19#374]
Hola, 

This is a fantastic repository! 

I was wondering whether there is any data product where each row represents a case with information such as date of onset, confirmation, hospitalisation, age, sex.

Moritz

Google translate English to Spanish:

"Este es un repositorio fantástico!

Me preguntaba si hay algún producto de datos en el que cada fila represente un caso con información como la fecha de inicio, confirmación, hospitalización, edad, sexo."

**Comment by damorend** [comment]
You and us all buddy, but our government refuses to release that information, even under restricted conditions for scientists.

**Comment by dna33** [comment]
Indeed, current Chilean regulation does not allow our Health Ministry to share that information under any circumstances, in consideration of every person right for privacy of their health records.
