### ISSUE TITLE
Por favor incluir las estadísticas de casos activos por comuna

### ISSUE THREAD

**Issue by JaimeCruzH** [MinCiencia/Datos-COVID19#38]

**Comment by MinCiencia** [comment]
Hola, la estadística de fallecidos y recuperados se reporta a nivel regional por parte de MINSAL, en cuanto se entregue información más desagregada la haremos disponible en formato abierto en este repositorio.

**Comment by ivanMSC** [comment]
@minsal Los casos activos y fallecidos por comuna han sido reportados en los últimos dos informes epidemiológicos. Los casos fallecidos por comuna se calculan restando las columnas "casos actuales" con "casos activos".

**Comment by MinCiencia** [comment]
Gracias, vamos a generar data product con la nueva información publicada.

**Comment by ivanMSC** [comment]
@MinCiencia Los fallecidos no están explicitamente, pero **se pueden calcular** restando las dos columnas: `casos actuales` menos `casos activos`. Si leen el glosario del informe se darán cuenta que la diferencia entre ambas columnas es justamente el numero de muertos.

**Comment by MinCiencia** [comment]
Perfecto, ahora entendemos el primer mensaje. Gracias por la aclaración.

**Comment by MinCiencia** [comment]
Hola, hoy incluimos este dato a nivel nacional reportado diariamente en el data product 5 y a nivel comunal reportado por informe epidemiológico cada 2-3 días en el data product 19.

Saludos,

Ministerio de Ciencia
