### ISSUE TITLE
Distribución de los casos no notificados que fueron reajustados

### ISSUE THREAD

**Issue by gmoralesc19** [MinCiencia/Datos-COVID19#381]
Falta realizar la distribución de los casos no notificados (los cuales fueron incorporados el 17 de junio) en todo el período pandémico, como en su mayoría son de la Región Metropolitana, se ve un salto en el producto3/CasosTotalesCumulativo_T.csv de 148302 a 180532 que ensucia la data.

**Comment by alonsosilvaallende** [comment]
Sí, pero esos fueron los casos informados ese día. Algunos han propuesto repartirlos en proporción al número de casos informados diarios sobre el total a esa fecha, pero hay otras formas, por eso pienso que acá lo dejan así y que cada quién decida que hacer con ese outlier...

**Comment by MinCiencia** [comment]
Hola, pueden revisar el producto 45 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto45 que muestra estos totales agregados por semana, como nos ha informado el ministerio de salud. Este producto se usó para actualizar los datos en la base de datos de JHU https://github.com/CSSEGISandData/COVID-19/issues/2858
