### ISSUE TITLE
Obtención de datos de Producto 37

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#382]
Hola, veo que los datos de defunciones por COVID-19 del producto 37 cuestan ser actualizados a tiempo los últimos días, probablemente por el origen de los datos. No han considerado usar los datos del gráfico que se publica en https://www.gob.cl/coronavirus/cifrasoficiales/ ? Quizás se puede hacer algo con la figura de Infogram, porque en el informe aparece sólo una foto de gráfico de Office.

Me parece importante contar con esa base de datos al mismo tiempo que el resto, ya que creo que es más útil para seguir el progreso de muertes que que ir contando con la irregularidad de los lunes y martes.

Muchas gracias por su trabajo, que sé que debe ser complejo en su obtención.

**Comment by dna33** [comment]
Hola, publicamos a medida que tenemos la información. Pero es bueno el punto que haces. De todas maneras, esta actualizado ahora.

Gracias.
