### ISSUE TITLE
Casos nuevos comunales Diarios

### ISSUE THREAD

**Issue by valkot** [MinCiencia/Datos-COVID19#385]
Seria posible obtener los datos diarios por comunas, yo puedo obtener los de las comunas de la cuarta región, creo que las gobernaciones los entregan diariamente, o en la prensa regional muestran los caso en sus comunas, como ara hacer un scraping y armar un archivo con esa información.

**Comment by ivanMSC** [comment]
Vea mi repo

**Comment by alonsosilvaallende** [comment]
Para Región Metropolitana faltan datos diarios @ivanMSC o has encontrado cómo obtenerlos de otra forma?

**Comment by ivanMSC** [comment]
No existen

**Comment by alonsosilvaallende** [comment]
OK, muchas gracias. Pensé que quizás se los enviaban a los municipios y estos los hacían públicos o algo así. Seguiré interpolando entonces. Muchas gracias.
