### ISSUE TITLE
Consulta  Casos nuevos entre 16-06-2020 y 17-06-2020

### ISSUE THREAD

**Issue by cgaetep** [MinCiencia/Datos-COVID19#386]
Estimad@s

Junto con saludar, quiero pedir su ayuda en si me pueden indicar por que  entre  los datos  acumulado de los días 16-06 y 17-06 hay un aumento significativo (casos nuevos),  por  ejemplo Tarapacá según tabla del producto 3 reporta  un dato 16-06-2020 de 4365 casos y para el  17-06-2020 , 4787 casos, lo que significa  422 casos nuevos, pero en el reporte diario se indican 114 casos nuevos. para metropolitana se reportan un aumento de 32230, pero en casos nuevos 3114. Sin embargo los datos de casos acumulados totales están  bien registrados en el reporte diario.

Muchas gracias de ante mano por la respuesta.

**Comment by dna33** [comment]
Hola, me parece esto está asociado a esto: https://github.com/MinCiencia/Datos-COVID19/issues/482
