### ISSUE TITLE
Error en los datos de Fecha de Inicio de Síntomas / Notificación

### ISSUE THREAD

**Issue by jorgeperezrojas** [MinCiencia/Datos-COVID19#389]
Lo datos del Data Product 39 de Fecha de Inicio de Síntomas / Notificación no parecen coincidir con el gráfico publicado en el [último informe de Epi Minsal](https://www.minsal.cl/wp-content/uploads/2020/06/Informe-EPI-230620.pdf). Si mirán por ejemplo en los últimos días, las barras azules (notificación) están siempre por sobre las rojas (sintomas). Sin embargo en el archivo [publicado acá](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto39/NotificacionInicioSintomas_T.csv) los valores de inicio de síntomas son mayores que los de notificación.
 
![Screen Shot 2020-06-25 at 18 37 06](https://user-images.githubusercontent.com/15633182/85803488-4222e200-b715-11ea-8a10-f8b59ea475eb.png)

**Comment by MinCiencia** [comment]
Corregimos, había un error en la tabla del informe epidemiologico. Gracias por reportar, @jorgeperezrojas
