### ISSUE TITLE
Data producto 17: inconsistencias

### ISSUE THREAD

**Issue by alonsosilvaallende** [MinCiencia/Datos-COVID19#39]
* Al 13 de abril el número de exámenes realizados acumulados en Hospitales Públicos es de 43.624 y para el 14 de abril 42.265, o sea menos que para el 13 de abril, lo cuál no puede ser.
* Sumando los exámenes realizados acumulados en Institutos de salud pública, Hospitales públicos y Privados, obtenemos los exámenes realizados acumulados totales. Para el 13 de abril se obtienen 85.035 exámenes realizados y para el 14 de abril se obtienen 84.794.
Adicionando los exámenes realizados acumulados al 13 de abril con los exámenes informados del día 14 de abril, se debería obtener los exámenes realizados totales acumulados, o sea 87.794. Pero no sé dónde faltan esos 3000. Quizás a Hospitales Públicos?
* Adicionando los exámenes realizados acumulados al 14 de abril con los exámenes informados del día 15 de abril, se debería obtener los exámenes realizados totales acumulados, o sea 91.873 pero el dato es 91.864. O sea, hay 9 tests extras quizás faltan en los informados?
Pueden ver un [gist](https://gist.github.com/alonsosilvaallende/22e41ce421778dde76e5c336b5a5e217) con esas incongruencias.

**Comment by fzmolina** [comment]
Hola alonsosilvaallende,

Muchas gracias por tu reporte. Los errores se debieron a dos typos, uno el 14 de abril (el dato correcto es 45.265 y no 42.265 como se tenía). Eso soluciona lo que expones en tu segundo punto.

El 15 de abril hubo otro error en los exámenes realizados en instituciones privadas se tenía 33.789, cuando el valor correcto es 33.798. Arreglando este valor la suma es la que indicas 91.873.

Ya hemos corroborado esto con la fuente y arreglamos el error. Gracias de nuevo.
