### ISSUE TITLE
Datos "Desconocido Arica y Parinacota"

### ISSUE THREAD

**Issue by juanshocl** [MinCiencia/Datos-COVID19#390]
Hola, quisiera saber ¿a que hace mención en el reporte del producto1 "Desconocido Arica y Parinacota" y los otros que también dicen desconocidos?.
Hace un tiempo no existía y ahora el script que me obtenía datos de ahi me dio error y descubrí que cambio la estructura del archivo.
¿Esos datos "desconocidos" son relevantes o no?

Saludos

![image](https://user-images.githubusercontent.com/2437325/85818378-85457b00-b73e-11ea-9ca3-3c41f1644740.png)

**Comment by fzmolina** [comment]
Hola @juanshocl ,

Sí, se agregó ese dato que se agrega en el informe EPI desde la publicación del 19 de Junio. Ese dato también está reflejado en el DP28 Casos nuevos por fecha de inicio de síntomas y región, informado por SEREMI: "...Estos casos tienen residencia indeterminada al momento de notificación (turistas sin domicilio conocido, pasajeros de cruceros, tripulantes de barcos mercantes, entre otros). Estos reflejan la información del último informe epidemiológico publicado por el Ministerio de Salud. Se recomienda sumar estos casos confirmados e informados por SEREMI a la suma de casos confirmados por comuna (totales regionales) dados en el Data Product 15 - Casos nuevos por fecha de inicio de síntomas por comuna y a otros productos que cuenten casos con fuente el Informe Epidemiológico."

Este dato se agrega para que se tenga claridad en el total de casos confirmados por región que se usa en la tasa de incidencia total por región reflejada en el DP18. 

Aclaro que en el DP18 no hay tasa de incidencia para desconocidos, porque estos no tienen una población asociada. Pero esos casos sí cuentan en el cálculo de la tasa de incidencia total de la región.

**Comment by juanshocl** [comment]
Gracias por la aclaración, lo tendre en consideracion en la recolección de datos, saludos.
