### ISSUE TITLE
datos regionales activos probables/confirmados informe diario

### ISSUE THREAD

**Issue by worldofvitox** [MinCiencia/Datos-COVID19#395]
hola

desde el informe diario de 21 de Junio, en la página 4 desde hoy 28 de Junio, hay un cuadro con los activos regionales, desglosados en confirmados y probables.

este dato hasta donde puedo ver, no está en este repositorio, lo mas cercano es el total regional de activos (probables+confirmados) del DP19.

este dato va a ser super interesante monitorearlo en los días que vienen debido a la marcada diferencia entre regiones entre sí y con RM

de antemano gracias.

**Comment by worldofvitox** [comment]
para ser mas exacto, en la pagina 1 del informe diario está el dato de "casos activos confirmados" en cada región, el que sumado al dato de "casos activos probables" de la página 4 del informe diario, da una cifra muy cercana (1%) a la reportada en DP19

**Comment by MinCiencia** [comment]
Hola, se nos había quedado este issue en el tintero. Te pedimos disculpas: en el producto 3 puedes encontrar lo que buscas:

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/TotalesPorRegion.csv
