### ISSUE TITLE
SUGERENCIA: Incluir producto con uso de ventiladores mecánicos

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#40]
Los reportes diarios de MINSAL incluyen datos del total de ventiladores, disponibles y ocupados

Esta es una información muy importante para monitorear la disponibilidad de estos recursos (y el riesgo de colapso de la atención crítica que requiera apoyo de ventiladores)

Sugiero crear  un producto con una serie de tiempo con estas métricas a nivel nacional

![image](https://user-images.githubusercontent.com/68602/79562175-999f3480-8078-11ea-9316-befd3e5039d8.png)

**Comment by estebaniglesias** [comment]
Hola @elaval!
Habrá una forma de automatizar la extracción de esos datos de los informes PDF?
Nosotros estamos trabajando con Tabula para la extracción automática de los infromes epidimiológicos, en https://github.com/YachayData/COVID-19

**Comment by ivanMSC** [comment]
@elaval Yo uso el servicio OCR de Google dentro de un GoogleApps Script. Así extraigo los datos sin necesidad de mirar el pdf.

**Comment by estebaniglesias** [comment]
Gracias! Le echaré una mirada!

**Comment by estebaniglesias** [comment]
Hola @ivanMSC , revisé tu repositorio y tienes muy buena info extraída de las comunas. Nosotros nos estábamos rompiendo la cabeza con los cambios de formato para extraer la info de los reportes EPI.
Creo que podríamos unir fuerzas en este sentido. De hecho, agregué tu repositorio como un submódulo en el nuestro, para captar rápidamente la info de las comunas que nos faltaban.

**Comment by MinCiencia** [comment]
Hola @elaval agregamos el [data product 20](/output/producto20) con esa información.
