### ISSUE TITLE
Producto 4   Archivo 2020-06-29- CasosConfirmados-totalRegional.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#401]
Hola, en el archivo de hoy del producto referenciado en el titulo el formato viene cambiado con . decimal y en caracteres lo que dificulta su conversión a números, los anteriores estaban en formato numérico. También tiene una fila agregada de totales que parece incorrecta.  Gracias

**Comment by fzmolina** [comment]
Hola @Jorgecibia,

Sí, el reporte diario cambió su formato hoy. Aprovechamos de concatenar los datos de dos de las tablas de la página 1 y 4 con las distribuciones regionales.

Arreglamos el problema que señalas. Gracias por reportar.
