### ISSUE TITLE
datos erroneos en producto1 / Covid-19.csv

### ISSUE THREAD

**Issue by alexisfch** [MinCiencia/Datos-COVID19#405]
En algunas comunas, i.e: Puerto Octay, Cobquecura, San Fabián, San Rosendo, Contulmo, Quilaco...

el dato de la fecha "2020-06-28", no esta correcto, siendo inferior el total **acumulado** de la comuna, que los **casos actuales** expresados en producto25 /CasosActualesPorComuna.csv

**Comment by alexisfch** [comment]
en realidad el problema está en el producto25 / CasosActualesPorComuna.csv, al agregar **fila en blanco 217** en la fecha "2020-06-28" se descompaginan valores desde comuna Sagrada Familia, hacia abajo, para esa fecha.

**Comment by fzmolina** [comment]
Hola @alexisfch ,

Sí, hubo un problema en el input. Fue resuelto, gracias por reportar
