### ISSUE TITLE
29 Junio: Faltan totales nacionales en producto 3 Datos-COVID19/output/producto3/TotalesPorRegion_std.csv

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#406]
![image](https://user-images.githubusercontent.com/68602/86073831-9948ef80-ba52-11ea-8cbe-224c272b1019.png)

**Comment by scornejob** [comment]
Resuelto en https://github.com/MinCiencia/Datos-COVID19/pull/410.

Todo se debio a nueva info entregada por minsal , que pusimos en el producto4

**Comment by elaval** [comment]
Gracias
