### ISSUE TITLE
Producto 37 Archivo Defunciones_deis_T.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#407]
Hola, del día 18/Jun al 25/Jun, las últimas filas (que se agregan vs semana anterior), están con punto decimal .0 lo que hace que no se cargue como número en excel.  Gracias

**Comment by fzmolina** [comment]
Hola @Jorgecibia ,

El formato ahora es de enteros para ese campo. Saludos.

**Comment by Jorgecibia** [comment]
Gracias
