### ISSUE TITLE
Por favor dejen de cambiar la estructura de los datos

### ISSUE THREAD

**Issue by guillermoburr** [MinCiencia/Datos-COVID19#408]
Por favor dejen de cambiar la estructura de los datos de este producto: https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto32/Defunciones_std.csv

**Comment by alexisfch** [comment]
algo asi como, paralamanoemano?

**Comment by fzmolina** [comment]
Estimado @guillermoburr ,

Son datos que recibimos en un formato que no ha sido constante. Estamos haciendo todo lo posible para estabilizar el formato en el output/producto32. Sabemos que estos cambios te pueden afectar, pero solicito también un poco de comprensión para ofrecer los datos de la manera más estable que las fuentes nos lo permiten.
