### ISSUE TITLE
PRODUCTO 13 - Casos nuevos hoy

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#413]
Hola amig@s, en el producto 13 los casos nuevos informados por el MINSAL corresponden a 75, mientras en el caso del producto 13 se declaran 81 igual que ayer... 
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto13

**Comment by adinamarca** [comment]
Pareciera que copiaron los datos de ayer y los colocaron para hoy... :(

**Comment by scornejob** [comment]
arreglado en https://github.com/MinCiencia/Datos-COVID19/pull/414

**Comment by adinamarca** [comment]
¡Gracias!, por casualidad, ¿el correo futuro@minciencia.gob.cl lo revisan?, he enviado varios correos y todavía no me responden por una iniciativa de página en Tarapacá que estoy llevando a cabo. 
Un saludo y gracias nuevamente.
