### ISSUE TITLE
Consulta: producto8 (Added data from reporte diario to repo)

### ISSUE THREAD

**Issue by mir-boz** [MinCiencia/Datos-COVID19#418]
Hola,
Deseaba consultar por el horario de subida de los datos correspondientes al reporte diario to repo. En particular el producto8. Habitualmente se suben tipo 12:00-13:00, y parece un poco extraño no haberlos subido aún. ¿Serán subidos hoy? ¿o no actualizarán ese producto?

Saludos, y muchas gracias por la labor.

**Comment by fzmolina** [comment]
Hola @mir-boz ,

Tuvimos un problema con el workflow y algunos productos no se generaron. Fue arreglado. Muchas gracias por reportar
