### ISSUE TITLE
Incluir region a los pcr informados

### ISSUE THREAD

**Issue by diegosep** [MinCiencia/Datos-COVID19#420]
Hola, en el [producto 17](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto17) podrían agregar la región a la que pertenecen los PCR informados? similar al [Producto 7](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto7)

Saludos!

**Comment by MinCiencia** [comment]
Hola @diegosep, la informacion que pides no ha sido hecha publica por el Ministerio de Salud hasta la fecha, por ende no podemos hacerlo. Dicho lo anterior, otros usuarios han solicitado lo mismo. Haremos llegar la solicitud a la autoridad sanitaria.
