### ISSUE TITLE
DUPLICACIÓN producto 13

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#430]
Estimad@s, nuevamente se duplicaron los valores en el producto 13, y quizás en otros más... Espero puedan arreglarlo, muchas gracias. :)
[Aquí](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto13/CasosNuevosCumulativo.csv)

**Comment by dna33** [comment]
Hola @adinamarca, ya está corregido. Gracias por reportar.

**Comment by adinamarca** [comment]
¡Gracias!, saludos.
