### ISSUE TITLE
Productos 3 y 4 Datos Regiones 

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#431]
Hola, datos con fecha de hoy son los de ayer. saludos y gracias

**Comment by elaval** [comment]
+1

![image](https://user-images.githubusercontent.com/68602/86537468-4097ad80-bebd-11ea-8e64-5bbf664a192d.png)

**Comment by frmco** [comment]
Producto N°4: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto4

![image](https://user-images.githubusercontent.com/64239643/86537974-f57f9980-bec0-11ea-8cff-bc14d2fa2f33.png)

Son datos de ayer.

**Comment by dna33** [comment]
Hola, ya está corregido, gracias por reportar @Jorgecibia @elaval @frmco
