### ISSUE TITLE
Producto 37 Defunciones_deis_T.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#432]
Hola, Columnas en algunas filas con formatos decimal distinto de la otras, se sugiere dejar sin punto decimal para facilitar carga en excel como numérico. 

![Captura de Pantalla 2020-07-06 a la(s) 00 07 22](https://user-images.githubusercontent.com/67611445/86554939-fb0acd00-bf1c-11ea-8cbb-b4375b18e674.png)
![Captura de Pantalla 2020-07-06 a la(s) 00 07 41](https://user-images.githubusercontent.com/67611445/86554942-fc3bfa00-bf1c-11ea-8af1-bbed558eda84.png)

. 
Gracias

**Comment by fzmolina** [comment]
arreglado
