### ISSUE TITLE
producto 19

### ISSUE THREAD

**Issue by robdi123** [MinCiencia/Datos-COVID19#44]
esta correcto el producto 19? los numeros no calzan

**Comment by ivanMSC** [comment]
@robdi123  Qué no calza?

**Comment by robdi123** [comment]
la suma de las comunas da un valor de 2790, cuando el total de casos activos a esas fechas debería estar en 5000 y tantos. o me equivoco con la interpretación del documento?

**Comment by arielhernandezcl** [comment]
Los totales cuadran con respecto a los publicados en el informe epidemiológico de los dias 13 y 15
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto19/CasosActivosPorComuna.csv

**Comment by robdi123** [comment]
no entiendo los datos... gracias de todas formas.

**Comment by arielhernandezcl** [comment]
@robdi123 
![totales](https://user-images.githubusercontent.com/63879018/79613444-89b14000-80cc-11ea-9f6a-69a34dc7bb08.png)

**Comment by robdi123** [comment]
si, la tabla la entiendo, que no calza es el numero, si bien el reporte epidimologico muestra lo mismo, el numero de activos debiese estar en el orden de los 5000 y no de los 2000 y tantos que ahi se muestran... no creo que sean 3000 casos fantasma, por lo que creo que el indice hace referencia a otra cosa.

**Comment by MinCiencia** [comment]
Los números vienen de MINSAL ambos, en el caso comunal vienen desde la investigación epidemiológica, que se hace una vez confirmado un caso, en consideración de la fecha de inicio de sus síntomas. La reportada diariamente a nivel nacional resulta de restar a los confirmados, las personas que no presentan síntomas luego de 14 días del diagnóstico y los fallecidos.

**Comment by ivanMSC** [comment]
@MinCiencia a ver... explicate mejor que no dijiste nada. Y cuida el uso de la puntuación.

**Comment by arielhernandezcl** [comment]
@robdi123 si tienes razon, discrepa la información del reporte con el informe, el dia 15 los casos activos deberian ser 5242 y es por lo siguiente:

de la tabla de donde obtuvieron los datos en el informe indica:

Se contabilizan todos los casos con información completa de comuna de residencia y semana epidemiológica de confirmación. **Datos faltantes se excluyen del análisis.**

por lo cual no indica el total de casos activos @MinCiencia 

![informe](https://user-images.githubusercontent.com/63879018/79616079-25917a80-80d2-11ea-979b-61b478b85df4.png)

**Comment by ivanMSC** [comment]
Más de la mitad de las personas infectadas no se sabe de qué comuna son. 
Excelente! Me parece brillante! Un 7!

**Comment by robdi123** [comment]
increible...

**Comment by MinCiencia** [comment]
Como ya explicamos arriba, son dos cifras distintas que hasta el momento se reportan con el mismo nombre. Probablemente se corrija ese error en el nombre en el próximo informe de epidemiología. Vamos denuevo con mejor puntuación, como nos sugiere @ivanMSC: 1) la cifra a nivel comunal es el resultado de la investigación epidemiológica y considera activos a las personas durante 14 días desde *la fecha de inicio de sus síntomas*, 2) la cifra nacional considera activos a personas durante 14 días desde *la fecha de diagnóstico* que no han fallecido. Por eso es mayor el reporte en el caso diario, como se puede intuir por el resto de los datos que se publican por parte de MINSAL y en este repositorio, si se conoce la residencia de los casos. Invito amablemente a comentar con respeto, el trabajo que hacemos acá lo hacemos tratando de contribuir, esperamos un comportamiento similar. Muchas gracias.

**Comment by ivanMSC** [comment]
Gracias por la explicación. Y mis disculpas. El Minsal me exacerba. Prometo comportarme.
