### ISSUE TITLE
Horas de actualizaciones

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#447]
Hola, buenas tardes. Quería consultar a qué hora suelen actualizar los reportes los días sábado y domingo... Creo aprox. a las 14, ¿no?... Gracias.
¡Saludos y gracias nuevamente por su trabajo! :)

**Comment by MinCiencia** [comment]
Hola, depende de las vocerías diarias, habitualmente son durante la mañana, pero estas últimas semanas han estado fuera de Santiago y se retrasan.
