### ISSUE TITLE
Quillota en cuarentena

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#448]
Nos llegó un correo reportando que Quillota esta cuarentena, y no en los geojson. Nos ayudas @Leandermen ?

**Comment by Leandermen** [comment]
Quillota efectivamente está en cuarentena y está visible en los registros de cuarentena activa (ID 94) y el GeoJson.

![image](https://user-images.githubusercontent.com/6208975/87379803-1732ed80-c55f-11ea-879f-de4bdbdcd6e5.png)

![image](https://user-images.githubusercontent.com/6208975/87379837-274acd00-c55f-11ea-86c5-ffe704fba9dc.png)

**Comment by scornejob** [comment]
Mil gracias @Leandermen!
