### ISSUE TITLE
Cuarentenas indefinidas

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#449]
Hola @Leandermen ,

Nos reportaron que hay cuarentenas indefinidas en varias comunas, y parece que en los geojson todos estan con fecha de termino, pero no estoy seguro. Nos puedes confirmar?

![image](https://user-images.githubusercontent.com/13997504/87234816-d7270b80-c3a2-11ea-84fb-d4465cf96c60.png)

**Comment by Leandermen** [comment]
Estimado.

Si bien es cierto las cuarentenas son de caracter "indefinido", en conformidad con lo decretado con la autoridad sanitaria si tienen una fecha que es renovable la cual es decretada en las Res.Ex. del MINSAL cada vez que se renueva la cuarentena.

En estas Resoluciones se especifica la fecha y hora de duración de las cuarentenas.
https://www.diariooficial.interior.gob.cl/publicaciones/2020/07/10/42702/01/1784251.pdf

![image](https://user-images.githubusercontent.com/6208975/87375946-768dff00-c559-11ea-9741-ea3a4a4df8b2.png)

Es por esa razón que presentan fecha de termino pese a ser "indefinidas"

**Comment by scornejob** [comment]
Un millón de gracias @Leandermen
