### ISSUE TITLE
PRODUCTO 13 y PRODUCTO 3, 17/06/2020

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#450]
Estimad@s, buenas. Deseo hallar solución al siguiente inconveniente.
Hace un mes que vengo trabajando con el [PRODUCTO 13](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto13) para obtener los datos de los casos nuevos en Tarapaca día a día y hasta hoy, no me había planteado obtenerlos a partir de los acumulados, para ello utilicé el [PRODUCTO 3](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto3). 
Los datos concuerdan en casi todas las cifras, sin embargo, un día en particular hay una diferencia enorme (no sé si tendrá que ver con los casos que no estaban considerados y luego se añadieron).
Este día corresponde al 17 de junio. Les adjunto una imagen.
![image](https://user-images.githubusercontent.com/63689583/87258719-c2667880-c473-11ea-9104-033124e45f56.png)
En esa imagen comparo ambas series de datos y claro, ese día en específico los números no cuadran.
El problema es que deseaba calcular los activos y en razón de que el PRODUCTO 13 me arroja 6839 casos totales y el PRODUCTO 3 me arroja los que hoy se comunican (7147 casos totales) no sé con cuál realizar el cálculo.

Una duda final, me gustaría saber cómo calculan los recuperados... En mi caso particular los calculo por aquellos que se infectaron hace 14 días menos los fallecidos del día de hoy.

Espero puedan responder y muchas gracias de antemano.
Saludos y gracias nuevamente por su trabajo.

**Comment by ivanMSC** [comment]
14 días desde la fis

**Comment by adinamarca** [comment]
Estimad@s, ¿alguien que pueda responder?, aún espero por favor...

**Comment by MinCiencia** [comment]
Hola, puedes usar el producto 45 para revisar, los casos que se agregaron ese día -acorde a la vocería del Ministerio de Salud en aquella oportunidad- corresponden a no notificados y probables.

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto45
