### ISSUE TITLE
Omisión de ciertas comunas en el producto  DP32 - Defunciones en Chile 

### ISSUE THREAD

**Issue by JoseUlloaD** [MinCiencia/Datos-COVID19#451]
Estimad@s, 
Falta en este producto agregar las siguientes comunas:

Sierra Gorda(2103), Santo Domingo(5606), Palmilla(6306), Laguna Blanca(12102), Rio Verde(12103), San Gregorio,(12104) Antartica,(12202) Timaukel(12303).

Saludos,

gracias por vuestro trabajo

**Comment by scornejob** [comment]
Gracias @JoseUlloaD 
Los datos que reportamos aca son los que nos entrega el registro civil, y reporta datos para 338 comunas:
```
$ cat Defunciones_std.csv | awk '{FS=","; print $3}' | sort | uniq | wc -l
338
```

**Comment by JoseUlloaD** [comment]
Gracias @scornejob
