### ISSUE TITLE
Producto32/2020-Defunciones.csv

### ISSUE THREAD

**Issue by EdlongR** [MinCiencia/Datos-COVID19#455]
Qué sucede con los datos. 
Ya vamos en el tercer dia sin ellos.
Se agradece un update

**Comment by scornejob** [comment]
@EdlongR lo que pasó fue un cambio en el endpoint de la API del registro civil. Acabamos de actualizar para ponernos al día, en https://github.com/MinCiencia/Datos-COVID19/pull/456
