### ISSUE TITLE
Diferencia de cerca de 900% en fallecidos en 24 horas en documento CasosConfirmadosTotales.csv

### ISSUE THREAD

**Issue by dhinojosac** [MinCiencia/Datos-COVID19#458]
Como se explica la gran diferencia en 24 horas de 1057 fallecidos en 24 horas?

![image](https://user-images.githubusercontent.com/5265771/87806381-c94f0b80-c824-11ea-966e-0c74813345ea.png)

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/457#issue-659333204
