### ISSUE TITLE
Producto 37 Defunciones_deis_T.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#465]
1. No está dato de desglose por día de Fallecidos Sospechosos del reporte epidemiológico 34 del 17/Jul, entendí que se actualizaría semanalmente por cada reporte, como lo harán ?

2.Cuando actualizan el desglose por día de los fallecidos confirmados con PCR positivo, es diario o semanal ?

Gracias

**Comment by MinCiencia** [comment]
Hola, teníamos un error en la etiqueta de los datos, que corregimos, en consecuencia sobre 1) se actualizará una fila o columna (en el tranapuesto) con los datos publicados de sospechosos por DEIS, una vez por semana. 2) Los fallecidos confirmados se actualizarán diariamente.

**Comment by Jorgecibia** [comment]
Ok, listo, muchas gracias
