### ISSUE TITLE
QUE SUCEDE REGISTROS MALOS

### ISSUE THREAD

**Issue by miguelcarvajala** [MinCiencia/Datos-COVID19#47]
Si el objetivo es restarle credibilidad a su información o página creo lo están haciendo de maravilla. Sus datos en estos 5 últimos registros ya no resultan confiables, favor revisen. Lastima el nivel de manejo de datos

**Comment by MinCiencia** [comment]
Hola @miguelcarvajala, a qué registros te refieres?

**Comment by MinCiencia** [comment]
Vamos a cerrar este, por ausencia de respuesta. Se agradecen los comentarios pero una crítica constructiva debería permitir mejorar, esto no sirve mucho.
