### ISSUE TITLE
Actualización de productos 40-42

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#470]
Hola, ¿hay alguna posibilidad de actualizar los datos que se presentan en los productos:

- [Transporte aéreo de pasajeros semanal](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto40)
- [Transacciones Bip!](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto41)
- [Viajes diarios por comuna en Transporte Público](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto42)?

Al menos en el de transporte aéreo sale que la actualización sería semanal y en los otros que sería entre 2-4 semanas. La última actualización fue la primera, hace más de un mes y los datos contenidos son hasta mayo en el caso del transporte público y la primera semana de junio en el transporte aéreo.

Muchas gracias por su trabajo, saludos.

**Comment by scornejob** [comment]
Hola @paarriagadap, 

Transporte aereo se actualizara los domingos a las 6:00.

Estamos trabajando para definir los mecanismos para actualizar los otros dos productos.

**Comment by paarriagadap** [comment]
Muchas gracias
