### ISSUE TITLE
Actualización Producto33

### ISSUE THREAD

**Issue by pabloazurduy** [MinCiencia/Datos-COVID19#473]
Hola, 
Hay alguna posibilidad de actualizar la data de [Producto33](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto33)? (actualmente tiene 14 días de desfase)
Saludos !

**Comment by fzmolina** [comment]
Hola @pabloazurduy ,

El producto 33 es una contribución con la Universidad del Desarrollo. En el readme se muestra que la actualización es mensual. Los datos se disponen tan pronto la UDD los genera y comunica.

Saludos!

**Comment by pabloazurduy** [comment]
muchas gracias @fzmolina , pensé que tenía una latencia menor. un saludo !

**Comment by fzmolina** [comment]
Hola de nuevo! @pabloazurduy 

Justo nos llegó una actualización de este producto. Ya puedes consultarlo :). Gracias por seguir el track.
