### ISSUE TITLE
Split series en producto 37

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#475]
El producto 37 tiene dos series:
Una que da cuenta de las defunciones sospechosas de ser casos de covid19, y otra de confirmados, etiquetados como publicacion. En realidad, ese campo da cuenta de la serie y la fecha de publicacion, por lo que lo abriremos en esos dos campos, modificando el producto como se ve en https://github.com/MinCiencia/Datos-COVID19/tree/p37-split

**Comment by ctroncoso** [comment]
Excelente. Me causó unos "fail", pero es como lo estábamos procesando. split("_")
