### ISSUE TITLE
Datos inconsistentes en los productos 1, 2, 4, 5, 6 y 11

### ISSUE THREAD

**Issue by jtapiath-cl** [MinCiencia/Datos-COVID19#478]
Los productos de datos 1, 2, 4, 5, 6 y 11 presentan algunas inconsistencias que pediría se aclararan:
* El producto 11 está actualizado **sólo hasta junio**
* El producto 6 excluye los datos de comunas no identificadas, que sí incluyen los productos 1 y 2.
* La agregación de los productos 1 y 2 (siendo idénticas entre ellas), a nivel regional, no coincide con la agregación del producto 4 al mismo nivel.
* La agregación a nivel nacional del producto 4 no es equivalente a los datos entregados en el producto 5. La máxima diferencia encontrada es de 336 mil casos, en favor de la agregación regional.

El detalle de los cálculos realizados se puede encontrar en 
[01-revisando_datos_regionales.pdf](https://github.com/MinCiencia/Datos-COVID19/files/4963598/01-revisando_datos_regionales.pdf); el código completo se puede encontrar en el siguiente repositorio: [jtapiath-cl/analisis_covid](https://github.com/jtapiath-cl/analisis_covid).

Espero las diferencias sean reconciliables y se deban a errores de cálculo, y no a errores de código en la fuente y falta de QA sobre los productos de datos.

**Comment by MinCiencia** [comment]
Hola @jtapiath-cl, gracias por el análisis. Sin embargo lo que encuentra no se debe a errores o falta de QA. Tienes que fijarte en la documentación de los productos, las distintas fuentes y las definiciones que se encuentran ahí explican lo que identificas como inconsistencias, que en realidad corresponde a la naturaleza de esos datos y a que no van a calzar, simplemente, uno es podríamos decir "una foto diaria", mientras otro es "una foto de la epidemia"

De todas maneras te explicamos acá: El producto 1 y 2 viene del informe epidemiológico mientras el producto 4 viene del reporte diario. En el reporte diario el Ministerio de Salud da cuenta de lo que ocurre en el día, con la mejor información disponible al momento del reporte, mientras el informe epidemilogico entrega cada 2 semanas cifras que se van acercando a la realidad de lo que ocurrió todos los días, a medida que progresa el proceso de vigilancia epidemiológica. Puedes analizar los productos 15, o el producto 45, viendo la evolución en el tiempo de los registros. También puedes encontrar algo similar en la evolución de los registros de defunciones, para comprender cómo opera el sistema de información del Ministerio de Salud.

Sobre el producto 6 y el 11, son productos contribuidos, en su documentación también puedes ver los autores y me parece puedes hacerles llegar también tu comentario.

**Comment by jtapiath-cl** [comment]
Gracias @MinCiencia por la explicación. Revisando la documentación y los datos, y *de cara a la opinión pública*, cómo se reconcilian los datos? Es decir, cuál es la ***información oficial***? Qué considero como datos epidemiológicos para realizar análisis y otras acciones, o es a gusto del analista?

Gracias por sus respuestas.

**Comment by MinCiencia** [comment]
Depende del análisis que quieras hacer, ambas son cifras oficiales. Si buscas realizar un análisis de lo que realmente pasó un día determinado, o un periodo respecto de casos totales, los activos u otro, sugiero utilizar los productos cuyas fuentes son informe epidemiológico, pues van acercándose a la "verdad" a medida que la vigilancia epidemiológica que hacen va progresando. Pero por otro lado, re pongo un ejemplo: si quieres hacer un análisis sobre la precisión de las cifras informadas diariamente por la autoridad, tienes que usar ambas fuentes, ¿se entiende?

El punto es entender la complejidad de cada una. Nosotros entendemos nuestro trabajo como ayudar a clarificar dudas. Asi que adelante con cualquiera otra que tengas.

**Comment by jtapiath-cl** [comment]
Gracias por sus comentarios.
