### ISSUE TITLE
producto 1 con errores

### ISSUE THREAD

**Issue by robdi123** [MinCiencia/Datos-COVID19#48]
hay comunas que pasaron a tener menos casos en un reporte incremental...

hay varios en la Araucania, como Villarrica o Victoria. hay alguna razon?

**Comment by ivanMSC** [comment]
Se corrige la comuna de residencia.

**Comment by robdi123** [comment]
gracias.

**Comment by MinCiencia** [comment]
Así es, gracias @ivanMSC. Cuando se confirma un caso el departamento de epidemiología del MINSAL investiga sobre él, la fecha de inicio de sus síntomas, su residencia, la fuente del contagio, entre otras cosas. En ese proceso a veces se corrigen datos como la comuna de residencia.
