### ISSUE TITLE
Dudas sobre el conteo total vs casos nuevos diarios (Producto 4)

### ISSUE THREAD

**Issue by NJEREZL** [MinCiencia/Datos-COVID19#481]
Estimados, a partir del 16 de Julio he detectado algunos detalles con respecto a las variables confirmados totales versus casos nuevos, pero tal como comento en el título quiero dejarlo como una duda porque tal vez mi problema es que estoy ignorando alguna variable.

Entiendo que los casos confirmados a una fecha corresponden a los casos confirmados el día anterior + los casos nuevos que se detectaron en dicho día. Esta regla se me cumple en todas las fechas y regiones del 4to producto excepto en 2 periodos:

1) el 17 de Junio en donde se añadieron 31 mil casos no contabilizados, por lo cual no hay nada que decir con respecto a ello, se entiende que no calcen.
2) Desde el 16 de Julio a la fecha, inclusive hoy 25 de Julio.

Las variaciones van desde 1 caso hasta 144 como la máxima diferencia que he encontrado, la cual la detecté en la región de Valparaiso precisamente el 16 de Julio, en donde reportan 196 casos nuevos, dejando en teoría un total acumulado de 15212 y no de 15068 como se reporta . Dejo los links de los reportes en ambos días para que lo puedan chequear:
- https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-07-15-CasosConfirmados-totalRegional.csv
- https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-07-16-CasosConfirmados-totalRegional.csv

El día de hoy en la región del biobio ayer se contabilizaron en total 10165 acumulados, el 25 de julio se detectaron 183 casos nuevos, lo que dejaría un total de 10348 y no de 10371 como indican. Dejo los link de ambos días:
- https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-07-24-CasosConfirmados-totalRegional.csv
- https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto4/2020-07-25-CasosConfirmados-totalRegional.csv

Hay otras regiones y fechas en donde ocurre esta situación, pero al aparecer de forma secuencial desde el 16 de julio puede significar que estoy ignorando algo.

Muchas gracias!!!

**Comment by MinCiencia** [comment]
Estábamos publicando esto, justamente:

https://github.com/MinCiencia/Datos-COVID19/issues/482

**Comment by NJEREZL** [comment]
Muchas gracias por aclararlo!
