### ISSUE TITLE
Ajustes a totales - Ministerio de Salud

### ISSUE THREAD

**Issue by MinCiencia** [MinCiencia/Datos-COVID19#482]
Acorde a lo indicado por el Ministerio de Salud, el acumulado total de casos COVID-19 se basa en todas las notificaciones validadas o en proceso de validación (se excluyen las eliminadas y no válidas) asociadas a un resultado positivo para la PCR, y también incluye los casos con PCR positivos sin una notificación asociada. Para estos últimos casos, se asignan según la región y fecha de toma de muestra.

Diariamente, el acumulado de casos de un día es contrastado con el acumulado de casos del día anterior y con la base consolidada de registros de laboratorio para identificar los casos nuevos con PCR positiva de las últimas 24 hrs. Este ejercicio refleja no sólo los casos nuevos que ingresan diariamente al conteo, sino también el movimiento que manifiestan los casos al comparar el acumulado de casos entre un día y otro. Esta dinámica que experimentan los casos del día anterior se explica por las siguientes razones:

- Casos presentes en el acumulado del día anterior que en el día actual no figuran. Corresponden a notificaciones que fueron eliminadas o dejadas en estado “no válidas” por el delegado de epidemiología del establecimiento que notificó el caso, o bien, por la propia SEREMI de Salud. Las razones de lo anterior se deben a notificaciones duplicadas, triplicadas o con mayor número de copias (en una misma región o entre regiones), notificaciones con información errónea, o casos que no correspondían haber sido notificados.
- Casos no notificados que fueron atribuidos a la región de toma de muestra en el reporte del día anterior, y que en las últimas 24-48 hrs fueron notificados en una región distinta.   
- Rectificación de resultados de PCR por parte de los laboratorios, o bien, de la región de toma de muestra de esos registros.

A raíz de lo anterior, se realizaron ajustes en el acumulado de casos regionales para dar cuenta del movimiento de casos mencionado anteriormente. Es importante recalcar que, este ajuste NO AFECTA EL CONTEO DE CASOS NUEVOS QUE SE REALIZA DIARIAMENTE. El detalle de los ajustes realizados en los casos acumulados diarios se resume como:

1. El 16 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 323698, considerando un ajuste de 18 casos más, aparte de los casos nuevos totales reportados ese día
2. El 17 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 326539, considerando un ajuste de 1 caso más, aparte de los casos nuevos totales reportados ese día
3. El 18 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 328846, considerando un ajuste de 122 casos más. aparte de los casos nuevos totales reportados ese día
4. El 19 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 330930, considerando un ajuste de 2 casos más, aparte de los casos nuevos totales reportados ese día
5. El 21 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 334683, considerando un ajuste de 2 casos menos, aparte de los casos nuevos totales reportados ese día
6. El 22 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 336402, considerando un ajuste de 22 casos menos, aparte de los casos nuevos totales reportados ese día
7. El 23 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 338759, considerando un ajuste de 14 casos menos que los casos nuevos totales reportados ese día
8. El 25 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 343592, considerando un ajuste de 1 caso más que los casos nuevos totales reportados ese día
9. El 28 de Julio 2020, los ‘casos totales acumulados’ reportados fueron 349800, considerando un ajuste de 1 caso más que los casos nuevos totales reportados ese día
10. El 29 de Julio 2020, los 'casos acumulados totales' reportados fueron 351575, considerando un ajuste de 2 casos mas que los  casos nuevos totales reportados ese día
11. El 30-07-2020 los 'casos totales acumulados' reportados fueron 353536 considerando un ajuste de 13 casos más que los casos nuevos totales reportados ese día
12. El 31-07-2020 los 'casos totales acumulados' reportados fueron 355667 considerando un ajuste de 8 casos más que los casos nuevos totales reportados ese día
13. El 04-08-2020 los 'casos totales acumulados' reportados fueron 362962 considerando un ajuste de 7 casos más que los casos nuevos totales reportados ese día
14. El 06-08-2020 los 'casos totales acumulados' reportados fueron 366671 considerando un ajuste de 1 casos más que los casos nuevos totales reportados ese día
15. El 07-08-2020 los 'casos totales acumulados' reportados fueron 368825 considerando un ajuste de 5 casos más que los casos nuevos totales reportados ese día.
16. El 08-08-2020 los 'casos totales acumulados' reportados fueron 371023 considerando un ajuste de 3 casos menos que los casos nuevos totales reportados ese día
17. El 09-08-2020 los 'casos totales acumulados' reportados fueron 373056 considerando un ajuste de 3 casos menos que los casos nuevos totales reportados ese día
18. El 11-08-2020 los 'casos totales acumulados' reportados fueron 376616 considerando un ajuste de 6 casos más que los casos nuevos totales reportados ese día
19. El 12-08-2020 los 'casos totales acumulados' reportados fueron 378168 considerando un ajuste de 12 casos más que los casos nuevos totales reportados ese día
20. El 13-08-2020 los 'casos totales acumulados' reportados fueron 380034 considerando un ajuste de 14 casos más que los casos nuevos totales reportados ese día
21. El 15-08-2020 los 'casos totales acumulados' reportados fueron 383902 considerando un ajuste de 14 casos más que los casos nuevos totales reportados ese día
22. El 16-08-2020 los 'casos totales acumulados' reportados fueron 385946 considerando un ajuste de 42 casos menos que los casos nuevos totales reportados ese día
23. El 18-08-2020 los 'casos totales acumulados' reportados fueron 388855 considerando un ajuste de 17 casos más que los casos nuevos totales reportados ese día
24. El 19-08-2020 los 'Casos totales acumulados' reportados fueron 390037 considerando un ajuste de 51 casos menos que los casos nuevos totales reportados ese día
25. El 20-08-2020 los 'casos totales acumulados' reportados fueron 391849 considerando un ajuste de 1 casos menos que los casos nuevos totales reportados ese día
26. El 22-08-2020 los 'casos totales acumulados' reportados fueron 395708 considerando un ajuste de 13 casos más que los casos nuevos totales reportados ese día
27. El 23-08-2020 los 'casos totales acumulados' reportados fueron 397665 considerando un ajuste de 15 casos más que los casos nuevos totales reportados ese día
28. El 25-08-2020 los 'casos totales acumulados' reportados fueron 400985 considerando un ajuste de 11 casos más que los casos nuevos totales reportados ese día
29. El 26-08-2020 los 'casos totales acumulados' reportados fueron 402365 considerando un ajuste de 9 casos más que los casos nuevos totales reportados ese día
30. El 27-08-2020 los 'casos totales acumulados' reportados fueron 404102 considerando un ajuste de 2 casos menos que los casos nuevos totales reportados ese día
31. El 28-08-2020 los 'casos totales acumulados' reportados fueron 405972 considerando un ajuste de 2 casos más que los casos nuevos totales reportados ese día
32. El 29-08-2020 los 'casos totales acumulados' reportados fueron 408009 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
33. El 30-08-2020 los 'casos totales acumulados' reportados fueron 409974 considerando un ajuste de 1 casos menos que los casos nuevos totales reportados ese día
34. El 31-08-2020 los 'casos totales acumulados' reportados fueron 411726 considerando un ajuste de 1 casos menos que los casos nuevos totales reportados ese día
35. El 01-09-2020 los 'casos totales acumulados' reportados fueron 413145 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
36. El 02-09-2020 los 'casos totales acumulados' reportados fueron 414739 considerando un ajuste de 12 casos más que los casos nuevos totales reportados ese día
37. El 03-09-2020 los 'casos totales acumulados' reportados fueron 416501 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
38. El 04-09-2020 los 'casos totales acumulados' reportados fueron 418469 considerando un ajuste de 3 casos más que los casos nuevos totales reportados ese día
39. El 05-09-2020 los 'casos totales acumulados' reportados fueron 420434 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
40. El 06-09-2020 los 'casos totales acumulados' reportados fueron 422510 considerando un ajuste de 1 casos menos que los casos nuevos totales reportados ese día
41. El 08-09-2020 los 'casos totales acumulados' reportados fueron 425541 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
42. El 09-09-2020 los 'casos totales acumulados' reportados fueron 427027 considerando un ajuste de 4 casos más que los casos nuevos totales reportados ese día
43. El 10-09-2020 los 'casos totales acumulados' reportados fueron 428669 considerando un ajuste de 3 casos más que los casos nuevos totales reportados ese día

**Comment by klieb12** [comment]
hay diferencia en los numeros de activos informados en región de O'higgins (vs. los datos que informa el GORE Ohiggins -diferencia por mucho-
