### ISSUE TITLE
Comunas Total Incremental - Datos-COVID19/output/producto1/Covid-19_T.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#492]
Fila 40 correspondiente al 20/jul presenta datos no incrementales, casos totales son menores al dato anterior (17/jul), en Región Valparaíso: Concón, Limache, Quillota, Quilpué, Valparaíso, Villa Alemana y Viña del Mar
![Captura de Pantalla 2020-07-29 a la(s) 01 53 30](https://user-images.githubusercontent.com/67611445/88762171-a84cbb80-d13e-11ea-9398-eaecf67036e3.png)
![Captura de Pantalla 2020-07-29 a la(s) 01 53 44](https://user-images.githubusercontent.com/67611445/88762174-a97de880-d13e-11ea-90a0-a43775fd5d57.png)
![Captura de Pantalla 2020-07-29 a la(s) 01 53 57](https://user-images.githubusercontent.com/67611445/88762176-a97de880-d13e-11ea-9244-0daa634165e0.png)
![Captura de Pantalla 2020-07-29 a la(s) 01 54 17](https://user-images.githubusercontent.com/67611445/88762177-aa167f00-d13e-11ea-915e-2dd722917f88.png)

**Comment by MinCiencia** [comment]
Hola @Jorgecibia, en algunos casos ocurre que las personas rectifican o actualizan su domicilio, generando una disminución para una comuna dada.

**Comment by Jorgecibia** [comment]
Ok, gracias, pero si alguien se enferma en valparaíso y después se cambia de comuna no se debiera cambiar el registro de casos de valparaiso, no entiendo como lo hacen, sin duda es complejo.  gracias

**Comment by MinCiencia** [comment]
Hola, le sugerimos haga lectura de las páginas 5 a 8 del informe epidemiológico que publica el Ministerio de Salud de Chile, que va en su trigésimo séptima edición. En estas páginas se puede ud. informar del proceso de vigilancia epidemiológica, y por qué se hace cómo se hace.

Le dejamos el link:

https://www.minsal.cl/wp-content/uploads/2020/07/Informe-EPI-27.07.20-final_RA.pdf
