### ISSUE TITLE
Total Nacional Incremental Diario - Datos-COVID19/output/producto5/TotalesNacionales_T.csv

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#494]
Hoy se reportan CASOS TOTALES 351.575, ayer 349.800, la diferencia es de 1.775 sin embargo casos nuevos se reportan en 1.773, hay una diferencia de 2 casos. Favor aclarar si hay algo que no estoy considerando, ? Gracias
![Captura de Pantalla 2020-07-29 a la(s) 14 11 10](https://user-images.githubusercontent.com/67611445/88837093-bbdf3d00-d1a5-11ea-8398-814a935c622c.png), adjunto cuadro hasta el 24/juk con diferencia que calcule del mismo tipo. 
![Captura de Pantalla 2020-07-29 a la(s) 14 16 02](https://user-images.githubusercontent.com/67611445/88837318-1e383d80-d1a6-11ea-82ec-377c1b60a3ba.png)

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/482

**Comment by Jorgecibia** [comment]
Gracias, pero podría ser un a repùesta que me oriente mas, verifique la documentación del producto y no encuentro algo que se asocie con la explicación de las diferencias, Gracias

**Comment by MinCiencia** [comment]
Nos referíamos a que revises este issue que se refiere específicamente al tema y tiene todos los detalles que creemos requieres, por favor: https://github.com/MinCiencia/Datos-COVID19/issues/482

**Comment by Jorgecibia** [comment]
Perfecto, me queda claro, muchas gracias
