### ISSUE TITLE
Actualización muertes DEIS 29 de julio

### ISSUE THREAD

**Issue by jorgeperezrojas** [MinCiencia/Datos-COVID19#495]
Hola,

Vi que no tienen actualizado aun el producto 37. Solo son 4 fechas las que cambian así que la actualización es pequeña. Estos son los datos. Saludos

```
23/07	48
24/07	59
25/07	36
26/07	3
27/07	0
```

**Comment by scornejob** [comment]
Gracias @jorgeperezrojas . No puedo encontrar el archivo en el DEIS. Por completitud, nos puedes compartir el link para obtenerlo?

**Comment by scornejob** [comment]
Borre mi comentario respecto al archivo, ya lo encontramos.

**Comment by scornejob** [comment]
Acabamos de actualizarlo. Gracias @jorgeperezrojas por el aviso.

**Comment by MinCiencia** [comment]
Gracias, @jorgeperezrojas.
