### ISSUE TITLE
Producto 37 

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#497]
Donde se están publicando los Fallecidos SOSPECHOSOS DEIS, del Reporte Epidemiológico,  no encuentro la distribución por dia que antes se publicaba en este producto (están hasta el 18/Jul).  Gracias

**Comment by scornejob** [comment]
Hola @Jorgecibia:
Efectivamente, algo pasó con el archivo. Lo acabamos de regenerar, e investigaremos que pasó con el que había.

**Comment by scornejob** [comment]
Al revisar el log del archivo, veo que ese registro nunca llegó al repositorio, y gracias a este reporte, nos pusimos al día.

**Comment by Jorgecibia** [comment]
Muchas gracias, slds
