### ISSUE TITLE
error Covid-19.csv

### ISSUE THREAD

**Issue by Stephenscts** [MinCiencia/Datos-COVID19#50]
en la filas de Panguipulli y Rio bueno  (región de Los Ríos) para el día 13.

**Comment by fzmolina** [comment]
Hola Stephenscts. Ese valor es el valor reportado por MINSAL, reporte epidemiológico del día 2020-04-13

**Comment by Stephenscts** [comment]
2020-04-13 los datos no corresponden con los informados por la seremi de salud, puedes observar aquello al final de la tabla. 

http://seremi14.redsalud.gob.cl/seremi-de-salud-confirma-tres-nuevos-casos-de-covid-19-en-los-rios-2/

ademas están los del día 12 
http://seremi14.redsalud.gob.cl/seremi-de-salud-confirma-un-fallecido-y-cinco-nuevos-casos-de-covid-19-en-los-rios/

**Comment by MinCiencia** [comment]
Hola @Stephenscts, hay discrepancias que en este caso se explican porque se corrigen las comunas de residencia de las personas en el curso de la investigación epidemiológica que se hace una vez confirmado el caso.
