### ISSUE TITLE
Actualización Sospechosos DEIS (Producto 37)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#500]
Hoy publicaron el tableau actualizado del DEIS sospechosos y confirmados al 30 julio, por ello en el producto 37 falta el actualizado de los sospechosos respectivamente. saludos

**Comment by MinCiencia** [comment]
Hola @dafernandez75, se encuentra actualizado ahora. Saludos.

**Comment by dafernandez75** [comment]
Muchas gracias, Saludos.
