### ISSUE TITLE
DP17 "Total Informado Ultimo Día"

### ISSUE THREAD

**Issue by worldofvitox** [MinCiencia/Datos-COVID19#504]
hola!

solo para reportar que el valor para 2 agosto se repite para 3 de agosto en la última columna.

**Comment by scornejob** [comment]
gracias @worldofvitox.Lo corregiremos cuando publiquemos los datos de hoy.

**Comment by scornejob** [comment]
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto17/PCREstablecimiento.csv
