### ISSUE TITLE
Se repite fallecidos confirmados producto37 con respecto día anterior

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#505]
Hola, Se repite fallecidos confirmados producto37 con respecto día anterior, favor corregir.

**Comment by scornejob** [comment]
Gracias @dafernandez75 . Hubo un error en la fuente de datos, nos entregaron una version actualizada, y nosotros acabamos de actualizar.

**Comment by dafernandez75** [comment]
ok. Saludos
