### ISSUE TITLE
Producto 1 y 19 con datos duplicados en última actualización 

### ISSUE THREAD

**Issue by villaseca** [MinCiencia/Datos-COVID19#509]
No revisé más productos, pero podría haber ocurrido también.

![image](https://user-images.githubusercontent.com/3867311/89420962-7240a600-d701-11ea-9c5e-afb81e6b9469.png)

**Comment by Jorgecibia** [comment]
producto38/CasosFallecidosPorComuna_T.csv   también esta duplicadas dos últimas filas

**Comment by scornejob** [comment]
Estamos al tanto: https://github.com/MinCiencia/Datos-COVID19/issues/510
