### ISSUE TITLE
nuevos casos por comuna 03Marzo - 29Marzo

### ISSUE THREAD

**Issue by jpvillanuevac** [MinCiencia/Datos-COVID19#51]
Hola,

Es posible obtener los datos historicos por comuna entre el 3 de marzo y 29 de marzo? 

El producto 1 esta incompleto si empieza el 30 de marzo.

gracias.

**Comment by ivanMSC** [comment]
https://github.com/ivanMSC/COVID19_Chile#datos-hist%C3%B3ricos-y-actualizaciones-diarias

**Comment by jpvillanuevac** [comment]
Hola Ivan,

Gracias por el link. 

he estado siguiendo tu repositorio y es fantástico. pero creo que hemos hecho el mismo diagnóstico en un punto: no hay datos históricos para la región metropolitana. 

Esto datos son importantes, y no entiendo por qué no han sido publicados. Tienes alguna idea_

saludos,
JP

**Comment by ivanMSC** [comment]
@jpvillanuevac  Antes del 18 de marzo, los datos que tenemos son del centro de salud y no de la comuna de residencia por lo que el hoyo en la data es gigante.

**Comment by jpvillanuevac** [comment]
Ups! 

Si entiendo bien, las comunas que reportas en la carpeta "old" en tu repositorio corresponden a las comunas en las que se encuentra el centro medico que confirmó el caso.  Correcto?

Si es asi, concuerdo contigo.  Realmente hay un gran hoyo en la data a nivel comunal.

@MinCiencia será posible conseguir los datos de marzo para la RM a nivel comunal? - Sin ellos tenemos menos de la mitad de la historia...

Gracias.

**Comment by ivanMSC** [comment]
> Si entiendo bien, las comunas que reportas en la carpeta "old" en tu repositorio corresponden a las comunas en las que se encuentra el centro medico que confirmó el caso. Correcto?

Correcto
