### ISSUE TITLE
Falta información entre 20 Julio y 30 Julio

### ISSUE THREAD

**Issue by Alonso9123** [MinCiencia/Datos-COVID19#511]
Con la ultima actualización de información se perdio la data entre el 20 y el 30 de julio a nivel de totales por comuna.

**Comment by scornejob** [comment]
hola @Alonso9123 . Nos especificas en que producto falta informacion?

**Comment by Alonso9123** [comment]
Hola @scornejob, 

Me paso con el CSV de datos totales incrementales por comuna " Datos-COVID19/output/producto1/Covid-19.csv "

![image](https://user-images.githubusercontent.com/69255739/89436469-47ac1880-d714-11ea-82ea-5e72afee0ad8.png)

**Comment by scornejob** [comment]
Gracias. Acabamos de identificar el problema: los archivos base que usamos para generar los productos fueron de un commit muy antiguo. Ya estan esos datos disponibles.

**Comment by Nonima** [comment]
Hola buenas, iba a reportar lo mismo con el data product 19, pero acabo de revisar y ya fue corregido. Mil gracias!
