### ISSUE TITLE
Actualización PRODUCTO 48

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#512]
Hola, buenas estimad@s. El producto 48 lleva una semana sin actualizar... Quería consultar cuándo lo harán (dado que su frecuencia de actualización especifica de 4 a 5 días). Desde ya, ¡gracias por su gran trabajo!
[PRODUCTO 48](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto48)

**Comment by villaseca** [comment]
Hola @adinamarca, yo soy el encargado de disponibilizar estos datos desde la Fundación Ciencia y Vida hacia MinCiencia. 

Debido a la gran cantidad de trabajo que ha tenido SOCHIMI estos meses, están tardando más de lo previsto en enviar los reportes. Justo hoy nos llegaron los 4 últimos reportes, que si te fijas ya están disponibles en el repositorio.

Con el equipo, estamos evaluando cambiar la frecuencia de actualización para no generar falsas expectativas. Apenas tengamos una buena estimación notificaremos este cambio.

**Comment by scornejob** [comment]
Gracias @villaseca !
