### ISSUE TITLE
Producto39 totales por cada fecha inicio síntomas, no cuadran con el total Inf.EPI (confirmado+no notificado+probable) 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#513]
Hola,
En Producto39 que acaban de actualizar algunos de los totales por columna "fecha inicio síntomas" no cuadran con el total según Inf.EPI nro.29 (confirmado+no notificado+probable). 
Fechas en que las cantidades no cuadran con el total Informe EPI (confirmado+no notificado+probable):
28-02
02-03 al 09-03
11-03 al 15-03
17-03
21-03 al 22-03
09-04
'sin fecha' (Ref.informe EPI nro.39), se indica en informe EPI cantidad 1 en "No notificada" (fecha inicio síntomas)). 

Nota: Con respecto a los totales respectivos de la columna fecha notificación no los revise.

Desconozco la razón del porqué los están sumando, deberían mantenerlos desagregados tal como en el informe EPI.

Saludos.

**Comment by dafernandez75** [comment]
fe de errata: en 3ra línea, donde indiqué Inf.EPI nro.29 debe decir nro.39.

**Comment by scornejob** [comment]
gracias @dafernandez75 . Estamos trabajando para actualizar esos datos cuanto antes.

**Comment by dafernandez75** [comment]
Hola, al revisar el prod39, nuevamente pasa lo mismo reportado (sigo hilo #513) y OJO en las mismas posiciones (fechas). 

Según informe 40 EPI, fecha inicio síntomas da como total 411.948 (confirmado+no notificado+probable) , con respecto al Prod39 que totaliza fecha inicio de síntomas con 410.873, siendo la diferencia -1.075, prácticamente la misma diferencia con respecto el Informe EPI anterior -1.074. Saludos

**Comment by dafernandez75** [comment]
se agrega #526

**Comment by dafernandez75** [comment]
Nuevamente se arrastra error en totales Fecha Inicio Síntomas con respecto al Informe EPI 42 publicado en el día de hoy, en las mismas fechas antes señaladas. 

Totales Informe EPI 42 Fecha Inicio Síntomas (Confirmada+No Confirmados+Probable) 428.679 con respecto a los totales registrados en Producto39 Fecha Inicio Síntomas 427.094, Diferencia -1.585.

**Comment by dafernandez75** [comment]
Nuevamente se arrastra error en totales Fecha Inicio Síntomas con respecto al Informe EPI 43 ya publicado, en las mismas fechas antes señaladas.

Totales Informe EPI 43 Fecha Inicio Síntomas (Confirmada+No Confirmados+Probable) 434.900 con respecto a los totales registrados en Producto39 Fecha Inicio Síntomas 433.319, Diferencia -1.581.
