### ISSUE TITLE
Exámenes pendientes

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#514]
Hola estimad@s. Tengo una nueva consulta.
Por casualidad, ¿hay alguna idea de la cantidad de exámenes pendientes por región?, creo sería interesante disponer de dicha cifra.
Gracias.
Saludos.

**Comment by ctroncoso** [comment]
Sería el producto 45, [Caso no notificado por comuna](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto45)

**Comment by adinamarca** [comment]
> Sería el producto 45, [Caso no notificado por comuna](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto45)

Me refiero a los exámenes PCR sin análisis, que creo, dispone cada Seremi. En Tarapacá al menos, hasta la fecha, hay 398 exámenes pendientes y es un dato que se actualiza de manera diaria...

Igual, ¡gracias por la respuesta!

**Comment by MinCiencia** [comment]
Hola @adinamarca, publicamos recientemente por contribución de la fundación ciencia y vida los indicadores asociados a trazabilidad y testeo, productos 63 a 67.
