### ISSUE TITLE
Nuevo foro para hablar de Datos-covid19 en DISCORD, para despejar los issues de github.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#516]
Estimad@s, veo que se ha estado usando los issues como un método de conversación y consultas, mas que para levantar errores, fallas o mejoras. 
Para esto, y para dessaturar esta zona, creamos un servidor Discord para poder hablar y debatir respecto a data covid, tanto de este repositorio como otros que estén disponibles para Chile y el mundo. 
A los que quieran unirse, son bienvenidos incluso si es solo para leer. 

**El link de invitación es: https://discord.gg/4S9wB2b**

Por supuesto, los moderadores y administradores de este repositorio están mas que invitados a participar.

**Comment by MinCiencia** [comment]
Muchas gracias, han habido muchas intervenciones apropiadas, y ocurre que se van cerrando a medida que se resuelven. Quizás podrían estar atentos e enviar links a las respuestas de este repositorio, en tanto son respuestas oficiales del ministerio de ciencia sobre las preguntas que nos hacen, cuando las tenemos o podemos coordinar.

Saludos.
