### ISSUE TITLE
Producto 33 Indice de Movilidad Desordenados

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#519]
Los datos expresado en los csv del producto 33 , están desordenado en cuanto a fechas. ¿es posible dar solución a esto?

**Comment by scornejob** [comment]
Hola @ekos77 . Ordenar los productos es una tarea que preferimos dejar a los consumidores, dado que los intereses difieren (hay gente que podría requerir un orden territorial o alfabético, por mencionar un ejemplo). En ese sentido, el orden que ves, es el orden con que recibimos los registros. Por lo tanto, no los ordenaremos.
Por otra parte, si deseas hacer un pull request ordenando los registro con otro criterio, es bienvenido.
