### ISSUE TITLE
Error en total de casos recuperados 20-abril

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#52]
La información oficial de minsal es de 4676 casos recuperados según el último informe diario publicado en https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/20.04.2020_Reporte_Covid19.pdf
El número queda validado por el número de casos activos y el gráfico que muestra la misma información.

Sugiero hacer el scraping a partir de estos reportes diarios en pdf en lugar de la página https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/ que es conocida por tener errores y demoras en la actualización.

![image](https://user-images.githubusercontent.com/35350256/79782584-57425580-830d-11ea-816d-02b85394a9ae.png)

**Comment by ivanMSC** [comment]
Otra fuente: https://twitter.com/ministeriosalud/status/1252246579798396928

**Comment by MinCiencia** [comment]
gracias, lo corregimos.
