### ISSUE TITLE
Producto 45, historia incompleta

### ISSUE THREAD

**Issue by gomena** [MinCiencia/Datos-COVID19#522]
Hola quería plantear que los datos históricos de del producto 45 están incompletos, sólo hay reportes desde el 28 de junio.
Esto es problemático porque si uno quiere mirar más atrás entonces hay que usar el producto 15, pero debido al problema de los "Casos perdidos" de mediados de junio, es imposible determinar si los que se mencionan como "confirmados" pueden ser en verdad no notificados o probables.

Saludos
Gonzalo

**Comment by MinCiencia** [comment]
En los nuevos productos 61 y  62 se encuentra la historia completa desagregada por día, desde el inicio de la pandemia por fecha de notificación y por fecha de inicio de síntomas respectivamente. Esperamos te sea útil.
