### ISSUE TITLE
producto37, a fallecidos confirmados les falta 1, según reporte 10.139, acá 10.138. 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#523]
Hola,
En producto37, a fallecidos confirmados les falta 1, según reporte 10.139, acá 10.138. 
Saludos.

**Comment by Jorgecibia** [comment]
Hola, a yo detecte lo mismo, gracias, quedamos atentos

**Comment by dafernandez75** [comment]
inclusive en la gráfica del reporte del sitioweb, tbn al descargar los datos está con 10.138.

**Comment by MinCiencia** [comment]
Hola, gracias por reportar. Nos indican que es un caso fallecido del cuál no se tiene información sobre la fecha de defunción, por eso la diferencia.

**Comment by dafernandez75** [comment]
pero deberían colocarlo como "sin fecha" dentro de los confirmados.

**Comment by Jorgecibia** [comment]
Hola Gracias, respecto a la situación, que el caso no esté registrado con fecha, hay que buscar algún criterio que no afecte el análisis histórico de casos, quizá no informar, dejarlo como sospechoso en la fecha que se detecte u otro criterio que no afecte el análisis comparativo o histórico, quizá la mesa de datos puede apoyar en definir criterios para varias situaciones que existen como los ajustes diarios, o los casos incrementales que bajan entre un reporte y otro, etc.  Gracias por la aclaración

**Comment by scornejob** [comment]
Hemos agregado el caso tal como lo reporta DEIS: "en verificacion"
