### ISSUE TITLE
Producto39 totales por cada fecha inicio síntomas, "Nuevamente" no cuadra con el total Inf.EPI (confirmado+no notificado+probable)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#526]
Hola,
En los últ 3 Informes EPI y para las mismas fechas, el Producto 39 actualizado de hoy (fecha inicio síntomas) no cuadra con los totales del  Inf. EPI (confirmado+no notificado+probable). Esto lo había reportado para los 2 informes anteriores en #513, en donde se mantiene la misma diferencia total faltante [1074= 419.269 (Inf.EPI41) - 418.195 (Prod39)].

**Comment by scornejob** [comment]
duplicado en https://github.com/MinCiencia/Datos-COVID19/issues/513
