### ISSUE TITLE
Totales Nacionales: error en recuperados y casos activos 20/04

### ISSUE THREAD

**Issue by IPF94** [MinCiencia/Datos-COVID19#53]
En los totales nacionales del 20 de abril deberían haber 4676 recuperados y 5692 casos activos.

https://cdn.digital.gob.cl/public_files/Campa%C3%B1as/Corona-Virus/Reportes/20.04.2020_Reporte_Covid19.pdf

**Comment by MinCiencia** [comment]
Corregido, muchas gracias!

**Comment by IPF94** [comment]
Hola, todavía falta corregir la cantidad de recuperados (no en recuperados.csv, sino que en TotalesNacionales.csv: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto5/TotalesNacionales.csv).
Para el 20 de abril aparecen 4476, pero son 4676.

**Comment by MinCiencia** [comment]
Gracias por reportar.

**Comment by MinCiencia** [comment]
Gracias por reportar.
