### ISSUE TITLE
Producto 29 - Fecha final cuarentenas

### ISSUE THREAD

**Issue by NJEREZL** [MinCiencia/Datos-COVID19#531]
Hola, en el producto 29 han desaparecido la fecha del término de varias cuarentenas que ya son históricas pero que debido a ese detalle aparecen como activas. Saludos!

**Comment by scornejob** [comment]
@Leandermen , nos puedes ayudar con este issue?

**Comment by scornejob** [comment]
En seguimiento en https://github.com/MinCiencia/Datos-COVID19/issues/537
