### ISSUE TITLE
Producto 50: Frecuencia de actualización

### ISSUE THREAD

**Issue by villaseca** [MinCiencia/Datos-COVID19#533]
Estimados, veo que la frecuencia de actualización de este producto es semanal, pero han pasado 3 semanas desde su última actualización. ¿Podrían entregarnos más información al respecto?

Muchas gracias!

**Comment by paarriagadap** [comment]
Venía a escribir lo mismo. Es información muy útil que sirve para ver el impacto real de la pandemia desagregado por comunas.

**Comment by paarriagadap** [comment]
Hola, es posible tener una actualización más frecuente de este archivo? Veo además que también se ha incluido el Producto 61, que me parece que apunta a lo mismo. Seguirán sólo con ese?

**Comment by villaseca** [comment]
Hola @cjag20! Podrían volver a actualizar este producto por favor? :pray:

**Comment by dna33** [comment]
Hola, está actualizado desde ahora acorde a la última publicación del DEIS (2020-12-31)
