### ISSUE TITLE
Producto 29: Frecuencia Actualización : Se necesita ayuda

### ISSUE THREAD

**Issue by Sergio-P** [MinCiencia/Datos-COVID19#537]
Hola, en el producto 29 se indica que la frecuencia de actualización son los días miércoles y viernes de cada semana. Sin embargo, actualmente este producto no ha sido actualizado en 15 días, previo a esto también habían pasado cerca de dos semanas sin actualizarse. Pueden por favor revisar esto? En particular dependo de este producto para crear visualizaciones.

**Comment by scornejob** [comment]
Hola @Sergio-P . El producto 29 corresponde a una contribución, y efectivamente no ha recibido actualizaciones. En este sentido, sólo podemos recurrir de vuelta a la comunidad para que nos ayude.

**Comment by diegosapunar** [comment]
Hola, hay alguna informacion de poder obtener la atualizacion de este producto? Es importantisimo para mi pipeline de datos
