### ISSUE TITLE
Productos ICOVID no son replicables, método producto 53 no está documentado

### ISSUE THREAD

**Issue by gomena** [MinCiencia/Datos-COVID19#539]
Estimados, planteo estas dudas

Es difícil hacer ciencia frente a tales niveles de falta de transparencia

Saludos
Gonzalo

**Comment by gomena** [comment]
Es imposible auditar externamente la veracidad y correctitud de los datos entregados si no se muestran las verdaderas series a partir de los cuales los cálculos de producto 53 y 54 son hechos, así como los métodos y códigos al respecto.

**Comment by MinCiencia** [comment]
Hola Gonzalo, esos productos son frutos de la colaboracion que se describe en sus readme, las Universidades involu

**Comment by MinCiencia** [comment]
Esta colaboración documenta su metodología en el siguiente link: https://www.icovidchile.cl/metodologia-1
