### ISSUE TITLE
producto5 inconsistente

### ISSUE THREAD

**Issue by rodrigogalvez** [MinCiencia/Datos-COVID19#54]
Revisé las sumas básicas del producto5 y no son consistentes con los casos nuevos vs casos totales acumulados. Hay una diferenda de 1 caso el primer día y el 20 de marzo otra diferencia también de 1 caso. Obviamente se puede calcular, pero me produce desconfianza un error tan sencillo.

**Comment by fzmolina** [comment]
Hola Rodrigo,

Muchas gracias por tu reporte. Sobre el día 20 de marzo, se trató de una actualización del producto4 del 19 de marzo un caso confirmado en Arica que no se sumó a los casos totales del día. De esta manera, los casos nuevos son 104 (no 103 como estaba en el producto5).

Sobre el primer día, el caso en "casos totales" fue confirmado en días anteriores, por ello no se considera como un caso nuevo para el 3 de marzo.
