### ISSUE TITLE
DEFUNCIONES DEIS CASOS CON DIAGNÓSTICO SIN PCR 

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#543]
Datos de Reporte Epidemiológico 44 respecto a defunciones con diagnóstico y sin PCR no está cargado para producto 37 

Datos-COVID19/output/producto37/Defunciones_deis_T.csv

Gracias

**Comment by scornejob** [comment]
@Jorgecibia muchas gracias. Ayer añadimos la ultiam publicacion de serie de sospechosos, para el 2020-08-21
