### ISSUE TITLE
Producto 55 (positividad iCovid) no está actualizado con último Informe Edpidemiológico

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#546]
Los productos con fuente en iCovid parecen estar actualizados según el último informe epidemiológico, excepto el Producto 55, que no parece haberse actualizado.

![image](https://user-images.githubusercontent.com/68602/91036119-c6d69300-e5d4-11ea-98f3-d6acecf65894.png)

**Comment by scornejob** [comment]
Acabamos de actualizar los productos, pero estos se generan a partir del input que nos entrega ICOVID. El producto 55 fue actualizado por ultima vez hace 5 dias.

**Comment by scornejob** [comment]
@elaval, ICOVID nos notificó de una nueva actualización, y actualizamos de acuerdo a eso.
