### ISSUE TITLE
Falta actualización Producto 39 según Informe EPI 45.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#547]
Hola,
Falta actualización Producto 39 según Informe EPI 45. Saludos.

**Comment by scornejob** [comment]
Gracias @dafernandez75 . Acabamos de actualizar el informe EPI.

Saludos.

**Comment by dafernandez75** [comment]
Quedó faltante un caso 'sin fecha' en 'No Notificados' de 'Fecha de Inicio de Síntomas' y en 'Fecha de Notificación'.

**Comment by scornejob** [comment]
gracias @dafernandez75 . Lo acabamos de corregir.
