### ISSUE TITLE
Falta actualización Producto37, lo actualizaron recientemente pero No lo correspondiente al reporte de hoy.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#548]
Hola,
Falta actualización Producto37, lo actualizaron recientemente pero No lo correspondiente al reporte de hoy.
Saludos.

**Comment by ctroncoso** [comment]
Las fechas aparecen como "en verificación"
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto37/Defunciones_deis_std.csv

**Comment by Jorgecibia** [comment]
Hola me agrego para estar al tanto cuando se agregue el día 26/ago(hoy)  Gracias

**Comment by dafernandez75** [comment]
![Anotación 2020-08-26 133849](https://user-images.githubusercontent.com/69001461/91338272-b07e3200-e7a2-11ea-8ed6-237a999e4ee9.jpg)

**Comment by scornejob** [comment]
Gracias por el aviso @dafernandez75 . Lo acabamos de reprocesar.
