### ISSUE TITLE
Existe Repositorio nuevo reporte Testeo, Trazabilidad y Aislamiento?

### ISSUE THREAD

**Issue by oderfla1978** [MinCiencia/Datos-COVID19#549]
Quisiera saber si dentro de sus repositorios existe el que tiene relacion con el nuevo reporte que indico el ministerior, si bien encontre la fuente "Datos-COVID19/output/producto55" no refleja los mismos valores que l reporte del departamento de epidemiología; estoy buscando la positividad que converse con los valores de ese reporte.

Gracias por su ayuda

**Comment by MinCiencia** [comment]
PErdón la demora, aquí esta la información:

Data Product 63 - Número de personas notificadas con exámenes RT- PCR por Comuna: Número de personas notificadas con exámenes RT-PCR positivos. Estos valores son levantados y reportados de manera semanal por el Laboratorio de Biología Computacional de la Fundación Ciencia & Vida acorde al informe de Indicadores de Testeo y Trazabilidad publicado semanalmente por el departamento de Epidemiología. Ver más

Data Product 64 - Cantidad de Test por búsqueda activa de casos (BAC) por Comuna: Proporción de test realizados por búsqueda activa de casos sobre el total de los test realizados en las personas notificadas con resultados de laboratorio.Estos valores son levantados y reportados de manera semanal por el Laboratorio de Biología Computacional de la Fundación Ciencia & Vida acorde al informe de Indicadores de Testeo y Trazabilidad publicado semanalmente por el departamento de Epidemiología. Ver más

Data Product 65 - Indice de Positividad Test RT-PCR por Comuna: Proporción de resultados de test positivos en las personas notificadas con resultados de laboratorio. Estos valores son levantados y reportados de manera semanal por el Laboratorio de Biología Computacional de la Fundación Ciencia & Vida acorde al informe de Indicadores de Testeo y Trazabilidad publicado semanalmente por el departamento de Epidemiología. Ver más

Data Product 66 - Cobertura de testeo por Comuna: Proporción de casos nuevos notificados (sospechosos) con al menos un resultado de examen de RT-PCR. Estos valores son levantados y reportados de manera semanal por el Laboratorio de Biología Computacional de la Fundación Ciencia & Vida acorde al informe de Indicadores de Testeo y Trazabilidad publicado semanalmente por el departamento de Epidemiología. Ver más

Data Product 67 - Oportunidad en la notificación de casos nuevos por Comuna: Proporción de casos nuevos confirmados por laboratorio, que fueron notificados en la primera consulta o contacto con salud, es decir, antes del proceso de la toma de muestra. Estos valores son levantados y reportados de manera semanal por el Laboratorio de Biología Computacional de la Fundación Ciencia & Vida acorde al informe de Indicadores de Testeo y Trazabilidad publicado semanalmente por el departamento de Epidemiología. Ver más
