### ISSUE TITLE
SUGERENCIA: Incluir producto con fechas de cuarentenas por comuna

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#55]
Sugiero (y agradecería) si pueden mantener un producto con las fechas de inicio / termino de cuarentenas por comuna.

(similar a esta tabla https://github.com/elaval/covid_chile_regional/blob/master/cuarentenas.csv)

Estos datos son útiles para analizar el impacto de cuarentenas en la evolución de casos confirmados y de fallecidos

Gracias

**Comment by Leandermen** [comment]
Estimado.
Nuestro equipo está trabajando en una base de datos de cuarentenas con georreferenciación, actualmente estamos pronto a lanzarla en nuestro portal https://covid19.soporta.cl/ y queremos disponerlos en formato GeoJson, en la base actual tenemos un producto informativo que es el visor de cuarentenas activas que lo estamos actualizando con las nuevas cuarentenas

https://soportachile.maps.arcgis.com/apps/opsdashboard/index.html#/6d03fef7ffff4c7cbd11ef1e192e6bf2

**Comment by MinCiencia** [comment]
Estamos revisando la contribución que hicieron @Leandermen , muchas gracias.

**Comment by ivanMSC** [comment]
@Leandermen como se diferencia eso del mapa que ya está en la pagina del ministerio?

**Comment by Leandermen** [comment]
@ivanMSC la base de datos de cuarentenas se diferencia en dos puntos. El primero es que, a diferencia del mapa del ministerio, no solo tiene cuarentenas vigentes sino tambien históricas (para análisis temporal) las cuales el ministerio va quitando. Y en segundo lugar se trabaja sobre la base dibujada pero tambien el propósito es refinar la base de datos con elementos mas detallados de cartografia. Revisando los polígonos estan en algunos casos con errores de dibujo, por ejemplo, la cuarentena de san pedro de la paz en su limite llega hasta coronel. No tienen una cartografia previa de referencia (suponemos que se dibuja a mano alzada) por lo que buscamos homologarla a fuentes oficiales como los planos de detalle de las jedena si existen, informacion del minvu sobre areas urbanas y esperamos compararlas a futuro con otros elementos como limites urbanos en especial cuando se decreta cuarentena solo para el area urbana.
Finalmente como se incluye en el pull request posee una base de datos con atributos para categorizar las zonas e incluir detalles que actualmente mantenemos en nuestro equipo.
