### ISSUE TITLE
Falta actualización en Producto 37, para los U072 Sospechosos según Informe EPI 46.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#550]
Hola,
Falta actualización en Producto 37, para los U072 Sospechosos según Informe EPI 46.
Saludos.

**Comment by Jorgecibia** [comment]
A la espera, se repite situación de no actualizar este dato. gracias

**Comment by scornejob** [comment]
hola @dafernandez75 . Acabamos de actualizar el producto 46 con la serie de sospechosos.

**Comment by dafernandez75** [comment]
Está aún pendiente el 'Producto37' con los U072 (sospechosos).

**Comment by scornejob** [comment]
Si, en rigor eso aun no lo publicamos. Lo haremos junto con el reporte diario de hoy.

**Comment by dafernandez75** [comment]
Hola, corregir fechas al actualizado de hoy...

**Comment by Jorgecibia** [comment]
Quedaron fechas futuras del 2020 en sospechosos

**Comment by scornejob** [comment]
El producto fue publicado. Lo de las fechas erroneas lo seguimos en https://github.com/MinCiencia/Datos-COVID19/issues/555
