### ISSUE TITLE
Indispensable que se clasifiquen las muertes por causa de acuerdo al CIE 10

### ISSUE THREAD

**Issue by guillermoburr** [MinCiencia/Datos-COVID19#552]
Indispensable que se clasifiquen las muertes por causa de acuerdo al CIE 10

**Comment by ctroncoso** [comment]
Esa info la puedes encontrar en gran detalle aquí 
[DEIS-Defunciones por causa de muerte 2016-2020 (Actualización semanal)](https://deis.minsal.cl/#datosabiertos)
