### ISSUE TITLE
ndiceDeMovilidad.csv Added data from UDD to repo 4 days ago IndiceDeMovilidad_std.csv

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#553]
El producto 33 en los formatos:
IndiceDeMovilidad_std.csv
IndiceDeMovilidad.csv
tienen fechas repetidas, específicamente la fecha 2020-08-23

**Comment by scornejob** [comment]
Duplicado en https://github.com/MinCiencia/Datos-COVID19/issues/554
