### ISSUE TITLE
Fechas repetidas del producto 33 (2020-08-23)

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#554]
El producto 33 en los formatos:
IndiceDeMovilidad_std.csv
IndiceDeMovilidad.csv
tienen fechas repetidas, específicamente la fecha 2020-08-23

**Comment by scornejob** [comment]
Gracias @ekos77 
Lo que ocurrio es que hubo un addendum, dado que los datos entregados en un aprimera instancia estaban incompletos. Acabamos de borrar los datos incompletos, y de regenerar los productos.
