### ISSUE TITLE
Producto 37 con fechas erróneas

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#555]
Hola! En la actualización de las defunciones del Producto 37 aparecen defunciones en los meses de septiembre, octubre, noviembre y diciembre.

**Comment by Jorgecibia** [comment]
Hay fechas futuras del 2020 para sospechosos

**Comment by scornejob** [comment]
Gracias. Estamos investigando que ocurrió.

**Comment by scornejob** [comment]
Hubo  un problema en cuanto pandas reconocio meses y dias intercambiados. Ya esta solucionado.
