### ISSUE TITLE
Producto37 sin actualizar

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#556]
Hola,
Con respecto a otros productos ya actualizados (2 hrs atrás), el producto 37 aún está sin actualizar según reporte del Minsal del día de hoy.

**Comment by scornejob** [comment]
Gracias @dafernandez75 . Acabamos de actualizarlo.

**Comment by scornejob** [comment]
por que la atomicidad de github esta basada en commits.
lo que ocurrio es que cuando hice el commit de los inputs de hoy (que comprenden lo del reporte diario + p36 y 47), lo hice al nivel de los inputs del reporte diario. Me di cuenta cuando hice el push a este repo.
En ese momento, generé los productos 36 y 47 localmente en mi maquina, e iba a esperar que termine el procesamiento del reporte diario para alinear mi branch contra este. Pero la memoria fue fragil, y se me fue hasta que vi tu issue.
