### ISSUE TITLE
Casos activos regionales producto 4 inconsistente con Informe Epidemiológico

### ISSUE THREAD

**Issue by nibravo** [MinCiencia/Datos-COVID19#558]
Saludos,

El producto 4 entrega desde el 21/6 la cantidad de casos activos regionales, pero al comparar este número con el entregado por el informe epidemiológico existe una gran inconsistencia.

Por ejemplo Tarapacá para el 30/08 el informe entrega una cantidad de activos de 627, pero el producto 4 solo 443 (Casos activos confirmados). Intenté sumarle los 191 Casos activos Probables, pero esto entrega un valor de 634, lo cual aunque cercano, sigue siendo inconsistente con el informe.

Existe una manera de obtener exactamente el dato de casos activos regionales entregado por el informe epidemiológico?

Muchas gracias de antemano

**Comment by dna33** [comment]
Como indica el readme.md del producto que aludes, este tiene por fuente el reporte diario. En el reporte diario no se incluyen los casos no notificados y probables, que si aparecen en el informe epi. Por eso la diferencia. 

Si existe una manera, sumando los casos activos por comuna que se reportan en el mismo informe epi.

**Comment by jtapiath-cl** [comment]
Yo reporté inconsistencias en los distintos productos de datos que se disponibilizan ([issue-478](https://github.com/MinCiencia/Datos-COVID19/issues/478)), y la respuesta fue "las fuentes son distintas". Me parece de una gravedad extrema que se entreguen a la comunidad datos inconsistentes, pero al menos podemos indicar luces sobre ello.

**Comment by MinCiencia** [comment]
Se insiste en el punto, que las fuentes sean distintas y que está bien fundamentado por qué las cifras son distintas, basta leer la documentación. En este repositorio se hace un esfuerzo por disponer datos de diveras fuentes que se han considerado relevantes para enfrentar y comprender la pandemia, nos parece bueno tener fuentes distintas y  explicar bien las diferencias que no catalogamos como inconsistencias.
