### ISSUE TITLE
Falta actualización Producto39 (Obs: Informe EPI °48 eliminó Anexo Fecha Inicio Síntomas)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#561]
Hola,
Falta actualización Producto39 Fecha Inicio Síntomas / Fecha Notificación [confirmado, no notificado, probable]. 
En Informe EPI ° 48 publicado hoy, no viene!!!.

Saludos.

**Comment by scornejob** [comment]
@dafernandez75 , yo veo el producto actualizado: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto39/NotificacionInicioSintomas_std.csv

Hay algo incorrecto en lo que estoy viendo?

**Comment by dafernandez75** [comment]
Cuando levante en su momento el Issue no estaba actualizado el producto39.
