### ISSUE TITLE
Producto 32 (Muertos Registro Civil) no actualiza desde 9-sept-2020

### ISSUE THREAD

**Issue by isoto2020** [MinCiencia/Datos-COVID19#573]
En la documentación dice que la actualización es cada una hora o diaria (según el archivo) pero viendo los datos, el registro más reciente es del 9 de septiembre de 2020.

**Comment by scornejob** [comment]
gracias @isoto2020 . El problema es que la API de registro civil dejó de responder. Revisaremos que ocurrio.

**Comment by scornejob** [comment]
Parece ser que hubo una interrupcion en el servicio, y ya esta respondiendo de nuevo.
