### ISSUE TITLE
Fechas mal capturadas en Producto 40

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#574]
Hola, en el Producto 40, de transporte aéreo, algunas fechas parecen haberse capturado erróneamente, debido a que ahora se encuentran registros de octubre de este año.

Saludos,

**Comment by scornejob** [comment]
El problema esta en la API: para agosto responde con los dias y meses cambiados:
`
{'anio': '2020', 'mes': '8', 'semana': '32', 'inicioSemana': '08-03-2020', 'finsemana': '08-09-2020', 'origen': 'Temuco', 'destino': 'Santiago', 'operaciones': '4.0', 'pasajeros': '273.0'}`

**Comment by scornejob** [comment]
Recien hice push del fix, con el producto corregido.
