### ISSUE TITLE
No se ha realizado Actualización de los Productos 13,37 ?, Informe Reporte Minsal 14 sep ya subido.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#575]
Hola,
No se ha realizado Actualización de los Productos: 13, 37 ?, Ref. Informe Reporte Minsal 14 sep ya subido.

saludos.

**Comment by Jorgecibia** [comment]
Tienen algún estándar de cuanto tiempo despues se actualizan los datos o dependen de factores ajenos ?, si es asi, seria bueno poner algún banner en el sitio de los datos, si hay problemas, gracias

**Comment by scornejob** [comment]
gracias @dafernandez75 , @Jorgecibia 

Acabo de hacer el push para procesar los datos.

**Comment by dafernandez75** [comment]
ok gracias. me sumo a la pregunta de @Jorgecibia , ya que a veces suben la actualización antes, durante, después del reporte. A qué hora tienen establecido la actualización de los productos?.

**Comment by scornejob** [comment]
cercano a la publicacion de los datos por parte del Ministerio de Salud

**Comment by Jorgecibia** [comment]
Gracias, cercano para mi son menos de 30¨

**Comment by scornejob** [comment]
> Gracias, cercano para mi son menos de 30¨

Dejemoslo en no tan cercano entonces :)

**Comment by Jorgecibia** [comment]
podrían definir un  SLA,  no se cuanta gente está esperando, pero si es un servicio de disponibilización de datos seria bueno tenerlo.  Gracias por responder y el trabajo. saludos
