### ISSUE TITLE
PRODUCTO 36 - Faltan usuarios en residencias

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#578]
¡Hola!, esperando hayan tenido buenas fiestas patrias.
Desde ayer, en el [PRODUCTO 36](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto36) no hay ningún dato de ayer y hoy para los usuarios en residencias.
Gracias.

**Comment by scornejob** [comment]
Gracias!

El problema fur que cambiaron el nombre de una columna en la tabal en el reporte.
