### ISSUE TITLE
Falta actualización Producto39, según Informe EPI 52.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#580]
Hola,
Falta actualización Producto39, según Informe EPI 52.

Saludos.

**Comment by ivanMSC** [comment]
@dafernandez75 el informe 52 salio hace como media hora. podriai esperarte un poquito, comerte un anticucho qué se yo y de ahi ver si postear un issue.

**Comment by scornejob** [comment]
acabamos de generar los productos de informe epidemiologico.

**Comment by Jorgecibia** [comment]
Gracias, faltan los sospechosos DEIS n producto 37
