### ISSUE TITLE
Actualización Producto 37 con Fallecidos Sospechosos DEIS REPORTE EPI-52

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#582]
Hola, falta actualizar producto con la distribución diaria de fallecidos sospechosos reportados por DEIS en Reporte Epidemiológico 52 del 19/Sep.  Gracias

**Comment by fzmolina** [comment]
Estimado @Jorgecibia ,

El producto 37 no se actualiza con fuente del informe Epidemiológico, sino con la actualización del DEIS que se realiza cada sábado y la fecha que se encuentra en los archivos correspondientes del DP37

<img width="246" alt="Screen Shot 2020-09-20 at 20 20 41" src="https://user-images.githubusercontent.com/13983083/93724632-3eb9be00-fb7f-11ea-827c-72e787c8d3c7.png">

Por otro lado, el informe epidemiológico 52 tiene fecha de publicación el 18 de Septiembre, no el 19 como apuntas

<img width="430" alt="Screen Shot 2020-09-20 at 20 20 53" src="https://user-images.githubusercontent.com/13983083/93724649-5f821380-fb7f-11ea-9c58-194fe9f7b58c.png">

Saludos

**Comment by Jorgecibia** [comment]
Gracias, disculpa, fue mi error, no vi la columna. estaba actualizado.  mis disculpas nuevamente y gracias
