### ISSUE TITLE
Sugerencia: Fecha de Resultado PCR

### ISSUE THREAD

**Issue by maurijoe** [MinCiencia/Datos-COVID19#59]
Para poder realizar trazabilidad de N° de Casos Nuevos vs Resultado de PCR, favor si pueden ingresar la fecha de los resultados de PCR o alguna planilla en que los N° de Casos Nuevos para una fecha determinada sean acorde a la fecha de resultado PCR. 

Con la información actual entregada de N° exámenes PCR y N° de Casos Nuevos, para un día X cualquiera, no es posible realizar trazabilidad, dado que los Casos Nuevos pueden ser fácilmente de un resultado de un PCR tomado hace 8-9 días atrás. 

Gracias

**Comment by estebaniglesias** [comment]
Hola! Me gustaría saber lo mismo. En los informes del Minsal se habla de una estadística de "tests informados en las últimas 24 horas". Son tests que se informaron positivo/negativo esa misma fecha?
Porque de ser así, no habría problema para la trazabilidad @maurijoe . De hecho, con https://github.com/YachayData/COVID-19 estuvimos analizando correlación entre el número de casos informados y positivos

![Screenshot 2020-05-04 09 12 20](https://user-images.githubusercontent.com/2274485/80969199-3ab31c80-8de7-11ea-94e9-344e3ad76c7e.png)

Obtuvimos correlación de un 73% con un valor p de 0,0000927 (ver publicación [aquí](https://www.instagram.com/p/B_vsGCJDQS5/))

Tenemos toda la impresión que el informe de la cantidad de test tiene el mismo desface que el informe de los casos positivos. 

**Alguien podría confirmar esto? O sabe dónde lo podríamos confirmar?** Gracias

**Comment by estebaniglesias** [comment]
@MinCiencia

**Comment by MinCiencia** [comment]
Es como indica @estebaniglesias, disculpen la demora en contestar.
