### ISSUE TITLE
Datos faltantes en Producto65 PositividadPor Comuna

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#594]
En producto 65 los datos de positividad por comuna aparecen en blanco para algunas comunas en ciertas fechas.

Por ejemplo, Antofagasta el 28 de Septiembre de 2020
![image](https://user-images.githubusercontent.com/68602/94989148-f0c29400-0548-11eb-86c8-b599147b1be6.png)

Estos datos sí están disponibles en el informe de indicadores TTA
![image](https://user-images.githubusercontent.com/68602/94989179-32533f00-0549-11eb-882a-41391c800613.png)

Fuente consultada
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto65/PositividadPorComuna.csv

**Comment by MinCiencia** [comment]
Puedes hacer un PR con las correcciones correspondientes, o también le podemos pedir apoyo a @fzmolina.

Gracias!

**Comment by fzmolina** [comment]
Estimado @elaval,

Muchas gracias por reportar el dato faltante. El dato de la comuna de Antofagasta fue corregido. El dato faltante de la comuna de Colchane en Tarapacá no está reportado, por eso no corresponde ninguna acción de nuestra parte.

Saludos,
Faviola
