### ISSUE TITLE
Producto37, con la actualización hay muchas diferencias con respecto al de ayer.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#595]
Hola, 

Al revisar producto37, existen muchas diferencias con respecto al de ayer.
Solo 10 días mantienen sus valores (total 194 días)
Con respecto la total está bien 12.919, pero con respecto a su distribución debe haber algún error. 

Saludos.

**Comment by dafernandez75** [comment]
Si se fijan, bastaría solo correr valores hacia abajo y cuadra, en fechas 22 y 24 marzo.
Me explico: en fecha 22 y 24 marzo dejar valor en 0, y ultima fecha debe ser 30 septiembre, ya que siempre tenemos 3 días desfase.

**Comment by ctroncoso** [comment]
Estas fueron las modificaciones respecto al de ayer.
https://github.com/MinCiencia/Datos-COVID19/commit/036fd9ea420cfca686da4d5aa8d49fb41bf68b44#diff-065f7e46e64257af2d8f7b32344c0468

Se cambiaron de posición 2 líneas (no creo que afecte)
Se anexaron los confirmados del 3-oct. 

Respecto a cual de los 3 archivos te refieres?

**Comment by dafernandez75** [comment]
Defunciones_deis.csv
Defunciones_deis_T.csv

el total acumulado no afecta pero su distribución en las fechas si afecta.

**Comment by ctroncoso** [comment]
lo podemos ver en discord?... no lo pillo, pero creo que te sigo la idea... a ver si pillamos el error. Quiero ir revisando los diff. 

> Defunciones_deis.csv
> Defunciones_deis_T.csv
> 
> el total acumulado no afecta pero su distribución en las fechas si afecta.

**Comment by dafernandez75** [comment]
ok.

**Comment by ctroncoso** [comment]
@scornejob 
Daniel encontró un desfase hoy. Se produce con dos ceros (0) que no se incluyen en el output del producto 37.
![image](https://user-images.githubusercontent.com/121016/94998551-ed4efd00-0588-11eb-8359-e3fb209335bc.png)

Creo que tengo al culpable. 
Hay datos con 0 y otros vacíos (nan). Creo que habría que normalizarlo antes del proceso. 
https://github.com/MinCiencia/Datos-COVID19/blob/master/input/NuevaDefDefunciones/DefuncionesDEIS.csv

![image](https://user-images.githubusercontent.com/121016/94998437-3783ae80-0588-11eb-85d4-1a8d8f60af9c.png)

**Comment by scornejob** [comment]
Gracias @ctroncoso  y @dafernandez75 . Yo pienso que puedo hacer un pr esta tarde o noche. Si alguno de ustedes lo puede hacer antes sería genial.

**Comment by ctroncoso** [comment]
Veré si le puedo dar una mirada. Tengo que trazar el proceso hacia atrás primero.. wish me luck! 

> Gracias @ctroncoso y @dafernandez75 . Yo pienso que puedo hacer un pr esta tarde o noche. Si alguno de ustedes lo puede hacer antes sería genial.

**Comment by MinCiencia** [comment]
Terminando el informe epi de hoy, a ver si lo alcanzamos a ver antes. Muchas a gracias a todos.

**Comment by scornejob** [comment]
El problema radica en que hay dos dias sin datos: 22 y 24 de Marzo.
