### ISSUE TITLE
Falta actualización producto37 con los Sospechosos U072 y los U071 ya publicados en reportes.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#597]
Hola,

Falta actualización producto37 con los Sospechosos U072 y la distribución de los U071 ya reportados.

Saludos.

**Comment by Jorgecibia** [comment]
Si falta actualización al día 4/oct de fallecidos con PCR + y sospechosos por día incluidos en Anexo informe semanal Defunciones por Covid-19 del Reporte Epidemiológico 56

**Comment by fzmolina** [comment]
Estos han sido actualizados. Quisiera recordarles que tal como mis contribuciones (como colaboradora de este repo) el MinCiencia acepta las contribuciones que puedan ayudar a completar los registros

**Comment by Jorgecibia** [comment]
Gracias, aún está pendiente la distribución diaria de fallecidos sospechosos que reportó DEIS  al 2/Oct en Rep-EPI-56.
