### ISSUE TITLE
documentar producto 12 y typo en producto 24

### ISSUE THREAD

**Issue by pachamaltese** [MinCiencia/Datos-COVID19#60]
hola

el producto 24 debiera decir "integrado" y no "integegrado"

acá documenté una API que hice a partir de esto https://github.com/pachamaltese/api-covid19-datauc

**Comment by fzmolina** [comment]
Hola Pacha,

Muchas gracias por tu reporte, hemos corregido el producto24. Además, se agregó un readme dentro del producto12

**Comment by pachamaltese** [comment]
X cierto, la API está andando en coronavirus-api.mat.uc.cl
