### ISSUE TITLE
Serie histórica de la situación comunal, plan paso a paso

### ISSUE THREAD

**Issue by damorend** [MinCiencia/Datos-COVID19#601]
Hola, en https://www.gob.cl/coronavirus/pasoapaso/, pestaña "Situación Comunal", se publica la etapa en que se encuentra cada comuna de Chile. Esta información está registrada en un formato estructurado: una planilla con la etapa correspondiente a cada una de las 345 comunas del país. Sin embargo, cada vez que se actualiza la información en la página web, se pierde el registro de las situaciones anteriores de las comunas. Dado que es un formato estándar, la información histórica debería ser muy fácil de recopilar y juntar en un solo repositorio con la etapa en que se encontraba cada comuna en cada día desde el inicio del plan Paso a Paso.

Gracias

**Comment by fzmolina** [comment]
Bienvenida sea tu contribución!

**Comment by damorend** [comment]
> Bienvenida sea tu contribución!

La información histórica debería ser muy fácil de recopilar _para los administradores de gob.cl y quienes les envían las planillas con los datos por comuna_. Yo no tengo cómo acceder a ella.

**Comment by fzmolina** [comment]
Bueno, para los administradores de gob.cl que no administran este repositorio

**Comment by dafernandez75** [comment]
algo así? Ref. https://twitter.com/kemanta       https://drive.google.com/file/d/1WieweYNSPdpmjUIyYcbKp1oaqwlnD61_/view

**Comment by damorend** [comment]
Exacto! Gracias por el aviso!

**Comment by dna33** [comment]
Hola, el nuevo producto 74 cuenta con esta información: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto74
