### ISSUE TITLE
Viajes diarios por comuna en Transporte Público

### ISSUE THREAD

**Issue by AleBarriosg** [MinCiencia/Datos-COVID19#605]
Hola a todos!. 

Tengo una consulta con respecto al producto 42. 

He notado que esta base de datos no se ha actualizado desde el 15 de mayo, habrá alguna razón de porque no se actualiza esta base? y será posible actualizarla?. Mantener actualizada esta base sería útil para hacer analíticas con modelos seir que consideren conectividad entre comunas dado que a pesar de las falencias que podría tener producto de la evasión del pago las conclusiones podrían ser buenas.

Agradezco la respuesta y dispuesta a colaborar si asi lo necesitan.

**Comment by jaimesoza** [comment]
Comento para darle más importancia a este tema. Es referido tanto al producto 41 como 42, ambos sin actividad en los últimos 7 meses, aún cuando se indicó que se actualizarían cada 2 o 4 semanas.
