### ISSUE TITLE
Falta actualización Producto37 del día de hoy, actualizaron hasta lo de ayer.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#606]
Hola,
Falta actualización Producto37 del día de hoy, actualizaron hace 2 horas hasta lo de ayer solamente.

Saludos.

**Comment by Jorgecibia** [comment]
Falta, distribución diaria al 6/Oct

Hola, ya esta ingresado, pero asi me entero de actualizacion, Gracias
