### ISSUE TITLE
Falta actualización Producto37, distribución de 61fallecidos reportados 12-oct-2020  

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#623]
Hola,
actualizaron recientemente Prod37 pero no con la distribución de los 61 fallecidos reportados hoy 12 octubre. 
Está lo de ayer no lo de hoy.

Saludos.

**Comment by ctroncoso** [comment]
Concuerdo. La diferencia con el reporte del 11, hay 47 fallecidos (45 considerando las fechas con reducción [27-28])

**Comment by Jorgecibia** [comment]
Me agrego aqui a la espera de la distribución diaria del día 12/Oct. gracias

**Comment by dafernandez75** [comment]
Actualizaron con un total de 13.396 fallecidos vs 13.379 según reporte acumulado.
qué fecha es Unnamed: 209 y Unnamed: 210 ??

**Comment by dafernandez75** [comment]
habrán adelantado lo de mañana ? , serían 17 adicionales con respecto a lo de hoy, distribuidos en los 4 días.

**Comment by dafernandez75** [comment]
Acaban de publicar el reporte de hoy 13 octubre, y coincidencia que son exactamente los 17 fallecidos con 13.396 en acumulados. 
Coincidencia? que por error publicaron en la actualización de ayer 12 octubre. 
![Captura de pantalla 2020-10-13 110522](https://user-images.githubusercontent.com/69001461/95871799-77932000-0d44-11eb-8e6f-62e2a2849dfe.jpg)

**Comment by MinCiencia** [comment]
Si, ayer actualizamos tarde y alcanzó a entrar la información que se publicaría hoy.
