### ISSUE TITLE
Producto 37 - confirmados del 16 y 17 son idénticos. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#639]
Linea 114 y 116 (16 y 17 de Oct) de Defuniones_deis.csv son idénticas.

**Comment by ctroncoso** [comment]
Agruparon 16 y 17 en el 16?

publicacion      N
2020-10-13      17.0
2020-10-14      19.0
2020-10-15      19.0
2020-10-16     154.0
2020-10-17       0.0

**Comment by dna33** [comment]
nos parece esta corregido, no?

**Comment by ctroncoso** [comment]
Old news
