### ISSUE TITLE
Falta actualización Producto 37 y Producto 13

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#643]
Hola,
Falta actualización Producto 37 Fallecidos Confirmados y Producto 13 Casos Nuevos Regionales.

Saludos.

**Comment by Jorgecibia** [comment]
No se actualizado la información con reporte de hoy 18 Oct que se entrego aprox a las 11:30, favor pueden comentar que pasa o  hora aprox de publicación. Gracias

**Comment by MinCiencia** [comment]
Actualizamos hace algunos minutos, saludos.

**Comment by Jorgecibia** [comment]
Gracias
