### ISSUE TITLE
Falta actualización Producto 37 y Producto 13, Según reporte 19 oct 2020 ya publicado hace horas...

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#645]
Hola,

Falta actualización Producto 37 y Producto 13, Según reporte 19 oct 2020 ya publicado hace horas...

Saludos.

**Comment by adinamarca** [comment]
Hola!, me añado a las palabras de @dafernandez75 ... Últimamente las cifras no se han actualizado tan regularmente como antes :(

**Comment by Jorgecibia** [comment]
Exacto, podrian avisar en la misma página o por aqui  si hay dificultad. Gracias

**Comment by dafernandez75** [comment]
ya actualizados, gracias!!!.

**Comment by Jorgecibia** [comment]
Gracias Daniel, alguna información de lo que paso, Gracias

**Comment by dafernandez75** [comment]
Ninguna información al respecto Jorge. 
Toda la info la obtengo por acá. Saludos

**Comment by Jorgecibia** [comment]
ok, gracias
