### ISSUE TITLE
Horarios de actualización

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#649]
¡Hola!, como siempre, esperando estén bien y agradeciendo su enorme trabajo, quería consultar qué suceden con los horarios de actualización (que por lo general, anteriormente eran a las 11:00 hrs - 12:00 hrs), dado que últimamente se han atrasado las actualizaciones de los productos hasta horas de la tarde.

¡Un saludo cordial!

**Comment by Jorgecibia** [comment]
Hola, Si era máximo 30" después del reporte Min Sal y ahora a aumentado, pueden contarnos, gracias

**Comment by dafernandez75** [comment]
Me sumo, no hay nada malo en señalar que no tienen recursos si ese fuese el caso, hagan un comunicado solicitando apoyo, sino como podemos ayudar.

**Comment by ctroncoso** [comment]
Si! Apoyamos en lo que se pueda.

**Comment by dafernandez75** [comment]
![Captura de pantalla 2020-10-20 152930](https://user-images.githubusercontent.com/69001461/96628808-1a214500-12e9-11eb-9d3e-4701d03b50b6.jpg)

**Comment by dafernandez75** [comment]
Estimados, acaban de actualizar!!!
Gracias.

**Comment by adinamarca** [comment]
Hoy lo mismo. :(

**Comment by dafernandez75** [comment]
toda esta semana fue así aprox 1 par de horas, la anterior excelente. Será algún turno?
