### ISSUE TITLE
PRODUCTO 3 - Faltan activos

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#653]
Hola!, buenas, [en el producto 3, totales por región](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/TotalesPorRegion.csv), faltan los activos confirmados en todas las regiones.
Gracias, saludos.

**Comment by adinamarca** [comment]
[https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/TotalesPorRegion.csv](url)

**Comment by scornejob** [comment]
Hola @adinamarca . Acabo de pushear un fix.

**Comment by adinamarca** [comment]
Genial!, muchas gracias!!
Saludos
