### ISSUE TITLE
Product 4, title with quotes and line break

### ISSUE THREAD

**Issue by frmco** [MinCiencia/Datos-COVID19#654]
On product 4, the title "Casos activos confirmados" have quotes and line break.

https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto4/2020-10-23-CasosConfirmados-totalRegional.csv

![image](https://user-images.githubusercontent.com/64239643/97039656-256fad00-1543-11eb-927e-f1c2efb4dc33.png)

**Comment by scornejob** [comment]
Thanks @frmco , I just merged https://github.com/MinCiencia/Datos-COVID19/pull/655
