### ISSUE TITLE
Error en fecha de último registro para Producto 1 (Dice 2020-10-24 y debiera ser 2020-10-23)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#658]
La actualización de datos en Producto1 corresponde al Informe Epidemiológico del 23 de Octubre (que se hace público hoy)

La serie de datos incluye registros para los días Lunes y Viernes, pero hoy se indica para un día Sábado (24 Octubre)

![image](https://user-images.githubusercontent.com/68602/97095454-ee2df880-1635-11eb-9b8f-559227505d23.png)

**Comment by ivanMSC** [comment]
Si abres el PDF publicado, tiene efectivamente fecha sábado con datos hasta viernes. Los de las semanas anteriores tenían fecha viernes con datos hasta jueves.

**Comment by fzmolina** [comment]
La fecha convenida para todos los informe epidemiológicos publicados en este repositorio es la que aparece en la portada del mismo. Que corresponde al día siguiente a la fecha de corte reportada en la página 5 del informe publicado hoy 2020-10-24
