### ISSUE TITLE
¿Cómo citar?

### ISSUE THREAD

**Issue by gobenavides** [MinCiencia/Datos-COVID19#667]
Hola. ¿Tienen algún formato de preferencia para citar este repositorio?

Saludos
Gonzalo

**Comment by jaguridi** [comment]
Hola!
No tenemos un formato en particular, pero lo relevante es que se cite al Ministerio de Ciencia, Tecnología, Conocimiento e Innovación; que se incluya el link al repositorio; y que se mencione el origen de los datos (está en los Readme de cada producto) y/o quienes los generaron (cuando son contribuciones de grupos externos).

**Comment by gobenavides** [comment]
Hola, Jorge.

Muchas gracias por responder. ¿Sería posible que me compartas ese formato particular?
