### ISSUE TITLE
Falta actualizar Producto37 con Sospechosos U072 ya publicados por el Deis.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#672]
Hola,

Falta actualizar Producto37 con Sospechosos U072 ya publicados por el Deis 4.943.-

Saludos

**Comment by dafernandez75** [comment]
Defunciones_deis.csv   Fila 138 se debe borrar, al igual que las filas 142 a la 147.

**Comment by fzmolina** [comment]
Quisiera acotar que en este repositorio se aceptan contribuciones de los usuarios, de la misma manera que lo hacemos los contribuyentes usuales
