### ISSUE TITLE
Producto37, repitieron hoy 11nov los fallecidos confirmados del 10nov.

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#676]
Hola,
En Producto37, en actualización de hoy 11nov repitieron los fallecidos confirmados del 10nov.

saludos.

**Comment by Jorgecibia** [comment]
Hola, si me sumo para estar enterado de la corrección. Gracias

**Comment by dafernandez75** [comment]
ver referencia: https://docs.google.com/spreadsheets/d/1mLx2L8nMaRZu0Sy4lyFniDewl6jDcgnxB_d0lHG-boc/edit#gid=1456422453
![Captura de pantalla 2020-11-11 191518](https://user-images.githubusercontent.com/69001461/98870669-624c0700-2452-11eb-8050-66eb2cdb94bd.jpg)

**Comment by scornejob** [comment]
gracias @dafernandez75 @Jorgecibia . Yo lo arregle en https://github.com/MinCiencia/Datos-COVID19/tree/issue676. Les agradecería si le dan una mirada.

**Comment by dafernandez75** [comment]
Ajustar fechas, se repite lo de ayer en fecha 10 y 11 noviembre, por la hora se presentan registros que seguramente serán los del reporte de mañana. Debe ser a hoy 14.633 y se indican 14.699 (+66) para mañana.

**Comment by scornejob** [comment]
"se me chispoteó" (y se me cayó el carnet también)

@dafernandez75 , le das una mirada porfi?

**Comment by Jorgecibia** [comment]
Yo veo que el archivo sigue igual, en el link que enviaste, entrando a la carpeta output y producto 37, están los datos del 10 y del 11 igual, se mantiene el día 11 sin agregar los 22 fallecidos y además hay una columna nueva del día 12 con el dato indicado por @dafernandez75 
Gracias
Aprovechó de reconocer la labor de publicación que están haciendo, un gran trabajo, felicitaciones

**Comment by scornejob** [comment]
@Jorgecibia, que commit miras?? lo ultimo que subi es https://github.com/MinCiencia/Datos-COVID19/commit/12d2e11037bc4fba0e3141921c1f8733f307cb2f

**Comment by dafernandez75** [comment]
Seba, ahora sí, dele su actualización.

**Comment by dafernandez75** [comment]
claro que dejaste pega adelantada de mañana, gracias!!!.

**Comment by Jorgecibia** [comment]
Mire ahora, y veo que siguen igual los dos días y el dia 12, te dejo prints
![Captura de Pantalla 2020-11-11 a la(s) 21 42 04](https://user-images.githubusercontent.com/67611445/98880621-e60fee80-2466-11eb-859d-5b14a6f730ab.png)
![Captura de Pantalla 2020-11-11 a la(s) 21 43 32](https://user-images.githubusercontent.com/67611445/98880657-f88a2800-2466-11eb-8ce8-5ec5f391646d.png)

**Comment by scornejob** [comment]
upsi... (no le digan a nadie, pero la voy a borrar)

**Comment by dafernandez75** [comment]
Jorge, estas viendo el producto final. Previamente Seba lo debe trabajar.

**Comment by Jorgecibia** [comment]
Si, ahora veo que esta ok, gracias
