### ISSUE TITLE
Producto 5 - datos faltantes 23 de octubre

### ISSUE THREAD

**Issue by luispsa** [MinCiencia/Datos-COVID19#680]
Hola, trabajando con este CSV:
https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto5/TotalesNacionales_T.csv

Hay datos faltantes en el día 23 de octubre (recuperados, activos, activos por FIS, recuperados por FIS, activos confirmados)

`

Casos nuevos con sintomas          1160.0
Casos totales                    498906.0
Casos recuperados                     NaN
Fallecidos                        13844.0
Casos activos                         NaN
Casos nuevos sin sintomas           584.0
Casos nuevos totales               1773.0
Casos activos por FD              21137.0
Casos activos por FIS                 NaN
Casos recuperados por FIS             NaN
Casos recuperados por FD         463925.0
Casos confirmados recuperados    471343.0
Casos activos confirmados             NaN
Casos probables acumulados        66702.0
Casos activos probables            2714.0
Casos nuevos sin notificar           29.0
Casos \nactivos confirmados       13635.0
Name: 2020-10-23 00:00:00, dtype: float64
`

**Comment by dna33** [comment]
Hola, corregido el problema. Gracias por reportar.

https://github.com/MinCiencia/Datos-COVID19/commit/49d913ddfdd7692bdeca9dc738b16d3ac8cfdf63
