### ISSUE TITLE
Verificacion simple

### ISSUE THREAD

**Issue by NilsRosenbaum** [MinCiencia/Datos-COVID19#681]
Casos Totales (A)- Total Recuperados (B)- Total Letal (C)- Total Activos (D) el resultado debe ser 0 y no lo es, ni en total pais ni en regiones.
A-B-C-D= 249 (diferencia en informe Nacional).
En caso Regiones, Stgo como ejemplo:
A-B-C-D=249
A-B-C-D= -7.
Puede ser error en formula por defecto.
saludos cordiales.
NR

**Comment by dna33** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/482
