### ISSUE TITLE
Actualización datos informe epidemiológico 

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#683]
El último informe Epidemiológico (con datos al 13 de Noviembre) fue publicado por el Ministerio de Salud el Sábado 14 de Noviembre (https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/
https://www.minsal.cl/wp-content/uploads/2020/11/Informe-Epidemiologico-68.pdf) 

Sin embargo los datos asociados a dicho informe no se encuentran actualizados en el repositorio para los productos asociados a dichos datos (revisado el 15 de Noviembre a las 11:00 AM).

![image](https://user-images.githubusercontent.com/68602/99186860-e55ead00-2731-11eb-86a6-3e3ac2c43e20.png)

Quizás es necesario ajustar los mecanismos de actualización automática de acuerdo a la publicación de los informes por parte del Ministerio de Salud.

Se observa que dicho reporte tampoco ha sido referenciado en la página de Coronavirus en gob.cl https://www.gob.cl/coronavirus/cifrasoficiales/#datos

**Comment by dna33** [comment]
Fue publicado.
