### ISSUE TITLE
Falta actualización Producto 37 (Fallecidos Confirmados).

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#686]
Hola,

Falta actualización Producto 37 (Fallecidos Confirmados) según lo reportado al día de hoy 16-nov-2020 (14.863).

Saludos.

**Comment by dafernandez75** [comment]
El commit que hicieron horas atrás no contempla hasta el 16-nov.

**Comment by scornejob** [comment]
@dafernandez75 , puede que me equivoque, pero creo que el p37 va uno o dos dias atrasado.

**Comment by fzmolina** [comment]
Hola @scornejob, en efecto el DP37 tiene como última fecha de publicación un día atrás.

**Comment by scornejob** [comment]
grax @fzmolina !
Entonces, como en https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto37/Defunciones_deis_std.csv veo la fecha de publicacion de ayer, cierro este ticket.

**Comment by dafernandez75** [comment]
Estimados Falta en serie, Confirmados 2020-11-16 con registros al 2020-11-13.
