### ISSUE TITLE
Se sugiere actualizar datos de informe Epidemiológico al ser publicado por el Ministerio de Salud

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#699]
El Informe Epidemiológico suele ser publicado por el Ministerio de Salud el día Sábado
https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/

Pero el enlace no se actualiza en la página de Coronavirus del gobierno hasta el día Domingo
https://www.gob.cl/coronavirus/cifrasoficiales/#datos

Sugiero explorar la actualización de los datos basados en el Informe Epidemiológico cuando este sea publicado por el Ministerio de Salud.  Muchas personas comienzan a analizar y compartir información luego de  la publicación del Ministerio de Salud.  Sin embargo, el repositorio de datos de Minciencia no se muestra actualizado, generando inquietud en los usuarios y retraso en los informes de terceros que dependen de estos datos. 

De antemano, agradezco considerar esta solicitud

Ejemplo, Domingo 29 de Noviembre a las 8:30 AM
![image](https://user-images.githubusercontent.com/68602/100540714-b8c09000-321d-11eb-9716-8e160d340728.png)

![image](https://user-images.githubusercontent.com/68602/100540663-59628000-321d-11eb-8d33-41bde59c0887.png)

Pero

**Comment by dna33** [comment]
Gracias por la sugerencia.
