### ISSUE TITLE
Casos por comuna Producto 1

### ISSUE THREAD

**Issue by AGSCL** [MinCiencia/Datos-COVID19#7]
¿Por qué estas comunas tienen una tasa si no registran casos?
![image](https://user-images.githubusercontent.com/37744754/78921931-b37ebd00-7a63-11ea-8f43-71fa6a39f37e.png)

**Comment by MinCiencia** [comment]
Estamos reflejando el dato como se reporta por parte de MINSAL. En el reporte del que obtenemos los datos indican que se calculan tasas de incidencia por cien mil habitantes.

**Comment by AGSCL** [comment]
0 * n = 0

**Comment by ivanMSC** [comment]
@AGSCL Se reportan los casos solo cuando son mas de 3. Si son menos de 4 se reporta la tasa. Tú puedes hacer la multiplicación con una calculadora.

**Comment by AGSCL** [comment]
Gracias ivanMSC!, todavía no entiendo muy bien. Pero voy a tratar de averiguar más. Por cierto, muy bueno tu repositorio!
