### ISSUE TITLE
Falta actualización Producto37 (Fallecidos) Confirmados 2020-11-29 con registros al 2020-11-26

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#701]
Hola,

Falta actualización Producto37 (Fallecidos) Confirmados 2020-11-29 con registros al 2020-11-26

saludos.-

**Comment by dna33** [comment]
Perdimos las actualizaciones entre el 26 de noviembre y el 12 de diciembre, por dificultades técnicas. Hoy solucionamos por lo que próximos actualizaciones no deberían tener dificultades.
