### ISSUE TITLE
Inconsistencia Producto 3

### ISSUE THREAD

**Issue by EnzoAndree** [MinCiencia/Datos-COVID19#703]
Los casos totales por región presentan inconsistencias entre Casos acumulados y Casos nuevos totales, al menos en la región metropolitana (no descarto el mismo problema en las demás regiones).

En la región metropolitana, la suma de los Casos acumulados del día 16-06-2020 (148.302) con los Casos nuevos totales del día 17-06-2020 (3.539) no es igual a los Casos acumulados del día 17-06-2020 (180.532). Es una diferencia no despreciable de 28.691 casos en un solo día. Desde esa fecha hasta hoy 02-12-2020 ha sucedido el mismo problema recurrentemente y se ha acumulado una diferencia de 28.810 casos entre la suma de los Casos nuevos totales y los Casos acumulados en la región metropolitana.

Tengo dudas si el problema es un error conceptual de mi parte o si realmente es un problema en la base de datos.

¿Podría alguien ser tan amable de confirmar ese error?

Saludos!

**Comment by fzmolina** [comment]
Hola @EnzoAndree ,

Ese salto en la cuenta del número de casos obedece a que los casos totales comenzaron a contarse por: confirmados, no notificados y probables.

Saludos

**Comment by EnzoAndree** [comment]
Hola @fzmolina !, 

Gracias por tu rápida respuesta 👍 .

Hasta donde comprendo la categoría Casos nuevos totales corresponde a la suma de Casos nuevos con síntomas, Casos nuevos sin síntomas, Casos nuevos sin notificar. Al menos empíricamente es así. Por lo que no creo que Casos nuevos sin notificar sean el problema

Adicional a eso, los Casos nuevos sin síntomas aparecen en la región metropolitana el 29-04-2020 (48 días antes de la inconsistencia). Así que no creo que sea problema del recuento de los casos nuevos sin síntomas.

Aun no comprendo que categorías debo sumar para mantener la consistencia de los Casos acumulados. Además, los nuevos casos probables que me indicas no están como categoría.

¿Es una inconsistencia histórica que no se puede resolver? Porque incluso en los reportes diarios están los datos así. Por lo que no es un problema de extracción de los números.

**Comment by fzmolina** [comment]
Hola @EnzoAndree,

No tiene que ver con casos totales (con o sin síntomas). Tu duda parte de la investigación epidemiológica y es la diferencia en que antes se contaban solamente los casos confirmados con PCR y después los no notificados y sospechosos, por ello se debe revisar el informe epidemiológico y no basarse en el reporte diario unicamente. 

Creo que para explicar mejor el origen de esta diferencia debo hacer referencia a los informes epidemiológicos publicados el 16 de Junio https://www.minsal.cl/wp-content/uploads/2020/06/16062020_Reporte_Covid19.pdf y comparar con el publicado el 19 de Junio (fecha donde aparece este "salto" en el conteo): https://www.minsal.cl/wp-content/uploads/2020/06/informe_epi_27_RA.pdf. A los casos acumulados se les siguió llamando de la misma manera, salvo que después de una fecha se comenzaron a contar los no notificados y los probables.

Avísame si aún quedan dudas.

Saludos
