### ISSUE TITLE
Producto 48 - Sin actualización hace un mes

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#707]
¡Hola!, esperando estén bien y agradeciendo nuevamente el enorme trabajo que realiza el @MinCiencia y sus colaboradores, quería consultar qué sucede con el [producto 48](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto48), **dado que no recibe actualización desde hace un poco más de un mes atrás**.
Desde ya, muchas gracias.

¡Saludos cordiales!

**Comment by dafernandez75** [comment]
30 octubre terminó ese trabajo de la Sochimi, publicaron que fue lo último hasta entonces ... https://www.medicina-intensiva.cl/site/post_covid.php?id=251

**Comment by dna33** [comment]
Muchas gracias por los comentarios @adinamarca y por la aclaración @dafernandez75. El [producto 52 ](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto52) cuenta con información similar usando el Ministerio de Salud como fuente.

**Comment by adinamarca** [comment]
Muchas gracias @dafernandez75 y @dna33 :)!
