### ISSUE TITLE
Producto 37 Defunciones DEIS (Distribución diaria de fallecidos Sospechosos)

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#708]
Hola, no se encuentra cargada distribución diaria de FALLECIDOS SOSPECHOSOS informe epidemiológico 74 del 5/Dic.  Saludos y gracias

**Comment by dafernandez75** [comment]
Buenas tardes,
En relación a este issue, para mañana me sumo y les agradeceré que puedan actualizar Producto 37: Confirmados U071 y Sospechosos U072, según lo que informará el Deis en Datos Abierto. Ref. https://deis.minsal.cl/#datosabiertos 

Saludos.

**Comment by Jorgecibia** [comment]
14/dic: Favor comentar que pasa con este problema, no entiendo mucho esta plataforma, la uso para extraer solamente los datos.  gracias

**Comment by Jorgecibia** [comment]
Hola, seguirán cargando distribución diaria de fallecidos sospechosos ?

Estan pendiente los Reportes Epi 74 y el 76, mañana se publica el 78

Gracias

**Comment by dafernandez75** [comment]
Jorge, ya están los registros correspondientes a todos los fallecidos confirmados y sospechosos en Datos Abiertos del Deis.
https://deis.minsal.cl/#datosabiertos

**Comment by Jorgecibia** [comment]
Gracias Daniel, si por ahora aplicando mouse en el gráfico y sacando los datos a manopla, pero me tiembla la mano ... ja ja ja  ....

**Comment by dna33** [comment]
Hola, añadimos los datos para el último informe EPI (12/17), tuvimos problemas con los anteriores. Continuaremos actualizando a medida que el DEIS publique.

**Comment by Jorgecibia** [comment]
Muchas gracias, excelente trabajo. slds

**Comment by dna33** [comment]
Añadimos los fallecidos sospechosos de los informes anteriores (4/12 y 11/12) y corregimos fechas de la última adición (de la errónea 17/12 a la correcta 18/12)
