### ISSUE TITLE
Aparentemente hay error en actualización del producto 17 el 13 de Diciembre de 2020 (registro sin valores)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#711]
En commit 94125e97a43015b8a252f95a09cc8e92b41c5c3b del 13 de Diciembre se agregaron registros patra el día 2020-12-13 sin valores

![image](https://user-images.githubusercontent.com/68602/102026275-a9902500-3d7b-11eb-8465-658ac15033a2.png)

![image](https://user-images.githubusercontent.com/68602/102025911-a72ccb80-3d79-11eb-9e66-e1c79fed66a0.png)

**Comment by scornejob** [comment]
Gracias @elaval . Lo arreglo ahora.

**Comment by scornejob** [comment]
Gracias @elaval . El error no es para nada aparente!!

**Comment by scornejob** [comment]
Va a estar arreglado cuando se publiquen los datos de hoy
