### ISSUE TITLE
Falta actualización Productos 37 (fallecidos) hoy 16/dic y Producto 39 (Notificación Inicio Síntomas) según Informe EPI ya publicado.. 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#715]
Hola,

Falta actualización Producto 37 (fallecidos) hoy 16/dic y Producto 39 (Notificación Inicio Síntomas) según Informe EPI 77 ya publicado hoy 16/dic.

![Captura de pantalla 2020-12-16 222813](https://user-images.githubusercontent.com/69001461/102426692-93d66600-3fee-11eb-95e4-cb1eeb234405.jpg)

**Comment by Jorgecibia** [comment]
Hola, también falta actualizar Producto 1 (Casos Totales por Comuna Incremental) y Producto 38 ( Fallecidos por Comuna), según último Reporte Epidemiológico N 77 publicado el martes 15/Dic.
Gracias

**Comment by dna33** [comment]
Hola, gracias por el mensaje. Acabamos de actualizar luego de algunas dificultades. Los datos están al día.

**Comment by dafernandez75** [comment]
muchas gracias por la gestión ...
