### ISSUE TITLE
Actualización Casos Activos por Comuna

### ISSUE THREAD

**Issue by fdubournais** [MinCiencia/Datos-COVID19#716]
Los casos activos por comnua (CasosActivosPorComuna_std.csv) no se han actualizado con la información del Lunes! Por lo general los miércoles está disponible la información del Lunes anterior y los Sábados la información de los Viernes. Cuando estará esa información disponible? 

Muchas gracias! Gran Repositorio!

**Comment by dna33** [comment]
Hola, gracias por el mensaje. Acabamos de actualizar luego de algunas dificultades. Los datos están al día.

**Comment by fdubournais** [comment]
Hola, podríamos actualizar los datos del Lunes por favor?

**Comment by MinCiencia** [comment]
¿Puedes indicar a qué producto te refieres?

**Comment by fdubournais** [comment]
Producto 19! CasosActivosporComuna_std.csv

**Comment by MinCiencia** [comment]
Se actualizarán los datos en función del informe publicado hoy informe 79 (https://www.minsal.cl/wp-content/uploads/2020/12/Informe-Epidemiologico-79.pdf).

**Comment by cjag20** [comment]
Hola @fdubournais, el producto ha sido actualizado.
Gracias por el aviso.

**Comment by fdubournais** [comment]
Muchísimas gracias Carlos!!
