### ISSUE TITLE
Informe Epidemiologico del Miércoles 22?

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#72]
Alguien tiene información sobre por qué está tan atrasado? Hoy corresponde el del Viernes y aún no ha salido el del miércoles.

**Comment by MinCiencia** [comment]
Hola, se publicará hoy.

**Comment by ivanMSC** [comment]
@MinCiencia Y sabes por qué?

**Comment by ivanMSC** [comment]
@MinCiencia Me perdí de algo? Cual es la explicación que da el MinSal al respecto?

![image](https://user-images.githubusercontent.com/35350256/80285568-fabbad80-86f3-11ea-83c2-2d721dec2e27.png)
