### ISSUE TITLE
Formato de Fecha incorrecto en archivo de origen DefuncionesDEIS.csv

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#720]
Archivo de origen input/NuevaDefDefunciones/DefuncionesDEIS.csv
Header tiene fechas en formato equivocado. 
Está en M/D/AA
Debería estar en AAAA-MM-DD

**Comment by dna33** [comment]
Cierto, corregido. Gracias por reportar.
