### ISSUE TITLE
Producto 58 aclaración camas UTI

### ISSUE THREAD

**Issue by nibravo** [MinCiencia/Datos-COVID19#724]
Saludos,

En la descripción del producto 58 se habla de camas de cuidados críticos utilizando UCI y UTI al mismo tiempo, pero solamente se entrega columnas para camas UCI. ¿Ese valor corresponde a la suma entre camas UCI y UTI, o solamente UCI?

Agradecido

**Comment by dna33** [comment]
Hola, solo UCI. Vamos a corregir la documentación. Gracias.
