### ISSUE TITLE
Actualización reporte diario 2020-12-29 (No se ha realizado a las 16:00)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#742]
A las 16:00 hrs del 29 de Diciembre no se han actualizado los inputs (ni outputs) del informe diario

¿Alguna hora estimada para la actualización?

![image](https://user-images.githubusercontent.com/68602/103307491-f405d880-49ee-11eb-89ac-1d92b57f9d65.png)

**Comment by dna33** [comment]
Así es, tuvimos una dificultad con la actualización de un nuevo producto (74, histórico del plan paso a paso), se actualizó a las 17 hrs. hoy a raíz de eso. Si no hay problemas, las actualizaciones ocurren diariamente a las 11am. Saludos, @elaval.
