### ISSUE TITLE
Actualización producto 19, Casos activos por comuna

### ISSUE THREAD

**Issue by fdubournais** [MinCiencia/Datos-COVID19#744]
Estimados,

Por favor actualizar el producto 19, con los casos activos por comuna. La información viene de Lunes y Viernes y por lo general se actualiza los miércoles y sabados. Favor actualizar! Muchas gracias

**Comment by ivanMSC** [comment]
@fdubournais El ministerio de Salud aún no ha publicado el Informe Epidemiológico del lunes.
