### ISSUE TITLE
Producto 74 (Etapas del plan paso a paso por comuna) no se encuentra actualizado

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#748]
El producto 74, con el estado de cada comuna en Plan Paso a Paso es un recurso muy útil para complementar información reportada por comunas

En la descripción se indica que la Frecuencia de Actualización es "Cada vez que se actualiza el estado."
![image](https://user-images.githubusercontent.com/68602/103442740-bba50b00-4c37-11eb-9651-d0e3ae3ded24.png)

Sin embargo la última versión publicada (a las 13:50 del 1 de Enero de 2021) **NO TIENE LOS ÚLTIMOS ESTADOS ACTUALIZADOS**

Por ejemplo, la Comuna de Curicó, que se encuentra en **Paso 1** (Cuarentena) desde el 30 de Diciembre de 2020, se registra en **Paso 2** (Transición) y el último registro tiene fecha 2020-12-23

![image](https://user-images.githubusercontent.com/68602/103442699-6d900780-4c37-11eb-93b7-50270f684a99.png)

Puede llevar a publicar información errada si usuarios asumen que es correcto que se actualiza  "Cada vez que se actualiza el estado" y se publica información asumiendo que el estado del último registro es el vigente.

Se sugiere actualizar los datos y/o clarificar información sobre la Frecuencia de Actualización

**Comment by dna33** [comment]
Hola, gracias por tu mensaje. Tienes razón, vamos a actualizar la redacción por ahora.

Para tu información y dado tu interés, decidimos publicar una primera versión del archivo confeccionada por el equipo del Ministerio de Salud, aún cuando estuviera incompleta, ese equipo trabaja en generar la historia desde el principio y ha adquirido el compromiso de actualizarlo con la frecuencia en la versión actual del readme. 

Se han demorado pues deben cruzar no con los anuncios, si no con las publicaciones en el diario oficial.

Saludos.

**Comment by dna33** [comment]
En todo caso, ahora que actualizamos la documentación, me fijé que el archivo no ha sido actualizado hoy como dices, te equivocas en eso. Dice con claridad el sistema que fue actualizado "4 days ago", no ha sido publicada hoy como tu indicas.

**Comment by elaval** [comment]
> En todo caso, ahora que actualizamos la documentación, me fijé que el archivo no ha sido actualizado hoy como dices, te equivocas en eso. Dice con claridad el sistema que fue actualizado "4 days ago", no ha sido publicada hoy como tu indicas.
> 
> <img alt="Screen Shot 2021-01-01 at 2 06 50 PM" width="251" src="https://user-images.githubusercontent.com/12438811/103443116-a8e00580-4c3a-11eb-89ba-90867f78ad39.png">

Gracias @dna33 

Probablemente me expresé mal.  No me refería a que el archivo hubiese sido actualizado hoy.  Me refería a que a esa hora (a las 13:50 del 1 de Enero de 2021), la versión que estaba publicada (que efectivamente fue actualizada hace 4 días) no tenía los últimos estados  actualizados de las comunas.

Saludos
