### ISSUE TITLE
Nacionalidad

### ISSUE THREAD

**Issue by guillermoburr** [MinCiencia/Datos-COVID19#752]
Es de todo interés el conocer la nacionalidad de los fallecidos con COVID. Importante agregar el dato.

**Comment by MinCiencia** [comment]
Hola, ¿por qué?

**Comment by mauriciomunozaufer** [comment]
Incluso la nacionalidad de los contagiados en la región de Tarapacá ya que ingresan ilegalmente más de 600 personas por las fronteras y no existe un control de epidemia serio en la ciudad.



________________________________

**Comment by juancri** [comment]
Me parece que este requerimiento debe ser evaluado con mucho cuidado. La nacionalidad de las personas contagiadas es irrelevante y publicar esa información puede llevar a análisis apresurados y discriminatorios.

**Comment by ctroncoso** [comment]
Mas allá que sea irrelevante, usualmente es inexacta. El deis "debería" recibir en las codificaciones GRD, la nacionalidad, provincia, comuna y hasta la etnia, sin embargo, rara vez se llena esta información, y hospitales y clínicas dejan el campo sin llenar. 
Conceptualmente se podría, pero en los hechos, no se podría verificar la data. En definitiva, de estar esta información disponible, no podrías confiar en los resultados.
