### ISSUE TITLE
No se gatilló el action Actualiza_productos_de_defunciones_DEIS luego de la carga de defunciones. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#769]
El commit fue realizado a las 23:12 y no gatilló el action que genera el output.

**Comment by dna33** [comment]
Cierto, acabo de arreglarlo (https://github.com/MinCiencia/Datos-COVID19/commit/636c1c82a9de9d530f9824d15ad68d4179c2b53c). Saludos.
