### ISSUE TITLE
Actualización de casos omitió el 08/01

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#776]
Hola, veo que las actualizaciones de hoy 09/01 de los productos 3 y 13, sobre casos nuevos y casos acumulados, se han saltado los datos del día de ayer, 08/01. Tal vez pasa con otros productos.

**Comment by adinamarca** [comment]
¡Exacto! También tuve el mismo problema en [https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto13/CasosNuevosCumulativo.csv](url)

**Comment by dna33** [comment]
Corregido

**Comment by adinamarca** [comment]
@dna33 El producto 7 sigue teniendo inconvenientes. Se repitió la fila correspondiente al día de hoy :( 
https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto7/PCR_T.csv

Gracias

**Comment by dna33** [comment]
Cierto, el transpuesto y el estándar tenían ese problema, ya está corregido.
