### ISSUE TITLE
Duplicated entries on 2021-01-09

### ISSUE THREAD

**Issue by eguidotti** [MinCiencia/Datos-COVID19#781]
Hi there,
it seems that the following files contain duplicated entries on 2021-01-09:
- https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto24/CamasHospital_Diario_T.csv
- https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto17/PCREstablecimiento_std.csv

Thanks!

**Comment by dna33** [comment]
Fixed https://github.com/MinCiencia/Datos-COVID19/pull/784/commits/80844e2a7c8ecad18c4571c6ba14aea197db0e5f

Thanks for reporting.
