### ISSUE TITLE
Producto 19 - Casos Activos por Comuna al parecer no coincide con el Reporte de MINSAL

### ISSUE THREAD

**Issue by Hsoto** [MinCiencia/Datos-COVID19#787]
Buenas tardes

Al revisar algunas comunas de la RM en el producto 19 y verificar con los casos activos nuevos reportados en último informe epidemiológico publicado hoy, se observa que no coinciden. 

Por ejemplo el caso de la Granja el producto 19 indica que existen 52 casos activos y en informe epidemiológico se indica que hay 72 casos activos. En reporte anterior fue de 69, luego esta diferencia puede conducir a un analisis erroneo de la tendencia.

En el caso de la Comuna de La Florida el producto 19 indica que existen 216 casos activos y en informe epidemilógico se indica que hay 300 casos. En reporte anterior los casos activos fueron 254, el cambio es significativo. 

Se adjunta recorte de Informe Epidemiologico de hoy, donde se observan ambos casos

<img width="764" alt="imagen" src="https://user-images.githubusercontent.com/11822438/104111776-22c06080-52c5-11eb-8995-2d2a808b9559.png">

Y se muestra imagen de los datos publicados en este repositorio CasosActivosPorComuna.csv 

![imagen](https://user-images.githubusercontent.com/11822438/104111806-7d59bc80-52c5-11eb-9834-d8bc418ef782.png)

¿Esta diferencia a que se debe? Entiendo que debería ser coincidente con lo entregado en informe epidemilógico.

Quedo atento, gracias!

**Comment by dna33** [comment]
Debido a un error que acabamos de lograr corregir en https://github.com/MinCiencia/Datos-COVID19/commit/92c77ec125ba3df79bf83d42b8abfc29155578a3
