### ISSUE TITLE
Varios productos afectados - Falta 08/01/2021

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#790]
Hola, buenas.

En el producto 3 falta la información correspondiente al 08/01/2021 [aquí.](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto3)

UPDATE: [producto 14](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto14) también (y puede ser que otros productos también).

**Comment by dna33** [comment]
corrected p3 https://github.com/MinCiencia/Datos-COVID19/pull/791/commits/38faa21fb99492c263c116d5ec8151f7c08cd9e1

**Comment by adinamarca** [comment]
@dna33 disculpa, pero también falta el producto 14, el producto 13 y entre otros... :(

**Comment by cjag20** [comment]
p 14 corregido. Veremos el p 13

**Comment by cjag20** [comment]
Corregido también p 13 y productos afectados
