### ISSUE TITLE
Cambio en el formato de la fecha del producto 14

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#793]
[Este commit](https://github.com/MinCiencia/Datos-COVID19/commit/f1ea0b8a64f281b05a971f6668f4c4b12e7c5fea#diff-1e3a7496cab657f67a5130283b67bab565cff2296f1257bd267f17f82513d752) cambió el formato de la fecha desde ISO a `dd-MM-yy` para el producto 14.

**Comment by dna33** [comment]
corregido https://github.com/MinCiencia/Datos-COVID19/pull/797/commits/7f1a5fc0fed653be1d39fe59653382d8ce3c2ba7, gracias por reportar
