### ISSUE TITLE
Línea vacía en producto 14

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#794]
[Este commit](https://github.com/MinCiencia/Datos-COVID19/commit/ced4661942126ffc7a6e78b2394ff75460e38aec#diff-1e3a7496cab657f67a5130283b67bab565cff2296f1257bd267f17f82513d752R10) introdujo una línea vacía entre `O'Higgins` y `Maule`, lo que causa errores al utilizar algunos parsers.

**Comment by dna33** [comment]
corregido https://github.com/MinCiencia/Datos-COVID19/pull/797/commits/7f1a5fc0fed653be1d39fe59653382d8ce3c2ba7, gracias por reportar
