### ISSUE TITLE
Transponer producto5

### ISSUE THREAD

**Issue by scornejob** [MinCiencia/Datos-COVID19#8]
Por consistencia.

**Comment by ivanMSC** [comment]
Podrías haber traspuesto los otros mejor. Por ejemplo en producto1, dejar columnas `Fecha, Comuna, Casos` en lugar de `Comuna, Fecha1, Fecha2, Fecha3,...`

**Comment by scornejob** [comment]
Dado que hicimos los productos estándar, cierro este issue
