### ISSUE TITLE
Error en Producto 19, casos activos

### ISSUE THREAD

**Issue by JaimeCruzH** [MinCiencia/Datos-COVID19#80]
Si suman el total de casos activos por comuna entregados en los últimos 5 informes no cuadra con el total de casos activos del país. Por ejemplo el total de casos activos informados por el gobierno el 25 de abril es 5.931 y si suman los casos activos del informe del 24 de abril estos suman 3.543.
Por favor revisar.

**Comment by MinCiencia** [comment]
Hola @JaimeCruzH no es un error, en la documentación del producto 5 y en en la documentación de los productos 15 y 25 por ejemplo están las explicaciones.

Los informes epidemiológicos reportan el numero usando la fecha de inicio de síntomas, que es un resultado de la investigación epidemiológica. El reporte a nivel nacional usa la fecha de diagnóstico. La investigación epidemiológica es un proceso en continua evolución, se encuentra el mecanismo de contagio, el inicio clínico de la enfermedad (síntomas) e incluso se pueden corregir retroactivamente datos, como por ejemplo la residencia de los individuos.

**Comment by JaimeCruzH** [comment]
Hola, gracias por la rápida respuesta. 
¿Es posible obtener la información por comuna de casos activos que coincida con la información diaria entregada por el gobierno?
Saludos,
JC

**Comment by MinCiencia** [comment]
Te refieres a obtener los casos activos por comuna, por fecha del diagnostico? No es posible con la información que se hace pública hasta el momento. porque los test PCR que confirman el diagnostico a veces se realizan en comunas distintas de la residencia de la persona.

**Comment by JaimeCruzH** [comment]
Ok, gracias por tu explicación. Ojalá algún día liberen las cifras por comuna online, ya que la diferencia es mucha respecto al estudio epidemiológico, en el último caso estamos hablando de un 67% más. 
Son 2.388 casos activos más que pueden hacernos entender algunas decisiones del gobierno.
Saludos,
JC

**Comment by MinCiencia** [comment]
@JaimeCruzH, puedes calcular casos activos por comuna usando el dato de epidemiología, se publica los lunes y los viernes todos las semanas. 

Epidemiología usa fecha de inicio de síntomas, reporte diario usa fecha de diagnostico, son dos referencias que puedes utilizar y dan números distintos, el primero da un numero menor lógicamente.
