### ISSUE TITLE
Producto 2 lleva 11 días sin actualizar

### ISSUE THREAD

**Issue by Rod241980** [MinCiencia/Datos-COVID19#800]
Producto 2 lleva 11 días sin actualizar, alguna fecha estimada para subir esta data?

**Comment by vivianahernan** [comment]
Por favor actualizar Producto 2, tenemos reportes con retrasos desde la semana pasada, van a subir esta data en algún otro producto? hay una fecha estimada?

**Comment by dna33** [comment]
La data esta en este producto: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto1/

**Comment by dna33** [comment]
En todo caso, aqui esta actualizado. Había un problema con el cambio de año en el calendario que acabamos de resolver. Saludos.

**Comment by vivianahernan** [comment]
muchas gracias por la respuesta. No vi que hubieran informado sobre el cambio al producto 1, por eso mi insistencia. Saludos

**Comment by dna33** [comment]
Hola @vivianahernan, está escrito en el readme.md del producto2 https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto2/README.md, nota aclaratoria número 5 (last Edit: agosto 2020).

**Comment by Rod241980** [comment]
Muchas gracias por la actualización, agradezco la pronta respuesta. Saludos
