### ISSUE TITLE
Producto 5 Casos Activos Nacionales no actualizado

### ISSUE THREAD

**Issue by nibravo** [MinCiencia/Datos-COVID19#803]
Estimados,

He notado que en el Producto 5 los casos activos nacionales se encuentran desactualizados desde el 08/01/2021 (Columa "Casos activos").
¿Se seguirá entregando este dato actualizado diariamente?

Agradecido de antemano por su respuesta,
Nicolás Bravo

**Comment by dafernandez75** [comment]
hola, ver columna casos activos confirmados. En esa columna los trasladaron a partir de la fecha mencionada ... saludos

**Comment by dna33** [comment]
voy a revisar el código porque no es el comportamiento diseñado, dicho eso lo que indica @dafernandez75 es cierto.

**Comment by ctroncoso** [comment]
Probablemente un espacio rezagado al final del string?

![image](https://user-images.githubusercontent.com/121016/104387048-1894a100-5515-11eb-8506-8632ca3ceef3.png)

**Comment by ctroncoso** [comment]
@dna33 cual es el source que genera este?... tal vez podríamos ayudar con el refactoring y dejarlo abierto para hacer el testing que propusieron hacer hace unos días... sería interesante.

**Comment by dna33** [comment]
Es este: src/reporteDiario.py

Line 87 to 235, llamado en la linea 720.
