### ISSUE TITLE
Datos sobre vacunas

### ISSUE THREAD

**Issue by lucasrodes** [MinCiencia/Datos-COVID19#804]
Buenas,
Hay previsión de añadir datos sobre vacunaciones?

Podrían ser de gran utilidad para el proyecto de [Our Wold in Data](https://github.com/owid/covid-19-data).

Gracias!

**Comment by dna33** [comment]
Si, estamos trabajando con el DEIS para añadirlos.

**Comment by dafernandez75** [comment]
Excelente, así con ello complementar la info ya entregada por el Minsal ... https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F1a8cc7ff-7df0-474f-a147-929ee45d1900&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false

**Comment by juancri** [comment]
Si alguien necesita la información de las vacunaciones diarias, las estoy publicando diaramente en [este repo](https://github.com/juancri/covid19-vaccination)

**Comment by MinCiencia** [comment]
De dónde estas obteniendo la información, @juancri ? Deis actualmente publica un tableu en deis.minsal.cl, el trabajo que estan haciendo ellos es asegurar la calidad de los datos, y el de nosotros es integrar su fuente con este repo.

**Comment by juancri** [comment]
Desde el [sitio del DEIS](https://deis.minsal.cl/). Se puede ver el detalle en el [README](https://github.com/juancri/covid19-vaccination/blob/master/README.md). Me parece que dejaron de publicar las vacunas por dia. Voy a investigar mas tarde y actualizar el proceso si es necesario.

**Comment by juancri** [comment]
**Actualización:**

Dejé el archivo CSV en el repositorio lo que permite tener una URL fija. Además, desde ayer estoy registrando las vacunas por región:

https://github.com/juancri/covid19-vaccination/tree/master/output

**Comment by dna33** [comment]
añadido nuevo producto usando lo de @juancri temporalmente, DEIS desarrolla en este momento integración para ampliar el data product.

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto76

**Comment by juancri** [comment]
Estuve revisando y tengo algunas dudas sobre el formato de:

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion_std.csv

No estoy seguro de si es intencional la descomposición. Tal vez sería mejor una de 4 columnas:

- Región
- Fecha
- Dosis
- Cantidad

**Comment by dna33** [comment]
Es cierto, estaba medio malo. Toda la razón con las 4 columnas. Este _commit_ lo implementa: https://github.com/MinCiencia/Datos-COVID19/commit/a811744f2f96a440ace96b238813376e58644540
