### ISSUE TITLE
Datos de disponibilidad de camas UCI no actualizado

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#811]
Los Datos de disponibilidad de camas UCI ([producto 52](/MinCiencia/Datos-COVID19/tree/master/output/producto52)) no ha sido actualizado en más de 2 semanas.

**Comment by MinCiencia** [comment]
Ver https://github.com/MinCiencia/Datos-COVID19/issues/809, el objetivo es actualizar la información este sábado, el Ministerio de Salud está haciendo una confirmación de los números con fuentes independientes.
