### ISSUE TITLE
Actualización de Marzo a Julio 2020, plan Paso a Paso, producto 74

### ISSUE THREAD

**Issue by jaimesoza** [MinCiencia/Datos-COVID19#813]
El título lo dice todo: actualizarán el producto 74 respecto al plan paso a paso desde marzo hasta julio? actualmente solo están actualizando la información reciente y no la pasada.

**Comment by dna33** [comment]
No entendí el comentario. Los productos tienen un readme.md que hay personas que invierten esfuerzo en que se lea bien. Espero los leas. Saludos.

**Comment by jaimesoza** [comment]
El readme no se lee bien, pues indica que el archivo solo tiene información de dos semanas en diciembre, lo cual no es correcto. Sin considerar ello, yo mismo cerré el issue pues me di cuenta de mi error (el plan paso a paso comenzó a mediados de Julio). No veo la necesidad de responder de esa forma.

**Comment by dna33** [comment]
Agradezco la lectura, entonces. Lo expresaba con respeto, pero sí un poco tajante porque siento a estas alturas el deber de relevar el trabajo que se hace. De todas maneras, tienes razón en lo que dices, vamos a corregir esa nota aclaratoria que agregamos a pedido de un comentario en este mismo espacio, y se ha quedado puesta por más tiempo del necesario.
