### ISSUE TITLE
¿Producto 33 descontinuado?

### ISSUE THREAD

**Issue by ekos77** [MinCiencia/Datos-COVID19#814]
Junto con saludar, deseo preguntar si ¿los datos del producto 33 están descontinuados?

**Comment by MinCiencia** [comment]
Hola, no. Hay un razago pues el origen de los datos cambió su mecanismo de sampleo. El equipo del IDS de la Universidad del Desarrollo está trabajando en una nueva actualización. En el intertanto acabamos de subir los últimos datos disponibles, entre el 21 de septiembre y el 30 de noviembre del 2020.
