### ISSUE TITLE
Actualización productos 52, 58

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#815]
Hola! Es posible actualizar los datos de los productos 52 y 58, referente a la disponibilidad de camas críticas? Creo que sobre todo en estos días es relevante tener esa información.
Aprovecho de preguntar también por el producto 40, sobre viajes aéreos.
Gracias

**Comment by dna33** [comment]
Hola, @paarriagadap. El Ministerio de Salud está verificando la información para poder continuar con la cadencia de actualización semanal que teníamos el 2020 (producto 58). Por otro lado, lamentablemente SOCHIMI dejó de hacer su encuesta (producto 52).

**Comment by MinCiencia** [comment]
Productos 52 y 58 actualizados recién.
