### ISSUE TITLE
Producto 37 - campo "sospechosos"

### ISSUE THREAD

**Issue by jccarvajal** [MinCiencia/Datos-COVID19#816]
Buenas,
El producto 37 no presenta el campo de las defunciones sospechosas desde el 01/01/2021.
Gracias.

**Comment by dafernandez75** [comment]
Hola,
Deis actualizó estos y eliminó entre otros el registro mal ingresado de la publicación que realizó el sábado pasado. Revisar acceso respectivo en el link siguiente.
https://deis.minsal.cl/#datosabiertos

**Comment by jccarvajal** [comment]
Ok gracias.

**Comment by MinCiencia** [comment]
Hola, el producto 37 estará actualizado con esa información cuando subamos el reporte diario de hoy. Saludos.
