### ISSUE TITLE
Aparente error en Porducto 74 - Etapas del plan paso a paso por comuna

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#818]
Comuna de ANCUD parecen no tener la información correcta en de Paso a Paso

ANCUD se informa en CUARENTENA en https://www.gob.cl/coronavirus/pasoapaso#situacioncomunal/
![image](https://user-images.githubusercontent.com/68602/104847437-b3e39880-58be-11eb-9f59-7d0709d778ae.png)

Pero los datos en el repositorio indican (para 2020-01-18):
ANCUD Urbana: Paso 2
ANCUD Rural: Paso 1

![image](https://user-images.githubusercontent.com/68602/104847389-73841a80-58be-11eb-8ffb-aa53ec614ff4.png)

**Comment by dna33** [comment]
Corregido en el commit referenciado. Gracias por reportar.
