### ISSUE TITLE
Consulta General 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#819]
Hola,
En relación a esta nueva dependencia del Dpto. Epidemiología (ver noticia del link adjunto), la información de la data que ustedes difunden en este repositorio seguirá funcionando normalmente?. Ya que relaciona a mi modo de ver lo indicado en el Punto 3 de las funciones ha realizar de esta nueva dependencia, referida a proveer información oportuna y de calidad.    

Saludos

https://twitter.com/manupalominos/status/1350964457330106371?s=20

**Comment by dna33** [comment]
Así es, seguirá funcionando.
