### ISSUE TITLE
Producto 29 desactualizado

### ISSUE THREAD

**Issue by nikolastico** [MinCiencia/Datos-COVID19#822]
Hola, el producto29 está desactualizado desde hace 10 días (aunque al parecer más porque sale data hasta el 23/12/20). En específico me refiero a _Cuarentenas-Totales_. ¿Hay planes para volver a mantenerlo actualizado?

**Comment by dna33** [comment]
Hola, este es el producto de referencia desde la implementación del plan paso a paso:

 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto74
