### ISSUE TITLE
Algún inconveniente con actualización de Informe Diario del 2020-01-22?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#824]
A las 16:30 del Viernes 22 aún no se actualiza input (ni output asociado)
![image](https://user-images.githubusercontent.com/68602/105536609-6062b780-5ccf-11eb-939b-45559670f88f.png)

**Comment by elaval** [comment]
Fue actualizado mientras escribía el issue

**Comment by dna33** [comment]
Gracias
