### ISSUE TITLE
Problema con el producto 32

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#825]
Hola, al parecer hay problemas en la captura de datos del producto 32, sobre defunciones desde el Registro Civil. Pasa que graficando las muertes que hay en las últimas semanas vi que se produjo un salto enorme que después volvió a bajar, un salto entre las semanas del 28 de diciembre y del 4 de enero. Fui a la [plataforma del Registro Civil](https://estadisticas.sed.srcei.cl/defcom), descargué y comparé los gráficos:
![image](https://user-images.githubusercontent.com/63430031/105566024-983a2100-5d08-11eb-89ad-3f5e6cf4c51e.png)
![image](https://user-images.githubusercontent.com/63430031/105566029-a2f4b600-5d08-11eb-8aca-08715c28d55d.png)
[Acá](https://public.tableau.com/views/MinCienciavsRegCivil/Sheet1?:language=es&:display_count=y&publish=yes&:origin=viz_share_link) están los tableros.

Aunque hay unas diferencias antes, en las últimas semanas la diferencia es mucha y es probable que se deba a duplicaciones en la captura. Agradecería mucho que se corrigiera.

Saludos!

**Comment by MinCiencia** [comment]
Hola, ¿puedes revisar los [inputs](https://github.com/MinCiencia/Datos-COVID19/tree/master/input/RegistroCivil/Defunciones) por favor? Creo que tiene que ver con que el registro civil corrige retroactivamente registros en el pasado, quizás más en el pasado que lo que estamos haciendo update retroactivo en el código acá.

**Comment by paarriagadap** [comment]
Comparé todos los archivos csv del input (los que dicen DO) y tengo esto:
![image](https://user-images.githubusercontent.com/63430031/105618339-c2511900-5dc4-11eb-96dd-41e8732a38a4.png)
![image](https://user-images.githubusercontent.com/63430031/105618477-5374bf80-5dc6-11eb-85a2-6e3677479039.png)

[Acá](https://public.tableau.com/views/Input_16114500864680/Comparacin1?:language=es&:display_count=y&publish=yes&:origin=viz_share_link) lo pueden ver también.
Se supone que la curva correcta es la última, la del 23-01 (azul), pero antes aparecen cosas bien distintas, sobre todo la del 08-01 (gris), 07-01 (amarilla), 06-01 (morada), 01-01 (rosada) y 31-12 (gris oscuro). Me parece que esos "super peaks" después son agregados de alguna manera que hacen que se vean reflejados en el output, pero no lo veo bien en el código.

**Comment by paarriagadap** [comment]
Hola, han podido encontrar algo_

**Comment by dna33** [comment]
No aún, por ahora extendí los scripts al 2021. Rn el diseño conceptual de la integración con el registro civil tuvimos la conciencia de que se corrigen o añaden inscripciones retroactivamente, y no habíamos actualizado esa revisión al 2021. Quizás las diferencias estaban relacionadas con eso. Pero seguimos investigando.

**Comment by dna33** [comment]
link to issue https://github.com/MinCiencia/Datos-COVID19/issues/833

**Comment by dna33** [comment]
Están corregidos los problemas de desacople, increíblemente las actualizaciones retroactivas del registro civil incluso afectaban registros del 2019, los problemas see solucionaron al correr una actualización histórica y hacerle mantención al código para considerar apropiadamente el 2021 (se crearon nuevos archivos con ese prefijo).

Para evitar dificultades, en cada actualización se revisaran registros entre enero de 2020 y la fecha actual.

Ver commit para mas detalles: https://github.com/MinCiencia/Datos-COVID19/commit/de2f5472f1f09a6e181bbac49ab3c278e89702f9

**Comment by paarriagadap** [comment]
Hola, ha pasado de nuevo que la actualización de defunciones del Registro Civil entrega un número inusual. Después de varios días que el valor de defunciones no se actualizaba, hoy cambió bastante en las últimas semanas. Como de nuevo me llamó la atención saqué la info de la plataforma del Registro Civil y hay discrepancias:

![image](https://user-images.githubusercontent.com/63430031/107986172-45235900-6faa-11eb-8074-59c1b241c3a5.png)
![image](https://user-images.githubusercontent.com/63430031/107986195-4f455780-6faa-11eb-8678-bd476dc976df.png)

Esta vez no me explico el salto de la línea naranja (el producto 32), porque entre los DO no hay ninguno que llegue a un valor inusualmente alto. Quizás tiene que ver con una agregación en el cambio de quincena que falla. Los datos que saqué del Registro Civil son entre el 01-01-2020 y el 14-02-2021.

Espero que se pueda arreglar, saludos.
