### ISSUE TITLE
Producto 37 - Fallecidos Sospechosos DEIS

### ISSUE THREAD

**Issue by Jorgecibia** [MinCiencia/Datos-COVID19#827]
Hola, Datos de distribución diaria de fallecidos Sospechosos reporte DEIS del 21/Ene no están cargados.  Gracias

**Comment by dna33** [comment]
Hola, añadidos recién: https://github.com/MinCiencia/Datos-COVID19/commit/4f9f61974091c785a905a78c1f05b1f4a386d36b

**Comment by Jorgecibia** [comment]
Gracias
