### ISSUE TITLE
Problema con Producto 58

### ISSUE THREAD

**Issue by dfuenzalidaf** [MinCiencia/Datos-COVID19#829]
Hola, tengo entendido que el producto 58 se actualiza los martes con el reporte diario pero hoy no fue actualizado. ¿Será actualizado la otra semana?

Saludos

**Comment by dna33** [comment]
Hola, estamos revisando con la Subsecretaría de Redes Asistenciales, la actualización debería ser semanal.

**Comment by dna33** [comment]
Hola, hoy actualizamos esta información, ver commit: https://github.com/MinCiencia/Datos-COVID19/commit/1e01a7462365cba954159e83be505b6c72d6daee
