### ISSUE TITLE
Casos Recuperados

### ISSUE THREAD

**Issue by rebollodani** [MinCiencia/Datos-COVID19#83]
Si al dia de hoy se consideran como recuperados los casos de hace 14 días menos los fallecidos, existe un número no menor de personas que se estarían dando por recuperadas y no caen dentro de la categoría ya que hace 14 días estaban hospitalizadas.  Por ej. según información del día 07.04 los casos totales (acumulados) eran 5116 (de los cuales se informaron 337 hospitalizados).  El día 21.04 se informa que tenemos 4969 recuperados que corresponde a 5.116 - 147 (los casos del día 7 menos los fallecidos).  Bajo este concepto estamos asumiendo que los 337 hospitalizados (al día 7.4) también fueron considerados recuperados el día 21 lo que no tiene ningún sentido ya que:
1. no todos salieron juntos del hospital
2. no todos los que salen de hospitalización salen "recuperados", salen a continuar cuarentena o cuidados en casa.
Entiendo que puede existir desviación respecto del nulo seguimiento de casos "simples" o sin hospitalización y que son considerados recuperados a los 14 días toda vez que siguen con síntomas, pero considerar a los 300 o 400 hospitalizados que tenemos como recuperados creo que no corresponde.
slds,

**Comment by rebollodani** [comment]
Esto incluso pensando en los hospitalizados en UCI que son los que informan en prensa ya que los hospitalizados totales son cerca de 1000 actualmente, es decir la desviación es de aprox 1000 personas en los recuperados.

**Comment by MinCiencia** [comment]
Hola @rebollodani, mirando esto en detalle, me parece que la serie de tiempo más correcta para hacer una proyección de recuperados es la que está en el data product 15 (por fecha de inicio de síntomas), pues está normalizada a la evolución clinica.

Dicho lo anterior, las proyecciones de recuperados no representan los recuperados reales, vamos a incluir una nota aclaratoria en el readme de las series de tiempo que incluyan este concepto.
