### ISSUE TITLE
Fallo la actualización de 28/01 (registro civil)

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#833]
Hay un action pegado hace 5 horas. ¿Es lo que está afectando la actualización de hoy?

**Comment by ctroncoso** [comment]
Al parecer, la acción se cae al normalizar el nombre de las comunas luego de la llamada al registro civil.

![image](https://user-images.githubusercontent.com/121016/106211791-10d92b80-61a8-11eb-8570-cd542b5d0eae.png)

**Comment by dna33** [comment]
Qué action era ese, @ctroncoso ?

**Comment by ctroncoso** [comment]
Actualiza_productos_del_Registro_Civil 
Tal vez una comuna mal escrita que no pudo normalizar?

**Comment by dna33** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/825
