### ISSUE TITLE
Falla en actualización de datos del 28 de Enero - Sugiero comunicar estado de la situación

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#835]
Muchos dependen de los datos actualizados en este repositorio para analizar y comunicar el estado de la pandemia

Entiendo que pudo haber un inconveniente con la actualización del día de ayer (que todavía no se resuelve al al Viernes 29 7:30AM)

Sugiero comunicar posibles causas y tiempo estimado de resolución por esta vía para mantener una buena comunicación / coordinación con la gran cantidad de usuarios / consumidores de estos datos.

**Comment by adinamarca** [comment]
> Muchos dependen de los datos actualizados en este repositorio para analizar y comunicar el estado de la pandemia
> 
> Entiendo que pudo haber un inconveniente con la actualización del día de ayer (que todavía no se resuelve al al Viernes 29 7:30AM)
> 
> Sugiero comunicar posibles causas y tiempo estimado de resolución por esta vía para mantener una buena comunicación / coordinación con la gran cantidad de usuarios / consumidores de estos datos.

¡Por favor! Estamos a la espera.

**Comment by dna33** [comment]
Se atrasó el reporte del día jueves y luego el código depende de la actualización diaria, corregimos todo ahora. Queda pendiente hacer el código más robusto. 

En todo caso, está listo el trabajo del reporte diario en los días faltantes, hasta la fecha. Y subidos también los productos que se actualizan con información del DEIS y el Departamento de Epidemiología (publicados hoy).

**Comment by elaval** [comment]
Muchas gracias por la información
