### ISSUE TITLE
Action de actualización de reporte diario 28/01 y 29/01 falló.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#836]
Proceso fallo en el paso de la generación del producto 5.

![image](https://user-images.githubusercontent.com/121016/106308961-36197880-6240-11eb-90cf-6bc620ac83b3.png)

**Comment by ctroncoso** [comment]
Revisando el código, el problema radica en que la actualización depende de "cuando" es realizada. 
La forma de generar la última fila depende del "ahora", por lo que puede causar muchos errores si no se realiza el mismo dia.
Recomendaría encontrar la fecha mas alta via  ` df_input_file['Fecha'].max()` o si se requiere obtener la última fila, ordenar via `sort_value`, y luego obtener la última via `tail(1)`

![image](https://user-images.githubusercontent.com/121016/106312098-eab59900-6244-11eb-9886-e4fc95042e4c.png)

**Comment by adinamarca** [comment]
¿Aún nada? @MinCiencia

**Comment by dna33** [comment]
Listo el trabajo del reporte diario en los días faltantes, hasta la fecha. Y subidos también los productos que se actualizan con información del DEIS y el Departamento de Epidemiología (publicados hoy).

Bienvenidos PR mejorando el cógido si te animas, @ctroncoso

**Comment by ctroncoso** [comment]
voy a darle un intento... creo entender la intención del código.
