### ISSUE TITLE
ACTUALIZACIÓN HA FALLADO X DÍAS EN VARIOS PRODUCTOS

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#838]
Hoy Sábado 30 de Enero de 2021 a las 7AM siguen sin actualizarse (desde Miércoles 27) una serie de productos (Ej Producto 5 - Totales Nacionales)

No se ha recibido ningún comentario a los issues que lo notifican y eso genera dudas sobre si están abordando el problema (¿se han dado cuenta del problema? ¿necesitan ayuda para resolverlo?)

Este problema está bloqueando el trabajo de mucha gente que depende de estos insumos de datos y a esta altura se ha tornado grave

Si requieren ayuda, hay mucha gente dispuesta a apoyar

POR FAVOR RESPONDER O ABRIR UN ISSUE NOTIFICANDO QUE ESTÁ OCURRIENDO

![0C85AC92-42F2-4049-814D-3EDC4545485A](https://user-images.githubusercontent.com/68602/106353305-50973480-62c8-11eb-9c6e-3ad0f1f030fa.png)

**Comment by juancri** [comment]
Me sumo a la preocupación y también a la oferta de ayuda.

**Comment by ivanMSC** [comment]
Les dejo este tutorial: 
https://www.youtube.com/watch?v=p2304BjvrB8

**Comment by dna33** [comment]
Listo el trabajo del reporte diario en los días faltantes, hasta la fecha. Y subidos también los productos que se actualizan con información del DEIS y el Departamento de Epidemiología (publicados hoy).
