### ISSUE TITLE
Reciente actualización incluye datos de 2021-01-30 pero omite 2021-01-29 & 2021-01-28 (Ej producto 3)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#839]
![image](https://user-images.githubusercontent.com/68602/106364453-e3a68d80-630d-11eb-8047-bd69967d03e7.png)

**Comment by dafernandez75** [comment]
Así mismo en Producto 13 publicado hace 1 hora, Total regional para sábado 30 enero 2021 es 4.260 siendo que en reporte Minsal indica 4.160 (diferencia 100). Faltando tbn días 28 y 29 de Enero.
![Captura de pantalla 2021-01-30 160337](https://user-images.githubusercontent.com/69001461/106365492-c32e0180-6314-11eb-8525-69645381e0d5.jpg)

**Comment by benjavicente** [comment]
@dafernandez75 Los datos que aparecen en el 30 de Enero son los del 28!

https://web.archive.org/web/20210128221221/https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/

El último commit de la fuente de datos menciona [_Actualización Reporte Diario **2021-01-28**_](https://github.com/MinCiencia/Datos-COVID19/commit/396ced19fbda1e33bc2fb6b2d4d91acfe3596068) y el código que arma el output del producto 13 debe estar usando la fecha actual

**Comment by dafernandez75** [comment]
ok gracias por el alcance... a la espera entonces de la actualización correspondiente que subsane los errores.

**Comment by dna33** [comment]
Es como dice @benjavicente, en unos minutos más voy a corregir todo y dejar actualizado a la fecha de hoy.

**Comment by dafernandez75** [comment]
Ok excelente, favor considerar la actualización de los productos relacionados con el Informe EPI 90 y Anexo defunciones (U071+U072) por publicar en el día de hoy, que a la fecha y hora no lo suben.

**Comment by juancri** [comment]
Gracias, @dna33 !

**Comment by dna33** [comment]
Listo el trabajo del reporte diario en los días faltantes, hasta la fecha. Y subidos también los productos que se actualizan con información del DEIS y el Departamento de Epidemiología (publicados hoy).

**Comment by elaval** [comment]
Cierro el issue

Gracias por corregir e informar

**Comment by Jorgecibia** [comment]
Gracias por la corrección, y muchas felicitaciones por el buen trabajo y disponibilidad de datos que ya llevan bastante tiempo haciendo. gracias
