### ISSUE TITLE
Varios productos afectados - Falta 29/01/2021

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#840]
¡Hola! Quería reportar que en el [producto 14](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto14) faltan los datos del 29/01/2021.

¡Saludos!

**Comment by dna33** [comment]
Corregido, gracias por reportar.

**Comment by adinamarca** [comment]
> Corregido, gracias por reportar.

¡Muchas gracias @dna33 !

**Comment by adinamarca** [comment]
Lo mismo ocurre con el [producto 8](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto8).

Saludos

**Comment by dna33** [comment]
Así es, corregido esta vez completamente: https://github.com/MinCiencia/Datos-COVID19/commit/47036219d5860cbf90790fa619d4d2209f5703b2

**Comment by felipeelorrieta** [comment]
Hola, en el producto 8 también faltan los datos del 25/01/2020. Saludos!

**Comment by dna33** [comment]
Corregido en el update de hoy, gracias por reportar.https://github.com/MinCiencia/Datos-COVID19/commit/29b8215a0411a601108e141f10b96143d7b1b459

**Comment by adinamarca** [comment]
> Corregido en el update de hoy, gracias por reportar.[29b8215](https://github.com/MinCiencia/Datos-COVID19/commit/29b8215a0411a601108e141f10b96143d7b1b459)

¡Gracias a ud. por su gran labor!

¡Saludos!

**Comment by adinamarca** [comment]
Perdón; en el [producto 13](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto13/CasosNuevosCumulativo.csv) faltan los datos del 29/01/2021. Desconozco si hay otros productos afectados.

**Comment by dna33** [comment]
Corregido:

https://github.com/MinCiencia/Datos-COVID19/commit/dad5b47a49d13eca67047537409724455155249a
