### ISSUE TITLE
En Producto 4 falta informe del 29/01/2021

### ISSUE THREAD

**Issue by lvidelam** [MinCiencia/Datos-COVID19#841]
En el producto 4 falta el reporte del 29/01/2021 
![44D24B76-0C16-4DC1-8259-EE6D59E131A3](https://user-images.githubusercontent.com/46109311/106388269-7dc50f00-63bc-11eb-8b0d-4cdcc66ddb31.png)

**Comment by dna33** [comment]
Gracias por reportar, corrected: https://github.com/MinCiencia/Datos-COVID19/commit/043ca5867b9850ddd6fc9f214fc75791270f1f7a
