### ISSUE TITLE
Producto 8: Actualización cambió nombre a región de "O’Higgins" a "Del Libertador General Bernardo O‚ÄôHiggins"

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#842]
Commit 29b8215a0411a601108e141f10b96143d7b1b459 generó un cambio en nombre de región

![image](https://user-images.githubusercontent.com/68602/106400297-3cecea80-63fc-11eb-8666-39b8ef5211da.png)

En el commit anterior (47036219d5860cbf90790fa619d4d2209f5703b2) se indicaba "O’Higgins" (que es consistente con otros productos)
![image](https://user-images.githubusercontent.com/68602/106400352-ac62da00-63fc-11eb-8b30-bac05698810f.png)

**Comment by ivanMSC** [comment]
Sugiero eliminar el campo región en todos los productos y solo dejar el código. Es redundante y un desperdicio de preciados bits.

**Comment by dna33** [comment]
fixed https://github.com/MinCiencia/Datos-COVID19/commit/a92bd9df5eca9d56ba2d3d525e263a9b7a5b87d2, gracias por reportar.
