### ISSUE TITLE
Producto 15 reporte epidemiológico 30 enero sin actualizar

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#843]
Hola, 

Saben cuándo se actualizará el producto 15 del reporte epidemiológico de hace 2 días. No recuerdo que se haya demorado tanto la actualización. 

Ojalá se resuelva pronto.

Saludos cordiales,

**Comment by dna33** [comment]
actualizado, https://github.com/MinCiencia/Datos-COVID19/commit/40ec2f22c4304b899062f046c455fd81a25ce915.
