### ISSUE TITLE
Producto 55 desactualizado

### ISSUE THREAD

**Issue by nibravo** [MinCiencia/Datos-COVID19#844]
Estimados,

El producto 55 entregado por iCovid se encuentra desactualizado desde el 22/01/2021.
No encontré ninguna issue asociada.
¿Se seguirá actualizando?

Agradecido por su respuestaa,
Nicolás Bravo

**Comment by nibravo** [comment]
Actualizado hasta el 29/01/2021 ayer lunes a las 22:00.

Notar que para la positividad nacional cambiaron los datos desde el 01/01/2021 y para la positividad provincial cambiaron todos los datos desde el 19/03/202. No guardé la positividad comunal, pero debido al que el gran tamaño del diff, parece que tambien cambiaron todos los datos.

Muchas gracias por la actualización

**Comment by nibravo** [comment]
Sería importante entender la razón de este reajuste de la positividad nacional, provincial y comunal.

**Comment by MinCiencia** [comment]
Hola, no entiendo bien lo que planteas. ¿Puedes elaborar un poco más en lo que indicas para plantear la pregunta al grupo que produce este resultado?

**Comment by nibravo** [comment]
Saludos,

Viendo el [último commit](https://github.com/MinCiencia/Datos-COVID19/commit/4fc7d7a05414ec5cdd577f5ea2a911a998cc867f#diff-9e5354ef77009abf58ae75d2ba40c592b390a95042c9c1ea8f63b725970ac7a5) que afectó el producto 55, este no solamente agregó datos para las fechas faltantes (23-01-2021 en adelante), sino que también se modificaron valores de positividad para días ya entregados.

En la imagen siguiente se muestra que para el caso de positividad nacional, el commit modificó los valores desde el 01-01-2021.
![imagen](https://user-images.githubusercontent.com/48862200/106656034-e658eb00-6578-11eb-8f99-d1a2c47a854e.png)

Para el caso provincial y comunal, los diff son demasiado grandes para mostrarlos por github, pero el commit modificó valores de este indicador desde un principio.

Por ejemplo, en el [commit anterior](https://github.com/MinCiencia/Datos-COVID19/blob/24d98e6a46fb6f8419658a8f2098612349e82759/output/producto55/Positividad_por_provincia.csv) la Provincia de  Antofagasta tenía una positividad de 0.019645, pero luego de la actualización este valor cambió a 0.0186147.

Muchas gracias por su respuesta.

**Comment by dna33** [comment]
Hola, Alejandro Jara uno de los investigadores del grupo ICOvid aclara "Las series se calculan para cada informe epi desde cero. Los cambios que se observan, que son marginales, se deben al rezago de información con la que se reportan las pruebas de PCR". 

Creo que queda claro, ¿no?
