### ISSUE TITLE
Actualización 2021-02-02 demorada

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#846]
Hola, tenemos dificultades técnicas que estamos resolviendo, en el origen del reporte (no tienen relación con la actualización del registro civil, como pregunta @adinamarca en https://github.com/MinCiencia/Datos-COVID19/issues/845). La hora estimada de actualización será 6 pm.

**Comment by ctroncoso** [comment]
Impeque. También me dio la impresión que no era problema de los actions.  Grax!

**Comment by adinamarca** [comment]
> Hola, tenemos dificultades técnicas que estamos resolviendo, en el origen del reporte (no tienen relación con la actualización del registro civil, como pregunta @adinamarca en #845). La hora estimada de actualización será 6 pm.

¡Gracias por la aclaración! Y por su enorme trabajo.

¡Saludos!

**Comment by Jorgecibia** [comment]
Gracias por la info, buen trabajo estan haciendo, saludos

**Comment by MinCiencia** [comment]
Acabamos de finalizar la actualización correspondiente a hoy 2 de febrero: https://github.com/MinCiencia/Datos-COVID19/commit/7836a0d1bb654f9fb3b894d0d016210ed25cb3c5. Que tengan una buena tarde.
