### ISSUE TITLE
Número de vacunaciones es distinto a lo que muestra DEIS (por que actualizaciones del DEIS no son a una hora fija, este repo se actualiza a las 10 PM hora local)

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#850]
Hola, con el comienzo de la vacunación masiva he revisado los números de vacunados y veo que el producto 76 está entregando números distintos a los que publica DEIS [acá](https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F1a8cc7ff-7df0-474f-a147-929ee45d1900&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false). 

Esto es lo de DEIS
![image](https://user-images.githubusercontent.com/63430031/106917641-38b81a00-66e7-11eb-9116-da5dbb488273.png)

Y esto es lo que arroja el producto 76:
![image](https://user-images.githubusercontent.com/63430031/106919297-c9432a00-66e8-11eb-8b31-880910e93411.png)

Si se mira la distribución diaria se ven las diferencias también:
![image](https://user-images.githubusercontent.com/63430031/106918690-31454080-66e8-11eb-94d6-e119a291f1d1.png)
![image](https://user-images.githubusercontent.com/63430031/106919031-83866180-66e8-11eb-80a1-ecbe3f9061d7.png)

También veo que la distribución diaria cambia si en vez de usar "Total" uso todas las regiones:
![image](https://user-images.githubusercontent.com/63430031/106919156-a31d8a00-66e8-11eb-9d14-176b00a12233.png)

Espero que se pueda arreglar, saludos!

**Comment by dna33** [comment]
@juancri ¿cachaste esto?

**Comment by juancri** [comment]
Hola. Esto tiene probablemente que ver con la hora de actualización.

En particular, para el ejemplo incluido aquí, estos son los horarios de actualización para el día 3 de febrero:

- **[juancri/covid19-vaccination](https://github.com/juancri/covid19-vaccination/commit/c8289b2edbf538ba6d91c5c0900ff38c31795f1d):** 20:49
- **[MinCiencia/Datos-COVID19](https://github.com/MinCiencia/Datos-COVID19/commit/0584990d0a4e426a0e949d576b7b0fbcb7271d7c):** 22:49
- **DEIS (screenshot):** 21:27

Por lo que he observado, no existe un horario fijo para esta actualización en el DEIS. El horario de las 21:00 (00:00) fue elegido originalmente porque es el horario en el que se publica el gráfico de [covid19statsvid](https://twitter.com/covid19statsvid).

Por lo que veo ahora, la actualización en el sitio web del DEIS ocurrió a las 21:49. ¿Es posible confirmar un horario de corte con el DEIS? SI no es así, otra alternativa sería correr el proceso más cercano a las 00:00 hora de Chile para asegurar que todas las actualizaciones del día fueron incluidas.

**Comment by ivanMSC** [comment]
No se puede tener un bot monitoreando el sitio de deis y que extraiga los datos cuando hay nuevos? Es scrapeable el sitio?

**Comment by juancri** [comment]
@ivanMSC hay un paso manual para obtener la URL del archivo JSON. De todas formas, con el cambio para incluir datos retroactivamente, las fechas anteriores se actualizarían una vez al día.

**Comment by ivanMSC** [comment]
@juancri y ese paso manual, alguna idea de como automatizarlo? Estuve sapeando la página y se ve complicado.

**Comment by juancri** [comment]
No he encontrado la forma aún.

**Comment by juancri** [comment]
Por ahora, considerando que ha habido actualizaciones pasadas las 9PM durante días anteriores, voy a correr el proceso a las 10PM (hora de Santiago).

**Comment by juancri** [comment]
Esto debería estar corregido por https://github.com/juancri/covid19-vaccination/issues/11

**Comment by juancri** [comment]
@dna33 creo que ya se puede cerrar este issue
