### ISSUE TITLE
Posible error en fecha de Reporte Epidemiológico #92 (4 Febrero o 5 Febrero)

### ISSUE THREAD

**Issue by dataCovid19CL** [MinCiencia/Datos-COVID19#851]
Para el informe epidemiológico que se publica los días Sábado se suele publicar datos con fecha del día Viernes (aunque al interior del informe se especifica que corresponde al día Jueves)

El informe #92 publicado hoy por el Minsal indica fecha 4 Febrero (Jueves) en su primera página los informes anteriores suelen indicar la fecha del Viernes

![image](https://user-images.githubusercontent.com/78309057/107133423-b2f2c500-68c6-11eb-84db-fd980bfb7259.png)

En su interior se indica que los datos son provisorios al día 4 de Febrero
![image](https://user-images.githubusercontent.com/78309057/107133440-d9186500-68c6-11eb-8557-d8000472075d.png)

En el repositorio github se publicaron tablas con datos al jueves 4 de Febrero, lo que no es consistente con las publicaciones previas

![image](https://user-images.githubusercontent.com/78309057/107133479-504df900-68c7-11eb-8fef-85360029484b.png)

Por ejemplo el Sábado 30 de Enero se publicó un informe EPI con fecha Viernes 29 de Enero que en su interior indicaba que los datos eran del Jueves 28 de Enero

![image](https://user-images.githubusercontent.com/78309057/107133508-b63a8080-68c7-11eb-8adb-9736925f610f.png)

Intuyo que fue un error poner fecha 4 de Enero en la portada del informe EPI (no es consistente con los anteriores) y este error se replicó en las tablas del repositorio

Este desfase en la serie de tiempo tiene importantes consecuencias en el análisis que se hace de los datos.

El aumento de casos semanales por comuna se calcula asumiendo que hay una distancia de 7 días entre informes subsiguientes.

Agradecería chequear con el Ministerio de Salud si fue un error poner fecha 4 de Febrero en informe EPI

**Comment by dna33** [comment]
Enviamos la consulta al equipo del Departamento de Epidemiología de la DIPLAS (MINSAL), entregaremos la respuesta por esta via. Gracias por reportar.

**Comment by dna33** [comment]
Nos confirman desde MINSAL que efectivamente ha habido un error en la portada del informe, los datos están correctos. Nosotros corregimos en el commit https://github.com/MinCiencia/Datos-COVID19/commit/98ca1bcc6b063635d2ff7875ff4723e480b2f0d3. El MINSAL va a corregir la publicación a más tardar el lunes a primera hora en su pagina web.
