### ISSUE TITLE
Cambio de la primera columna del producto 23

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#852]
[Este commit](https://github.com/MinCiencia/Datos-COVID19/commit/a57fc21fc82ddd8f461b94b314558dcbb5a97180#diff-e620df399d71e2ee8cc20cd7fc5ca460ece11e0a1b1417b0ed5c844c4547cc04) cambió el nombre de la primera columna de los archivos del producto 23 desde ***Casos*** a ***Variable***. Sólo megustaría saber si es un cambio planificado y permanente o solo un error.

**Comment by dna33** [comment]
Gracias, nos debatimos sobre si publicar un anuncio o no. Al actualizar la fuente del producto para completar su atumatizacion evaluamos que la construcción tenia ciertos errores que corregimos, estos se even reflejados en la versión sed principalmente.

**Comment by juancri** [comment]
Perfecto, gracias.
