### ISSUE TITLE
Sugiero enriquecer datos de avance en vacunación

### ISSUE THREAD

**Issue by dataCovid19CL** [MinCiencia/Datos-COVID19#854]
DEIS publica tablas con datos de vacunación por grupos de edad, región y genero

Sugiero incluir tablas con estos datos (al menos por grupo de edad) que se actualicen diariamente

**Comment by juancri** [comment]
Está en proceso como parte de [este issue](https://github.com/juancri/covid19-vaccination/issues/8).

Relacionados:
- [Publicar formato que incluye grupos de vacunación](https://github.com/juancri/covid19-vaccination/issues/5)
- [Publicar formato que incluye el tipo de vacuna](https://github.com/juancri/covid19-vaccination/issues/6)
- [Actualizar fechas anteriores](https://github.com/juancri/covid19-vaccination/issues/7)

**Comment by juancri** [comment]
Aún está pendiente el proceso de los datos por grupo y edad. Más info aquí:

https://github.com/juancri/covid19-vaccination/issues/5

**Comment by dna33** [comment]
Con la ayuda de @juancri agregamos grupos de vacunación y rangos erarios que se actualizan diariamente.

Agregaremos los datos históricos también en colaboración con DEIS en los próximos días.

Muchas gracias a todos los involucrados en este proceso. Buen trabajo!

**Comment by juancri** [comment]
@dna33 ¿hay alguna fecha estimada en que el DEIS comenzará a enviar los datos directamente? También, ya que estás en contacto con ellos, ¿es posible que nos avisen en caso de que ocurra un gran cambio de formato como el que sucedió esta semana? Gracias!

**Comment by MinCiencia** [comment]
Ya estamos integrados, escribí los prototipos [en este mensaje](https://github.com/MinCiencia/Datos-COVID19/issues/870#issuecomment-782859852).

Queda un trabajo por hacer, DEIS no esta guardando la historia del avance desglosado por edad y sexo, ni por grupo, ni por edad y región. Queremos mantener la alimentación de "la foto por dia" en estos 3 archivos (https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/fabricante.csv, https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/grupo.csv, https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/rango_etario.csv) con este nuevo input, eso esta pendiente aun. Una solucion posible es que @juancri uses en vez de DEIS, los nuevos productos 77, 78 y 79 para alimentar esa foto.

**Comment by luismbriones** [comment]
Estimados, alguien tiene noticias si se subirán acá los datos de vacunación por comuna?

**Comment by MinCiencia** [comment]
Si, durante este fin de semana vamos a trabajar en eso. Proyectamos tenerlo arriba el domingo.

**Comment by juancri** [comment]
Por el momento, están publicados aquí:

https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-comunas.csv

**Comment by dna33** [comment]
Como indica https://github.com/MinCiencia/Datos-COVID19/issues/879

Agregamos los siguientes productos, en integración con DEIS -se actualizan 2 veces al día, en el reporte diario (alrededor de medio día) y al final del día laboral de MINSAL (alrededor de las 7 pm):

[Data Product 76 - Avance regional en Campaña de Vacunación COVID-19](output/producto76):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel regional. [Ver más](output/producto76)

[Data Product 77 - Avance por rango etario y región en Campaña de Vacunación COVID-19](output/producto77):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por rango etario y región. [Ver más](output/producto77)

[Data Product 78 - Avance por sexo y edad en Campaña de Vacunación COVID-19](output/producto78):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por edad (en años) y sexo. [Ver más](output/producto78)

[Data Product 79 - Avance por grupo prioritario en Campaña de Vacunación COVID-19](output/producto79):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por criterio y sub criterio de prioridad. [Ver más](output/producto79)

[Data Product 80 - Avance comunal en Campaña de Vacunación COVID-19](output/producto80):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel comunal. [Ver más](output/producto80)
