### ISSUE TITLE
Registros históricos fase 2

### ISSUE THREAD

**Issue by storresl** [MinCiencia/Datos-COVID19#855]
Hola,

Me sería útil contar con registros históricos de fase 2 por comuna. ¿Alguien sabe donde partir? 

Saludos,

**Comment by paarriagadap** [comment]
Hola, revisa el [producto 76](https://www.github.com/MinCiencia/Datos-COVID19/tree/master/output%2Fproducto74). De ahí lo podrías sacar.

**Comment by storresl** [comment]
Gracias! No conocía ese producto. Saludos.
