### ISSUE TITLE
Producto 40 no se actualiza hace más de un mes

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#856]
Hola, el [producto 40](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto40), sobre transporte aéreo de pasajeros no se ha actualizado desde el 27 de diciembre, con información hasta la semana del 14 al 20 de diciembre. He estado siguiendo esa información en mi tablero [acá](https://public.tableau.com/views/Coronavirus_15857831577770/TransporteareoenChile?%3Aembed=y&%3Aembed=y&%3AshowVizHome=no&%3AshowVizHome=n&%3Adisplay_count=y&%3Adisplay_static_image=y&%3Alanguage=es&%3AapiID=host0#navType=0&navSrc=Parse&1):

![image](https://user-images.githubusercontent.com/63430031/107380524-b48dda00-6acc-11eb-909d-ff657530172b.png)

Saludos!

**Comment by dna33** [comment]
Había un problema en la api de JAC que cambió el formato en que entrega las fechas, lo actualizamos y reparamos la automatización:

https://github.com/MinCiencia/Datos-COVID19/commit/788d5a314d2f06784b7c1db1b59fb3dab91071d8
