### ISSUE TITLE
No aparece ninguna provincia de Aysén en el producto 54

### ISSUE THREAD

**Issue by syunusic** [MinCiencia/Datos-COVID19#861]
No aparece ninguna provincia de Aysén en el producto 54. ¿es por alguna razón en especial?

**Comment by dna33** [comment]
Hola,

Nos comentan desde ICOVID que se debía a que en los meses pasados la cantidad de casos no era suficiente parta estimar el Re en esas provincias. Sin embargo, desde hace algún tiempo la cantidad de casos si permite su estimación y se debió incluir, pero no se había revisado la situación. Las incluiremos en la nueva carga de datos.
