### ISSUE TITLE
Sincronización con fuente de datos de vacunación

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#862]
No alcancé a correr el proceso en la noche del miércoles 10/02. El sitio del DEIS está teniendo errores en estos momentos, pero ha sucedido antes y parecen ser intermitentes.

Una vez que estén los datos actualizados en [juancri/covid19-vaccination](https://github.com/juancri/covid19-vaccination/tree/master/output), ¿podemos correr el proceso de sincronización de alguna forma? Sería ideal si hubiera algún webhook que podamos invocar cuando el archivo de origen se actualiza. De todas formas, voy a dejar un comentario aquí cuando esté actualizado hoy.

Gracias!

**Comment by juancri** [comment]
[archivo origen](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination.csv) actualizado

**Comment by dna33** [comment]
Actualizado acá, podemos hacer algo como esto https://github.com/MinCiencia/Datos-COVID19/blob/master/.github/workflows/UC.yml

Sincroniza rutas específicas entre 2 repos.

**Comment by juancri** [comment]
@dna33, perfecto. Estoy con muy poco tiempo, pero lo reviso el fin de semana.

**Comment by dna33** [comment]
Done: https://github.com/MinCiencia/Datos-COVID19/commit/03d582e221618638c0170fc2208307b374f49e77
