### ISSUE TITLE
Incorporar tipo de vacuna en datos de vacunación

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#865]
Desde hoy, en el repo [covid19-vaccination](https://github.com/juancri/covid19-vaccination/issues/6) se publica un formato que incluye el tipo de vacuna: [chile-vaccination-type.csv](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-type.csv)

Issue: https://github.com/juancri/covid19-vaccination/issues/6

[Más info sobre los formatos](https://github.com/juancri/covid19-vaccination/blob/master/output/README.md)

**Comment by dna33** [comment]
Excelente, añadimos nuevo producto por fabricante basado en tu output. Muchas gracias!

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto76
