### ISSUE TITLE
producto 48: Camas totales intermedio < Camas ocupadas intermedio??

### ISSUE THREAD

**Issue by martinezpp** [MinCiencia/Datos-COVID19#866]
Hola, creo que están mal calculados los datos del producto 48 (SOCHIMI_std.csv) 
Por ejemplo: 2020-06-10; SS METROPOLITANO NORTE; Metropolitana
Tiene 305 Camas ocupadas intermedio y 199 Camas totales intermedio.

**Comment by dna33** [comment]
Hola, ese producto fue descontinuado por la Sociedad Chilena de Medicina Intensiva hace algunos meses, por favor usa estos que tienen como fuente el Ministerio de Salud:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto52

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto58

**Comment by martinezpp** [comment]
Gracias Demian, pero necesito los datos desagregados por sector, no a nivel de region. Sera posible que se verifiquen los datos del producto 48, o que se genere un nuevo producto usando los datos del Ministerio de Salud, pero mas desagregados (o sea que el sector sea incluido)? Tampoco es clara la descripción del producto 48 a si son solo servicios de saludos públicos o ambos (públicos y privados)

**Comment by dna33** [comment]
@fzmolina trabaja en la fundación ciencia y vida, quienes desarrollaron este producto junto con SOCHIMI. Quizás ella puede ayudarnos a aclarar esta situación.
