### ISSUE TITLE
Registros repetidos últimos 3 días en producto 76 (datos Vacunación por grupo y rango etareo)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#870]
Hay registros repetidos en días 2021-02-16, 2021-02-17, 2021-02-18

Para datos de cobertura de vacunación por grupo y rango etareo

![BDF8F0A2-35FF-4B80-BE62-29611B83D2D3](https://user-images.githubusercontent.com/68602/108501673-69c04f00-7290-11eb-92e7-bc1bc3396b0e.png)

**Comment by juancri** [comment]
Sospecho que para estos casos, el DEIS cambia el informe todos los días y nosotros estamos obteniendo el mismo del día anterior. Lo puedo investigar durante el fin de semana probablemente.

**Comment by dna33** [comment]
@juancri creo que es porque tu archivo no se esta actualizando.

**Comment by juancri** [comment]
@dna33 sí. Trackeado aquí: https://github.com/juancri/covid19-vaccination/issues/16

**Comment by juancri** [comment]
En el repositorio original se corrigieron todos los archivos a excepción de `chile-vaccination-groups.csv`

**Comment by MinCiencia** [comment]
Hola @juancri:

1. chile-vaccination-type.csv se ve **OK**
2. chile-vaccination.csv se ve **OK**
3. chile-vaccination-ages.csv **not OK**
4. chile-vaccination-groups.csv **not OK**

**Comment by juancri** [comment]
Puedes elaborar sobre el punto 3? El 4 es known issue.

**Comment by MinCiencia** [comment]
Estamos terminando de implementar el vinculo directo con las bd de DEIS, en paralelo. Puedes revisar los resultados en:

1. chile-vaccionation.csv es ahora este: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion.csv, https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion_T.csv, y https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion_std.csv
2. por edad y region: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto77
3. por edad y sexo: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78
4. por grupo prioritario: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto79

**Comment by felipetodev** [comment]
A que se debe que grupos etarios cambiaran su rango en columna 'Rango_etario'? el posible normalizarlo y no duplicar las filas?

**Comment by juancri** [comment]
> chile-vaccination-ages.csv not OK, faltan los dias entre el 17 y el 21 de febrero.

Resultado esperado. El DEIS no publica datos retroactivamente para grupos etarios.

> A que se debe que grupos etarios cambiaran su rango en columna 'Rango_etario'? es posible normalizarlo y no duplicar las filas?

El DEIS cambió la definición de los rangos etarios a publicar. Hasta donde sé, no hay forma de normalizarlos ya que los grupos nuevos no son solo subconjuntos o superconjuntos de los grupos antiguos.

**Comment by MinCiencia** [comment]
muchas gracias @juancri. Vamos a tratar de conseguir los valores que faltan. Sobre los rangos etarios, una vez consigamos los valores que faltan, quizas podrias reconstruir los rangos etarios desde el nuevo producto77. Avisaremos acá cuando tengamos los valores históricos.

**Comment by dna33** [comment]
Nuevos productos de vacunación publicados:
[Data Product 76 - Avance regional en Campaña de Vacunación COVID-19](output/producto76):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel regional. [Ver más](output/producto76)

[Data Product 77 - Avance por rango etario y región en Campaña de Vacunación COVID-19](output/producto77):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por rango etario y región. [Ver más](output/producto77)

[Data Product 78 - Avance por sexo y edad en Campaña de Vacunación COVID-19](output/producto78):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por edad (en años) y sexo. [Ver más](output/producto78)

[Data Product 79 - Avance por grupo prioritario en Campaña de Vacunación COVID-19](output/producto79):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por criterio y sub criterio de prioridad. [Ver más](output/producto79)

[Data Product 80 - Avance comunal en Campaña de Vacunación COVID-19](output/producto80):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel comunal. [Ver más](output/producto80)
