### ISSUE TITLE
Problema con producto 32

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#871]
_***Posteado originalmente el 15-02 en #825 (ya cerrado)**_

Hola, ha pasado de nuevo que la actualización de defunciones del Registro Civil entrega un número inusual. Después de varios días en que el valor de defunciones no se actualizaba, hoy cambió bastante para las últimas semanas. Como de nuevo me llamó la atención saqué la info de la plataforma del Registro Civil y hay discrepancias:

![image](https://user-images.githubusercontent.com/63430031/107986172-45235900-6faa-11eb-8074-59c1b241c3a5.png)
![image](https://user-images.githubusercontent.com/63430031/107986195-4f455780-6faa-11eb-8678-bd476dc976df.png)

Esta vez no me explico el salto de la línea naranja (el producto 32), porque entre los DO no hay ninguno que llegue a un valor inusualmente alto. Quizás tiene que ver con una agregación en el cambio de quincena que falla. Los datos que saqué del Registro Civil hoy son entre el 01-01-2020 y el 14-02-2021.

Espero que se pueda arreglar, saludos.

_Originally posted by @paarriagadap in https://github.com/MinCiencia/Datos-COVID19/issues/825#issuecomment-779411705_

**Comment by MinCiencia** [comment]
puedes probar ahora? A todo esto, en tu imagen la curva naranja titulada "minciencia", a que corresponde?

**Comment by paarriagadap** [comment]
Hola, veo que el salto prácticamente ya no está en la primera quincena de febrero, pero sí hay uno más chico que el de antes para la segunda quincena:
![image](https://user-images.githubusercontent.com/63430031/109507487-8ec97480-7a7d-11eb-8edd-a69b6f6d0970.png)
![image](https://user-images.githubusercontent.com/63430031/109507515-9721af80-7a7d-11eb-81d3-2c3263aef9ba.png)

La curva naranja que dice Min Ciencia es lo que está (y estaba) en el output del producto 32, así comparo con lo que sale del portal de datos del Registro Civil (azul) y los otros colores son los inputs de este github.

**Comment by paarriagadap** [comment]
Veo que hicieron un cambio y ahora mismo lo que muestra el producto 32 es exactamente lo mismo que lo que muestra el portal de datos del Registro Civil:
![image](https://user-images.githubusercontent.com/63430031/109514940-4b730400-7a85-11eb-9bb7-bce0c7548620.png)

**Comment by paarriagadap** [comment]
Hola, perdón por la insistencia, pero después de que los gráficos se acoplaran bien hace 5 días, los días siguientes los datos no cambiaron y cuando sí lo hicieron hoy nuevamente se generó un desacople que puede llevar a que quienes usen los datos del P32 terminen desinformando:
![image](https://user-images.githubusercontent.com/63430031/110211668-6de69200-7e76-11eb-845c-da25841b8df7.png)

No sé cómo se puede arreglar, espero que se pueda encontrar el problema.

**Comment by dna33** [comment]
Todo lo contrario, gracias por la insistencia. Ha faltado espacio para revisar adecuadamente este codigo:

https://github.com/MinCiencia/Datos-COVID19/blob/master/src/registroCivil.py

**Comment by paarriagadap** [comment]
Hola, he visto que aunque no ha hecho una nueva actualización, el Financial Times usa la información errónea que está entregando este producto: se ve en el salto que está hacia el final del gráfico que llega a febrero. Ya no está así por las correcciones, pero si ellos actualizan tomarán los (aún mayores) saltos que se han acumulado las últimas semanas.
![image](https://user-images.githubusercontent.com/63430031/113308858-f7a24780-92dc-11eb-8cab-9cc11af47eaf.png)

**Comment by dna33** [comment]
Hoy corrí una actualización para los registros del año 2021, sigo sin entender por qué se produce el desfase, el código debería corregirlo.

**Comment by paarriagadap** [comment]
Hola, vi que hace unas semanas en el FT actualizaron sus datos de exceso de muertes y me parece que han tomado el "ascenso artificial" que aparece en el producto 32.
![image](https://user-images.githubusercontent.com/63430031/119519462-7056da80-bd47-11eb-87d2-4ddedcaa8195.png)

Así se ve en estos momentos la comparación entre lo que se saca del portal estadístico del Registro Civil y lo que se saca del P32:
![image](https://user-images.githubusercontent.com/63430031/119519769-b449df80-bd47-11eb-8549-294a93ed20ce.png)
![image](https://user-images.githubusercontent.com/63430031/119519805-bc098400-bd47-11eb-9c70-a57eebba9e34.png)

**Comment by mpaulacaldas** [comment]
Hola! Quizás está relacionado, pero puede que este aumento artificial sea causado por unos duplicados que hay en el producto a nivel del día y comuna (estoy usando `Defunciones_std.csv`). Por lo que he notado, los duplicados solo aparecen a partir de 2021. Dejo aquí un ejemplo con R importando la versión más reciente de los datos:

``` r
suppressPackageStartupMessages(library(dplyr))

prod32 <- read.csv(
  "https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto32/Defunciones_std.csv", 
  encoding = "UTF-8"
  )

duplicados <- prod32 %>% 
  group_by(across(-Defunciones)) %>% 
  filter(n() > 1) %>% 
  ungroup() %>% 
  arrange(Fecha, Codigo.comuna) %>% 
  select(Fecha, Comuna, Defunciones)

head(duplicados)
#> # A tibble: 6 x 3
#>   Fecha      Comuna               Defunciones
#>   <chr>      <chr>                      <int>
#> 1 2021-01-27 Colina                         0
#> 2 2021-01-27 Colina                         1
#> 3 2021-02-01 San Juan de la Costa           1
#> 4 2021-02-01 San Juan de la Costa           6
#> 5 2021-02-08 Castro                         5
#> 6 2021-02-08 Castro                         4

range(sort(duplicados$Fecha))
#> [1] "2021-01-27" "2021-04-29"
```

<sup>Created on 2021-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
