### ISSUE TITLE
Falló actualización 21/02/2021

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#872]
Hola. Al parecer, [la actualización de hoy está fallando](https://github.com/MinCiencia/Datos-COVID19/commit/fcfa533c47862d52e1f962d10afb3b227000f0b9).

Saludos.

**Comment by ctroncoso** [comment]
Fallo se produjo por error en cálculo de población de comunas 
[reporteDiario.py#Producto 47-Linea 571](https://github.com/MinCiencia/Datos-COVID19/blob/fcfa533c47862d52e1f962d10afb3b227000f0b9/src/reporteDiario.py#L571)
![image](https://user-images.githubusercontent.com/121016/108632257-bd779780-744c-11eb-9d6b-f32a611b9d00.png)

**Comment by ctroncoso** [comment]
Explorando más, en la linea 564, al hacer el merge, se duplican las regiones de Magallanes, ya que en una tabla es "Magallanes" y en la otra es "Magallanes y de la Antártica Chilena" generando 18 regiones 0->17
Este es el producto del merge (mediamovil)
Chocan la 10 y la 17
Falta normalizar nombres previo al merge o en su defecto, operar bajo código de región.

```
                                  Region  Codigo region   Poblacion  ...  2021-02-19  2021-02-20  2021-02-21
0                            Antofagasta            2.0    691854.0  ...       237.0       256.0       212.0
1                     Arica y Parinacota           15.0    252110.0  ...        96.0        83.0        92.0
2                                Atacama            3.0    314709.0  ...        40.0        93.0        88.0
3                                  Aysén           11.0    107297.0  ...        27.0        28.0        17.0
4                                 Biobío            8.0   1663696.0  ...       481.0       541.0       485.0
5                               Coquimbo            4.0    836096.0  ...       146.0       160.0       181.0
6                              Araucanía            9.0   1014343.0  ...       293.0       359.0       284.0
7                              O’Higgins            6.0    991063.0  ...       168.0       144.0       151.0
8                              Los Lagos           10.0    891440.0  ...       312.0       336.0       244.0
9                               Los Ríos           14.0    405835.0  ...       202.0       141.0       209.0
10  Magallanes y de la Antártica Chilena           12.0    178362.0  ...         NaN         NaN         NaN
11                                 Maule            7.0   1131939.0  ...       285.0       283.0       303.0
12                         Metropolitana           13.0   8125072.0  ...       910.0       806.0       806.0
13                              Tarapacá            1.0    382773.0  ...       108.0       117.0       126.0
14                            Valparaíso            5.0   1960170.0  ...       338.0       348.0       239.0
15                                 Ñuble           16.0    511551.0  ...        95.0       130.0       104.0
16                                 Total            NaN  19458310.0  ...      3827.0      3893.0      3618.0
17                            Magallanes            NaN         NaN  ...        89.0        68.0        77.0

```

Ahora, al tener 18 regiones, en el for de la 570, se excede el index, y por supuesto, no se actualizan as columnas correctas.

**Comment by MinCiencia** [comment]
Gracias por los avisos y la revisión, muy útil. Rompimos sin darnos cuenta el utils.py que corrige nombres de región para no generar duplicaciones, echando a perder el update automático de hoy. Corregido en este _commit_:https://github.com/MinCiencia/Datos-COVID19/commit/85bf565d6136fd7a12ec4655a914348610b7a86c

**Comment by ctroncoso** [comment]
> Gracias por los avisos y la revisión, muy útil. Rompimos sin darnos cuenta el utils.py que corrige nombres de región para no generar duplicaciones, echando a perder el update automático de hoy. Corregido en este _commit_:[85bf565](https://github.com/MinCiencia/Datos-COVID19/commit/85bf565d6136fd7a12ec4655a914348610b7a86c)

Sucede. Cuando se mueve el alfil para atacar al rey, se olvida que ese alfil estaba protegiendo a la reina. :+1: 
Lo importante es agarrarlos a tiempo. Gracias por todo el trabajo!

PD: paso el aviso... necesitamos urgentemente los valores del numerador y denominador de el producto 64. Practico tener la proporción, pero si no tenemos en N, no nos es muy útil. Se  podrían agregar esas 2 columnas?

**Comment by adinamarca** [comment]
¡Gracias a tod@s!
