### ISSUE TITLE
Nuevas defunciones 23-02 faltante

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#873]
Hay retraso en la carga de esto?

**Comment by adinamarca** [comment]
> Hay retraso en la carga de esto?

Así parece, las cifras del reporte diario del Minsal tampoco han sido actualizadas. :(

**Comment by MinCiencia** [comment]
Hola, estamo retrasados con la actualizacion de hoy. Hay un cambio en el reporte diario que estamos recomendando revertir, y en el intertanto adaptando el codigo. Deberiamos tener lo segundo solucionado en unos minutos.

**Comment by adinamarca** [comment]
> Hola, estamo retrasados con la actualizacion de hoy. Hay un cambio en el reporte diario que estamos recomendando revertir, y en el intertanto adaptando el codigo. Deberiamos tener lo segundo solucionado en unos minutos.

¡Hola! Muchas gracias por la respuesta y por el trabajo que realizan día a día. ¡Saludos!

**Comment by ctroncoso** [comment]
> Hola, estamo retrasados con la actualizacion de hoy. Hay un cambio en el reporte diario que estamos recomendando revertir, y en el intertanto adaptando el codigo. Deberiamos tener lo segundo solucionado en unos minutos.

Impecable, todo ok!
