### ISSUE TITLE
Cambio en el Producto 9 el 2021-02-23 (Pacientes COVID-19 en UCI por grupo de edad)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#874]
La suma de pacientes por grupos de edad da una cifra mayor al total de pacientes COVID19 ese día.  El total informado es 1640 y la suma de los grupos de edad es 2161.

(En producto 8 la suma de totales por región da la cifra correcta)

![image](https://user-images.githubusercontent.com/68602/108931470-7cd37600-7626-11eb-8cfa-38d458b5a2af.png)

**Comment by dna33** [comment]
Corregido, con el siguiente comentario que vamos a incorporar en la documentación: el total es menor ahora, se cambia la fuente de información, ya no es el sistema de ugcc sino encuesta diaria realizada por subsecretaria de redes asistenciales. Estamos trabajando en la documentación nueva.

**Comment by ctroncoso** [comment]
> Corregido, con el siguiente comentario que vamos a incorporar en la documentación: el total es menor ahora, se cambia la fuente de información, ya no es el sistema de ugcc sino encuesta diaria realizada por subsecretaria de redes asistenciales. Estamos trabajando en la documentación nueva.

¿Hubo alguna razón para el cambio? La UGCC con el sistema RightNow es bastante más fiable que una encuesta, ya que por cada registro, hay un paciente con rut asociado a una cama ocupada, mientras que una encuesta es bastante más "flexible" en términos de respuesta.

**Comment by MinCiencia** [comment]
El subsecretario Dugnac explicó el cambio en búsqueda de tener información más actualizada, sacrificando la precisión del rango etario en pos de aumentar la resolución temporal y precisión del dato respecto de ocupación.

**Comment by ctroncoso** [comment]
> El subsecretario Dugnac explicó el cambio en búsqueda de tener información más actualizada, sacrificando la precisión del rango etario en pos de aumentar la resolución temporal y precisión del dato respecto de ocupación.

Gracias, esperemos que tenga razón.
