### ISSUE TITLE
Defunciones 27 feb no actualizado.

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#878]
Hola! Se tiene estimado de hora para cuando estarán las defunciones de hoy?
Saludos y gracias por todo el trabajo!

**Comment by dna33** [comment]
Hola, actualizado con la información del DEIS publicada hoy.

**Comment by ctroncoso** [comment]
Extraño, no viene lo informado el 27. Esperaremos al de hoy. Grax!
