### ISSUE TITLE
Nuevos productos de la campaña de vacunación

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#879]
Nuevos productos de vacunación publicados:
[Data Product 76 - Avance regional en Campaña de Vacunación COVID-19](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto76):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel regional. [Ver más](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto76)

[Data Product 77 - Avance por rango etario y región en Campaña de Vacunación COVID-19](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto77):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por rango etario y región. [Ver más](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto77)

[Data Product 78 - Avance por sexo y edad en Campaña de Vacunación COVID-19](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por edad (en años) y sexo. [Ver más](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78)

[Data Product 79 - Avance por grupo prioritario en Campaña de Vacunación COVID-19](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto79):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 por criterio y sub criterio de prioridad. [Ver más](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto79)

[Data Product 80 - Avance comunal en Campaña de Vacunación COVID-19](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto80):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel comunal. [Ver más](https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto80)

**Comment by paarriagadap** [comment]
Excelente, muchas gracias. En cuanto a la información comunal, creo que es necesario enriquecerla aún más, para poder ver si las diferencias que se están viendo en la Región Metropolitana se deben a la composición etaria de las comunas o a otros factores. Por ahora, esta foto es incompleta:
![image](https://user-images.githubusercontent.com/63430031/109421857-da194f80-79b7-11eb-982e-00339413f8c8.png)

**Comment by dna33** [comment]
Sirve agregar el rango etario por comuna?

**Comment by ctroncoso** [comment]
> Sirve agregar el rango etario por comuna?

Si, sería muy potente tener el rango etario por comuna, y quien no lo necesite, puede agrupar para tenerlo sin rango etario. +1.

**Comment by paarriagadap** [comment]
Sí, idealmente como una nueva columna en el producto 80, que permita distribuir las dosis y la población entre los grupos etarios. "Más idealmente", todos los otros datos, como grupos prioritarios, sexo, edad o fabricante podrían estar juntos en el mismo producto 80.

**Comment by juancri** [comment]
Tal vez les interese
https://github.com/juancri/covid19-vaccination/issues/24

**Comment by dna33** [comment]
gracias @juancri, añadimos este nuevo producto con la vacunacion por edad, lista desde 15 a "80 años y más":

[Data Product 81 - Avance comunal por edad en Campaña de Vacunación COVID-19](output/producto81):
Este producto da cuenta del avance en la campaña de vacunación contra Sars-Cov-2 a nivel comunal por edad. [Ver más](output/producto81)

**Comment by paarriagadap** [comment]
Gracias, @juancri y gracias por el producto 81, @dna33. Parece que las edades quedaron en un campo "Fecha" que desapareció. 

Aún creo que es necesario obtener el total de población por grupo etario ("población objetivo") para poder comparar, veo que está disponible en la plataforma de DEIS. Por ejemplo acá está filtrado Talcahuano:
![image](https://user-images.githubusercontent.com/63430031/109425255-2f5c5d80-79c6-11eb-9bb8-fce85725cd3c.png)

**Comment by dna33** [comment]
Vamos a añadir un archivo auxiliar en el producto que incluya la población objetivo por edad (o rango etario 80 y mayores).

No contamos con los valores parciales por fecha en este caso, solo el ultimo acumulado publicado.

**Comment by dna33** [comment]
Hecho: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto81/poblacion_comuna_edad.csv, https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto81/poblacion_comuna_edad_T.csv y https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto81/poblacion_comuna_edad_std.csv

**Comment by paarriagadap** [comment]
Muchas gracias. Agradecería que el campo "Fecha" se renombre a "Edad" o algo parecido en los dos tipos de archivo del P81, puede que si lo cambian después la gente tenga problemas cuando cargue el archivo. También en el de población la variable "Población" sale dos veces.

Saludos, y muchas gracias de nuevo

**Comment by MinCiencia** [comment]
Es verdad, los std estaban mal formulados, han sido corregidos ahora.

**Comment by paarriagadap** [comment]
Gracias, falta una última modificación, creo: ahora los archivos de población y de primera dosis son exactamente iguales y aún no es posible calcular la proporción de vacunados por grupo de edad.

Muchas gracias nuevamente.

**Comment by MinCiencia** [comment]
Hola, puedes elaborar un poco más, no entindo lo que dices.

**Comment by paarriagadap** [comment]
Que entiendo que el producto 81 se separa en 3 archivos: uno para cada dosis y otro para la población objetivo que hay para cada edad. Pasa que en estos momentos el archivo de la primera dosis es igual al de la población objetivo, con lo que no se puede obtener la proporción de vacunados por grupo etario (porque daría todo 100%).

**Comment by MinCiencia** [comment]
Es cierto, estabamos tomando mal las columnas del input, poniendo poblacion como 1era dosis y 1era dosis como segunda, sin pescar 2da dosis. Ahora los archivos del producto 81 estan correctos. Gracias por reportar.

**Comment by paarriagadap** [comment]
Muchas gracias a ustedes, funciona perfecto ahora.
