### ISSUE TITLE
Disponibilizar data products en formato estándar (unpivoted)

### ISSUE THREAD

**Issue by ivanMSC** [MinCiencia/Datos-COVID19#88]
Hasta ahora, en este repositorio se disponibilizan las series de tiempo en dos formatos, uno donde las fechas son columnas y otro formato que le llaman transpuesto (donde las fechas son filas, pero las comunas son columnas???). 

Ambos formatos son del tipo conocido como pivoteado (e.g. tablas dinámicas) donde un campo de la base de datos se expande en columnas. Esto tiene ventajas pero solo desde un punto de vista de visualización de los datos. Es decir, sirve si uno desea abrir el archivo csv y buscar cosas al ojo.

Para facilitar el manejo y uso de datos quisiera solicitar la disponibilización de datos en formato estándar. A diferencia de los dos formatos ya disponibles, en el formato estándar (o unpivoted) tanto fechas como comunas estarían en **filas**. Por ejemplo, para cada par fecha/comuna corresponde un registro en la base de datos. Entonces, el Data Product 1 tendría la siguiente estructura:

`Fecha, Region, Codigo Region, Comuna, Codigo Comuna, Poblacion, Casos Confirmados`
`2020/03/30, Arica y Parinacota, 15, Arica, 15101, 247552,  6`
`2020/04/01, Arica y Parinacota, 15, Arica, 15101, 247552,  6`
...
`2020/03/30, Magallanes, 12, Torres del Paine, 12402, 1021, 0`
`2020/04/01, Magallanes, 12, Torres del Paine, 12402, 1021,  0`
...

Una sola columna de fechas, una sola columna de comunas, y una sola columna de casos confirmados. 

No sé si me explico.

Me he referido para ejemplificar al data product 1 (fechas, comunas), pero este issue abarca a todos los dp que son series de tiempo (creo que serian todos en realidad).

**Comment by Leandermen** [comment]
Comparto el planteamiento, la idea es que la base de datos posea una estructura estable y robusta en el tiempo, en especial si se está consumiendo en línea, si en modelos de base de datos se añadiera una columna por región o por fecha el modelo mutaría contínuamente. El planteamiento de @ivanMSC es tratar cada dato como una transacción en una base de datos que crezca solo en registros no en columnas.
Otro beneficio es que si esto a futuro se lleva a una API de servicios hay un ahorro de tiempo y proceso porque no tendría que desarrollarse y mantenerse una función de unpivot.

**Comment by scornejob** [comment]
Si entiendo correctamente, quieren hacer un melt de los dataframes:

https://pandas.pydata.org/docs/reference/api/pandas.melt.html

Y resultaria algo asi:

https://github.com/MinCiencia/Datos-COVID19/blob/productosEstandar/output/producto1/Covid-19_std.csv

estoy en lo correcto?

**Comment by ivanMSC** [comment]
@scornejob Exactamente!
