### ISSUE TITLE
En el producto 15 no se actualizo el archivo de FechaInicioSintomasHistorico_std.csv 

### ISSUE THREAD

**Issue by felipeelorrieta** [MinCiencia/Datos-COVID19#880]
Hola.Se actualizaron todos los archivos del producto 15 menos el FechaInicioSintomasHistorico_std.csv. Hay alguna razón para esto.
Saludos,

**Comment by dna33** [comment]
Si, que supera el tamaño permitido de 100mb, vamos a crear una partición 2021.

**Comment by MinCiencia** [comment]
Problema resuelto en commit https://github.com/MinCiencia/Datos-COVID19/commit/c3960b886586cc754bb8fe948005a7c1ab5e9b79
