### ISSUE TITLE
Casos nuevos por edad por comuna

### ISSUE THREAD

**Issue by martinezpp** [MinCiencia/Datos-COVID19#881]
Es posible generar un nuevo producto que contenga los casos nuevos por edad por comuna? Similar al producto 15, pero que ademas tenga las edades. O a quién podría contactar para hacer el requerimiento? Gracias.

**Comment by dna33** [comment]
No existe ese desglose, tendrías que pedirlo a la Directora de la división de planificacion sanitaria: johanna.acevedo@minsal.cl
