### ISSUE TITLE
Columna vacía en el producto 58

### ISSUE THREAD

**Issue by juancri** [MinCiencia/Datos-COVID19#883]
El archivo [Camas_UCI_diarias.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto58/Camas_UCI_diarias.csv) del producto 58 tiene la última columna (2021-03-03) con datos vacíos.

**Comment by MinCiencia** [comment]
Corregido en el reporte diario de hoy, gracias por reportar.

**Comment by juancri** [comment]
Creo que el problema persiste aún

**Comment by dna33** [comment]
Ahora si, había una fecha que sobraba en el input.

**Comment by juancri** [comment]
Gracias!
