### ISSUE TITLE
¿Existe estadístuca de pacientes criticos y fallecidos que hayan sido vacunados (1a y/o 2a dosis)? 

### ISSUE THREAD

**Issue by syunusic** [MinCiencia/Datos-COVID19#884]
Existe estadístuca de pacientes criticos y fallecidos que hayan sido vacunados (1a y/o 2a dosis)? 
Sería muy útil tener ese dato.

**Comment by ctroncoso** [comment]
Aun de existir, es muy temprano en Chile. Aun que sería interesante tenerlo, serían muy pocos y no tendrían mucha significancia estadística. Tal vez sea mejor sea contar vacunados que tengan ingreso a hospitalización por covid.

**Comment by syunusic** [comment]
Creo que serviría mucho para demostrar con datos empíricos la eficacia de las vacunas.

**Comment by dna33** [comment]
No existe la información, voy a preguntar si está en los planes de MINSAL publicarlo.

**Comment by syunusic** [comment]
Hola. @dna33 Te dieron alguna respuesta? Está este dato en alguna parte? Creo que cada día es más importante contar con él. Gracias!

**Comment by houselizz** [comment]
Me interesan estos datos,atent.

**Comment by syunusic** [comment]
Hola. ¿Alguna novedad con este caso? Creo que ahora más que nunca es importante tener el dato del porcentaje de vacunados con dos dosis en las UCI. Es algo que se habla mucho en los reportes diarios en la TV, en las noticas, pero aun no logro ver esos datos reflejados en el repositorio, para mostrar datos empíricos.

**Comment by dna33** [comment]
Hola, al igual que los issues relacionados https://github.com/MinCiencia/Datos-COVID19/issues/1003, https://github.com/MinCiencia/Datos-COVID19/issues/985, el camino es hacer una solicitud de transparencia, solicitando se publiquen los datos en este repositorio.

**Comment by syunusic** [comment]
Listo. El código de seguimiento es el AO001T0014218. La solicitud fue hecha a la Subsecretaría de Salud Pública (MINSAL).
