### ISSUE TITLE
¿ Que es archivo terminado en STD ?

### ISSUE THREAD

**Issue by bwcastillo** [MinCiencia/Datos-COVID19#885]
Hola!

Tengo una pregunta simple, la busqué dentro del respositorio en algunas -muchos- carpetas de interés con los datos que estoy trabajando pero no la encontré.  Me gustaría saber a que se refieren los archivos terminados con _"_std"_.

De antemano muchas gracias por el increíble labor y también por responder.

Saludos!

**Comment by bwcastillo** [comment]
Me respondo solo: creo que simplemente es el formato donde las fechas están en una columna, disculpen por la poca intuición. Quedo atento si no es lo que creo.

Saludos!

**Comment by ctroncoso** [comment]
para referencia futura. 
El formato standard es el que solo tiene UN dato por fila, y le resto son dimensiones.
Acá tenemos 2 dimensiones... X e Y, y para cada par, un único dato, Valor.

X|Y|Valor
-|-|-
1|1|7
1|2|14
2|1|5
2|2|22
