### ISSUE TITLE
Estimación de actualización de producto 65?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#888]
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto65

Hoy (12 de Marzo) se tienen datos actualizados hace 9 días (informe TTA fue actualizado el 10 de Marzo)

Alguna estimación de cuando será actualizado nuevamente?

![image](https://user-images.githubusercontent.com/68602/110970653-b56a9380-8338-11eb-911b-f6f87b5a5d55.png)

Gracias

**Comment by fzmolina** [comment]
Hola,

Lo haré en breve.

Saludos

**Comment by dna33** [comment]
Gracias @fzmolina. Pull request merged.
