### ISSUE TITLE
Diferencia en casos nuevos diarios 13-03-2021

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#891]
En el último informe diario del 13 de marzo hay diferencia en la cantidad de casos nuevos confirmados. Lo anterior se fundamenta en lo siguiente:

1) Casos confirmados acumulado al 12-03-2021: 879.485

2) Casos confirmados acumulado al 13-03-2021: 885.379

3) Diferencia 1) y 2): 5.894

4) Casos nuevos confirmados 13-03-2021: 5.928  - valor distinto al calculado en 3)

Si hay una explicación a esta diferencia, favor me indican; en caso contrario, es posible que los datos oficiales tengan errores? A quién se debe reportar esto para que se hagan las correcciones?

**Comment by dna33** [comment]
Hola,

El 13-03-2021 los 'Casos totales acumulados' reportados fueron 885379 considerando un ajuste de 34 casos menos que los casos nuevos totales reportados ese día.

Más detalles del mecanismo y razón de los ajustes fueron anunciados por minsal hace algunos meses: https://github.com/MinCiencia/Datos-COVID19/issues/482

**Comment by ishmaster** [comment]
Muchas gracias por aclarar la duda!
