### ISSUE TITLE
Obsolescencia de información product74

### ISSUE THREAD

**Issue by valkot** [MinCiencia/Datos-COVID19#892]
Estimados, la información referente a los estados del plan paso a paso estas muy desactualizados, es mas llevan 7 días sin actualizarse, podrían ver si se actualizaran con la periodicidad con que los actualiza Minsal o los dejaran de lado.

Saludos y gracias por su importante aporte.

**Comment by dna33** [comment]
Hola, es una información histórica y se actualiza 1 vez a la semana.
