### ISSUE TITLE
Actualización de producto29

### ISSUE THREAD

**Issue by danieljay25** [MinCiencia/Datos-COVID19#895]
Estimados,

La información de cuarentenas se encuentra desactualizada desde enero, favor si pueden recuperar la frecuencia de actualización.

Saludos y gracias

**Comment by MinCiencia** [comment]
Hola, estas mirando el producto deprecado. Por favor usa el producto 74.

**Comment by danieljay25** [comment]
> Hola, estas mirando el producto deprecado. Por favor usa el producto 74.

Gracias, funcionando con el 74

Saludos
