### ISSUE TITLE
Frecuencia de actualización del producto 74

### ISSUE THREAD

**Issue by storresl** [MinCiencia/Datos-COVID19#899]
Hola,
La frecuencia de actualización del [producto 74](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto74/README.md#frecuencia-de-actualizaci%C3%B3n) no es buena. ¿Hay alguna fuente que se actualice el mismo día que los anuncios del gobierno? Si así fuera, me encantaría colaborar para mejorar la frecuencia.
Saludos.

**Comment by MinCiencia** [comment]
Hola, la única fuente que entendemos se actualiza al mismo tiempo que se anuncia es https://www.gob.cl/coronavirus/pasoapaso#situacioncomunal/

La diferencia con el producto 74, es que el 74 se actualiza cuando salen las resoluciones excentas en el diario oficial, que es cuando burocraticamente entran en vigencia.

Dicho eso, una contribución podría ser crear un nuevo producto que lea la información en el sitio gob.cl y actualice provisionalmente el producto 74, que pueda ser sobre-escrito una vez se publique en el diario oficial.

Gracias por la oferta, la tomamos.
