### ISSUE TITLE
Invitación a compartir analisis

### ISSUE THREAD

**Issue by MinCiencia** [MinCiencia/Datos-COVID19#902]
Hola! Con alegría vemos el articulo publicado en LUN hoy, no alcanzamos a revisar todo lo que se publica, pero si nos interesa motivar a que esta inteligencia colectiva se divulgue y profundice. En ese sentido, compartimos la nota en lun de hoy, y los invitamos a compartir tambien por acá lo que les parezca interesante, idealmente basado en la evidencia que se comparte a través de datos oficiales.

Con cariño,

Equipo Ministerio de Ciencia

Link: https://www.lun.com/Pages/NewsDetail.aspx?dt=2021-03-27&PaginaId=2&bodyid=0

**Comment by jsolinop** [comment]
Estimados. Me encantaría sumarme a la felicitación pero el análisis presentado en la noticia refleja el % de reparto, no el volumen de contagios. Por tanto, afirmar que la disminución de la participación de los contagios sobre 60 no implica una disminución de contagios necesariamente, sino el preocupante incremento de contagios hasta 59 años. 
De hecho, una vez que sabemos que hemos superado los 9000 en un día, necesariamente debemos concluir que no baja el contagio. Para que el análisis no deje ambigüedades debe acompañarse el % del número de contagios por día.
Espero que sea aporte. Saludos cordiales.

**Comment by MinCiencia** [comment]
@juancri Es el autor del análisis, basado en cifras oficiales publicadas por esta vía, Minsal y DEIS.

**Comment by jsolinop** [comment]
Estimados, no he dicho el el gráfico no corresponda a los datos reales u oficiales. Lo que indico es que la conclusión  o la afirmación de que bajan los contagios entre adultos mayores no puede surgir únicamente del % de participación. Hay un KPI fundamental que requiere ser considerado, y es el total de contagios confirmados.
Si no me equivoco, esto es un caso típico de "confounder" (factor de confusión).
Saludos cordiales.

**Comment by juancri** [comment]
Hola. Gracias por tus comentarios. Si lees la nota, verás que dije esto:

![screenshot8](https://user-images.githubusercontent.com/1131070/114317375-a48a7a80-9abc-11eb-87c4-9c8cefb928b8.png)

Hay otros expertos en cada una de sus áreas que luego hacen más comentarios.

Esto fue el 26 de marzo. Hoy ya podemos ver que la baja no es sólo en los porcentajes sino también que los adultos mayores de 60+ están estancados en números absolutos mientras otros grupos crecen:

![EyptKeBU8AE10_O](https://user-images.githubusercontent.com/1131070/114317411-d4d21900-9abc-11eb-8dd1-d39e5a4fede0.jpeg)

**Comment by jsolinop** [comment]
Hola @juancri ,

Quizás yo estoy analizando mal los datos. Yo estoy tomando el archivo que aparece en "input/CasosGeneroEtario.csv". Según ese archivo, lo que se observa es incremento en ambos casos. La pendiente es mucho mayor para los rangos de edades inferior a 60 años.

![image](https://user-images.githubusercontent.com/20975381/114325634-2ac7b080-9aff-11eb-9ee3-320b7805dd3f.png)

Lo que he hecho es agrupar los rangos de edades en 2: los menores de 60 (hasta 59) y los de 60 o más. En la gráfica yo no veo que haya una tendencia horizontal.

![image](https://user-images.githubusercontent.com/20975381/114326310-294bb780-9b02-11eb-875e-27cadabacc68.png)

Si estoy tomando alguna fuente errónea o estoy haciendo algo mal, te agradezco me ayudes a identificarlo. 

Gracias y un saludo. JSoliño

**Comment by juancri** [comment]
@jsolinop, ¿estás usando la pendiente de casos acumulados en vez de los casos por semana (o media móvil)? En ese caso, tu análisis debería mostrar una pendiente lineal y no necesariamente una curva horizontal (lo que en realidad significaría que no hay nuevos casos en ese rango de edad).

**Comment by jsolinop** [comment]
Muchas gracias @juancri.
Inicialmente, y con el objetivo de hacer las menores asunciones posibles,  tomé los datos del archivo  [CasosGeneroEtario.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/input/InformeEpidemiologico/CasosGeneroEtario.csv), tal cual vienen. 

- Ese archivo recoge los datos acumulados. 
- Adicionalmente, he confirmado que este archivo tiene datos de varios días acumulados (se reporta los lunes y los viernes).

Al ver tu gráfico, me quedé dando vueltas y antes de recibir este último mensaje, había re-hecho el análisis similar al que indicas (calculando las diferencias) y ahora sí identifico lo que indicas. Adjunto el archivo nuevo:

![image](https://user-images.githubusercontent.com/20975381/114331302-b77b6a00-9b11-11eb-9eb1-5ec7253eee3c.png)

Se evidencian las mismas conclusiones que tú indicas: el número de nuevos infectados sobre los 60 años lleva 3 semanas estancados (aunque todavía no baja), mientras que el de los menores de 60 sigue creciendo día a día.

Te agradezco mucho que te hayas dado el tiempo de explicarme la forma del análisis.
Si me permites el comentario, creo que el gráfico que has compartido en esta conversación es mucho más contundente que el que publicó LUN. 
Mil gracias y un saludo.. 
> Nota: revisaré el paso a paso que me indicas. Yo me manejo mejor en R que en Python, pero espero seguir profundizando en los datos y ojalá contribuir.

**Comment by juancri** [comment]
@jsolinop,

La verdad es que el trabajo con LUN generalmente es que yo envío varios gráficos y ellos eligen cuál publicar. Gracias.
