### ISSUE TITLE
Cifra de fallecidos no coincide (Producto 5) con lo informado en informe diario

### ISSUE THREAD

**Issue by dataCovid19CL** [MinCiencia/Datos-COVID19#903]
Producto 5 indica 22966 fallecidos totales e Informe Diario 22754

Producto 5
![image](https://user-images.githubusercontent.com/78309057/112756552-1ee6d500-8fbc-11eb-8520-0d43a407cb2d.png)

Informe diario
![image](https://user-images.githubusercontent.com/78309057/112756578-463da200-8fbc-11eb-9a98-b32a75253000.png)

**Comment by MinCiencia** [comment]
Gracias por reportar, corregido acorde a información recibida por MINSAL, domingo 28 de marzo, 2pm
