### ISSUE TITLE
Producto 37 (Fallecidos) |  28-03 indica 313 fallecidos. 

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#904]
Haciendo la diferencia entre informe del 28 y 27, solo casos confirmados, me da 313 fallecidos. 
![image](https://user-images.githubusercontent.com/121016/112756422-79336600-8fbb-11eb-8f35-8fe593490947.png)

Alguien puede confirmar si vemos lo mismo? Error de cálculo o hay error en el origen?

**Comment by dafernandez75** [comment]
Así es, vemos lo mismo en varios productos, más que preocupante, ya sea por omisión o por equivocación.

**Comment by ctroncoso** [comment]
> Así es, vemos lo mismo en varios productos, más que preocupante, ya sea por omisión o por equivocación.
Lo que me preocupa, es que se distribuye por fecha de deceso, no pareciera ser error. 

![image](https://user-images.githubusercontent.com/121016/112757715-56a44b80-8fc1-11eb-99c8-dc495c8493bf.png)

**Comment by dafernandez75** [comment]
lo mismo pienso.

**Comment by dna33** [comment]
Hola, nos enviaron una nueva fuente desde minsal. No especularía respecto del origen, sin embargo podría deberse a la suma de casos sospechosos junto con los confirmados.

**Comment by MinCiencia** [comment]
Corregido acorde a información recibida por MINSAL, Domingo 28 2 pm

**Comment by ctroncoso** [comment]
> Hola, nos enviaron una nueva fuente desde minsal. No especularía respecto del origen, sin embargo podría deberse a la suma de casos sospechosos junto con los confirmados.

Gracias.. intentaremos mantener bajo el nivel de paranoia... 😀
