### ISSUE TITLE
Cifras de fallecidos producto 3 no coinciden con reporte diario

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#905]
En el producto 3 se informan 22.966 fallecidos en total en Chile y en cada región más de lo que se da en reportes diarios. 313 nuevos fallecidos respecto ayer.

Por favor verificar.

**Comment by MinCiencia** [comment]
Corregido acorde a error reportado por el Ministerio de Salud, a las 2 PM.

Por favor considerar datos actuales.
