### ISSUE TITLE
Corregir Producto 37, totaliza 22.966 fallecidos (+313!!!!!!)

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#906]
Hola,
En producto 37 se totaliza 22.966 (+313!!!), debiendo ser 22.754. Esta correcto el de Uds o el Min.Salud omitió.???
Saludos.

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/904
