### ISSUE TITLE
Se busca: Informe epidemiológico 106 (27 de marzo) 

### ISSUE THREAD

**Issue by weichafan** [MinCiencia/Datos-COVID19#907]
Pasado el mediodía del domingo 28 de marzo no hay señales del reporte epidemiológico del día sábado 27 (con corte el viernes 26 a las 6 am ... probablemente) 

Tampoco el reporte de defunciones  ni el -probablemente cada 15 días- reporte de variantes.

En el Ministerio de Ciencia saben algo de estos reportes?? 

Alguna información se agradece

**Comment by dafernandez75** [comment]
![Captura de pantalla 2021-03-28 131947](https://user-images.githubusercontent.com/69001461/112759202-61161380-8fc8-11eb-81cb-c6b183fa8d27.jpg)
https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/

**Comment by MinCiencia** [comment]
El equipo de epidemiología subió el informe hace algunos minutos, hemos actualizado los datos en concordancia. Recomiendo seguir: https://twitter.com/min_ciencia_IA

Avisa cuando hace estas actualizaciones.
