### ISSUE TITLE
Problema de formato en output de producto05

### ISSUE THREAD

**Issue by syunusic** [MinCiencia/Datos-COVID19#909]
Todos los datos anterior al último día, aparecen con ".0", pero el día actual no.
¿Por qué es esto?
Ejemplo:
Fallecidos: Antes de ayer 82.0, ayer 74.0 y hoy, 66.
esto hace casi imposible automatizar el procesamiento de datos. 
¿Por qué es así? Hablo en particular del archivo TotalesNacionales_T.csv.

**Comment by MinCiencia** [comment]
Hola Sacha, todos los ideas es lo mismo. En qué lenguaje estas automatizando? Existen infinitas maneras de manejar el comportamiento del producto5, quizás podemos ayudarte.

**Comment by ctroncoso** [comment]
> Todos los datos anterior al último día, aparecen con ".0", pero el día actual no.
> ¿Por qué es esto?
> Ejemplo:
> Fallecidos: Antes de ayer 82.0, ayer 74.0 y hoy, 66.
> esto hace casi imposible automatizar el procesamiento de datos.
> ¿Por qué es así? Hablo en particular del archivo TotalesNacionales_T.csv.

Sucede en algunos datos, pero se puede manejar. 
Como dicen arriba, si tienes tu código en algún git, avisa y puede que podamos aportar. 
Una de las grandes tareas de data science, es poder manejar los datos aunque estén sucios... mas cuando vienen de diferentes fuentes.  Vamos que se puede!... ah no, eso es para el tenis.
