### ISSUE TITLE
Consulta actualización D19 - Casos activos por fecha de inicio de síntomas y comuna: Descripción

### ISSUE THREAD

**Issue by Orlando-GIS** [MinCiencia/Datos-COVID19#91]
Hola, quería comentar que la información en el formato que se dispuso el 24 de abril, la pude consumir bien y si es posible, saber ¿cuándo habrá una próxima actualización?
Saludos y gracias

**Comment by ivanMSC** [comment]
El MinSal actualiza esa información dos veces a la semana. Creo que lunes y viernes.
El del lunes deberian subirlo cuando terminen de transcribir los datos que anotan en sus servilletas.
