### ISSUE TITLE
Permisos de vacaciones

### ISSUE THREAD

**Issue by paarriagadap** [MinCiencia/Datos-COVID19#911]
Hola, no existe en ninguna parte la forma de extraer la información de los permisos de vacaciones? La prensa solía publicar cantidades totales y regionales (sobre todo entre Santiago y Valparaíso), pero sería realmente útil estudiar el detalle por fecha y comuna. Imagino que está difícil, pero pregunto igual...

Saludos.

**Comment by ctroncoso** [comment]
> Hola, no existe en ninguna parte la forma de extraer la información de los permisos de vacaciones? La prensa solía publicar cantidades totales y regionales (sobre todo entre Santiago y Valparaíso), pero sería realmente útil estudiar el detalle por fecha y comuna. Imagino que está difícil, pero pregunto igual...
> 
> Saludos.

Sería útil, sobre todo saber en forma anónima la fecha y ruta de origen y destino (movilidad), pero esa información la tiene  carabineros, no el minsal.

**Comment by paarriagadap** [comment]
Quizás es más difícil obtener directamente los permisos de vacaciones, pero veo que ISCI tiene un estudio de vacaciones [acá](https://covidanalytics.isci.cl/movilidad/visor-vacaciones/) que puede ser la mejor opción para estudiar esto. Se han publicado otros datos de movilidad de ISCI, salvo este, me parece.

**Comment by MinCiencia** [comment]
Muy buen producto ese, trabajaremos con el ISCI para subir un archivo en los formatos de este repo.

**Comment by paarriagadap** [comment]
Se ha podido hacer algo con esto?

**Comment by paarriagadap** [comment]
Sí, por eso mismo lo pongo. Igual están esos datos del ISCI, como hablamos antes.
