### ISSUE TITLE
Campo de Fecha sin valor en DP8 y DP20

### ISSUE THREAD

**Issue by jccarvajal** [MinCiencia/Datos-COVID19#912]
DP8 y DP20 presentan el campo vacío en donde debiese estar la fecha de hoy.
Saludos

**Comment by MinCiencia** [comment]
Cierto, debería estar corregido en el commit: https://github.com/MinCiencia/Datos-COVID19/commit/a104007c6903433492ece6f1bd91c016f8951ea1
