### ISSUE TITLE
Fallo en actualización P37 y P46

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#914]
![image](https://user-images.githubusercontent.com/121016/113316044-53240380-92e4-11eb-9b56-2a49690b5e65.png)

**Comment by ctroncoso** [comment]
![image](https://user-images.githubusercontent.com/121016/113316674-fecd5380-92e4-11eb-80a5-51fa8d1bc50b.png)
Error en fecha... envié un PR.

**Comment by MinCiencia** [comment]
Muchas gracias
