### ISSUE TITLE
Falla en actualización de P74

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#916]
Falta la hoja `CAMAS BASE' en el XLS
![image](https://user-images.githubusercontent.com/121016/113321255-cb40f800-92e9-11eb-8362-01cdbf04b9f2.png)

**Comment by MinCiencia** [comment]
Muchas gracias por los mensajes, fueron muy utiles en corregir los problemas de hoy. Creemos se encuentran resueltos.
