### ISSUE TITLE
Actualización de datos: Producto29 y Producto74.

### ISSUE THREAD

**Issue by CAGC2021** [MinCiencia/Datos-COVID19#919]
Estimados, primero que todo muchas gracias por compartir esta valiosa información.
¿Cuándo será la próxima actualización de estas bases?
Desde ya muchas gracias.

**Comment by dna33** [comment]
El producto 29 ya no se actualiza más, lo reemplazamos por el producto 74. Estos se actualizan cuando se publican las resoluciones exentas en el diario oficial.

Dicho lo anterior, fue actualizado con la información que entregó la autoridad sanitaria hoy, en este commit https://github.com/MinCiencia/Datos-COVID19/commit/e7450c2f4084c6e3374d8530898c4647e189783a

**Comment by CAGC2021** [comment]
Muchísimas gracias!!!

**Comment by samyalarcon** [comment]
Hola! Muchas gracias por este producto. ¿Existe alguna versión que contenga la información del producto 74 (paso a paso, con las etapas) entre marzo y julio de 2020? Porque el producto 29 no generaba la información en el mismo formato, según he visto. Gracias.
