### ISSUE TITLE
Api 

### ISSUE THREAD

**Issue by alvar0cks** [MinCiencia/Datos-COVID19#92]
Como ministerio mínimo deberían tener una api en vez de obtener data desde un Excel , por otro lado en sitios móviles se comporta mal el seleccionador y buscador de comunas...

**Comment by Leandermen** [comment]
@alvar0cks a que sitio te refieres con el seleccionador y buscador de comunas? es del visor territorial?

**Comment by sanguineti** [comment]
@alvar0cks https://github.com/sanguineti/chile-coronapi

**Comment by Leandermen** [comment]
nosotros tenemos una api en nuestro centro que está en crecimiento (https://covid19.soporta.cl)
En el podrás explorar y consumir nuestras fuentes de datos
https://covid19.soporta.cl/search?collection=Dataset

**Comment by scornejob** [comment]
Hace algunos dias liberamos una primera version de la API:
https://github.com/Data-Observatory/covid19-API
