### ISSUE TITLE
Edited: Pregunta respecto de los datos del producto 76

### ISSUE THREAD

**Issue by sabrown1016** [MinCiencia/Datos-COVID19#920]
Hola, el número total de dosis en los archivos vacunacion_t.csv y fabricante_t.csv no son consistentes con los del archivo rango_etario_t.csv. Por ejemplo, la primera fecha disponible en rango_etario_t.csv es Febrero 15 y el total de primeras dosis para esa fecha es 2,092,453. En el archivo vacunacion_t.csv el número de primeras dosis en esa fecha es 2,136,333 y en el archivo fabricante_t.csv el número de primeras dosis en la misma fecha es 2,136,344. Sería súper útil si pudieran rectificar y completar las fechas del archivo rango_etario_t.csv. Gracias.

**Comment by MinCiencia** [comment]
Hola, ocupa por favor este producto: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78

Tiene lo que necesitas y se va actualizando completo, diaramente, 2 veces por día con información del DEIS (a veces actualiza retroactivamente).

En el producto 76 solo el de vacunacion (en sus 3 formatos) se va actualindo de esta manera. Los otros son fotos de lo que tenía el DEIS a un dia dado, sirven para auditar, pero no son los más precisos con lo que realmente pasaba ese día.

Espero me explique y si no, pregunta no más.

Por ejemplo para fabricante te sugiero utilizar: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto83

Si quieres una serie de tiempo de los achivos que son totales, lo que se me ocurre puedes hacer es ver la historia de cada archivo.

**Comment by sabrown1016** [comment]
Gracias por la respuesta. Creo que los datos de la vacuna por fabricante en el producto 76 está más o menos alineado con el de vacunación total.

Pero por lo que me contestas, entiendo que la mejor manera de armar una serie de tiempo de la vacunación por grupo de edad es usando el producto 78 y utilizando el historial de cada archivo.

Si te malentendí, porfa avísame. Gracias de nuevo por la disposición a ayudar.

**Comment by sabrown1016** [comment]
Última pregunta, ¿hay alguna otra forma de armar una base de datos de vacunación por edad? Te pregunto porque las revisiones del producto 78 sólo empiezan a eso del 20 de Enero cuando ya se habían administrado algo así como 2.8 millones de vacunas. Gracias de nuevo.

**Comment by MinCiencia** [comment]
Esa es la fecha en que integramos esa fuente con el DEIS, la manera de complementarlo es con la información el producto 76.  Pero ojo el 20 de enero iban como 20,000 vacunas no más.

**Comment by sabrown1016** [comment]
Toda la razón. La fecha a la que me refería era el 20 de **Febrero** Sólo a partir de esa fecha veo actualizaciones del archivo. Gracias.

**Comment by SebaSilvaS** [comment]
Hola! Respecto a esta respuesta:

> Hola, ocupa por favor este producto: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78
> 
> Tiene lo que necesitas y se va actualizando completo, diaramente, 2 veces por día con información del DEIS (a veces actualiza retroactivamente).
> 
> En el producto 76 solo el de vacunacion (en sus 3 formatos) se va actualindo de esta manera. Los otros son fotos de lo que tenía el DEIS a un dia dado, sirven para auditar, pero no son los más precisos con lo que realmente pasaba ese día.
> 
> Espero me explique y si no, pregunta no más.
> 
> Por ejemplo para fabricante te sugiero utilizar: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto83
> 
> Si quieres una serie de tiempo de los achivos que son totales, lo que se me ocurre puedes hacer es ver la historia de cada archivo.

Existe alguna forma de descargar rápidamente el historial del archivo? O tener acceso directamente a la base de datos de DEIS?

Quedo atento, saludos!
