### ISSUE TITLE
Error en datos de positividad comunal en Informe de Indicadores TTS (reflejado en producto 65)

### ISSUE THREAD

**Issue by dataCovid19CL** [MinCiencia/Datos-COVID19#923]
El informe de Indicadores TTA del 31 de Agosto de 2020 tiene un error en a tabla con datos para las comunas de la Región de Los Ríos.  Al parecer incluyeron datos que no correspondían en la primera columna (% Búsqueda Activa) y el resto de las columnas quedaron con información incorrecta (ej 38,9% de positividad cuando debió ser 2,4%)

Esto se refleja en las tablas del producto 65 https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto65

![image](https://user-images.githubusercontent.com/78309057/114175972-98f65280-9908-11eb-8e90-fd560e5ee2a9.png)

**Comment by MinCiencia** [comment]
Hola, muchas gracias por reportar. Entregamos el caso al departamento de epidemiología del Minsal, en el intertanto, puedes elaborar para nuestro equipo minciencia como descubriste este error?
