### ISSUE TITLE
Producto 20 - Error dato faltante  30-09-2020

### ISSUE THREAD

**Issue by luispsa** [MinCiencia/Datos-COVID19#924]
Hola,

En el producto 20, se encuentra faltante la cantidad de camas criticas disponibles del 30-09-2020, además que la columna totales de ese día también sale mal

![image](https://user-images.githubusercontent.com/70834945/114339211-a7b85180-9b22-11eb-853c-a985b40d9b3d.png)

![image](https://user-images.githubusercontent.com/70834945/114339374-04b40780-9b23-11eb-9d55-5c1010bb191e.png)

saludos

**Comment by MinCiencia** [comment]
Corregido
