### ISSUE TITLE
Edited: Cómo descargar los datos del Github, a través de la web 

### ISSUE THREAD

**Issue by frojaso** [MinCiencia/Datos-COVID19#927]
Hola, soy nuevo en Github por lo que no sé si puedo descargar los csv de los datos para analizarlos o bien sólo pueden ser visualizados en la plataforma(dado que no he encontrado la forma de descargarlos)

**Comment by dna33** [comment]
Hola, dentro de cada data product puedes usar el botón "raw" para desplegar el contenido y luego guardas lo que tu navegador despliega en la carpeta que te parezca. 

Lo interesante es que ese link al que te lleva el botón "raw" es permanente, es decir que siempre accederás a la última versión del producto cada vez que descargues su contenido. Esto te sirve como interface útil para tus planillas locales, también como para visualizaciones que tengas en línea, si fuera el caso. Muchas de las aplicaciones que se crean a partir de este github utilizan este mecanismo (ver https://www.minciencia.gob.cl/comunidad_covid19)

![raw](https://user-images.githubusercontent.com/12438811/114564543-e03c5600-9c1c-11eb-826e-526d8bc71673.png)

**Comment by frojaso** [comment]
Muchas gracias Demián! Funcionó perfecto! 
Muy buen trabajo el que hacen aquí por cierto.
