### ISSUE TITLE
Producto 69 diferente a datos en sitio ICOVID

### ISSUE THREAD

**Issue by sabrown1016** [MinCiencia/Datos-COVID19#929]
Hola,

Por lo que entiendo, el producto 69 lo provée ICOVID Chile y corresponde a la carga de infectados (incidencia diaria de casos por cada 100 mil habitantes).

En el último informe de iCovid (https://uploads.strikinglycdn.com/files/46e490f7-552a-49ce-a1f1-86cbf74fea5a/Informe%2035_ICOVID%20Chile.pdf) los autores notan que en la semana del 28 de Marzo la carga de enfermedad pasó "de 35 a 31.6 casos por 100,000 habitantes".

Si obtengo los datos el gráfico del sitio de Covid (https://public.tableau.com/views/COVID_v2_15952814711910/Dim1-Carganacional?:language=es&:increment_view_count=no&:embed=y&:embed_code_version=3&:loadOrderID=0&:display_count=y&:origin=viz_share_link) y luego calculo el promedio del indicador de carga para la semana epidemiológica que va desde el 28 de Marzo al 4 de Abril obtengo 31.6. Si repito el cálculo usando los datos del 21 de Marzo al 27 de Marzo obtengo 35. Esas cifras son consistentes con el informe.

Sin embargo, en el repositorio de github los números son distintos. Por ejemplo, el promedio para la semana del 21 al 27 de Marzo es 35.4 y el promedio y para la de Marzo 28 a Abril 3 el promedio es 34.4.

Acá dejo otros dos ejemplos de datos asociados a los gráficos del sitio Icovid y los del repositorio de Github que no son consistentes:

**Icovid**
Fecha                      | Lim Inf               | Carga estimada | Lim sup
Abril 3 2021            | 24.0715920340 | 27.7186713540  | 31.6118152090
Diciembre 31 2020 | 13.2372749740 | 13.9244107020  | 14.6162487900
    
**Github**
Fecha                      | Lim Inf               | Carga estimada | Lim sup
Abril 3 2021            | 29.6160098179 | 30.7234030088  | 31.9065478965
Diciembre 31 2020 | 13.2278959478 | 13.9032629247  | 14.6585186483

Sería súper útil si pudieran ya sea corregir los datos en el repositorio o alguien me pudiese explicar la diferencia entre ambas series de tiempo. Gracias.

**Comment by MinCiencia** [comment]
Hola, nos informan desde ICOVID que no corresponde a un error, sino que a medida que avanza la investigación epidemiológica los datos van cambiando (situación que ha sido explicada en este repositorio en múltiples issues). A raíz de lo anterior, se corrigen hacia atrás las series completas, pero en el repositorio queda la foto que se entregó en el pasado, por razones de trazabilidad de datos.

**Comment by sabrown1016** [comment]
Perfecto. Muchas gracias.  Y por si acaso busqué el issue dentro de los que ya estaban cerrados antes de preguntar pero no encontré anda. Gracias de nuevo.
