### ISSUE TITLE
Actualización DP22 y DP44

### ISSUE THREAD

**Issue by sabrown1016** [MinCiencia/Datos-COVID19#930]
Hola,

¿Tienen planes de actualizar los datos de estos productos? De no tener planes, ¿saben dónde estarán disponibles esos datos o datos similares? Gracias

**Comment by MinCiencia** [comment]
El 22 se reporta diariamente y incluye en el DP09, el DP44 lo actualizaremos junto con el reporte diario en los próximos días.
