### ISSUE TITLE
Actualización de DP 22 

### ISSUE THREAD

**Issue by sabrown1016** [MinCiencia/Datos-COVID19#931]
Me cerraron el issue anterior que abrí así que tengo que abrir uno nuevo.

El DP22 no se ha actualizado en por lo menos 2 meses. Y los datos del DP9 son distintos a los del DP22 en dos dimensiones relevantes:
1) El DP22 incluye datos tanto de hospitalizaciones como de hospitalizaciones en la UCI (el DP9 sólo incluye UCI)
2) El el DP22 incluye el total acumulado de pacientes que ha pasado por la UCI o hospitalizados. El DP9 y el DP24 (que incluye hospitalizaciones en general) sólo incluyen el número diario de hospitalizados mientras.

Usando sólo los datos diarios de DP9 y DP24 no puedo saber si los (por ejemplo) los 1898 pacientes en camas básicas el 14 de abril son los mismos 1898 pacientes del día anterior o si los dieron a todos de alta y se internó una cantidad igual de nuevos pacientes. El no poder saber cuántos pacientes con covid-19 han sido hospitalizados o han pasado por la UCI significa que no es posible estimar la probabilidad de ser hospitalizado condicional en haber contraído la enfermedad.

Si es posible, por favor vuelvan a actualizar el DP22 o señálame dónde están los datos porque por lo menos los del DP9 son distintos y no son suficientes para derivar la información que contenía el DP22.

Gracias

**Comment by dna33** [comment]
Hola, el equipo actualizó el producto 22 acorde a la última información publicada. Cerramos por error el issue anterior, pero me parece siempre los puedes reabrir. Avísame si tienes más preguntas, por favor.

**Comment by sabrown1016** [comment]
Gracias Demián. Creo que  sólo ustedes pueden reabrir issues. 

Igual, la segunda mitad de mi pregunta sigue abierta: **¿Planean actualizar el DP 22?** 

La última actualizaión del archivo "HostpitalizadosEtario_Acumulado" fue hace 2 meses y por o menos hasta el informe epidemiológico diario #100 de ayer los datos necesarios para completar esa tabla seguían siendo publicados (Tabla 3 en la pagina 24). El archivo "HospitalizadosUCI_Acumulados" dejó de actualizarse en Mayo del año pasado pero no estoy seguro si el informe epidemiológico diario sigue publicando la información necesaria para actualizar el productio.

Gracias

**Comment by MinCiencia** [comment]
Ahi actualizamos el DP22

**Comment by sabrown1016** [comment]
Muchas gracias.
