### ISSUE TITLE
Edited: ¿por qué cambian los valores para semanas anteriores?

### ISSUE THREAD

**Issue by roroba** [MinCiencia/Datos-COVID19#938]
Cuando publican un nuevo reporte del producto 15, los valores de casos nuevos cambian en las semanas epidemiologicas anteriores?
Es decir: Puente alto en el reporte del producto 15 de la semana 202114 tenia 1027 casos nuevos confirmados, el reporte nuevo de hoy (17 abril 2021) la semana 202114 tiene 2032 casos nuevos confirmados Para puente alto. Por que pasa esto?

**Comment by MinCiencia** [comment]
Hola, porque son curvas completas, a medida que avanza la investigación epidemiológica se agregan más casos, a veces se verifican los domicilios también (por lo que en algunos casos a veces hasta disminuye)
