### ISSUE TITLE
Posible error en Producto 22

### ISSUE THREAD

**Issue by jathibaut** [MinCiencia/Datos-COVID19#940]
Estimados. Sugiero revisar el cambio de pacientes hospitalizados entre el 05.04.2021 y el 09.04.2021. Indica un salto de más de 13.000 hospitalizados en 4 días. Saludos.

![image](https://user-images.githubusercontent.com/81814292/115316353-317da580-a147-11eb-9320-07b834ab88f8.png)

**Comment by MinCiencia** [comment]
El departamento de epidemiología está investigando, porque verificamos que lo publicado en el producto 22 corresponde a los informes epidemiológicos asociados.

**Comment by jathibaut** [comment]
Muchas gracias.
Efectivamente. Creo incluso que Uds han corregido errores de los informes
epidemiológicos.
Pero luego del enorme desfase, las cifras siguieron igual.
Saludos cordiales!
JT
