### ISSUE TITLE
Problema con datos de vacunación - Producto 76 rango_etario.csv

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#943]
A partie del 2022-04-21 se agregaron registros en grupos etarios distintos a lo que se venía haciendo (ej 60 a 69 en vez de 61 a 70) además de los grupos que se usaban hasta el 21 de Abril.

El 22 de abril aparecen los datos duplicados c/r al 21 de Abril para los nuevos grupos (y no hay datos para los grupos que se venían publicando desde el 21 de Febrero (se pierde la evolución de la serie)

No hay datos para el 23 de Abril

Entiendo que hay un nuevo producto en prueba con datos por edad individual, pero este producto se utilizaba en reportes automáticos.  Sugiero no descontinuar  y mantener consistencia con los grupos usados en los últimos meses.

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/rango_etario.csv

![image](https://user-images.githubusercontent.com/68602/115959464-52911e00-a4da-11eb-983d-0ca07ba5b1f8.png)

**Comment by MinCiencia** [comment]
Hola @elaval, la creación del nuevo producto no tiene que ver con los cambios en este. Son dos hechos independientes. Los cambios acá vienen desde el origen, @juancri contribuyó con este código quizás puede dar más luces al respecto.

**Comment by juancri** [comment]
Debido a que el sitio del DEIS no incluye el historial, lo que [hace el script es obtener la situación actual y juntarla con el histórico](https://github.com/juancri/covid19-vaccination/blob/5d939ac35c0c136961951aed3d9944a347692475/process/src/writers/ChileVaccinationsAges.ts#L34-L39).

Ha ocurrido ya un par de veces que el DEIS cambia los grupos reportados y, en esos casos, el script agrega los grupos nuevos y actualiza los anteriores (si es que el nombre es el mismo). Hay más información aquí: https://github.com/juancri/covid19-vaccination/issues/20

**Comment by MinCiencia** [comment]
A todo esto, nos parece que el producto que contribuye @juancri es muy útil para controlar las publicaciones (qué se dijo cada día, similar a los balances diarios de las autoridades), sin embargo es mejor para conocer el avance de la campaña consultar estos https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78. Pues son "curvas completas", que se actualizan una vez al día con la información más ajustada a lo que ocurrió en realidad en una jornada determinada.

Saludos.
