### ISSUE TITLE
Producto 78 -Mayor vacunación que población

### ISSUE THREAD

**Issue by JuliusOdian** [MinCiencia/Datos-COVID19#944]
Los datos de vacunación de personas entre 80-89 suman mucho más que la población de Chilenos en ese rango etario. Estimo que hay aprox 450.000 mil Chilenos en ese rango etario y hay más de hay más de 1,1 millones de segundas vacunas realizadas en ese grupo de edades.

**Comment by MinCiencia** [comment]
Si estas mirando el producto78, aun esta en periodo de prueba, ver https://github.com/MinCiencia/Datos-COVID19/issues/925

**Comment by MinCiencia** [comment]
Arreglamos los archivos, ojo que el que se llama "total", suma ambas dosis, por lo que debiese andar cerca del doble de la población total en ese rango etario, si es que se ha vacunado cerca del 100%.

De cualquier manera, corregimos algunos problemas que teía y el total no supera los 937000
