### ISSUE TITLE
Diferencias U071 & U072 con DatosAbiertos(DEIS).

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#945]
Hola,
OJO: Según fuente: Datos Abiertos DEIS, son 26.134 U071 y 7.239 U072 (actualizados), total 33.373 al 21-abril-2021.
Según reporte y acá son 25.742 U071.

De los casos U071: 26.134-25.742 = 392 (pendientes del reporte y del repositorio de agregar), estos pendientes de agregar están entre 10-abril-201 al 14-abril-2021.

**Comment by dna33** [comment]
Hola, no hemos agregado aún la última actualización del DEIS, el equipo trabaja en eso ahora. Puedes revisar en cuanto lo hagamos la consistencia. Se hacen actualizaciones retroactivas en cada entrega del deis, pues su investigación en causas de muerte va evolucionando con el tiempo.

**Comment by dafernandez75** [comment]
Es curioso, que el actualizado del sábado anterior fue: 25.055 U071 + 8.318 U072 = total 33.373, el mismo actualizado de hoy del Deis al 21-abril-2021. Quedaremos atento, saludos

**Comment by MinCiencia** [comment]
Actualizamos la información desde DEIS hace algunas horas, puedes probar ahora?

**Comment by dafernandez75** [comment]
Casos Sospechosos U072: Deis / Repositorio / Diferencia faltante
10-abril-2021: 41 / 20 / 21
11-abril-2021: 60 / 25 / 35
12-abril-2021: 79 / 39 / 40
13-abril-2021: 72 / 35 / 37
14-abril-2021: 47 / 37 / 10

Casos Confirmados U071: Deis / Repositorio / Diferencia faltante
10-abril-2021: 178 / 107 / 71 
11-abril-2021: 199 / 105 / 94 
12-abril-2021: 241 / 126 / 115 
13-abril-2021: 228 / 132 / 96  
14-abril-2021: 110  / 94 / 16  

Total Deis                          : 26.134 U071 + 7.239 U072 = 33.373
Total Repositorio Prod.37 : 25.742 U071 + 7.096 U072 = 32.838
Dif.Total                            :      392 U071 +    143 U072 = 535

**Comment by dafernandez75** [comment]
Cabe mencionar, revise lo que tiene arriba el Deis ahora, y los registros que tienen ahora están alineados con lo del Producto37.
Desconozco la hora que actualizaron nuevamente DatosAbiertos. 
Es decir, con la nueva actualización del Deis (2da versión) estaría correcto el Producto 37 (también en su 2da versión), pero de tener otros registros al medio día los tenían, mantengo el histórico. Saludos
