### ISSUE TITLE
Problema con el producto 76

### ISSUE THREAD

**Issue by datagovuc** [MinCiencia/Datos-COVID19#946]
Estimad-s,

En el archivo `rango_etario_std.csv` hay un error en la suma de las vacunas para la fecha `2021-04-21`. El total para la primera dosis en dicha fecha es de **15932698**, pero al sumar las cantidades para la primera dosis en esa fecha obtengo **23710617**, lo que no es consitente con el total reportado. 

Me parece que desde esa fecha en adelante hay problemas de este tipo, pues hice el check en la fecha inmediatamente anterior, y el total para el `2021-04-20` es de **7777919** para la primera dosis ---lo cual ya indica que hay algo extraño--- y al sumar todas las primeras dosis para esa fecha el número coincide.

**Comment by juancri** [comment]
El 21 de abril hubo una [actualización en el sitio del DEIS](https://github.com/juancri/covid19-vaccination/commit/3922c81e458feb53752faa61b696ed3c3e45dca9) y probablemente este error está relacionado. Voy a revisarlo.

**Comment by MinCiencia** [comment]
Hola, en el intertanto sugerimos usar este producto, que reune los totales por dosis y edad, y tambien el avance por edad y fecha a lo largo de la campaña.

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78

**Comment by psotou** [comment]
Hola @juancri. Finalmente pudieron ver si era un problema con la base DEIS?

Saludos,

**Comment by juancri** [comment]
He decidido suspender por ahora la actualización de estos archivos en el [repo de vacunaciones]():

- [chile-vaccination-ages-comunas.csv](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-ages-comunas.csv)
- [chile-vaccination-ages.csv](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-ages.csv)
- [chile-vaccination-groups.csv](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-groups.csv)

Es posible que tenga tiempo de revisarlo en la semana, pero por ahora, prefiero asumir que no están correctos.

Si alguien quiere aportar un fix, me puede enviar un PR. Gracias.

**Comment by dna33** [comment]
Hola @psotou, pudiste revisar si este producto cumple con tus requisitos? https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto78 si no es así, cuéntanos por qué, por favor.

**Comment by psotou** [comment]
Hola @dna33, sí. Estoy usando los datos del producto 78 ahora y no he visto nada extraño. Así que voy a cerrar el issue. Gracias por las respuestas!
