### ISSUE TITLE
¿Actualización de informe epidemiológico Nº 115?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#947]
Hace algunas horas está disponible el informe epidemiológico Nº115 en sitio web de Minsal

¿Cuál es la hora estimada de actualización de los productos asociados en el repositorio?

Gracias

![image](https://user-images.githubusercontent.com/68602/116480667-bfe0de00-a84f-11eb-96f7-c0f337c4c5ff.png)

**Comment by MinCiencia** [comment]
https://twitter.com/min_ciencia_IA/status/1387583146095489025?s=20

**Comment by elaval** [comment]
Gracias
