### ISSUE TITLE
Actualización de producto 65 (Positividad Test PCR por comunas)

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#949]
Entiendo que el "Preprocesamiento y manejo de datos" es realizado por Fundación Ciencia y Vida

Agradecería si pueden compartir información sobre fecha/hora estimada de la actualización (y/o saber si hay una estimación - en general - de cuanto tiempo después de publicado el informe epidemiológico se realiza esta actualización.

Estos datos son muy relevantes, especialmente en la situación actual.

![image](https://user-images.githubusercontent.com/68602/116540684-7ed0e400-a8b8-11eb-9787-83a0bbd3fe37.png)

**Comment by fzmolina** [comment]
Hola @elaval ,

Los productos relacionados al informe de testeo y trazabilidad del departamento de epidemiología del Ministerio de Salud fue iniciado desde la Fundación Ciencia y Vida. Sin embargo, la actualización desde el 1 de abril es hecha como contribución personal, por mí.

Estoy iniciando la actualización.

Saludos,
Faviola

**Comment by MinCiencia** [comment]
Muchas gracias, @fzmolina. @elaval, al igual que el informe epidemiológico, el robot avisa cuando este producto ha sido actualizado: https://twitter.com/min_ciencia_IA/status/1387736796620939270?s=20

**Comment by ivanMSC** [comment]
@minsal El robot avisa cuándo algo ha sido publicado, pero no **cuándo se publicará**, que es lo que @elaval insiste en saber.

**Comment by dna33** [comment]
claro, pero quizás podrían armar un modelo estadístico para predecirlo? Lo mejor que podemos ofrecer, para que no tengan que preguntar, es este robot que avisa. ;)

**Comment by elaval** [comment]
Gracias Faviola, Ivan y Demián,

No necesito un modelo predictivo ;-). Me basta con saber que se espera que los datos se actualicen dentro de 2 horas (o 24 o 48 ... ) desde que se publica el informe de indicadores, o bien que hay un sistema automático que se gatilla ante X evento ... 

No estaba exigiendo un SLA ... solo saber como era el proceso

Saludos y gracias por su pega

Ernesto

**Comment by dna33** [comment]
creo que podemos sostener que siempre (99% de los casos), se actualizan habitualmente dentro de las 12 horas posteriores a la
publicación por parte de minsal.

**Comment by elaval** [comment]
Gracias a @fzmolina y @juancri 

Y también gracias @dna33 (y equipo) por el trabajo que hacen ustedes manteniendo este repositorio (más allá de un servicio del estado hay dedicación personal en mantenerlo funcionando y responder consultas y solicitudes de muchos que somos usuarios de estos datos)

Lo útil e importante de esta información hace que muchos la usemos y estemos pendientes de las actualizaciones (y eventuales problemas que puedan ocurrir).  No hay una crítica personal cuando levantamos issues ... sólo tratamos de aportar (y también calmar nuestra propia ansiedad por tratar de informar a otros en forma oportuna).

Saludos

**Comment by MinCiencia** [comment]
Gracias @elaval. Nosotros trabajamos en el gabinete de un ministro de estado, consideramos en el ministerio que hacer lo que tu nos agradeces es nuestro deber.

Estamos totalmente de acuerdo en la utilidad e importancia de estos datos, por eso nos hemos coordinado con el Ministerio de Salud para lograr que estén disponibles, sin embargo no podemos y ese es el punto que Demián que dirije este equipo intenta hacer, no podemos garantizar a priori una hora de actualización, no está en nuestro poder. Lo mejor que podemos ofrecer es avisar mediante el robot cuando aquello ocurre para así evitar que tu y otros tengan que preguntar por acá cuando estará.

Como has visto, las 2 o 3 veces que hemos tenido problemas, también lo anunciamos por esta vía.
