### ISSUE TITLE
Producto 37. 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#951]
Hola,
Nuevamente no cuadran valores del Deis con reporte Minsal de hoy 01-05-2021, que bajaron la información en estos momentos, manteniendo ahora lo del 30-04-2021, ojala rectifiquen con respecto al Deis.
Ref. Datos Abierto Deis: 
U071 = 26.457   
U072 = 7.302
Total = 33.759

Sería factible que cuando actualicen el Producto 37, se haga alineado con respecto al DEIS (U071 y U072), la información ya está.
Saludos

**Comment by MinCiencia** [comment]
Hola, lo que dices es que no calza lo que publica deis.minsal.cl con lo que está en www.gob.cl ?

**Comment by dafernandez75** [comment]
Principalmente me refiero a que hace más de 4 horas se conocen los U071 y U072 y solo actualizan los U071, teniendo los datos desde Datos abiertos Deis.

Con respecto al reporte Minsal, en relación a los registros U071 no siempre se cuadra con respecto al U071 que publica el Deis (DatosAbierto), debido la mayoría de las veces a los ajustes por sospechosos que pasan a confirmados o se descartan finalmente.  Hoy paso de que el total reportado por Minsal fue otro, que luego bajaron, y en la nueva publicación se cuadra con el total Deis U071. 
Saludos

**Comment by ctroncoso** [comment]
Disculpen que meta la cuchara... tampoco me calzó el pr37, pero incluso solo en los U07.1. Salieron 210 fallecidos. 
Quería revisar con ustedes si estamos con los mismos valores.
![image](https://user-images.githubusercontent.com/121016/116796000-12680780-aaa7-11eb-90e0-452f5437cd92.png)

**Comment by dafernandez75** [comment]
Así es, +210 con respecto ayer. Desde el 07 junio 2020.

**Comment by ctroncoso** [comment]
error por hora de corte?.. es como mucho pasar de 104 (informe diario) a 210.

**Comment by dafernandez75** [comment]
sabes los +210, veo que es la diferencia entre hoy 01-05-2021 y el 29-04-2021, lo de ayer 30-04-2021 no está en el producto 37.

**Comment by ctroncoso** [comment]
@dafernandez75 : freak... y si.. tienes razón, falta el 30. Error en carga. 
@MinCiencia parece que habrá que revisar el input. Falta la carga de ayer. No nos asusten! :stuck_out_tongue: 
![image](https://user-images.githubusercontent.com/121016/116796289-5b20c000-aaa9-11eb-9196-9555519e5f56.png)

**Comment by ctroncoso** [comment]
https://github.com/MinCiencia/Datos-COVID19/commit/fec84a88165dab2db4b887cc91d06ae4ffbec0dc Excelente! gracias!

**Comment by MinCiencia** [comment]
Corregido, muchas gracias @ctroncoso y @dafernandez75 por reportar.
