### ISSUE TITLE
Actualización de datos de informe diario 1 Mayo 2021?

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#952]
Hola

Lo he preguntado antes en relación a otros informes y entiendo que el robot IA avisará cuando de actualizarán los datos en los repositorios

Sin embargo quisiera consultar en esta oportunidad por el informe diario del día 1 de Mayo de 2021

Este es un informe crítico que generalmente se actualiza pocos minutos después de ser publicado el PDF en la página de gobierno, sin embrago hoy no no ha sido actualizado (luego de algunas horas)

¿Existe algún contratiempo con la actualización de los repositorios asociados a este informe?

Lo consulto porque muchos reportes externos se alimentan de estos datos y hay personas que nos consultan por dicha actualización

Saludos,

Ernesto

**Comment by fzmolina** [comment]
Hola @elaval ,

Dónde está publicado el informe que mencionas? revisé la página del departamento de epidemiología y no veo la publicación (16:27): https://www.minsal.cl/nuevo-coronavirus-2019-ncov/informe-epidemiologico-covid-19/

Podrías por favor compartir dónde se están publicando ahora?

Saludos,
Faviola

**Comment by MinCiencia** [comment]
Hola, https://twitter.com/min_ciencia_IA/status/1388602909303078912?s=20

**Comment by elaval** [comment]
Gracias

**Comment by MinCiencia** [comment]
Anytime, @elaval

**Comment by elaval** [comment]
Hola Faviola,

Vi muy tarde tu mensaje...

Estaba publicado en 

https://www.gob.cl/coronavirus/cifrasoficiales/#datos

**Comment by fzmolina** [comment]
Hola Ernesto,

Perdona, interpreté mal el mensaje. Confundí tu mensaje del reporte diario
con el informe epidemiológico.

Gracias por tu respuesta.

Saludos,
Faviola
