### ISSUE TITLE
Actualización de productos diarios 05/05/2021

### ISSUE THREAD

**Issue by adinamarca** [MinCiencia/Datos-COVID19#954]
Hola, muy buenas.

¿Sucedió algo con la actualización de los productos diarios?

¡Saludos!

**Comment by dna33** [comment]
Hola @adinamarca, acabo de aprobar la actualización.

https://twitter.com/min_ciencia_IA/status/1390008871704428547?s=20

**Comment by adinamarca** [comment]
> Hola @adinamarca, acabo de aprobar la actualización.
> 
> https://twitter.com/min_ciencia_IA/status/1390008871704428547?s=20

@dna33 
¡Muchas gracias por el enorme trabajo!
Saludos
