### ISSUE TITLE
Población que ha estado en UCI

### ISSUE THREAD

**Issue by vnavia** [MinCiencia/Datos-COVID19#956]
Buenas tardes necesito información de numero total de pacientes COVID 19 que han requerido hospitalizaciòn en UCI, idealmente cruce con sobrevivientes (excluyendo los que hayan fallecido) lo anterior ya que se habla de cifra de recuperados de covid 19 pero aquellos pacientes que pasaron por UCI en un porcentaje que se estima hasta un 50% quedan con secuelas funcionales y/o cognitivas al menos a 6 meses. Agradezco la informaciòn

**Comment by MinCiencia** [comment]
Hola, 

La información disponible en este repositorio se publica acorde con la disposición del Ministerio de Salud de Chile, en regla con las leyes 19628, y 20584, de datos personales y de derechos y deberes de los pacientes respectivamente.

Esto, en el marco actual, ha permitido avanzar hasta el momento en la publicación de datos eventualmente asociables a personas, de manera que estén agrupados o agregados, ya sea por unidad temporal (siendo el "día" la unidad con mayor resolución) o territorial (siendo la "comuna", o  "servicio de salud" la unidad con mayor resolución).

Los datos que dan cuenta de los fenómenos que parecen ser de tu interés son los siguientes (hay más productos que pueden serte útiles, este es una propuesta inicial):
- Egresos hospitalarios (agrupados por semana) https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto44
- Pacientes hospitalizados con covid 19 (agrupados por dia y edad) https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto22 
- Pacientes fallecidos y estado de hospitalziación (agrupados por día y por region) https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto57 
- Pacientes en uci con covid 19 (agrupados por dia) https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto24
- Pacientes vacunados, agrupados por  comuna y dia (hay mas agrupaciones que pueden serte útiles) https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion.csv
- Casos confirmados positivos por laboratorio, por fecha y comuna: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto63
- Pacientes fallecidos por comuna, dia y edad: https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto84
