### ISSUE TITLE
Consulta U072 del Producto 37, factibilidad de subreporte u072. 

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#957]
Hola,
junto con agradecer el trabajo que están realizando y las constantes mejoras que han estado realizando a los productos de este repositorio,  como en el día de hoy que junto con U071 están publicados los U072, excelente mejora. 
Les consulto lo siguiente:

En relación a los U072 como bien saben, se desconoce temporalmente qué pasa con ellos temporalmente,  los que pasan a U071 o los que se eliminan del registro. 
Por ejemplo, hoy se eliminaron 25 y se agregaron 205, siendo +180 la diferencia con respecto al registro anterior de U072. En semanas anteriores han existido casos de muchos más los eliminados que no pasan a U071.

Considerando lo anteriormente expuesto, existe la posibilidad de que puedan consultar en el Minsal reportabilidad sobre los movimientos semanales de los U072, lo anterior para transparencia de los datos con la modificación en los registros correspondientes sin fundamento, creando para ello el producto correspondiente en este repositorio para conocer el destino final de aquellos que originalmente fueron U072, si pasan a U071 u otra causa de fallecimiento.

Saludos.

**Comment by MinCiencia** [comment]
Hola, este producto da cuenta de lo que tu observas, no respecto de fallecidos, si no de todos los casos:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto59

Con respecto a los fallecidos, no entiendo la pregunta, pero el nivel de detalle entregado por deis.minsal.cl es 1 fila, 1 caso.

**Comment by dafernandez75** [comment]
Por ejemplo, si revisan las series correspondientes:
U072 (2020-04-10):  son 4 (registros sospechosos 30-04-2020) ;  son 3 (registros sospechosos 08-05-2021).
Por ende 1 caso menos , pero este caso no se agregó a Confirmados, ya que se mantienen en 7 los ult 2 reportes. Es decir, esa persona cuál fue su causa de fallecimiento real.

**Comment by dna33** [comment]
El flujo esta explicado en el informe de defunciones del deis, lo has visto? 

Las causas pueden terminar siendo otras no-covid. 

En el deis.minsal.cl puedes ver las causas de muerte de todas las defunciones, no solo las covid sospechoso/confirmado

**Comment by dafernandez75** [comment]
No existe producto ni información derivado de una trazabilidad de seguimiento de los casos U072. Solo totales finales.

**Comment by ctroncoso** [comment]
> El flujo esta explicado en el[ informe de defunciones del deis](https://www.minsal.cl/wp-content/uploads/2021/04/Informe-Semanal-Defunciones-DEIS-22-04-21.pdf), lo has visto? En las páginas 2 a 6 se hace un esfuerzo de explicar bien detalladamente, pero también con simpleza cómo es que ocurre el análisis que va determinando las causas de muerte.
> 
> Las causas pueden terminar siendo otras no-covid, principalmente otras enfermedades respiratorias y cardiovasculares, como se indica en el informe que cito.
> 
> En el deis.minsal.cl puedes ver las causas de muerte de todas las defunciones, no solo las covid sospechoso/confirmado

Exacto. Digamos que hay un caso sospechoso, que ya está de alta y con PCR pendiente. Temporalmente es U07.2 por diag clínico.  Diagnostico principal de neumonía, y secundario, por covid (sospecha). 

Si llega el PCR y dá negativo, se recodifica y queda como un caso de neumonía normal. Sin clasificació U07X y sale de la estadistica covid.
