### ISSUE TITLE
Error en varios product

### ISSUE THREAD

**Issue by valkot** [MinCiencia/Datos-COVID19#962]
Estimados, se han hecho cambios en las columnas que reportan los casos del sitio del minsal, por ende ha generado errores en la extracción de información

**Comment by dna33** [comment]
Hola, en qué productos hay errores?

**Comment by valkot** [comment]
En los casos diarios, PCR, Fallecidos pero ya se soluciono, quizás actualizaron a la nueva disposición que genero el misal, ahora separo los totales de los diarios en tablas separadas.

Saludos.

**Comment by MinCiencia** [comment]
Hola, no encontramos los errores que mencionas, ¿puedes ayudarnos a identificar con mayor precisión?

**Comment by valkot** [comment]
Bueno te comento, en la mañana los productos:
5, 7, 8, 14, 17, 19, 20, 36, 76 presentaban problemas cuando intentaba acceder al ultimo registro, después revise la web del MINSAL y me percate que ellos habían separado en dos tablas los registros diarios, tal vez modificaron las tablas de los reportes igual, por eso no registraba dato la ultima columna de estos productos, pasado las 10 AM revise y ya estaba corregido. Te menciono esto porque tengo una App que esta constantemente consumiendo lo que ustedes publican parte de obtener por mi cuenta otros datos, por eso me di cuenta del evento.

Saludos.

**Comment by dna33** [comment]
Ok, entonces solo para cerrar el primer tema, el equipo lo considerará resuelto.

Con respecto a lo segundo, de todas maneras. El equipo piensa que es muy importante para trazabilidad citar la fuente de los datos, y ha hecho un esfuerzo de escribir documentación que se mantiene al día respecto de cada producto. En lo posible, citar incluso nombrando el data product que utilizas es ideal. 

Además, si quieres aparecer en el listado que el equipo compila, avísanos para agregarte: https://minciencia.gob.cl/comunidad-covid19/

**Comment by valkot** [comment]
Ok la App tiene mas de 1 año ya publicada y tiene sumando ambas tiendas sobre 7.000 descargas, trabajo en Salud por eso nace esto y ustedes son un gran aporte.

La App es **cov_cl** de hecho ustedes(ministerio) han llamado para preguntar sobre esta App.

Saludos.

**Comment by dna33** [comment]
Super, la bajó el equipo. Por favor inclúyenos como fuente. Buen trabajo!

**Comment by valkot** [comment]
Sip, ya los incluí, hice unas modificaciones a la app a nivel comunal y los agregue en el "acerca de", estoy a la espera que la App Store la revise y la publique, posterior a eso la subo a la Google Play, es mas fiable la revisión de la App Store.


Saludos.
