### ISSUE TITLE
Data Product 82 - Movilidad por comuna - ISCI Producto movilidad por comunas -  ERROR

### ISSUE THREAD

**Issue by ricardopavez** [MinCiencia/Datos-COVID19#964]
Data Product 82 - Movilidad por comuna - ISCI Producto movilidad por comunas presenta los siguientes errores:

- Cuando se considera el archivo con días de semana (lunes-viernes) excluyendo festivos falta información de la semana 7/09/2020 al 10/09/2020.

- Información de la comuna 5801 está repetida dos veces, con diferencias en la etapa del plan paso a paso.

**Comment by scespinoza** [comment]
Hola,

Las semanas faltantes en ambos archivos corresponden a caídas de sistema por parte de Entel, por lo tanto no tenemos datos para esas semanas. Agregamos esto al readme para evitar confusiones  (#965). Con respecto al segundo punto, efectivamente había un error en los datos que corregimos. Esta corrección se verá reflejada en el repositorio el día lunes, que es cuando se actualiza el producto. Por ahora, puedes acceder a los datos directamente desde los servidores del ISCI (https://nodejs.isci.cl/api/visor-movilidad/week).

**Comment by ricardopavez** [comment]
Muchas gracias!!

Saludos,

Ricardo Pavez Sura
Alumno Magíster en Ciencia Económicas
Ingeniero Comercial en Economía
Universidad de Santiago de Chile

**Comment by MinCiencia** [comment]
Actualizado también en este repo: https://github.com/MinCiencia/Datos-COVID19/commit/4b59e897ba9423e0f474cfad919a537c4328b891 

Todo bien ahora?
