### ISSUE TITLE
Posible error en fecha de último informe Epidemiológico dice 2020-05-13 y esperábamos 2020-05-14

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#966]
Los informes Epidemiológicos publicados los días sábado generalmente reportan datos asociados a un día viernes

La publicación del  sábado 15 de Mayo de 2021 reporta datos asociados al JUEVES 13 de Mayo de 2021

Esto tiene importantes implicancias en la interpretación de los datos (ej el aumento de casos no habría sido en 7 días sino en 6 días lo cual afecta fuertemente la incidencia de casos diarios).  Agradecería chequear si efectivamente hubo un cambio en la fecha esperada o si es un error en la convención utilizada para nombrar el informe (que acarreó un error en la generación de los datos del producto)

Esto es importante para evitar reportar un fuerte aumento de los casos diarios en muchas comunas que puede no ser correcto

Saludos

![image](https://user-images.githubusercontent.com/68602/118396017-8237cf80-b61b-11eb-8989-233c15a702f0.png)

**Comment by MinCiencia** [comment]
Esto es correcto, corregiremos en breve.

**Comment by MinCiencia** [comment]
Corregido: https://github.com/MinCiencia/Datos-COVID19/commit/9eaceff2be400c7abba05fb08577ba3f10a38c44
