### ISSUE TITLE
Actualización Producto 37?

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#967]
Hola, 
![Captura de pantalla 2021-05-16 135118](https://user-images.githubusercontent.com/69001461/118407392-8df0b980-b64e-11eb-84e6-e533dfb98969.png)
![Captura de pantalla 2021-05-16 135752](https://user-images.githubusercontent.com/69001461/118407447-c2fd0c00-b64e-11eb-8c2c-2e9c9813fe6a.png)
según lo publicado en Twitter ya estaría actualizado el Producto 37, y al revisar este no lo está.

Saludos

**Comment by dna33** [comment]
Cierto, el equipo corregirá durante la tarde. De todas maneras antes de las 22 horas.
