### ISSUE TITLE
Demora en reporte diario - 21 de mayo de 2021

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#970]
Estimados:
Por qué aún no está disponible la información correspondiente al reporte diario del 21 de mayo, siendo que el reporte está informado hace más de 2 horas?

**Comment by MinCiencia** [comment]
Hola, una actualización programada de los sistemas considerando el feriado ha tomado más de la cuenta. El equipo subirá el reporte de vacunación y el balance diario en los próximos minutos.

**Comment by ishmaster** [comment]
Ok! gracias por la respuesta.
