### ISSUE TITLE
Casos genero etario por comuna en sexta region

### ISSUE THREAD

**Issue by sandragaete** [MinCiencia/Datos-COVID19#975]
es posible compartir los datos de casos confirmados según fecha, rango etario y sexo** como están en "PRODUCTO 16" pero sólo de la sexta región y no a nivel nacional, y ojalá además por comunas? o a quien debo escribir para solicitar la información? De antemano muchas gracias

**Comment by dna33** [comment]
Este producto es el que se acerca más a lo que usted describe:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto73

Si es que nnecesitaras un mayor desglose de la información, puede hacerse vía solicitud de transparencia al Ministerio de Salud, Departamento de Epidemiología. En tal caso sugiero solicitar que se dispongan los datos periodicamente a través del github del ministerio de ciencia, en lo posible... esto para que no solo entreguen la foto al día, si no algo que se mantenga actualizado.

**Comment by sandragaete** [comment]
muchas gracias por su respuesta
