### ISSUE TITLE
DP74 - Etapas del plan paso a paso 

### ISSUE THREAD

**Issue by jccarvajal** [MinCiencia/Datos-COVID19#976]
Buenas,
El producto 74 no ha sido actualizado desde el 20/05/2021.
Gracias.

**Comment by dna33** [comment]
https://github.com/MinCiencia/Datos-COVID19/commit/261b6e7c98902744e1e5eb5e91edf662ee70fa72

Se había quedado en el tintero, gracias por el recordatorio.
