### ISSUE TITLE
No están disponibles actualizaciones de datos de Vacunas, Reporte diario ni Reporte Epidemiológico del 29 Mayo 2021

### ISSUE THREAD

**Issue by elaval** [MinCiencia/Datos-COVID19#977]
Mensaje original del 29 de Mayo (≈4pm)

El input de vacunas al 29 de Mayo 2021 se actualizó hace 5 horas (pero no se ha actualizado el output)
Tampoco se observa actualización del input de informe diario ni los respectivos outputs (al menos hasta las 15:40 del 29 de mayo)

Se espera una actualización pronto? (si hay algún inconveniente se agradecería avisar para informarle a nuestros clientes de reportes que esteran dicha actualización)

Gracias

![image](https://user-images.githubusercontent.com/68602/120082949-c0a9a180-c093-11eb-892b-78e97c5bc1eb.png)

**Comment by ishmaster** [comment]
Siendo las 21:25 del sábado 29 de mayo, aún los datos del informe diario, vacunación e informe epidemiológico no están actualizados. Hubo algún problema en particular? Porque no es primera vez que hay retraso en la publicación.

**Comment by elaval** [comment]
9:30am de Domingo 30 de Mayo
Aún no está disponible la actualización de datos diarios del Sábado 29 de Mayo

Agradecería si los administradores del proceso pueden comunicar si este es un issue conocido y si se está trabajando en él
(Hay muchos procesos externos que dependen de la actualización de estos datos y ayuda mucho tener reportes de progreso ante eventos)

**Comment by MinCiencia** [comment]
Hola, fue actualizado el fin de semana, con la información del sábado y el domingo. Luego ha continuado su actualización diaria sin contratiempos.

Ver issue relacionado: https://github.com/MinCiencia/Datos-COVID19/issues/980

En el futuro, es bueno revisar si otros usuarios han presentado la misma duda, o si se ha informado respecto de la actualización con algún contratiempo, cuestión nos parece ha sido conversada con algunos de ustedes en este issue en otras oportunidades. Todo esto en virtud de hacer más efectiva nuestro diálogo sobre los datos. Saludos.
