### ISSUE TITLE
Producto 3: Casos nuevos de antígeno por región

### ISSUE THREAD

**Issue by ehcoshinoo** [MinCiencia/Datos-COVID19#979]
¿Existe algún apartado en dónde se refleje por fecha los casos nuevos confirmados por antígeno por región? Se que el dato se menciona en todos los reportes diarios, pero no pude encontrarlo en ninguna parte. Muchas gracias

**Comment by MinCiencia** [comment]
Hola, acá puedes encontrarlo:

https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/TotalesPorRegion.csv

**Comment by ehcoshinoo** [comment]
Gracias!
