### ISSUE TITLE
Reducción en casos acumulados de la comuna de Hualpén

### ISSUE THREAD

**Issue by rodrigo19822** [MinCiencia/Datos-COVID19#98]
Hola, no soy experto, pero entiendo que el producto 1 muestra los casos acumulados a nivel comunal. De ser así, a que se debe la reducción de 30 casos entre el 13 y 14 de abr 2020?

![imagen](https://user-images.githubusercontent.com/63676994/80629089-ba786a00-8a28-11ea-8ffc-6af6ef2c6c3a.png)

**Comment by ivanMSC** [comment]
Si solo te interesa el número de casos confirmados, te recomiendo seguir los casos de tu comuna a través de los reportes oficiales del gobierno de tu region. En mi repo está el seguimiento hecho. No es perfecto, pero sí es más granular que el informe epidemiológico y tiene menos inconsistencias, o al menos están mejor justificadas..

Según el gobierno de Biobio, el gráfico de Hualpén es el siguiente:
![image](https://user-images.githubusercontent.com/35350256/80632635-894a6a80-8a25-11ea-8d8b-efb9b083b34c.png)

Puedes ver el gráfico interactivo en https://datastudio.google.com/u/2/reporting/b1689869-0c59-442c-951d-2991c0fc611d/page/g9aMB

**Comment by rodrigo19822** [comment]
Prefiero tratar de entender la causa de las discrepancias entre los datos, dado que ahora me causa desconfianza tanto los del min de la ciencia, como los del gob regional. Sin considerar que la ausencia de 30 casos podría modificar la situación sanitaria de la comuna (actualmente con cordón sanitario, no con cuarentena). Lo anterior, sin mencionar que hay al menos otras 2 comunas donde la situación se repite.

**Comment by ivanMSC** [comment]
Los datos son del MinSal, no del MinCiencia.

**Comment by patricionicolas** [comment]
Estoy tomando estos mismos datos para crear gráficas por comuna. He encontrado en mas de una comuna que los datos incrementales disminuyen.

![imagen](https://user-images.githubusercontent.com/17221394/80650354-d9cfc100-8a41-11ea-893e-a4bf36fb529a.png)

Hace un tiempo, cuando veía los reportes entregados para mi región la Araucania, leí que algunos casos eran "reubicados" debido a que eran algunas personas pertenecían a otras comunas/regiones. Entiendo que eso pudiese ser una posible respuesta a desprender a la espera de una oficial.

**Comment by MinCiencia** [comment]
Así es, el domicilio de las personas es un dato provisorio que se actualiza a medida que evoluciona la investigación epidemiológica, el departamento de epidemiología del ministerio de salud de chile reporta el estado de su investigación en los informes epidemiológicos, los mejores números son los últimos que publican.
