### ISSUE TITLE
Actualización sábado 29 y domingo 30

### ISSUE THREAD

**Issue by dna33** [MinCiencia/Datos-COVID19#980]
Se realizarán hoy
domingo al final del día.

**Comment by elaval** [comment]
Gracias por la información

(apreciamos info sobre el estado de avance ante eventos, ya que muchos procesos y sitios dependen de esta actualización)

**Comment by ishmaster** [comment]
Gracias por la información.
De todas formas, sería muy util que se informe en caso de haber retraso en la actualización de datos.

**Comment by lcvidelam** [comment]
Muchas gracias por la información, concuerdo con los otros dos comentarlos.

**Comment by weichafan** [comment]
Me dio sueño, Domingo 22.23 llegué al final de mi día esperando los datos. Ojalá mañana al comienzo del día ya estén los datos. Gracias

**Comment by felipeelorrieta** [comment]
Aqui seguimos atento a la actualización

**Comment by MinCiencia** [comment]
Hola, se encuentran actualizados al 30 de mayo los productos del balance diario y el informe epidemiológico, además de aquellos que se actualizan en base a información publicada por el DEIS.

**Comment by weichafan** [comment]
Hola me parece que no fueron todos, falta el producto 37 que entendería es en base a información DEIS. Gracias

**Comment by MinCiencia** [comment]
Hola, @weichafan, si bien -no entendemos por qué- aparece como actualizado 3 días atrás, se encuentra actualizado. Revisaste los datos? Incluyen la última información disponible hasta dónde podemos revisar (p37, p50 y p84 que se actualizan con info del DEIS los 3).

**Comment by weichafan** [comment]
Gracias. No había visto los datos solo la fecha de actualización y decía hace 2 días. Pero los datos están hasta ayer. Gracias y saludos
