### ISSUE TITLE
Solicitud datos por Cuadrante

### ISSUE THREAD

**Issue by smunozv** [MinCiencia/Datos-COVID19#981]
Estimados, quisiera solicitar la información publicada sobre casos totales, por genero y edad, mortalidad, morbilidad para los cuadrantes COVID, como podría generar esa información.

En caso de considera que se vulnera el secreto estadístico o medico, que al parecer no es el caso, el dato mas interesante seria la cantidad de casos por fecha para cada cuadrante de epivigila , cualquier antecedente se agradece enormemente.

Muchas gracias por la informacion.

**Comment by MinCiencia** [comment]
Hola, la información existe a un nivel de agregación territorial de menor desglose, que es el comunal.

Acorde a lo conversado con el departamento de Epidemiología, el conducto regular para solicitar desagregación mayor es a través de una solicitud por transparencia al Departamento de Epidemiología del MINSAL, en la que sugerimos incluir que se compartan los datos a través de esta plataforma, así se satisface no solo para ti si no para toda la comunidad.

Gracias a ud. por la inquietud.

**Comment by CGMGEMA1** [comment]
Estimados nosotros hemos solicitado eso por transparencia y no se encuentran disponibles y no han contestado en los plazos indicados.

**Comment by MinCiencia** [comment]
Para entregar una retroalientación coherente al Ministerio de Salud tendría ud. @CGMGEMA1  que compartirnos qué es específicamente lo que solicitó, como lo solicitó y luego la respuesta que recibió.

**Comment by smunozv** [comment]
@MinCiencia , Algo asi estará bien como solicitud?

Estimados, 
Quisiera solicitar la desagregación de la información ya publicada sobre COVID19, en el portalhttps://github.com/MinCiencia/Datos-COVID19, desde el inicio de la pandemia hasta la fecha, en formato de cuadrantes epidemiológicos, del total de información publicada se solicita específicamente lo siguiente:  casos totales, por género y grupos de edad, mortalidad, morbilidad a nivel de cuadrante COVID. Entendiendo que de ser posible enriquecer esta solicitud con el total de datos publicados a nivel comuna seria bastante mas provechoso.

Dicha información se encuentra publicada a nivel de comuna y sería necesario simplemente descender al nivel espacial de cuadrante epidemiológico, el cual asegura la anonimización de datos, en base a lo entendido por parte del equipo de github MINCIENCIA en sus respuestas, esta solicitud de desagregación de datos no irrumpe el secreto estadístico ni tampoco el secreto médico.
La solicitud contempla también la petición de incluir estos datos para compartir a través de la plataforma https://github.com/MinCiencia/Datos-COVID19, de este modo se podría satisfacer la necesidad de la gran cantidad de investigadores interesados.

Con esto se busca dar mayor utilidad al formato de cuadrante epidemiológico, el cual solo entrega los casos totales con limite de 15 días. Al mismo tiempo permitiría realizar estudios espacio temporales en función de distintas zonas de las comunas.
