### ISSUE TITLE
Falló carga de producto diario

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#983]

**Comment by dna33** [comment]
¿qué productos no están actualizados?

**Comment by ctroncoso** [comment]
raro.. estaba aun escribiendo el issue... Voy a cerrar esta.. la descripción y propuesta está en la #984

**Comment by ctroncoso** [comment]
> ¿qué productos no están actualizados?

FYI, falló el action de actualización de producto diario, en el P37 y P46
Supongo que todo proceso posterior tampoco se ejecutó.
en el #984 dejé una propuesta de modificación del código para que el proceso no dependa de la fecha de ejecución. 

![image](https://user-images.githubusercontent.com/121016/120193108-01b3ca00-c1ea-11eb-8748-9314ce634e48.png)
