### ISSUE TITLE
Falló carga de producto diario

### ISSUE THREAD

**Issue by ctroncoso** [MinCiencia/Datos-COVID19#984]
El código en línea 118 es susceptible a fallas ya que intenta calzar con la fecha de hoy en vez de la fecha máxima.
`last_row = df_input_file[df_input_file['Fecha'] == timestamp]`

Al correr hoy 31 y no haber carga para el día 31, last_row queda vacío y falla en la línea 131

https://github.com/MinCiencia/Datos-COVID19/blob/19159f7ed1d733c0c0bedbaa6d6cacd4ac0c2552/src/reporteDiario.py#L131

sugiero cambiar por fecha máxima contenida en el dataframe.
`last_row = df_input_file[df_input_file['Fecha'] == df_input_file['Fecha'].max()]`

https://github.com/MinCiencia/Datos-COVID19/blob/19159f7ed1d733c0c0bedbaa6d6cacd4ac0c2552/src/reporteDiario.py#L118

![image](https://user-images.githubusercontent.com/121016/120191722-4b031a00-c1e8-11eb-879f-409cf98c2937.png)

**Comment by MinCiencia** [comment]
Hola @ctroncoso: qué producto no se encuentra actualizado, @ctroncoso, porque sabemos como funciona el código y lo que hicimos ayer, a raíz de actualizar varios días retroactivamente es subir el output directamente, además del input (que efectivamente gatilló procesos que fallaron, pero lo anterior es irrelevante porque esos procesos los corrimos de todas maneras y comiteamos los cambios).

Dicho todo esto, nos preguntamos qué productos te parece no están actualizados.

Gracias

**Comment by ctroncoso** [comment]
El P37 no se vé actualizado. Defunciones. 



> Hola @ctroncoso: ¿qué producto no se encuentra actualizado? Porque sabemos como funciona el código y lo que recomendamos hacer ayer a la persona que actualizó, a raíz de actualizar varios días retroactivamente, es subir el output directamente habiéndo corrido el código localmente con las fechas que correspondía -muy en línea con tu sugerencia-, además del input (que efectivamente gatilló procesos que fallaron, pero es irrelevante porque esos procesos los corrimos de todas maneras, y comiteamos los cambios).
> 
> Dicho todo esto, nos preguntamos qué productos te parece no están actualizados. Porque quizás hicimos algo mal, pero hasta el momento no vemos problemas con los datos en "output".
> 
> Gracias

**Comment by MinCiencia** [comment]
https://github.com/MinCiencia/Datos-COVID19/issues/980#issuecomment-851470779

**Comment by MinCiencia** [comment]
Hola @ctroncoso, cerramos este? Muchas gracias por reportar de todas maneras.
