### ISSUE TITLE
Datos anonimizados georeferenciados de mortalidad por COVID

### ISSUE THREAD

**Issue by CGMGEMA1** [MinCiencia/Datos-COVID19#985]
En ninguno de los archivos disponible podemos encontrar los datos anonimizados y georreferencidos por cuadrantes de la mortalidad por COVID y los casos positivos. En el caso de los casos positivos estos se muestran en el visor territorial de datos COVID gestionado por el Ministerio de Bienes nacionales sin embargo, no tenemos acceso a estos datos ya que se cambian semana a semana a nivel urbano pero no se alojan luego en ningún servidor de acceso público, además en estos no encontramos mortalidad, en este sentido nos gustaría ver la posibilidad de que se facilitaran esos datos para poder trabajar con ellos en el marco del Proyecto COVID0184

**Comment by MinCiencia** [comment]
Buen punto, la respuesta que hemos recibido es el camino de solicitud de transparencia, quizá podría agregar más detalles sobre el proyecto que menciona, cuál es su objetivo, quienes son los responsables. Por otra parte, nosotros podríamos administrar disposición de esos datos, pero efectivamente hoy no contamos con ellos como Ministerio.

**Comment by CGMGEMA1** [comment]
Se le indicó los datos necesarios y los objetivos del mismo en la solicitud realizada por transparencia la cual no ha sido contestada a la fecha.

Adjunto acá los objetivos del mismo.

Objetivo general: Dilucidar las relaciones entre los niveles de SARS-CoV-2 en aire, la calidad del aire y los indicadores epidemiológicos mediante la evaluación del riesgo ambiental. Objetivos específicos:
1. Determinar la abundancia de SARS-CoV-2 en el aire de las ciudades de Antofagasta, Santiago y Concepción, de julio a octubre, y comparar la evolución genómica local en Chile con la de otros países.
2. Determinar la especiación química como carbono orgánico (OC), carbono elemental (EC) metales, compuestos orgánicos solubles en agua (WSOCs), del material particulado fino (MP2.5) en Antofagasta, Santiago y Concepción, de julio a octubre.
3. Relacionar las condiciones atmosféricas (MP2.5 y sus especies químicas, contaminantes asociados, radiación UV, y abundancia de SARS-CoV-2 en muestras de aire) con la incidencia, mortalidad y letalidad por COVID-19 en las tres ciudades de Chile estudiadas.

**Comment by MinCiencia** [comment]
A qué ministerio se le hizo la solicitud? Y cuál fue la respuesta específicamente?

**Comment by CGMGEMA1** [comment]
Se le hizo al MINSAL directamente y no hemos recibido respuesta todavía, mañana se acaba el plazo de la misma. El código de la solicitud  AO001T0013857

**Comment by MinCiencia** [comment]
Comparta cuando ocurra la respuesta, para ver como ayudar. Gracias.

**Comment by CGMGEMA1** [comment]
Eso haré por que el no acceso a los datos no permite cumplir con los objetivos de la propuesta financiada

**Comment by MinCiencia** [comment]
Hola, el Consejo para la Transparencia publicó esto hoy, nuestro equipo esta revisandolo, pero nos ayudaría tener vuestra opinión respecto de cómo esta recomendación afecta o insuma la solicitud que han hecho acá:

[N°000157 Según Distribución.PDF](https://github.com/MinCiencia/Datos-COVID19/files/6617242/N.000157.Segun.Distribucion.PDF)

**Comment by smunozv** [comment]
> Eso haré por que el no acceso a los datos no permite cumplir con los objetivos de la propuesta financiada
Consulta, alguna respuesta o novedad de transparencia?

**Comment by smunozv** [comment]
> Hola, el Consejo para la Transparencia publicó esto hoy, nuestro equipo esta revisandolo, pero nos ayudaría tener vuestra opinión respecto de cómo esta recomendación afecta o insuma la solicitud que han hecho acá:
> 
> [N°000157 Según Distribución.PDF](https://github.com/MinCiencia/Datos-COVID19/files/6617242/N.000157.Segun.Distribucion.PDF)

Que debo hacer si ya paso el tiempo de transparencia para responder y no hay novedad?

**Comment by ctroncoso** [comment]
> > Hola, el Consejo para la Transparencia publicó esto hoy, nuestro equipo esta revisandolo, pero nos ayudaría tener vuestra opinión respecto de cómo esta recomendación afecta o insuma la solicitud que han hecho acá:
> > [N°000157 Según Distribución.PDF](https://github.com/MinCiencia/Datos-COVID19/files/6617242/N.000157.Segun.Distribucion.PDF)
> 
> Que debo hacer si ya paso el tiempo de transparencia para responder y no hay novedad?

Si tu hiciste el requerimiento, tienes 15 días para realizar el reclamo. 
En el mismo portal donde está tu solicitud hay instrucciones de cómo realizarlo. 
![image](https://user-images.githubusercontent.com/121016/127709477-828847ba-c768-4822-a79e-432c62439d3b.png)

Ingresa con tu código de solicitud y luego anda al link destacado.

**Comment by smunozv** [comment]
> e está tu solicitud hay instrucciones de cómo realizarlo.

Gracias, la verdad creo que ya termino el plazo formal, pero luego llego un documento donde comprometen la fecha de entrega al 15-07-2021, con 10 días hábiles de prorroga, es decir 29-07-2021, sin embargo el transparencia desconoce el plazo y dice que ya pasaron los 15 días de reclamos. :/

**Comment by CGMGEMA1** [comment]
Lo volveremos a solicitar es una vergüenza

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: SMUNOZV ***@***.***>
Enviado: Friday, July 30, 2021 5:20:58 PM
Para: MinCiencia/Datos-COVID19 ***@***.***>
Cc: Cristobal Galbán Malagón | U.Mayor ***@***.***>; Author ***@***.***>
Asunto: Re: [MinCiencia/Datos-COVID19] Datos anonimizados georeferenciados de mortalidad por COVID (#985)


e está tu solicitud hay instrucciones de cómo realizarlo.

Gracias, la verdad creo que ya termino el plazo formal, pero luego llego un documento donde comprometen la fecha de entrega al 15-07-2021, con 10 días hábiles de prorroga, es decir 29-07-2021, sin embargo el transparencia desconoce el plazo y dice que ya pasaron los 15 días de reclamos. :/
