### ISSUE TITLE
Vacunación - diferencias entre producto 80 y 81

### ISSUE THREAD

**Issue by ishmaster** [MinCiencia/Datos-COVID19#986]
Estimados:

Revisando los productos 80 y 81 encontré diferencias en los vacunados con 1º y 2º dosis. A modo de ejemplo, les presento el caso de la comuna de Providencia.

1) Producto 81 (imagen visor: https://informesdeis.minsal.cl/SASVisualAnalytics):

![image](https://user-images.githubusercontent.com/62425955/120400876-c5c55580-c30c-11eb-822e-5ab76dc8645a.png)

2) Producto 80 (imagen visor: https://yomevacuno.visorterritorial.cl/)

![image](https://user-images.githubusercontent.com/62425955/120401093-39676280-c30d-11eb-9365-1dbe9a3a98e6.png)

Entonces, qué explicación hay para esta diferencia?

**Comment by MinCiencia** [comment]
Persisten las diferencias luego de la actualización?

**Comment by ishmaster** [comment]
Sí, persiste la diferencia. Además, ahora se presentó otra diferencia entre los productos 80-81 y lo mostrado en el visor territorial ([link](https://yomevacuno.visorterritorial.cl/))  y las cifras oficiales del DEIS/MINSAL ([link](https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F9037e283-1278-422c-84c4-16e42a7026c8&sectionIndex=1&sso_guest=true&sas-welcome=false)) las que proceso a señalar a continuación con el ejemplo de la región metropolitana.

1) Producto 81
- 1º dosis: 4.424.658
- 2º dosis: 3.220.627
- Reporte DEIS/MINSAL

![image](https://user-images.githubusercontent.com/62425955/120685803-45b70100-c46e-11eb-8a32-91128be43b8e.png)

2) Producto 80
- 1º dosis: 4.351.249
-  2º dosis: 3.163.938
- Reporte DEIS/MINSAL

![image](https://user-images.githubusercontent.com/62425955/120686218-c1b14900-c46e-11eb-8599-8cb387dd7b65.png)

- Visor territorial

![image](https://user-images.githubusercontent.com/62425955/120686471-fd4c1300-c46e-11eb-80d3-c044f6d3223c.png)

Adicional a lo anterior, se está contemplando una mejora a los productos relacionados a la vacunación para incorporar las vacunas con dosis única?

**Comment by ishmaster** [comment]
Hay novedades sobre este tema?
Cuál es la explicación para esta diferencia?
Cuándo se va a regularizar la actualización de datos en los productos de vacunación para que vuelva a cuadrar con lo mostrado en los visores?

**Comment by MinCiencia** [comment]
No aún, lo estamos revisando entre otras tareas. Cuando exista una novedad, le escribiremos por acá y le llegará una notificación.

**Comment by MinCiencia** [comment]
Acabamos de incluir en los productos la vacunación mono-dosis. Puedes por favor verificar si continúa ocurriendo el problema? Entendemos sería afortunado si esto lo solucionase, porque en principio no pareciera estar relacionado. Quedamos atentos a tu revisión, @ishmaster.

**Comment by ishmaster** [comment]
Gracias por la mejora incluida en los productos de vacunación. No obstante, se mantiene la diferencia entre el producto 80 y 81.

- Ejemplo para la comuna de ñuñoa (producto 80)

![image](https://user-images.githubusercontent.com/62425955/121793219-fe95e200-cbca-11eb-9b84-53731dfaf712.png)

Además, se verifica para esta comuna que hay datos de vacunación 0 desde el 2 de junio.

Respecto al producto 81, también persiste la diferencia respecto a lo informado por el DEIS según lo mencionado en mensajes anteriores. De todas formas, llama la atención que haya diferencia entre los datos consolidados y etarios (también expuesto previamente en este issue), por lo que sería bueno tener una explicación para esto.

**Comment by MinCiencia** [comment]
Ahora si, nos parece que @dna33 pudo corregir el problema, en el commit https://github.com/MinCiencia/Datos-COVID19/commit/f01eacb6cfdd6b365e5db5de3cb3c9318a157c3f

¿Puedes por favor revisarlo, @ishmaster y si esta resuelto, cerrar este issue?

**Comment by ishmaster** [comment]
Respecto al producto 80, los datos están cuadrados. Solo queda pendiente lo siguiente:
1) Revisar los datos del producto 81 y comparar con lo informado en Reporte Informe DEIS ya que hay diferencia.

- Ejemplo: vacunación 1º dosis en ñuñoa rango etario 18-39

1) Reporte Informe DEIS

![image](https://user-images.githubusercontent.com/62425955/121817201-f16e0700-cc4d-11eb-9098-eacff48aff66.png)

2) Producto 81

![image](https://user-images.githubusercontent.com/62425955/121817378-26c72480-cc4f-11eb-889f-f99897a44367.png)

2) Aclarar por qué la vacunación etaria (producto 81) no cuadra con la vacunación consolidada (producto 80)

**Comment by ishmaster** [comment]
Estimados:
Luego de resolverse el descuadre en el producto 80, vuelve a presentarse diferencias entre lo informado en Github vs DEIS al 26 de junio de 2021. A modo de ejemplo, se presenta el caso de la región metropolitana.

A) Github
- 1º dosis: 4.866.466
- 2º dosis: 3.948.829

B) Visor territorial

![image](https://user-images.githubusercontent.com/62425955/123527238-bd61ff80-d6ab-11eb-8559-421cd0f0a620.png)

C) Reporte DEIS

![image](https://user-images.githubusercontent.com/62425955/123527255-f4d0ac00-d6ab-11eb-9ba8-5d7776343a6d.png)

Además, sigo a la espera de respuesta de por qué hay diferencias entre los datos consolidados y etarios.

**Comment by MinCiencia** [comment]
Hola, revisamos y todos lo numeros calzan para el producto 81, para RM con el archivo que se cargo ayer el total con 1era Dosis fue 4,900,547 que es el mismo numero encontrado en DEIS y el Visualizador.

Con respecto a comparar producto 81 con producto 80, hay una diferencia que vamos a revisar con el DEIS, pues se encuentra en la base de datos del DEIS de la cual hacemos la extracción.

**Comment by ishmaster** [comment]
No fui claro en el error: la diferencia es entre el producto 80 y lo informado por el DEIS. Al 27 de junio de 2021, estos son los valores para la región metropolitana.

A) Github
- 1º dosis: 4.873.171
- 2º dosis: 3.968.399

B) Visor territorial

![image](https://user-images.githubusercontent.com/62425955/123551546-4e82b600-d740-11eb-8b0c-7d0c8247dcca.png)

C) Reporte DEIS: los datos aún no se actualizan

**Comment by MinCiencia** [comment]
Los datos de DEIS y visión territorial no están actualizados al 27, al parecer. El resumen, para mantener el orden en la conversación: 

1. El producto 80 es consistente con la base de datos con que conectamos al DEIS, ordenada por fecha y comuna 
2. El producto 81 es consistente con la base de datos con que conectamos al DEIS, ordenada por edad y comuna
3. El producto 80 es consistente con el visor territorial (VT), porque también se conecta al DEIS por fecha y comuna 
4. El producto 80/VT es inconsistente con el producto 81 a nivel regional, pero consistente a nivel nacional.

La sospecha del equipo es que se cuenta con información completa respecto de edad (dado que la implementación de la campaña depende de ese dato), mientras no está completa en cuanto al domicilio. Planteamos la pregunta al DEIS, veremos que contestan.

**Comment by ishmaster** [comment]
Respecto al punto 3, entonces cómo se explica la diferencia?

**Comment by MinCiencia** [comment]
Ahi si, corregimos el comentario anterior.

**Comment by ishmaster** [comment]
Ok!
Si a futuro quiero revisar la cantidad de vacunados y sus respectivas dosis, tendría que chequear solamente con los datos del reporte DEIS ([link](https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F9037e283-1278-422c-84c4-16e42a7026c8&sectionIndex=1&sso_guest=true&sas-welcome=false)) ? Porque si es así, al menos hasta ayer los datos de ese informe (considerando ocurrencia de vacunación en vez de residencia) y el visor territorial estaban ok y distintos al producto 80 según lo que revisé.

**Comment by MinCiencia** [comment]
Hoy creo que puedes revisar el 81 o DEIS/VT indistintamente, ahora si quisieras información de la evolución de la campaña por día y por comuna, desde diciembre a la fecha, aún recomendaríamos usar el producto 80, la diferencia es de apenas un 0.56% 

Avisaremos qué dice el DEIS en cuanto nos conteste, probablemente el martes.
