### ISSUE TITLE
Consulta actualización 29 de abril

### ISSUE THREAD

**Issue by Orlando-GIS** [MinCiencia/Datos-COVID19#99]
Hola, me llamo la atención, que no he encontrado actualizaciones de los datos descarga para el día de hoy. ¿paso algo?

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto4
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto13
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto5

Saludos

**Comment by ivanMSC** [comment]
@Orlando-GIS  El minsal no entregó los datos hoy
https://www.gob.cl/coronavirus/cifrasoficiales/

**Comment by javierconcha** [comment]
La verdad es que el Minsal ya actualizó los datos en [https://www.gob.cl/coronavirus/cifrasoficiales/](https://www.gob.cl/coronavirus/cifrasoficiales/). El problema es que el Minsal no ha actualizado la website de donde este repo "scraps" los datos:
[https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/]( https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/). Espero que esto sea solo por hoy, ya que utilizo la misma website para obtener los datos para la website que desarrollé:
[www.elcoronaenchile.com](www.elcoronaenchile.com)

O quizás tendré que crear un scrapper para obtener la data del primer link. Y lo mismo tendrían que hacer los desarrolladores de este repo. Qué creen?

**Comment by ivanMSC** [comment]
@javierconcha No esta el reporte diario por regiones. O por lo menos no lo veo. Donde está? Puedes subir un pantallazo?

**Comment by javierconcha** [comment]
No, no está todavía. No sé que habrá pasado. Quizás este relacionado con lo que anunció el Minsal hoy ([fuente](https://www.emol.com/noticias/Nacional/2020/04/29/984579/Minsal-diferenciacion-positivos.html)):

> "De acuerdo a lo que hemos decidido con el consejo asesor, nosotros incorporamos al día de hoy, dos tipos de personas notificadas como positivas para coronavirus: primero, lo que hemos informado siempre, los pacientes que tienen síntomas y que tienen un examen positivo para la enfermedad como positivos, y en segundo lugar, y esto es lo nuevo, personas que no tienen síntomas y que han estado en contacto estrecho con alguien que sí ha estado enfermo y que tienen un PCR positivo”

**Comment by Orlando-GIS** [comment]
> @Orlando-GIS El minsal no entregó (o al menos aún no) los datos hoy
> https://www.gob.cl/coronavirus/cifrasoficiales/
> 
> Recuerda que el @MinCiencia no produce los datos, solo los disponibiliza.

Vale, esperaremos un poco más, lo raro es que a nivel comunal ya se reportó, porque aparece en @MinCiencia.
https://raw.githubusercontent.com/ivanMSC/COVID19_Chile/master/historial_comunas.csv

**Comment by ivanMSC** [comment]
@Orlando-GIS Si, esos datos los saqué del reporte de cada región.

Puede haber inconsistencias ya que no sabemos si todas las regiones están reportando asintomáticos. Hay que esperar la información centralizada por el minsal.

**Comment by estebaniglesias** [comment]
Nosotros en YachayData  https://github.com/YachayData/COVID-19/ tenemos el mismo problema.
Y es porque nosotros sacamos los datos de:
https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/
Y ahí no los han actualizado. Normalmente los actualizaban a las 12:00
Seguramente es por la polémica!

En nuestro repositorio pueden encontrar tódo el código utilizado para extraer los datos. Mantenemos GitHub Actions opensource para actualizar cada 30 minutos

**Comment by ivanMSC** [comment]
Todos hablan como si fueran una corporación. Que se pasan a caca ajajajaja

**Comment by estebaniglesias** [comment]
Creo que todos hacemos lo que podemos y desde nuestro tiempo libre. No está nada de mal hacernos conocer e intercambiar experiencias e información. Me imagino que buscamos un propósito en común y la idea es echarles pa adelante sin mala onda

**Comment by ivanMSC** [comment]
jajaj tranqui solo me parece cómico que uses el pronombre plural majestuoso (royal we)

**Comment by ivanMSC** [comment]
Aparecieron los datos. Aún no queda claro si son 15135 o 14885.
En https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/ dice una cosa y en https://www.gob.cl/coronavirus/cifrasoficiales/ dice otra cosa.

**Comment by alonsosilvaallende** [comment]
[Acá](https://twitter.com/perez/status/1255694494332325891) el profe [Jorge Perez](https://github.com/jorgeperezrojas) hace un llamado a toda la gente que junta datos (supongo que hay hartos por acá):
> "usaré "total confirmados" como eso, como el **total de confirmados** incluyendo sintomáticos y asintomáticos. Espero que toda la gente que junta datos como yo haga lo mismo."

**Comment by damorend** [comment]
El mismo informe diario del 29 tiene dos cifras distintas de casos totales, en la primera y la última página.

**Comment by javierconcha** [comment]
Y el Minsal volvió a cambiar el orden de la tabla!

**Comment by MinCiencia** [comment]
Creo que la situación se ha estabilizado. Estamos atentos. Gracias por reportar.
