### ISSUE TITLE
serie_fallecidos_comuna.csv datos repetidos

### ISSUE THREAD

**Issue by EduardoB-Chile** [MinCiencia/Datos-COVID19#990]
Estimados los datos del producto 61 están repetidos los datos del 28.05.2021, en esa fecha y en el 31.05.2021

**Comment by MinCiencia** [comment]
Tienes razón, corregiremos.

**Comment by MinCiencia** [comment]
Corregido https://github.com/MinCiencia/Datos-COVID19/commit/89b3e247a118536b5758cb535f04cff48da154cd
