### ISSUE TITLE
Vacunados con Cansino

### ISSUE THREAD

**Issue by CeciliaBustos** [MinCiencia/Datos-COVID19#995]
Hola, dónde puedo encontrar el número de vacunados con Cansino, por edad? Gracias.

**Comment by MinCiencia** [comment]
Es un producto pendiente de desarrollo, pero la información se tiene. Tenemos que incluir dentro de este código https://github.com/MinCiencia/Datos-COVID19/blob/master/src/vacunacion.py el correcto procesamiento de los archivos en input https://github.com/MinCiencia/Datos-COVID19/tree/master/input/Vacunacion, para producir el resultado en este formato: https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto81

**Comment by CeciliaBustos** [comment]
ok, muchas gracias!!
