### ISSUE TITLE
falta actualización producto 39

### ISSUE THREAD

**Issue by dafernandez75** [MinCiencia/Datos-COVID19#998]
buenas noches,

Aún no se actualiza Producto 39, según Informe EPI Nº127 ya publicado en el día de hoy miércoles 09/06/2021.

Saludos,
![Captura de pantalla 2021-06-09 220531](https://user-images.githubusercontent.com/69001461/121453350-09ecd180-c96f-11eb-86de-3dd8177e4631.png)

**Comment by MinCiencia** [comment]
cab29eb50cdc8fc2294bbed4177f650798250df2
